### ISSUE TITLE
Use cover as raw binary screen buffer instead GIF

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1001]
This can prevent wrong (animated, invalid width/height) GIFs embedding.
Also, we could add the Cover image editor to TIC.
Current `CHUNK_COVER` will be marked as deprecated and automatically converted to the new cover type on cart loading.

**Comment by StinkerB06** [comment]
It is possible to have (16×136)+16 = 2192 colors onscreen by pushing SCN and OVR to their max limits. Maybe allow such high color depth supported in your raw format so such cover images don't appear downgraded.

**Comment by MarcusPeixe** [comment]
> This can prevent wrong (animated, invalid width/height) GIFs embedding.
:(
> Also, we could add the Cover image editor to TIC.
:)

**Comment by nesbox** [comment]
Main f6bd43f changes:
- added a new chunk `CHUNK_SCREEN` to every bank
- `tic_screen` is a `240 x 136 x 4bpp` raw buffer, you can copy it to `VRAM` using `tic_api_sync(...)`
- all the import/export commands use `.png` format now
