### ISSUE TITLE
Saving cart with 65536 chars of code corrupts cart

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#1002]
This is because the chunk size in *.tic files are being represented with a 16-bit unsigned integer, which ranges from 0 to 6553**5** (0xFFFF). 6553**6** (0x10000) doesn't fit in it though, wrapping around to 0. TIC-80 does inject the 65536 bytes of code into the cart though with no 16-bit wraparound, so the code text will start to be interpreted as *.tic file data and load garbage.

A workaround is to have the unused `TEMP` byte be used as an extra 8 bits of chunk size, so that we have a 24-bit range of 0 to 16777215. 65536 does fit into this number, so it absolutely works as expected. I think you used a 24-bit size before but you eventually changed it and broke a thing.

**Comment by asiekierka** [comment]
Alternatively, TIC_CODE_SIZE could simply be set to `(64 * 1024) - 1`, or 65535 bytes. Since carts actually running into the limit are all corrupted, there should be none actually relying on it being 65536 at this time, I think?
