### ISSUE TITLE
What's the difference between Tic-80 and Pico-8?

### ISSUE THREAD

**Issue by sfmemz** [nesbox/TIC-80#1009]
I think they are both great but just don't know the most of difference
The only difference that I know:
Pico-8 is 4:3 and Tic-80 is 16:9

**Comment by StinkerB06** [comment]
Actually, PICO-8 is 1:1 and TIC-80 is 30:17.

**Comment by nesbox** [comment]
full TIC80 resolution is 256*144 (with border), so it's 16:9

**Comment by RobLoach** [comment]
Quality | TIC-80 | PICO-8
--- | --- | ---
Resolution | 128x128 | 240x136
License | Open Source MIT | Proprietary
Community Size | Small-ish | Large
Language | Lua, Moonscript, JavaScript, Fennel, Wren, Squirrel | Lua
Platform | Windows, macOS, Linux, Android, RPi, libretro, Web | Windows, macOS, Linux, Raspbery Pi, Web

**Comment by finalpatch** [comment]
I think TIC-80 doesn't limit the number of instructions per tic,  so in theory you could write more complex stuff in TIC-80.
