### ISSUE TITLE
Change the build link in the readme

### ISSUE THREAD

**Issue by fantomx11** [nesbox/TIC-80#1014]
Currently it points to the releases here on Github. I did not know, until perusing the itch.io community that there is another releases page with more current downloads at https://builds.tic.computer/master.

**Comment by nesbox** [comment]
https://builds.tic.computer isn't Releases page, it's a page with nigthly builds
Releases page is still here https://github.com/nesbox/TIC-80/releases

**Comment by nesbox** [comment]
You can download the latest builds on the Github Actions page https://github.com/nesbox/TIC-80/actions
