### ISSUE TITLE
Is there a way to build text only games?

### ISSUE THREAD

**Issue by clsource** [nesbox/TIC-80#1015]
Hello I would like to make games using simple text input.

```lua
print('Hello, what is your name? ')
local name = read()
print('Nice to meet you ' ..name)
```
I believe this may be possible using a `while true` loop and `key()` functions. saving the input and returning it when `enter` is pressed. But a built in solution can be handy.

Specially if you want to port early games such as those seen in

BASIC Computer Games
Edited by David H. Ahl, published 1978

https://www.atariarchives.org/basicgames/

Thanks :)

**Comment by RobLoach** [comment]
You could put together a small in-game console UI in TIC-80, wrapped by an API similar to what you outlined above.

**Comment by clsource** [comment]
I tried this code

```lua
function read()
	local text = ""
	local shouldRead = true
	while(shouldRead) do
		if(key(1)) then
			text = text .."A"
		end
		
                -- enter
		if(key(50)) then
			shouldRead = false
		end
	end
	
	return text
end

local name = ""
cls(2)
print("Hello, what is your name?")
name = read()
print("Hello " ..name)

function TIC()
-- empty
end
```

but somehow it hangs :C

**Comment by RobLoach** [comment]
It hangs because you're in a while loop that never ends. At that stage, `key()` will always return `false`.

**Comment by clsource** [comment]
I made something that works. But this seems that is not trivial to do.

```lua


readline = ""
function read()
	
		if(keyp(1)) then
			readline = readline .."A"
		end
		
		if(keyp(2)) then
			readline = readline .."B"
		end
		
		if(keyp(3)) then
			readline = readline .."C"
		end
		
		return readline
end

out = ""
display = false

function TIC()

	cls(2)
	print("Hello, what is your name?")
	name = read()
	out = name
	
	if(keyp(50) or display) then
		out = "Hello " ..out
		display = true
	end
	
	print(out, 0, 8)
	
end

```

**Comment by RobLoach** [comment]
You're getting there. You could have two GUI components to accomplish it...

1. Text input box
2. Log window

For text input, draw a box, and a `input` string. Have key input add a string to the `input` string. Act on the ENTER key, and add the input to the log window.

For the log window, print a string array from the end of the array to the beginning.

**Comment by clsource** [comment]
ok I will try those ideas. thanks :).

imho this kind of behaviour could be included. Many games could benefit of having a keyboard input without re implementing it each time.
👍

**Comment by clsource** [comment]
Here is a sort of complete example

```lua



input = {
	buffer = "",
	rows = {}
}

function input:reset()
		input.buffer = ""
end
	
function input:lowercase()
	if(keyp(1)) then
		input.buffer = input.buffer .."a"
	end			
	
	return input.buffer
end

function input:uppercase()
	if(keyp(1)) then
		input.buffer = input.buffer .."A"
	end
	
	return input.buffer
end

function input:read()

	local buffer = input.buffer

	if(key(64) or key(62)) then
		input:uppercase()
	else
		input:lowercase()
	end
	
	if(keyp(50)) then
	 table.insert(input.rows,input.buffer)
		input:reset()
	end
	
	local out = ""
	for index, value in ipairs(input.rows) do
		out = out ..value .."\n"
	end
	
	return out
end

function TIC()
 cls(2)
	print(input.buffer)
	print(input:read(), 0, 16)
end
```

**Comment by RobLoach** [comment]
Great work! Added some `rectb()` to help add to the GUI :wink: 

![Screenshot at 2020-03-17 12-37-41](https://user-images.githubusercontent.com/25086/76879118-2a9da880-684c-11ea-8a35-0421d1b936e1.png)

**Comment by clsource** [comment]
added the code to the wiki :)

https://github.com/nesbox/TIC-80/wiki/Code-examples-and-snippets#text-only-game

**Comment by joshgoebel** [comment]
This could be vastly simplified with `string.byte` and `string.char` removing the need to hard-code things like a-z to integer, etc.
