### ISSUE TITLE
implement Effects column in the Music Editor

### ISSUE THREAD

**Issue by babatunde3** [nesbox/TIC-80#1016]
Add note cut command (Nxx)
Add tremor (Ixx)
Add tremolo (Rxx)
Add pattern loop (Zxx)
Add position jump (Qxx)
Add wave switching (Wxx)
Add fade in (Hxx)
Add set volume (Oxx)
Add set panning L/R (Yxx)
Add drop (pitching down) effect (Kxx)
Add fade out (Yxx)

**Comment by StinkerB06** [comment]
In 0.80-dev there are some effect commands implemented:
http://builds.tic80.com/master/2020.03.01

List of effect commands:
https://github.com/nesbox/TIC-80/issues/261#issuecomment-566043505

**Comment by nesbox** [comment]
yes, the effects column is already implemented in .80
