### ISSUE TITLE
Mirror/rotate selection

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/TIC-80#103]
It should be able to mirror/rotate only for the selected part, but will rotate the whole part instead.

**Comment by nesbox** [comment]
will do

**Comment by AnastasiaDunbar** [comment]
My question was a bit ambiguous for myself and doesn't even mention about the sprite editor, sorry about closing and reopening. Here's a GIF that explains it:
![gif](https://user-images.githubusercontent.com/11806048/32212644-d360d34e-be52-11e7-9a45-0bb73cdbd137.gif)

**Comment by noxarivis** [comment]
i dont think its that important, its more a "nice to have"

its a tool to create retrogames at least

**Comment by josefnpat** [comment]
How would we rotate a selection that is not square? We could rotate and then scale, but that sounds like a bad solution.

**Comment by AnastasiaDunbar** [comment]
But you can't make an irregular selection, that's not necessary because you could just export sprites then open it in a graphics software and import it back but for something small like this might be useful in some cases.

**Comment by frenetic** [comment]
Just added a pull request to solve flipping horizontally and vertically.
It also enables pressing the `trash` button to delete a selection.

The problem now resides on `rotate`.
We need to discuss proper behavior for the following scenario:
![rotate trouble](https://user-images.githubusercontent.com/122976/34542844-14c5a354-f0bd-11e7-870a-bdfe933ea009.gif)

**Comment by AnastasiaDunbar** [comment]
I just discovered a glitch:
![glitch](https://user-images.githubusercontent.com/11806048/34545569-d584dde2-f128-11e7-9edd-31d437ceb1c7.gif)

There could be a way to check if the rotated rectangle is out of boundaries?

**Comment by AnastasiaDunbar** [comment]
Here's a demo I made in TIC-80:
```javascript
// title:  rotation
// author: Anastasia Dunbar
// desc:   hold z and use arrow keys to resize selection, press x to rotate.
// script: js
var region={
	w:20,h:30
},
selection={
	x:0,y:0,w:1,h:1
};
function TIC(){
	if(btn(4)){
		if(btn(0)){selection.h=Math.max(selection.h-1,1);}
		if(btn(1)){selection.h=Math.min(selection.h+1,region.h-selection.y);}
		if(btn(2)){selection.w=Math.max(selection.w-1,1);}
		if(btn(3)){selection.w=Math.min(selection.w+1,region.w-selection.x);}
	}else{
		if(btn(0)){selection.y=Math.max(selection.y-1,0);}
		if(btn(1)){selection.y=Math.min(selection.y+1,region.h-selection.h);}
		if(btn(2)){selection.x=Math.max(selection.x-1,0);}
		if(btn(3)){selection.x=Math.min(selection.x+1,region.w-selection.w);}
	}
	var flash=false;
	if(btnp(5)){
		var w=selection.h,h=selection.w,x=Math.min(selection.x,region.w-w),y=Math.min(selection.y,region.h-h);
		if(!(x<0||y<0)){
			//Can rotate.
			selection.x=x;
			selection.y=y;
			selection.w=w;
			selection.h=h;
		}else{
			//Cannot rotate, will overlap outside.
			flash=true;
		}
	}
	cls(flash?14:0);
	rectb(0,0,region.w,region.h,1);
	rectb(selection.x,selection.y,selection.w,selection.h,15);
}
```

**Comment by frenetic** [comment]
I think it is ok to do it this way. Move the selection if it crashes with the walls.

**Comment by frenetic** [comment]
@AnastasiaDunbar I tried to replicate this bug, but I was unsuccessful. Tried on `0.50.1` and building `master` for `linux`.
Do you mind opening a new issue for this bug, so we can further discuss it without polluting this feature request discussion?

**Comment by AnastasiaDunbar** [comment]
It happened on 0.60.0 dev.

**Comment by frenetic** [comment]
Found a good solution to the rotation situation.
![rotate solution](https://user-images.githubusercontent.com/122976/34623054-64acea40-f22e-11e7-8bfe-c021b871b796.gif)

Rotate at the center of the selection.
This way, it behaves similar to other editing tools.
Also, if it goes out of bounds, just adjust it a little bit to keep it inside the canvas.

I will finish the rotation algorithm later or tomorrow... When I have some more free time.

**Comment by nesbox** [comment]
done here 6b092a5 by @frenetic
