### ISSUE TITLE
Wiki page on ram unclear

### ISSUE THREAD

**Issue by lolbinarycat** [nesbox/TIC-80#1032]
I don't know if this is the right place to put this, but I can't think of a better one.
The wiki page on [RAM](https://github.com/nesbox/TIC-80/wiki/RAM) often uses an ellipsis instead of having a description, seemingly with varying meaning. 
For example, the `03FFC` range. What does it do? I can't seem to find info on it anywhere, and the only thing about it on the page is this:
`| 03FFC | ...               | 4     |`
which dosn't tell us anything.
It dosn't seem to just be unused, because when I check it in tic-80, it has a value.
Anyone have any insight into this?

**Comment by nesbox** [comment]
This means that the area isn't used at the moment but reserved for future use.
For example `03FFC` does nothing https://github.com/nesbox/TIC-80/blob/d054b8578455db213043b2c40e294b6112d196e5/src/tic.h#L459
