### ISSUE TITLE
ls/dir fails to sort properly

### ISSUE THREAD

**Issue by lolbinarycat** [nesbox/TIC-80#1033]
![2020-03-23-1584977672_screenshot_1366x768](https://user-images.githubusercontent.com/19915050/77333889-7348dc00-6cfa-11ea-95ad-f116e877abc1.jpg)
As you can see, the sorting is all over the place, with cart.tic right in the middle. There seems to be no logic to how it is sorted.

**Comment by sssilver** [comment]
Would alphabetic sorting be better? I'd be happy to submit a PR

**Comment by nesbox** [comment]
yes, alphabetic sorting is ok
thank you

**Comment by nesbox** [comment]
Fixed here 42a4850 0b119e9
