### ISSUE TITLE
Bug: TIC-80 overwrites saved cart with the Hello World starter.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [nesbox/TIC-80#1034]
Demo:

![demo](https://user-images.githubusercontent.com/19352442/77359859-aa32e800-6d22-11ea-8c3a-f271eb6b11b9.gif)

Version: 0.70.5
OS: Windows 10

**Comment by StinkerB06** [comment]
This isn't a bug, you just forgot to `load test.tic`.

**Comment by AleksandrHovhannisyan** [comment]
Phew, that worked!

I was afraid I'd lost all my work from earlier today :)
