### ISSUE TITLE
HTML export lacks CSS `image-rendering:pixelated` on canvas

### ISSUE THREAD

**Issue by sol-foxie** [nesbox/TIC-80#1036]
tested this in chrome, but basically when exporting an html cartridge, the canvas is not crisp, i.e. the browser applies the standard scaling algorithm. I applied the `image-rendering: pixelated` style and the image became considerably sharper. I had no luck getting this to work in safari, however, and I also tried `crisp-edges`, but didn't get any positive response in my limited testing

still, I see no harm in hedging bets by applying this property. however, my view is limited, as I am not primarily a webdev. I figured I'd ask here if there is a reason that style is not currently applied? or is it something we should go ahead and add?

**Comment by stefandevai** [comment]
Hi! I think it's a good idea to enforce the rendering as pixelated :) We can add that and update the generated HTML file with the improvements from #972.

**Comment by asiekierka** [comment]
Shouldn't this one be closed, as it was resolved?

**Comment by nesbox** [comment]
yes, fixed with #972
