### ISSUE TITLE
export native exporting TIC-80 itself

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#1042]
When using command ``export native`` TIC-80 also exporting itself. It is possible, to close the cart in exported file and edit the code, sprites or create new cart.

**Comment by MineRobber9000** [comment]
This is not a bug, this is an intended feature.

**Comment by BuoYancYdabl** [comment]
> This is not a bug, this is an intended feature.

This "feature" exports the PRO version as well, so users wont buy or build it by themselfs.

**Comment by nesbox** [comment]
Duplicate of #169
