### ISSUE TITLE
Unknown method dofile in last dev builds

### ISSUE THREAD

**Issue by mrtraveller** [nesbox/TIC-80#1046]
dofile() is returning error "unknown method dofile" in the last dev builds

**Comment by RobLoach** [comment]
It was removed as it caused more confusion then helped people. If you're looking to load your local filesystem, use something else....

I use....

tic80 cart.tic -code mycode.lua

**Comment by nesbox** [comment]
Or you could save cart in text format, like `save cart.lua`, locate the cart with `folder` command and edit it in any text editor.

**Comment by mrtraveller** [comment]
> 
> 
> Or you could save cart in text format, like `save cart.lua`, locate the cart with `folder` command and edit it in any text editor.

Hey, this is really... better!
