### ISSUE TITLE
Using font() in JS causes RangeError

### ISSUE THREAD

**Issue by kimnorth** [nesbox/TIC-80#1052]
Hi,

I'm attempting to use the font() method for the first time in a game written in JS. I'm getting an error when I try to run the following code (adapted from the docs):

`font('A',20,20,2,9,9,true,3)`

The error being logged out into the console is: 

`RangeError: Invalid Stack Index 8`

<img width="1245" alt="Screenshot 2020-04-17 at 23 14 07" src="https://user-images.githubusercontent.com/25009414/79618132-25f53a00-8101-11ea-9910-6dd15b830f42.png">

There is definitely a sprite at the corresponding ASCII position for character "A" and when I run the same code as lua, it prints it out correctly to the screen. So it looks like an issue with the implementation in JS.

I am using v0.70.6

Thanks

**Comment by RobLoach** [comment]
Could you provide a focused example?

**Comment by nesbox** [comment]
reproduced, but don't understand what causes the problem...

**Comment by kimnorth** [comment]
This is the js version of the file I'm trying to run:

```
// title:  Font Demo
// author: PaulR
// desc:   Shows the working of font()
// script: js
function TIC(){
	cls()	
	font('A',20,20,2,9,9,true,3)
}
```

And this is the lua version of that script:

```
-- title:  Font Demo
-- author: PaulR
-- desc:   Shows the working of font()
-- script: lua
function TIC()
	cls()	
	font('A',20,20,2,9,9,true,3)
end
```

The lua version correctly prints out the sprite at that location in the sheet:

<img width="1280" alt="Screenshot 2020-04-18 at 14 23 04" src="https://user-images.githubusercontent.com/25009414/79638911-1ff26e00-8180-11ea-9ef6-366ed0724e24.png">

**Comment by kimnorth** [comment]
Amazing, thanks all!
