### ISSUE TITLE
game display of uploaded HTML game to itch.io is clipped in viewport in version .80

### ISSUE THREAD

**Issue by ergodicbreak** [nesbox/TIC-80#1056]
hello, this is an issue with a recent build, tic80-MinGW-w64-2020-04-01, but I thought I'd report it here anyway. When I export as HTML and upload to itch.io, the game display looks clipped in the itch.io viewport, even if I adjust the itch.io viewport embed dimensions to something larger. You can see an example here, [https://ergodicbreak.itch.io/xenoamob](https://ergodicbreak.itch.io/xenoamob). 

If I serve the HTML locally, the game seems to display OK, so perhaps this is a problem with itch.io, but I couldn't find any relevant information after searching. Thanks for any advice and the great TIC-80.

**Comment by nesbox** [comment]
Hi, TIC80 has 4x UI scale by default, try to enter `1024x576 (256*4 x 144*4)` values on the itchio page.

**Comment by ergodicbreak** [comment]
Thanks, that worked much better!
