### ISSUE TITLE
(0.80.1129-dev) Letters/numbers/symbols on virtual keyboard don't show up

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#1060]
Makes it almost impossible to type unless you know which keys do what.
![Screenshot_20200427-092944](https://user-images.githubusercontent.com/30059831/80397549-2b722300-886b-11ea-91d8-87300d4767a6.png)

**Comment by BraininaBowl** [comment]
Can confirm, problem present in every Android built since 1130-dev.
For me it happens on a OnePlus 6 running OxygenOS 10.3.4, in case that matters.

**Comment by nesbox** [comment]
TIC virtual kbd was removed in .80, but we are going to restore it in .90
