### ISSUE TITLE
Running Problems

### ISSUE THREAD

**Issue by AJtophat** [nesbox/TIC-80#1062]
Hey, How are you guys doing, so, im new to tic-80, i´ve learned some basics of it off some youtube videos, and now im trying to work onto a project solo, the project being me trying to make a plataform game, i got some code from the tutorials, modified a litle bit and its working! now im trying to make my character _run,_ like in the super mario games, if you hold a button, mario runs, if you 
don´t, mario walks, here´s some code of mine and my plan to do it.

```
`--` `title:` plataform test.tic
`--` `author:` `AJ`
-- desc: simple plataformer game test
-- script: lua
 
`modes={`
  `move=0` --0= walk 1= run
  }
		
function solid(x,y)
    return solids[mget((x)//8,(y)//8)]
end

function init()
    solids={[1]=true,[3]=true}
    p={
    x=120,
    y=68,
    vx=0, --Velocity X
    vy=0, --Velocity Y
}
end

init()
function TIC()

    if btn(2) then p.vx=-1
        elseif btn(3) then p.vx=1
        elseif btn(2) and modes.move=1 then p.vx
        elseif btn(3) and modes.move=1 then p.vx=2
        else p.vx=0
    end	
				
	if btn(1) then modes.move=1
	else modes.move=0
				
   end			
				
       if p.vy==0 and btn(4) then p.vy=-2.5 end
       if p.vy==0 and btn(5) then p.vy=-4.0 end
				
if solid(p.x+p.vx,p.y+p.vy) or solid(p.x+7+p.vx,p.y+p.vy) or solid(p.x+p.vx,p.y+7+p.vy) or solid(p.x+7+p.vx,p.y+7+p.vy) then
    p.vx=0
end

if solid(p.x+p.vx,p.y+8+p.vy) or solid(p.x+7+p.vx,p.y+8+p.vy) then
    p.vy=0
else
    p.vy=p.vy+0.2
end

    p.x=p.x+p.vx
    p.y=p.y+p.vy
    
				cls()
    map()
    rect(p.x,p.y,8,8,15)
    
end
```
` 
My plan was "modes", every action of an object that can have different types will have different modes shown as numbers, like this:

`modes={
move=0,
sword=1
sheild=0
}`

So the first i programmed was a "move" mode that when in 0 the character walked, and in 1 the character runned, like in mario i made the run button another button, when i booted it up, it didin´t
work, showing an error saying 

"[string "--plataform test.tic...:29: ´then´ expected near `=`]"

There is no lone = on line 29, i checked it. so i thought you guys could help!
Thanks if somebody can find something i didin´t spot before.
![i](https://user-images.githubusercontent.com/64497072/80531876-acb3dd80-8971-11ea-8bed-653bdb0fd0e2.jpg)

**Comment by RobLoach** [comment]
```

        elseif btn(3) then p.vx=1
        elseif btn(2) and modes.move=1 then p.vx
        elseif btn(3) and modes.move=1 then p.vx=2
```

You're missing something after `p.vx` on `btn(2)`

**Comment by nesbox** [comment]
@AJtophat I think you're missing `==`
try something like
``` lua
if btn(2) then p.vx=-1
elseif btn(3) then p.vx=1
elseif btn(2) and modes.move==1 then p.vx=1
elseif btn(3) and modes.move==1 then p.vx=2
else p.vx=0
end	
```
