### ISSUE TITLE
Lua: Compound Assignment Operators

### ISSUE THREAD

**Issue by RobLoach** [nesbox/TIC-80#1065]
Thoughts on adding the Compound Assignment Operators to Lua from the [Lua Power Patches](http://lua-users.org/wiki/LuaPowerPatches)?

```
position += 2
```

**Comment by nesbox** [comment]
Surely it's great, but I'm afraid how to update to future Lua releases, will this patch be actual?
Or maybe better to wait to an official Compound Assignment Operators support :)

**Comment by Anrock** [comment]
@RobLoach try moonsript. It translates to lua and has a really nice syntax with compound operators

**Comment by RobLoach** [comment]
Love MoonScript 😉 .... Was using native Lua on a little project. Porting some pico8 component and found the += .

I doubt they will bring compound assignment into mainline Lua. They've also been pretty clear about breaking compatibility in 5.4. Unsure how dramatic it will be, so we will have to do some testing when/if we move to 5.4.

**Comment by RobLoach** [comment]
Going to close this for now. Being as close to Lua native as posssible is likely best. Thanks!
