### ISSUE TITLE
Exporting into .tic format

### ISSUE THREAD

**Issue by TesterSzymoon** [nesbox/TIC-80#1073]
Hello, I want to export my cart into tic.computer site and upload it, but I don't know how to export in .tic format. I have TIC-80 version 0.70.6. Can someone help?

**Comment by nesbox** [comment]
Hi,
First of all, you have to assign cover to the cartridge, run your game and press `F7`, you will see that cover assigned.
Save your cart using `save game.tic` command and `get game.tic` to download cart.
