### ISSUE TITLE
Clamped 1,2[,3?] bits palette mode

### ISSUE THREAD

**Issue by ddelemeny** [nesbox/TIC-80#1074]
### Proposed feature
I think it would be nice to be able to draw sprites using a lower bit depth palette.

The idea would be to pass a `bit_depth` parameter to sprite drawing functions that would clamp the palette and read `bit_depth` bits per pixel from the sprite memory (with appropriately scaled coordinates)

The spirit of this proposal is really a low-level memory trick, which is IMHO completely in the style of a fantasy computer.

### Use cases
- This would allow a better use of the sprite memory for low-color graphics such as fonts, ui elements, textures, etc.
- Games with 4color sprites would have a double-sized spritesheet
- The user can use the `PALETTE_MAP` section of the memory to locally adapt the palette to their needs. 
- This could also be leveraged in the config cartridge where most sprites are actually low-palette

### What to modify (non exhaustive)
- add bit_depth mode to `spr`, possibly `map`, `remap` and `textri`
- add bit_depth mode switch to the sprite[/map] editor
- `poke1`, `poke2`, `poke3` ? or general `poke` with bitmask

### Possible caveats
- the sprite memory segment size isn't a multiple of 3, therefore a 3bit mode could leave a few bits unused
- `map` (and `textri` from map) would be harder to adapt to mixed bit_depth data. `remap` can help

### Possible improvements
- #952 (true coordinates blit function) would be a good companion to this feature
- the sprite editor might need some additional masking feature to ease the manipulation of a spritesheet with mixed bit_depth data.

What do you think ?

**Comment by ddelemeny** [comment]
So, I've been trying to prototype this as an exercise...
https://github.com/ddelemeny/TIC-80/commit/303713a39a33d4fc77d32aea1cfabe028034ccf8 implements a (very unpolished) `sspr` function with a bit_depth parameter.

Key takeaways:
- the spritesheet's pixel layout in ram could make it difficult to implement a 3bits palette mode. 2bits and 1bit is easy.
- implementation of true-coordinates `sspr` is pretty straightforward, although my version of it does not implement arbitrary bitmap scaling

Here's the result : 

```lua
x=72
y=24

function TIC()
        cls(13)
        -- sspr(sx, sy, sw, sh, x, y, colorkey, scale, flip, rotate, bit_depth)
        sspr(16,0,32,16,x,y,14,3,0,0,2)
        print("HELLO WORLD!",84,84)
end

-- <TILES>
-- 001:eccccccccc888888caaaaaaaca888888cacccccccacc0ccccacc0ccccacc0ccc
-- 002:ccccceee8888cceeaaaa0cee888a0ceeccca0ccc0cca0c0c0cca0c0c0cca0c0c
-- 003:eccccccccc888888caaaaaaaca888888cacccccccacccccccacc0ccccacc0ccc
-- 004:ccccceee8888cceeaaaa0cee888a0ceeccca0cccccca0c0c0cca0c0c0cca0c0c
-- 017:cacccccccaaaaaaacaaacaaacaaaaccccaaaaaaac8888888cc000cccecccccec
-- 018:ccca00ccaaaa0ccecaaa0ceeaaaa0ceeaaaa0cee8888ccee000cceeecccceeee
-- 019:cacccccccaaaaaaacaaacaaacaaaaccccaaaaaaac8888888cc000cccecccccec
-- 020:ccca00ccaaaa0ccecaaa0ceeaaaa0ceeaaaa0cee8888ccee000cceeecccceeee
-- </TILES>

-- <PALETTE>
-- 000:1a1c2c5d275db13e53ef7d57ffcd75a7f07038b76425717929366f3b5dc941a6f673eff7f4f4f494b0c2566c86333c57
-- </PALETTE>
```
![tic_sspr_bit_depth](https://user-images.githubusercontent.com/1690574/81012505-f319a880-8e59-11ea-9144-5d14cee99efb.gif)

**Comment by RobLoach** [comment]
Judging by that image, I think the caption should instead read "PLEASE KILL ME!"

**Comment by StinkerB06** [comment]
I'd prefer replacing the `scale` parameter with `w` and `h`:
`sspr(sx, sy, sw, sh, x, y, colorkey, w, h, flip, rotate, bit_depth)`
This would allow the sprite to be scaled freely both horizontally and vertically (with float values allowed, which is a sole purpose of `sspr()` in PICO-8).

**Comment by ddelemeny** [comment]
@StinkerB06 I think it's more relevant to #952, but I was going for it anyway : https://github.com/ddelemeny/TIC-80/commit/503fcb9f7572da0f76a475427041ebd29b0e27d0
I preferred keeping `dx,dy,dw,dh` together in the function signature (as pico-8 does) to keep some coherence in surface coordinates definition between source and dest, but I'm open to counter-arguments on this.

**Comment by ddelemeny** [comment]
https://github.com/ddelemeny/TIC-80/commit/7d82ac9a581667f5b30b9e82e4c7361db920db04 implements `drawSurface` an optimized version of this _almighty_ drawing function (true coordinates, arbitrary bitmap scaling, bit-depth aware... it just lacks a texture-repeat mode at this point) that could serve as a drawing backend for the other drawing functions of the api (spr, map).

But there's a catch.
The current drawing backend, drawTile, is tightly optimized. I've tried to re-implement the same optimizations except the following :
1. in drawTile, the tile buffer address is known in advance, there's no need to recompute from source coordinates on each drawn pixel.
2. in drawTile, the integer scale parameter allows fast drawing of block of pixels without having to interpolate source coordinates on each drawn pixel.

This means drawSurface is quite fast, but not as fast as drawTile yet.
Using https://tic.computer/play?cart=631 as a naive benchmark on my laptop, I managed to obtain 85% of the performance of drawTile at 1:1 scale (drawSurface can draw 85% of the sprites that drawTile can draw at 30fps), and I lose 40 to 50% of drawTile's performance at scale 3:1.

Fast, but not fast enough. I need to find a way to match the fast paths of drawTile.
Any ideas welcome.

**Comment by ddelemeny** [comment]
Current progress of the bit_depth feature experiment _(\<placeholder for the commit ref\>):_

Here's the editor working in 2bits mode:
![2bit-editor-screen](https://user-images.githubusercontent.com/1690574/81277496-caa9ce00-9054-11ea-92aa-beafad1b99fa.gif)

And here's a bit_depth enabled `spr` drawing the same animated sprite :
- center is 4bits per pixel data
- left is 2 bits per pixel
- right is 2 bits per pixel with palette remapping

![2bit-sprite-example](https://user-images.githubusercontent.com/1690574/81277499-caa9ce00-9054-11ea-9c74-ab9e2865a6b7.gif)

Now I need to find a good UI to handle that mode in the sprite editor. And do a bit of code cleanup.

**Comment by ddelemeny** [comment]
Here's the current state of the sprite editor at https://github.com/ddelemeny/TIC-80/commit/65930f31633f9101a3ded28368ed3b7166e538a2

![2bit-editor-screen-ui](https://user-images.githubusercontent.com/1690574/81473606-deddfe80-91ff-11ea-963b-b8a8c0259996.gif)

**Comment by ddelemeny** [comment]
Some remaining stuff to resolve :
- Can `bit_depth` be enabled on more functions (`map`, `textri`, `font`) ?
- Can `bit_depth` be enabled in the map editor ? Should it ?
- Can `config` use a low-palette spritesheet ? Should it ?
- `SPRITE FLAGS` memory segment is limited. What to do of flags for extra sprite indices in low-palette modes ?
- `MOUSE CURSOR` could benefit from low palette, but the interpretation of value in is quite tied to the 4bits mode, is there something doable with this ?

**Comment by RobLoach** [comment]
Nice work on the UI!!!!

**Comment by ddelemeny** [comment]
More UI experiments at https://github.com/ddelemeny/TIC-80/commit/7f1cdb5d48a97dcc812a0de89c666f24f8aa15a5 , some prompted by @nesbox's suggestions 

- put bitmode selector under the palette
- swap bank and page tabs positions
- reduce number of flags per sprite on lower bitmodes
- increase palette cell size instead of shrinking the palette
- cue extended spritesheet with dashed borders

![ezgif com-optimize](https://user-images.githubusercontent.com/1690574/81487606-0a440600-925f-11ea-80d1-046d407a2d44.gif)

**Comment by ddelemeny** [comment]
Progress update:
- renamed bit_depth to bpp
- bpp is now activated by poking a value in vram. Full register specification in progress.
- reverted changes to api to avoid overloading it
- bpp enabled `fset`/`fget` 
- bpp enabled `font` (see demo below)

![ezgif com-optimize(5)](https://user-images.githubusercontent.com/1690574/81588425-c6651400-93b8-11ea-8b29-c3f7994bfd60.gif)
