### ISSUE TITLE
Paren matching in code editor

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#1075]
When I'm using TIC without an external editor, it's great, but one difficulty I have is with matching parentheses up. In other editors sometimes when you put the cursor on a paren, it colors the matching paren on the other side in a way that helps you know which correspond to which.

Do you think this would be a good addition in the TIC code editor? I could give it a shot if so.

**Comment by nesbox** [comment]
I think it sounds good, pls give it a shot if you have time.
Thank you.

**Comment by technomancy** [comment]
I made a lot of progress on this; I have an initial implementation here: https://github.com/technomancy/TIC-80/commit/f383b45591ccd6aac6401515b67561011d570ca4

It works in the case of having nested delimiters in between the outer ones; for instance `hello(1, 2, abc[a()], {})` will match the outer parens, and the ones on the inside won't interfere.

However, I got stuck on two problems:
* If the cursor is inside a string or comment, it shouldn't even attempt to find a match.
* If it is looking for a closing delimiter, it should skip matches which are inside a string or comment.

If I had a function like `isInsideString(Code* code, char* position)` and `isInComment(Code* code, char* position)` then this would be easy, but I could find nothing in `code.c` that knows about strings or comments other than the `parseCode` function, which does not seem reusable. Do you have any suggestion for how to proceed?

I am very inexperienced at writing C, so please let me know if you have any other suggestions for making the code better too.

**Comment by technomancy** [comment]
Also, unrelated to this change, I would like to get some changes to Fennel in before the 0.80.0 release goes out; do you think that will be soon or do we have a bit more time to get that ready?

**Comment by nesbox** [comment]
> If I had a function like isInsideString(Code* code, char* position) and isInComment(Code* code, char* position) then this would be easy, but I could find nothing in code.c that knows about strings or comments other than the parseCode function, which does not seem reusable. Do you have any suggestion for how to proceed?

I think we could use `code->colorBuffer` to detect string or comment, but it has to be rewritten a bit. I'm going to fill the buffer with keyword types (number/string/api/...) instead of colors and it will be easier to detect and skip these parts while you're matching parentheses.

**Comment by nesbox** [comment]
> Also, unrelated to this change, I would like to get some changes to Fennel in before the 0.80.0 release goes out; do you think that will be soon or do we have a bit more time to get that ready?

I hope we have a month at least :)

**Comment by nesbox** [comment]
I added syntax buffer here c98eb4a,
now you can use 
``` c
if(code->syntax[pos] == SyntaxTypeComment)...
```
or 
``` c
if(code->syntax[pos] == SyntaxTypeString)...
```
to determine string type.

**Comment by technomancy** [comment]
That's exactly what I needed; thank you!
