### ISSUE TITLE
Stopping TIC() function

### ISSUE THREAD

**Issue by TesterSzymoon** [nesbox/TIC-80#1079]
Is it possible to stop an TIC() function from code? I mean in "if" condition, for example if a>5 then stop() end, but there's no command such an stop(), there's only exit(). How do I do that?

**Comment by stefandevai** [comment]
Hi :) So you have some options. For your example, you could wrap all your TIC function inside your condition:
```lua
function TIC()
  if a < 5 then
    update_and_render_game()
  end
end
```

Or if you have to stop TIC from another function, just create a flag variable:
```lua
local stop_tic = false

function foo()
  if a > 5 then
    stop_tic = true
  end
end

function TIC()
  if stop_tic == false then
    foo()
    update_and_render_game()
  end
end
```

If things get more complex, I suggest you using a [finite state machine](https://gameprogrammingpatterns.com/state.html) to avoid spaghetti code with a lot of if and else statements.

Good luck!

**Comment by Anrock** [comment]
One more option, without wrapping contents of your TIC function: add a condition at the very beginning of a TIC function: `if stop-condition then return`

**Comment by TesterSzymoon** [comment]
Thanks for the replies!
