### ISSUE TITLE
dofile() doesn't work with moonscript files

### ISSUE THREAD

**Issue by mth36** [nesbox/TIC-80#1080]
If i have a .tic file that looks like this:
![tic](https://user-images.githubusercontent.com/42794839/81460533-9e34a580-916b-11ea-8e93-985009022ea5.gif)

where game.moon is:
![moongame](https://user-images.githubusercontent.com/42794839/81460552-b99fb080-916b-11ea-8c1f-52779d91cfdb.PNG)
(it's in the same directory as the tic80 exe)

I get this error:
![error](https://user-images.githubusercontent.com/42794839/81460564-c58b7280-916b-11ea-8e41-5f4eac47d206.gif)

BUT if I write game.moon as if it were a .lua file:
![ticgame](https://user-images.githubusercontent.com/42794839/81460575-d4722500-916b-11ea-83ab-f7514a2cf5f8.PNG)

it runs just fine.

is that intended behavior? I thought that, since i tagged the script as 'moon', it would treat the dofile() as moonscript. Am i only allowed to import lua code with dofile()?

**Comment by nesbox** [comment]
Try to add `-- script: moon` at start

**Comment by nesbox** [comment]
Btw, `dofile()` is removed in upcoming .80 version but you can save carts as text

**Comment by mth36** [comment]
Okay, it seems to work if I add `-- script: moon` to both files, but I guess it doesn't matter much if 0.80 won't include it.
