### ISSUE TITLE
Screen fails to re-size correctly after Alt+Enter (Linux)

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1083]
I run any cart then go full screen via Alt+Enter. I restore window size using Alt-Enter and TIC's output is now smaller than it was originally. If I slightly enlarge the window the output immediately scales to the original size. I think there's a small error in the scaling algorithm. Maximizing and restoring the window works as expected, it only happens when switching to full screen and back.

Before:
![image](https://user-images.githubusercontent.com/3756822/81741197-1665d880-9496-11ea-8a7f-0b6baebf1591.png)
After:
![image](https://user-images.githubusercontent.com/3756822/81741240-25e52180-9496-11ea-8995-e1d367e159eb.png)

**Comment by nesbox** [comment]
It's strange, because I just fixed this bug few weeks ago here 1fcde1a.
What version do you test? I don't see a version number in your build.
Thanks.

**Comment by RobLoach** [comment]
Thisi s okay for me on the latest from master...

![Screenshot at 2020-05-13 01-58-12](https://user-images.githubusercontent.com/25086/81776710-4aa0bf80-94bd-11ea-894a-c96cb3076337.png)
![Screenshot at 2020-05-13 01-58-27](https://user-images.githubusercontent.com/25086/81776711-4aa0bf80-94bd-11ea-86bb-26bb12740de3.png)

**Comment by paul59** [comment]
> It's strange, because I just fixed this bug few weeks ago here [1fcde1a](https://github.com/nesbox/TIC-80/commit/1fcde1acccc62d984cf2a0cf38fd55765f8e833d).
> What version do you test? I don't see a version number in your build.
> Thanks.

Ah ok, I'm using the Pro binary from itch.io so it's probably out of date. I had errors building from latest on git - I just got a new machine, maybe missing some dependencies, will try again later.

(Sorry for the duplicate)
