### ISSUE TITLE
Building without GTK dependencies

### ISSUE THREAD

**Issue by vanfanel** [nesbox/TIC-80#1084]
Hi there!

I have just discovered TIC-80, and I am trying to build it for my Pi, where no Xorg server is running or needed. SDL2 programs dont need Xorg because SDL2 has KMSDRM support, so the system boots in 1 second :)

So, since we have SDL2 and its KMS/DRM backend, is it possible to build TIC-80 without GTK dependencies? If its not possible... why not?

Thanks!

**Comment by nesbox** [comment]
It's possible to build without GTK, we use it to show system file save/load dialogs, so you can disable code in the `file_dialog_load() / file_dialog_save()` functions and build.
https://github.com/nesbox/TIC-80/blob/0feb848378fc40d16aaa609ed7a2148d7a064ac4/src/ext/file_dialog.c#L170

**Comment by vanfanel** [comment]
Ok, I am trying to build like that, but I get a not related problem:

`
manuel@teclast:~/src/TIC-80/b3$ cmake ..
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	b3/

nothing added to commit but untracked files present (use "git add" to track)
Building for target : Linux
PROJECT_VERSION: 0.80.2-dev
CMake Error at CMakeLists.txt:355 (add_subdirectory):
  The source directory

    /home/manuel/src/TIC-80/vendor/sdl2

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:545 (add_subdirectory):
  The source directory

    /home/manuel/src/TIC-80/vendor/zip

  does not contain a CMakeLists.txt file.


-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:778 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/manuel/src/TIC-80/b3/CMakeFiles/CMakeOutput.log".
See also "/home/manuel/src/TIC-80/b3/CMakeFiles/CMakeError.log".

`

I can add -DDISABLE_NETWORKING=1 to the cmake command, but it fails on sdl2 and zip directories.
Any idea on whats going on?

**Comment by nesbox** [comment]
you have to update submodules, use `git submodule update --init --recursive` command

**Comment by vanfanel** [comment]
@nesbox Right! Thanks!
Commenting out the GTK functions in src/ext/file_dialog.c, and the GTK include, and the GTK detection in CMakefiles.txt, does indeed get me a building version now :)
Would you accept a PR so I dont have to do all this every time I rebuild on the PI? My idea is simply disabling it if it is not found, and putting the small GTK code inside an #ifdef. You can also do it yourself, if you feel like it. But I think that making GTK an "optional dependency" is a good idea, as TIC-80 is very well suited for small Xorg-less systems thanks to SDL2.

**Comment by nesbox** [comment]
better, I will add an alternative file saving functionality without UI dialogs and a build option to enable/disable it.

**Comment by vanfanel** [comment]
Great! What about X11 linkage? Can it be disabled somehow or is it detected depending on whats SDL2 built against?

**Comment by nesbox** [comment]
Don't know about disabling X11 in SDL2, try to look into `vendor/sdl2/CMakeLists.txt`, maybe you find options you need.

**Comment by vanfanel** [comment]
Well, it seems that independently from SDL2, it tries to build Desktop GL:

```
In file included from /home/pi/src/TIC-80/vendor/sdl-gpu/src/externals/glew/glew.c:33:
/home/pi/src/TIC-80/vendor/sdl-gpu/src/externals/glew/GL/glew.h:1202:14: fatal error: GL/glu.h: No such file or directory
 1202 | #    include <GL/glu.h>
      |              ^~~~~~~~~~
compilation terminated.

```

No way to disable that? SDL2 is enough, really.

**Comment by RobLoach** [comment]
You'll need the gl-dev dependencies. libopengl-dev usually.

Also can be...
libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev

**Comment by vanfanel** [comment]
@RobLoach So, does TIC-80 depend on desktop-GL? Cant it just use whatever renderer SDL2 uses? In my case, its GLES2. And anything (2D) goes.

**Comment by nesbox** [comment]
Added GTK libs autodetection here ee40393 20ff233.
