### ISSUE TITLE
Suggestion: Change show/hide grid key in map editor

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1085]
Would it make more sense to change the show/hide grid shortcut from ` (back-tick) to # (hash) as this matches the symbol at the top of the window for this feature?

**Comment by nesbox** [comment]
to get `#` you have to press `shift+3` on my keyboard, don't think it's more convenient than just one button

**Comment by paul59** [comment]
> to get `#` you have to press `shift+3` on my keyboard, don't think it's more convenient than just one button

Fair point I wasn't thinking about the convenience, just the association of the symbol with the key. What about changing the symbol from '#' to 

![image](https://user-images.githubusercontent.com/3756822/82039929-9d38d200-969d-11ea-8e60-7184c19ede0d.png)

**Comment by nesbox** [comment]
Could you pls change it yourself here
https://github.com/nesbox/TIC-80/blob/0feb848378fc40d16aaa609ed7a2148d7a064ac4/src/map.c#L110
I'll approve your pull request

**Comment by paul59** [comment]
Done
