### ISSUE TITLE
Problem building on Linux (Mint)

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1086]
I'm trying to build the latest version using the supplied instructions. When issuing command 'make -j4' I get the following fatal error (I also tried installing alsa-source package in case the missing header file is in that package but get the same error):

In file included from /home/paul/TIC-80/src/system/sokol_impl.c:36:0:
/home/paul/TIC-80/vendor/sokol/sokol_audio.h:765:10: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/sokol.dir/build.make:86: recipe for target 'CMakeFiles/sokol.dir/src/system/sokol_impl.c.o' failed
make[2]: *** [CMakeFiles/sokol.dir/src/system/sokol_impl.c.o] Error 1
CMakeFiles/Makefile2:798: recipe for target 'CMakeFiles/sokol.dir/all' failed
make[1]: *** [CMakeFiles/sokol.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 86%] Built target SDL2-static
[ 86%] Building C object CMakeFiles/tic80core.dir/src/tools.c.o
[ 86%] Building C object CMakeFiles/tic80core.dir/src/jsapi.c.o
[ 86%] Building C object CMakeFiles/tic80core.dir/src/luaapi.c.o
[ 87%] Building C object CMakeFiles/tic80core.dir/src/wrenapi.c.o
[ 87%] Building C object CMakeFiles/tic80core.dir/src/squirrelapi.c.o
[ 87%] Building C object CMakeFiles/tic80core.dir/src/ext/gif.c.o
[ 87%] Linking CXX static library lib/libtic80core.a
[ 87%] Built target tic80core
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Any suggestions please?
This is on Mint 19.3 64 bit.

**Comment by nesbox** [comment]
Try to install `libasound2-dev`.

**Comment by paul59** [comment]
> Try to install `libasound2-dev`.
Thanks, of course! OK it builds properly now **but** I have no sound on boot or in SFX editor for example. I ran the 0.80 binary from itch.io I was using and sound is normal. Any idea?

(And wow! Looks like you've made a lot of changes!)

**Comment by nesbox** [comment]
Do you see any errors in the terminal?

**Comment by paul59** [comment]
No, sorry, all appears fine:

 ./tic80

 TIC-80 tiny computer 0.80.1173-dev
 http://tic80.com (C) 2020

 hello! type help for help

>help
available commands:

HELP      show this info
WIKI      open github wiki page
RAM       show 80K RAM layout
VRAM      show 16K VRAM layout
EXIT/QUIT exit the application
NEW       create new cart
LOAD      load cart
SAVE      save cart
RUN       run loaded cart
RESUME    resume run cart
EVAL/=    run code
DIR/LS    show list of files
CD        change directory
MKDIR     make directory
FOLDER    open working folder in OS
ADD       add file
GET       download file
EXPORT    export native game
IMPORT    import sprites from .gif
DEL       delete file or dir
CLS/CLEAR clear screen
DEMO      install demo carts
CONFIG    edit TIC config
VERSION   show the current version
EDIT      open cart editor
SURF      open carts browser

press ESC to enter UI mode

**Comment by nesbox** [comment]
What about regular build with SDL, does it have sound?
Also, try to test the latest builds from our server https://builds.tic80.com/master/2020.05.13

**Comment by paul59** [comment]
Thanks for that. Sound works fine using test binary from that url. Not sure what you mean by 'regular build with SDL'?

**Comment by nesbox** [comment]
> Not sure what you mean by 'regular build with SDL'?

After a successful build, you can find two binaries in `build/bin` folder, `tic80` (SDL lib) and `tic80-sokol` (Sokol lib).
Please test them for the issue with sound and let us know, if not difficult.
Thank you.

**Comment by paul59** [comment]
OK, I have sound with tic80-sokol but not with SDL version.

**Comment by nesbox** [comment]
ok, try to install `sudo apt-get install libasound2` and test SDL again, thanks

**Comment by paul59** [comment]
It's already installed (both the lib and the dev files)

**Comment by nesbox** [comment]
Hmm, don't what to say then, sorry.

**Comment by paul59** [comment]
OK, at least the sokol and latest test build binaries work.
Thanks again,

PaulR

**Comment by paul59** [comment]
Running the test build from the url you gave, I've just noticed this in the terminal:

ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred

TIC starts and the sound seems to work normally. I'm guessing from the filesize this is the sokol version rather than SDL (4mb against 13mb)?

Any help?

**Comment by nesbox** [comment]
> I'm guessing from the filesize this is the sokol version rather than SDL (4mb against 13mb)?

Yes, Sokol lib is much smaller than SDL with the same functionality, that's why we are going to use it in the future releases. Also, try to run CMake with flag `-DCMAKE_BUILD_TYPE=MinSizeRel` and rebuild the release version, you will get ~2mb for Sokol version and ~4mb for SDL.

**Comment by nesbox** [comment]
One more thing, try to do a clean rebuild if you installed `libasound2-dev` after the first unsuccessful build.

**Comment by paul59** [comment]
Yes, a clean build now gives me sound in SDL and sokol versions! 

Thanks for the help, looks like the wiki will be getting some updates from me shortly!

**Comment by nesbox** [comment]
Great, thank you for the help 👍 
I'm closing the issue...
