### ISSUE TITLE
Music Editor with piano roll

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1090]
![image](https://user-images.githubusercontent.com/1101448/82188772-0c5d3300-98f7-11ea-8ab6-5e2663c264dd.png)

**Comment by nesbox** [comment]
added wave preview to the Sfx and Music editors 4c8922e
![ezgif com-optimize](https://user-images.githubusercontent.com/1101448/82224202-40068000-992c-11ea-89dd-dce2a8a3b5ea.gif)

**Comment by BuoYancYdabl** [comment]
What the "command" field for?

**Comment by nesbox** [comment]
The first implementation of the Piano mode 8bfb0de
![music](https://user-images.githubusercontent.com/1101448/91062357-44ca8680-e635-11ea-8174-9d6b8b85c472.gif)

**Comment by farvardin** [comment]
isn't a file missing in the repo? I don't have the piano display at the top:

![image](https://user-images.githubusercontent.com/477243/91172981-5e270d80-e6dd-11ea-85e3-44670cb8e5db.png)

**Comment by nesbox** [comment]
pls do clean rebuild or use `config reset` command

**Comment by farvardin** [comment]
I did a make clean and make again, but it was the same. Typing "config reset" inside the TIC-80 console did the trick, thank you!

**Comment by nesbox** [comment]
- added reverse note behavior for the right click e9ecc7b
- added tips b5fa023
![screen](https://user-images.githubusercontent.com/1101448/91175627-c67bec00-e6e9-11ea-9052-02139374cb64.gif)

**Comment by nesbox** [comment]
Added piano roll animation 5536097
![screen](https://user-images.githubusercontent.com/1101448/91195110-698c3000-e701-11ea-86ef-8513a93bc907.gif)
