### ISSUE TITLE
sfx() inconsistent frequency with string notes

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1092]
When calling sfx() with the note as string (e.g., "c-4"), sometimes the correct note is played but sometimes it isn't, playing another note instead. The behaviour seems inconsistent; one time, when I added one sfx call with string note, it suddenly "broke" several other string note sfx calls. With integer notes I always get the note I wanted, though.

Win 10, 0.70.6 pro

**Comment by nesbox** [comment]
hmm, what version?
dev or < 0.80

**Comment by nesbox** [comment]
could you also provide a small piece of code to reproduce the bug?

**Comment by borbware** [comment]
0.70.6 pro, i could try to write a short program that reproduces the bug for me!

**Comment by nesbox** [comment]
Could you pls try to reproduce it on the latest build https://builds.tic80.com/master/2020.05.22
Thank you.

**Comment by borbware** [comment]
okay i just realized what was the problem; i was using lowercase letters, which apparently do not work. feeling like an idiot :D

**Comment by paul59** [comment]
> okay i just realized what was the problem; i was using lowercase letters, which apparently do not work. feeling like an idiot :D
Trust me, you're not the first to have done this! Maybe we will get automatic toupper() someday :D

The other tiny issue I have is with the natural/sharp notation. While it makes coding easier and more compact than having both sharp and flat notation, to me it feels like E- is indicating E flat! Maybe a different character could be used... 'E:' maybe??
