### ISSUE TITLE
Print error trace in JavaScript

### ISSUE THREAD

**Issue by chronoDave** [nesbox/TIC-80#1113]
When TIC-80 throws an error when running JavaScript code, it returns just the error message, making debugging quite difficult on larger projects.

I'm not entirely sure how difficult this would be to implement, but I'd be more than happy to help solve this problem.

![t1MSIFL](https://user-images.githubusercontent.com/27073716/83950526-adbb1300-a82b-11ea-8aac-2f1dd1018078.png)

**Comment by chronoDave** [comment]
By replacing all `duk_safe_to_string()` functions to `duk_safe_to_stacktrace()` in `jsapi.c` I was able to get a rudimentary trace working. It's not a pretty trace, but the line numbers in the eval add up to the lines in the TIC-80 code editor

![DDSkeI4](https://user-images.githubusercontent.com/27073716/83952832-0692a780-a83c-11ea-8873-8a5905840234.png)

**Comment by RobLoach** [comment]
That seems like a better solution than I had proposed in https://github.com/nesbox/TIC-80/pull/1114

**Comment by chronoDave** [comment]
If it's ok, I'll leave the implementation up to you. You already got the PR open and seem more knowledgeable on the project. I simply followed build instructions and changed 4 lines in `jsapi.c` :)

**Comment by RobLoach** [comment]
Updated the PR to reflect that! :+1:
