### ISSUE TITLE
Add Gravity Scripting Language

### ISSUE THREAD

**Issue by RobLoach** [nesbox/TIC-80#1115]
Looks pretty neat! Similar to Wren, seems like.... https://github.com/marcobambini/gravity

**Comment by darltrash** [comment]
Sounds like a very cool idea!

**Comment by RobLoach** [comment]
Started to have a look at this https://github.com/RobLoach/TIC-80/pull/1

**Comment by RobLoach** [comment]
I'm going to be closing this one. Gravity looks pretty young still.
