### ISSUE TITLE
TIC-80 lags when display refresh rate is under 60 Hz

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1116]
**NOTE:** Here is the original post in which I did not know the culprit was my laptop's display refresh rate.

TIC-80 runs on a maximum of 48 fps on relatively new hardware (i7 8565U+UHD Graphics). The audio is distorted, as it runs on the same fps as well. 

I'm running [Al Rado's FPS.tic](https://tic.computer/play?cart=123) at 48 fps, and here, TIC-80 is utilizing around 25% of the CPU. I tried setting the priority of `tic80.exe` to high, but it made no difference.

![tic-80-fps](https://user-images.githubusercontent.com/19384640/84576105-e2464600-adba-11ea-9ce7-23af0fb3bb1a.png)

The CPU seems to use two (or three?) of the eight threads:

![tic-80-cpu-usage](https://user-images.githubusercontent.com/19384640/84576197-892ae200-adbb-11ea-957d-4d959d79ab55.png)

The two most utilized threads most likely belong to the same physical core, as TIC-80 uses only a single core, as discussed here[here](https://itch.io/t/185977/is-tic-80-too-heavy-for-me). The whole CPU usage is here 34%, of which around 10% is constituted by other apps than TIC-80.

Would parallelization be a viable and doable solution for this?

**EDIT:** Or... is this even associated to CPU, or is this rather a GPU issue? For reference, PICO-8 seems to run at 60fps!

**EDIT 2:** The culprit was not the CPU or the GPU, but rather my laptop's display refresh rate, which is 48 Hz:

![display-refresh-rate](https://user-images.githubusercontent.com/19384640/84592593-79f57400-ae4f-11ea-9d79-30a7e1ec77ff.png)

So, apparently TIC-80's internal clock is tied to the display refresh rate. Does this mean that on high-refresh rate monitors, TIC-80 runs super fast? And could TIC's internal clock be decoupled from the display refresh rate?

**Comment by RobLoach** [comment]
Somethign is really wrong with that build. It's running just fine for me on Linux. Try one of the latest dev builds?
http://dev.nesbox.com/master/2020.06.07

**Comment by borbware** [comment]
The newer builds had the same problem. And I found out the culprit - my laptop's display refresh rate is 48 Hz! I'll edit the post accordingly

**Comment by nesbox** [comment]
It's interesting because we don't use VSYNC to reach 60Hz refresh rate, maybe SDL2 lib doesn't allow use lower than 60Hz. Could you pls check `tic80-sokol.exe` build?

**Comment by borbware** [comment]
yeah, sure! I could not find `tic80-sokol.exe` in builds.tic.computer so I guess I'll build it myself once I've installed MinGW-64 on my laptop.

**Comment by borbware** [comment]
oof, tried building the latest master, but run into this error: (that is, I only succeeded in building the non-sokol version...)

![tic80-sookolbuild](https://user-images.githubusercontent.com/19384640/84835912-5001a480-b03d-11ea-84d7-20236db64159.png)

**Comment by nesbox** [comment]
I just checked at 30Hz and it seems to be ok, the only thing you need is disable VSYNC if Hz < 60.
