### ISSUE TITLE
Using relative path for `dofile` with html export

### ISSUE THREAD

**Issue by chronoDave** [nesbox/TIC-80#1117]
`./build.js` nor `build.js` are recognized by the html version of TIC-80 (v0.70.6).

![llD3o3c](https://user-images.githubusercontent.com/27073716/84648860-e59a1880-af05-11ea-831c-d90834fb9db4.png)

![BFPClZ3](https://user-images.githubusercontent.com/27073716/84648866-e6cb4580-af05-11ea-93d7-1607ca511003.png)

For building an html version of the game, is it recommended to simply copy-paste the code from the `dofile` into TIC-80 and then export it as html?

**Comment by nesbox** [comment]
yes, pls copy your code to the cart
