### ISSUE TITLE
"413 Request Entity Too Large" when uploading a cart to tic.computer

### ISSUE THREAD

**Issue by sssilver** [nesbox/TIC-80#1124]
After running`export native`, I try to upload the resulting 5.4Mb file to my account at https://tic.computer/add, however nginx complains:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/619878/85933563-62e36700-b8d0-11ea-945b-f8b151bfa599.png">

**Comment by StinkerB06** [comment]
The website only accepts *.tic carts. You cannot upload native binaries.

**Comment by potato25** [comment]
you need to add title , author , desc and script meta tags , add cover image by running program and pressing ' F7 ' key and then save it , and then export .tic cart and then upload , i figured this out after 1 year lol
