### ISSUE TITLE
(Enhancement) Posibility to map buttons

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#1127]
On android it would be great to map buttons and create new one's. For example:
``mapbtn("A",1,256,0,200,80,14,1,0,0,1,1,false)``
This command need to be run every tic to work. Parameters are: button title (may be empty ""), button id, sprite when unpressed, sprite when pressed, x, y cords, colorkey, size, rot, mir, size x, size y, change sprite when pressed.

**Comment by nesbox** [comment]
Not sure we can add new API functions especially for Android.
