### ISSUE TITLE
Saving to a cart extension that isn't .tic doesn't display the overwrite warning

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1130]
When saving over and existing file that ends in .tic a warning is shown but this doesn't show when saving over a .js 
![screen](https://user-images.githubusercontent.com/13716824/86684202-3af3b200-bffa-11ea-8c92-9d2dbb6ca5b4.gif)

**Comment by nesbox** [comment]
fixed here eeb1e4c
