### ISSUE TITLE
clipc(x,y,radius) function

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#1131]
clip() functions clips rectangle area , why isn't there a clipc() function to clip circular area ? i've wondered why it wasn't done . It would let for drawing light effects , stage effects , etc .

**Comment by RobLoach** [comment]
Because no one implemented it.

**Comment by potato25** [comment]
clip() resets whole screen to default , how would that work with this , if implemented ?

**Comment by potato25** [comment]
I resolved the problem using existing 0.70.6 functions , here's the cart : https://tic.computer/play?cart=1309
I added circular lighting effect by picking radius of particular size and getting individual pixel values inside radius using pix ( x , y ) function and updated the pixel values using pix ( x , y , val ) accordingly
So , this is unnecessary , so should this be closed ?

**Comment by nesbox** [comment]
Great, thanks :)
