### ISSUE TITLE
Release early, release often?

### ISSUE THREAD

**Issue by sssilver** [nesbox/TIC-80#1134]
Hi,

The last release of TIC-80 was 2 years ago. I understand there's a defined milestone with 15 issues still left in it to be resolved, but maybe we could subscribe to a model where we could try to release at least a little bit more frequently than 2 years?

**Comment by nesbox** [comment]
Hi,

>2 years ago I was working on TIC full time and releases were more often, about once a month.
Definitely, we have to choose a new more frequent model, ideally once a month, let's try to do it after .80 release.

**Comment by farvardin** [comment]
It's important to release often, it will raise more interest to the project, and give people the impression that's it's still alive. Not everyone will check the project's github or are able to compile it themself. People who paid for the pro version could also get a nice update (I paid for it but I can also compile it myself)

**Comment by nesbox** [comment]
Will try :)
