### ISSUE TITLE
Surf loops around at end only

### ISSUE THREAD

**Issue by nalquas** [nesbox/TIC-80#1138]
Surf appears to behave somewhat unintuitively here.
When going down the list and hitting the end, surf puts you back to the beginning of the list.
However, when going up the list, you are **not** being put to the bottom.
![tic80_surf_looping](https://user-images.githubusercontent.com/22664233/88513167-15017200-cfe8-11ea-9688-1a1d9838adc5.gif)
(Built from source using AUR `tic-80-git`, 0.80.1267-dev Pro, Linux 64bit)

**Comment by nesbox** [comment]
fixed here c28510a
