### ISSUE TITLE
Surf does not show all games

### ISSUE THREAD

**Issue by nalquas** [nesbox/TIC-80#1139]
Surf seems to cut off at a certain point down the list.

As you can see, surf cut off the list of games at "cat at home" for me while the TIC-80 website's list contains more games down the list:
![Screenshot_20200727_092105](https://user-images.githubusercontent.com/22664233/88514680-cdc8b080-cfea-11ea-93f4-eb2f102a616c.png)
(Built from source using AUR `tic-80-git`, 0.80.1267-dev Pro, Linux 64bit)

**Comment by nesbox** [comment]
fixed on the server
