### ISSUE TITLE
Found Bug in 0.80.1278-dev

### ISSUE THREAD

**Issue by rahul625** [nesbox/TIC-80#1145]
![Screenshot_2020-08-15-06-16-41-175_com nesbox tic](https://user-images.githubusercontent.com/47915829/90301739-48387200-debf-11ea-83dd-255dccbea357.png)
Found bug in android version ,
The bug can be replicated by first changing palette in OVR palette editor , then calling spr() function in OVR() function and running the program and then going to sprite editor

What's happening is the default Palette is replaced by OVR() Palette in Sprite editor and Map editor

**Comment by nesbox** [comment]
Thanks, investigating...

**Comment by nesbox** [comment]
Fixed here 13ee498.
Thank you for the report.
