### ISSUE TITLE
Bug: reCAPTCHA shows up unnecessarily

### ISSUE THREAD

**Issue by abowerman** [nesbox/TIC-80#1146]
Bug: I'm seeing a reCAPTCHA on initial login.

Steps to reproduce: 

- visit https://tic.computer/signin
- reCAPTCHA appears on page.

**Comment by StinkerB06** [comment]
reCAPTCHA is implemented as a security measure to prevent bot-spamming on the site.

**Comment by abowerman** [comment]
This didn't happen after any attempts though. this was my first visit.

**Comment by abowerman** [comment]
It looks like I already have to go through reCAPTCHA on account creation as well.

**Comment by fnordomat** [comment]
As a tor user, I've been harassed by reCaptcha at every login, not just account creation where it would make sense.
Also, the rudely worded "we're checking your browser" page of cloudflare shows up on every page load.
Please fix this :-(
