### ISSUE TITLE
Shouldn't "cd.." (without a space) be a valid command? 

### ISSUE THREAD

**Issue by Skaruts** [nesbox/TIC-80#1150]
I don't know if this annoys other people, but because I use `cd..` all the time in the windows console, the force of habit makes me keep getting the _"unknown command"_ error in TIC-80. It gets a bit annoying over time...

You think you could add support for it?
Thanks. :)

**Comment by raydeejay** [comment]
It's relevant in that `cd..` is an artifact of how MSDOS implemented command-line parsing, whereas most other OSs/shells, unix or not, will require a space between a command and its parameters.

**Comment by Skaruts** [comment]
@raydeejay, I don't mean to be rude, but you're not telling me anything fundamentally different from what I've already been told. Which is irrelevant all the same if TIC-80 isn't aiming to accurately mimicking any specific systems or standards, which seems to be the case, given that the existing commands are a mix. It really doesn't matter if it came from a bug or a hack or whatever. It's there, and personally I even think it's quite a good idea (makes frequent navigating easier), and I'm just putting it on the table here. Personally, I think TIC could even support `cd\` as well. I would even vote for an `md` command, which is in some ways a more wieldy version of `mkdir`, but that would grow the list of commands and I don't know if that's acceptable. 

Don't get me wrong, I'm ok with this being rejected, if it gets to that. It's no big deal. I just don't find your points relevant to whether or not it should be a thing in TIC-80. What is relevant is:
- is it a good idea?
- is it easy, or at least feasible to implement?
- if it requires a bit of a hack to implement, would that be a problem in this case?

**Comment by nesbox** [comment]
Seems `cd..` is an invalid command.

**Comment by Skaruts** [comment]
@nesbox ok, but that's why I created this issue asking if it could be turned into a valid command.

**Comment by joshgoebel** [comment]
My 0.02: This is an _edge case_ not worth the time to add support for with all the other things in the queue.  I'd rather have a 0.90 release a bit sooner than hold it up working on things like this.

It seems it's being requested because someone has developed an affinity for Windows "broken" behavior (IMHO).  I don't think we should emulate that brokenness.   Would it be of benefit to the requestor?  I have no doubt, hence the request... BUT would it be helpful to the other 98% of people who use TIC-80 - and probably will never even know about this behavior... I doubt it.

**Comment by Skaruts** [comment]
Well, I'm not asking for it to be supported ASAP. I'm just asking. This is at most a _nice-to-have_, not an pressing matter. It's an edge case, indeed, and I'm probably the only one annoyed enough to be here. The only reason I asked is because it seems to be trivial to implement by someone feeling bored on a coffee break. Unfortunately I don't know enough to do it myself, or to even be sure of it being that trivial.

As for it being broken... well it can't be broken if it works reliably and is handy. I'm quite happy to be spoiled by it, as I use the console a whole lot (and it's totally an unfathomably ridiculous facepalm of a console, but not at all for this reason).
