### ISSUE TITLE
TIC-80 package for Atom Editor

### ISSUE THREAD

**Issue by ViChyavIn** [nesbox/TIC-80#1153]
Hello!

I've just published TIC-80 package for Atom Editor! Despite it's 0.1.0, it's pretty polished at this point (however, I plan do add some more features later).

 It includes:
* Tools to run/edit files and a functionality to easily create a project
* Terminal that duplicates TIC's console output in Atom
* Autocomplete feature for TIC's API and some snippets

Repo: https://github.com/ViChyavIn/atom-tic80/

**Comment by nesbox** [comment]
Looks great!
Could you please add a link to the wiki, to the [Using external code editors](https://github.com/nesbox/TIC-80/wiki#using-external-code-editors) section?
Thank you.

**Comment by ViChyavIn** [comment]
Done!
