### ISSUE TITLE
Piano mode bug

### ISSUE THREAD

**Issue by maniek207** [nesbox/TIC-80#1156]
Keys on keyboard in piano mode does not show up properly.
![screen](https://user-images.githubusercontent.com/46056766/91862883-ca21ec80-ec6e-11ea-9a6a-0d4fbfaac5df.gif)

**Comment by nesbox** [comment]
pls do clean rebuild or call `config reset` command

**Comment by maniek207** [comment]
Reseting config worked. Thanks.
