### ISSUE TITLE
JS multi-line comments can never be closed

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1157]
![image](https://user-images.githubusercontent.com/13716824/92115025-b64ec580-ede9-11ea-9f4d-c279a3545dbf.png)
![image](https://user-images.githubusercontent.com/13716824/92115038-bc44a680-ede9-11ea-8174-803fd152bc70.png)

**Comment by nesbox** [comment]
Thank you for the report.

**Comment by nesbox** [comment]
Unfortunately, can't reproduce it, does it reproduce consistently on your side?

**Comment by ChildishGiant** [comment]
I can reproduce on the beta build from github ([0.80.1300-beta](https://github.com/nesbox/TIC-80/releases/download/v0.80-beta/tic80-v0.80beta-win.zip)) but not on the build on itch (0.80.1261-dev) I guess this means that it's a regression since then?

![image](https://user-images.githubusercontent.com/13716824/93017218-e0a93b80-f5be-11ea-81ba-8965a0f046a6.png)
![image](https://user-images.githubusercontent.com/13716824/93017222-ebfc6700-f5be-11ea-8ac8-fd8b78a58ffc.png)

**Comment by Kozova1** [comment]
I built from master (commit: 195832ba01922f59db141967304dff93cc68821f) and I don't have this issue too. Version 0.80.1324-dev on linux.

**Comment by nesbox** [comment]
Reproduced on the version from Github.
Fixing...

**Comment by nesbox** [comment]
Stupid MS compiler optimizes code in a wrong way and doesn't see `continue` statement, all the other compilers works ok.
So, I added `goto` statement here https://github.com/nesbox/TIC-80/blob/master/src/code.c#L413 to avoid this.
Fixed here 12b06d5.
