### ISSUE TITLE
Update Visual Studio Build Instructions for 2019

### ISSUE THREAD

**Issue by nogwater** [nesbox/TIC-80#1158]
Visual Studio 2019 is the current version and the build instructions are slightly different.  For one, cmake isn't part of the Windows PATH by default, and the string argument is slightly different.  Here are the steps I used for [VS 2019 Community](https://visualstudio.microsoft.com/vs/community/) (installed with the `Desktop Development C++` workload):

1. Launch Visual Studio 2019
2. Get Started > Open a Local Folder
3. Select the `TIC-80` Git folder
4. Tools > Command Line > Developer Command Prompt
5. `cd build`
6. `cmake -G "Visual Studio 16 2019" ..`
This generates your project files and a solution file.  Back in Visual Sutidio:
7. File > Open > Project/Solution
8. Select `TIC-80\build\TIC-80.sln`
9. Build > Build Solution
Executables can be found in `TIC-80\build\bin`

Alternatively, you can build without project or solution files with these steps:
1. Launch Visual Studio 2019
2. Get Started > Open a Local Folder
3. Select the `TIC-80` Git folder
Wait for CMake to finish its work.
4. Solution Explorer > Right-Click CMakeList.txt > Build
Executables can be found in `TIC-80\out\build\x64-Debug (default)\bin`

I don't know if one of these is better than the other.  I'm not a C++ developer.

**Comment by nesbox** [comment]
Could you pls update the build instructions?
https://github.com/nesbox/TIC-80/wiki/build-instructions
Thank you.

**Comment by nogwater** [comment]
Done
