### ISSUE TITLE
btnp/btn functions not responding in certain carts on master

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#1162]
While I was testing #1161 I with some games written in Fennel I noticed that in certain carts, the `btnp` and `btn` functions seemed to never return true. Most carts it worked fine, but in Amethyst Waters (https://stefandevai.itch.io/amethyst-waters) I was unable to begin the game. It also came up with my Conway's Life implementation: https://tic.computer/play?cart=656

I bisected the history and found that this bug was introduced in #810. Prior to that patch, these carts both worked fine.

**Comment by nesbox** [comment]
Amethyst Waters uses `--input: keyboard` tag and Conway's Life uses `--input: mouse` which means only these declared input types will be allowed in a game and `btn()` API won't work.
So, it's not a bug, it just wasn't working in 0.70 but works now :)

**Comment by technomancy** [comment]
Aha, I see! Thanks for the explanation.

So for Amethyst Waters the solution is rather simple; replace `btn` with `key`. For Life, it will be a bigger change since some kind of purely-mouse-based menu system will be needed for commands that used to use `btnp`.

In any case, I will close this since it's not a bug. However, I foresee this causing surprises to other cart authors. Perhaps this change could be made clearer on the release notes?
