### ISSUE TITLE
(0.80 beta) time() always returns 0 when built with sokol

### ISSUE THREAD

**Issue by drako0812** [nesbox/TIC-80#1163]
I remember this has also happened before 0.80 beta, but the function `time` always returns 0 when using `tic80-sokol`.

The easiest way to see this is when running the `benchmark.tic` cart. When running one of the benchmarks they will never finish, because they aren't detecting any time has taken place. This seems like a fairly important bug to me.

The main reason I use the sokol build is because it performs better and the audio isn't choppy on my computer. It looks like the audio issues for the main build are being looked into for the 0.90 version, though.

**Comment by nesbox** [comment]
This is because `getPerformanceCounter()` and `getPerformanceFrequency()` not implemented here https://github.com/nesbox/TIC-80/blob/a858e83594cde0ac1a0f6c722f2b4ee445cf0047/src/system/sokol.c#L79

**Comment by nesbox** [comment]
It's not difficult and it's provided by the Sokol https://github.com/floooh/sokol/blob/master/sokol_time.h
We just need to use it...

**Comment by drako0812** [comment]
Funnily enough I was just looking at the header myself, this should be easy enough. I can't guarantee anything, but I'll see if I could put together a pull request when I have the time.
