### ISSUE TITLE
Discord Streaming Unintended Behavior

### ISSUE THREAD

**Issue by nearlyNonexistent** [nesbox/TIC-80#1166]
![image](https://user-images.githubusercontent.com/4041565/92420682-ac023380-f129-11ea-973c-9705f93eb09f.png)

Going to presume behavior like this isn't intended. When I hit screen share on TIC-80, it discords the screen wildly in ways that are unpredictable. This applies for 0.70.6 and the 0.80 betas.

**Comment by nesbox** [comment]
Is this really a TIC problem?

**Comment by borbware** [comment]
Don't think so, I was able to stream TIC-80 on Discord without any issues.

**Comment by nearlyNonexistent** [comment]
Might be driver related; built it myself and sokol build works fine. Might just be SDL build on my system. Closing issue as others can't reproduce.
