### ISSUE TITLE
JS: classes don't work? Why?

### ISSUE THREAD

**Issue by ViChyavIn** [nesbox/TIC-80#1168]

**Comment by RobLoach** [comment]
The interpreter used by TIC-80 is Duktape https://duktape.org/ .... It doesn't implement ES5.

You can, however, transpile your JavaScript with something like:
https://github.com/RobLoach/tic80-js

You could even use TypeScript, as long as you compile it down to <ES5.

**Comment by ViChyavIn** [comment]
Got it. Thanks!
