### ISSUE TITLE
Export to html doesn't work on Windows

### ISSUE THREAD

**Issue by Dzejkop** [nesbox/TIC-80#1169]
Version is `0.80.1300-beta`, when using `export native`, `export sprites`, etc. everything is working fine. But for `export html` nothing is exported and the console only shows `game not exported :(`.

Tested both on my project and on an empty project

**Comment by Dzejkop** [comment]
Going to test Linux tomorrow

**Comment by nesbox** [comment]
Hmm, do you have the Internet on this machine?
TIC needs to download an HTML template first time to do the export.

**Comment by Dzejkop** [comment]
Works fine on Linux.

I did have internet, wouldn't lack of internet also cause `export native` to fail?

Also is there any log file I could look into to figure out what caused this?

**Comment by Dzejkop** [comment]
Actually I have an idea, could this be caused by spaces or non ASCII characters in paths?

**Comment by nesbox** [comment]
Yes, this could :) I think I know how to fix it, thank you :)

**Comment by nesbox** [comment]
Added temporary workaround here d0f4248.
