### ISSUE TITLE
Can't remap default gamepad inputs in the browser version

### ISSUE THREAD

**Issue by another-m00** [nesbox/TIC-80#1177]
I'm having trouble setting the gamepad **(A)** button to Y (I use a qwertz keyboard) and i want to set Y as a default **(A)** button.
I'm guessing the _Create_ windows's configuration is copied so i tried to set it there.
In _Create_ I couldn't set it beacuse, `surf` just exits when im pressing escape, without the menu, that would allow to do so.

There's no metion of it in the in the config file and it wont be copied backwards as far as i know.

**No such prolem is present in any other console.**
(tested on android, windows and web.)

_I hope the problem is clear, and thanks in advance._

_Edit:_ In the console versions you can set the default keypad, by navigating and loading a project in the tic.computer directory and setting it over there with the escape method

**Comment by nesbox** [comment]
You can use `menu` command and configure the gamepad there.
