### ISSUE TITLE
Bug when saving cart with exactly 65536 characters of code

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#1179]
https://github.com/nesbox/TIC-80/blob/4f8ab300fdb9e6b8d04750842d9d4bca22661823/src/cart.c#L209

Shouldn't you be using `>=` instead of `>`? `TIC_CODE_BANK_SIZE` is 65536, but the maximum 16-bit integer is 65535. Thus, when the code is 65536 characters long, it ends up writing a size of 0 to the code chunk.

**Comment by nesbox** [comment]
Seems you're right here.
Thanks.

**Comment by nesbox** [comment]
Fixed here 704f8e0.
Thank you.
