### ISSUE TITLE
Editor doesn't highlight HTML-style JS comments

### ISSUE THREAD

**Issue by Kozova1** [nesbox/TIC-80#1180]
![img](https://user-images.githubusercontent.com/30871100/93438458-02176980-f8d6-11ea-8c61-4226bd607d5b.png)
ECMAScript 2015 supports HTML style comments for JS. those comments are of this format:
```html
<!-- This is a comment -->
```
Please note that they're also supported by Duktape, so IMO they should definitely be highlighted correctly.

I might submit a PR to fix this later.

**Comment by nesbox** [comment]
Didn't know it, thanks

**Comment by nesbox** [comment]
Fixed here a6bdfb4.
