### ISSUE TITLE
Binary section comments in text carts are left in code when using -code-watch

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#1183]
When you run `load foo.lua` in the console, it successfully parses the binary sections, and the text section omits the comments containing binary data as per `loadTextSection`.

However, when you load a file using `-code-watch`, this does not happen; the binary sections are loaded but their comments are left inside the text section. Saving it off again as `foo.lua` results in duplicate data comment sections in the resulting file.

**Comment by nesbox** [comment]
Not sure it's a bug, because it loads the whole `.lua` file as a code section when you use `-code` cmd param.
Try to run TIC `tic80 foo.lua`, this will allow the loading cart as a project with enabled code auto-update.
