### ISSUE TITLE
TIC-80 32-bit version does not run on 32-bit Windows

### ISSUE THREAD

**Issue by romanxsource** [nesbox/TIC-80#1185]
Try running this on a 32-bit version of Windows! It won't work! Fix it please.

**Comment by RobLoach** [comment]
What error do you get?

**Comment by nesbox** [comment]
Beta is 64 bit, please check one of these https://builds.tic80.com/master/2020.09.19/win depending on your Windows version.
Thanks.

**Comment by kikeroga3** [comment]
The binary size of "tic80.exe" is smaller than before. It's good (^^
