### ISSUE TITLE
Creating or loading a cartridge resets font setting to default in code editor

### ISSUE THREAD

**Issue by JasonNumberThirteen** [nesbox/TIC-80#1188]
It's a tiny thing, but I noticed retrieving font to default (wider) everytime **when a new cartridge is created by the "_new [language]_" command**. It's the same situation after loading any previously saved. Shouldn't software remember this setting when user switched to the narrower font earlier? Checked **0.80.1345 Pro** and **0.80.1344** (on official website) versions. Both produce this.

**Comment by nesbox** [comment]
TIC recreates the Code Editor on a new cart and this causes this reset, we have to keep the previous one.

**Comment by JasonNumberThirteen** [comment]
OK, I thought it wasn't supposed to happen and it was an another bug.
