### ISSUE TITLE
New Startup Sound - (0.90) Update

### ISSUE THREAD

**Issue by MasterNama2008** [nesbox/TIC-80#1189]
Hi, I do you change startup sound TIC-80 new one?
**Example:** TIC-80 opening the app after playing startup sound.

File: 
[new startup.zip](https://github.com/nesbox/TIC-80/files/5286461/new.startup.zip)

SFX Data: `00c0000000c0003000000030000000300000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000f000360000000000`

**Comment by another-m00** [comment]
The startup sound is stored in the config cartirdge, at sfx id 1.
I don't think that the default startup sound should change, but you can customize the current one.

I hope i could help

**Comment by nesbox** [comment]
Yes, you can always save the sound in the config.
