### ISSUE TITLE
(0.90.1340-dev) BUG: Android Version opening the app and open again results black screen

### ISSUE THREAD

**Issue by MasterNama2008** [nesbox/TIC-80#1190]
Hi, I got black screen i switched app. That's annoying!!!

File: 
[TIC80_BLACKSCREENGIF.zip](https://github.com/nesbox/TIC-80/files/5288059/TIC80_BLACKSCREENGIF.zip)

Please check this video.

**_PLEASE FIX THIS!!!_**

**Comment by MasterNama2008** [comment]
Here, there's is video link: [TIC-80 BUG Video](https://youtu.be/mFvKzVxTgYo)

**Comment by nesbox** [comment]
Hmm, all is ok on my side, does anyone has the same problems?

**Comment by MasterNama2008** [comment]
@nesbox 

> Hmm, all is ok on my side, does anyone has the same problems?

I used **SDL** video plugin, i reopened app cause like black screen. What happening that code bug?.
duplicate of issue #1013.

**Comment by nesbox** [comment]
What is the SDL video plugin? Also, does it reproduce if you don't use the SDL plugin?
I don't understand, sorry.
