### ISSUE TITLE
Change Duktape to QuickJS for ES6 features.

### ISSUE THREAD

**Issue by Kozova1** [nesbox/TIC-80#1191]
[QuickJS](https://github.com/bellard/quickjs) supports way more ES6 features than Duktape, some of which would help developers.

I have a [repository](https://github.com/Kozova1/quickjs-example) that demonstrates using QuickJS when embedded in C, with a C module that can be imported from JS, if that helps.

**Comment by Kozova1** [comment]
This is a possible way to close issue #1129

**Comment by Kozova1** [comment]
I'm working on a PR that will introduce QuickJS as an option (`new qjs` or `new qjavascript`).

**Comment by nesbox** [comment]
We could replace Duktape with QuickJS if all the JS carts will work.

**Comment by Kozova1** [comment]
It should be possible to add functions to a global scope instead of inside a module using JS_GetGlobalObject(), JS_SetPropertyStr(), and JS_CreateCFunction(). In that case, all JS carts should still work perfectly.

my fork at https://github.com/Kozova1/TIC-80.git uses the ES6 module system, and hides away all the builtin TIC-80 functions inside the `tic80` module.  
Unfortunately, my fork has some memory bugs because of my shitty implementation, so until they're solved it should not be merged (since it just crashes immediately if it doesn't get a JS exception).

**Comment by RobLoach** [comment]
Duplicate https://github.com/nesbox/TIC-80/issues/874

**Comment by joshgoebel** [comment]
Agree. Recommend we close as dup.

**Comment by joshgoebel** [comment]
@Kozova1 Did you ever make any more progress? Anything specific you need help with?

**Comment by Kozova1** [comment]
Didn't really make any more progress. Some help with how exactly to use QuickJS would be great since last time I checked the docs aren't really great.

**Comment by joshgoebel** [comment]
Yeah seems you'd have to read and learn from the examples.  If you had a very specific question feel free to ask here.

**Comment by rdeforest** [comment]
I'm interested in this as a way to make using CoffeeScript easier. Currently I'm using Babel and Rollup and some magical incantations just so I can require() a module of code shared amongst my various toys.

If this moves forward I might be tempted to contribute a hack to make CoffeeScript work in TIC 'natively': write CoffeeScript in the editor, translate it to JS behind the scenes.

**Comment by joshgoebel** [comment]
I personally don't think we should support transpiled languages... gotta draw the line somewhere.

**Comment by RobLoach** [comment]
Moonscript is in there 🤷... CoffeeScript is pretty old tho lol

**Comment by joshgoebel** [comment]
Yeah, maybe old is a better argument. :-)

**Comment by Anrock** [comment]
> Yeah, maybe too old is a better argument. :-). I think we need SOME criteria though. I don't think "add every language someone writes a PR for" is a maintainable long-term strategy since already we can see where this is falling down with languages like JS not getting updated... we have no one/few willing to do the hard long-term maintenance work.

Wasn't there an idea to leave only WASM interpreter in TIC-80 and thus have support for any language that supports compiling to WASM without having to maintain each language interpreter in TIC-80?

**Comment by joshgoebel** [comment]
> Wasn't there an idea to leave only WASM interpreter in TIC-80

No, I don't think the goal was ever "WASM only"...
