### ISSUE TITLE
editor command for comment/uncomment for multiple lines

### ISSUE THREAD

**Issue by Sylfir** [nesbox/TIC-80#1192]
Hello, i tried to comment multiple lines of code by selecting text and pressing ctrl+/ but only last line is commented.
TIC version used 0.80.1344

Example: selecting all this text and pressing ctrl+/ does this:
if btn(0) then y=y-1 end
if btn(1) then y=y+1 end
if btn(2) then x=x-1 end
--if btn(3) then x=x+1 end

i suggest it does this instead:
--if btn(0) then y=y-1 end
--if btn(1) then y=y+1 end
--if btn(2) then x=x-1 end
--if btn(3) then x=x+1 end

Thanks for considering this issue.

**Comment by tstopak** [comment]
Implemented in #1363
