### ISSUE TITLE
F9 key captures still image instead of video

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#1194]
In version 0.80 on Debian and Fedora under Xorg, I've noticed that I'm no longer able to record video gifs of gameplay in TIC. Pressing F9 has the same effect as pressing F8. I've confirmed it on a build of latest master, but older builds from a couple months ago seem to also be affected.

**Comment by nesbox** [comment]
Could you please recheck?
I can't reproduce it on Ubuntu.
Thank you.

**Comment by technomancy** [comment]
I've found that this behavior depends on what window manager I use. When I am running TIC under XFCE, pressing F9 immediately shows "Saved video.gif :)" and opens `feh` on the gif file, which has just a single frame. (feh is an image viewer I have installed).

When I use my normal window manager (exwm) it actually hard-crashes the entire process. The red "* REC" indicator shows, but the entire thing becomes unresponsive; I have to use `kill -9` to close the program.

This is on Debian Buster on a fresh build of master from today.

**Comment by nesbox** [comment]
I suspect that your system sends `F9` pressed signal two times, recording starts and immediately stops with only one recorded frame.
Could you pls try to debug keyboard handling?
Somewhere here https://github.com/nesbox/TIC-80/blob/662d266a68ed77d1fa197be90fd62a03ed049b72/src/studio/studio.c#L1523?
