### ISSUE TITLE
editor outline command ctrl+o scrolling not possible

### ISSUE THREAD

**Issue by Sylfir** [nesbox/TIC-80#1195]
Hello, when i have lots of functions in my game and i want to look at the outline (ctrl+o) then i see only the first 17 function and i can not look after that. Scrolling with mouse does not work on the gui list. Moving with keys will jump onto the functions below those who are shown in list but the list will not scroll up with the cursor.

version used 0..80.1344

**Comment by nesbox** [comment]
Added editor outline scrolling here ad6fac4
