### ISSUE TITLE
mouse() coordinates incorrect when mouse moving out of bounds 240x136

### ISSUE THREAD

**Issue by Sylfir** [nesbox/TIC-80#1196]
When i move the mouse cursor outside of 240x136 screen bounds it starts to return clipped values but i think it is not correct.

You can test it for example here https://tic80.com/play?cart=1426
Select line tool. Click somewhere in center for first point. Then just move the cursor for X and Y outside of left and top screen to see what happens. The value returned by mouse() command returns 255 instead of negative. 

I suggest either returning correct negative values so they could be programatically clipped. Or return clipped values 0 for top and left and 239/135 for right and bottom?

**Comment by RobLoach** [comment]
You can see this happen on https://tic80.com/play?cart=456 .

**Comment by Sylfir** [comment]
Yes i know and that is the problem. You see normally the mouse outside the view is eiter negative for example -10 or stays at 0. In this example you provided you can see that the mouse when it goes out of left side jumps suddenly from 0 to 255. I suspect that it is the cutting of number sign to clip the value in range of 8bit (byte) number.

I played with this a little bit in my vector editor and found out this can be "fixed" by software like this:
local mousex,mousey,left,middle,right,scrollx,scrolly=mouse()
if mousex>250 then mousex=0 end
if mousex>239 then mousex=239 end
if mousey>250 then mousey=0 end
if mousey>135 then mousey=135 end

This way the mouse x and y coordinate stays in the viewport when i move the mouse outside of view.

**Comment by Sylfir** [comment]
Oh my bad. I see now that the mouse is stored as BYTE into the ram of console. That's why it is not possible to just change the values to signed integer. Nevermind, the workaround that i posted here is working. I close this issue now.
