### ISSUE TITLE
[3DS v0.80.1344] Crash on Startup

### ISSUE THREAD

**Issue by Kikasuru** [nesbox/TIC-80#1200]
Hello again, I finally got the 3DS version of TIC-80 built, but I have a bug to report.

On an o3DS, TIC-80 will crash upon startup, right around when the console is meant to appear. A crash dump can be found here
[crash_dump_00000000.zip](https://github.com/nesbox/TIC-80/files/5313749/crash_dump_00000000.zip)

EDIT: This happens on both the CIA and 3DSX versions.

**Comment by AnthonyDiGirolamo** [comment]
I'm running into this as well. When I get some time I'll try building the merge commit https://github.com/nesbox/TIC-80/pull/1122 to see if that works and if so bisect.

**Comment by AnthonyDiGirolamo** [comment]
@asiekierka any idea what fix might be needed?

**Comment by Kikasuru** [comment]
> I'm running into this as well. When I get some time I'll try building the merge commit #1122 to see if that works and if so bisect.

Just tested it now, it runs fine as I can see.

**Comment by Kikasuru** [comment]
Alright, I've widdled it down to the crash being added sometime between 6ebf1d2a46afc96856ce0cc0378b53660ecae114 and 2039bd6de67517191cd1da51d0858baca7939399, I'll go ahead and check for anything that might crash the 3DS.

**Comment by Kikasuru** [comment]
I've widdled the error being put in between f6a216240ad58032e88f86489242174e344bfe6e and 2039bd6de67517191cd1da51d0858baca7939399.

**Comment by AnthonyDiGirolamo** [comment]
Nice find! So maybe something to do with the async URL fetching code. I'm new to both tic80 and 3ds development but will take a look.

**Comment by asiekierka** [comment]
Thank you for the research! Looking into it right now - the 3DS uses custom HTTP code to reduce the binary's size.

**Comment by asiekierka** [comment]
This should do it. Thank you again!
