### ISSUE TITLE
Script engine fails when enabling strict-mode javascript

### ISSUE THREAD

**Issue by dvdkhlng** [nesbox/TIC-80#1204]
Hi,

just started with the initial lua example translated to javascript.  Working as expected, however I would prefer to enable the Javascript engine's strict mode.  But when adding "use strict" to the start of the javascript sources, tic-80 cannot run the script, complaining that
```
'function TIC()...' isn't found :(
```

This is the script, it does work as soon as I comment out the "use strict"; statement:

```javascript
// title:  game title
// author: game developer
// desc:   short description
// script: javascript
"use strict";

var t=0
var x=96
var y=24

function TIC(){

	if (btn(0)) y=y-1
	if (btn(1)) y=y+1 
	if (btn(2)) x=x-1 
	if (btn(3)) x=x+1 

	cls(13)
	spr(1+Math.floor(t%60/30)*2,
	    x,y,14,3,0,0,2,2)
	print("HELLO WORLD!",84,84)
	t=t+1
}
```

This is with tic80-v0.80pro-linux.deb on Devuan Beowulf. I verified that the "use strict"; statement itself does work correctly, it does enable error reporting when writing undeclared variables.

cheers,

David

**Comment by nesbox** [comment]
Hi,

we use Duktape JS lib here, don't know does it supports strict mode...

**Comment by dvdkhlng** [comment]
Hi,

thanks for the prompt reply.  After looking through the duktape API I found a solution:  In strict mode any functions do not seem to be added to the global object, but are put in some loal scope.  And TIC80 expects to find TIC() in the global object.  So appending this statement to my "use strict" javascript program does in fact make it work:

```javascript
globalThis.TIC = TIC;
```

(I wonder why I have to use globalThis and cannot use another name for the global object.  Looking at the sources it looks like _TIC80 would be the global object's name, but that does not seem to work).
