### ISSUE TITLE
WASM build does not load on Chrome OS 85.0.4183.133

### ISSUE THREAD

**Issue by MineRobber9000** [nesbox/TIC-80#1207]
I'm using TIC-80 to pass the time in my study hall, and today I decided I'd try 0.80. I downloaded the zip file, extracted it, clicked "Click to Play", and... nada. Nothing. Just a blank screen.

This isn't the first issue I've had with TIC-80 and this Chromebook: 0.70.6 randomly freezes and requires a page reload. Because it's a domain chromebook, I can't use Dev Tools, but I'll try some window.onerror shenanigans later today and let you know if that turns up anything.

**Comment by nesbox** [comment]
Hi, Wasm build works only through a web server, please run one or upload exported .zip to the itch.io for example.
Don't run `index.html` file directly.
Thank you.
