### ISSUE TITLE
[openSUSE] Trying to package for openSUSE, can I use installed SDL2 instead of third-party?

### ISSUE THREAD

**Issue by kevinsmia1939** [nesbox/TIC-80#1211]
Hello,

I am trying to create tic-80 package for openSUSE Tumbleweed.
I encounter this error which show that it need SDL2 development files.
However, I have include SDL2 development files in the dependencies. So I think that it does not look for locally installed SDL or other third-party files. Are there cmake flags that I can tell it to look into locally installed dependencies? 

Thank you.

Repository:  https://build.opensuse.org/package/show/home:andythe_great/tic-80
Error log: https://build.opensuse.org/package/live_build_log/home:andythe_great/tic-80/openSUSE_Tumbleweed/x86_64
```
[   53s] CMake Error at CMakeLists.txt:362 (add_subdirectory):
[   53s]   The source directory
[   53s] 
[   53s]     /home/abuild/rpmbuild/BUILD/TIC-80-0.80.1344/vendor/sdl2
[   53s] 
[   53s]   does not contain a CMakeLists.txt file.
[   53s] 
[   53s] 
[   53s] CMake Error at CMakeLists.txt:524 (add_subdirectory):
[   53s]   The source directory
[   53s] 
[   53s]     /home/abuild/rpmbuild/BUILD/TIC-80-0.80.1344/vendor/curl
[   53s] 
[   53s]   does not contain a CMakeLists.txt file.
[   53s] 
[   53s] 
[   53s] CMake Error at CMakeLists.txt:567 (add_subdirectory):
[   53s]   The source directory
[   53s] 
[   53s]     /home/abuild/rpmbuild/BUILD/TIC-80-0.80.1344/vendor/zip
[   53s] 
[   53s]   does not contain a CMakeLists.txt file.
```

**Comment by nesbox** [comment]
It's not possible at the moment but we could add a CMake option for this.
Thanks.

**Comment by nesbox** [comment]
Also, pls try to initialize submodules `git submodule update --init --recursive`

**Comment by epassaro** [comment]
Hi @nesbox 

If I understand correctly:

- GitHub does not include submodules in source code releases
- The openSUSE Build Service (OBS) works offline so it's not possible to fetch submodules

A solution could be to make a "real" source code release (not just the automatic one) including submodules via GitHub Actions.

**Comment by nesbox** [comment]
Yes, we could release all the sources with submodules, will try with the next release.
