### ISSUE TITLE
mouse cursor sprite displaying incorrectly with CRT filter

### ISSUE THREAD

**Issue by nequ16** [nesbox/TIC-80#1212]
I noticed that the mouse cursor sprite is being drawn incorrectly when using a CRT filter.
It also seems that the sprite that is set as a mouse cursor is actually rendering stretched to the whole screen size but is only visible in a 8x8 square around the mouse position.

![bug](https://user-images.githubusercontent.com/72892369/96052003-55ed8200-0e85-11eb-80fd-1bab359a69e7.gif)

**Comment by nesbox** [comment]
Already fixed on the latest dev build.
Thank you.
