### ISSUE TITLE
Please add a export for web

### ISSUE THREAD

**Issue by MasterFoof** [nesbox/TIC-80#1216]
Please add export for web. I code on chromebook I am not really able to download anything cause of chromeOS and I dont want to install linux. If you add a web export then I feel like this would be better than pico-8.

**Comment by nesbox** [comment]
Hi, have you tried `export html` command?
Or it doesn't work?

**Comment by MasterFoof** [comment]
when I do that it just says: Web/Arm version dosent support html or native export

**Comment by RobLoach** [comment]
Ah, you mean export for web, from the web. Wasn't sure which client you were on. Makes sense.

**Comment by MasterFoof** [comment]
oh lol

**Comment by MasterFoof** [comment]
If I download the app can I export on that?

**Comment by nesbox** [comment]
Added html export for web here 41469fe
![image](https://user-images.githubusercontent.com/1101448/99987587-b398b680-2dc1-11eb-864b-9544202803f0.png)

**Comment by nesbox** [comment]
I think I could add all types of export for web: `html win linux mac`.

**Comment by nesbox** [comment]
Added `export <html win linux rpi mac> <file>` command to all the clients e0940e0
