### ISSUE TITLE
[3DS] Sharp linear (prescale) filter 

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [nesbox/TIC-80#1219]
Hello! I'm hoping it's possible to add a prescale 2x or 3x screen filtering option to the 3ds port. Right now there seems to be: pixel perfect, nearest neighbor, and linear scaling. 

Something similar to this would be ideal:
https://retropie.org.uk/forum/topic/12387/a-simple-sharp-pixel-shader-config-for-retropie-with-integer-prescale-and-no-pixelwobble

As far as I understand it the original screen is integer scaled 2x or 3x with nearest neighbor scaling. Then at the larger size a linear or bilinear filter is applied. Then the screen is scaled back down to the desired screen resolution (using nearest neighbor).

This would greatly improve readability at full screen. @asiekierka is this a possibility? Thank you for all your work on the 3ds port, it really is amazing!

**Comment by asiekierka** [comment]
@AnthonyDiGirolamo @Kikasuru Could you please try out [this build](https://asie.pl/files/tic80-3ds-20201026.zip)? It replaces both nearest and linear filters with prescaled linear filters, and enables 800x240 "wide" mode on supported consoles (any but "old" 2DS).

**Comment by AnthonyDiGirolamo** [comment]
Wow the results are really good! Took a photo but it's much more noticeable in person. Bottom is the old linear filter, top is the new build.

![PXL_20201026_144334779](https://user-images.githubusercontent.com/37681/97187553-c5a21d80-175f-11eb-9b72-1d6b83d5fdb3.jpg)
