### ISSUE TITLE
In HTML exported games, all unused buttons on Xbox One controller open/close the TIC menu

### ISSUE THREAD

**Issue by jf1x** [nesbox/TIC-80#1220]
Is there a way to disable this behaviour, or maybe bind this function just to the Menu button on the controller? Right now it's very easy to accidentally hit one of these buttons while playing the game and restart or close it.

**Comment by nesbox** [comment]
There is no way, we need to fix it.

**Comment by nesbox** [comment]
will be fixed with #210

**Comment by nesbox** [comment]
fixed here 9ec7eb7
