### ISSUE TITLE
Support for newer ECMAScript/JavaScript versions

### ISSUE THREAD

**Issue by novachief101** [nesbox/TIC-80#1223]
Is support for ES6 (ES2015) or above possible? I'm kind of annoyed of using ES5.
Edit:
Just noticed `const` is the only ES5+ thing supported.

**Comment by novachief101** [comment]
I'm using [Babel](https://www.babeljs.io) for now

**Comment by nesbox** [comment]
We use Duktape https://github.com/svaarala/duktape as JS engine and it supports ES5 only.

**Comment by RobLoach** [comment]
Like Babel, you can use a bundler. Here are two options...
- https://github.com/chronoDave/tic-bundle
- https://github.com/RobLoach/tic80-js
