### ISSUE TITLE
music() parameter changed?

### ISSUE THREAD

**Issue by skz1024** [nesbox/TIC-80#1226]
0.70.6 music function
music
music [track=-1] [frame=-1] [row=-1] [loop=true] [sustain=false]

Parameters:
track : the id of the track to play from (0..7)
frame : the index of the frame to play from (0..15)
row : the index of the row to play from (0..63)
loop : loop music or play it once (true/false)
sustain : sustain notes after the end of each frame or stop them (true/false)

but 0.80.4 music function
loop parameter required number. not use true or false.
The rest of the parameters remain the same.
this music function changed? please edit wiki data.
![캡처990](https://user-images.githubusercontent.com/66052782/97660243-5193ac80-1ab4-11eb-81d0-2d244ca7f1a2.PNG)

**Comment by nesbox** [comment]
Fixed here 3f14c65.
Thank you for the report.
