### ISSUE TITLE
Feature: Add colors to text with control characters (like Commodore 64)

### ISSUE THREAD

**Issue by SDMelipone** [nesbox/TIC-80#1227]
On Commodore 64, you can enter colors as characters. This would be convenient for color changes within strings, especially when printing lots of text to screen. Here's an example GIF.
![recording](https://user-images.githubusercontent.com/70553347/97785706-14dfb800-1b7d-11eb-8bf8-df48a7a799e9.gif)
In this example, Ctrl+number creates the characters before the 4, 5, 5 and sets a specific color.

**Comment by joshgoebel** [comment]
It'd also be pretty easy to do this with a small utility function I would think.

**Comment by nesbox** [comment]
Agreed with @joshgoebel it can be easily done with small utility function.
For example:
``` lua
function printc(str,x,y)
	local c=0 i=1 s=0
	while i<=#str do
		s=str:sub(i,i)i=i+1
		if s=='#'then c=tonumber(str:sub(i,i),16)i=i+1
		else print(s,x,y,c)x=x+6 end
	end
end

cls()
printc('#2H#3E#4L#5L#6O #7W#8O#9R#AL#BD#C!',10,10)
function TIC()end
```
![image](https://user-images.githubusercontent.com/1101448/125278106-f5f41100-e31a-11eb-94da-06b75abc2bab.png)
