### ISSUE TITLE
Problem with insertion of GTK-3.0 includes path in Cmake

### ISSUE THREAD

**Issue by Popolon** [nesbox/TIC-80#1230]
I encountered a problem with GTK-3.0 detection, on  Archlinux ARM, but I believe it's probably a dependency missing that misconduct the test.

I used the [same PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tic-80-git) than the default one for ArchLinux x86.
<pre>
    cmake -DBUILD_PRO=true ..
    make -j4
</pre>

It compiled fine on x86 but didn't added the include path in build/CMakeCache.txt file, so during the make, an error <gtk/gtk.h> appeared. I copy pasted what x86 version detected to ARM version, made a make and everything worked fine.
Where could I find the detection error ? the libs names was correctly put in this file, only the include path missed . The variables empty was GTK_CFLAGS:INTERNAL, GTK_INCLUDE_DIRS:INTERNAL, GTK_STATIC_CFLAGS:INTERNAL and GTK_STATIC_INCLUDE_DIRS:INTERNAL

Just for information, TIc-80 works fine in full screen 800×600 on a very slow AllWinner-a20 (2*ARM Cortex-A7@1GHz + GPU ARM Mali-400, using Lima open source driver), on a dev lowpower board. I used XFCE with disabled compositing.

**Comment by nesbox** [comment]
Hi,

we detect Gtk libs here:
https://github.com/nesbox/TIC-80/blob/3f14c65dff0cdcf08fe59a0c1ec96bbcf86dd494/CMakeLists.txt#L145

and here we add include path:
https://github.com/nesbox/TIC-80/blob/3f14c65dff0cdcf08fe59a0c1ec96bbcf86dd494/CMakeLists.txt#L666

**Comment by Popolon** [comment]
Sorry I didn't have time to investigate further and the detection problem is not solved.

**Comment by nesbox** [comment]
I'm going to remove GTK dependency at all soon.
Thanks.
