### ISSUE TITLE
portrait mode

### ISSUE THREAD

**Issue by dosuserx** [nesbox/TIC-80#1231]
tic 80 on android would work so much better if it had a portrait mode, a mode where the windows of the editors are rotated and rearrangeed when the phone is turned on upright. there's no reason desktop couldn't benefit from portrait mode either (example: make it a side bar while reading a tutorial.) it would also make the Android version look less empty. sorry in advance if this is the wrong place for such a request.

**Comment by nesbox** [comment]
TIC will stay in landscape mode only.
wontfix, sorry

**Comment by dosuserx** [comment]
if i make a fork with portrait mode will you try it out to see if I'm not
totally crazy? i think pc users would really love portrait mode.

**Comment by nesbox** [comment]
Of course, I'll try to see :)

**Comment by Kikasuru** [comment]
I could see this used well for Shmups! Can't wait to see that fork @dosuserx!
