### ISSUE TITLE
Possibility of incorporating NES white noise mode 1 for electric and metallic alike sound effects

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1232]
Could it be possible that in a future update they will add this feature to TIC-80? or something similar

Noise output occurs when the waveform is empty (zero-filled). For this mode it occurred to me that could be activated when the waveform is full (full-filled) instead

**Comment by nesbox** [comment]
It's possible and I think we could play 16 different noises for every full-filled waveform line, not sure, have to recheck.
Info from NESdev wiki (https://wiki.nesdev.com/w/index.php/APU#Noise_.28.24400C-400F.29):
```
If bit 7 of $400E is set, the period of the random bit generation is drastically shortened, 
producing a buzzing tone (e.g. the metalic ding during Solstice's gameplay).
The actual timbre produced depends on whatever bits happen to be in the generator when it is switched to periodic, 
and is somewhat random.
```

**Comment by nesbox** [comment]
Added 16 different types of noise here 23a6e7a697df39794c364e776327071e1804a986
Noise plays now for every full-filled waveform line.
To check it, please paste this waveform `cccccccccccccccccccccccccccccccc` for example, and play

![video12](https://user-images.githubusercontent.com/1101448/133431093-02f97171-924d-4767-befe-f2e107eb5580.gif)
Thank you for the idea :)

**Comment by StinkerB06** [comment]
Wouldn't this break compatibility with existing carts?

There are 2 bits left in the SFX format, so here are possible suggestions:
- Use those bits to specify one of 4 noise types. Allocate a byte of the RAM to store the noise type for each of the 4 channels. This is not as superior as what's already present in the current dev version.
- Better, use one of those bits as a flag to enable variable noise (instead of flat-line waveforms that produce nothing but pops on volume changes). Use the upper nibble of 0x0FFFF as variable noise enable flags for each of the 4 channels.

**Comment by Kyuchumimo** [comment]
@StinkerB06 This does not affect the compatibility with previous game carts at all, nor does it affect RAM. Its use involves flattening the waveforms. This new feature is called periodic noise.

https://user-images.githubusercontent.com/74131798/141601704-9283e6a8-d245-4bdc-803e-b8724160e611.mp4

**Comment by StinkerB06** [comment]
> @StinkerB06 This does not affect the compatibility with previous game carts at all, nor does it affect RAM. Its use involves flattening the waveforms. This new feature is called periodic noise.

I ***know*** you need to flatten wavetables to get noise output. What I'm saying is this change could break compatibility with existing carts that play flat-line wavetables (that aren't an all-zeroes flat line) in *any* way, and they don't expect that noise output would happen *at all* for those other flat lines. It certainly might break software wavetable synthesis, a crucial part of the [Fallspire](https://tic80.com/play?cart=806) sound engine.

**Comment by Kyuchumimo** [comment]
I don't see any particular change from the Fallspire sound engine. TIC-80 0.90.1723 vs TIC-80 1.0.1770-dev Pro

https://user-images.githubusercontent.com/74131798/141653879-c3703e4b-c908-4062-9c1a-ccbfe5517e80.mp4

**Comment by Kyuchumimo** [comment]
The only carts that manipulate the waveforms and that in quiet parts could be affected are the following:

TIC-ROLL:
https://tic80.com/play?cart=1754
MERCEDES BENZ:
https://tic80.com/play?cart=2284

In the MERCEDES BENZ cart, there are parts where there is audible noise, and this even and using TIC-80 v0.90 which has not yet implemented the periodic noise

**Comment by nesbox** [comment]
@StinkerB06 you were right
A lot of problems with the compatibility and it seems we have to use one of your suggestions.
Thanks for that

**Comment by nesbox** [comment]
Reduced to two types of noise for the backward compatibility 8dbeba661e60e677ac31ddad7dc3bf729a41aa36
```
0x0-standart noise
0xf-periodic noise
```
