### ISSUE TITLE
Using the row attribute other than [Row=-1] in the music() command adds a small pause or silence.

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1235]
Code example to jump from row 32 to row 32 using music() at the same period of time:

function TIC()
t=t+1
if t%(640)==0 then music(0,-1,-1,false) end
if (t+(320))%(640)==0 then music(0,-1,32,false) end
end

For this to work you need to write music on track 0, frame 0 fixed to tempo 150, speed 10 and 64 rows.

**Comment by nesbox** [comment]
I don't understand what are you doing in the code?
Pls explain.
Sorry
