### ISSUE TITLE
UP button always pressed when a program is running

### ISSUE THREAD

**Issue by Chosolino** [nesbox/TIC-80#1238]
Everytime when i run a program the Up Button keeps pressed. I already tried to remap the Up button to another key but this bug persists.
![bug 1](https://user-images.githubusercontent.com/45438416/99081473-a00b7580-25a1-11eb-96bb-0b7194d2c4a4.gif)

**Comment by RobLoach** [comment]
Do  you have a gamepad plugged in? Is it being pushed up or something? Try configuring it in your OS... What OS you on?

**Comment by Chosolino** [comment]
> Do you have a gamepad plugged in? Is it being pushed up or something? Try configuring it in your OS... What OS you on?

I'm using Windows 10. I don't have a gamepad connected, but a few weeks ago I was using a Dualshock 4 with DS4Windows.
  This problem is only happening when the TIC-80 is running a program, all of the editor's tabs are working fine.

**Comment by nesbox** [comment]
Seems you have a device that generates signals for UP gamepad button :)
Could you please disconnect your mouse, for example, and check?
Thank you.

**Comment by Chosolino** [comment]
I had a virtual joystick installed and it was recognizing the up button pressed all the time. 
Thanks @nesbox and @RobLoach , helped me a lot. =D
