### ISSUE TITLE
When compiling TIC-80 with GCC Mingw-w64 it (mingw64) adds additional DLL dependencies

### ISSUE THREAD

**Issue by KatPurpy** [nesbox/TIC-80#1240]
The resulting TIC-80 executables (i compile tic80, tic80-sokol, utils and players for test) depends on these dlls:

libwinpthread-1.dll
libstdc++-6.dll
libgcc_s_seh-1.dll

Solution? Statically link standard C library into executables.

What i did to solve my problem is adding this line in the beginning of the cmake line
`set(CMAKE_EXE_LINKER_FLAGS "-static")`

Please add this line in the cmake file or something similar so it would add C library statically no matter what.

**Comment by nesbox** [comment]
Fixed here c3b5d8a
