### ISSUE TITLE
Web export is working incorrectly

### ISSUE THREAD

**Issue by PecheCop** [nesbox/TIC-80#1245]
I have downloaded 8 Bit panda (https://tic80.com/play?cart=188) and tried to 'export html' it. 
It said it was a success
![screenshot](https://user-images.githubusercontent.com/32987297/99214643-8ca31900-27f2-11eb-843c-f3f8abf7f314.png)

I unpacked the archive and tried to run it in my browser. 
It says 'click to play' but nothing happens when you click. Except for the error in the web console
![screenshot](https://user-images.githubusercontent.com/32987297/99215369-7dbd6600-27f4-11eb-83f6-27817c149fc3.png)

Export also do not work in Super Mario Bros? (https://tic80.com/play?cart=223)

OS - Linux amd64
Browser - Firefox 80.0
TIC80 - 0.90.1417-dev Pro (latest at this moment)

**Comment by PecheCop** [comment]
I tried other browsers too (Chromium, Pale Moon) and the error remained

**Comment by nesbox** [comment]
It works via webserver only, try to upload provided `.zip` to the itch.io or similar site.
Or run your own webserver.
