### ISSUE TITLE
Add benchmark demos for every supported script.

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1246]

**Comment by nesbox** [comment]
Added bunnymarks for lua/js/wren/squirrel/moon 227ef9a

**Comment by Rabios** [comment]
Hey @nesbox , Thanks for being interested and submitted my Lua code!

Hope soon to work on the fennel version of the bunnymark if i have time, Then gonna make issue so you test and submit it! 😄

**Comment by nesbox** [comment]
Looking forward to it, thanks.
