### ISSUE TITLE
Make TIC work more like a compiler.

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1247]
We have to pass console commands as command-line arguments and process them without running UI.

**Comment by nesbox** [comment]
1597f7b commit:
- removed all the native file save/load dialogs
- temporary removed code/sprites/map injection and live reloading
- added ArgParse lib to parse command-line arguments as a submodule (https://github.com/cofyc/argparse), not it looks like:
``` bash
$ ./tic80 -h
Usage: tic80 [cart] [options]

TIC-80 startup options:

    -h, --help        show this help message and exit
    --skip            skip startup animation
    --nosound         disable sound output
    --fullscreen      enable fullscreen mode
    --surf            run SURF mode to explore carts
    --fs=<str>        path to the file system folder
    --scale=<int>     main window scale
    --crt             enable CRT monitor effect

```

**Comment by nesbox** [comment]
Added `cmd` command-line option, you can pass commands directly to the Console.
For example, with the command `tic80 --skip --cmd="load game.tic & export html game.zip & exit"` you will load cart, export HTML and exit:
``` bash
$ ./tic80 --skip --cmd="load bpp & export html game & exit"

 TIC-80 tiny computer 0.90.1432-dev Pro
 http://tic80.com (C) 2020

 hello! type help for help

>load bpp
cart bpp.tic loaded!
use RUN command to run it

>export html game
GET /export/0.90/html.zip [100%]
exporting html...

game.zip exported :)
>exit
>
```

**Comment by borbware** [comment]
How about a headless mode to run console commands without opening a TIC-80 window?

That would make automating the creation of different native builds more painless!

**Comment by nesbox** [comment]
Added headless mode to run without main window here 29aa5fd
```
usage: 
tic80 --cli --cmd="load game.tic & export music track1.wav id=1 & exit"
```
Thanks.
