### ISSUE TITLE
Let javascript be interpreted by browser in html version of TIC-80

### ISSUE THREAD

**Issue by KatPurpy** [nesbox/TIC-80#1248]
As far as I can tell javascript is interpreted by duktape library that is also supplied with html export. So... **javascript is interpreted by javascript bytecode**

I suggest to create a <script> tag in the game's iframe and dump javascript code into it when the cartridge is supposed to start.

About other languages? A utopian option would be converting other languages into javascript before running the game but keep original source code in interface. So javascript "compilation" would happen on each time the cartridge is run.

**Comment by KatPurpy** [comment]
I am entirely not sure about other languages this is why i said it is utopian option

**Comment by RobLoach** [comment]
To achieve this, we would implement an [emscripten API](https://emscripten.org/) around the TIC-80 API. Sounds like you're looking to do something similar to the CLI `-code` parameter to inject code on cart load.

```
tic80 -code mycode.js cart.tic
```

Having it as an iframe is sub-optimal. You don't have the ability to inject scripts across iframe domains. What you're trying to do is have something like this....

```
<script>
TIC.onload(function() {
  const options = {
    code: "// Some code goes here"
  }
  TIC.load("/assets/cart.tic", options)
  TIC.run()
});
</script>
```

Even that seems very hacky. It might be easier for you to put together a JavaScript utility that would build the cart binary given some code. Here's the spec for what the cart binary looks like:
https://github.com/nesbox/TIC-80/wiki#specification

**Comment by nesbox** [comment]
@KatPurpy wants to run a game JS script directly in the browser without the Duktape layer, I think it's not worth it, to maintain a strange bridge to only one script. Seems it's a really utopian option :)
