### ISSUE TITLE
Debian Linux TIC-80 won't run on raspbberry pi

### ISSUE THREAD

**Issue by RaspberyPye** [nesbox/TIC-80#1249]
Basically the title, I dont know whether it is intentional that the .deb would run on Raspberry pi or not, but if yes it doesnt, and if no, is there a plan to do this?

**Comment by nesbox** [comment]
We already have rpi build (not released).
Please, go to the `Actions` section https://github.com/nesbox/TIC-80/actions, select any workflow and download `tic80-rpi` artifact.
Thank you.
