### ISSUE TITLE
Multiple resolution support

### ISSUE THREAD

**Issue by ambyra** [nesbox/TIC-80#1250]
The TIC80 resolution was set (I assume) for the Pocket CHIP project, which is now dead. GameShell, a popular TIC80 platform uses a different resolution/aspect. The upcoming DevTerm from clockworkpi.com is on another resolution. The new gameboy from Analogue uses yet another resolution. 

Point made, it would be nice to have a tag to set the target platform. To maintain compatibility, carts would default to current resolution/specs. 

DevTerm, laptop monitors are widescreen. Text editing would benefit greatly. It would be nice not to have to switch back and forth from a text editor to TIC. QBASIC offered multiple screen modes, had a really nice resolution for text editing. TIC text editing is pretty cramped. 
![3C5F1C4D-C9E9-4FD6-ABFD-CF52C8DFF9B6](https://user-images.githubusercontent.com/10302044/99829690-d86b0080-2b19-11eb-819d-e886fef07f0c.jpeg)
![Uploading 54EDB16D-2AB7-4B86-9660-8AD7C610D0A6.jpeg…]()

**Comment by RobLoach** [comment]
Having platform definitions can result in quite a bit of micro-management to maintain. Could you expand on how you see developers making use of it?

One example where we run into this is with libretro and RetroArch. libretro cores provide their own screen resolution, but then RetroArch scales the resolutions either using integer scaling, or a scaler, while keeping the aspect ratio in tact.

**Comment by nesbox** [comment]
We are not going to change `240x136` size, it's a limitation, sorry.
It will be another fantasy console with a different resolution in this case.

**Comment by ambyra** [comment]
These handheld platforms have fixed resolutions. There would have to be a profile for each one. I’m guessing there are a lot of hard coded values/functions, mmap adjustments, that would make this too difficult. Maybe this falls in the realm of ‘port’ and not ‘feature’.

![9A304454-D022-474D-B200-042BC237C075](https://user-images.githubusercontent.com/10302044/99848627-58539380-2b37-11eb-90a2-c7b6d7215b14.jpeg)

**Comment by ambyra** [comment]
As a feature request @nesbox would you be willing consolidate the hard coded values into one file, so others can port to various handhelds? Or, it would be good to know at least which files/functions have resolution specific code.

**Comment by nesbox** [comment]
They already in one file, please look at https://github.com/nesbox/TIC-80/blob/1d1998a384c370c4d3fc124a32b64905d9b09d7b/include/tic80.h#L32

**Comment by ambyra** [comment]
Changing these defs to 320x240 (https://forum.clockworkpi.com/t/run-tic80-on-gs/1121)  breaks the sprite and map editors on 0.9. The code editor looks verrry roomy though :) 


<img width="494" alt="Screen Shot 2020-11-23 at 18 07 07" src="https://user-images.githubusercontent.com/10302044/100033132-ca85db80-2db6-11eb-9f19-a089416b471d.png">

**Comment by ambyra** [comment]
<img width="675" alt="Screen Shot 2020-11-23 at 18 09 28" src="https://user-images.githubusercontent.com/10302044/100033258-15075800-2db7-11eb-98b8-b0aae0f74837.png">

**Comment by nesbox** [comment]
I think it can be closed, we are not going to change the resolution in the near future.
Sorry.
