### ISSUE TITLE
Struggling to operate remap function in Squirrel

### ISSUE THREAD

**Issue by RaspberyPye** [nesbox/TIC-80#1251]
Hi, I have had a look at the docs and seen the remap function and was hoping to use it in my squirrel project. I can't seem to get it to work, for example:

```
function DrawWorld()
	{
		cls();
		map(mapx,mapy,30,17,0,0,-1,1,WorldAni);
	}
	
function WorldAni(tile,x,y)
{
	if (tile==2)
	{
		return 3;
	}
}

```

If i am understanding the docs right this should change all tiles with id 2 to id 3, but that doesnt happen,
what am i missing?

**Comment by RobLoach** [comment]
Did you get it to work?

**Comment by RaspberyPye** [comment]
Yes, in squirrel, when returning multiple values, you must return them as an array. Doing:
```
function DrawWorld()
	{
		cls();
		map(mapx,mapy,30,17,0,0,-1,1,WorldAni);
	}
	
function WorldAni(tile,x,y)
{
	if (tile==2)
	{
		return [3];
	}
}
```

works.
