### ISSUE TITLE
Squirrel doesn't have its math library

### ISSUE THREAD

**Issue by RaspberyPye** [nesbox/TIC-80#1252]
using squirrel, you cannot referance math.foo() to get squirrels built in math library, will this be implemented?

**Comment by nesbox** [comment]
Unfortunately, I'm not familiar with the Squirrel lang, only if someone will add math lib via pull request.

**Comment by RobLoach** [comment]
I think the math library is registered? I'm able to call `rand()` and get a number... http://www.squirrel-lang.org/squirreldoc/stdlib/stdmathlib.html

https://github.com/nesbox/TIC-80/blob/master/src/api/squirrel.c#L1362

**Comment by joshgoebel** [comment]
@RaspberyPye Could you give a specific [real] code example of a math function that is failing for you?

**Comment by RobLoach** [comment]
Yeah, I think is in place already....

```
static void squirrel_open_builtins(HSQUIRRELVM vm)
{
    sq_pushroottable(vm);
    sqstd_register_mathlib(vm);
    sqstd_register_stringlib(vm);
    sqstd_register_bloblib(vm);
    sq_poptop(vm);
}
```

**Comment by joshgoebel** [comment]
@RobLoach Yeah I saw your comment, just asking for a reproducible example so we can confirm for sure... and close this (or not). :-)

**Comment by RobLoach** [comment]
It's not `math.foo()`, it's just `foo()`....

``` squirrel
// script: squirrel
function TIC() {
  cls(2)
  local stuff = ceil(30.55)  
  print(format("Hello: %i", stuff))
}
```

**Comment by joshgoebel** [comment]
If one uses Squirrel "proper" do they have to use the `math` namespace?

**Comment by joshgoebel** [comment]
Did my own googling: https://developer.electricimp.com/squirrel/math

> Squirrel’s math library provides a set of mathematical functions you can incorporate into your agent or device code. _Unlike standard Squirrel_, imp Squirrel requires that all of these functions are prefixed with math., for example:

So some variants do seem to namespace it but evidently "standard Squirrel" does not, so I'd say the existing behavior is correct and we can close this issue.
