### ISSUE TITLE
better clipboard support

### ISSUE THREAD

**Issue by lolbinarycat** [nesbox/TIC-80#1254]
There are 2 problems with clipboard support currently
1. pasting into/copying from the command line is unsupported.
2. pasting from the X primary selection is unsupported (select -> middle click).

**Comment by SuperPupperDoggo** [comment]
the web version also does not seem to support it

**Comment by nesbox** [comment]
Added console text selection, console clipboard, middle click d33e444
![console](https://user-images.githubusercontent.com/1101448/115587096-f198f880-a2d5-11eb-92ec-97fd7fd940b0.gif)
