### ISSUE TITLE
CRT effect in mac

### ISSUE THREAD

**Issue by u254254** [nesbox/TIC-80#1255]
CRT effect showing not good in Mac.
<img width="1136" alt="스크린샷 2020-11-26 오후 8 59 03" src="https://user-images.githubusercontent.com/72965213/100348907-f610fc00-302a-11eb-8967-ddd8f48ddd5b.png">

**Comment by jminor** [comment]
That looks like the shader isn't accounting for your computer's retina display. I saw the same thing a while back. In a build of TIC-80 from the current main branch (as of 2021-04-29), this seems to have been fixed.

**Comment by nesbox** [comment]
Yes, seems it's fixed.

**Comment by nesbox** [comment]
The latest version was released without SDL GPU lib support because a lot of people complain about it.
If you need the CRT pls download `tic80-windows-sdlgpu` version here https://nightly.link/nesbox/TIC-80/workflows/build/master
