### ISSUE TITLE
Emulationstation support

### ISSUE THREAD

**Issue by jlbrd** [nesbox/TIC-80#1258]
Hi, I am a user of Rg351p with ArkOS. I asked on https://github.com/christianhaitian/arkos/issues/36 if it is possible to integrate TIC-80 into the list of built-in emulators. Can you view the answer given in this issue? It is said that TIC-80 must first be integrated into Emulationstation. Thank you

**Comment by nesbox** [comment]
Hi,
Does ArkOS support the Retroarch?
because TIC already runs on it https://docs.libretro.com/library/tic80

**Comment by RobLoach** [comment]
You can add it through the EmulationStation configs....

``` xml
<system>
  <name>tic80</name>
  <fullname>TIC-80</fullname>
  <path>/path/to/carts</path>
  <extension>.tic</extension>
  <command>tic80 %ROM%</command>
  <platform>tic80</platform>
  <theme>tic80</theme>
</system>
```

As nesbox mentioned, the tic80 core for RetroArch is another option if you can't compile TIC-80 itself on ArkOS.

**Comment by jlbrd** [comment]
Just to tell you that christianhaitian added tic80 in ArkOS and it works perfectly. Thank you all for your work. The issue may be closed.

**Comment by jlbrd** [comment]
Resolved
