### ISSUE TITLE
(0.90.1460-dev) Importing Map Bug

### ISSUE THREAD

**Issue by MasterNama2008** [nesbox/TIC-80#1260]
I loaded `map. tic` on the cartridge.
When type `import map map.tic` command result will be corrupted garbage.

**Video:**
![bug map import](https://user-images.githubusercontent.com/71924055/100766130-51256300-341e-11eb-84da-1877510d39c2.gif)

**Comment by nesbox** [comment]
I don't think it's a bug, you're importing map data as a whole tic cart, 
try to call `export map map.dat` and then load another cart and call `import map map.dat`
