### ISSUE TITLE
Command line arguments do not work anymore in the latest commit

### ISSUE THREAD

**Issue by KatPurpy** [nesbox/TIC-80#1267]
I use `tic80/tic80.exe cart.js -code code.js` to test my code changes but since I had upgraded to latest version of TIC-80 now the console shows nothing and returns **error code 1**

**Comment by nesbox** [comment]
Dev version has new command-line arguments since #1247
```sh
$ ./tic80 -h
Usage: tic80 [cart] [options]

TIC-80 startup options:

    -h, --help        show this help message and exit
    --skip            skip startup animation
    --nosound         disable sound output
    --fullscreen      enable fullscreen mode
    --fs=<str>        path to the file system folder
    --scale=<int>     main window scale
    --cmd=<str>       run commands in the console
```

So, to embed the code to the cart you could call `tic80 --cmd "load cart.js & import code code.js"` but code importing was removed, I still doubt do we really need code import when you can open `cart.js` in any text editor?

**Comment by KatPurpy** [comment]
The reason why I want you to keep code importing is because I have somewhat of JavaScript build pipeline where JavaScript code is built from multiple little source files as editing 2k long file is kind of... frustrating. I do not want to be forced to use typescript as it may produce additional bugs and possibly errors that TIC-80 reports may be incorrect leading into harder debugging

![изображение](https://user-images.githubusercontent.com/43522532/101767282-0ded8300-3af5-11eb-8d22-0ae1c7455d86.png)

**Comment by nesbox** [comment]
I see, I'll try to restore `import code ...` command soon then.
Thanks.

**Comment by nesbox** [comment]
I restored `import code ...` command in the console here 2c542f9
Try to use `tic80 cart.js --cmd "import code code.js"`, also, use `--fs <path>` to assign the path to the TIC's filesystem, use `--fs .` for the working dir.
Thanks for the report.
