### ISSUE TITLE
Zlib compression does not seem to work in 0.80+ versions of TIC-80

### ISSUE THREAD

**Issue by KatPurpy** [nesbox/TIC-80#1268]
If I make possibly more than 64k of JavaScript then loading such cartridge will result in TIC-80 totally ignoring code and saying "the code is empty!"
![изображение](https://user-images.githubusercontent.com/43522532/101766310-a97df400-3af3-11eb-87f5-90d9511eb2e9.png)

What is more weird that CART2PRJ utility will also ignore code resulting in project cart's code part being empty but PRJ2CART **will** embed code into the cartridge

What is even more weird that loading project directly (for example by dragging project file on TIC-80 icon) makes the game load just fine

Here are the test carts I used to check if the bug wasn't game specific, ~~they contain a lot of pain~~: [tic80_compression_issue.zip](https://github.com/nesbox/TIC-80/files/5672325/tic80_compression_issue.zip)

**Comment by nesbox** [comment]
Reproduced, it's weird.
Thanks.

**Comment by KatPurpy** [comment]
Also I would like to note that exporting on TIC-80 (latest commit) that was fed big project file will result in **native TIC-80 with the default hello world cartridge**

**Comment by nesbox** [comment]
Ahh, all is ok, you have to use `prj2cart` instead `cart2prj`.
You load `.js` as '.tic' file and convert it to `.tic` file and got cart with garbage :)

**Comment by nesbox** [comment]
> Also I would like to note that exporting on TIC-80 (latest commit) that was fed big project file will result in **native TIC-80 with the default hello world cartridge**

What OS are you exporting? just tested `export win game.exe` and all is ok.

**Comment by KatPurpy** [comment]
> 
> 
> Ahh, all is ok, you have to use `prj2cart` instead `cart2prj`.
> You load `.js` as `.tic` file and convert it to `.tic` file and got cart with garbage :)

I had miswritten util names but when I exported using prj2cart

**Comment by KatPurpy** [comment]
> What OS are you exporting? just tested `export win game.exe` and all is ok.

Windows 64 bit, TIC-80 compiled with MinGW

**Comment by KatPurpy** [comment]
It seems to be the main problem was that I mixed up previous version utils with current TIC-80...

But now i am having other problem. Latest TIC-80 exports hello world if it was started using project file.  The version I was using did not have such bug (0.90.1400)

**Comment by nesbox** [comment]
The problem was with non-ASCII chars in the path, I fixed it here a42e9f3.
Please, try to `export win game.exe` now.
Thanks.

**Comment by KatPurpy** [comment]
The bug seems to be gone. Thanks.
