### ISSUE TITLE
tic80 -h command outputs to nowhere unless redirected

### ISSUE THREAD

**Issue by KatPurpy** [nesbox/TIC-80#1269]
OS: Windows

Problem: when executing `tic80 -h` it seems to output nothing BUT if I write`tic80 -h >>OUT.TXT` then file OUT.TXT appears with output exactly what's expected

```
Usage: tic80 [cart] [options]

TIC-80 startup options:

    -h, --help        show this help message and exit
    --skip            skip startup animation
    --nosound         disable sound output
    --fullscreen      enable fullscreen mode
    --fs=<str>        path to the file system folder
    --scale=<int>     main window scale
    --cmd=<str>       run commands in the console

```

Possible solution? Make ArgParse module write into stdout not stderr or wherever it is writing now

**Comment by msx80** [comment]
i don't know if it helps, but looking at the code recently i came across a wild `setbuf(stdout, NULL);` [here](https://github.com/nesbox/TIC-80/blob/master/src/studio/studio.c#L2031). Perhaps it's related.

**Comment by nesbox** [comment]
I found a hacky solution on how to output to the console in the windows app.
