### ISSUE TITLE
Pre-seed the random generator in the Lua environment

### ISSUE THREAD

**Issue by Viza74** [nesbox/TIC-80#127]
I needed random numbers in one of my games, and realized that it is not easy to seed the math.random function, because in TIC-80 the os.time is not accessible.
Please consider pre-seeding the random generator in Lua on TIC-80’s every startup.

**Comment by nesbox** [comment]
done in .25

**Comment by fmaida** [comment]
Could you also add the function "rnd()" to the language interpreter, as a wrapper for the lua command "math.random()" ?

It would be shorter and easier to remember for anyone that used to code on Pico-8.

Thank you

**Comment by Effer** [comment]
You can add

rnd=math.random()

At top of your file, and the call rnd(0,100) where you need

**Comment by Viza74** [comment]
(I can't reopen the issue, so I just commenting here, and don't know if it get's noticed by anyone. But actually it is not that important issue)

I'm not sure the pre-seeding is completely OK in TIC - if I start my cart from the command line (tic blahblah.tic) I still always get the same sequence of random numbers every time.
This particular game generates tetris-like pieces, and I always get the same sequence of the same pieces with the same rotation, both of which are chosen with a simple math.rnd

If I re-run the cart with cmd+r, there is a new sequence - Is it possible that the lua rnd generator is seeded with a simple time(), and not os.time()? That could explain this behaviour.

**Comment by harrisyu** [comment]
Same problem here, math.random got  same sequence, can you please check it again?

**Comment by nesbox** [comment]
@harrisyu weird, I preseed rand on every TIC start https://github.com/nesbox/TIC-80/blob/92214f13b3a30ce3c1dac80e8a554ddee09bbddd/src/studio.c#L2402
will check

**Comment by nesbox** [comment]
can't reproduce it
just do _preseeding_ on every game start
