### ISSUE TITLE
Distorted sound with 0.80.1345 Pro on Linux

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1273]
On a fresh install of the pro binary from itch.io on Linux, all sound is distorted (eg hitting a note on the SFX piano in a new cart) and timing is wrong (eg I loaded Super Meat Boy cart and the tunes are out of sync and badly distorted). Maybe related to the high latency mentioned here https://github.com/nesbox/TIC-80/issues/1199 although restart doesn't fix it.

**Comment by paul59** [comment]
Just built 0.90.1482-dev, not an issue with that so you might want to ignore?

**Comment by nesbox** [comment]
Hmm, could you pls test one of the latest dev builds?
You can download it here https://github.com/nesbox/TIC-80/actions/runs/422482734

**Comment by paul59** [comment]
As per my second comment,  I built the latest version and the issue is no longer present. so maybe close this issue?

**Comment by nesbox** [comment]
Yes, but I'd like to find a reason why our build has distorted sound, maybe we are doing something wrong on our build servers?

**Comment by paul59** [comment]
Ah I see. Just did that and your version of 0.90.1482 definitely has distorted sound whereas the version I build does not.

The version I build is 12mb  whereas the .deb has a 4mb ... there's no separate sokol build as there used to be, maybe this is the difference??

**Comment by nesbox** [comment]
I think you build a debug version, that's why it's 12Mb instead of 4Mb, pls add `-DCMAKE_BUILD_TYPE=MinSizeRel` to the CMake command.
As for distorted sound, I think the problem is with the sound library with are using to build SDL2 lib on our build servers and you have your own sound lib that perfectly works on your side. It would be great if you investigate and get what sound lib SDL2 uses on your system.
Thanks.

**Comment by paul59** [comment]
> I think you build a debug version, that's why it's 12Mb instead of 4Mb, pls add `-DCMAKE_BUILD_TYPE=MinSizeRel` to the CMake command.
> As for distorted sound, I think the problem is with the sound library with are using to build SDL2 lib on our build servers and you have your own sound lib that perfectly works on your side. It would be great if you investigate and get what sound lib SDL2 uses on your system.
> Thanks.
You mean libsdl2 version? If so it's 2.0.10 (I'm running Debian based MX Linux)

**Comment by nesbox** [comment]
During the SDL2 lib docs https://github.com/SDL-mirror/SDL/blob/76468465a94b59f0dde4791846bc2476be4f245f/docs/README-linux.md:
```
- libsamplerate0-dev lets SDL optionally link to libresamplerate at runtime
  for higher-quality audio resampling. SDL will work without it if the library
  is missing, so it's safe to build in support even if the end user doesn't
  have this library installed.
```
I added `libsamplerate` and `libsndio` libs installation for the SDL2 build ddc837f.
Should work better now, pls check if not difficult.
