### ISSUE TITLE
Running TIC-80 on RetroPie

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#1277]
I compiled the TIC-80 from the current master on RPI with the help of https://github.com/nesbox/TIC-80/issues/1017

I'm using [Game HAT handheld](https://www.waveshare.com/game-hat.htm). It has display 480x320. Even when I change the https://github.com/nesbox/TIC-80/blob/master/include/tic80.h
```c
#define TIC80_FULLWIDTH 240
#define TIC80_FULLHEIGHT 160
```

and run it with `--scale=2` I see borders around the window and that's not happening for other games.

**Comment by RobLoach** [comment]
What are you trying to accomplish? TIC80's width and height is 240x160, and that likely won't change.

**Comment by jahodfra** [comment]
I was trying to scale it up to the display as near as possible. TIC-80 has 240x136px so it could nicely fit into 480x320 with top and bottom border. Unfortunately the system resolution is 640x480 and that completely confuses TIC-80 and I have massive borders on really small display. So the problem is not in TIC-80 but in my system config.
