### ISSUE TITLE
Stretch to fill screen on Raspberry pi

### ISSUE THREAD

**Issue by RaspberyPye** [nesbox/TIC-80#1279]
![2020-12-25-094515_1152x720_scrot](https://user-images.githubusercontent.com/59261030/103130754-ecb09900-4695-11eb-9427-31cf36664615.png)

When in fullscreen (both maximised and completely fullscreen) there is a large black bar around the screen which get annoying quite quickly, Is this intentional or a bug?

Also, is there a command to change the transparant colour, like 'palt()' in pico8?

Thanks, and merry christmas!

**Comment by nesbox** [comment]
We scale screen only by an integer, so, for example, if you have `800 x 600 px` resolution TIC screen will be `(240*3) x (136*3) = 720 x 408 px` with `40 96 40 96 px` black border padding, it's by design :)
Unfortunately, there is no function to change the transparent color, only by passing `colorkey` to the `spr()` API https://github.com/nesbox/TIC-80/wiki/spr
Thank you.

**Comment by 12buntu** [comment]
> We scale screen only by an integer, so, for example, if you have `800 x 600 px` resolution TIC screen will be `(240*3) x (136*3) = 720 x 408 px` with `40 96 40 96 px` black border padding, it's by design :)

Is it possible to manually change this? I was trying to experiment with making a VR-ish thing that could run on my phone, but it doesn't fill the entire screen, which causes obvious problems.

**Comment by nesbox** [comment]
Yes, try to replace `calcTextureRect()` function https://github.com/nesbox/TIC-80/blob/master/src/system/sdl/main.c#L451
with this one to stretch the screen
``` c
static void calcTextureRect(SDL_Rect* rect)
{
    SDL_GetWindowSize(platform.window, &rect->w, &rect->h);
}
```
![image](https://user-images.githubusercontent.com/1101448/103165562-9759c080-482a-11eb-945b-654cd97dcc24.png)

 or with this one, to keep aspect ratio
``` c
static void calcTextureRect(SDL_Rect* rect)
{
    SDL_GetWindowSize(platform.window, &rect->w, &rect->h);

    {
        enum{Width = TIC80_WIDTH, Height = TIC80_HEIGHT};

        if (rect->w * Height < rect->h * Width)
        {
            s32 discreteWidth = rect->w;// - rect->w % Width;
            s32 discreteHeight = Height * discreteWidth / Width;

            rect->x = (rect->w - discreteWidth) / 2;

            rect->y = rect->w > rect->h 
                ? (rect->h - discreteHeight) / 2 
                : TIC80_OFFSET_TOP*discreteWidth/Width;

            rect->w = discreteWidth;
            rect->h = discreteHeight;

        }
        else
        {
            s32 discreteHeight = rect->h;// - rect->h % Height;
            s32 discreteWidth = Width * discreteHeight / Height;

            rect->x = (rect->w - discreteWidth) / 2;
            rect->y = (rect->h - discreteHeight) / 2;

            rect->w = discreteWidth;
            rect->h = discreteHeight;
        }
    }
}
```
