### ISSUE TITLE
Live reload not working

### ISSUE THREAD

**Issue by juniorgarcia** [nesbox/TIC-80#1290]
Hello guys, how are you?

I coudn't make live reload code to work. Here are some information that may be useful:
- TIC-80 Version: Pro 0.80.1345
- OS: macOS 10.15.7 (19H15)
- tic80 is on my `$PATH`
- My game's file is **not** in the same path as tic80, _and_ is a .js file, although I tried with a .lua game and didn't work either
- The command line I'm running is `tic80 -code-watch game.js`

I also tried the TIC80 sample game as a .lua file, also didn't work.

You've done a great job! It's very funny to play with TIC80!

**Comment by nesbox** [comment]
Please, try another way to test it, save your cart using `save game.js` command, then use `folder` command to locate your `game.js` cart and try to edit it with any text editor, save it and go back to TIC-80, the cart should be automatically reloaded.
Thanks.

**Comment by juniorgarcia** [comment]
I did that and _sometimes_ (I didn't notice a pattern to that) tic80 detects the changes and asks if I want to reload. Even though I click `YES`, nothing happens, but when I type `CMD+R` the game is updated.

**Comment by nesbox** [comment]
Ok, I'll try to reproduce thanks.

**Comment by scambier** [comment]
I'll chime in for this issue. I'm currently trying to integrate the `-code-watch` option into my [typescript compiler][https://github.com/scambier/tic80-typescript).

So, once everything is running and watching, the flow is the following:
- Save source (compilation begins)
- Focus to TIC-80
- (compilation ends)
- TIC-80 does nothing particular, ctrl+r does not load the new file
- Focus out from TIC-80, then back to TIC-80
- ctrl+r loads the new file

Alternatively:
- Save source, and wait the end of compilation
- Focus to TIC-80
- ctrl+r loads the new file

So, TIC never reloads by itself, and it does not detect changes if they happen while it's in focus.

**Comment by ChildishGiant** [comment]
It seems that in .90 code watch has been removed. While you can easily make it load code on startup there doesn't seem to be any way to watch for changes any more 😢

**Comment by nesbox** [comment]
Why? Try to load `*.lua` project as a command-line parameter and TIC will watch for changes while you edit the `.lua` file in another code editor.

**Comment by nesbox** [comment]
73e0b4d
- added checking for cart/project changes in every tick, not only when window gained focus
- `-code-watch` is deprecated, please use `tic80 game.lua` to load your code

**Comment by leoncvlt** [comment]
I've got a `test.lua` project open in visual studio code, and run it with the command `tic80 test.lua`.

However, when making changes to the code and saving, the changes are not automatically reloaded. I need to shift focus on the TIC-80 window and press CTRL-R to do so - is this the intended behaviour?

**Comment by nesbox** [comment]
Unfortunately, live reloading works with internal files only.
- save `test.lua` to the TIC's internal folder
- and then call `load test.lua`
- open `test.lua` in the external editor and edit it
- go back to TIC, all the changes should be reloaded

**Comment by winny-** [comment]
Here's another approach if you have the PRO version:

```sh
echo test.lua | entr -r tic80 /_
```

This will restart tic80 every time the file changes.
