### ISSUE TITLE
Glitchy Scrolling on laptop

### ISSUE THREAD

**Issue by 00Her0** [nesbox/TIC-80#1304]
Scrolling on laptop (2 finger scroll) is really glitchy. it just scrolls to the bottom and won't go up.

**Comment by 00Her0** [comment]
on the version I downloaded from the microsoft store

**Comment by nesbox** [comment]
could you pls check the latest release from the website?
https://github.com/nesbox/TIC-80/releases/download/v0.80.1344/tic80-v0.80-win.zip
Thanks.

**Comment by 00Her0** [comment]
Ah, yes. Microsoft store is still on ver. 0.60.3

**Comment by 00Her0** [comment]
is there a reason for that btw?

**Comment by 00Her0** [comment]
Oh wait never mind. Thanks for responding!
