### ISSUE TITLE
`poke` to VRAM does nothing inside OVR()

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1305]
```
function TIC() 
  cls(13)
end

function OVR()
	print("HELLO WORLD!",0,0)
	for i=0,20 do
		poke(i, 0xcc)
	end
end
```

Expected result:

- See HELLO WORLD
- See a ~40px line of white on the first row

Actual result:

- Only HELLO WORLD is shown
- The pokes to VRAM seem to have no effect

**What I'm wanting to accomplish**

I'm trying to build a filter in OVR().. something to read/modify every frame (INCLUDING the overlay):

```
function OVR()
-- do final overlay stuff, if needed

-- read VRAM
-- modify/filter
-- write VRAM
end
```

I wondered if I might have issues with the "do final overlay stuff" not being "committed" to VRAM yet, but first I ran into the fact that changes to VRAM inside OVR seem to be entirely ignored... I suppose this either wasn't considered or is some type of optimization?

**The expected behavior here (IMHO) would be that ANY changes to VRAM are written to the display.**

It would seem to make sense to draw the VRAM (to screen) once per frame so I'd expect something like this sequence:

- frame begins
  - TIC/SCN fires
  - buffer is committed to VRAM(?)
  - OVR fires
  - buffer is committed to VRAM(?)
  - _VRAM is written to actual display_
- wait for next frame

I put `?` because it's not clear that every single draw command shouldn't actually be writing directly to VRAM... In any case it seems the key thing would be a single final flush of VRAM after the entire sequence, so I'm quite puzzled why my `pokes` inside OVR do nothing.

**Comment by nesbox** [comment]
Yes, OVR mode is not "pokable" at the moment, all the drawing operations draw directly to the rendered screen.
We will try somehow fix it in 0.90
Thanks.

**Comment by potato25** [comment]
I wanted to change palette of OVR() through code and poke() function , is this why it wasn't working ?

**Comment by joshgoebel** [comment]
Not sure you can change ovr palette at all.

**Comment by nesbox** [comment]
@potato25 look at this line https://github.com/nesbox/TIC-80/blob/master/src/core/core.c#L669
```c
memcpy(core->state.ovr.raw, tic_tool_palette_blit(ovrEmpty ? &tic->ram.vram.palette : ovr, fmt), sizeof core->state.ovr.raw);
```
Here we copy the `OVR` palette from `VRAM` to render a frame, so you can poke it in the `TIC()` callback.

**Comment by joshgoebel** [comment]
Wait, I'm lost.  All that's doing is giving you a pointer to a copy of the OVR palette (if there is one) and then copying that into `state.ovr.ram`.  What does this have to do with palette VRAM?

The `overline` callback isn't run until the very end, so even if I'm reading this wrong why would we init the OVR stuff before we're even ready to start drawing with the overline palette?

**Comment by nesbox** [comment]
Because after the `TIC()` callback goes `SCN()` callback where you can change palette in the VRAM, and we save OVR palette to avoid this.
I agree, it looks totally ugly and I personally hate this part of TIC, I thought to add OVR mechanism just to render more than 16 colors in the Sprite/Map editors, but later decided to add this to the API and I little regret about this decision now.
And I'm thinking about how to fix this illogical part without breaking compatibility for the carts.

**Comment by joshgoebel** [comment]
> ...and we save OVR palette to avoid this.

To avoid what?  I'm still not seeing where you ever put OVR into VRAM... If we're "backing it up" here where are we restoring it?

>  I little regret about this decision now.

Welcome to software ownership. :)

> And I'm thinking about how to fix this illogical part without breaking compatibility for the carts.

Maybe you can't?  But you could deprecate it the next time you introduce something new so that if you new thing B you lose the old OVR behavior...

**Comment by nesbox** [comment]
> To avoid what? I'm still not seeing where you ever put OVR into VRAM... If we're "backing it up" here where are we restoring it?

Here for example
https://github.com/nesbox/TIC-80/blob/master/src/core/core.c#L56

**Comment by joshgoebel** [comment]
I feel like we're talking past each other.  I'm coming back to:

>  I'm still not seeing where you ever put OVR into VRAM

_Which was @potato25 question earlier._  From what I've seen so far OVR is *never* copied into VRAM... so from what I discern it's impossible to alter at runtime (other than banking), is that correct?

Interesting enough `sync` seems to copy it into `state.ovr.palette` when the palette mask is set -  so you can still use 8 banks of OVR palettes and swap them out via `sync`, but again from what I can tell the OVR palette is still never in "hardware" VRAM.

**Comment by Popolon** [comment]
This is a working example, the trick is here to define at the last scanline the palette. But I noticed that, if ,an overlay color is edited in the sprite/color palette editor, this doesn't work anymore. A cart containing this code or a new cart + past is then needed. This can perhaps help to understand the source of the bug.

```
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua

function SCN(y)
 if y==136 then
  end
 for i=0,15 do
  local of=3*i
  poke(0x03FC0+of,i*10)  
  poke(0x03FC0+of+1,i*10)
  poke(0x03FC0+of+2,i*10)
 end
end

function OVR()
 for i=0,15 do rect(i*16,32,16,16,i) end
end

function TIC()
 for i=0,15 do
  local of=3*i
  poke(0x3FC0+of,(15-i)*10)  
  poke(0x3FC0+of+1,i*10)
  poke(0x3FC0+of+2,i*10)
 end
  cls(13)
 for i=0,15 do rect(i*16,0,16,16,i) end
end
```

**Comment by joshgoebel** [comment]
>  But I noticed that, if ,an overlay color is edited in the sprite/color palette editor, this doesn't work anymore.

Yes, we're talking about an actual OVR palette here (or I thought potato25 was).  If you don't have one defined then the standard palette is just reused and it's not surprising that has slightly different behavior.  I believe nesbox has said the OVR stuff is a little messy behind the scenes.

**Comment by Popolon** [comment]
For the compatibility, a flag could be used ? Compatible and broken or stable and full featured ? Is there carts that use it ? I just noted a miss in my example (the test end is at the wrong place).

**Comment by joshgoebel** [comment]
@Popolon Is your demo only showing that you can alter the OVR palette (in RAM) WHEN it's not a separate palette, IE, if it's just using the normal palette?  That actually makes sense - and very useful to know.  Though that may have some issues with rendering the last scanline... I'm not sure if the sequencing there will get ya or not.  IE, if you setup the OVR palette on the last scanline - doesn't that "break" rendering of the last scanline (it would be the OVR colors)? (though a game could find a way to work around that)

@potato25 Would that help you?

**Comment by potato25** [comment]
@joshgoebel Well , As Nesbox mentioned earlier , it's very messy . Let Nesbox decide what to do

**Comment by Popolon** [comment]
Sure need to manage last line a special way, like black line (one line cost) or using it of few more line for special things with OVR palette. I used black last line here https://tic80.com/play?cart=1714

**Comment by nesbox** [comment]
Added `VRAM` access from the `OVR()`
Added `BDR(row)` callback, it goes through full-height `0-143` lines instead `0-135` in case with the `OVR()`
973dd00

**Comment by joshgoebel** [comment]
I've been staring at 973dd00 for a while now... so before 0.90 released did you VASTLY change how OVR works (when you fixed my bug)?  So there is no more "secret" OVR buffer... everything just draws straight to VRAM, the "overdraw" element is handled by `memmask`... but now all changes drawn to OVR are fully persistent - because they are truly written to actual VRAM - just like everything else.

That's a very different understanding than what I had an hour ago. :)

Am I understanding it properly?

**Comment by nesbox** [comment]
It seems yes :)
