### ISSUE TITLE
Add a new VERSION chunk type

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1307]
Should consist of a 4-byte unsigned integer with the current revision.

**Comment by nesbox** [comment]
Added here d0545d9

**Comment by Anrock** [comment]
But what does it do?

**Comment by nesbox** [comment]
@Anrock It doesn't matter anymore, just reverted it :)

**Comment by joshgoebel** [comment]
Should this be reopened then or did we decide no version chunk?

**Comment by nesbox** [comment]
no version chunk atm
