### ISSUE TITLE
Wiki improvements

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1309]
Creating list here to track improvements I still want to make:

- [x] Sprite Editor
- [ ] Sprites / Tiles / Maps (concepts)
- [ ] Improved "The Code" / Code Editor
- [x] Expand `Palettes` to talk about more than just the default palette
- [ ] Expand `Bankswitching` (concept)
- [ ] Tie Display/palette and BPP together better somehow
- [ ] blit segment
- [x] Figure out where build instructions live

---

I've been cleaning up the wiki in some small ways (consistency, improving API docs, etc) and wanted to check here before perhaps making some larger changes.  I'd like to suggest making "Home" a bit more of a summary and creating individual pages for:

- Console
- API
- Code Editor
- Sprite Editor
- Map Editor
- SFX Editor
- Music Editor

Home would still mention these things (and include a snap so it's nice to scroll the), but instead of HUGE detail (as is now found there) we'd perhaps include just a paragraph and then link to the more details wiki page on the subject.

This would also allow us to make important things "pop" a lot easier... for example Code Editor might become (very roughly):

```
## Code editor

[image]

~We have a great built-in editor... [short paragraph] [link to learn more]

~You can also use your favorite external editor (Atom, VS Code, etc). [link to learn more]
```

_Text above isn't verbatim, just showing the idea of summarizing vs details._

Right now the fact that you can use an external editor gets lost quite easily.

**Comment by nesbox** [comment]
I like the idea and would really appreciate it if you help to clean up the Wiki.
Thanks for the help 👍

**Comment by joshgoebel** [comment]
It the canonical website tic80.com or tic.computer ?

**Comment by nesbox** [comment]
Pls use `tic80.com` everywhere, `tic.computer` is deprecated atm

**Comment by joshgoebel** [comment]
What is the point of the https://github.com/nesbox/TIC-80/wiki/Demo-Carts page since it's just the content anyone can get by typing `new js`, etc?

**Comment by nesbox** [comment]
Don't know, @clsource created this page

**Comment by clsource** [comment]
@joshgoebel It serves as a documentation for comparing the different ways to init a game in the TIC-80 supported languages.

Anyone can get those codes by typing `new`. But someone new to TIC-80 can easily compare and see how a language is implemented before booting up TIC-80.

Finally it documents better the usage of the `new` command by providing the end result of the operation.

**Comment by joshgoebel** [comment]
@nesbox 

I think I've made some decent progress on the Wiki.  Too many changes to count but at a very high level:

- Simplified Home greatly making it a bit more of a summary that links to detailed pages 
  - Home should explain the WHAT at a high level
  - Detailed pages should explain HOW, more detailed instructions, etc.
  - This means separate detailed pages for most of the Editors, Console, etc.
- Removed duplication (ex: RAM layout is only on the RAM page, remove build instructions from Wiki vs README)
- Increase cross-linking within the wiki where it seems to make sense
- Increased conformity of API function pages
- Split API functions into categories (Drawing, Memory, Input, etc)
- Moved API reference to it's own page
- Bulked up some pages like Palette to be more "what does a palette mean in TIC-80, how do i work with palette?"  vs just "here are the colors"

I don't consider that I'm "done" yet, but I think it's a lot tidier and definitely think you can see the vision that I had when I first opened this issue.  Let me know if you have any big picture thoughts.

**Comment by clsource** [comment]
> > Finally it documents better the usage of the new command by providing the end result of the operation.
> 
> Ok, so that'd be a good place to link it... but I find the "Demo Carts" quite misleading in the sidebar... I expect I'm going to find some real demos or something, not just the "starter" cartridges for each language...
> 
> Is it possible we can find a better name or perhaps remove the sidebar link in favor of just linking from the list of commands - and then truly tweaking this page a bit more to make it document `new` as you suggest? Thoughts?
> 
>     * Starter Carts
> 
>     * Cartridge Templates
> 
>     * ?

Sure. I think that maybe inside the Commands docs.

A link to a specific file maybe.

`tic-command-new.md`

**Comment by joshgoebel** [comment]
To me it's more about the final product than the command - and so far we don't have individual pages for commands (yet)... so I renamed it Hello Word, and referenced it from the command list.

- https://github.com/nesbox/TIC-80/wiki/console
- https://github.com/nesbox/TIC-80/wiki/hello-world

**Comment by potato25** [comment]
The Bits Per Pixel Page should contain this : https://github.com/nesbox/TIC-80/wiki/Advanced-Drawing-Techniques

**Comment by nesbox** [comment]
> I think I've made some decent progress on the Wiki. Too many changes to count but at a very high level:

Awesome, one thing, I want you to add to the Credits https://github.com/nesbox/TIC-80#credits, could you pls provide the record with your name and link to your account?
Thanks.

Also, I'll try to record new GIFs for the Editors preview.

**Comment by joshgoebel** [comment]
@potato25 Indeed or link to it... I didn't even know that page existed. :-)  Thanks for the pointer.

**Comment by joshgoebel** [comment]
@potato25 Is that page linked externally somewhere?  I don't see any internal wiki links to it?

**Comment by potato25** [comment]
Drop down pages tab in Home - wiki and select Advanced Drawing Techniques

**Comment by joshgoebel** [comment]
Ah. You just mean the full list of pages.

**Comment by joshgoebel** [comment]
I now consider the Wiki more of a constantly moving "work in progress" than a TODO list of specific things that need to be done in the future... and this list is aging poorly anyways... so I'm going to close this.
