### ISSUE TITLE
Lets settle on a single location for build instructions

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1310]
- https://github.com/nesbox/TIC-80/wiki/build-instructions
- https://github.com/nesbox/TIC-80#build-instructions

Right now the wiki seems to have more overall... I'd like to see this duplication removed so that it's easy to keep the build instructions updated (no need to update two places) and have a single canonical location.

Should that be in the Wiki or in the README?

**Comment by nesbox** [comment]
I think README is a better place.
Thanks.

**Comment by joshgoebel** [comment]
Ok we still have a problem in that the Wiki includes a lot of data NOT in the README:

- Much more detailed build instructions for Visual Studio
- Build instructions for Raspberry Pi (Retropie)
- Mention of where to find TIC-80 on Arch (in AUR)
- Build instructions for ALT Linux 64-bit (which look crazy long, surely you could use `cmake`)

Should any of that need to be pulled over into the README first?

**Comment by nesbox** [comment]
I think we have to move only `Raspberry Pi` instructions to the README, all the others are deprecated.

**Comment by joshgoebel** [comment]
PR created.

**Comment by nesbox** [comment]
Merged, thank you :)
