### ISSUE TITLE
Map editor image reference is broken on Wiki

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1311]
https://github.com/nesbox/TIC-80/wiki#map-editor

The file it's looking for is a 404.

**Comment by nesbox** [comment]
Try to use this gif for example https://user-images.githubusercontent.com/1101448/105969223-11cf6780-6099-11eb-9dbb-48609c43c568.gif
![map](https://user-images.githubusercontent.com/1101448/105969223-11cf6780-6099-11eb-9dbb-48609c43c568.gif)

Yes, also we have to update all the Editors screenshots for the actual version.
Thanks.

**Comment by joshgoebel** [comment]
Thanks!
