### ISSUE TITLE
[Request] Please add THEME.CODE.FG to alter foreground text in code editor

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1312]
<img width="1024" alt="Screen Shot 2021-01-26 at 6 30 32 PM" src="https://user-images.githubusercontent.com/6473/105920053-a5a32400-6004-11eb-9a54-0155783adfc7.png">

_I would prefer my text not also be purple here._

The UI colors are fixed (am I wrong?) so that means if one wants to customize their top and bottom borders that requires editing palette entry 12 - which unfortunately also has the side effect of changing all the text (and console) to whatever new color is chosen.

There should be a was to specify a custom "default" foreground/text color with themes.

**Comment by joshgoebel** [comment]
So I tracked this as far as `drawCode` and:

```
                drawChar(code->tic, symbol, x, y, colors[syntaxPointer->syntax], code->altFont);
```

But it seems it should *always* be using a color from the theme (based on the `syntaxPointer->syntax` array index)... but my theme doesn't have 13 (white) in it other than sign and cursor... so I'm not sure where in the stack that default of color 13 is coming in...

**Comment by joshgoebel** [comment]
LOL, so everything is a variable by default... um ok. :-)

```
    for(s32 i = 0; i < TIC_CODE_SIZE; i++)
        code->state[i].syntax = SyntaxTypeVar;
```

**Comment by nesbox** [comment]
Added THEME.CODE.FG to the config + some refactoring 09e2370

**Comment by joshgoebel** [comment]
Much saner naming. :)
