### ISSUE TITLE
holding down a button eventually registers as new btnp()

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1313]
If a button or key is held down for a few seconds, TIC-80 eventually registers a new button press (functions that trigger with btnp()  of that button get triggered) - even though there wasn't a new button press, the button was held down the whole time.

Maybe TIC-80 "loses signal" from the held-down button for one frame or so, and then registers the same button press again as a new press.

**Comment by nesbox** [comment]
Please, give us a small code to test the issue.
Thanks.

**Comment by borbware** [comment]
i tried to create a test cartridge for this, but could not reproduce the issue. it seems like this only happens when the cart is heavy enough so that the framerate dips. i'll try to recreate the issue with this in mind.

**Comment by borbware** [comment]
Here's a test cartridge that i used to reproduce the issue. A long empty for loop was added to simulate calculation-intensive code. My code calls `trace()` every time `btnp()` retriggers, and on my PC this happened roughly every 100 frames.

```
-- title:  btnp retrigger test
-- author: borb
-- desc:   tests when btnp gets retriggered if btn is held down
-- script: lua

t=0
x=96
y=24

FPS={fps=0,frames=0,lastt=-1000}
function FPS:upd()local F=self
    if time()-F.lastt <= 1000 then F.frames=F.frames+1
    else F.fps,F.frames,F.lastt=F.frames,0,time()end
end
function FPS:drw()print(FPS.fps,0,8,14)end

function TIC()

    cls(13)
    FPS:upd()
    for i=0,7 do
        if btnp(i) then
            cls(15)
            trace(t)
        end
    end

    for i=1,1000000 do
    end

    FPS:drw()
    print(t,84,84)
    t=t+1
end
```

**Comment by joshgoebel** [comment]
I can confirm, but I'm mystified as to why (I spent a few minutes looking at the input code and got nowhere).  The input registers in RAM never seem change.

No value over 100 works for hold since for some reason it thinks all the buttons are released every 100 ticks.

**Comment by joshgoebel** [comment]
@borbware Can you reproduce on the latest build?  I'm not seeing this issue anymore.

**Comment by borbware** [comment]
@joshgoebel Can confirm: I tested same inputs with 0.90 and 1.0-1979-dev: the bug does not appear anymore! \o/
