### ISSUE TITLE
duktape submodule fetches all duktape versions ever released

### ISSUE THREAD

**Issue by glebm** [nesbox/TIC-80#1323]
Fetching TIC-80 submodules currently downloads all of duktape releases ever made because it includes `https://github.com/svaarala/duktape-releases.git` as a submodule (and submodules do a full clone by default).

Options:

a) CMake's `FetchContent` can be used instead to download only the latest release.
b) `.gitmodules` can be configured to shallow-clone the duktape submodule. https://stackoverflow.com/a/17692710/181228

**Comment by nesbox** [comment]
I haven't known about it before, will try, thanks.

**Comment by glebm** [comment]
Thanks @RobLoach @nesbox!
What do you think of marking all or most submodules here as shallow?

**Comment by RobLoach** [comment]
The other repos are pretty small. I have no opinion.

**Comment by glebm** [comment]
The top 3 are `circle-stdlib`, `sdl2`, and `curl`.
Of these, `sdl2` and `curl` have huge commit histories.

```
du -sh vendor/* | sort -rh 
197M	vendor/circle-stdlib
62M	vendor/sdl2
25M	vendor/curl
22M	vendor/duktape
8.9M	vendor/wren
6.0M	vendor/sdl-gpu
5.1M	vendor/libuv
3.6M	vendor/zlib
2.4M	vendor/giflib
1.6M	vendor/moonscript
1.5M	vendor/lua
1.2M	vendor/squirrel
900K	vendor/fennel
712K	vendor/sokol
560K	vendor/zip
304K	vendor/http-parser
268K	vendor/lpeg
256K	vendor/blip-buf
180K	vendor/dirent
72K	vendor/argparse
```

**Comment by nesbox** [comment]
Added `shallow` for all the submodules 4a8c6a5
