### ISSUE TITLE
current build crashes on 3ds

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1326]
I tried the newest build ([Build #234](https://github.com/nesbox/TIC-80/actions/runs/520718158)) on my new 3ds xl. it crashed shortly after launching: 
![image](https://user-images.githubusercontent.com/19384640/106367918-deb5fe00-634e-11eb-965c-adc184839ca5.png)

I could confirm, however, that [Build #179 ](https://github.com/nesbox/TIC-80/actions/runs/405870883) works.

**Comment by nesbox** [comment]
Could you please check these two builds on 3DS [Build #198](https://github.com/nesbox/TIC-80/actions/runs/460682675) and [Build #210](https://github.com/nesbox/TIC-80/actions/runs/495629218)
I suspect d7da7dd where I broke here something.
Thanks.

**Comment by borbware** [comment]
can confirm, #210 crashes on 3ds but #198 does not!

**Comment by nesbox** [comment]
I made a temporary fix for 3DS, could you check it pls
https://github.com/nesbox/TIC-80/actions/runs/545003985

**Comment by borbware** [comment]
nope, build 241 still crashes.

**Comment by nesbox** [comment]
Maybe @asiekierka could look at this because I don't have any thoughts :(
Thanks.

**Comment by asiekierka** [comment]
The curl-based codepath wasn't really tested; using HTTPC led to a far smaller executable, so I didn't really look into curl much. I'd suspect that's where the problem might lie.

**Comment by nesbox** [comment]
We are still using `HTTPC` in the build...

**Comment by asiekierka** [comment]
Ah, you merged the two files... let's see, then

**Comment by asiekierka** [comment]
I've looked into it, and it's... weird. I'm trying to get a smaller reproduction case going, but... if you look at the binary with `objdump`, you'll find that `tic_net_get` just... doesn't generate the correct code:

```
001074f4 <tic_net_get>:
  1074f4:       e3a03000        mov     r3, #0
  1074f8:       e5933004        ldr     r3, [r3, #4]
  1074fc:       e7f000f0        udf     #0
```

A workaround is - believe me or not - to either:

* disable optimizations on `net.c` on 3DS specifically,
* move `sizeof(net_ctx)` from n3ds_net_get to a helper method (`int net_ctx_size(void)` f.e.),
* remove `tic_net *net` from the `net_ctx` struct (of course, that will make the code not compile anymore).

I have no idea why this is occuring yet, and I may look into it further when I find some more time.

**Comment by nesbox** [comment]
I'll try this, thank you 👍

**Comment by nesbox** [comment]
I changed `tic_net_get()` a bit here 4832d7c, now `objdump` looks like:
``` asm
00000000 <tic_net_get>:
   0:   e92d43f0        push    {r4, r5, r6, r7, r8, r9, lr}
   4:   e1a05000        mov     r5, r0
   8:   e1a09003        mov     r9, r3
   c:   e1a07001        mov     r7, r1
  10:   e1a08002        mov     r8, r2
  14:   e24dde83        sub     sp, sp, #2096   ; 0x830
  18:   e24dd00c        sub     sp, sp, #12
  1c:   e59f6094        ldr     r6, [pc, #148]  ; b8 <tic_net_get+0xb8>
  20:   e28d400c        add     r4, sp, #12
  24:   e1a02006        mov     r2, r6
  28:   e3a01000        mov     r1, #0
  2c:   e1a00004        mov     r0, r4
  30:   ebfffffe        bl      0 <memset>
  34:   e5951004        ldr     r1, [r5, #4]
  38:   e1a00004        mov     r0, r4
  3c:   e59f2078        ldr     r2, [pc, #120]  ; bc <tic_net_get+0xbc>
  40:   e58d580c        str     r5, [sp, #2060] ; 0x80c
  44:   e58d9824        str     r9, [sp, #2084] ; 0x824
  48:   e58d882c        str     r8, [sp, #2092] ; 0x82c
  4c:   ebfffffe        bl      0 <strncpy>
  50:   e59f2064        ldr     r2, [pc, #100]  ; bc <tic_net_get+0xbc>
  54:   e1a01007        mov     r1, r7
  58:   e1a00004        mov     r0, r4
  5c:   ebfffffe        bl      0 <strncat>
  60:   e59f1058        ldr     r1, [pc, #88]   ; c0 <tic_net_get+0xc0>
  64:   e28d0008        add     r0, sp, #8
  68:   ebfffffe        bl      0 <svcGetThreadPriority>
  6c:   e1a00006        mov     r0, r6
  70:   ebfffffe        bl      0 <malloc>
  74:   e1a02006        mov     r2, r6
  78:   e1a01004        mov     r1, r4
  7c:   e1a05000        mov     r5, r0
  80:   ebfffffe        bl      0 <memcpy>
  84:   e3e00000        mvn     r0, #0
  88:   e3a01001        mov     r1, #1
  8c:   e59d3008        ldr     r3, [sp, #8]
  90:   e1cd00f0        strd    r0, [sp]
  94:   e59f0028        ldr     r0, [pc, #40]   ; c4 <tic_net_get+0xc4>
  98:   e3a02901        mov     r2, #16384      ; 0x4000
  9c:   e1a01005        mov     r1, r5
  a0:   e2433001        sub     r3, r3, #1
  a4:   e08f0000        add     r0, pc, r0
  a8:   ebfffffe        bl      0 <threadCreate>
  ac:   e28dde83        add     sp, sp, #2096   ; 0x830
  b0:   e28dd00c        add     sp, sp, #12
  b4:   e8bd83f0        pop     {r4, r5, r6, r7, r8, r9, pc}
  b8:   0000082c        .word   0x0000082c
  bc:   000007ff        .word   0x000007ff
  c0:   ffff8000        .word   0xffff8000
  c4:   00000018        .word   0x00000018
```

@borbware could you pls check [Build #243](https://github.com/nesbox/TIC-80/runs/1853223793), it seems should work now.
Thank you.

**Comment by borbware** [comment]
Tested; Build 243 works!

**Comment by nesbox** [comment]
Awesome, thank you all for the help and the new experience with disassembling :)
