### ISSUE TITLE
mget(y, x) reversed parameters?

### ISSUE THREAD

**Issue by RobLoach** [nesbox/TIC-80#1327]
@joshgoebel found the mget parameters are flipped...

https://github.com/nesbox/TIC-80/wiki/mget/_compare/eb1d1b8%5E...eb1d1b8

Is this by design? Or should we fix it?

**Comment by joshgoebel** [comment]
Wait did I find that?  Lol. Seems like a problem though but one hard to fix without breaking existing code. Is this really switched?

**Comment by nesbox** [comment]
reverted
