### ISSUE TITLE
Little pause at the beginning of the music

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1331]
Jesus Ricardo:

> I always have bugs with the music loops in TIC-80.
> Using the music () command with the attribute 'row' different from -1 causes a little pause at the beginning of the music.
> Using the Jxx command also has errors, it has a small delay when activating.

Should be investigated

**Comment by Kyuchumimo** [comment]
https://user-images.githubusercontent.com/74131798/107132106-73fa4a80-6899-11eb-888d-0b23c7ae627b.mp4

**Comment by nesbox** [comment]
Fixed here 6ff08ee
Build https://github.com/nesbox/TIC-80/actions/runs/752204709
Thank you for the report.
