### ISSUE TITLE
alt-tab inserts a space in the code editor

### ISSUE THREAD

**Issue by asexto** [nesbox/TIC-80#1332]
When switching apps using the usual shortcut (alt+tab) TIC-80 inserts one space in the code editor. It would be great to make TIC-80 ignore the pressed keys. This is specially annoying for example when reading the wiki while programming.

**Comment by nesbox** [comment]
Can't reproduce it on the latest 0.90 and 0.80, tested on Windows and Mac.
Please, reopen if you have more details on how to reproduce it.
THanks.

**Comment by asexto** [comment]
I just updated to the Git version and I see the problem still exists. This is what I do:
* I am typing with the *code editor* visible
* I switch applications pressing alt+tab and focus another application (for instance the web browser)
* I switch back to the code editor of TIC-80 pressing alt+tab again
In this same moment TIC-80 inserts a space character just where the cursor is located

I don't see how to reopen this issue. Do you want me to open a new one?

**Comment by joshgoebel** [comment]
I assume Windows since you say "alt" tab?

**Comment by nesbox** [comment]
Unfortunately, still can't reproduce but added a workaround here 78c0b15
@asexto could you pls test the latest version?
https://github.com/nesbox/TIC-80/actions/runs/729775636
Thanks.

**Comment by asexto** [comment]
Sorry I forgot to mention I'm using Manjaro Linux and I install TIC-80 from the Arch Linux build file published in the AUR that fetches the code from your repository (https://aur.archlinux.org/packages/tic-80-git/).

I just rebuilt TIC-80 this way but the problem is still there. Do you want me to make a video or something?

Thank you!

**Comment by nesbox** [comment]
OK, I've just reproduced it on Manjaro Linux...

**Comment by nesbox** [comment]
Fixed here c83b696
@asexto please, check it.

**Comment by asexto** [comment]
Checked, now it works great. Thank you!!!
