### ISSUE TITLE
Angle() Function

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#1337]
Plz add a function named angle( x1 , y1 , x0 , y0 , x2 , y2 ) which returns angle in radians ( 0 to 2*pi ) and it is angle between point ( x1 , y1 ) and ( x2 , y2 )  w.r.to ( x0 , y0 ) as center

**Comment by joshgoebel** [comment]
Sounds like something for an external library to me, some sort of geometry lib.

**Comment by RobLoach** [comment]
You could implement this in a small function in your code. Pythagoras will help you out 😉

**Comment by joshgoebel** [comment]
I found this helpful for just the math: 

https://www.varsitytutors.com/calculus_3-help/angle-between-vectors

**Comment by nesbox** [comment]
Agreed, it's a kinda geometry lib function, the current API is more for working with the virtual "hardware" :)

**Comment by joshgoebel** [comment]
https://gist.github.com/Xeoncross/9511295#file-mathlib-lua-L231

```lua
-- Returns the angle in degrees between the first and second points, measured at the centre
-- Always a positive value
function angleAt( centre, first, second )
	local a, b, c = centre, first, second
	local ab = math.lengthOf( a, b )
	local bc = math.lengthOf( b, c )
	local ac = math.lengthOf( a, c )
	local angle = math.deg( math.acos( (ab*ab + ac*ac - bc*bc) / (2 * ab * ac) ) )
	return angle
end
```

**Comment by potato25** [comment]
Thanks :)

**Comment by potato25** [comment]
I made it , angle between 3 points with x0,y0 as center , it's 30 lines of code :)

**Comment by joshgoebel** [comment]
30 lines? Why doesn't the code there work as is?

**Comment by potato25** [comment]
I just wrote my own code :)

**Comment by potato25** [comment]
It's done here : https://tic80.com/play?cart=1663
Should this be closed now ?

**Comment by nesbox** [comment]
Great, thank you :)

**Comment by potato25** [comment]
Usage of angle ( ) Function i created : https://tic80.com/play?cart=1946
