### ISSUE TITLE
Classic Z+X key binding for Ⓐ/Ⓑ buttons difficult to use on German keyboard

### ISSUE THREAD

**Issue by jancborchardt** [nesbox/TIC-80#1339]
On a [German keyboard layout](https://en.wikipedia.org/wiki/German_keyboard_layout), <kbd>Z</kbd> and <kbd>Y</kbd> are switched, meaning <kbd>Z</kbd> is in the top middle.
This makes it difficult to play most of the showcased games as the common keyboard button combo <kbd>Z</kbd>+<kbd>X</kbd> (controller Ⓐ+Ⓑ) is quite far apart, and requires playing with index finger and pinky.

I browsed the code and as far as I could tell, an issue with fixing this could be that all keys are emulated:
https://github.com/nesbox/TIC-80/blob/master/src/system/sdl/keycodes.inl
So a simple "<kbd>Y</kbd> is also <kbd>Z</kbd>/Ⓐ" would not work well with games which use <kbd>Y</kbd> for other things – I assume.

Maybe it’s possible to check the person’s keyboard layout? Or any other ideas, short of key remapping (or changing the keyboard layout)?

**Comment by nesbox** [comment]
Known issue, let's try to add keyboard remapping to the game menu...

**Comment by vincelord** [comment]
I'm also interested in german keyboard support.
As of now, I cannot enjoy any game on TIC80 that utilizes the Y (in my case Z) button... its pointless!

**Comment by nesbox** [comment]
It will be fixed here #1613

**Comment by nesbox** [comment]
Added mapping detection 80089c1

**Comment by jancborchardt** [comment]
Thank you so much @nesbox! :)
