### ISSUE TITLE
"sync" API behaves strangely

### ISSUE THREAD

**Issue by kikeroga3** [nesbox/TIC-80#1340]
In the PRO version(0.80.1345), the following results are all 8 8 8 8 8 8 8 8.

for b=0,7 do
 sync(4,b,true);mset(0,0,b+1)
end
for b=0,7 do
 sync(4,b,false);a=mget(0,0)
 trace(a)
end

I think it's correct to be 1 2 3 4 5 6 7 8, but is my understanding wrong?

Thank you.

**Comment by joshgoebel** [comment]
Confirm (0.80.1344 release, non-PRO).  This also defies my expectations of what should happen.

Should pro cartridges still run on non-PRO, that would be my assumption...

**Comment by joshgoebel** [comment]
0.90.1509-dev seems to have the same unexpected behavior.

**Comment by nesbox** [comment]
You can call `sync()` only once per `TIC()`, it's a limitation.
https://github.com/nesbox/TIC-80/wiki/sync

**Comment by nesbox** [comment]
> Should pro cartridges still **run** on non-PRO, that would be my assumption...

Yes, they should, only bank switching in the editors is disabled in the non-PRO version.

**Comment by kikeroga3** [comment]
> You can call sync() only once per TIC(), it's a limitation.

Thank you for your reply.
It seems that my understanding was insufficient.

**Comment by nesbox** [comment]
> Oh I knew that... what about outside of TIC though?
> 
> How does one bank switch in PRO? I've compiled from source but still don't see it in the editors.

You can switch banks using `sync()` api no matter pro or nonpro, but edit banks only on pro version.
