### ISSUE TITLE
Mac do I build a Mac executable?

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1342]
I know how to build a `tic80` binary (with make), but how do I build a replacement `tic80` application bundle that I can just drop into my Applications folder?

**Comment by joshgoebel** [comment]
Ok I didn't really need a whole DMG but `make -j4 package` seems to work.

**Comment by nesbox** [comment]
Please, check how we build `.dmg` with `cpack` command on Github Actions https://github.com/nesbox/TIC-80/blob/4a8c6a50d4760b79de8c6ca23f74fecb36d673a2/.github/workflows/build.yml#L251

Unfortunately, there is no option for `.app` bundle, only `tic80` binary and `.dmg`.

**Comment by joshgoebel** [comment]
> Unfortunately, there is no option for .app bundle, only tic80 binary and .dmg.

Seems it [app bundle] can be found in one of the temp folders afterwards, it's just slower to build the DMG also when it's not needed.  But shouldn't be necessary super often, so not a huge deal. :)
