### ISSUE TITLE
(end) add "Debug" to TIC_VERSION_LABEL for debug builds

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1343]
When a debug build is created `version` command and should clearly say it's a debug build.

Reference to discussion: https://github.com/nesbox/TIC-80/pull/1341

**Comment by nesbox** [comment]
Added `(debug)` prefix for debug build here b170a8e
Now it look like:
![image](https://user-images.githubusercontent.com/1101448/107750870-aab6e180-6d2d-11eb-88a0-6e947f27db8e.png)

**Comment by joshgoebel** [comment]
Awesome!
