### ISSUE TITLE
Add the ability to choose destination colors in 1/2BPP source mode

### ISSUE THREAD

**Issue by Popolon** [nesbox/TIC-80#1359]
Currently the 1BPP and 2PP sprite modes don't allow to choose the destination color(s), as far I know. This could allow to have less memory usage but still more color possibilities for this sprites, and should be less slow than a scripted implementation.

For references in former console limitations, I seen, than NES was able to manage 4 different palettes for its 4 (with transparency) colors sprites. So it could be a special palette for sprites. Else it could just map on desired already set colors in background. 3 colors sprites are used in lot of old arcade/console games, including original arcade version of Dongkey Kong or Pac-Man, and lot of C64 (limit was 2 real pixel width pixels to have 3 colors), Collecovision or MSX games. So there are several examples of limitations on those systems to have interesting and funs constraints, but this is probably not the current philosophy of TIC-80 as 3BPP sprites are general mapping.

**Comment by joshgoebel** [comment]
Aren't the colors just chosen from the palette?  in 2-bit mode the first 4 palette colors are used... and I would assume the palette swap RAM would also work...

**Comment by joshgoebel** [comment]
For ways you want PALETTE MAP:

https://github.com/nesbox/TIC-80/wiki/RAM#palette-map

**Comment by Popolon** [comment]
Thanks a lot, and sorry for these question, I didn't find these informations. This is exactly what I searched for.

So what is needed is to mix both 2 bits and palette swap. I tested it and worked fine:

```
function draw2bitsmapped_stuff(map1,map2,map3)
 poke4(2*0x03FFC, 4) -- move to 2 bit source state
 spr(160,140,20,0,2,0,0,4,4) -- draw default color 2 bits sprite
 poke4(PALETTE_MAP * 2 + 1, map1) -- change colors in palette
 poke4(PALETTE_MAP * 2 + 2, map2)
 poke4(PALETTE_MAP * 2 + 3, map3)
 spr(165,140,15,0,2,0,0,1,1) -- draw remapped 2 color sprites
 poke4(PALETTE_MAP * 2 + 1, 1) --restore colors in palette
 poke4(PALETTE_MAP * 2 + 2, 2)
 poke4(PALETTE_MAP * 2 + 3, 3)
 poke4(2*0x03FFC, 2) -- restore 3 bit source state
end

function tic()
 cls(0)
 draw2bitsmapped_stuff(13,14,15)
end
```
