### ISSUE TITLE
Editor does not update when pressing enter

### ISSUE THREAD

**Issue by another-m00** [nesbox/TIC-80#1370]
In the 0.80.1334 build on Windows and web, pressing enter doe not update the editor screen.

-the line count does not update
_-a hightlited bracket soimetimes is diplayed outside of the editor frame (different problem)_
-after a longer line the screen won't follow the cursor

Enter at the end of a long line does not update the screen:
![Long line does not update the screen](https://user-images.githubusercontent.com/71275068/110221615-82a24480-7ecd-11eb-9593-a741bb1dfd9c.gif)
Pressing enter does not update the line count
![Pressing enter does not update the line count](https://user-images.githubusercontent.com/71275068/110221638-9c438c00-7ecd-11eb-9fe5-9ed72c92ffce.gif)

I cound't find similar issue report in the near past, but this might be still a duplice...

**Comment by nesbox** [comment]
Fixed here 5543a60
