### ISSUE TITLE
Flickering bars on Intel graphics card

### ISSUE THREAD

**Issue by Mynotaurus** [nesbox/TIC-80#1374]
When TIC-80 is run on my integrated graphics card (Intel HD Graphics 530) the whole window is overlaid with a set of repeating white bars that change the colours under them (it is hard to explain in words, so I’ve attached a screenshot) These bars either stay stationary or rapidly flicker depending on the dimensions of the window.

I can confirm it is the graphics card as it runs on my dedicated GPU (Nvidia Quadro M1000M) perfectly fine, however as it is on my laptop, it is usually preferable to use the less power hungry iGPU.

![49AEB8D3-7028-43DF-A5DC-965399EACAB4](https://user-images.githubusercontent.com/46263022/111233243-8aa46780-85e4-11eb-85b5-0683e6a9d03b.png)

**Comment by Mynotaurus** [comment]
Just realised I’m using an old version, will update and see if it is still there

**Comment by nesbox** [comment]
Could you pls check `tic80-windows-sdl` version?
You can download it here https://github.com/nesbox/TIC-80/actions/runs/631588932
I suspect the SDLGPU library produces this bug.
Thanks.

**Comment by Mynotaurus** [comment]
Just tried it, appears to have fixed the issue!
