### ISSUE TITLE
code editor scroll on touch screens

### ISSUE THREAD

**Issue by blurymind** [nesbox/TIC-80#1375]
It is currently impossible to scroll down in the code editor without highlighting the text.

Multi-touch scrolling doesnt work, there is no scrollbar and the android keyboard doesnt have up/down arrow keys.

This really breaks usability on android imo

**Comment by nesbox** [comment]
Please try to use the `HAND` icon on the toolbar to drag the code.
![image](https://user-images.githubusercontent.com/1101448/111312281-2f1fbb80-8670-11eb-8fd7-ad094a0ff7e1.png)

And we are going to restore the TIC's keyboard with arrow keys in 0.90
