### ISSUE TITLE
Segfault - 0.80.1345 Pro Build - Ubuntu 20.04

### ISSUE THREAD

**Issue by ben-clegg** [nesbox/TIC-80#1378]
I bought the pro version of TIC-80 from itch.io, and installed the .deb on my Ubuntu 20.04 machine. 
When I launch the program from the desktop entry, it often spikes my CPU load and memory usage and hangs without recovery. 
When launching with the command `tic80`, I sometimes get a trace like the following:

```
 TIC-80 tiny computer 0.80.1345 Pro
 http://tic80.com (C) 2020
[1]    38951 segmentation fault (core dumped)  tic80
```

I'm not sure what's happening. Am I perhaps missing a dependency?
Please let me know if I can provide any more useful information.

System spec: 
```
i5-7200U @ 4x 3.1GHz
~8GB RAM
```

**Comment by ben-clegg** [comment]
I get the same problem when building from source as well.

**Comment by RobLoach** [comment]
Not getting the same error here on Ubuntu 19.04. Could you build with debug and try to figure out where the segfault happens?

**Comment by ben-clegg** [comment]
Hi @RobLoach, thanks for the quick reply. 
As I shut down for the night I remembered I had a similar issue with the Godot Engine, caused by an Intel graphics driver problem on some machines. 
I tried the same fix for TIC-80 and it runs exactly as I'd expect.

If anyone else is searching and has a similar segmentation fault, you have to add something in your CLI before running TIC-80, for example: 
`MESA_LOADER_DRIVER_OVERRIDE=i965 DRI_PRIME=0 ./tic80` (or `MESA_LOADER_DRIVER_OVERRIDE=i965 DRI_PRIME=0 tic80` if you're running a packaged copy should work.)
