### ISSUE TITLE
Black Screen after install

### ISSUE THREAD

**Issue by Chris-Leeworthy** [nesbox/TIC-80#1379]
Hi,

I downloaded TIC-80 0.80.1344 on my intel Mac running Big Sur version 11.2.3

After dragging the icon to the Applications folder and allowing the software to run I get a TIC-80 window and I hear the start chime, but the content of the window is completely black.

If I hit Escape to go into editing mode I can see the mouse pointer change to a text insert mark, but the screen stays black and I can't see anything if I try to type something in.

![Screenshot 2021-03-22 at 12 54 57](https://user-images.githubusercontent.com/13499355/111992912-db005580-8b0d-11eb-8d9b-0422bc65bb62.png)

Update: This also happens if I build the TIC-80 from source.

**Comment by nesbox** [comment]
Pls try this one [tic80-macos-sdl.zip](https://github.com/nesbox/TIC-80/files/6184355/tic80-macos-sdl.zip)
This is the latest dev build.
Thank you.

**Comment by Chris-Leeworthy** [comment]
Thanks for getting back to me so quickly.

I tried the newer build, but got the same problem.

![Screenshot 2021-03-23 at 08 44 07](https://user-images.githubusercontent.com/13499355/112118117-f58d0a00-8bb3-11eb-8ec3-cc511dfd0732.png)

**Comment by nesbox** [comment]
Just checked on Big Sur 11.3 Beta (20E5224a) and all is ok.
Please, leat us know if you find something.
Thank you.

**Comment by Chris-Leeworthy** [comment]
All working OK for me now.  Thanks for your help.

**Comment by DannyCork** [comment]
can be closed
