### ISSUE TITLE
Update wiki: CHUNK_SCREEN, tic_screen, sync, etc.

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1380]
Main f6bd43f changes:
- added a new chunk `CHUNK_SCREEN` to every bank
- `tic_screen` is a `240 x 136 x 4bpp` raw buffer, you can copy it to `VRAM` using `tic_api_sync(...)`
- all the import/export commands use `.png` format now

_Originally posted by @nesbox in https://github.com/nesbox/TIC-80/issues/1001#issuecomment-804726957_

**Comment by joshgoebel** [comment]
@nesbox You can assign to me.

**Comment by joshgoebel** [comment]
Just to confirm, Screen is NOT loaded into VRAM upon boot up like many of the other data types, correct?

**Comment by joshgoebel** [comment]
@nesbox To be clear this is just the 16320 bytes of screen, not all of VRAM, right?

**Comment by nesbox** [comment]
Right :)
Sorry for the delay with the response.
