### ISSUE TITLE
Setting sustain=true in the music() API does nothing.

### ISSUE THREAD

**Issue by icwass** [nesbox/TIC-80#1381]
The Sustain setting in the music editor (i.e. this ![sustain_icon](https://user-images.githubusercontent.com/64374645/112544278-cda0d080-8d84-11eb-9797-acadd9b82412.PNG) button) works correctly when doing playback in the music editor.

However, calling the music() API plays music with sustain=false, _even if the sustain parameter is set to true_. That is, "music(x,y,z,loop,false)", "music(x,y,z,loop,true)" and "music(x,y,z,loop)" all have the same effect.

I've attached a cart that demonstrates the bug.

[bad_sustain.zip](https://github.com/nesbox/TIC-80/files/6207971/bad_sustain.zip)

![Screen Shot 2021-11-05 at 12 55 12 AM](https://user-images.githubusercontent.com/6473/140460311-30aa5ebe-1dcd-4fc6-af38-f76d9e48298e.png)

(This bug is occurring in version 0.80.1345 Pro on my Windows 7 laptop.)

**Comment by Weeppiko** [comment]
I was wondering if someone ever noticed this, but for some reason the sustain parameter does not work when set it to true but it does work when set to 1 instead

**Comment by joshgoebel** [comment]
Could either of you provide a working test program that could be copy/pasted to show this?

**Comment by icwass** [comment]
Here's an updated cart that demonstrates the bug - the sustain parameter does not work when set to true, but it DOES work when set to 1.

[bad_sustain_2.zip](https://github.com/nesbox/TIC-80/files/7479537/bad_sustain_2.zip)

(This bug is occurring in version 0.90.1723 Pro on my Windows 10 desktop.)

**Comment by joshgoebel** [comment]
**Seems to work here.**  Both `true` and `1` AND `0` work as they are truthy in Lua.  `false` disables sustain.

If anything is surprising it is the `0`, but that's just normal Lua behavior... unless our API goes out of the way to hide that in other places?

**Comment by nesbox** [comment]
dup of #1553 which was fixed
closing

**Comment by icwass** [comment]
> **Seems to work here.** I'm using the latest source from Git.

Makes sense if the latest source from Git is more up-to-date than the itch.io download.

> `true` and `1` AND `0` all work (sustain is enabled) as they are truthy in Lua.
> The API docs also clearly state the input here should be a boolean.

Yep, I know this, was just pointing out that of these options, only '1' seemed to work on my version.

Glad to know this issue is fixed!
