### ISSUE TITLE
Request for TIC-80 PRO version

### ISSUE THREAD

**Issue by kikeroga3** [nesbox/TIC-80#1382]
I want TIC-80 PRO EX (16 x more resources).
I'll buy it for 10 $.

Thnk you.

**Comment by RobLoach** [comment]
You could save $5 by buying it through the normal streams https://nesbox.itch.io/tic80

**Comment by BrunoDSL** [comment]
> I want TIC-80 PRO EX (16 x more resources).
> I'll buy it for 10 $.
> 
> Thnk you.

By the time you add more resources, you're kinda defeating the purpose of the thing, really. You're better off using a modern engine, like Godot, and making your projects look like they're low res.

**Comment by joshgoebel** [comment]
Worth noting that with bank syncing in PRO already you already have 8x more resources than you may have realized. :-)

**Comment by nesbox** [comment]
> I want TIC-80 PRO EX (16 x more resources).

I doubt this will ever happen, sorry.
