### ISSUE TITLE
TIC-80 for Debian arm64

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1389]
Request from itch.io https://itch.io/t/1298710/tic-80-for-debian-arm64

**Comment by technomancy** [comment]
I'm using TIC-80 on my arm64 machine, and it works great out of the box. Do you need any help testing things? Or is this specifically about setting up a cross-compiler in the CI config?

**Comment by nesbox** [comment]
I think this is about setting up CI config.
Any help is appreciated :)

**Comment by nesbox** [comment]
ok, let's wait...

**Comment by aliceisjustplaying** [comment]
I've set up a system for unofficial linux/arm64 nightly builds in https://github.com/nesbox/TIC-80/pull/2586. See [this section of the README](https://github.com/nesbox/TIC-80?tab=readme-ov-file#unofficial-linuxarm64-nightly-builds) for details.
