### ISSUE TITLE
Ctrl+A (Select All) on Website clears code

### ISSUE THREAD

**Issue by trelemar** [nesbox/TIC-80#139]
With native version it works correctly, ctrl+a selects all of the code. In-browser through website this error occurs.

Using Ubuntu-MATE with Mozilla Firefox.

**Comment by trelemar** [comment]
Seems that with selection highlighted ctrl+c clears it as well. will try a different browser and report back.

**Comment by nesbox** [comment]
OMG, I reproduced it in Firefox on Windows
very strange, thanks

**Comment by frenetic** [comment]
It is not detecting the `CTRL` key...

**Comment by frenetic** [comment]
I was looking at it again.
It is detecting 2 keystrokes instead of 1.
It is detecting `CRTL+A` then `A`, instead of only `CRTL+A`.
It happens to other combinations like `CRTL+Z`.

**Comment by frenetic** [comment]
Just tested this on latest Firefox and Chrome. It is working fine. I think it is safe to close.
