### ISSUE TITLE
TIC-80 Crashes when I stream it in a Discord voice channel.

### ISSUE THREAD

**Issue by IAmTheRealXYZ** [nesbox/TIC-80#1398]
Hi!
So I recently started using TIC-80 after getting tired of PICO-8 slightly, and I really liked it more than PICO-8 to be honest.
The only problem I had with it, is that whenever I try to share my TIC-80 Tab (or "Screen") in Discord, by joining a voice channel, clicking on the "Screen" button on the bottom left, and choosing "TIC-80", the software crashes and all my unsaved stuff goes to heaven.
I am using TIC-80, version 0.80, Non-Pro, on Windows.

**Comment by nesbox** [comment]
Someone else previously reported the same issue, I'll try to investigate.
Thank you for the report.

**Comment by IAmTheRealXYZ** [comment]
> Someone else previously reported the same issue, I'll try to investigate.
> Thank you for the report.

No problem, mate! :D

**Comment by nesbox** [comment]
Unfortunately, can't reproduce it on my side, but I've added some fixes here 9a1966a where I think the crash could be.
Please check it and let us know.
Thank you.

**Comment by AMcBain** [comment]
I can unfortunately report this is still a thing in the latest pro version. 🙁
