### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by MasterFoof** [nesbox/TIC-80#1399]
In the demos the game Quest or Quest for Glory when I edit it to see inside the project I see colors that are not in the normal TIC-80. How do I access those colors? (I have Pro Version)

**Comment by nesbox** [comment]
Click on the `Advanced mode` switch and then `Edit palette` and you will see palette RGB sliders.
Also, you can copy/paste palette you want.
![video10](https://user-images.githubusercontent.com/1101448/113886230-2f235f00-97c9-11eb-811c-dbc77fe0362e.gif)

**Comment by MasterFoof** [comment]
Oh, thank you so much!
