### ISSUE TITLE
TIC-80 Libretro savegame issues

### ISSUE THREAD

**Issue by fry-guy** [nesbox/TIC-80#1410]
The savegame function is not working with this game https://tic80.com/play?cart=873 in the TIC-80 libretro core.

The savegame will load if you reset the game without exiting retroarch. However, once you exit the game and reload, it will not work and you get the following error message. 

"[string ="title: Shadow Over the Twelve Lands..."]:1353: !P_L0 stack traceback"

The game description contains some details related to this issue. But it suggests it should work as long as you're not trying to play in the Chrome browser. (It says "if you are playing this seriously, consider downloading the cart and playing in the TIC-80 program.")

As background, I am running retroarch in ArkOS on the RG531P. Here is more information about ArkOS: https://github.com/christianhaitian/arkos. And here is the Github for the game in question: https://github.com/btco/so12l

Any ideas why the game will not load? Thank you for your help!

**Comment by RobLoach** [comment]
Thanks for the heads up. libretro just stores what's in `pmem()` to the save, and it's up to the cart how/what is in `pmem()`.

Another good one to test this with is [Multiplayer with pmem](https://tic80.com/play?cart=893). It stores all the player characters in the pmem values each frame, so can be a good way to test.

**Comment by fry-guy** [comment]
Hi! Thanks for replying. I also found this tool, created by the same dev who made the game, which tests the pmem value. http://tic80.com/play?cart=185

This seems to show that the pmem value is staying in memory across game launches. So the crashes when trying to load the save game seem unrelated to the pmem?

**Comment by fry-guy** [comment]
Good morning,

With the help of the developer, I updated the TIC-80 core on my installation of ArkOS to the latest version, which resolved the savegame issues but introduced slowdowns and audio stutter. https://github.com/christianhaitian/arkos/issues/323

Any idea why this may be happening?

**Comment by joshgoebel** [comment]
> I updated the TIC-80 core on my installation of ArkOS (0.90.1579-dev) to the latest version, which resolved the savegame issues 

Awesome.  That would close this issue then.

> but introduced slowdowns and audio stutter.

Could you please create a second issue for that if you're still seeing that with a fresh build?

**Comment by joshgoebel** [comment]
> That would close this issue then.
