### ISSUE TITLE
Update wiki: Added music tempo/speed parameters to the RAM here 8c1e0ae (the wiki will be updated after 0.90 release)

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1412]
Added music tempo/speed parameters to the RAM here 8c1e0ae (the wiki will be updated after 0.90 release)
so, music `tempo`, `speed` can be poked by `0x14E04/0x14E05` addr now

```
+-----------------------------------+
|           96KB RAM LAYOUT         |
+-------+-------------------+-------+
| ADDR  | INFO              | BYTES |
+-------+-------------------+-------+
           ...
| 14E04 | MUSIC PARAMETERS  | 2     |
           ...
+-------+-------------------+-------+
```

> Also, you can add a channel mute function. Unless, of course, it overloads the system.

Try to poke a sound register volume to mute the channel https://github.com/nesbox/TIC-80/wiki/RAM#sound-registers

Thank you.

_Originally posted by @nesbox in https://github.com/nesbox/TIC-80/issues/1193#issuecomment-820354160_

**Comment by nesbox** [comment]
#1193 is reverted because breaks compatibility with some carts
