### ISSUE TITLE
Bank switching tab not appearing on self-built Linux Pro version

### ISSUE THREAD

**Issue by datguywitha3ds** [nesbox/TIC-80#1413]
Hi, I built Tic-80 (0.80.1344) with the pro parameters a few days ago and now that I wanted to check out bank switching I noticed I'm missing the cart tab that changes banks, I'm pretty sure I'm using the pro version since I can save to .lua, .js and .moonscript files, which is one of the Pro-only features listed on the wiki, am I doing something wrong here?

**Comment by joshgoebel** [comment]
Triple check your build arguments. Likely you aren't building pro at all. See Readme for the correct args.

**Comment by nesbox** [comment]
Also, please check you have `version 0.80... Pro` postfix

**Comment by joshgoebel** [comment]
Note the "Pro" that nesbox is referring to.

<img width="683" alt="Screen Shot 2021-04-16 at 7 03 42 AM" src="https://user-images.githubusercontent.com/6473/115015606-e8e19600-9e81-11eb-8878-cac7a0cffef9.png">
