### ISSUE TITLE
Please add Git SHA to the build number version in console

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1414]
<img width="683" alt="Screen Shot 2021-04-16 at 7 03 42 AM" src="https://user-images.githubusercontent.com/6473/115015655-00b91a00-9e82-11eb-8dac-15a0dd67f28d.png">

It'd be super helpful to add a short SHA after the build version so that at a glance I could tell which version I have installed when doing bug triage.

Here is what we do in Highlight.js:

```
/*!
  Highlight.js v11.0.0-alpha0 (git: 3cc4091b40)
```

IE, this would be really nice to have:

```
version 0.90.1575-dev Pro (c6bd653)
```

**Comment by joshgoebel** [comment]
Perhaps the 1575 does that already?  Honestly I didn't even consider that until this very moment.  But that requires an extra trip to the website to look up if that is a build #... just to turn it into a Git hash so I can find out how it corresponds to what code is installed.

**Comment by nesbox** [comment]
Added Git SHA to the build version cd72193
![image](https://user-images.githubusercontent.com/1101448/115211452-3ff89c80-a108-11eb-8292-5e27c1a517d5.png)
Thank you.

**Comment by joshgoebel** [comment]
Thanks, and whoa, taste the rainbow! Nice.
