### ISSUE TITLE
Continue keyword in Wren doesn't Work

### ISSUE THREAD

**Issue by Joseph02MR** [nesbox/TIC-80#1415]
First I found weird that the word wasn't highlighted. Then after executing my program the console gave me an error.
I'm working in version 0.90.1575-dev

I have some screenshots to show another test:
![screen1](https://user-images.githubusercontent.com/67172507/115101793-a1541c00-9f0c-11eb-861f-903bf0c1f70d.gif)
![screen3](https://user-images.githubusercontent.com/67172507/115101794-a44f0c80-9f0c-11eb-911d-7cd5f5c57ffd.gif)

I tried the same in the wren main page because I started with the language in TIC and i had to make sure that i wasn't doing something wrong
![wren](https://user-images.githubusercontent.com/67172507/115101847-fbed7800-9f0c-11eb-9fd2-0c059a0b6537.gif)

**Comment by RobLoach** [comment]
This is still an issue, but the keyword is now defined. Thanks!

**Comment by joshgoebel** [comment]
Recommend this be closed in favor of #1666.

**Comment by joshgoebel** [comment]
This was resolved in 40b68f7c29a8d3072ab5a30bc421dacc72209a21 with the upgrade to Wren 0.4.
