### ISSUE TITLE
Keyboard shortcuts are broken if input is different than "keyboard"

### ISSUE THREAD

**Issue by scambier** [nesbox/TIC-80#1417]
On Windows, version 0.80.1345

Keyboards shortcuts quickly trigger on/off when the input method is explicitly set to something else than `keyboard`

To reproduce:

- Make a carte with `-- input: mouse` or `--input: gamepad`.
- Try to switch to fullscreen with F11 -> the screen flickers
- Try to record a gif with F9 -> the recording stops after 1 frame

**Comment by nesbox** [comment]
The issue already fixed on 0.90 dev version ba3abf37437b271f26b7dae7d87e25b6a9b80412
Thank you for the report.
