### ISSUE TITLE
Navigate palette with `[` and `]` keys

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1421]

**Comment by nesbox** [comment]
Shortcut changes 3584ea4:
`-` and `=` to change brush size
`[` and `]` to navigate palette

@joshgoebel Please update the Hotkeys sections on the wiki https://github.com/nesbox/TIC-80/wiki/Hotkeys if not difficult
Thank you.

**Comment by RobLoach** [comment]
Added this.... Could likely be worded better. Feel free to update

```
[]                      choose previous/next palette color in the sprite editor
```

**Comment by nesbox** [comment]
Thank you :)
