### ISSUE TITLE
Coloring for special Brackets for long string isn't working for Tic-80 [=[ ]=]

### ISSUE THREAD

**Issue by alexsilent** [nesbox/TIC-80#1426]
Coloring for special Brackets in Lua for long string isn't working:
scn = [=[ Hello World! ]=]
Example: https://tic80.com/play?cart=1820

**Comment by joshgoebel** [comment]
Can you confirm this is still an issue and provide a screen shot?

**Comment by joshgoebel** [comment]
We only support a single type of block string syntax in our highlighter...and currently this is set to `[[` and `]]`?  What is the difference between that and the `[=[` variant?

**Comment by joshgoebel** [comment]
@alexsilent Ping.

**Comment by joshgoebel** [comment]
Closing from inactivity, happy to reopen in future if need be.
