### ISSUE TITLE
Horizontal scrolling while shift is held

### ISSUE THREAD

**Issue by another-m00** [nesbox/TIC-80#1430]
Could you add horizontal scrolling to the editor while shift is held?
It's a common behaviour in applications, but not yet present in the editor.

I think to implement it, the app needs to find the longest line, and allow to scroll to it's length (or +1 character, so its not that annoying to put the cursor at the end of the line) like it scrolls between lines.
The longest line could be the either the longest line onscreen or the longet in the entie code, both are equally good.

**Comment by nesbox** [comment]
ok, will do, thanks

**Comment by nesbox** [comment]
Added horizontal code scrolling with the shift key 2449804

**Comment by another-m00** [comment]
Thank you :)
