### ISSUE TITLE
map editor select appears over show tiles

### ISSUE THREAD

**Issue by 00Her0** [nesbox/TIC-80#1434]
I don't know how to explain it, so here's a screenshot:
![selectGlitch](https://user-images.githubusercontent.com/77644448/116634796-ea936b00-a911-11eb-9766-158d6d4ba10e.png)
If I select map tiles and then press shift, the select thing appears over the available tiles
(I guess this might be on purpose but it looks kind of weird to me, so I'm putting it here anyway.)

**Comment by nesbox** [comment]
Oops, thank you for the report

**Comment by nesbox** [comment]
Fixed here 25c77b7
