### ISSUE TITLE
How to run TIC-80 after build linux

### ISSUE THREAD

**Issue by WildSource** [nesbox/TIC-80#1441]
hello
I'm a new linux user and wanted tic-80. I followed the build instruction and everything went well, but after the commands what do I do to run tic-80 ? I'm very confused and there is no instruction after to explain it

**Comment by RobLoach** [comment]
After building, you'll find a `tic80` executable in the bin directory. Run that :+1:

**Comment by WildSource** [comment]
Thank you so much

**Comment by ChildishGiant** [comment]
Ah this caught me up too as they're not displaying as executables for some reason.

**Comment by joshgoebel** [comment]
> Ah this caught me up too as they're not displaying as executables for some reason.

Are you saying the executable bit isn't set or...?
