### ISSUE TITLE
2 arrow keys are pressed for the entire duration of running a game

### ISSUE THREAD

**Issue by a-pavaskar** [nesbox/TIC-80#1445]
I recently compiled TIC-80 on my system (Archlinux with Plasma).

Whenever I run any program, the Up and the Left arrows are pressed for the entire duration of the runtime, without any actual keyboard input.
(I've tested with two different keyboards; both wired, USB)

- I have attached a relevant gif and picture using the default demo project and the Key Test project.
- If I run TIC-80 in a VM or via firejail, it works perfectly on my system.
- Also, with firejail, if I comment out →
`protocol unix`
, it doesn't work.

I've also tried with different versions, none of them have any difference.
Any help would be appreciated. Thank you!

![TIC-80-input-bug](https://user-images.githubusercontent.com/70765049/117190166-b7167c00-adfc-11eb-8f64-aa50b71d40d8.gif)
![image](https://user-images.githubusercontent.com/70765049/117190487-1c6a6d00-adfd-11eb-8e9c-be9ce709836a.png)

**Comment by joshgoebel** [comment]
> Also, with firejail, if I comment out → protocol unix

Do you know what this means/does? (perhaps as a clue)

**Comment by nesbox** [comment]
dup #1654
