### ISSUE TITLE
M command retriggers note

### ISSUE THREAD

**Issue by phedoff** [nesbox/TIC-80#1446]
(tested on v080pro & v090dev, windows+android)
The notes are being retriggered when using the M command.

How to reproduce:
- enter a note 
- use m command like this
![tic80_m_bug](https://user-images.githubusercontent.com/33154602/117260255-2c12a180-ae4f-11eb-8881-6f632454ec54.jpg)

Also: is there a way to in-/decrease the number of rows faster? not one by one but like +/-5 steps or something like that.

**Comment by nesbox** [comment]
Thank you for the report

**Comment by nesbox** [comment]
Hmm, just tested and can't reproduce, only volume is changing while playing the note.

**Comment by phedoff** [comment]
I don't know which tracker you use else, but compare the audio output. Tried several (lsdj, deflemask, vt2) against it - they all produce a smooth transition, in t80 it sounds like it's retriggered (with changed volume, but that's not the problem).

**Comment by nesbox** [comment]
Ok I got you, we have to add a smooth transition for the volume changing :)

**Comment by phedoff** [comment]
Great. What about the question below the screenie? About increasing / decreasing the number of rows faster?

**Comment by nesbox** [comment]
There is no way to increase / decrease rows faster, I suppose the JUMP command doesn't do this.
How does it usually look in other trackers?
Thank you.

**Comment by phedoff** [comment]
in pico8 you can use the shift key for such tasks
(from their manual)
![2021056506_130750](https://user-images.githubusercontent.com/33154602/117289090-7c4c2c80-ae6c-11eb-917e-4b113d769e8e.png)
on other trackers you can enter it directly, could be a "problem" in tic-80 (at least a lot of code maybe) - deflemask:
![Screenshot_20210506-130310](https://user-images.githubusercontent.com/33154602/117289332-c03f3180-ae6c-11eb-8cca-39bbdffeafdb.png)
I think the shift key could be a good way and would probably be easier to be implemented (if you consider to add this, but it would definitely be great :))

**Comment by nesbox** [comment]
Oops, I didn't understand you correctly again, so...
I agreed, the shift key is a good way, will do it soon.
Thanks.

**Comment by phedoff** [comment]
Nice, thanks a lot.

**Comment by nesbox** [comment]
Added increase/decrease tempo/speed/rows by -5/+5 values if shift pressed 352d0f6
As for smooth transition for the volume changing pls use fading for the instruments or smth like that.
