### ISSUE TITLE
Cursor shows over bookmarks tab

### ISSUE THREAD

**Issue by 00Her0** [nesbox/TIC-80#1447]
Screenshot:
![cursorGlitch](https://user-images.githubusercontent.com/77644448/118562706-13916980-b722-11eb-972e-81f1f444d3eb.png)
The cursor is also drawn on top of bookmarks on that tab:
![cursorGlitchBookmarks](https://user-images.githubusercontent.com/77644448/118562907-74b93d00-b722-11eb-8f0f-ea47faae430d.png)
and letters shadows are drawn with it:
![cursorGlitchLetters](https://user-images.githubusercontent.com/77644448/118562977-974b5600-b722-11eb-821a-454ae92669f3.png)

**Comment by nesbox** [comment]
Hi
How to reproduce?
Thanks.

**Comment by 00Her0** [comment]
Put your cursor near the bookmark tab, and then right-click and drag. (sorry, I forgot to put that in the original error

**Comment by 00Her0** [comment]
Here's a gif of this:
![cursorGlitchGif](https://user-images.githubusercontent.com/77644448/118699626-979d2d00-b7c6-11eb-806d-769a6ffaf6b9.gif)

**Comment by nesbox** [comment]
Got it, thank you for the report.

**Comment by nesbox** [comment]
Fixed here 9a4decf
