### ISSUE TITLE
[Suggestion] return a height value for the print() statement

### ISSUE THREAD

**Issue by blazelink3** [nesbox/TIC-80#1450]
As the title suggests, implement some sort of function that allows you to find the height, as well as width of any text string, be it by print or otherwise (given the relative inefficiency of having to print a statement once to get the dimensions of the text, then again to actually output the text.)

**Comment by joshgoebel** [comment]
Height is 99% of the time going to be the same no?  Am I missing something?

**Comment by blazelink3** [comment]
> Height is 99% of the time going to be the same no? Am I missing something?

it's true mostly, but in writing a dialogue system, or a tooltip, I've found the need to use a newline operator in a string to make it fit onscreen, which throws off alignment worse and worse the more lines created. I recognise it's a relatively niche desire, and could probably be fixed in other ways but having the ability for the TIC-80 to figure out how "tall" any given text is would essentially eradicate the problem where I could never figure out how much extra space would be needed,

**Comment by joshgoebel** [comment]
Just count the newlines... easy.

**Comment by blazelink3** [comment]
I'm sorry if I wasn't being clear before, but my problem, is with the height of individual lines + line spacing- 
```
function dialogueBox(text,x,y)
	--side stuff
	local padL = 2
	local padR = 2
	local padT = 2
	local padB = 2

 -- important variables
	local lineCount = 2 -- because i'm too lazy to write an actual line counter
	local lineHeight = 7	
	local dialogueWidth=print(text,x,y)
	
	--drawing it
	rect(x,y,
	dialogueWidth+padL+padR,
	(lineHeight*lineCount)+padT+padB,8)
	print(text,x+padL,y+padT,12)
end
```

if we set lineHeight to 7, for instance, here it is too large at the bottom- it's only meant to have 2 pixel gap, which obviously it doesn't

![image](https://user-images.githubusercontent.com/19394539/119016424-d6331300-b991-11eb-9c5b-5aea9e6bd1c1.png)

but if we increase the number of lines as shown here:

![image](https://user-images.githubusercontent.com/19394539/119016564-fd89e000-b991-11eb-8b70-806f47d8fb7e.png)

suddenly it's too small, and if we kept adding lines, the problem would only get worse, and increasing the variable we assign to be the height of the characters and inbetween line spacing only breaks it differently, 7.5 makes it about right in the 5 line example above, but making it 8 lines, just for the sake of testing or whatever massively screws it up again:

![image](https://user-images.githubusercontent.com/19394539/119017027-7b4deb80-b992-11eb-9aed-6594471030cc.png)

I'm genuinely sorry if I come off as pushy or annoying, it's just that I've never found a solution that could satisfactorily solve this problem aside from "Write better", which isn't guaranteed to help.

**Comment by joshgoebel** [comment]
I found the bug:

```
 -- because i'm too lazy to write an actual line counter
```

Count the lines.  If you have 7 lines, make the box 7*8... if you have 2 lines, make the box 2*8, etc (plus padding etc)...

**Comment by blazelink3** [comment]
![image](https://user-images.githubusercontent.com/19394539/119018916-8a359d80-b994-11eb-97cd-9668587872cf.png)

I tried it, but again, it makes the box too big or small, depending on line count, like, I guess i'll just leave it there, if only to stop continuing to waste your time, but still, it would be a nice thing to have to just let the TIC handle it for you

**Comment by joshgoebel** [comment]
> I tried it, but again, it makes the box too big or small, depending on line count,

How?  _Each line is a fixed height._  

2 lines = 16 pixels + padding
5 lines = 40 pixels + padding
10 lines = 80 pixels + padding

It's just math.  You aren't explaining HOW or WHY the box is too small...

Print the # of lines on the screen somewhere, print the height of the box... where is the problem happening?

**Comment by potato25** [comment]
The height of the text is always constant

**Comment by joshgoebel** [comment]
Since This would be a breaking API change (returning 2 values, an array, a struct, etc)... I'm pretty sure the actual request is no go based  on that alone (it would break all existing cartridges that check that return value).

@nesbox Any interest in a `lineCount` utility API... I'm guessing not (since we don't really have ANY pure "utility" APIs outside of what the core runtimes provide)... if not then I think we can close this as a #wontfix.
