### ISSUE TITLE
Process of adding new languages to TIC-80?

### ISSUE THREAD

**Issue by ylluminate** [nesbox/TIC-80#1451]
Curious is there a discussion or explanation somewhere I'm missing for the process of adding new languages to TIC-80?

Would like to see an overview with some specific requirements that need to be met to make this happen.

**Comment by RobLoach** [comment]
Follow what was done in one of the other languages https://github.com/nesbox/TIC-80/tree/master/src/api 

Which one have you been curious about?

**Comment by ylluminate** [comment]
Nice, thanks! There's been some discussion by a [V lang](https://vlang.io/) community member on Discord about adding V and I was just poking about to help them find a starting point.
