### ISSUE TITLE
TIC throws OOMs when trying to run this cart in browser

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1454]
https://tic80.com/play?cart=1860

**Comment by nesbox** [comment]
we have to increase `TOTAL_MEMORY=67108864` to avoid this assertion
https://github.com/nesbox/TIC-80/blob/f724c8c9bbc38d1f8d60707f9e1ce84ca7021f66/CMakeLists.txt#L856

**Comment by nesbox** [comment]
Fixed here a8efce2
Thanks.
