### ISSUE TITLE
TIC-80 crashes as soon as a launch it in Android.

### ISSUE THREAD

**Issue by DinoNuggies4665** [nesbox/TIC-80#1465]
Currently using Samsung Galaxy S9, tried the TIC-80 from the google playstore and the APK from tic80.com, both act the exact same. It didn't do this before, but after a while of not using it it got an update, and that's when the crashes started. I would very much apprecate it if someone were to know the cause of this.

**Comment by nesbox** [comment]
Hi,
Could you pls grab the log from your phone with `logcat` tool.
Here is an example how to do it https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClYXCA0
Thank you.

**Comment by DinoNuggies4665** [comment]
Hey, so I actually deleted it before writing this so I went to go download it again and I ran it to create a log, but then it started working again. However it does say NEW VERSION 0.80.1344 AVAILABLE at the top, but there is no new version in the play store.

**Comment by nesbox** [comment]
It checks version from the tic80.com website and it seems it a bit different.
