### ISSUE TITLE
All unmapped gamepad buttons are mapped to Esc?

### ISSUE THREAD

**Issue by JunoNgx** [nesbox/TIC-80#1468]
While shopping for a engine/platform for my next game, I tried playing a handful of TIC-80 games and had a terrible experience with my Xbox One controller on the web.

There are 12 keys on the controller assigned to Esc:
- 4 D-pads key
- Left and right bumpers
- Left and right triggers
- Left and right thumbstick
- Change view and Options/Select and Start

While I'm not certain if this behaviour is intentional, it is so easy to accidentally end up stuck in the console screen, in which is then impossible to return to the game without putting down the gamepad and typing "resume" into the console (pressing Esc twice will land you in the code menu). The worst part is while using a gamepad, getting into this state is pretty much guaranteed because there are so many ways to end up there (e.g. Using D-Pad as actual D-Pad, or accidentally pressing the thumbstick while playing). I think this is quite an unacceptable user experience.

Is there anything I can do, at least as an individual developer, to avoid this in the release of my game?

**Comment by nesbox** [comment]
We changed this behavior somewhere here #1220, please check the latest dev build https://nightly.link/nesbox/TIC-80/workflows/build/master. Also, we are going to add gamepad buttons mapping setup to the game menu.

**Comment by borbware** [comment]
also, in builds after [this](https://github.com/nesbox/TIC-80/commit/d81ba5b26bf83c91a6a33e08f1b1f0fdcd36eb34) commit (builds 465 onwards), you can give the `alone=1` parameter to remove the "close game" option from pause menu!

**Comment by JunoNgx** [comment]
Thanks for the clarification. Playing the existing uploaded games will be a tad annoying, but good to know that this has been handled going forward.
