### ISSUE TITLE
TIC-80 crash on Windows XP

### ISSUE THREAD

**Issue by H1N1-dev** [nesbox/TIC-80#1469]
v0.80.1344
I downloaded the .exe file from releases, is crashed with error:
` the procedure entry point initializecriticalsectionex could not be located in the dynamic link kernel32.dll.`
TIC-80 support XP? If not, then what is last release for XP?

**Comment by ChildishGiant** [comment]
Are you using the correct build? https://github.com/nesbox/TIC-80/issues/743

**Comment by nesbox** [comment]
Please, try to check `tic80-winxp-sdl` here https://nightly.link/nesbox/TIC-80/workflows/build/master

**Comment by H1N1-dev** [comment]
Nope, this is dont work.

'The procedure entry point inet_pton could not be located in the dynamic link WS_32.dll'

**Comment by nesbox** [comment]
Hmm, I'll try to investigate. Thanks.

**Comment by nesbox** [comment]
I checked it and seems `tic80-winxp-sdl` requires at least Win7, don't know the reason, I'm using `v141_xp` toolchain with Visual Studio as Microsoft recommended, but it doesn't work.
I think the `0.70` is the latest version which can run on XP https://github.com/nesbox/TIC-80/releases/tag/v0.70.6, please check it.

**Comment by H1N1-dev** [comment]
Sorry, i can't check this, i moved to linux. And this works.
But thanks for help :)

**Comment by erloncabral** [comment]
@nesbox Yes, I can confirm that version `0.70.6` works "normally" on XP (Professional SP3 to be precise). It is a pity that the most current version is not working any more, but thanks for indicating the version that still works.

![tic80_2022-11-08_22-50-33](https://user-images.githubusercontent.com/732755/200454962-994da6d8-fbc6-4de3-badc-43f99cc10423.png)
