### ISSUE TITLE
Android touch input not registering

### ISSUE THREAD

**Issue by chrisleewoo** [nesbox/TIC-80#1470]
I am having an issue on the android pro build with touch not working as an input on games that use mouse input. Also, in the editor it is not working to select tabs/text.

**Comment by nesbox** [comment]
Are you having the issue on 0.80?
If yes, please check the latest Android build https://nightly.link/nesbox/TIC-80/workflows/build/master, should be fixed.
Thank you.

**Comment by chrisleewoo** [comment]
Yeah, version 0.80.1330

Using version 0.90.165-dev has solved the issue, thank you. I also appreciate the virtual keyboard coming back.
