### ISSUE TITLE
Custom items for the pause menu

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1472]
Feature suggestion: Ability to add custom items to pause menu from code for restarting level, skipping cutscene, etc.

See [menuitem](https://pico-8.fandom.com/wiki/Menuitem) in Pico-8 API.

**Comment by ElNico56** [comment]
This would need a way to open the menu regardless of how you opened the game (surf or run or ctrl+r)

**Comment by nesbox** [comment]
You can define Game Menu items using `-- menu: ITEM1 ITEM2 ITEM3` metatag.
And handle them in the `MENU(index)` callback.

``` lua
-- menu: ITEM1 ITEM2 ITEM3

function ITEM1()trace("1")end
function ITEM2()trace("2")end
function ITEM3()trace("3")end

GameMenu={ITEM1,ITEM2,ITEM3}

function MENU(i)
  GameMenu[i+1]()
end
```
Also, it doesn't matter now from where you started a game from the Surf or from the Console, the Menu is always showed.
Added here 06fde1279677273856c1daf9f2fa22e337daba3d
