### ISSUE TITLE
Add an additional parameter to peek/poke functions for diferent bit resolutions 

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1475]
Certain TIC-80 RAM and VRAM areas has diferent bit resolutions, varying from 1-bit to 12-bit. see: https://github.com/nesbox/TIC-80/wiki/RAM
in this way, it would be more convenient to access certain areas of RAM and VRAM:

(For retrocompatibility)
* peek addr res  -> val
* poke addr val res

**Comment by StinkerB06** [comment]
I think `peekb()` and `pokeb()` functions would do. Basically, `pokeb(0x20000,255,8)` would be equivalent to `poke(0x4000,255)`.

**Comment by joshgoebel** [comment]
If anything I think you'd have peek2 and peek1 perhaps, for consistency. But I don't think either is necessary in the API because they are so trivial to implement.

**Comment by nesbox** [comment]
3ef73db: added `res=1,2,4,8` parameter to `peek()/poke()` api
Now they looks like:
- `peek addr res=8 -> val`
- `poke addr val res=8`

**Comment by joshgoebel** [comment]
@nesbox I was unaware of this.  Please review https://github.com/nesbox/TIC-80/wiki/peek and see if this seems correct... If so I'll update `poke` accordingly.

Of course this also isn't exactly the same [as what was requested here] since it allows no 1, 2, or 4 but precision access to the high bits, only the low bits... but it's nice and should still be documented.

**Comment by nesbox** [comment]
Thank you, it looks good, one thing about addressing low/hi bits, the `address` parameter is aligned to bits depth.
For example, if you want to get `BITS` of `ADDR` pls call `peek(ADDR * 8 / BITS, BITS)`
for `1bits` call `peek(ADDR * 8, 1)`
for `2bits` call `peek(ADDR * 4, 2)`
for `4bits` call `peek(ADDR * 2, 4)`
for `8bits` call `peek(ADDR * 1, 8)`

another example
```
ADDR  VALUE
0     0b00000000
1     0b00000000
2     0b00000000
3     0b01100000
```
If you want to peek 2bits of the `ADDR=3` with offset `5` pls call `peek(3 * 4 + 5, 2)`

**Comment by nesbox** [comment]
Additional API methods won't help here, because `peek4()` do the same, and `ADDR` is aligned by bits depth here too. :)
So `peek(ADDR, 4) == peek4(ADDR)` where `ADDR` is offset of 4bit value in the RAM.

**Comment by joshgoebel** [comment]
I only meant it might have been easier to explain on 4 wiki pages vs cramming it all into one, but I'll deal. :-)

And now we have  some confusion on when someone should use `peek4` vs `peek(*,4)` :-)

**Comment by joshgoebel** [comment]
@nesbox https://github.com/nesbox/TIC-80/wiki/peek

Better?

**Comment by nesbox** [comment]
Yes, thank you 👍
