### ISSUE TITLE
Sort games by categories / genres label:website

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1476]
Something that I would like to see in the future is that the tic80.com/play page in the category of games can be subcategorized by genre, for example: platforms, races, beat em ups, shoot em ups, puzzles, role-playing games, fights, etc.

Currently on the platform there are about 1840 software scattered. When you open a game you don't know what you're going to play

Note to Nesbox: Sorry, I don't know how to put labels here [website]

**Comment by TimotheeGreg** [comment]
Duplicate of #1436
