### ISSUE TITLE
saveid not working when exporting with alone=1 

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1477]
If I export a windows executable with the new `alone=1` parameter, using saveid does not guarantee that the same savefile is used as in previous exports. Particularly, I noticed that when I make changes in the map editor, the next exported build will use a new save file. Without the `alone=1` parameter, the save file persists with saveid as it should.

Used build: 0.90.1678-dev (74fd7f5), pro version.

**Comment by nesbox** [comment]
fixed here bf110eb
thank you
