### ISSUE TITLE
Update Fennel to 0.9.x

### ISSUE THREAD

**Issue by peterhil** [nesbox/TIC-80#1478]
I have been learning Tic-80 with Fennel, and noticed an old version 0.8.1 is included with Tic-80.

There are some things that would be really nice to have, like:

* Include stack trace for errors during macroexpansion
* Nil safe table lookup operator `?.`
* Support for guards using `where/or` clauses in `match`
* Support `:until` clauses for early termination in all loops

References:

* [Fennel changelog](https://fennel-lang.org/changelog#section-1)

**Comment by nesbox** [comment]
@technomancy could you please participate?
Thank you.

**Comment by technomancy** [comment]
Thanks! I will submit an update once we get the next version of Fennel out; if I do it now it will just be outdated again soon. =) Shouldn't be too long tho.
