### ISSUE TITLE
Website: Name the downloaded cartridges

### ISSUE THREAD

**Issue by peterhil** [nesbox/TIC-80#1479]
Please name the downloaded cart.tic files with the name of the game, so
when clicking ‘download cartridge’ on [Komet game](https://tic80.com/play?cart=610) for example,
the file name should be `komet.tic` instead of `cart.tic`.

- [ ] Name the downloaded cartridge (maybe using `<a href="..." download="name-of-the-game.tic"`)
- [ ] Replace spaces and special characters with dashes or underscores if needed?

References:

* [\<a\>: The Anchor element download attribute - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download)

**Comment by nesbox** [comment]
Dup of #901
