### ISSUE TITLE
Feature request: Drag and drop support on Mac OS X

### ISSUE THREAD

**Issue by peterhil** [nesbox/TIC-80#1481]
It would be really nice to be able to open cartridges on Mac OS X by:

* [ ] Double clicking (associate `.tic`files with the Tic-80.app)
* [ ] Dragging the cartridge into Tic-80.app

References:

* [Launch Services | Apple Developer Documentation](https://developer.apple.com/documentation/coreservices/launch_services?language=objc)
* [Making a View into a Drop Destination | Apple Developer Documentation](https://developer.apple.com/documentation/uikit/drag_and_drop/making_a_view_into_a_drop_destination)

**Comment by DannyCork** [comment]
works great in version 1.0. 1937-dev Pro (893c755)

**Comment by joshgoebel** [comment]
What does?  I just tried the other day and swear neither worked...

**Comment by nesbox** [comment]
Only dragging to the main window works atm.
