### ISSUE TITLE
Website: Can’t upload Fennel cartridges

### ISSUE THREAD

**Issue by peterhil** [nesbox/TIC-80#1482]
I tried to upload a text based and then a binary cartidge on the [upload page](https://tic80.com/add), saved the cover image but it still keeps complaining:

    Please add at least TITLE, AUTHOR and COVER (by press F7) metadata to the cartridge and try again.

Does it expect the metadata to look like Lua comments?

This is the cartridge I tried to upload:
https://github.com/peterhil/tic-demo-platformer/blob/main/src/game.fnl

**Comment by nesbox** [comment]
Hi,
The website accepts `.tic` carts only, in your case you perhaps don't save cover in binary cart.
Please provide the `.tic` cart and we will check it.
Thank you.

**Comment by nesbox** [comment]
I just converted `.fnl` project to cart [game.zip](https://github.com/nesbox/TIC-80/files/6808007/game.zip) and successfully uploaded it to the website.
note: I used 0.80 to convert the cart because in 0.90 `<COVER>` tag is deprecated and this is could be the issue.
