### ISSUE TITLE
Cannot build the 3DS version

### ISSUE THREAD

**Issue by dhollinger** [nesbox/TIC-80#1484]
3DS version fails during `make` with the following error:

```
/usr/bin/ld: /opt/devkitpro/portlibs/3ds/lib/libz.a(compress.o): relocations in generic ELF (EM: 40)
/usr/bin/ld: /opt/devkitpro/portlibs/3ds/lib/libz.a(compress.o): relocations in generic ELF (EM: 40)
/usr/bin/ld: /opt/devkitpro/portlibs/3ds/lib/libz.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bin2txt.dir/build.make:104: bin/bin2txt] Error 1
make[1]: *** [CMakeFiles/Makefile2:572: CMakeFiles/bin2txt.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

devkitpro packages are installed as per the 3DS README file.

This happens when trying to build on the latest master or on the v0.80.1344 tag

**Comment by nesbox** [comment]
I don't the reason for this fail, maybe try to build using the Docker container (https://hub.docker.com/r/nesbox/devkitpro-tic80) we are using to build 3DS version.
Pls, look at https://github.com/nesbox/TIC-80/blob/master/.github/workflows/build.yml#L286 for the build instructions.

**Comment by dhollinger** [comment]
Nice! That worked!

I saw the dockerfile, but hadn't dug into what the container looked like yet.
