### ISSUE TITLE
[0.90 bug] ctrl+r returns multiple times

### ISSUE THREAD

**Issue by ElNico56** [nesbox/TIC-80#1489]
When executing via top right button lua only returns a single error, however when executing via ctrl+r lua throws the same error a couple of times in a row

**Comment by StinkerB06** [comment]
That's because you didn't `cls` at the command line. It shows the previous error and the new error at the same time because the previous error traced wasn't cleared by the `cls` command.

**Comment by ElNico56** [comment]
I did, it throws like 10 errors dude

**Comment by nesbox** [comment]
fixed here a52755c
