### ISSUE TITLE
[0.90] (Win7) getsystemtimepreciseasfiletime error in exported executable 

### ISSUE THREAD

**Issue by RandomUnit** [nesbox/TIC-80#1490]
I have Windows 7 so I've downloaded WinXP version and it launches just fine, but when I do `export win test`, it creates a "test.exe" file in working directory and when I try to launch this executable, it gives me a "getsystemtimepreciseasfiletime not found in kernel32.dll" error.

UPD: When I build Pro version from source with MinGW, it launches fine, but has same issues with exporting.

**Comment by nesbox** [comment]
Added new export target `winxp` here 4fdbdec
Please use `export winxp game.exe` command in your case, you can test it on nightly builds https://nightly.link/nesbox/TIC-80/workflows/build/master
Thank you.

**Comment by RandomUnit** [comment]
works like a charm, thank you so much!

**Comment by c1oudsky** [comment]
Still experiencing this issue on windows 7 with 0.90.1723

**Comment by c1oudsky** [comment]
sorry for asking here, but I have win7 and as I can see from this github's discussions I should downaload XP version, but I can't find it as it's not on the main site. Can someone guide me?

**Comment by Skaruts** [comment]
Wait... windows 7 users should be downloading the XP version?

**Comment by nesbox** [comment]
Yes, windows 7 users should download winxp build.

**Comment by Skaruts** [comment]
Ok then. Thanks. 

Maybe there should be some kind of warning about that somewhere, though.

**Comment by nesbox** [comment]
You're right, I'll try not to forget to add a warning with the upcoming release.
Thanks.
