### ISSUE TITLE
0.90 commands don't work with absolute paths

### ISSUE THREAD

**Issue by scambier** [nesbox/TIC-80#1491]
Hello!

When I execute this command:

```
tic80.exe --skip --cmd load C:\Dev\tic80\mygame\mygame.tic & import code  C:\Dev\tic80\mygame\build\compressed.js
```

I have the following errors:
```
>load C:\Dev\tic80\mygame\mygame.tic
file not found
>import code C:\Dev\tic80\mygame\build\compressed.js
error, C:\Dev\tic80\mygame\build\compressed.js file not loaded
```

After a few tries, it seems that commands like `load` or `import` only work with path relative to tic80.exe. Would it be possible to make them work with absolute paths?

**Comment by ChildishGiant** [comment]
You should be able to use `-fs C:\Dev\tic80\mygame\build` and then use relative paths from there

**Comment by scambier** [comment]
Thanks, that works!
