### ISSUE TITLE
[0.90]No name and author name by pressing Ctrl+S to save cart.png

### ISSUE THREAD

**Issue by JMdmi** [nesbox/TIC-80#1492]
when I save the cart through the command line it works very well but if I later edit the game and press Ctrl + S to save the cartbrige, this happens:
![plataformas](https://user-images.githubusercontent.com/51972389/126051478-ab73be63-0f84-486d-9981-3e01aa5aa007.png)
does not show the title or the author's name
Thanks

**Comment by ChildishGiant** [comment]
I assume the metadata is correctly set? Could you post the cart or at least the comments at the top?

**Comment by JMdmi** [comment]
yes, it is correctly set, because saving by command, the png show the metadata correctly
Save with commands
![plataformas2](https://user-images.githubusercontent.com/51972389/126068160-0947e22a-7e79-430d-946f-71964886588c.png)
then I press Ctrl+S to save and show like the first image I uploaded

**Comment by JMdmi** [comment]
in fact, I even tried without modifying the metadata. And it only works with commands.

**Comment by nesbox** [comment]
fixed here cf2ee24
