### ISSUE TITLE
[0.90] TIC-80 does not start

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1495]
The new 0.90 (both pro and regular) build does not run on my desktop pc: the TIC-80 window opens for a few frames and then closes itself. Restarting the machine did not fix it.

This issue does NOT happen if I build the binaries myself with MinGW with the latest codebase (commit a2ed622bbabf5b144f0e2b2320966e022c87db80). There's a version difference tho: The MinGW build says the version is 1701, not 1706, and informs that a newer version 1706 is available.)

My configuration: 

Win10 x64 Version 1909 (OS Build 18363.1556) / AMD Ryzen 7 3800x / Asus Prime x570-P / Asus Geforce GTX 1060 6GB

On my Win10 laptop, 0.90 runs normally.

**Comment by JMdmi** [comment]
I have the same problem. And the screen turn white:
![image](https://user-images.githubusercontent.com/51972389/126183843-76378f30-4c27-4b81-b6c6-c52dbe098506.png)
 
Windows 10 Pro x64 version 21H1 compilation 19043.1110
Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz   2.70 GHz
4 GB RAM
Direct X 12
Graphics: Intel G41 Express Chipset
The pc had windows 7 and it didn't work either

**Comment by nesbox** [comment]
We have three Windows versions for 0.90:
- `tic80-windows-sdl` 64bit build with SDL2 lib
- `tic80-windows-sdlgpu` 64bit with CRT screen effect
- `tic80-winxp-sdl` 32bit build for windows < 10 (xp 7 8)

You can check them here https://nightly.link/nesbox/TIC-80/workflows/build/stable

Unlike 0.80 where we had only 32bit build for windows < 10, but it has very low performance in comparison with 64bit version

**Comment by JMdmi** [comment]
> We have three Windows versions for 0.90:
> 
> * `tic80-windows-sdl` 64bit build with SDL2 lib
> * `tic80-windows-sdlgpu` 64bit with CRT screen effect
> * `tic80-winxp-sdl` 32bit build for windows < 10 (xp 7 8)
> 
> You can check them here https://nightly.link/nesbox/TIC-80/workflows/build/stable
> 
> Unlike 0.80 where we had only 32bit build for windows < 10, but it has very low performance in comparison with 64bit version

I Thank you very much, the SDL version worked for me.
I bought the pro version. How can I download the pro version of that?

**Comment by nesbox** [comment]
Please wait until the end of this week, I'm going to release hotfixed 0.90 version with sdl pro version, or you can build it yourself :)
Thank you.

**Comment by borbware** [comment]
> We have three Windows versions for 0.90:
> 
> * `tic80-windows-sdl` 64bit build with SDL2 lib
> * `tic80-windows-sdlgpu` 64bit with CRT screen effect
> * `tic80-winxp-sdl` 32bit build for windows < 10 (xp 7 8)
> 
> You can check them here https://nightly.link/nesbox/TIC-80/workflows/build/stable
> 
> Unlike 0.80 where we had only 32bit build for windows < 10, but it has very low performance in comparison with 64bit version

Out of the stable windows builds, the Sokol version was the only one that worked for me: both sdl and sdlgpu closed right away

**Comment by nesbox** [comment]
> Out of the stable windows builds, the Sokol version was the only one that worked for me: both sdl and sdlgpu closed right away

And does 0.80 run your config (Win10 x64 Version 1909 (OS Build 18363.1556) / AMD Ryzen 7 3800x / Asus Prime x570-P / Asus Geforce GTX 1060 6GB)?
Do you have Visual Studio to build and debug to find the crash reason?

**Comment by borbware** [comment]
yeah all editions of version 0.80 run fine on my desktop pc. i can try building with visual studio, tho i've been unsuccessful with it before so i've only used mingw, really.

**Comment by borbware** [comment]
![image](https://user-images.githubusercontent.com/19384640/126322902-28426c79-7e04-40c4-a8ed-74d2d1484322.png)

yeah, sorry. visual studio doesn't want to play with me :(

**Comment by nesbox** [comment]
you have to choose `tic80.exe` as a Startup Item
![image](https://user-images.githubusercontent.com/1101448/126323595-4d888d0e-1343-4a5f-9a86-4cf2e1b05bac.png)

**Comment by borbware** [comment]
![image](https://user-images.githubusercontent.com/19384640/126324491-1d3c77f4-6674-42dd-b1cb-315206cccf98.png)
hmm... my visual studio looks quite different. i don't see tic80.exe as an option anywhere.

Anyway, I finally managed to build the thing - I right-clicked on ALL_BUILD and selected "Build" which actually successfully built the exe. I tried opening the executable and it crashed right away, as before...

**Comment by nesbox** [comment]
ok, we are close to the truth, now try to run with VS debugger but before, right-click on `tic80` project in the Solution Explorer and check `Set as Stratup Project`, then run the debugger.
![image](https://user-images.githubusercontent.com/1101448/126325623-62f29b34-67d5-425d-a294-069082116ab9.png)

**Comment by borbware** [comment]
okay! I now did it - I set tic-80 as startup project and ran the Local Windows Debugger, which resulted in this:

![image](https://user-images.githubusercontent.com/19384640/126326498-e71bef4a-83b6-415a-8856-7ab29e4f3021.png)

**Comment by nesbox** [comment]
hmm, does VS show you the place where the crash occurs?
could you go through the running process using `F10/F11` keys to locate the crash or error?

**Comment by borbware** [comment]
i'm doing it now (holding down F11), and it seems to take forever; i feel like i'm stuck in SDL_dynapi_procs.h...

**Comment by nesbox** [comment]
ok, let's go to the https://github.com/nesbox/TIC-80/blob/7e1d69c9bb4229a4fc723b3bf4dfbaf7082d0192/src/system/sdl/main.c#L1670
toggle breakpoint (press `F9`) and run the project by `F5` and then go through the code by `F10/F11`

**Comment by borbware** [comment]
I added breakpoint on that line, and run the project. Then, pressing F10 resulted in this: 
![image](https://user-images.githubusercontent.com/19384640/126334388-a567050f-c1b4-487e-b92d-5087d6093f5d.png)

**Comment by nesbox** [comment]
weird, maybe do a full rebuild and try again, or try to find the commit which works fine
only you can help to fix it atm

**Comment by borbware** [comment]
Okay my bad, the configuration was accidentally changed from Debug to Release. Now I can try with the breakpoints again. The program doesn't crash before the line 1670 breakpoint, it might happen somewhere inside studioInit. I'll make more breakpoints and try to see where it crashes.

**Comment by borbware** [comment]
Okay found the issue. `fs_exists(path)` returns `false`, and the program exits at line 2085.

![image](https://user-images.githubusercontent.com/19384640/126336642-5ac9821a-fc4d-4708-bd0d-5a2ed4189077.png)

**Comment by nesbox** [comment]
ok, what is the `path` value?

**Comment by borbware** [comment]
`path	0x00007ff6ea2526f0 "C:\\Users\\MyUserName\\AppData\\Roaming\\com.nesbox.tic\\TIC-80\\"	const char *
`

**Comment by nesbox** [comment]
ok, waiting for the reason, because I don't know what else to say :)

**Comment by borbware** [comment]
Sorry for the hassle, the problem was unrelated to version 0.90. I had used a symbolic link to move the TIC-80 appdata folder to my cloud storage, and recently had renamed a folder which broke the symbolic link, which in turn crashed (apparently only the new version of) TIC-80 on startup. Fixing the symlink made TIC-80 work again. Closing the issue now.

**Comment by nesbox** [comment]
:)

**Comment by borbware** [comment]
At least I learned how to debug with Visual Studio. Thanks for the patience and sorry again 😅
