### ISSUE TITLE
Won't Start in Firefox

### ISSUE THREAD

**Issue by christopher-kleine** [nesbox/TIC-80#1496]
The latest version of TIC-80 (0.90.1706) won't start in Firefox 90.
Example Cartridge: https://tic80.com/play?cart=2009
The console reports:
```
Uncaught (in promise) RuntimeError: abort(LinkError: import object field 'a' is not a Memory). Build with -s ASSERTIONS=1 for more info.
    abort https://tic80.com/js/tic80.js?0.90.1706:1
    instantiateArrayBuffer https://tic80.com/js/tic80.js?0.90.1706:1
```

I checked this on Windows (10) and Linux (Arch Linux). Both show the same error.
Chrome and Chromium however work just fine.

**Comment by ChildishGiant** [comment]
Hmm I'm having no issues on Firefox 90 or 89 on Elementary OS (Ubuntu 18.04.4), also on 0.90.1706

**Comment by nalquas** [comment]
I'm having the same issue on Manjaro with Firefox 90.0, though the error message sometimes seems to be a bit longer on my end:

![Screenshot_20210720_003320](https://user-images.githubusercontent.com/22664233/126236053-37a81aaa-db20-4cbc-9106-0f3c87bb94c3.png)

**Comment by nesbox** [comment]
I just tested on Chrome, Firefox, Opera, Edge and all is ok.
Anyway, I made some changes to ensure your browser loads the proper `tic80.wasm` file.
Could someone recheck it pls?

**Comment by nalquas** [comment]
Seems to work fine on my end now, thanks

**Comment by christopher-kleine** [comment]
Same for me. It now works like a charm. Both on Linux and Windows. Thanks! :smile:
