### ISSUE TITLE
TIC-80 is not opening on linux

### ISSUE THREAD

**Issue by vaaako** [nesbox/TIC-80#1501]
Hello, I'm trying to open TIC-80 in **Linux** Mint 20 (I already tried it in Linux Mint **20.1**, and it gave the same error) and every time I try to open the TIC-80 in version 0.90, 0.80 and 0.70.6 and it returns the following error:

**TIC-80 0.90**
```
 TIC-80 tiny computer
 version 0.90.1706 (a838293)
 https://tic80.com (C) 2017-2021
malloc(): invalid next size (unsorted)
Abortaded (core image recorded)
```
**TIC-80 0.80**
```
 TIC-80 tiny computer 0.80.1344
 http://tic80.com (C) 2020
malloc(): invalid next size (unsorted)
Aborted (core image recorded)
```
**TIC-80 0.70.6**
```
 TIC-80 tiny computer 0.70.6
 http://tic.computer (C) 2017
malloc(): invalid next size (unsorted)
Aborted
```

I've tried to solve this error with other Issues or in other forums, but I wasn't successful
whoever can help me, I'll thank you very much

**Comment by nesbox** [comment]
Hi,
Please, try to check `tic80-linux-sdl`
https://nightly.link/nesbox/TIC-80/workflows/build/stable
Thank you.

**Comment by vaaako** [comment]
> Hi,
> Please, try to check `tic80-linux-sdl`
> https://nightly.link/nesbox/TIC-80/workflows/build/stable
> Thank you.

Wow, it just **works**, thank you so much.
