### ISSUE TITLE
javascript bug and 65535 character limit

### ISSUE THREAD

**Issue by skz1024** [nesbox/TIC-80#1505]
![tic80_0 9_picture1](https://user-images.githubusercontent.com/66052782/126387772-9219eb44-b945-46e2-8019-fb9c37857034.PNG)
// script: js
this runs fine

![tic80_0 9_picture2](https://user-images.githubusercontent.com/66052782/126387778-f4028b8b-22a3-40c4-b879-7a7db41959cf.PNG)
![tic80_0 9_picture3](https://user-images.githubusercontent.com/66052782/126387779-1a834a0b-2eff-421d-835f-10935b799c24.PNG)
// script: javascript
this is an error

tic80 ver 0.8 is script: javascript using not error. so ver 0.9 is change script type?
and this error after using I can't even load the cart using surf.
After that, when I delete the error and load the cart, stop the console and I can't do anything.

![tic80_0 9_picture4](https://user-images.githubusercontent.com/66052782/126389418-5c7b6697-790e-4197-897d-e3e837ce6dca.PNG)

After the version change, you can no longer enter more than 65535 characters. But execution is possible.

**Comment by nesbox** [comment]
How important is it for you to use `// script: javascript` instead of` // script: js`?

The `65535` characters limit is for the regular version, in PRO you have `65535*8=524288` characters to edit.

**Comment by skz1024** [comment]
1. ![tic80_script_tag](https://user-images.githubusercontent.com/66052782/126617409-15764e17-5015-4132-a1d5-8d7e2b4cc0ed.PNG)
Looking at the wiki, `//script: js is correct.`

![tic80_script_tag_0 7](https://user-images.githubusercontent.com/66052782/126619237-34348948-70cb-4195-8122-acff2326b7cc.PNG)
but version 0.7 and 0.8 is support type: `// script: javascript` and `// script: js`
I didn't notice the `//script: javascript` mistake when creating the game in previous versions. The game run and I thought there was no problem.
However, for this problem, I can fix the game.

2. version 0.7 is 65535 limit for regular version.
but version 0.8 is remove codebank and 64K compress data and 524288 character limit.
![tic80_codelimit](https://user-images.githubusercontent.com/66052782/126616118-e0b2e5de-9c42-41d3-83a6-a9330ab9d6fa.PNG)
![tic80_codelimit2](https://user-images.githubusercontent.com/66052782/126616735-22f80a9e-980c-4a28-88e4-4013d518ebb1.PNG)
![tic80_codelimit3](https://user-images.githubusercontent.com/66052782/126616781-3ba3f49d-faaa-4f46-b917-b8e8fad6fc00.PNG)

**Comment by nesbox** [comment]
It turned out some people have games with code that can't be compressed in 64K but still < 524288.
So, to put it simply, we're back to the 0.70 schema where you had a code size of 8 * 64KB in the Pro version.
If your game is> 64K it will work everywhere, but it can only be edited in Pro.

**Comment by skz1024** [comment]
Then, from version 0.9, the limit is 65535 characters. pro is limited to 524288 characters.
64K compression removed. I'm thinking right?

**Comment by nesbox** [comment]
yes, you're right.
