### ISSUE TITLE
Feature request (music editor): Use "Play from now" to play the whole track

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1515]
The "play from now" feature in music editor (shift+enter) is nice, but I'd like it to play the whole track instead of looping the pattern. It would be more useful for me so I could start playing a track from halfway through.

Note that this change would pretty much mean that its keyboard shortcut should be shift+space then.

Alternatively, I guess both "play pattern from now" and "play track from now" could be implemented, but imo the latter is more useful, and the music editor has quite many icons already; having just one of them would keep the UI a bit cleaner. Suggestions welcome!

**Comment by nesbox** [comment]
`PLAY FROM NOW` plays whole track 89c15a7
