### ISSUE TITLE
Feature request (music editor): a faster way to change tempo

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#1516]
Now that tempo can be changed by an accuracy of 1 bpm, it's very slow to change tempo from, say, 100 to 200.

Propositions:
A) make tempo a keyboard-editable field like pattern ID
B) press and hold tempo UI arrows with left mouse button to change tempo faster

**Comment by nesbox** [comment]
Please, use `shift+left click` to change values by `5`.
