### ISSUE TITLE
(bug) Texttri use_map argument results in weird UV behaviour

### ISSUE THREAD

**Issue by blazelink3** [nesbox/TIC-80#1523]
`
function TIC()
	cls()
	textri(
		0, 0, -- X1, Y1
		0, 16, -- X2, Y2
		16, 0, -- X3, Y3
		--UV
		0,0, -- U1, V1 
		0,16, -- U2, V2
		16,0, -- U3, V3
		true, -- use_map
		-- if set to false, it renders tiles 1, 2, and 16
		-- when set to true, it renders tiles 18, 19, and 34. (tile 18 being 16 pixels across and 8 pixels down from UV 0,0
		-- either way, it doesn't render any sprite data
		-1 -- transparency index
	)
	
end`

as comments point out, the textri use_map argument seems to do odd things with the map UV, and never interacts with the sprite data whatsoever.

tested on 0.90.1723 Pro

**Comment by nesbox** [comment]
What tiles does your map consist of?

From https://github.com/nesbox/TIC-80/wiki/textri 
`use_map : if false (default), the triangle's texture is read from SPRITES RAM. If true, the texture comes from the MAP RAM.`

Please, look at this demo https://tic80.com/play?cart=234
It uses both types of `textri()`, without and with `use_map` flag.
