### ISSUE TITLE
Difficult to use external IDE, please rollback `dofile` function

### ISSUE THREAD

**Issue by 13luck** [nesbox/TIC-80#1531]
Its useful when you develop in external IDE. In my case I'm transpiling TypeScript -> JS.
 Can't upgrade to 80> version, still using 70.6

**Comment by trufae** [comment]
I tried to use the dofile() thing but it seems like it doesnt exist anymore. How’s the external editor suposed to be used without it? I understand how dofile can be abused to access resources from the outside world.. but what is the alternative?

**Comment by nesbox** [comment]
You can save your cart in text format using `save game.js` command and edit in any editor you want and TIC will auto reload it (it's a pro feature)
