### ISSUE TITLE
Raspberry Pi 4, baremetal - bug with mkdir command

### ISSUE THREAD

**Issue by PetruCHIOrus** [nesbox/TIC-80#1541]
There is one bug on the Raspberry Pi 4 build related to the **mkdir** command. 

The fact is that the command apparently creates a folder not in the tic80 folder, where the visible files are located, but in the actual root of the flash drive. You can go to this folder, but it is impossible to read its contents or write it. 

![photo_2021-08-09_21-02-13](https://user-images.githubusercontent.com/39710644/128759085-764ae31d-688c-417f-882c-910cdbbc2419.jpg)

The **demo** command creates a **bunny** folder also in the actual root of the flash drive, it cannot write cartridges there, and therefore the folder remains empty.

For example, normal command behavior:

![photo_2021-08-09_20-57-16](https://user-images.githubusercontent.com/39710644/128759529-6ce2ebb1-7f4a-4ada-8af4-0429ecbb4958.jpg)

**Comment by msx80** [comment]
Hi there, i took a look at the Rpi3 version, it's buggy but in a different way 😅 It actually creates the folder in the right place but you can't "cd" into it.
If i find some time i'll look into it

**Comment by nesbox** [comment]
Seems fixed here 22378fb300bf0f0b5711dd3ffa59ebff191ad2f5
Thanks to @msx80
