### ISSUE TITLE
External Editor support for Javascript

### ISSUE THREAD

**Issue by gjoedev** [nesbox/TIC-80#1544]
I just recently started using TIC-80 again, this time with alot more programming experience. I decided to use Javascript, since its the language im most fluent with, and got to work. I suddenly realized that using TIC-80s Built in editor with Javascript would be very painful, so I decided to look for external editor support. [I found a page on the wiki](https://github.com/nesbox/TIC-80/wiki/external-editor) showcasing external editor support, and followed the article only to be greeted by an error. Here is my code...
```
dofile('Test.js');
// title: Test
// author: gjoedev
// desc:   test
// script: js


var ship ={
x: 120,
y: 115,
}

function TIC()
{
update();
render();
}

function update(){
if(key(23)){
ship.y--;
} else{
if(key(19)){
ship.y++;
}
if(key(1)){
ship.x--;
}else{
if(key(4)){
ship.x++;
}
}
}
}

function render(){
cls();
print("Hello World");
spr(0, ship.x, ship.y)
}
```
The dofile('Test.js'); is what I was instructed to do in the wiki. Here is the error:
```
undefined
    at [anon] (duk_js_var.c:1236) 
internal
    at eval (eval:1) preventsyield
```
 Anyone know how to properly set this up for Javascript
Edits because i cant spell

**Comment by RobLoach** [comment]
`dofile()` isn't really a thing anymore. I'd recommend looking at the command line arguments, and loading the code through `--cmd`...

https://github.com/nesbox/TIC-80/wiki/Command-line-arguments

**Comment by joshgoebel** [comment]
Or just `save mygame.js` and then `folder` and open mygame.js in your fav editor, done

**Comment by ChildishGiant** [comment]
Yea the wiki needs updating to make it clear that dofile is long gone :sweat_smile:

**Comment by gjoedev** [comment]
> Or just `save mygame.js` and then `folder` and open mygame.js in your fav editor, done

Runing save test.js creates test.js.tic? IS that would I am supposed to do?

**Comment by ChildishGiant** [comment]
saving to formats other than .tic is a pro feature, you can still do the method Rob mentions though

**Comment by joshgoebel** [comment]
It's always worked just fine in my non-pro despite what the discs might say. Had this recently been changed?

**Comment by nesbox** [comment]
Carts in text format is a pro feature since 0.90 (it was always planned to be a pro feature, but it was available in the regular version)

**Comment by paul59** [comment]
> Yea the wiki needs updating to make it clear that dofile is long gone sweat_smile

I've been holding fire on more wiki edits - some stuff that mentions earlier versions badly needs updating... does anyone still use a pre 0.8 version I wonder (and if so, why?!).

**Comment by sinsinpub** [comment]
tested with kinds of benchmark tic, 0.7 slightly better performance...
and one of my old android phone (4.0) can only run 0.7. for same env, still need `dofile` because my 0.7 not pro ver

> does anyone still use a pre 0.8 version I wonder (and if so, why?!).

**Comment by paul59** [comment]
> tested with kinds of benchmark tic, 0.7 slightly better performance...
> and one of my old android phone (4.0) can only run 0.7. for same env, still need `dofile` because my 0.7 not pro ver
> 
> > does anyone still use a pre 0.8 version I wonder (and if so, why?!).

Fair enough, maybe I should have asked 'should the wiki contain information that applies only to older versions?' :D

**Comment by sinsinpub** [comment]
I think histories required for wiki, especially for those incompatible changes, which confusing ppl

**Comment by paul59** [comment]
I've updated the wiki to clarify the procedure for using external editors depending upon TIC version (at least pre and post 0.80!): https://github.com/nesbox/TIC-80/wiki/External-Editor

**Comment by gjoedev** [comment]
Nice I'll close the issue
