### ISSUE TITLE
Pattern size in the tracker

### ISSUE THREAD

**Issue by vitorpdsg** [nesbox/TIC-80#1545]
It would be nice if the pattern size for songs wasn't universal for a song, and there could be a different amount of rows on patterns for the same track! most trackers have that, and it is a very useful feature.

**Comment by nesbox** [comment]
Please add info on how it works in other trackers.
Thank you.

**Comment by Kyuchumimo** [comment]
You could address this issue by using the Jxx command

**Comment by nesbox** [comment]
Really, we already have this :)
@Kyuchumimo thank you
