### ISSUE TITLE
I need help with the new export command in the newest update (0.90.0)

### ISSUE THREAD

**Issue by DinoNuggies4665** [nesbox/TIC-80#1547]
I can't find any documentation on the new way to use the export command, and I can't figure it out.

**Comment by DinoNuggies4665** [comment]
NVM Figured it out

**Comment by joshgoebel** [comment]
Is there anything confusing in the wiki we might need to update?

**Comment by DinoNuggies4665** [comment]
Well the wiki is pretty outdated, I would probably look through it and update some of the gifs/images and stuff

**Comment by nesbox** [comment]
Also, you can use `help export` command to get info
```
>help export
---=== COMMAND ===---
export cart to HTML,
native build (win linux rpi mac),
export sprites/map/... as a .png image 
or export sfx and music to .wav files.

usage: 
export [win|winxp|linux|rpi|mac|html|
tiles|sprites|map|sfx|music|screen|help] 
<file> [bank=0 ovr=0 id=0 alone=0]
```
