### ISSUE TITLE
Map Editor: default position

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1548]
Create a new cart, the map editor by default puts cell 000:001 at top left meaning user has to drag the map to show 000:000 which is surely the more sensible (and commonly used) starting point when creating the map.

![image](https://user-images.githubusercontent.com/3756822/129096581-00d51db7-cb7e-469d-8030-373706692fc9.png)

**Comment by Kyuchumimo** [comment]
That is because row 000 is partially covered by the upper bar, for me it is normal

**Comment by joshgoebel** [comment]
I agree with this issue that it might make more sense for the editor to be aware of how much room the bar takes and start the ACTUAL map at 0,0.. that makes it harder to "see" the first screen as a whole composition though - which is likely why it's the way it is.

**Comment by paul59** [comment]
> I agree with this issue that it might make more sense for the editor to be aware of how much room the bar takes and start the ACTUAL map at 0,0.. that makes it harder to "see" the first screen as a whole composition though - which is likely why it's the way it is.

Yeah but you can't see all 30x17 cells at once so it would seem more logical to me to show the map 'origin' at top left (below the bar) rather than see a tiny sliver of whatever is in (0,0) and some of what's in (29,16), especially as bounding walls are often quite important parts of the map. Just my personal preference I suppose :-D

**Comment by nesbox** [comment]
I prefer the 0:0 pos too, let's do not touch this then
