### ISSUE TITLE
[Bug] TIC-80 crashes when try to access tiles with id higher than 999 in 1bpp mode

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1556]
![image](https://user-images.githubusercontent.com/88540876/129792933-ed60393b-86d4-475e-b8d0-74b51a672195.png)

**Comment by nesbox** [comment]
Thank you for the report.

**Comment by nesbox** [comment]
fixed here 30e0823fc483e68dd13d10d80d6e68a5ba446ffa
