### ISSUE TITLE
Music "Play Music" Command

### ISSUE THREAD

**Issue by Francisco2021521** [nesbox/TIC-80#1557]
How can i play music? is there a command for this?

**Comment by Francisco2021521** [comment]
just recreated EEEAAAOOO (sd_bbb from Patricia Taxxon)
And i dont know how is the PLAY MUSIC command called...

**Comment by ChildishGiant** [comment]
Here's the relevant page on the wiki: https://github.com/nesbox/TIC-80/wiki/music
