### ISSUE TITLE
Stop Sprite and Map Editor UI from using the current game palette

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1562]
This dependency makes it hard to arrange a new palette without making the editor look ugly or even unusable.
![image](https://user-images.githubusercontent.com/88540876/130295021-2f70b5c2-c02c-4912-a26a-cd0cd93f7ecb.png)

**Comment by nesbox** [comment]
It seems I broke something with this commit 973dd00a3227036addb073472f0ec49757664784

**Comment by ChildishGiant** [comment]
I had always assumed this was intentional as it's been around for years. That and the low res are the main reasons I don't use the in-built editor. If this is changed/fixed and the proposed BPP change for text editing happens I might drop external tools altogether!

**Comment by nesbox** [comment]
fixed here 326909c5ff78e893bec1c66f8ab0377811e754b3
