### ISSUE TITLE
[Suggestion] Add apk to fdroid

### ISSUE THREAD

**Issue by WellsBit** [nesbox/TIC-80#1569]
Since this is a FOSS project, perhaps it'd be suitable to put it up on fdroid, an alternative to the play store on android containing only open source projects. It could be published directly to the fdroid repository, so users could simply find it in the fdroid app. Or, a custom repository separate from the main repository could be hosted on the tic 80 site, and users can add it as a custom repository to fdroid.

**Comment by ClockGen** [comment]
I've opened a merge request to add the application to F-Droid. Please see:
RFP: https://gitlab.com/fdroid/rfp/-/issues/402
MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12319
@nesbox

**Comment by nesbox** [comment]
Sorry, what should I do?
Is there any action expected from my side?

**Comment by ClockGen** [comment]
@nesbox Hello, nothing, just notifying about the progress. The metadata builds fine and the app should build fine on F-Droid buildserver as well. It's up to maintainers now to review and merge it.

Also, while optional, but very welcome, if you'd set up [fastlane structure](https://gitlab.com/-/snippets/1895688) in your repo, so F-Droid could display your own app description, screenshots and more.

**Comment by ClockGen** [comment]
@nesbox can you please verify apk's built here https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12319#note_1222880724

**Comment by nesbox** [comment]
Hooray, I see TIC-80 in the FDroid catalog https://f-droid.org/en/packages/com.nesbox.tic/
