### ISSUE TITLE
TIC-80 exports 4 GB of empty audio

### ISSUE THREAD

**Issue by literallyMilk** [nesbox/TIC-80#1570]
Hello! Today i encountered a issue with export command. I tried exporting music data from my game as .wav, and the TIC-80 just froze.
![изображение](https://user-images.githubusercontent.com/86829280/130800699-f31ca0fd-b2c6-4366-9b6f-248621f0ce89.png)
Then it generated 4 GB of audio. 
![изображение](https://user-images.githubusercontent.com/86829280/130800936-0389c72b-09a2-4fc1-8157-cc14a2f1363e.png)
I opened it with Audacity and the file was... empty.
I don't know if the problem is caused by TIC-80 version (i use XP version, 0.90.1723), but i will wait for the answer.

**Comment by nesbox** [comment]
Hi,
can't reproduce it on my carts, could you pls provide your cart?
Thank you

**Comment by literallyMilk** [comment]
Here it is: 
[faultycart.zip](https://github.com/nesbox/TIC-80/files/7081285/faultycart.zip)

**Comment by nesbox** [comment]
I reproduced it, thanks...

**Comment by nesbox** [comment]
fixed here 66656dddb1e8cdb3eea6ddf57af94fd53ff29ba4
The `jump` command doesn't work if `loop` parameter isn't set.
You can test it here https://nightly.link/nesbox/TIC-80/workflows/build/master
Thank you.
