### ISSUE TITLE
Insert line in music editor [Android]

### ISSUE THREAD

**Issue by phedoff** [nesbox/TIC-80#1573]
Hi,

could you add an insert-function to the original tic80-keyboard for the music editor, maybe via [shift]+[back]? I really like the embedded keyboard, so it would be a great addition.
The shortcut mentioned in #978 works great, but only with a hardware keyboard or hacker's keyboard (software). 

Kind regards

(If this has been asked elsewhere - sorry, I didn't find the according request)

**Comment by nesbox** [comment]
Or we could add the `Insert` key to the keyboard somewhere :)

**Comment by phedoff** [comment]
Yeah, uhm... There is a little space left... ;)
![202108314431_120144](https://user-images.githubusercontent.com/33154602/131483454-3ae1efa7-831d-4386-b419-5a0ec2da2ece.png)

**Comment by nesbox** [comment]
Added `INS` `DEL` buttons to the software keyboard 9de0e2e1b8925434ea00ee280f09f2c130dffed5
![image](https://user-images.githubusercontent.com/1101448/159901740-f92f35a3-4154-482a-8edc-b12438311fc2.png)

**Comment by phedoff** [comment]
Great. Thank you.
