### ISSUE TITLE
Black screens when entering fullscreen on linux

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1577]
Whenever entering fullscreen mode, both my screens go entirely black except for the cursor. The app can still receive inputs but nothing is shown until entering windowed mode again. The window can sometimes appear again on the other screen but that is probably a separate issue.

Tic version: `0.90.1723 Pro (9c38a80)`
OS: elementary OS 6 Odin (Based on Ubuntu 20.04)

https://user-images.githubusercontent.com/13716824/131421784-deb7e3d4-775a-46a2-a575-bb5b2dbb28b7.mp4

**Comment by nesbox** [comment]
Not sure it's a TIC-80 issue, I suspect it's on SDL2 lib side.
Anyway, pls also check `tic80-linux-sdlgpu` from here https://nightly.link/nesbox/TIC-80/workflows/build/master

**Comment by ChildishGiant** [comment]
tic80-linux-sdlgpu seems to have the same issue for me

**Comment by paul59** [comment]
I get a similar issue on MX Linux - [alt]+[enter] displays only a quarter of the screen (at top left), the rest is black. It also grabs all input (so I can't alt+tab etc and confines the cursor to the top left quarter. Going back via [alt]+[enter] I end up with a magnified view in the TIC window.

I'm on the same version - 0.90.1723 pro.

**Comment by nesbox** [comment]
Great, it can be closed if all is ok on 1.0.1784-dev :)
