### ISSUE TITLE
Cart.png and custom config file palette inconsistency

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1581]
I'm currently using a custom palette in the config file and noticed that when exporting a cart in png format it uses the default palette for the entire cart, except in the info section where it uses the config palette, resulting in this image on the right:
![image](https://user-images.githubusercontent.com/88540876/131569255-80e87c2b-cfbb-42c0-a41b-402e8561f3a8.png)

**Comment by Miguel-hrvs** [comment]
The thing is that for the cart's text colors and it's background we are using the palette from the config. The rest comes from the image directly and not from the palette. One fix is to get the colors from sweetie16 directly instead of the one set in the config.
