### ISSUE TITLE
1.0.1553-dev / 9.0dev: Copy and pasting something can paste incorrectly data (Bug)

### ISSUE THREAD

**Issue by MasterNama17083** [nesbox/TIC-80#1584]
**Attempt 1**. Copy the code and go to "Sprite Editor" and paste it or go something to paste.
![video2-min](https://user-images.githubusercontent.com/80534869/131967442-444e3075-33ee-4167-a0c9-1c22a9a3d62b.gif)

**Attempt 2**. I made it my code number limit test and go to "Sprite Editor" and paste it or go something to paste.
![video3-min](https://user-images.githubusercontent.com/80534869/131968366-f801181d-a863-416c-8a19-df8380524382.gif)

Similar Bug: #115

**Comment by EODROID** [comment]
That's weird

**Comment by nesbox** [comment]
It's not a bug, TIC's clipboard has a string representation, so you can paste any string you want if it doesn't break the limits.
