### ISSUE TITLE
fixed width argument in print() API not working correctly after changing system font

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1585]
The results are supposed to be the same for each color:
![image](https://user-images.githubusercontent.com/88540876/132079880-c3e9753e-b669-4d7f-98af-f9436481bfc2.png)

When it try to use the fixed width it get completely inconsistent and broken:
![image](https://user-images.githubusercontent.com/88540876/132080326-3472c074-5a5c-4206-91ca-c3fac52fd043.png)

Cart:
[customfont.zip](https://github.com/nesbox/TIC-80/files/7109099/customfont.zip)

EDIT: I was messing more with this issue and I noticed that the variable width is actually working fine, the actual problem is not that it becomes reversed but it's just not working correctly when trying to use the fixed width. Also, the default font is 6x6, the new font that I used is 8x8, how does TIC knows the fixed size of the font that are being used?

**Comment by nesbox** [comment]
To fix the issue I added the font params variable to the RAM
```
| ...
| 14604 | FONT              | 1016  |
| 149FC | FONT PARAMS       | 8     |
| 14A04 | ALT FONT          | 1016  |
| 14DFC | ALT FONT PARAMS   | 8     |
| 14E04 | ... (free)        | 12796 |
+-------+-------------------+-------+
```
which are containing the `width` and `height` values of the current font.
For example, if you want to set fixed `width=7` and `height=10` call 
``` lua
poke(0x149FC, 7) -- setting width
poke(0x149FC+1, 10) -- setting height
```

and your cart will look like
``` lua
function fontset(spr_id,alt)
	local d=alt and 160 or 32
 for c=0,95 do for i=0,7 do
  local v=peek(0x4000+spr_id*32+c//4*32+c%4+i*4)
  poke(0x14604+(d+c)*8+i,v)
 end end
 
-- here we set the fixed width to 8
 poke(0x149FC,8)
end

function TIC()
	if not done then
		cls()
		for i=0,1 do
			print('Fixed Width!',32,32+32*i,12,true)
			print('Variable Width!',32,32+32*i+16,14)
			fontset(256)
		end
		done = true
	end
end
```
![image](https://user-images.githubusercontent.com/1101448/133089292-271c049c-b71b-4b7b-9ed0-9f9fea33b9ca.png)

All the changes done here 07318ffc476b040d885a9f12773267bcb89bf94f
Thank you
