### ISSUE TITLE
[Feature Request] Export map to png

### ISSUE THREAD

**Issue by symbolisch1234** [nesbox/TIC-80#1586]
I would love to see the possibility to export the whole map to a 1920x1088 png file. This would be super helpful as a starting point to creating a supplementary map for my game.

Thanks!

**Comment by ChildishGiant** [comment]
https://github.com/AlRado/TiledMapEditor-TIC-80 This might be worth having a look at (not sure if map export exists any more though)

**Comment by symbolisch1234** [comment]
Yes, this works as a 4-step process, using 3 different pieces of software:

1. export tic80 map using command `export map filename.map`
2. convert .map to .tmx (using https://github.com/AlRado/TiledMapEditor-TIC-80 )
3. open in Tiled Map editor (from https://thorbjorn.itch.io/tiled )
4. export as png (as per https://doc.mapeditor.org/en/stable/manual/export-image/ )

I am asking for the one-step solution `export mapng filename.png`

**Comment by nesbox** [comment]
Added `export mapimg <file.png>` command here 4e7f1f1714a7b15fe13a452b634287761629291e

**Comment by nesbox** [comment]
Exported map as an example
![map](https://user-images.githubusercontent.com/1101448/133055486-6bda6e30-d1cb-479c-af50-ca797c0bacd8.png)
