### ISSUE TITLE
(Spanish) add lines, circles and squares in the sprite editor

### ISSUE THREAD

**Issue by eggbanana173** [nesbox/TIC-80#1593]
hola "nesbox", si otra vez soy yo, 
como el titulo lo dice, mi sugerencia seria la siguiente
agregar líneas, círculos y cuadrados al editor de "sprites" 
que obviamente serviría para dibujar líneas, círculos y cuadrados en el editor
(como si fuera un editor de imágenes)

**Comment by ChildishGiant** [comment]
Kinda a duplicate of #1118

**Comment by eggbanana173** [comment]
buerno, honestamente no sabia de ese
