### ISSUE TITLE
Cannot Copy/Paste on 3DS

### ISSUE THREAD

**Issue by JuniorBecari10** [nesbox/TIC-80#1594]
Hey nesbox! I've finally downloaded TIC-80 on my 3DS. But I can't copy/paste neither text nor sprites on it.

**Comment by nesbox** [comment]
I even see the place where we forgot to set the clipboard https://github.com/nesbox/TIC-80/blob/master/src/system/n3ds/main.c#L162

**Comment by nesbox** [comment]
fixed here c904c5e36dff638df3f527bbecb825fdc7303623
thank you
