### ISSUE TITLE
Hotkeys also triggers numkeys

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1595]
```
ALT+~                   show console
ALT+1/F1                show code editor
ALT+2/F2                show sprite editor
ALT+3/F3                show map editor
ALT+4/F4                show sfx editor
ALT+5/F5                show music editor
```
When pressing these key combinations to access the different editors, the keyboard numbers are also being pressed, for example, when pressing ALT + ~ to display the console, the `symbol appears, and the same happens with the sprite editor, ALT +2 will always activate the color picker, in the map editor ALT + 3 it will activate the select tool and in the music editor the number 5 will be registered. Using TIC-80 0.90.1722 but is also present in TIC-80 0.90.1723

![screen2](https://user-images.githubusercontent.com/74131798/132999082-8a940d09-a801-48fa-95e6-0529e5ac8981.gif)
![screen3](https://user-images.githubusercontent.com/74131798/132999084-58ab1428-3c44-4c41-b836-d1cfdcd68e77.gif)
![screen4](https://user-images.githubusercontent.com/74131798/132999142-c6d9cdad-14e3-49dc-96f1-106822a2f0a6.gif)
![screen5](https://user-images.githubusercontent.com/74131798/132999144-99b1f1fe-7abc-49b7-a02f-ee334a2b1524.gif)

**Comment by nesbox** [comment]
fixed here f4f16f95237b8c77d1b77147f2dbffd332800d6b
thank you
