### ISSUE TITLE
Recent commit broke keyboard for linux?

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#1597]
It looks to me like commit 5634f65f2b3453b3b12b0503ec9e3381a78bbc35 broke some keyboard support in Linux for me.. for example, Enter, Backspace and all function keys don't work.

Is it only me ? i'm on arch linux. I've recently upgrade the system, some sdl updates were included.. so maybe it's that but if i build with f4f16f95237b8c77d1b77147f2dbffd332800d6b it works.

**Comment by nesbox** [comment]
fixed here c0a9c934b80b497be0d4d7af3b65cc4c69e17408
