### ISSUE TITLE
tic_api_btn() in io.c doesn't work as intended

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#1599]
Hi there, as the title says, that api call is broken if i understood correctly. As it is now it works as a "btnp", ie it checks for previous buttons and only return true once. And indeed it's not used by any implementation (or anywhere really), they just go and read the ram directly.
I don't know if this is the intended behaviour but it seems like all tic80 functions should cleanly map to a tic_api_* call, even if it's a super thin layer on a ram access.

Thanks :)

**Comment by nesbox** [comment]
Yes, you're right, I even realized we don't use `tic_api_btn()` API at all in the project :)
Should be fixed, thank you.

**Comment by nesbox** [comment]
fixed here e823217
