### ISSUE TITLE
[Feature request] - Basic 3D support

### ISSUE THREAD

**Issue by anonimo82** [nesbox/TIC-80#1604]
Hello everyone. 
I'd like some basic 3D in this, maybe with a model editor (similar to picoCAD - https://johanpeitz.itch.io/picocad - but with animations) and a simple level editor, maybe something like FPS Creator's one (https://play.google.com/store/apps/details?id=org.silentworks.fpscreatorfree)

**Comment by potato25** [comment]
i love picoCAD too :)

**Comment by anonimo82** [comment]
Yes, picoCAD is great!
By the way, I also saw, in pico-8, there's a "3D version", named Voxatron. It uses Voxels and provide a model and a level editor, with physics and stuff.
Even better, the pico8 author is working on a new product, called picotron, which seems like a pico8 + VoxaTron + something else.
It's called picoTron, and I wonder if will ever tic80 be similar.

Thanks for any help.

**Comment by DinoNuggies4665** [comment]
There's a couple of 3d engines on the tic 80 website, although it would be cool to have built in support.

**Comment by RobLoach** [comment]
While it would be nice to have some sort of 3D engine, I think it makes sense to keep this out of TIC-80's core API. As DinoNuggies4665 mentioned, there are a few demonstrations available that could be abstracted into a 3D external library.

**Comment by anonimo82** [comment]
Writing 3D code requires... code, which you could use for your game, if 3D were part of the API.
