### ISSUE TITLE
[0.90 - Android] keyboard doesn't change to gamepad when resume

### ISSUE THREAD

**Issue by MFauzan26** [nesbox/TIC-80#1608]
when trying to resume cart (with "resume" command) on android device virtual keyboard does not change to virtual gamepad. unlike when running cart (run), the virtual keyboard will be replaced by a virtual gamepad.

![Screenshot_20210929-175238_TIC-80](https://user-images.githubusercontent.com/39972629/135256153-ddaf67f0-03bd-4a76-9ce6-857e6f6b87ff.jpg)

**Comment by nesbox** [comment]
Thanks for the report.
