### ISSUE TITLE
peek4/poke4 addressing is opposite to the one described in wiki

### ISSUE THREAD

**Issue by slaierno** [nesbox/TIC-80#1619]
As per title, `peek4` and `poke4` access byte nibbles in the opposite way as described in the wiki.
In the wiki description, the memory is grouped in 4-bits words, i.e. nibbles. High nibbles should be mapped first, low nibbles second.

Therefore, if poking `0xab` at `0x4000`, the high nibble is `0xa` and the low is `0xb`, if we interpret "leftmost 4 bits" and "rightmost 4 bits" as "most significant 4 bits" and "less significant 4 bits" respectively.

If this is the right interpretation, the following snippet will clearly reveal a bug in the behaviour of those functions:

```lua
addr=0x14e04

function TIC()
	cls(13)
	print("poke(addr, 0xab)",0,0)
	poke(addr, 0xab)
	print("peek(addr) = " .. string.format("%02x", peek(addr)),0,8)
	print("peek4(2*addr) = " .. string.format("%x", peek4(2*addr)),0,16)
	print("peek4(2*addr+1) = " .. string.format("%x", peek4(2*addr+1)),0,24)
	
	print("poke4(2*addr, 0xc)",0,40)
	poke4(2*addr, 0xc)
	print("poke4(2*addr+1, 0xd)",0,48)
	poke4(2*addr+1, 0xd)
	print("peek(addr) = " .. string.format("%02x", peek(addr)),0,56)
end
```

The result is the following:
![immagine](https://user-images.githubusercontent.com/7281159/136366652-fc7f17f6-b4f5-4607-9314-04bbc96e5e76.png)

I suppose it is going to be one of the following case:

1. The wiki inverted leftmost/rightmost, and the function are working as intended
2. The wiki used leftmost/rightmost as, respectively, _less significant_ and _most significant_ (putting less significant bits to the left, like in network theory), leading to my confusion
3. The wiki is right, I understood it correctly, but the function are not working as intended

I want to add that, in any case, left/right are really confusing references and most/less significant should be used to avoid any confusion.

**Comment by joshgoebel** [comment]
> and the function are working as intended

This is likely the case, but damn this is confusing either way. I bet it's the way it is because the VRAM storage inverts the nibbles in a strange way and this makes more sense in that regard.  I'll see about updating the wiki to be clearer.

**Comment by joshgoebel** [comment]
This is really the old big vs little endian discussion but at the nibble level... it makes sense (when indexing in 4 bit segments) for the least significant to come first - even if that makes it harder to "follow along" if you have a byte by byte hexadecimal printout.

**Comment by joshgoebel** [comment]
> if we also consider that changing the code behaviour would have affected existing TIC-80 codebases.

Yeah that seems super unlikely now even if we somehow decided his was a mistake. Ship has sailed. 

🤷🏻‍♂️

It's trivial for someone to redefine both these methods though if they so chose.
