### ISSUE TITLE
(0.90.1723) can't open cart in android

### ISSUE THREAD

**Issue by omnidotnet** [nesbox/TIC-80#1620]
I downloaded tic_edit from the official website and tried to load it.
> load tic_edit
cart loading error
> load tic_edit.tic
cart loading error
> run tic_edit
_opens hello world_

Is it impossible to load carts in android? Or am I just being dumb?

**Comment by another-m00** [comment]
Tic 80's load command only looks for the files in Tic80's app directory. Also, the run command does not take arguments, it only runs the currently loaded cart.
To load a downloaded cart, you need to open the path thats printed out on the console in a file manager, then you need to move/copy the downloaded file there.
In earlier version (prior to v 0.80) you can do all this by the Add command.
