### ISSUE TITLE
print() and trace() function. Color Default Parameter Value, expected index color 12, not 15

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1622]
print text [x=0 y=0] **[color=12]** [fixed=false] [scale=1] [smallfont=false] -> text width
https://github.com/nesbox/TIC-80/wiki/print (In the example 1 screenshot, using print(string,(240-width)//2,(136-6)//2), the index color 12 (white, sweetie-16 palette) is shown as the default color)
Current result:

![screen3](https://user-images.githubusercontent.com/74131798/136642946-48dc38bc-43cf-4afe-8cfe-f4b77063081c.png)

![screen4](https://user-images.githubusercontent.com/74131798/136642950-13537e4f-d636-4d88-9e63-1d0631d5ebb9.png)

src/api/lua.c
`1124        s32 color = TIC_DEFAULT_COLOR;`
https://github.com/nesbox/TIC-80/blob/master/src/api/lua.c

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

trace message [color]
https://github.com/nesbox/TIC-80/wiki/trace (In the example screenshot, using trace('Hello console:'..time()), the index color 12 (white, sweetie-16 palette) is shown as the default color)
Current result:

![screen](https://user-images.githubusercontent.com/74131798/136642965-ff04d26c-69ed-4dbb-ae98-9ef05699345d.png)

![screen2](https://user-images.githubusercontent.com/74131798/136642969-4dc1e053-e4eb-4e88-9548-3b40d1ffefdb.png)

src/api/lua.c
`1181        u8 color = TIC_DEFAULT_COLOR;`
https://github.com/nesbox/TIC-80/blob/master/src/api/lua.c

**Comment by joshgoebel** [comment]
This seemed to change from 12 to 15 here:

https://github.com/nesbox/TIC-80/commit/f6bd43f822c35e3700c85cd548dbb2642856c80d

@nesbox Is this intentional or a regression?

**Comment by nesbox** [comment]
Yes, one time we changed it to `12` (white color), but then we realized it breaks compatibility with some old cart and decided to revert it to `15`.
The Wiki is changed, thank you.
