### ISSUE TITLE
Request: hotkey to toggle PIANO and TRACKER mode

### ISSUE THREAD

**Issue by runlow** [nesbox/TIC-80#1624]
**Expected:**
Some way to switch to the tracker right away using the keyboard - in the pro version.
If there is such a keyboard shortcut - I haven't found it yet.
(The tracker can be navigated entirely with the keyboard and that's the only click needed when switching from code editor)

**Actual:**
One has to click the tab icon in the top right corner each time.

**Possible solution:**
- if the user is in the music editor **already** but they try to switch to the music editor by pressing the corresponding hotkey (F5 or alt+5) then MUSIC_PIANO_TAB and MUSIC_TRACKER_TAB are toggled
- when you press the existing music editor hotkey but with shift then it takes you directly to tracker mode

**Comment by nesbox** [comment]
Ok, it could be `F5`.
Thanks.
