### ISSUE TITLE
tracker "sharp column" should be editable or not selectable

### ISSUE THREAD

**Issue by runlow** [nesbox/TIC-80#1625]
When you press *right* on a note - you end up on the "sharp" (hash symbol `#`) column which you can't interact with in any way. 

When you are in the tracker and on a note (first column), and then press *right* - it should take you directly to the octave number column.

Since you cannot interact with this "sharp column" - it doesn't seem warranted that you should be able to select it as it's an extra keypress when you move the cursor around.

Alternatively - you should be able to toggle whether a note is sharp or not when on the "sharp column".

**Comment by nesbox** [comment]
What hotkeys do you think we will use to toggle sharp?

**Comment by joshgoebel** [comment]
If it was focused wouldn't you use whatever over key we usage for toggling in the UI? Space? Enter?

**Comment by runlow** [comment]
Any key would do as it's an on/off. Space and/or Enter would do.

Something to keep in mind though is that some notes "cannot be" sharpened, like B or E. Technically they can be (to C and F) but not sure if the user would expect that or if it would be useful. For those two notes perhaps it could just do nothing?

**Comment by joshgoebel** [comment]
> . Technically they can be (to C and F) but not sure if the user would expect that or if it would be useful.

Since the sharp column is a boolean I'd suggest that in those cases we do nothing.  Since if sharp really just means "roll forward" then I'd suggest it's not really a toggle at all but we should have a `<` and `>` key on the note itself or some such to permit rolling it forward/backwards easily.  That's just OTTOMH.

**Comment by runlow** [comment]
Sounds like it's much easier and simpler to skip over the sharp column completely.

Everything would look and work the same way as now - except the "sharp column" would not be selectable. To sharpen the note one could just have to input the note anew.

**Comment by joshgoebel** [comment]
What about `.` (period)"?  I didn't realize both space and return play the song. :-)

**Comment by runlow** [comment]
I know I suggested it myself, and thank you for the PR, but now I'm starting to think "sharp toggle" might be a bad idea because it's feature creep. It would probably be much better to just make the sharp column not selectable and call it a day.

In music vocab you **can** sharpen E and B, it's just that in this paradigm one "can't". There are even double-sharps. This is not to mention flats and double flats. Not sure it's worth diving into that mess.

This is not to mention that one can **already** "sharpen" a note by pressing ctrl+F2 (transposing it up)

I will compile your PR branch, just need to figure out how to do that with `trizen` or I may do it manually.

**Comment by runlow** [comment]
Just compiled the PR, it seems to work as intended. As you said yourself @joshgoebel - the shortcut works regardless if on the "sharp column" or not.

Either way with or without the shortcut - there's no reason for sharp column to be selectable as it's an extra keypress. I think the highlight could work the exact same way as now, except it would skip directly to the octave when pressing right.

**Comment by joshgoebel** [comment]
Ok, I thought this would be weird but skipping it feels perfectly natural... 

The one thing I dislike now is when you hit `.` on a key that doesn't have a corresponding "sharp" and it just does nothing.

**Comment by runlow** [comment]
The skipping works great, thank you!

As for "toggling sharpness" I think that can be removed altogether, unless you wish to keep it for fun maybe. With Ctrl+F2 working there's no need for it. I originally suggested it a month ago and was just brainstorming ideas and I didn't realise there's a shortcut for transposing.

Either way thank you.
