### ISSUE TITLE
Request: Hold Alt or Ctrl key to jump between words (in console)

### ISSUE THREAD

**Issue by lua-rocks** [nesbox/TIC-80#1626]
Like in most terminal emulators `alt` or `ctrl` should be used as modifiers to:

+ `alt` or `ctrl` + left or right arrows: jump between words
+ `alt` or `ctrl` + `del` or `backspace`: delete words

You have already added this feature to the code editor, but for some reason it is not available in terminal mode.

**Comment by another-m00** [comment]
Everything you described is aleady implemented in v0.90, I just tested them. The program on the other hand only considers strings as words that are made out of letters and numbers, you can jump to, select (via ctrl+shift+left/right) or delete words already.

**Comment by lua-rocks** [comment]
@another-m00 I said:

> "You have already added this feature to the **code editor**, but for some reason it is not available in **terminal mode**". 

Your gif shows the **code editor**.

My OS is Xubuntu 20.04.
