### ISSUE TITLE
[Glitch] Fullscreen (Alt+Enter) not resizing and not centering

### ISSUE THREAD

**Issue by lua-rocks** [nesbox/TIC-80#1627]
When I press Alt+Enter part of screen disappears. OS - Xubuntu 20.04.

https://user-images.githubusercontent.com/82697845/136666108-477fa5f2-6028-4ea2-8abd-22730ad1bce3.mp4

**Comment by ChildishGiant** [comment]
The video's not working for me but this is probably the same issue as #1577

**Comment by nesbox** [comment]
Not sure it's TIC80 issue, I suspect it's SDL2 library bug.
Could you please check, do you have any display scaling in the system preferences, 150% for example?
Thank you.

**Comment by ChildishGiant** [comment]
This build has fixed my issues with fullscreening, maybe try it? https://github.com/nesbox/TIC-80/actions/runs/1412373779#artifacts

**Comment by lua-rocks** [comment]
No, I don't have any scaling.

This bug is still active in the latest version installed through the deb package (0.90.1723) but not in the compiled from source version (1.0.1770-dev).

**Comment by lua-rocks** [comment]
Looks like it fixed, yeah.
