### ISSUE TITLE
Paste a sprite while editing a color palette replaces the palette data instead of the sprite

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1634]
I simply tried to copy and paste a sprite using the top paste button and it just replaced the palette instead of pasting the sprite.
![image](https://user-images.githubusercontent.com/88540876/137333636-0f942fca-573f-47ee-baa6-6f3ecc246da8.png)

**Comment by ChildishGiant** [comment]
Could this be related to #1584

**Comment by nesbox** [comment]
Fixed here 690c373
Thank you
