### ISSUE TITLE
Can't build on Linux mint, Cmake returns errors.

### ISSUE THREAD

**Issue by SrDasNeves** [nesbox/TIC-80#1639]
That's the return of the console.

`Building for target : Linux
PROJECT_VERSION: 1.0.1770-dev
VERSION_HASH: 60e63de
BUILD_SDLGPU: OFF
BUILD_TOUCH_INPUT: OFF
BUILD_STUB: OFF
CMake Error at vendor/sdl2/CMakeLists.txt:2 (message):
  Prevented in-tree built.  Please create a build directory outside of the
  SDL source code and call cmake from there

-- Configuring incomplete, errors occurred!`

**Comment by SrDasNeves** [comment]
Thank's for the help!

I don't know why, but this time it worked!

**Comment by lzap** [comment]
For the record, I ran into this when I did not provide `--recursive` but I initialized submodules at a later stage:

```
git clone ...
git submodule init
git submodule update
```

Then I got the same error. Deleted and checked out with `--recursive` fixed it.

**Comment by RobLoach** [comment]
Can also init and update in one command too :wink: 
```
git submodule update --init
```
