### ISSUE TITLE
Print a more helpful message when trying to load text carts with non-pro version

### ISSUE THREAD

**Issue by gcentauri** [nesbox/TIC-80#1643]
Hello!

Thanks for TIC-80.

I'm happy to help fix this issue, but wanted to get it up before i forget. I was trying to open text carts (like cart.fnl) and just getting a "cart failed to load" error. I found out though #lispgames that it is because I don't have the pro version. It might be nice to indicate that as an error from TiC-80 for those who didn't manage to see it on the website?

**Comment by another-m00** [comment]
Tic-80 is designed to only open .tic files as cartridges. The .tic files also contain the sprite, the sound and the map data, so the simple code is not enough to load with the load command.
Althought you have a command line option which you can load in a source code to Tic-80 when it starts up.
It's (Ill update this answer when i find the wiki page).

**Comment by joshgoebel** [comment]
Yes we definitely should improve this error.

**Comment by joshgoebel** [comment]
@gcentauri How exactly were you trying to load these files?

**Comment by gcentauri** [comment]
@joshgoebel I tried both with loading the file in TIC-80 and also calling it from the CLI `tic80 cart.fnl` i can try to recreate if that helps

**Comment by joshgoebel** [comment]
![Screen Shot 2021-11-05 at 7 46 51 PM](https://user-images.githubusercontent.com/6473/140589938-4c456915-e799-41e9-b98d-d2ed34bfc908.png)

@nesbox Thoughts on wording?  Should we have a link somewhere (even if someone has to copy and paste it?) or a blurb about the pro version? Some marketing?

**Comment by nesbox** [comment]
Maybe just link to the itch.io page https://nesbox.itch.io/tic80

**Comment by gcentauri** [comment]
Yeah I think something like

"Loading text cartridges (projects?) is a PRO feature! Get it at https://nesbox.itch.io/tic80"

Its friendly and helpful, and points me in the right direction if its a feature I desire :)

**Comment by joshgoebel** [comment]
It'd be nicer if we had a redirect at `https://tic80.com/pro` or some such... @nesbox Any chance on making the thappen?

**Comment by nesbox** [comment]
I added https://tic80.com/pro URL which redirects to https://tic80.com/create#pro, possibly we'll change it in the future.

**Comment by ChildishGiant** [comment]
"You can support developer's pants" is this supposed to be pockets or am I missing something? Doesn't make much sense to me
