### ISSUE TITLE
code chunk header flags for language (feature)

### ISSUE THREAD

**Issue by runlow** [nesbox/TIC-80#1647]
Everything would work the same way as current, except you could also specify the language in the chunk header (in the unused byte), rather than as a comment.

For example 0 could be Lua, 1 Javascript, 2 Moonscript, 3 Wren, 4 Fennel, 5 Squirrel, etc

In other words it would no longer be necessary to have
```javascript
// script:js
```
...at the start of the code chunk payload but if you did that anyway it would still work like it does now

Motivation: to give non-lua languages a chance for golfing/sizecoding carts because that extra line is an extra 13 bytes
Motivation: not having to write `// script:js` each time in all *.js files

**Comment by runlow** [comment]
It isn't just the golfing. Having to add `// script:js` seems pointless if the file is already `foo.js`, maybe I'm wrong.

**Comment by joshgoebel** [comment]
Lets not forget there isn't always file or a filename... snippets of code are often handed about / copied pasted, etc...

**Comment by nesbox** [comment]
ok
@runlow how do you see the setting of this flag from the code editor?

**Comment by runlow** [comment]
@joshgoebel the snippets could still work the exact same way as now, if the coder doesn't add `// script:foo` or doesn't specify the language it's on them - to remember it. It's not like they usually explicitly state the language when they share code in Lua.

@nesbox I don't think it would need to be necessarily set from the editor, as long as the "language byte" is in the chunk header it would work - everything else could behave the same way as it does now. The editor could recognise that the cart was loaded with that chunk header. If the user decided to use `// script:foo` it would overwrite what's in the chunk header. This could be a hidden feature (like the separate chunk for compressed code) - possibly later added to the editor later if there is need.

As for how it could work if it were to be set from editor - it could be an icon that cycles between LU/JS/MS/WR/FN/SQ each time it's clicked but for now it could be hidden.

**Comment by joshgoebel** [comment]
>  If the user decided to use // script:foo it would overwrite what's in the chunk header.

This is surely a neat and easy way to do it.  The only support case would seem to be someone who empties out a cartridge and tries to switch it from one language to another without the magic comment... they will be in a world of hurt... but I think I could agree that seems a pretty narrow edge case so that's not a great argument against.

But this request itself also seems a very narrow edge case... we're suggesting adding a very hidden feature, just for code-golfers, that is accessed by:

- add the magic comment
- save cartridge
- remove the magic comment

I think my vote would be this is a lot of effort for very little payoff, but ultimately it's up to nesbox. :-)

**Comment by nesbox** [comment]
OK, thank you for the ideas...

**Comment by nesbox** [comment]
Added `CHUNK_LANG` to the cart and `ID` to define a language
```
CHUNK_LANG (1 byte):
10 - Lua
11 - MRuby
12 - Js
13 - Moon
14 - Fennel
15 - Squirrel
16 - Wren
17 - Wasm
```
10d852a8446bd306eed375eaa64e7ee501bde435

**Comment by nesbox** [comment]
Using an external tool, or you can save it as a `project.lua` or whatever and add `LANG` tag manually, then save as a `.tic`
``` lua
-- <LANG>
-- 000:0a
-- </LANG>
```

**Comment by joshgoebel** [comment]
AHHHHH, I missed that because it's so small a patch because it's using the existing binary section logic. :-) Nice.
