### ISSUE TITLE
Request: screen tearing on linux, need to allow VSYNC

### ISSUE THREAD

**Issue by runlow** [nesbox/TIC-80#1652]
OS: Archlinux
GPU: GeForce GT 730
Driver: nvidia-390xx-dkms
Resolution: 1920x1080
WM: ratpoison

Not sure why but getting really bad tearing on my setup in TIC-80.

There used to be a "vsync" option in the config cart but I couldn't find it any more.

Someone suggested to me that it's to do with Xorg setup but I have games installed with perfect vsync, zero screen tearing.

It's especially noticeable when something is scrolling horizontally, the screen tears and the tear slowly moves up and then cycles. It's to the point that it can interfere with gameplay.

**Comment by nesbox** [comment]
We could add a `--vsync` command-line option to enable VSYNC.

**Comment by nesbox** [comment]
Added `--vsync` cmd option as well as `VSYNC=true` option to the config a13f380

**Comment by runlow** [comment]
Seems to work OK. Thank you.
