### ISSUE TITLE
[tic80-v0.90-win-pro] Up arrow key spam

### ISSUE THREAD

**Issue by Faust90** [nesbox/TIC-80#1654]
Hi all,

after opening every cartridge, I see that TIC80 keeps registering a "up arrow key pressed" event, like if that key is being held down.

Thanks in advance for every bit of help.

**Comment by RobLoach** [comment]
Do you have a controller plugged in?

**Comment by Faust90** [comment]
No controller is plugged in.

**Comment by nesbox** [comment]
Usually, it happens when you have connected any external input devices like gamepads, touchpads or etc.
Do you have?

**Comment by Faust90** [comment]
No external device is plugged to the computer. I also tried removing both external mouse and keyboard, using my laptop integrated hardware only (touchpad and keyboard).

**Comment by nesbox** [comment]
Unfortunately, I have no more ideas, sorry.
I'll try to create a special build for you to detect this spamming device.

**Comment by ChildishGiant** [comment]
Probably worth checking this still happens in nightly builds before sinking lots of time into it

**Comment by DannyCork** [comment]
I don't see this in the latest nightly build on Mac.

**Comment by Faust90** [comment]
Problem on my machine still persist on  Win build 1.0.1941-dev (03d73e8)

**Comment by nesbox** [comment]
dup of #2055
