### ISSUE TITLE
named arguments don't work in api

### ISSUE THREAD

**Issue by runlow** [nesbox/TIC-80#1655]
#875 mentions this problem but it seems a solution wasn't implemented

Sometimes I want to provide only one parameter, for example `map{scale=3}` rather than have to set many unrelated ones to get to that argument. The problem is that this syntax doesn't work with current api functions.

The example nesbox gives `spr{id=5, x=100, y=100, flip=2}` doesn't do anything. I think he meant that it *could* work this way, not that it already does.

If I'm doing something wrong please explain.

**Comment by paul59** [comment]
I think you're right - it isn't implemented, probably because it would involve a lot of work!

http://www.lua.org/pil/5.3.html

**Comment by joshgoebel** [comment]
>  The problem is that this syntax doesn't work with current api functions.

It's not intended to.  The API expects individual parameters,  not named parameters.  Supporting a named argument API would also have performance impacts in languages that don't truly support first-class named arguments as a built-in feature... (like Lua, where you're really just passing a table)... and then you'd need extra code to check whether a table was passed or a regular list of arguments, etc...

I do see why this would be nice, but I don't think we should support it in languages where there would be a performance impact in doing so - or where the implementation cost is quite high - because two different APIs for every function is a hassle to document/maintain/etc...

**Comment by paul59** [comment]
> I do see why this would be nice, but I don't think we should support it in languages where there would be a performance impact in doing so - or where the implementation cost is quite high - because two different APIs for every function is a hassle to document/maintain/etc...

Exactly.

**Comment by runlow** [comment]
I didn't realise that this would impact performance or involve a lot of work.

Is there some other way to not have to set a bunch of stuff to get to the parameter you actually want to set or is it just how it has to work?

**Comment by joshgoebel** [comment]
> involve a lot of work.

Remember we don't just have an single API, we have 3: Lua, JS, Squirrel, Wren... with people wanting to add more languages all the time... :-)

> Is there some other way to not have to set a bunch of stuff to get to the parameter you actually want to set or is it just how it has to work?

What is your worst example of this - the one you're banging your head on the most?  You can also write your own API wrappers to simplify the API yourself, but yes it will likely have a cost - even if it's only a small cost.

**Comment by runlow** [comment]
> What is your worst example of this - the one you're banging your head on the most?

When I want to change the font to half-width have to also set `color` `fixed` `scale` and have to remember the order of these.

The most challenging is perhaps the `remap` callback in `map()` which requires setting everything that comes before it.

You're right, making a wrapper may be the best. I could make it so that it works with tables. Haven't considered it.

**Comment by joshgoebel** [comment]
If you commonly use a single remap I might build that concept into your wrapper paired with a global... so you could just set the remap function globally and then forget about it... say even going so far as naming your new function `remap` for example. :-)

FYI: I actually fully agree with the intent (and motivation) behind your request just I think it's not practical given all the other considerations.  In my mentoring I often frown if I see more than 2-3 unnamed arguments, so yes some of our API is a bit crazy. :)

**Comment by runlow** [comment]
I suppose writing my own wrappers is good enough solution for me personally. Thank you.

We can close the issue, unless anyone else wants to comment on this.
