### ISSUE TITLE
Crash with sprite id: -1

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1656]
### Discussed in https://github.com/nesbox/TIC-80/discussions/1617

<div type='discussions-op-text'>

<sup>Originally posted by **MasterNama17083** October  7, 2021</sup>
Hello. I've got idea let's see how did crash TIC-80?
https://user-images.githubusercontent.com/80534869/136331051-310e86d7-5bcd-4aff-b6ad-244713fadba7.mp4

**Code:**
```lua
t=0
x=96
y=24

function TIC()

	if btn(0) then y=y-1 end
	if btn(1) then y=y+1 end
	if btn(2) then x=x-1 end
	if btn(3) then x=x+1 end
	-- to trigger crash
        if btnp(4) then spr(-1)end
 
	cls(13)
	spr(1+t%60//30*2,x,y,14,3,0,0,2,2)
	print("Press A to trigger Crash",54,84)
	t=t+1
end
```

How it works?</div>

**Comment by joshgoebel** [comment]
I thought I might try and fix this, but what is the correct behavior in that case?  Should nothing happen if invalid input is passed?

**Comment by eggbanana173** [comment]
yo sugeriría que al detectar el numero negativo, se detenga el juego y muestre el error
