### ISSUE TITLE
Request: remove `sync` "hardware" frame limitations 

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1662]
Currently sync has a major limitation: 

> The function can only be called once per frame.

This actually isn't 100% true.... last time I read the source each segment could be swapped once per frame, so this code would be quite valid in a single TIC:

```lua
-- screen, bank 1
sync(SCREEN_RAM, 1)
-- tiles, bank 2
sync(TILES_RAM, 2)
-- music, bank 3
sync(MUSIC_RAM, 3)
```

**Is there a reason for this limitation on the entire API?**

I could see perhaps reasons for perhaps throtte `tocart=true` (to avoiding writing to disk 100 times per TIC), but I'm not sure why the rest of the API should be artificially hobbled.  If this is merely an arbitrary "hardware" limitation I'd suggest it's incompatible with things like OVR (which seem to ignore "hardware" limitations entirely). 

At the very least I feel there is a bit of inconsistency here. :-)

**Comment by Weeppiko** [comment]
I think this limitation exists to prevent people from use multiple banks at once, having way more colors for tiles and graphics, and be able to draw multiple maps at once, etc.

**Comment by nesbox** [comment]
> I think this limitation exists to prevent people from use multiple banks at once, having way more colors for tiles and graphics, and be able to draw multiple maps at once, etc.

Exactly
