### ISSUE TITLE
Request: Upgrade Wren to 0.4

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1666]
We're still bundling Wren 0.3.  And now 0.4 is the current release.

This would also close: 

- #1415

Seems there are only 2 breaking changes and I'm not sure either would apply to us (or should be easily resolvable).

**Comment by joshgoebel** [comment]
@RobLoach Any thoughts?  Isn't this right up your alley? :-)  Or am I misremembering? :)

**Comment by Jeephsngdjdbj** [comment]
stop e-mailing me or my cell phone will spoil please

Em qui., 4 de nov. de 2021 9:03 AM, Josh Goebel ***@***.***>
escreveu:

**Comment by RobLoach** [comment]
> We're still bundling Wren 0.3. And now 0.4 is the current release.

Didn't know the new version came out! Happy to see it pushed forwards. Still a long list of Pull Requests too :stuck_out_tongue_winking_eye: 


> @Jeephsngdjdbj  stop e-mailing me or my cell phone will spoil please

You have control over GitHub notifications. Change from WATCH to IGNORE if you don't want any notifications on this project:
https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/viewing-and-triaging-notifications/managing-notifications-from-your-inbox

**Comment by RobLoach** [comment]
@joshgoebel We're already on 0.4.0 :wink: https://github.com/wren-lang/wren/releases/tag/0.4.0
```
4a18fc489f9ea3d253b20dd40f4cdad0d6bb40eb
```
https://github.com/nesbox/TIC-80/tree/master/vendor

**Comment by joshgoebel** [comment]
Right oh, my git submodules were old!  @RobLoach Thanks!
