### ISSUE TITLE
Rpi3 and Rpi4 Baremetal: minus/dash key - is interpreted as an apostrophe

### ISSUE THREAD

**Issue by redej0** [nesbox/TIC-80#1668]
I'm in the US, I believe this might be due to the Raspberry Pi default keyboard country setting to be English UK.  Could we add a feature to set the keyboard type in the config.txt file?  I have to cut and paste a minis/dash from existing code when doing things in the editor.

**Comment by msx80** [comment]
The mapping is defined [here](https://github.com/nesbox/TIC-80/blob/0be2fd8b157284410c373a6b213118a0ba390f28/src/system/baremetalpi/keycodes.h)
It's based on the Italian keyboard, the map is derived from [here at circle](https://github.com/rsta2/circle/blob/bbc9264ead9dc9e0cf5fc2d4530c26b55ca78c29/lib/input/keymap_it.h). There are other layouts available, it shouldn't be hard to port over.
Btw circle already has his Keymap system (and kernel option), perhaps we can let circle do the mapping and then use the mapped value, somehow.
