### ISSUE TITLE
Rp3 and Rp4 baremetal - needs mouse or gamepad support

### ISSUE THREAD

**Issue by redej0** [nesbox/TIC-80#1669]
I see the mouse pointer in the top right corner but cannot interact with it when a USB mouse is attached.  The USM gamepad also seems inop, but perhaps there is a command to enable these that I'm missing.

**Comment by msx80** [comment]
Uhm mouse should work.. Perhaps you have more than one attached to the rpi? some wireless stuff often presents as both keyboard and mouse even if it's only one of them. Try disconnecting all usb except for the mouse.

Gamepad has support but it's super crude. Basically it worked for my own joystick and that's it. Unfortunately game controllers are not very standardized, a good support would require some button/axis/hat mapping tool. That said at least some button should respond..

**Comment by redej0** [comment]
Yes I see. I'm using a VILROS keyboard and touchpad hub for Raspberry Pi.
It is a housing for a Pi3 and 4. It's nice because it looks like a black
C64. I'm trying to make a physical retro computer with the brain if a
Tic-80! Sadly it uses a single wireless dongle. The keyboard works but the
touchpad is not being seen by Tic-80 as a mouse on the bare metal Pi. If I
remove the dongle and plug in a wired mouse then it is seen as you already
know, but then hence, no keyboard. So it plays games well with the keys,
just not quite there for using the editor features since I need some mouse
functionality. I'm hopeful one day it will work if the single wireless
dongle supporting bith a mouse pad/keyboard combo doesn't confuse the
kernel.

**Comment by redej0** [comment]
Problem resolved!  The wireless VILROS touchpad keyboard combo hub
doesn't work as both, and in earlier attempts adding an external mouse
didn't work and only the keyboard was seen.  BUT, getting the VELROS
keyboard hub and an external mouse does work IF you plug them into the 2
left USB2 ports on the RP4 with the mouse on top and the wireless keyboard
dongle in the bottom one!  Yay!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
