### ISSUE TITLE
Question: `BDR` seems to entirely remove need for `SCN`

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1674]
If you try to use both, `BDR` completely replaces any changes that was done during `SCN`

_Originally posted by @Weeppiko in https://github.com/nesbox/TIC-80/issues/1632#issuecomment-962364844_

---

My response:

What I was assuming:

```
- BDR called
- BDR painted (left and right)
- SCN called
- middle of row painted
```

This would allow for border to have an independent palette from the main screen.  Which I assumed was (some of) the point.

The reality:

```
- SCN called
- BDR called
- BDR painted (left and right)
- middle of row painted
```

---

So why do we have both `SCN` and `BDR`?    What was the original thinking behind this?  I know there are a few extra lines (and the `n` count value is therefore different)... but is that the whole reason we have a second callback?

It seems right now it'd be faster to someone to do EVERYTHING in a single `BDR` callback and just avoid SCN.

**Comment by nesbox** [comment]
> It seems right now it'd be faster to someone to do EVERYTHING in a single BDR callback and just avoid SCN.

Yes, you are right, you can avoid `SCN` with `BDR` in the current dev version, but this may change in the future if we move it to the `OVR` stage.

**Comment by nesbox** [comment]
We can use `BDR(144)` instead of `SCN(136)` in all cases, but we have to leave SCN for backward compatibility.

**Comment by joshgoebel** [comment]
So BDR is 0 - 152 then?  I'm updating the Wiki...

**Comment by nesbox** [comment]
No, BDR is 0-143

**Comment by nesbox** [comment]
Looks good, thank you.
