### ISSUE TITLE
Changing border color kills all sprites

### ISSUE THREAD

**Issue by lzap** [nesbox/TIC-80#1681]
Hey,

I would like to do an effect of blinking border for a very short period of time, but the moment I start poking with the color at the documented address, all sprites render as black. Basically it somehow overwrites the memory incorrectly.

```lua
t=0
function TIC()
	cls(13)
	spr(1,96,24,14,3,0,0,2,2)
	t=t+1
 poke(0x03FF8,t%15)
end
```

This draws the Hello World sprite in the first frame, then it starts blinking and the sprite goes black. I tried to poke from `SCN` but it did not help.

**Comment by joshgoebel** [comment]
If you're using the latest version compiled from source you'll need to poke4 not poke as that byte is now also shared with the blit segment. ￼ If you're poking then you're also updating the blit segment which could cause all sorts of problems. ￼

See the memory map on the wiki￼

**Comment by lzap** [comment]
Oh I see, can I safely call `poke4` from `SCN` then?

**Comment by lzap** [comment]
Oh I see, so I need to `peek` and `poke`.

**Comment by joshgoebel** [comment]
You can poke individual bits now... you don't need to read, modify, write...

**Comment by lzap** [comment]
Thanks!

**Comment by joshgoebel** [comment]
Did that fix it?

**Comment by lzap** [comment]
Apologies, I gave up when I realized that would be not inclusive for people who are sensitive to blinking. So I ditched the idea completely. But I could not get it working, no :-)

**Comment by nesbox** [comment]
```lua
t=0
function TIC()
	cls(13)
	spr(1,96,24,14,3,0,0,2,2)
	t=t+1
---------------------
-- use poke4() to set 4bit value here instead poke()
	poke4(0x03FF8*2,t%15)
end
```
