### ISSUE TITLE
[1.0-dev] The export templates are outdated

### ISSUE THREAD

**Issue by scambier** [nesbox/TIC-80#1682]
Exports for (at least) HTML and Windows are still using the `1.0.1782-dev` version, even when exported from a `1.0.1808-dev`. This causes issues due to the vram layout change (related to #1508) if you're using 1bpp or 2bpp sprites.

Render from the editor:
![image](https://user-images.githubusercontent.com/3216752/140661856-20e6931e-9cec-45c9-bf68-cd8697180bd3.png)

Render from a Windows or HTML export:
![image](https://user-images.githubusercontent.com/3216752/140661875-e43d752f-b0cc-4494-b4a8-0907c90c1625.png)

**Comment by joshgoebel** [comment]
@nesbox The backwards compatibility of this change may need to be considered.
