### ISSUE TITLE
Question: Licensing issues regarding emulating REAL processors

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1686]
I've been looking at older 8-bit processors... like the 6502 and Z80... does anyone know if there are any type of intellectual property or licensing issues if we built an emulated 6502 or Z80 CPU core into TIC-80 that could be then used to write software for the rest of the TIC-80 fantasy hardware stack (screen, gfx card, audio card, etc)... See #1007.

**Comment by RobLoach** [comment]
I suppose it depends on which architecture you're looking at? MAME has re-implemented a lot of old hardware as software, and is GPL-2.
