### ISSUE TITLE
Drawing VRAM trails glitch

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#1687]
On the master branch there's a graphical glitch in certain games (such as https://tic80.com/play?cart=692) which does not occur on the stable release. Moving the cursor leaves behind trails and doesn't clear it.
![powder-bug](https://user-images.githubusercontent.com/141/141035612-94c9036d-634a-4b12-bf4e-23c218eec255.gif)

Someone on IRC told me that they bisected this problem to this commit: https://github.com/nesbox/TIC-80/commit/973dd00a3227036addb073472f0ec49757664784

**Comment by nesbox** [comment]
I reproduced it, will try to fix, thank you

**Comment by nesbox** [comment]
#1709 dup
