### ISSUE TITLE
Disable Editors

### ISSUE THREAD

**Issue by ZYOUNG10** [nesbox/TIC-80#169]
The ability to disable editors in a "finished product" of a game would be nice :D

**Comment by Effer** [comment]
Like it.

**Comment by hseiken** [comment]
+1 but only for webplayer for obvious reasons.  I think the editor shouldn't be disabled from viewing code, however, but in terms of editing, there's no point to have it in the webplayer if the point of the webplayer is pure distribution of projects to non-TIC users.

**Comment by darkhog** [comment]
Well, "on site" webplayer should have this functionality as it makes it easier to see how other people done certain things, but yeah, after issuing export command the resulting binary or html/js shouldn't have editors enabled unless you specifically allow for them (it should be an option to keep them for the developers who would like their game to be modded)

**Comment by Yukitty** [comment]
If the console and editors were _completely stripped out_ of exported builds, they could potentially be a lot smaller too, and maybe my text editor wouldn't barf at how big the html is...

**Comment by DjPale** [comment]
A lot of player hit Esc by default since it often means "cancel" or "back" or similar. So an option for disabling would be good. Agree that one could consider only having it in a web-player. Another solution would be to make a different shortcut for breaking out the game like `Ctrl-Q` or similar.

**Comment by nesbox** [comment]
it can be a part of TIC-80 Pro :)
encrypted game resources without editors...

**Comment by jahodfra** [comment]
I like that all games have visible code and assets. It makes tic80 nice learning tool. Disabling editors would prevent cheating, but in the same way it would make harder to lure gamers into game making (and programming).

**Comment by andrechalom** [comment]
I think this links to #387 - maybe games that have reuse licenses should have some sort of "read-only editors" at least, but games with no license can strip editors completely?

**Comment by Jummit** [comment]
I would like this feature to give the finished game to a friend or so. On the web page, editors should be always enabled by default (see what jahodfra said).

**Comment by carlsmith** [comment]
On remapping Escape to Ctrl-Q, Ctrl-Q is commonly bound to Quit, so it would need to be something different, but I think it's a bad idea anyway.

If you don't want end users accessing the code from in the game, the solution is to disable that feature, not to obscure it behind a more awkward keybinding. That doesn't solve the problem (it only minimises it), and it makes life a little bit more difficult for the vast majority of users, two hundred times a day.

**Comment by ChildishGiant** [comment]
Is this still on the cards?

**Comment by RobLoach** [comment]
Tossing my vote in against this. A big part of what makes TIC-80 appealing is the open nature to it. Being able to see how a project was made invites collaboration and more involvement.

What are you trying to hide by disabling the editor? Have you stolen some assets and don't want people to know? Are you using some malicious code that goes against the original author's license? Keeping things open and transparent protects yourself and encourages community growth.

If you really want to keep people from seeing your work, however, you could obsuscate the source code, and embed it in a TIC-80 player binary directly. But why?

**Comment by ChildishGiant** [comment]
Well if one wanted to publish a game to steam or something like that I think most people would agree that it looks more professional to not have the editors enabled. Imagine if every unity game came with the editor installed and by pressing F1 you could change anything to do with the game. [This video by Game Maker's Toolkit](https://www.youtube.com/watch?v=7L8vAGGitr8) comes to mind. Enabling a player to cheat can, despite what they think, ruin their experience.

**Comment by RobLoach** [comment]
You could embed the cart binary into your own sdl player:
https://github.com/nesbox/TIC-80/blob/master/src/player/sdl.c#L42-L43

Would give you the added benefit of using SDL to add your own application icon, window title, etc.

**Comment by AndersonFirmino** [comment]
> Tossing my vote in against this. A big part of what makes TIC-80 appealing is the open nature to it. Being able to see how a project was made invites collaboration and more involvement.
> 
> What are you trying to hide by disabling the editor? Have you stolen some assets and don't want people to know? Are you using some malicious code that goes against the original author's license? Keeping things open and transparent protects yourself and encourages community growth.
> 
> If you really want to keep people from seeing your work, however, you could obsuscate the source code, and embed it in a TIC-80 player binary directly. But why?

What if I want to send my game to end users? who don't know how to program. It would be nice that this option really exists and I even bought the pro version just because of that.

**Comment by borbware** [comment]
I'm planning to ship a commercial game with TIC-80 this year, so yeah, I'd like to see this feature in the pro version. At the moment It's way too easy to get stranded in the terminal with just two start button (or ESC) presses.

**Comment by joshgoebel** [comment]
> At the moment It's way too easy to get stranded in the terminal with just two start button (or ESC) presses.

I wonder if you couldn't just add some JS to the webpage to grab the ESC key and ignore it?

**Comment by ChildishGiant** [comment]
> I wonder if you couldn't just add some JS to the webpage to grab the ESC key and ignore it?

What if you're not shipping it as a webpage?

**Comment by joshgoebel** [comment]
No suggestion then, sorry.

**Comment by borbware** [comment]
Yeah, the problem was present on every platform. Emphasis on _was_, Nesbox kindly fixed the issue already! ^^

**Comment by ChildishGiant** [comment]
> Export your game without editors, and then publish it to app stores (WIP)

https://github.com/nesbox/TIC-80/commit/96fa418accd4eda51bf17c5b6230ffa3c4a64288 It's been three years 🥺

**Comment by nesbox** [comment]
Added `alone` parameter to export game without editors support (only Pro)
Usage: `export [win linux rpi mac html] <game> alone=1`

**Comment by ChildishGiant** [comment]
`alone=1` doesn't seem to do anything different to a normal export for me. I'm running 0.90.1676-dev (da18f30) tic80-ubuntu-sdlgpu-deb. Here's the default cart exported using `export linux test alone=1`. Also worth noting that the binaries made aren't marked as executable but that's not a massive issue
[test.zip](https://github.com/nesbox/TIC-80/files/6677988/test.zip)

**Comment by nesbox** [comment]
Pls use Pro version

**Comment by nesbox** [comment]
Added `chmod 0755` for exported binaries here 3233766.

**Comment by borbware** [comment]
i built a new pro version with mingw, and it runs fine, but there's something broken in the export. If i export a windows build with alone=1, the game screen is all black - but i can still press ESC to enter the pause menu, where "close game" isn't any more, as supposed. If i export without the alone parameter, the exported .exe file does not contain the game - it's just a regular tic-80 executable.

**Comment by nesbox** [comment]
Just checked, all is ok on my side, could you pls provide the cart you used pls?

**Comment by nesbox** [comment]
Or better check this one [game.zip](https://github.com/nesbox/TIC-80/files/6678975/game.zip) on your side pls.

**Comment by borbware** [comment]
game.zip runs fine on my machine.
