### ISSUE TITLE
What's the use of exit() in a cartridge without editors?

### ISSUE THREAD

**Issue by Joseph02MR** [nesbox/TIC-80#1690]
The wiki is clear about the command, it just returns to the console when called.

But when i use the same code in the same project exported with param alone = 1, the command causes unexpected behaviour.
Basically the screens stops showing the mouse pointer and i have no response from the program, the only thing left is closing and reopening.
Here are short demos from a little project i was making with editors and without editors. The stop button just calls exit() when pressed.

I was expecting it to close the program instead if the cartridge has no editors, but now I'm not so sure if that is a feature useful for the program or just a misuse from me.
 
alone=0
![aloneFalse](https://user-images.githubusercontent.com/67172507/141609121-2e47390c-ef21-4233-9763-7ca2368c2260.gif)
alone=1
![aloneTrue](https://user-images.githubusercontent.com/67172507/141609153-7b2a0f21-2713-4972-953f-a545c886138d.gif)

**Comment by nesbox** [comment]
It's a bug, of course, the program should be closed on `exit()` without editors.
Thank you for the report.

**Comment by nesbox** [comment]
Fixed here ca5b6c8961c36d483c6504c03253daeb4effde51
Thank you
