### ISSUE TITLE
Request: BINARY chunk, support external compilers

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1693]
Related #1007.

Could we add a BINARY chunk and external compiler support?    The intention is to support fantasy (or not) emulated CPUs and to allow usage of external (quite complex) compiler toolchains (Assembly, Rust, C, etc) to produce the compiled machine code.

See #1694 for further background.  Of course this wouldn't apply to just 68000.  It would apply to any language that compiles down to machine code / bytecode (And this isn't suitable for storage in the CODE chunk - because the code itself might be stored there).

This also paves the road for distributing cartridges/games that no longer contain the source they were build from.

**How it might work with cartridges:**

```
tic80 --cmd "load cart.tic & import binary cart.bin & save"
```

Would take the data from `build.bin` and load it into the BINARY chunk of the cartridge.

**How it might work with project:**

The binary data would simply be included as any other binary data is:

```
-- <BINARY>
001:eccccccccc888888caaaaaaaca888888cacccccccacc0ccccacc0ccccacc0ccc
002:ccccceee8888cceeaaaa0cee888a0ceeccca0ccc0cca0c0c0cca0c0c0cca0c0c
003:eccccccccc888888caaaaaaaca888888cacccccccacccccccacc0ccccacc0ccc
...
```

When working on a project with an external build toolchain it would be the build processes job to compile the source in the project source file, and then re-write the source file so that than `BINARY` section contained the latest release.  For easy development this would be done with some type of file watch process most likely.

Would could also add a `BINARY_ZIP` chunk for parity (though I think this is a bad idea - the amount of binary storage "ROM" should be a fixed amount, not subject to random size issues depending on compressibility)... obviously for distribution you could imagine a cartridge with only a BINARY chunk and no CODE chunk...

@nesbox Thoughts?

**Comment by joshgoebel** [comment]
Editing this right now to split out the BINARY question from the 68000...

**Comment by nesbox** [comment]
I think the `BINARY` chunk idea sounds good and can be easily integrated, also I just realized we have an unused `temp` field in the `Chunk` struct that can be used as a binary definition: `0 - WASM`, `1 - Motorola 68000` and so on.

https://github.com/nesbox/TIC-80/blob/master/src/cart.c#L62

``` c
typedef struct
{
    u32 type:5; // ChunkType
    u32 bank:TIC_BANK_BITS;
    u32 size:TIC_BANKSIZE_BITS; // max chunk size is 64K
>>> u32 temp:8; // could be a chunk parameter
} Chunk;
```

**Comment by joshgoebel** [comment]
>  also I just realized we have an unused temp field in the Chunk struct that can be used as a binary definition:

Sure, or we could also leave it reserved.  There is no reason the chunk data itself couldn't include that piece of meta-data upfront... ie:

```c
typedef struct
{
    u8 binary_type;
    char data[TIC_BINARY_SIZE];
} tic_binary;
```

> I still don't know what to do with the Code Editor if the binary chunk is present, we could disable it or maybe leave it as it is and TIC-80 will ignore the code...

I say let's try not to overthink it... I imagine you might have some comments or notes about the program there, OR you might include the full source as well (for reference).  OR (for some architectures) TIC-80 might be able to build the binary chunk from source.... so a cartridge might hold both.  

The biggest point of confusion I see is:

- someone includes the source (for reference)
- TIC-80 can't re-build the binary chunk
- some other person tries to edit the code without knowing this.

I think in that case you could perhaps show a special warning or something - some indication that they are running from the binary segment, not source.

**Comment by nesbox** [comment]
Ok, let's do nothing with the code editor for now.

**Comment by joshgoebel** [comment]
@nesbox Could you give me a few hints?  What 2-3 main files am I likely to need to touch to pull off the main piece of this work?

**Comment by nesbox** [comment]
First of all, add a new chunk definition here https://github.com/nesbox/TIC-80/blob/master/src/cart.c#L38
as well as load/save to `tic_cart_load()/tic_cart_save()` (same for the project support `tic_project_load()/tic_project_save()` https://github.com/nesbox/TIC-80/blob/master/src/studio/project.c)
You can load the binary to the `tic_cartridge` https://github.com/nesbox/TIC-80/blob/master/src/tic.h#L438, so define some data here.
And finally, here https://github.com/nesbox/TIC-80/tree/master/src/core/core.c#L436 you can init your wasm VM with your binary data.
That's all for now...

**Comment by joshgoebel** [comment]
Thanks, super helpful!  And regarding the:

```
tic80 --cmd "load cart.tic & import binary cart.bin & save"
```

Where do I want to look for adding import and export commands for BINARY?

**Comment by nesbox** [comment]
Add `binary` to the `IMPORT_CMD_LIST` https://github.com/nesbox/TIC-80/blob/master/src/studio/screens/console.c#L93
The import/export  commands parameters are here https://github.com/nesbox/TIC-80/blob/master/src/studio/screens/console.c#L93

**Comment by joshgoebel** [comment]
You pointed me to the same two locations in your last post, did you mean to use two different URLs?

**Comment by msx80** [comment]
Hi, love how this binary chunk is working!

About what to show in the editor, just to share what i did with WASM: i extracted the textual representation of the binary and shown that. Wasm has a 1-to-1 textual representation of the binary called "wat" and a tool to convert between binary and text (wat2wasm and wasm2wat). The appeal is that you can look at the actuall code and even modify it. Probably nobody sane would ever modify wat code manually, so that's certainly totally useless but it felt right to have the code editor show something really connected to what you're actually running.  
In theory the same thing could be done with 68000 or other assemblys, as mnemonic representation is very easy to extract and to rebuild as binary (not talking about a full blown assembler with variable and labels here, just instruction decoding).

The system could be generalized if all "binary languages" were required to provide their own 2-way converter. 

Just some toughts, not really proposing it. Probably overkill!

Another idea is to show a generic "hex editor" like this one that would work for any binary blob.
![image](https://user-images.githubusercontent.com/2278103/147707219-3fb42ff6-77af-4b0c-a088-877e7338b73e.png)

**Comment by joshgoebel** [comment]
> -(same for the project support tic_project_load()/tic_project_save()

I'm going to circle back to this last.  _I'm not sure BINARY belongs in projects at all..._ I just don't see the workflow for it...  project are intended for working with text source where the source is *runnable* by TIC-80.  This won't be the case with BINARY _most of the time_... 

And in cases where it is possible - if we include a WAT to WASM compiler... then again the BINARY chunk doesn't matter (in a project)... the source matters - TIC-80 would compile to WASM each time the cartridge was reloaded doing live development (same as Lua etc is reinterpreted every time a cart reloads etc).

I imagine most people will be using compiled toolchains that know nothing about TIC-80 and using `import binary` to get build code into their cartridges.  So the workflow is:

- You have your cartridge (.TIC) open in TIC-80.
- You have your C#/C++/Zig/Go/Rust project (with potentially many files) open in your primary editor of choice.
- After you build the project `tic80 --cmd 'import binary'` is called, updating the cartridge and resulting in the running TIC-80 instance to auto-reload it.

So I can't see any point of having BINARY chunks in projects.... I just don't see "project mode" being all that useful with BINARY.

**Comment by nesbox** [comment]
Ok, sounds reasonable, thanks.

**Comment by joshgoebel** [comment]
**All code below is pseudo-code, not actual WASM instructions since I don't know all the instructions off the top of my head.**

Are their any thoughts on the LOW-LEVEL Wasm API?  WASM functions have a fixed # of parameters and a single output value (I'm sure WASM-3 [our interpretter] supports multi-output values yet)... so that means that a lot of function signatures will look similar to a low-level C API:

```js
// psuedo-code!!
pix(0,0,16) // write pixel
pix(0,0,-1) // read pixel
```

So our `pix` would just be a function with 3 arguments that _always_ returns the color...  someone is free to ignore it.  And if you want to read the pixel you pass `-1` for the color to be written.  Of course in the higher-level language wrapper libraries there may be much nicer ways to deal with this.  In `C++` for example you'd likely just make the `-1` a default argument for the last parameter and then the 2 or 3 argument version of `pix` works "magically".

This however gets uglier for some fo the functions with a zillion params:

```
map [x=0 y=0] [w=30 h=17] [sx=0 sy=0] [colorkey=-1] [scale=1] [remap=nil]
```

Do we want to just do the lowest-level thing possible in WASM and require all these params, all the time?  IE to just call `map()` one would need (low-level) the following WASM instructions:

```js
// psuedocode
i32.push 0
i32.push 0
i32.push 30
i32.push 17
i32.push 0
i32.push 0
i32.push -1
i32.push 1
i32.push -1
call $map
```

I think this may be OK - and let the higher-level libraries sort out doing it nicer *if possible*... 

It does get a bit ridiculous for some functions though like `clip`... we either require the programmer to keep track of the details, or we build it into the TIC_80 API layer... so either:

```
i32.push 0
i32.push 0
i32.push MAX_WIDTH
i32.push MAX_HEIGHT
call $clip
```

OR:

```
i32.push -1
i32.push -1
i32.push -1
i32.push -1
call $clip
```

I actually started out with `clip(x,y,w,h)` and `noclip()`... would we be open to possibly expanding the API in a few areas (for all languages) for some of the more ridiculous examples... or would it be ok if WASM was just a "special case" and supported a slightly extended API to make some for the edge cases nicer?

**Comment by joshgoebel** [comment]
Taking a simpler example:

```
sync [mask=0] [bank=0] [tocart=false]
```

I feel like the "simple just works" TIC approach boiled down to WASM might would be `-1` for "i dunno" or "just do the right thing"... ie, no one would need to know the defaults to call the API - that would be all handled INSIDE TIC, not WASM. So to call `sync()`, effectively `sync(0,0,false)` you would need to know that `-1` was "default" and the number of arguments (to push the right number of args onto the stack).

```
i32.push -1
i32.push -1
i32.push -1
call $func
```

Does that sound right?

**Comment by joshgoebel** [comment]
Sorry this should really have been in the Web Assembly thread...

**Comment by joshgoebel** [comment]
If we're supporting 512kb of code now (64kb * 8 banks) could we start by supporting perhaps say max 256kb BINARY chunks?  64kb doesn't seem realistic anymore.  Technically you could also limit the `import` command based on whether you had PRO or not... if we wanted to have two tiers.  I was told we do that with CODE, but I'm not sure we do?

**Comment by nesbox** [comment]
I don't see a problem here because the basic (non-pro) version runs 512kb code carts without problems, the limitation is only valid in the code editor, but we don't use it for BINARY chunks.

**Comment by joshgoebel** [comment]
So I think I'm hearing a "yes" there, that it's fine to have 256kb chunks for better parity with the larger CODE segment.

**Comment by nesbox** [comment]
hmm, now I'm not sure we understand each other correctly, pls don't change chunks size, just save the 256kb binary in `64kb * 4 banks`, because we have only 16bits to save the chunk size
```c
typedef struct
{
    u32 type:5; // ChunkType
    u32 bank:3; // [0-7]
    u32 size:16; // max chunk size is 64K <<<<<<<<<<<<<
    ...
} Chunk;
```

**Comment by joshgoebel** [comment]
Ah, _that's why you're jumping thru hoops putting code in a bunch of different chunks_. I wondered. *thinking*

I may just put it back down to 64kb for now and let someone else take that... it seems like now that we have TWO large data pieces that the code you use to save "multi-chunk chunks" should probably be abstracted... and that's probably beyond my C foo (to do it nicely - I imagine it would involve macros) or would simply take me too long vs other things I could be working on.

**Comment by joshgoebel** [comment]
Closing via https://github.com/nesbox/TIC-80/pull/1772. (which was manually merged)
