### ISSUE TITLE
Request: Motorola 68000 CPU Support

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1694]
Related #1007. #1693.  I've updated this top-section to be my "vision" for 68000 on TIC-80.

I feel like non-fantasy CPU architectures on TIC-80 are a "whole new ballgame".  They are likely going to need different ways of thinking about them compared to interpreted languages.  I feel that each CPU architecture we support should be a "in good faith" representation of that CPU used as it might have been used historical in a similar retro environment.  Much like our JS scripting is "real ES5 Javascript"... not "well it's sort of JS, but not really, with so many TIC-80 specific quirks"... **our 68000 support shouldn't be some frankenstein monster or "TIC-80 flavored 68000"** - it should be a normal Motorola 68000 that's "physically" [fantasy] wired to regular hardware and TIC-80 specific hardware pieces. IE, the fantasy story would be something like:

- A 240x136 LCD/OLED, etc...
- ROM/EPROM segments (in the form of the cartridge data/code)
- RAM segments (running memory for sprites, data storage, etc)
- A "GPU" chip for accelerated graphics operations
- An IO board for keyboard and controller inputs, etc.
- Its memory layout should make sense given known 68000 systems.

Now some of this could indeed by handled by memory mapped into the device memory segment (such as the controller I/O, VRAM, etc)... but in areas where the 68000 was historically implemented a certain way, I think we should follow that path:

- Interrupts are used to signal VBLANK (`tic`), HBLANK (`scn`), etc.
- Likely a tiny ROM accessed by traps to support non-GPU TIC-80 features: timekeeping, bank-switching, etc.
- [Trap #15 IO](http://www.easy68k.com/QuickStart/TrapTasks.htm) in ROM
  - one would halt the emulator by calling Trap `#15` routine 9.  This would be the equivalent of `exit` in the existing API.

Thus immediately making developing for 68000 familiar for anyone who's developed for it before in a retro console/computer environment.  As such I provide the following big-picture check-list for this meta-task:

- [ ] TIC-80 support for `BINARY` chunks
- [ ] VBLANK (tic)
- [ ] HBLANK (scn/bdr)
- [ ] How to handle overlay?
- [ ] Trap `#15` limited support (halt, etc)
- [ ] Tiny ROM functions for non-GPU API access (`trace`, `tstamp`, etc)
- [ ] Memory-mapped GPU command pipeline for those wanting to talk directly to "hardware"
- [ ] Tiny ROM for GPU access (to wrap the memory-mapped pipeline)???
- [x] Memory layout that makes sense for 68000
- [ ] Can we bump unmapped "free user ram" to 64kb?
- [ ] Should cartridge ROM/code space be 64kb or 128kb?
- [x] Need GCC linker script to support copying BSS/startup values, etc...??? (for those wanting to use the gcc m68k compiler)

**Suggested memory layout**

This is a draft, could use more feedback here.... but obviously this is not the typical TIC-80 layout... since we can't have VRAM at `0` I think it makes sense to go with a more "real" 68000 layout instead.  Here is an example that lays everything in the first 1mb of addressable space:

```
0x00000 - 0x003FF   Interrupt vectors (1kb)
0x10000 - 0x1FFFF   Available RAM (for use by variables, stack, etc) (64kb)
0x80000 - 0x8FFFF   Cartridge Program ROM (64kb)
0xA0000 - 0xAFFFF   TIC-80 "BIOS" ROM (64kb)
0xC0000 - 0xDFFFF   Device I/O and RAM map (128kb, not all backed)
```

Whatever "MMU" we have would support paging individual areas in and out of the Device address space such as everything supported by `sync`: TILES, SPRITES, MAP, SFX, MUSIC, PALETTE, FLAGS, SCREEN. 

We could try and line all these things up at 8kb boundaries or something just to make them a bit nicer to work with.  Overall I'm suggesting almost all of current TIC-80 "RAM" (less 12kb) be moved into the device area of memory and that our free RAM be broken out (and increased) and that be entirely separated from the device IO.

I chose 64kb because it sounds like a realistic number that's in line with the limits we use elsewhere.  An open question is whether (for parity with 64kb of interpreted code) if cartridge might need a 128kb ROM rather than 64kb.

---

_Original post:_

I think super simple 8-bit/16-bit CPUs (despite the 6502 and Z80 being "fun" ideas) may not be enough to integrate with TIC-80 _easily_: too primitive, no multiplication, no easy 16-bit math (on 8-bit), no easy way to address the full 96kb of RAM without banking (not to mention all of the chips being Von Neumman vs Harvard - so no way to address ANY RAM at all if you assume 64kb code segment)... IMHO there are enough other problems to solve here (for a first "fantasy" CPU) that I think a more modern platform makes a bit of sense. 

I've taken a liking to the [Motorola 68000](https://en.wikipedia.org/wiki/Motorola_68000).  We have multiplication opcodes, plenty of address space, interrupts, some idea of privileged mode, etc... and it's still retro-ish IMHO. It's also seen a resurgence recently with LLVM and Rust gaining support for the architecture, so toolchain options are improving (if one wants more than assembly).

So, are we open to having a CPU core like that in TIC-80 proper? On my system:

- TIC-80 PRO build: 4.4mb
- 68000 assembler: vasm m69k MOT build: 440kb
- 68000 emulator: Musashi: 700kb

The emulator code seems simple enough to work with, but I'm less excited about committing myself to integrating a full assembler... and there are perhaps licensing issues also with VASM (though perhaps they could be resolved).  The emulator core I've found is MIT licensed, so that's ready to roll.  Even if we were to bundle AN assembler there might still be desired to use an external (better) assembler... so it seems this would still be a question.

Source would be compiled into binary that would be stored in a new BINARY chunk. See #1693.

Thoughts?  I'm considering working on this myself if there is interest.

**Comment by Anrock** [comment]
Toolchain support and available emulator is really great but after quickly skimming mk68k manual it seems like it has huge amount of instructions we wouldn't ever need. Like multiprocessor control, MMU, cache control, supervising. I'm not sure how they would integrate into TIC-80.

@joshgoebel Were there any other alternatives you considered?

**Comment by joshgoebel** [comment]
I expanded the initial message greatly with my idea of more of a vision/plan for 68000 and how I think it might be very different from the existing interpreted languages.  Some big questions:

**Can we have more RAM?**

The existing map only has 12kb of "free" RAM... meanwhile no one uses it... existing cartridges allocate however much RAM they need inside the interpreters with no limits whatever.  A CPU needs a "real" actual limit, and I don't think 12kb is the correct number.  It seems that roughly (as much as possible) the various TIC-80 supported environments should have "parity"...

I shouldn't be able to write a small game in Lua that I couldn't also write in Wren, or in 68000 C/assembly. So since Lua and Wren have "unlimited" RAM currently then to be fair I think the 68000 needs to step a little closer to parity with that than 12kb.

64kb is what I suggest and the first number that comes to mind.  The interrupt vector table could be paid for out of this if necessary, giving us 63kb of usable RAM for cartridges.

**Can we have more ROM?**

I think the assumption was 64kb CODE max means we should have 64kb BINARY max... but compiled low-level code might be a lot larger or smaller than it's written form... if we find a huge disparity (between what 64kb of Lua does and what 64kb of 68000 machine code does) are we against binary ROMS supporting larger sizes?  It's possible for example that 128kb might be a better fit here.

**Comment by Anrock** [comment]
@joshgoebel
> a tiny ROM accessed by traps to support non-GPU TIC-80 features: timekeeping, bank-switching, etc.

> Tiny ROM for GPU access (to wrap the memory-mapped pipeline)???

Can you elaborate more on that? Is this about "magical" opaque routines that can't be implemented by user? If not, how about distributing as source code instead? In cart template or separately maybe.

**Comment by joshgoebel** [comment]
There would be source for everything.  Just inside TIC-80.  At the core it's all assembly so the user could do whatever they wanted, not call the BIOS, etc... the end goal would be to have 0 magic... at the bottom it's just all CPU opcodes and memory.  But the difference is fast or slow, as in:

```
const int VRAM = 0x9000000;
void pix(int x, int y, unsigned char color) {
  int offs = (y*240+x)/2;
  unsigned char old = peek(VRAM + offs);
  unsigned char result;
  if (x & 0b1) {
    result = (old & 0x0F) | color << 4;
  } else {
    result = (old & 0xF0) | (color & 0xF);
  }
  poke(offs, result);
}

const int VRAM_cmds = 0x9200000;
const int VRAM_commit = 0x9200990;
const int DRAW_PIXEL_OP = 22;
void GPU_pix(int x, int y, unsigned char color) {
  char* cmd = (char*) VRAM_cmds;
  char* commit = (char*) VRAM_commit;

  *(cmd++) = DRAW_PIXEL_OP;
  *(cmd++) = (unsigned char) x;
  *(cmd++) = (unsigned char) y;
  *(cmd++) = color;

  *commit = 0xFF;
}
```

The latter routine compiles down to just 5 CPU opcodes (all storing the byte sequence to RAM)... while the former gets choked up on :

```
int offs = (y*240+x)/2;
```

Which alone generates 15 instructions or so... not even counting the rest of the routine.

**Comment by Anrock** [comment]
@joshgoebel okay, than why store it in ROM instead of putting into demo cart?

**Comment by joshgoebel** [comment]
For the same reason people don't have to include the whole Lua API in their cartridges.  Because the cartridge is already size constrained and these routines waste a lot of space.

**Comment by joshgoebel** [comment]
> okay, than why store it in ROM instead of putting into demo cart?

I am coming around to perhaps thinking that might be simpler though (and would make cartridges more resilient since they'd depend on nothing other than themselves - ie, you could never break a cartridge with a BIOS upgrade)... just it would making writing assembly harder (without an BIOS interrupts to use to make things easy)...

We could always start that direction (monolithic cartridge) and then later pull the functions out into their own ROM, so that might be what I go with first.

**Comment by joshgoebel** [comment]
The "just a bit of magic" functions like `btnp` and `keyp` are annoying and I think for now I might treat them as tiny little hardware I/O devices... the alternative is porting the button state tracking code from TIC to the 68000 VM (and exposing it in the address space somewhere)... and while it's not "hot" code... it would just be wasteful to have it in both places... making two things to maintain.

And of course APIs in C with optional params are UGH. :-)  So er can use a C struct to represent the request object/API (this is on the 68000 library side):

```c
typedef struct {
  char commit;    // tells the IO devices to run the request
  char pressed;   // results
  // params
  char id;
  uint16_t hold;
  uint16_t period;
} btn_request_s;
```

Then you just write that to RAM by making a pointer to the struct:

```c
const long int TIC_BTNP_QUERY_ADDR = 0xF0000;

bool tic_api_btnp(char id, int hold, int period) {
  btn_request_s* req = (btn_request_s*)(TIC_BTN_QUERY_ADDR);
  req->id = id;
  req->hold = hold;
  req->period = period;
  req->commit = EXECUTE;
  // wait for the hardware to see our request and write
  // response with the button status based on it's
  // internal button tracking state
  while (req->commit == EXECUTE) {};

  return req->pressed;
}
```

Anyways I'm just playing with this and feeling it out as I go.

**Comment by joshgoebel** [comment]
Ah, forgot about varargs, perhaps this is better:

```c
#define tic_api_sfx(...) tic_api_sfx(NARGS(__VA_ARGS__), __VA_ARGS__)

void fntic_api_sfx(char nargs, char id, ...) {
  sfx_request_s* req = (sfx_request_s*)(TIC_SFX_QUERY_ADDR);
  va_list ap;
  va_start(ap, id);
  req->id = id;
  req->note = nargs > 0 ? va_arg(ap, int) : -1;
  req->duration = nargs > 1 ? va_arg(ap, int) : -1;
  req->channel = nargs > 2 ? va_arg(ap, int) : 0;
  req->volume = nargs > 2 ? va_arg(ap, int) : 15;
  req->speed = nargs > 2 ? va_arg(ap, int) : 0;
  req->commit = EXECUTE;
  va_end(ap);
}
```

**Comment by TheRektafire** [comment]
How many cycles per frame would the cpu get? If we're going off how fast the cpu was run under traditional circumstances then it seems like it should have ~8mhz so presumably each frame would just get that / 60? And how would it work with stuff like the "gpu", it would be cool if the GPU ran in lockstep with the cpu (ie for every "x" cpu cycles the gpu advances across the screen by 1 pixel) so you could do stuff like change palettes per line with an hblank interrupt or change the screen offset on every line to easily achieve certain types of graphical effects like wavy graphics. But idk how the renderer is written currently so that might involve rewriting a ton of stuff

**Comment by joshgoebel** [comment]
>  If we're going off how fast the cpu was run under traditional circumstances 

I'm not sure that's reasonable since this is a VERY different environment... where we have a *powerful* "GPU" doing much of the work (for many games)... I'm taking a wait and see approach until we actually have some real code running and see what mhz seems to "fit"... and we also have to take into consideration our slower platforms like Android/RaspberryPi... can they emulate the 68000 at 8mhz easily?  

> it would be cool if the GPU ran in lockstep with the cpu ... so you could do stuff like change palettes per line with an hblank interrupt 

There is no need for any type of "lockstep" (like what you describe) to support HBLANK interrupts... these would probably just be triggered via interrupt and the interrupt handler would do whatever it wanted before the line was drawn... very similar to how it works on all the other languages - just here it's interrupt driven instead of function driven.

**Comment by TheRektafire** [comment]
> I'm not sure that's reasonable since this is a VERY different environment... where we have a powerful "GPU" doing much of the work (for many games)... I'm taking a wait and see approach until we actually have some real code running and see what mhz seems to "fit"... and we also have to take into consideration our slower platforms like Android/RaspberryPi... can they emulate the 68000 at 8mhz easily?

Can a raspberry pi run a sega genesis or Amiga emulator at full speed? If so I'd say yes especially if said emulators are cycle and hardware accurate. Android phones easily could at least the more expensive ones, not sure what the lower limit would be there though
