### ISSUE TITLE
Mouse scroll-wheel x value?

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1695]
I just updated the wiki mouse() example but I have no idea what the scroll-wheel x value is supposed to represent - can someone put me out of my misery? :D

**Comment by Weeppiko** [comment]
The scroll wheel valuea represents... well, the scroll wheel...
Most commons mouses only have a wheel for scrolling in the y direction, but some mouses do also have a wheel to scroll in x direction

**Comment by paul59** [comment]
I thought maybe some other input or key/mouse button/wheel combination was being mapped there.

According to https://en.wikipedia.org/wiki/Scroll_wheel: 

"Some mice can scroll horizontally as well as vertically, using a tilting scroll-wheel, or additional wheel on a perpendicular axis located elsewhere on the mouse."

Does such a device exist? I've never seen one.

**Comment by joshgoebel** [comment]
Sure. My Apple mouse has a ball like trackpads. You can scroll horizontal, vertical, diagonal, any which way.

**Comment by joshgoebel** [comment]
> always assumed that would equate to mouse x,y

If it was a trackpad it would. But if it's a mouse with a "trackball" on top you now how two entirely different coordinate systems.
