### ISSUE TITLE
Check some Fennel games

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#1709]
From #1708:
https://stefandevai.itch.io/amethyst-waters
https://alloy-d.itch.io/butterfly-effect

**Comment by technomancy** [comment]
As I mentioned elsewhere, the bug with Amethyst Waters is a duplicate of #1687.

The bug with Butterfly Effect is different, but using bisecting I found that it was introduced in a54f4b1 by #1508.

**Comment by nesbox** [comment]
fixed with a6b4b7e
