### ISSUE TITLE
New font for tic-80

### ISSUE THREAD

**Issue by Tyler887** [nesbox/TIC-80#1712]
### Discussed in https://github.com/nesbox/TIC-80/discussions/1711

<div type='discussions-op-text'>

<sup>Originally posted by **icubyx** November 28, 2021</sup>
Hi, 
I'm new to the console and after fiddling around, I really am liking the console, but for the font. The wide font takes up too much space and the compact font is compact but could look better. Is it possible to change the font to the one used on the main website instead? It is compact as well as much more readable. 
Just my 2 bits and a request. 
Thanks for all the wonderful work being done on this - it has helped kindle my interest in learning programming!</div>

**Comment by RobLoach** [comment]
Not sure why this needs to be an issue, as it's already a discussion.
