### ISSUE TITLE
Pull cartridges off of Github or Website for easy collaboration and game sharing

### ISSUE THREAD

**Issue by UntrustedInstaller** [nesbox/TIC-80#1720]
I have a proposal if this isn't already a feature (other than SURF), The ability host your cart on your own website (e.g., https://untrustedinstaller.github.io/tic80-carts.html [not a real link on my page]) or something like that so collaboration on games is easy and it's a great way to host backups on GitHub and said website.

If this is already a feature, please let me know.

**Comment by Tyler887** [comment]
Almost stale.

**Comment by Tyler887** [comment]
Referencing in a discussion.

**Comment by Tyler887** [comment]
> ### Now discussed in #1751
> Posted by **[Tyler887](/Tyler887)**<br>December 17, 2021
-------
> Closes #1720.
> 
> I have a proposal if this isn't already a feature (other than "SURF"), the ability host your cart on your own website (e.g., https://untrustedinstaller.github.io/tic80-carts.html [not a real link on my page]) or something like that so collaboration on games is easy and it's a great way to host backups on GitHub and said websites.

**Comment by Tyler887** [comment]
Rather use `export html` instead to publish your game on a 3rd party site
