### ISSUE TITLE
Borderless/NOFRAME a non exclusive fullscreen

### ISSUE THREAD

**Issue by revdeluxe** [nesbox/TIC-80#1732]
**Why, What happened**
- So i have been tinkering TIC-80 for a while now, and i find the launch command  `tic80 --fullscreen` doesn't work
version 0.90...

**BUG?**
- when i enter this  `tic80 --fullscreen`  in bash/fish, it only renders black screen.
but the tic80 boots, and i can type exit, and that terminate/exits the app. (i also tried to wait overnight and still blank screen)
- i have been searching for fixes and non work.

**Obviously**
- implementing this would be a hassle because windowed already works fine.
- but it does make a difference. and a really - really great work around as a alternative for --fullscreen
- `--scale` is limited by the screen size so there's no way to get more higher res.

**Comment by RobLoach** [comment]
What operating system are you on? Which version of TIC-80? I'm on Ubuntu 20.04, TIC-80 1.0.1851-dev (ed8c10d), and it's working just fine.

**Comment by nesbox** [comment]
#773 dup

**Comment by revdeluxe** [comment]
> What operating system are you on? Which version of TIC-80? I'm on Ubuntu 20.04, TIC-80 1.0.1851-dev ([ed8c10d](https://github.com/nesbox/TIC-80/commit/ed8c10dcf08a64ae4d34c251a7bef7f6fa86b295)), and it's working just fine.

MINT latest, version 0.90.1723(pre-compiled bin/.deb)
