### ISSUE TITLE
Add squirrel to learn page

### ISSUE THREAD

**Issue by DannyCork** [nesbox/TIC-80#1737]
The [tic-80](http://tic80.com/learn) page does not include Squirrel.
<img width="809" alt="image" src="https://user-images.githubusercontent.com/3512672/146219752-7b8fb653-38eb-450a-a8db-893b3a40062d.png">

 It should according to  https://github.com/nesbox/TIC-80/wiki/The-Code

**Comment by nesbox** [comment]
done
thanks
