### ISSUE TITLE
Surf can fails to load a cart causing a softlock

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1738]
Doing a very specific sequence of things, `surf` can fail to load a cart resulting in a softlock after exiting the game. It seems to be random at first, but I figured to get it consistently with these steps:
- Load a cart from `surf`
- Exit to the code editor and change something in the code
- Run the game again from the code editor (without saving)
- Exit to the console and try to load a different cart from `surf`

After that, it will fail to load the new cart, resetting the cart that are already loaded, and after exiting the game it will get completely stuck on console.

**Comment by nesbox** [comment]
reproduced it, thank you

**Comment by nesbox** [comment]
Fixed here 36836e461fc7c8d58ee06e7ce48a647832157f06
Thank you.
