### ISSUE TITLE
Music Editor requests

### ISSUE THREAD

**Issue by RushJet1** [nesbox/TIC-80#174]
- copying/pasting specific sections of patterns instead of the entire pattern.  Either mouse-selecting by dragging or keyboard-selecting by holding down shift or something would be nice.

- an octave and instrument number box at the top along with track, tempo, spd, etc.  Currently if you change instrument or octave in the editor, it changes it for all new notes.  This is frustrating if editing an old section, and it's frustrating that this is the only way to change octaves (meaning you have to place incorrect notes, then fix them later every time).

- having some kind of instrument/sfx naming system would be nice to display in the actual sfx window, as right now i have to keep which sfx is which sound in a notepad window on my PC.

- ability to change note value of selected notes.  this is usually done with CTRL or SHIFT+scroll wheel on mouse in most trackers I've seen.

- add effects column, like cutting off patterns and jumping to the next one, jumping to other patterns for proper looping etc

**Comment by nesbox** [comment]
cut/copy/paste/delete selection works
![cpy](https://user-images.githubusercontent.com/1101448/31121299-52a59352-a840-11e7-9334-18dc10575273.gif)

**Comment by nesbox** [comment]
now the Music Editor restores last entered octave/sfx/volume only for new notes 00e9672
> an octave and instrument number box at the top along with track, tempo, spd, etc. Currently if you change instrument or octave in the editor, it changes it for all new notes. This is frustrating if editing an old section, and it's frustrating that this is the only way to change octaves (meaning you have to place incorrect notes, then fix them later every time).

**Comment by nesbox** [comment]
added CTRL+scroll to change selected notes 44855c6

**Comment by nesbox** [comment]
and the last one "add effects column" will be implemented here #261 
closing
