### ISSUE TITLE
Should surf and the pause menu also accept the return key?

### ISSUE THREAD

**Issue by blinry** [nesbox/TIC-80#1740]
Current behavior is that you need to press the A key to confirm a menu entry.

For me, this is counter-intuitive, and I often try to press the return key. Would it be a welcome/useful addition to also add the return key to the same mapping in those modes?

(I see that you're currently re-working some menu stuff, @nesbox, maybe this feature will already be included!)

**Comment by nesbox** [comment]
It will be fixed as part of #1613

**Comment by nesbox** [comment]
Fixed here 9322d57
