### ISSUE TITLE
Add Ctrl+L as a keybinding for clearing the console

### ISSUE THREAD

**Issue by blinry** [nesbox/TIC-80#1741]
This is another thing I tried to do intuitively, coming from a Linux background, where it's the default shortcut for "clear" in many shells.

Reading the source code, I saw that Ctrl+K is already a keybinding for that, which seems to be a MacOS thing. Would it hurt to also add a Ctrl+L keybinding? Very willing to implement that! :)

**Comment by joshgoebel** [comment]
Thought for sure I'd use Ctrl+K on Linux as well in the past... 😕

If it's truly per platform then we shouldn't just do BOTH but the right key should work on the right platform (IF it's truly so clear cut).

**Comment by nesbox** [comment]
Ok, let's do `Ctrl+L` on Linux and `Ctrl+K` on all other platforms.
