### ISSUE TITLE
Add a "cp" command to the console

### ISSUE THREAD

**Issue by blinry** [nesbox/TIC-80#1743]
When doing the [50 carts challenge](https://twitter.com/blinry/status/1467112486952443907), I often wanted to start from a simpler template file, and needed to run external commands to make copies of it.

Would a `cp <source> <target>` command be a welcome addition?

(And if we have that, it would probably also be straightforward to add a `mv <source> <target>` command.)

**Comment by blinry** [comment]
I discovered that `config default lua` comes very close to what I needed this for!

**Comment by another-m00** [comment]
Also, if you load a cart then save it as another name, it's the same as copying the cart.

**Comment by blinry** [comment]
Good point! That seems enough for now! :)
