### ISSUE TITLE
Add help entries for keys and buttons

### ISSUE THREAD

**Issue by blinry** [nesbox/TIC-80#1746]
I very often look up functions and RAM addresses in the built-in help. The only thing I need to look up externally is the list of key and button IDs.

Would a feature that adds the "keys" and "buttons" help topics be welcome, which show tables from https://github.com/nesbox/TIC-80/wiki/Key-Map and https://github.com/nesbox/TIC-80/wiki/key?

**Comment by joshgoebel** [comment]
Closing with #1754.
