### ISSUE TITLE
[Request] Ability to define cartridge directory TIC-80 standalone uses

### ISSUE THREAD

**Issue by Terumoc** [nesbox/TIC-80#175]
Hello! And nice to see the 0.27.1 update!

I would appreciate the ability to define a specific directory that the TIC standalone program uses for storing and reading carts, rather than automatically and always in the user's directory.

For example, I am interested in making a self-contained USB stick for creating and running TIC games and programs, and being able to configure it to use a subdirectory on the stick rather than a local directory would be very useful. Even if it's just a command-line option like `-cartdir x/y/z` that could be packed into a batch file/shell script would be great.

**Comment by nesbox** [comment]
ok, I'll add a command line parameter `-cartdir x/y/z`

**Comment by nesbox** [comment]
you can assign working directory by the first parameter in cmd, for example:
call `tic .` to define current directory as cart storage
call `tic ./folder/cart.tic` to define `folder` directory as storage and load `cart.tic`
and etc.

**Comment by nesbox** [comment]
done

**Comment by to90zeroblue** [comment]
Thank you!

**Comment by Terumoc** [comment]
Nice! Thanks for implementing it.

**Comment by gregoryklein** [comment]
m8, it would be cool if we could set this within tic-80. Some of us like using GitHub...

**Comment by MineRobber9000** [comment]
note to future readers: the arguments that tic80 takes (and how tic80 interprets those arguments) have changed. copying the old examples and updating them:

call `tic --fs=.` to define current directory as cart storage
call `tic --fs=./folder ./folder/cart.tic` to define folder directory as storage and load `cart.tic`
