### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by Tyler887** [nesbox/TIC-80#1750]
Dependabot is a GitHub tool that sends alerts and does other actions to decrease how prone a repo is to hacking.

This issue is a request for it to turn on.

**Comment by nesbox** [comment]
I'll take a look at this, thanks.

**Comment by Tyler887** [comment]
Notes:

- Only the owner of a repo can see a dependabot alert.

**Comment by Tyler887** [comment]
Enabling dependabot:

1. Go to Settings >> Dependencies
2. Enable anything that you think may trigger dependabot action

**Comment by RobLoach** [comment]
The majority of TIC-80 dependencies are handled through git submodules. Curious what dependabot would pick up
