### ISSUE TITLE
Extra feature similar to surf

### ISSUE THREAD

**Issue by Tyler887** [nesbox/TIC-80#1752]
### Discussed in https://github.com/nesbox/TIC-80/discussions/1751

<div type='discussions-op-text'>

<sup>Originally posted by **Tyler887** December 17, 2021</sup>
I have a proposal if this isn't already a feature (other than "SURF"), the ability host your cart on your own website (e.g., https://tyler887.github.io/tic80-carts.html [not a real link on my page]) or something like that so collaboration on games is easy and it's a great way to host backups on GitHub and said websites.</div>
Closes #1720

**Comment by RobLoach** [comment]
I'd rather not having content available on SURF that is hosted other than tic80.com. seems like a security nightmare, along with a huge possibility or 404 content.
