### ISSUE TITLE
how

### ISSUE THREAD

**Issue by Danny123B** [nesbox/TIC-80#1757]
how do i add metadata to add a cart to tic80.com????

**Comment by StinkerB06** [comment]
In the cartridge you want to upload, you need to add the `title` and `author` tags to the top of the source code. For a cart written in Lua, these tags look like this:
```lua
-- title:  the name of my game
-- author: the game's author
```
Save the cart to apply the change, before you upload to the site.

**Comment by Danny123B** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/96117651/146696914-624f42d4-a38a-41aa-bba1-618b45ae65f2.png)
like this right?

**Comment by another-m00** [comment]
Yes, like that. If you're unsure what these tags are you can find them in any new cartridge.
