### ISSUE TITLE
Music recording improvements

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#176]
I've noticed few things that irks me about the record function. Note that these are annoyances at best, but it would be nice if these would be improved.

- Recording should start as soon as you press record button.

- When pressing a key for a longer period of time, it starts to record multiple same notes on each row. Instead, it should record only first instance and rest replace with empty rows (--------). This will make subsequent adjustments easier to do.

- I've noticed that in note row you don't use qwerty/numbers rows which in other trackers are usually used for inputting notes that are octave higher than ones inputted with zxcv/asdf rows which is very convenient. Any particular reason?

- Finally, when while recording you pres a note button and you let it go, previous note starts to play again, e.g. if you have this for example: c-4/---/--- and then you press b-4 on the next row once you let it go, c-4 will play again which wouldn't take place during normal course of the song (and will be working properly once the pattern loops over, but then any new notes will have similar issue).

**Comment by RushJet1** [comment]
I'm not the author of the program but these responses are just based on my using the program for a day now.

1) you have to choose a pattern button at the top of the channel you're recording into first.  I will admit that this was confusing the first time I used the program too.

2) this behavior (adding the same note over and over) mirrors most trackers I've used.  if they don't repeat the note, they just add one line and stop.

3) I just wrote a couple tracks yesterday and q2w3er5t6y7u works for the 2nd octave.  not sure why you're having that problem.

4) I have not noticed this problem.  recording down one note doesn't play the previous one in my window.

Are you using the [web version](http://tic.computer/create) of this or a downloaded one? Sounds like it could be out of date.

**Comment by darkhog** [comment]
I'm using downloaded 0.27.1 (newest one) and since recording arrived in .27...

Also just checked and now qwerty row works. Not sure why it didn't work yesterday when I was trying it.

As for 4, I think video would be in order as my explanation was kinda wonky. Will update it when I record one.

**Comment by darkhog** [comment]
Okay: Here's the video presenting problem 4: https://youtu.be/QiCe3mcsm5k First I input C-4 normally then i start recording. Notice that after letting go of A-4 C-4 starts playing again even though it shouldn't at this point in the song. During recording I do no other input that pressing N to input A-4.

**Comment by RushJet1** [comment]
Oh I see what you mean, while the pattern is playing it goes back to the previous note. I hadn't tried entering notes while the pattern is playing because generally the timing isn't precise enough.  But in most trackers it doesn't have this behavior so yeah that's probably a bug.

**Comment by farvardin** [comment]
I have the octave error too, sometimes q2w3er5t6y7u works for the second octave, other times it doesn't (for unknown reason). 

As far is I know, when I start a new cartridge, it's always working, but after a while there is a problem, and the cartridge no longer accept the octave. In such situation, if I quit tic-80 then start it again, and reload the cartridge, the problem still occurs.

**Comment by nesbox** [comment]
Close as outdated
