### ISSUE TITLE
SFX issues on Linux

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1764]
Might be difficult to track this one down but...

I've noticed a couple of issues with sound effects on MX Linux (with version 0.90.1723) **but only when TIC has been running for some time**:

- There's a noticeable delay before any sound effect starts when a key is pressed in the piano roll keyboard or started via a call to sfx()
- Occasionally (during program execution) a sound will play and repeat continuously even when all sfx() calls are commented out (there are no peeks or pokes within the program that might be the cause).

I can't provide a way to reproduce the issue other than using TIC for several hours. Both issues can be 'fixed' by restarting TIC. My guess would be a memory leak or something being written where it shouldn't.

**Comment by nesbox** [comment]
Seems it's already fixed on the dev build, pls check it here https://nightly.link/nesbox/TIC-80/workflows/build/master

**Comment by paul59** [comment]
> Seems it's already fixed on the dev build, pls check it here https://nightly.link/nesbox/TIC-80/workflows/build/master

That doesn't want to run so I can't test it I'm afraid...

'/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./tic80)'

It seems 2.28-10 is the latest in the repo for MX Linux 19.4

**Comment by nesbox** [comment]
Pls try again, I changed the Linux version to 18.04
Thanks

**Comment by paul59** [comment]
Thanks will give it a try - might take some time to report back as the issue only seemed to occur after a few hours of having TIC open.

**Comment by paul59** [comment]
> Pls try again, I changed the Linux version to 18.04 Thanks

That runs but it uses a software cursor which makes all the editors very laggy - 0.90 uses the system cursor.  Is there a way to specify OS cursor in config?

**Comment by nesbox** [comment]
What do you mean when you say "very laggy"?

> Is there a way to specify OS cursor in config?
Not yet

**Comment by paul59** [comment]
> What do you mean when you say "very laggy"?
Sorry, the cursor movement is slow and isn't smooth/responsive, possibly because it changes from a pointer to a hand so often as it moves across the window? 

I can see the benefit in highlighting what it's pointing to in the sfx editor where selectable areas are small but is there any value in changing it to a hand/finger cursor when you're already highlighting icons (for example cut/paste/outline etc)?

I've also just noticed that it doesn't change to a hand cursor (or work for selection) in the exit menu (unsaved changes) when hovering over 'No' or 'Yes'. Additionally, that menu exhibits some slightly odd behaviour (scrolling) when pressing up or down repeatedly.

**Comment by nesbox** [comment]
The cursor movement is not smooth because it works in terms of TIC screen coordinates. As for the game menu, it is currently under development and mouse handling will be added shortly.
So, what about the SFX issue, is it gone in the dev build? :)

**Comment by paul59** [comment]
> The cursor movement is not smooth because it works in terms of TIC screen coordinates. As for the game menu, it is currently under development and mouse handling will be added shortly. So, what about the SFX issue, is it gone in the dev build? :)

I see, an option to use the system mouse cursor would be welcome though. Regarding the sfx issue I don't know yet, I haven't had a single instance running long enough to find out... should be able to report back over the next few days.

**Comment by paul59** [comment]
Did some SFX editing, played a track for over two hours (!), did some more editing. No sign of the earlier 'delayed note' problem. I'll leave this issue open for a few days just in case it happens again.

**Comment by nesbox** [comment]
ok, thank you

**Comment by paul59** [comment]
No recurrence of this issue so I assume it's fixed.
