### ISSUE TITLE
Website needs a report button

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1765]
I feel that the website is lacking of moderation, and I think if it have a report button it could help to prevent things like this from flooding the site:
![image](https://user-images.githubusercontent.com/88540876/147427688-50574073-76b8-4794-aba0-c77bfe165c13.png)
![image](https://user-images.githubusercontent.com/88540876/147427765-8ecc742e-bbb0-4254-bf5a-40655a6acd14.png)
![image](https://user-images.githubusercontent.com/88540876/147427904-1739823b-5c26-472f-9353-ad7c7af5c176.png)
![image](https://user-images.githubusercontent.com/88540876/147427942-5c5ede46-c929-43f5-8c5d-a072e89f34cd.png)

**Comment by nesbox** [comment]
dup #1133
