### ISSUE TITLE
Tic80 website.

### ISSUE THREAD

**Issue by EliasWolf-Br** [nesbox/TIC-80#1766]
Hi, I didn't mean to be rude but...

I would like to see some changes on the tic80 website!

for example:
font - the "pixelated" font in the app is cool, but on the website it's kind of uncomfortable.

manage - it is impossible to delete games and comments,
it is also impossible to edit comments.

interface - the site's interface is not that good... that's all ;-;

NOTE: It's just my opinion, if I offend someone I'll delete this post!
NOTE 2: Unfortunately I can't help, I'm still starting with programming.

**Comment by nesbox** [comment]
Possibly that something will change after the source of the website is opened #1659

**Comment by EliasWolf-Br** [comment]
Seriously?
Thank you very much!
I'm here waiting for the best ;-)
