### ISSUE TITLE
The music editor is not very discoverable

### ISSUE THREAD

**Issue by blinry** [nesbox/TIC-80#1767]
I feel like this is one of the few features that is not discoverable: when switching to the music editor for the first time, I was confused that I could not place notes there (because you have to create a pattern first).

Similar to how there's some sprites in the example cart already, giving you something to play with, I think the music editor should have pattern 1 in channel 1 of frame 0 of track 0 enabled by default, so that people can start building a melody.

**Comment by paul59** [comment]
I agree, good idea.

**Comment by nesbox** [comment]
Fixed here 870ef7262c17862db19319e3d541196b372f08f7
Thank you.
