### ISSUE TITLE
Do we want to "own" the per-language WASM bindings/libs?

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1771]
I've created the first, for Zig: https://github.com/joshgoebel/zig_bunnymark/blob/main/src/tic80.zig

Related: #1259 

I imagine people will over time show up to write bindings for all the possible languages - look at the WASM-4 project for a list of what's already possible to compile to WASM pretty simply:

- C/C++
- D
- C# (in progress)
- Nelua
- Go
- Nim
- Odin
- Rust
- Wat
- Zig

WASM-4 "owns" the bindings (and build scripts) for each of these in it's own repo: https://github.com/aduros/wasm4/tree/main/cli/assets/templates

Although because of this they also kind of keep the API to "least common denominator" and the functions are all very C like - even when the languages might allow for much nicer APIs... Personally I'd hope we could be a little more flexible in that regard, but it does have concerns like documentation, etc... ie, the "original" API looks one way while the Zig or Odin API has "more niceness".  Perhaps we could support both "raw" and nicer... Mostly I'm imagining useful "aliases" (such as `noclip()`, if we don't decide to add it more broadly) and named arguments:

```zig
// behind the scenes calls clip(-1,-1,-1,-1)
tic.noclip() 
// named arguments via a struct
tic.print("hello world", x, y, .{ scale: 3, fixed: false, smallfont: true, color: 4 })
```

**Comment by nesbox** [comment]
yes, we want it :)

**Comment by joshgoebel** [comment]
Where in the source tree should we place such things?

- examples?
- projects
- templates?
- examples/templates?

**Comment by nesbox** [comment]
I'd select something like `src/api/wasm/[c d go nim odin ...]`, but anyway it's your choice.

**Comment by joshgoebel** [comment]
Closing this as asked and answered and continuing with #1784.
