### ISSUE TITLE
Key error for Retropie build

### ISSUE THREAD

**Issue by wheelbarrow-of-mellons** [nesbox/TIC-80#1774]
When I attempted to  follow the instructions for installing tic-80 on retropie the commands for the key server all gave back error messages.  Does anyone else know how to fix this.  
![C91FBFE3-44AF-485C-BD0B-343C17E9C30B](https://user-images.githubusercontent.com/94632850/147862177-efc12ac3-5922-4d9c-87ec-b922001e9ae3.jpeg)

**Comment by paul59** [comment]
You might get more joy on the [RetroPie](https://retropie.org.uk/forum/) forum as it seems to be a repo issue rather than anything to do with TIC-80 specifically (or maybe I'm missing something?). Good luck!

**Comment by nesbox** [comment]
Yes, it's not related to TIC80.
Closing...
