### ISSUE TITLE
WASM demo cartridge

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1776]
Something slightly different needs to be done here... My first pass at just the "above the fold"...

![Screen Shot 2022-01-02 at 1 50 32 PM](https://user-images.githubusercontent.com/6473/147886261-6ac6716e-dafc-4800-a69b-17c0da175d7b.png)

I think for WASM we need to tell the user what they've gotten themselves into and then they could go to the Wiki or look at the sample starter projects in various languages to learn more.   I went with the `--` comments from Lua for their hopeful familiarity since Lua is our original language.

This "in cart help" could be as short or long as we wanted but it may be best to keep it brief and then direct them elsewhere, to somewhere like the wiki where the content is easier to maintain.

Thoughts?

**Comment by joshgoebel** [comment]
Also I think it's important to direct them to where they can see the source... do we need the full GitHub URL, or would they perhaps have these files installed locally somewhere?

**Comment by joshgoebel** [comment]
The `script` tag is also no longer accurate as WASM is not a script language, but I'm not sure what we could do about that...

**Comment by nesbox** [comment]
Let's leave it as is, maybe we'll find a better solution later.

**Comment by joshgoebel** [comment]
Are you ok with the WASM demo's code section being a small writeup like this that directs people to the Wiki for more information about using WASM cartridges?

**Comment by nesbox** [comment]
I am ok with all these things, please don't hesitate and do as you see fit :)

**Comment by joshgoebel** [comment]
This is now compose of two files:

- demos/wasm/`wasmdemo.wasmp` (textual project)
- demos/wasm/`wasmdemo.wasm` (wasm binary)

The `prj2cart` combines them during build time.  Having a textual version should make correcting typos and small fixes easier.

**Comment by joshgoebel** [comment]
Closing via https://github.com/nesbox/TIC-80/pull/1772. (which was manually merged)
