### ISSUE TITLE
Making TIC RAM a pointer so that runtimes can provide their own RAM

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1777]
I'm frustrated to have gotten so far and then realized the memory is more of an issue than I thought... WASM3 (by default) wants to "own" it's own memory... so the simplest thing would be to let it do that and then hand that to TIC-80 and say "hey, here is the memory to use for the machine"... if a runtimes doesn't need that,  you could provide the default allocation yourself (as is done now).  This has the side benefit of allowing some runtimes to have more RAM than others, depending on their needs.

I actually though maybe I could handle this myself inside `wasm.c` since all the API functions take `tic_mem*`, but it's a bit misleading... several of them cast it back to `tic_core` to get access to `state` and other internal pieces of TIC... not to mention the other internal pieces which would still be looking at the "original" RAM.

So then the question is could we perhaps just replace the WASM3 ram with TIC-80s RAM.  This looks more doable since it appears to purposely be a pointer... but we require a minimum of 128kb for WASM3 (WASM spec works in 64kb chunks)... so would you just want to change the entire TIC-80 to 128kb?  Then what if we decide for "fairness" with interpreted languages that WASM needs 256kb?  Then see the ongoing discussion in #1259 where some think the memory limit should be MUCH higher - to match the same "memory limit" of the other runtimes, which is effectively uncapped.  I'm not sure we'd want to share that same extra allocation with the runtimes though - which have their own RAM already - although I'm also not sure it would hurt - although it does increase the overall memory demand if we just have a lot of allocated but unused RAM just laying around.

So that's lead up to:

_Would it be possible if anywhere we referenced `tic_ram` it was via a pointer?_  This would allow the WASM runtime to replace the internal RAM with it's own at `init` and then swap it back at `close`...

And a related question:

_Also, why does pausing copy the RAM and state into a whole other data structure?_  Is something bad going to happen to the original copy during the pause?

**Comment by msx80** [comment]
wait, the author of WASM3 offered to implement some sort of abstract memory [here](https://github.com/nesbox/TIC-80/issues/1259#issuecomment-1002229776), perhaps we should take his offer? I think at the very basic we could be providing our pointer to wasm3

**Comment by nesbox** [comment]
> Would it be possible if anywhere we referenced tic_ram it was via a pointer? This would allow the WASM runtime to replace the internal RAM with it's own at init and then swap it back at close...

It's possible, but the idea to involve the wasm3 author is preferable and will look more elegant :)

> Also, why does pausing copy the RAM and state into a whole other data structure? Is something bad going to happen to the original copy during the pause?

Because we use RAM to draw the editors UI, play sounds, and so on, and have to restore the game state on the resume command.

**Comment by joshgoebel** [comment]
> Because we use RAM to draw the editors UI, play sounds, and so on

Oh right, gotcha...

> perhaps we should take his offer? 

Oh, I didn't realize who that was. :-) Sorry.

>  we could be providing our pointer to wasm3

Yes, I think this would work (currently) if the memory is a multiple of 64kb.

Our problem right now seems to be that our system isn't easily structured such that we can hand you a pointer to our own RAM (because the amount of RAM we want WASM3 to have might be a lot higher than the default amount our scripting runtimes use - since they don't use RAM the same way) - and currently our own allocation is static... and all our internal APIs pass state structures around that are expected to include a lot more than RAM... so it seems difficult to easily take the pointer to RAM you currently provide and just "drop it in" somewhere...

What type of abstraction did you have in mind? 

CC @vshymanskyy Thoughts?

**Comment by joshgoebel** [comment]
I've been chatting with WASM3 author.  Technically it seems we could "hand" WASM3 our RAM... if we wrap the `tic_core` struct in it's own struct... the way memory is done in WASM3 is that it's accessed thru a header.. and the header must set at the top of the memory allocation... So it looks like:

```
[overall allocation]
  [memory header]
  [free RAM]
[/end allocation]
```

And the WASM3 internals store a pointer to the HEADER, not the actual RAM... so getting memory is a (HEADER+1) define... so for us that would mean hacking our startup and shutdown to produce a wrapper:

```
[wrapper]
   [WASM3 memory header]
   [tic_core]
```

And when running WASM3 we would simply alter the `runtime-memory->mallocated`  pointer to point to our header...

But ugh, I don't really love the idea.  Seems very hackish.

**Comment by joshgoebel** [comment]
One option is maintaining a fork of wasm3 and modifying the memory access opcodes: https://github.com/wasm3/wasm3/blob/4436c7c525ffb76d48a00e44771d5cf4aa12b9b1/source/m3_exec.h

You could have it such that memory was laid our as follows:

```
[96kb TIC-80 RAM]
[256kb WASM3 RAM] 
```

In a single 352kb address space...  This is a bit beyond me and I think a worse solution, plus having to maintain the fork... it seems simplest if we refactored to where TIC's RAM is accessed behind a pointer (NOT a fixed size allocation of `tic_core` struct)... which would be trivial to swap out to point to somewhere else (such as WASM3, etc)... and this comes right back to #1179 about cleaning up the difference between tic_ram and tic_core and stopping pretending they are one and the same.

I'm thinking perhaps the `userdata` we attach to the various runtimes should be a pointer to a struct, not `tic_ram`... ie:

```
struct {
  core: tic_core*
  ram: tic_ram*
}
```

I think this could also simplify the pause situation... Why bother copying in and out all the time?  Why not just hav a different let the editors have their own `{core, UI_ram}` struct that points to their own RAM all the time to begin with... then the only shared state becomes the magic "core" object...

It might be a bit more effort on our end, but it's much easier to understand what's happening and doesn't have any edge cases (like `memcpy` that crosses the magic TIC/WASM boundary)

**Comment by joshgoebel** [comment]
There are likely security considerations here as well regarding potential overflows, off by one, etc errors... placing critical system state immediately after memory we're allowed to write to willy-nilly via pointers... seems like it wouldn't hurt if those things were separated a bit further.

**Comment by joshgoebel** [comment]
@nesbox IE, like this:

https://github.com/joshgoebel/TIC-80/commit/8e0749a7b69678358f2490c6368e2d2e0e934ee1

I did this with two regex and one manual change... seems to work fine.  If you're ok with something like that overall the next step is to see how it can actually integrate into WASM3.  I assume in WASM3 init we'd just:

- ask WASM3 to allocate it's own RAM
- update `core.memory.ram` to point to that RAM
- call `tic_api_reset` to clean up the RAM to a good boot state

You could either free/alloc the TIC-80 RAM every time we need it or we could keep it around and track which state we're in... such that when WASM3 was closed it would free it's memory, set the pointer to NULL and then we'd provide a callback to TIC-80 could just restore it's own base RAM again (Actually this works regardless of whether we keep it around or release/reaquire it).

When pausing this ram would be "swapped" in and out just like any other ram... I don't see why the pause routine cares one bit... pause would only swap the first 96kb, but that's fine for our usages since I presume the TIC-80 internals aren't expecting to have more than 96kb anyways.

**Comment by joshgoebel** [comment]
Tagging this fantasy CPU since it also seems you could memory map the TIC I/O space anywhere you wanted into into a fantasy address space just by setting `ram` to an offset of your actual memory pool.  Say we wanted the stack in the bottom 16kb of RAM (for reasons) then we'd set:

```
memory.ram = ACTUAL_RAM_PTR + 16*1024;
```

Now the VRAM would start at `0x10000`, etc... and everything would "just work" with the exception of things that take REAL addresses like `peek`, `poke`, `memset`, and `memcpy`... those could perhaps be made aware of the offset (via some sort of  `memoffset`)... perhaps there is an easier way to do this... I only mention this because it suddenly popped into my head and might be relevant in the future.

**Comment by joshgoebel** [comment]
![Screen Shot 2022-01-03 at 5 37 50 PM](https://user-images.githubusercontent.com/6473/147987938-e90d8a1a-6ab3-457a-9f0c-fce35f8e4778.png)

And it all works, except for memory offset 0, which I'm worried might be some issue with WASM and pointers...

**Comment by joshgoebel** [comment]
And allowing WASM to provide it's own runtime RAM (for all of TIC-80) was only about a 20 line patch after I made RAM a pointer instead of a hard-coded part of the struct... :-)

https://github.com/joshgoebel/TIC-80/commit/219d4d89fb1e286254b3e81e45774e884bd6c9ee

**Comment by nesbox** [comment]
Or we could do a PR for WASM3 to initialize the VM with our RAM without these hacks :-P

**Comment by joshgoebel** [comment]
Which hacks?  I think my solution above is pretty clean - and it's 100% working. :)

**Comment by joshgoebel** [comment]
> to initialize the VM with our RAM without these hacks :-P

Our RAM still needs to be resizable, did you miss that?  WASM needs at LEAST 128kb (must be even multiples of 64kb), and for parity with the other runtimes it may need even more... so it makes sense to allocate that extra RAM only when using WASM, and the test of the time use the 96kb allocation.  We can't do that if RAM is trapped inside a fixed size struct.

**Comment by nesbox** [comment]
> We can't do that if RAM is trapped inside a fixed size struct.

I think we can resize the RAM for WASM, something like
```c
struct tic_mem
{
    tic_ram             ram;
    u8                  wasm[128*1024];
    tic_cartridge       cart;

...
```

And you don't need to copy the RAM data on `init/pause/resume` in this case.

**Comment by joshgoebel** [comment]
And how would all the internals know whether to use `ram` or `wasm` at any given moment?  That's why I added the pointer... do you have any argument why a pointer to memory is BAD?  I feel like I've already solved this problem... we use malloc all over (as do the runtimes) so I'm not sure why this fascinating with statically allocating the RAM.

**Comment by joshgoebel** [comment]
None of the other runtimes statically allocate their RAM, I'm not sure why WASM should either... if Lua seeds 1mb while it runs, then when you stop it and switch VMs (to say a JS cartridge), that memory is released.  If WASM needs 1mb while it runs, why do you want that 1mb wasted all the time, _even if the user never plays a WASM cartridge_?

**Comment by joshgoebel** [comment]
Also WASM (like the other runtimes) allows dynamic memory allocation.  It's possible that one cartridge might needs 128kb and another needs 256kb... that's something we could easily support (with my approach) - like we support with every other runtime.  _But not if the allocation is static._

**Comment by nesbox** [comment]
I don't want to argue with you, because I didn't dive deeply into this topic :)

**Comment by joshgoebel** [comment]
@nesbox I can possibly take yet another look at this if you *insist*, but I'd appreciate it if you could perhaps first review the work I've already done (with an open mind) and comment on the reasons I provided.  I don't feel like I've heard anything from you other than "i don't like it, do it this other way" (paraphrase).  And while that is certainly your prerogative as the project owner, I'd feel a lot better if I got a little more actual feedback or if I understood your concerns.  Possibly there is a 3rd path here to be found if I understood the actual concerns.

The `ram.` to `ram-> `patch touches a lot of files true, but it's also a *trivial* patch that is mostly a search and replace of the codebase (and guaranteed by the compiler).  It worked immediately.  You did kind of say "told ya so" to my keyboard issue, but that was a real security issue regarding keeping key system state in untrusted TIC-80 "device" RAM - not really something I think I should have predicted.  Now that we copy the RAM on both the way in *and* out (closing the loop fully) I really can't imagine similar issues.  To both cartridges and even TIC-80 it's just memory.  It should work flawlessly.

I think other than the search and replace, the actual change here is a tiny (and easy to follow) 8-10 line patch. Just `memcpy` on the way in and out.  I could perhaps split the commit into two if that would make it easier for you to review. Oh, I actually already did that:

- https://github.com/joshgoebel/TIC-80/commit/f9e06e8ed0bbb9d06c1e1a3efa14d458314177f8 RAM pointer
- https://github.com/joshgoebel/TIC-80/commit/8a77ec475ddc1417d93554b79eee297a3f4f9e9c WASM3 integration

It looks a bit longer in the diff because i also moved the `deinit` function... sorry.

The reasons I provided:

- I know the TIC-80 codebase much better than WASM3, so I'm much more confident of a correct solution here. (fewer unknown unknowns)
- This requires adding no special WASM3 headers to our data structures.  Presently we'd have to add a `M3MemoryHeader` at the very least AFAIK - because WASM3 has no way to inject a "raw" pointer. (where-as it was trivial to allow us to have a raw pointer to RAM)
- This allows for dynamic runtime resizing (like **all** our other runtimes - none of them are statically allocated) - which is a reasonable thing to have in our pocket for the future.
- This is more flexible, and allows for other runtimes in the future that have different memory requirements.

Thoughts?

**Comment by joshgoebel** [comment]
There are also more questions the other route would need answers to.  If we go with a static allocation of say 192 or 256kb...:

- Do we add special code to keep Lua/Wren/JS out of that extra RAM?
- Or does every scripting runtime get access to all that RAM?
- If not, what is the justification?  
- Forcing user code to use SLOW runtime memory (if they wanted to memcpy the screen, say) vs using the super fast low-level `memcpy` built into the "OS".. why?  Let's say it's 16kb either way... why force them to use the slow memory with `for` loop inside the interpreter vs using the fast `memcpy`? "we don't want to allocate" is a good argument, but if you have a static allocation just sitting there doing nothing... why not allow its use?

And that's just off the top of my head...  I'm trying a bit to avoid yet more questions so that I can get this PR finished since it's already a large enough chunk of work. :-)

**Comment by nesbox** [comment]
I didn’t say “I don’t like this”, I just want a more elegant solution that allows WASM3 to work with real RAM and not a copy of RAM, because this can generate a lot of errors, for example, `keyp()` stopped working ... Anyway, I really appreciate all your work and your desire to make TIC better, and of course, we will merge your changes, but after that, I am going to open an issue to fix it in the future, possibly after the PR for WASM3. ...
I hope you understand me and do not take offense.
Thank you.

**Comment by joshgoebel** [comment]
> for example, keyp() stopped working

That bug was with the design I think - storing "system" state in untrusted user RAM.  I do agree big changes (like the RAM pointer) can both _create and reveal_ bugs, I guess I'm just objecting to the use of the word "error".   Something like the difference between "finding problems" and "creating them" I think. 😇  I'd like to think I found a problem there, not created one. 😁

> after that, I am going to open an issue to fix it in the future, possibly after the PR for WASM3. ...

Awesome, though I think you may find it doesn't need any fixing. :-)  But if you find a more elegant way to do it, that's cool.  

---

> I hope you understand me and do not take offense.

I'm almost impossible to offend, no worries. :-)  Just excited about finishing up this WASM stuff and seeing if it generates any more interest in TIC-80.  Thanks for all your hard work on TIC-80!

**Comment by joshgoebel** [comment]
Closing via https://github.com/nesbox/TIC-80/pull/1772. (which was manually merged)
