### ISSUE TITLE
Low-level API concerns (WASM, etc)

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1778]
Much of the TIC-80 API is potentially problematic because of default values/variable args.  (ie our scripting languages allow passing a variable number of arguments, and in WASM that is not easily possible)

In other places the API is problematic because using `-1` as a "default placeholder" would mix types, such as when the value is supposed to be a boolean. Ie, in Zig for example there is no way a function can return an integer in one place and a boolean in another... it's one or the other, those are not compatible types.

- btn() - the default form that returns a numeric, the `btn(x)` variant returns a boolean
- font (take booleans)
- print (take booleans)

Or you have cases when the input CAN be negative but the value is also optional:

- map - the `sx` and `sy` arguments, etc

Many others take only positive numeric arguments and I think using `-1` could work there such as:

- cls
- clip
- etc
- sfx
- pix
- etc

---

_Originally posted by @msx80 in https://github.com/nesbox/TIC-80/issues/1259#issuecomment-1004032808_ :

> I feel like the "simple just works" TIC approach boiled down to WASM might would be -1 for "i dunno" or "just do the right thing"... ie, no one would need to know the defaults to call the API - that would be all handled INSIDE TIC, not WASM. So to call sync(), effectively sync(0,0,false) you would need to know that -1 was "default" and the number of arguments (to push the right number of args onto the stack).

So the problem with how to map the API to simpler languages (like C or wasm) is tougth. Maybe we could do a separated issue for this?

Anyway, i think there are two ways: one where the defaults are implemented in the language and one were they're implemented in TIC. I also think the second one offer more value (you avoid repeating all the defaults values), but it's a bit harder to implements. It would require changes to the tic80 layer (which is not much trouble).

The most delicate thing would be to choose a value to communicate "default" to tic80. You propose -1 which works for most cases but what if -1 is also a valid option for the parameter? I think tic80 accepts negative values for coordinates in api. In "map" you can pass negatives to sx and sy, -1 would be ambiguous as the default is 0.

PS we already have some kind of "c api" in [api.h](https://github.com/nesbox/TIC-80/blob/master/src/api.h). I think it's sensible to use it (or at least take it into consideration)

**Comment by joshgoebel** [comment]
And my original post from the other thread:

---

**All code below is pseudo-code, not actual WASM instructions since I don't know all the instructions off the top of my head.**

Are their any thoughts on the LOW-LEVEL Wasm API?  WASM functions have a fixed # of parameters and a single output value (I'm sure WASM-3 [our interpretter] supports multi-output values yet)... so that means that a lot of function signatures will look similar to a low-level C AP using -1 "nulls":

```js
// psuedo-code!!
pix(0,0,5) // write pixel, returns 5
pix(0,0,-1) // read pixel
```

So our `pix` would just be a function with 3 arguments that _always_ returns the color...  someone is free to ignore it.  And if you want to read the pixel you pass `-1` for the color to be written.  Of course in the higher-level language wrapper libraries there may be much nicer ways to deal with this.  In `C++` for example you'd likely just make the `-1` a default argument for the last parameter and then the 2 or 3 argument version of `pix` works "magically".

This however gets uglier for some fo the functions with a zillion params:

```
map [x=0 y=0] [w=30 h=17] [sx=0 sy=0] [colorkey=-1] [scale=1] [remap=nil]
```

Do we want to just do the lowest-level thing possible in WASM and require all these params, all the time?  IE to just call `map()` one would need (low-level) the following WASM instructions:

```js
// psuedocode
i32.push 0
i32.push 0
i32.push 30
i32.push 17
i32.push 0
i32.push 0
i32.push -1
i32.push 1
i32.push -1
call $map
```

I think this may be OK - and let the higher-level libraries sort out doing it nicer *if possible*... 

It does get a bit ridiculous for some functions though like `clip`... we either require the programmer to keep track of the details, or we build it into the TIC_80 API layer... so either:

```
i32.push 0
i32.push 0
i32.push MAX_WIDTH
i32.push MAX_HEIGHT
call $clip
```

OR:

```
i32.push -1
i32.push -1
i32.push -1
i32.push -1
call $clip
```

I actually started out with `clip(x,y,w,h)` and `noclip()`... would we be open to possibly expanding the API in a few areas (for all languages) for some of the more ridiculous examples... or would it be ok if WASM was just a "special case" and supported a slightly extended API to make some for the edge cases nicer?

**Comment by joshgoebel** [comment]
>  In "map" you can pass negatives to sx and sy, -1 would be ambiguous as the default is 0.

Ugh, I missed that case, very good point.  It's also possible to pass a stack of values thru as an argument... that's how the C ABI interface handles varargs, etc... though it's uglier to code... In that case you'd have access to `null/0` (technically a valid pointer, but not one that would ever reference a variable)... and you'd also pass an argument count... but now we're making the ABI very, very different than everywhere else...  Let me do a review and post the list of functions that are problematic.

**Comment by joshgoebel** [comment]
`btn` is still problematic though because of the return types, so I'd already considered two functions:

```
btn(id) => bool
anyBtn() => integer
```

I'm not sure a lot of people are even aware of the second form.

**Comment by joshgoebel** [comment]
@msx80 Is this an uglier API for C though, can you write simple structs inline in C if the types are known in advance?

**Comment by msx80** [comment]
Uhm i'm not sure, i'm not an expert on C by any means. But i don't like moving to structs everywhere much. I think it would be nicer to resolve ambiguities by having multiple functions for a single api, when defaults are not enought. Either that, or bite the bullet and implement defaults on the language side, which would let us use the actual C api as defined in api.h. Perhaps it's the lesser of two evils. It's not like defaults are going to change, i think.

**Comment by joshgoebel** [comment]
So I guess overall thoughts, trying to focus on "necessary changes":

```
btn => `btn => bool` and `anyBtn => int` though this could just be a wrapper around `btn(-1) => int`
btnp => struct
clip => `clip` and `noclip` (via clip -1 -1 -1 -1)
cls =>  not sure
font => struct
map => struct
music => struct
pix => `pix` and `getpix`
pmem => split into two functions
print => struct
sfx => struct
spr => struct
sync => struct
```

Though in all cases where I say "two functions" this might just be API niceness built on top of a simpler TIC-80 API... ie, the functions only exist in our language API, not TIC itself.

**Comment by joshgoebel** [comment]
> having multiple functions for a single api,

This works in _simple_ cases where I listed above, like `btn`, `clip`, `pmem`, perhaps `cls` but not complex cases where there are literally like 1000s of ways to draw a sprite but in each case we're drawing a sprite.

>  would let us use the actual C api as defined in api.h

That API doesn't define how to deal with optional params ... which is the whole discussion here...  So for your example of map... HOW do we call the `map` API and tell it we aren't passing `sx`?  We can't pass `-1` as you've already said.  The C API assumes this is already being handled upstream by the per language APIs.

**Comment by joshgoebel** [comment]
This still leaves a small problem for Zig (and perhaps others) that are very strongly typed.

Given the APIi: `print text [x=0 y=0] [color=15] [fixed=false] [scale=1] [smallfont=false] -> text width`

If you just do the dumb, -1 default, your low level API might look like this:

```
print("hello world", 20,20, 15, true, -1, -1)
// but then I can't write 
print("hello world", 20,20, -1, -1, -1, -1)
```

Because -1 and bool are not compatible types. So I'm forced to write things like:

```
print("hello world", 20,20, 15, -1, -1, -1)
print("hello world", 20,20, 15, 0, -1, -1) // false
print("hello world", 20,20, 15, 1, -1, -1) // true
```

Which is ugly and harder to read IMHO.  This is not an issue for C I know as it's far more lax in this regard, but something I have at the back of my mind.  And there is no nice way to wrap this (short of a struct with defaults) that I know of...

**Comment by msx80** [comment]
What i meant was: if we implement defaults on the "wasm" side, then we can simply call the regular API with ALL parameters explicitly set, which btw is what other scripts do too [see lua for example](https://github.com/nesbox/TIC-80/blob/e1fe8827ed92631c89e5497561c058356fe2b41b/src/api/lua.c#L711), but inside TIC80. Then we don't have the problem of defaults at all. After that, each wasm-based language can provide their own high-level API with defaults, varargs or what shortcut that specific language offers. People can then write games against that high-level api.

Sure we have to implement defaults on the "external side" but it's probably better then the alternative, as i said defaults are not gonna change often, if at all.

**Comment by joshgoebel** [comment]
I think I'm not following exactly what you're proposing.  There must always be a thing C -> WASM and WASM -> C wrapper... this is much like every other scripting language... those functions have some brains, they aren't just calls into the native TIC APIs... so if we were to pass `-1` from "inside" wasm this is the layer that would handle turning that into defaults, as is already done in several places, see:

https://github.com/joshgoebel/TIC-80/blob/wasm_support/src/api/wasm.c#L332

This is no different than how all the other scripting wrappers work... the TIC-80 internal APIs expects fully "cooked" parameters... actually this isn't 100% true since some allow passing `-1`... but in a lot of those cases that isn't to say "use default" it's to say "param not passed"... so I'd argue still cooked.

For example here is the Wren API setting all the defaults (in the Wren wrapper): https://github.com/joshgoebel/TIC-80/blob/wasm_support/src/api/wren.c#L637-L645

---

So there are 3 places here:

- internal C TIC API (which takes full cooked params)
- internal per-languages wrappers (which provide defaults and cook the params)
- external library code (which is often dumb, but smarter in some cases, see Wren, etc)

I'm not sure which you're referring to as "wasm side" and "external side"

**Comment by joshgoebel** [comment]
Oh, the assumption here is that we aren't touching the internal C API.  So really most all my discussion resolves around the per language and wrapper and library code.

```
print("hello world", -1, -1, -1, -1, -1, -1)
```

I think I'm "ok" with a low-level WASM API like this, IF we can resolve the `map` issue (and any other edge cases)... but I wouldn't want to write actual game code like this - I'd want the language wrappers we SHIP to have nicer abstractions.

**Comment by joshgoebel** [comment]
OH, there may be performance implications of passing 10 unused params around, but I'm not sure I know enough to get into that so I'm not sure how much that can educate our discussion here.  Vs a struct, which would be passed by reference, not value...

**Comment by desttinghim** [comment]
I think we should have the WASM API be a pretty direct mapping that requires all values to be passed in, and then provide a idiomatic wrapper for each language supported like WASM4 does. It does make documentation harder, but I think that's an acceptable cost. We can provide a page for each language that documents any deviations from TIC-80's normal API. 

In the case of Zig, we can provide functions that accept a struct that look like this `sprOpt(.{.id=0,.x=0,.y=0,.scale=2})`, and have variations such as `spr(id,x,y)` and `sprColor(id,x,y,colorkey)` for common cases. This makes simple calls less verbose without having to make a separate version for each argument count. If we follow the WASM4 route it also gives end users the ability to easily add new variations for their use cases.

**Comment by joshgoebel** [comment]
> I think we should have the WASM API be a pretty direct mapping that requires all values to be passed in, and then provide a idiomatic wrapper for each language supported like WASM4 does.

I'm coming around to this but `map` seems problematic in that `-1` can't be used as a placeholder for "default"... -1 is ambiguous for both `sx` and `sy` arguments... did you have any idea there?

If the first 3 are **required** why would `sprOpt` not be:

```
sprOpt(id,x,y, .{.scale=2})
```

**Comment by desttinghim** [comment]
Re `sprOpt`: that seems like a good idea. Maybe just `spr(id, x, y, .{})` then.

For map, it looks like the default for sx and sy is 0. What's wrong with just passing that? It seems unlikely to me that that will ever change.

**Comment by joshgoebel** [comment]
> For map, it looks like the default for sx and sy is 0. What's wrong with just passing that? It seems unlikely to me that that will ever change.

Consistency.  It's weird if everywhere else you pass `-1` as a placeholder for "use default/no argument" but then in this one place it doesn't work... those kind of quirks in an API are infuriating.

**Comment by desttinghim** [comment]
I think with a low level binding, we can just have default arguments be required, and let a wrapper implement it per language. For missing arguments, we'll need to define values that indicate null. I'm not familiar enough with the TIC-80 API to be sure, but it looks like the following functions will be affected:

* `pix`
* `music`
* `pmem`

I think `-1` will work in those cases, though the pmem argument will need to be a 64 bit signed int that gets cast to an unsigned 32 bit int.

**Comment by joshgoebel** [comment]
Also, `btn`, `btnp`, `keyp`, and `sfx`... and yes I think `-1` would work in those cases. Though you could argue `music` is just default arguments... 

`sfx` is weird though... would you use `-1` only for the optional `note` argument that has no default?

**Comment by joshgoebel** [comment]
So to be clear to stop music I'd call:

```
// music [track=-1] [frame=-1] [row=-1] [loop=true] [sustain=false] [tempo=-1] [speed=-1]
WASM_music(-1,-1.-1, true, false,-1,-1)
```

Which we'd then likely hide being a nicer `nomusic()`... and `music(track, .{})`...

**Comment by desttinghim** [comment]
`-1` for the `note` argument in `sfx` to use the default value looks good to me. `WASM_music` looks fine for the underlying API call to stop music.

**Comment by nesbox** [comment]
Still think the internal per-languages wrappers only help us here

**Comment by joshgoebel** [comment]
> Still think the internal per-languages wrappers only help us here

Sorry that we're creating so much content you don't even have time to reply.  I'm not sure what this means.  Of course those are valuable for the other languages - because they are very high-level scripting runtimes... the C API is much too low-level (and benefits from wrapping)... but for WASM it's a bit different, so we're trying to find the right balance.

@desttinghim I forgot about color lists... should we just take both a pointer to an array and count of colors the same way the C API does?  The C API for `sfx` is also a different than the higher level API exposed to all the scripting languages, digging more into that now.

So a call to `spr` now looks like (in C):

```
// I think
u8 colors[5] = {1,2,3,4,5 };
u8 colorCount = COUNT_OF(colors);
tic_spr(index, x, y, w, h, &colors, colorCount, scale, flip, rotate) ;

// or
tic_spr(index, x, y, w, h, NULL, 0, scale, flip, rotate) ;
```

If so then we could pass those pointers and count straight thru.

**Comment by nesbox** [comment]
> Sorry that we're creating so much content

Yes, there has been a lot of content lately, I can't keep track of all your thoughts, sorry.

> Still think the internal per-languages wrappers only help us here

What I mean is that default parameter handling in per-languages wrappers is a good solution for me.

**Comment by joshgoebel** [comment]
> What I mean is that default parameter handling in per-languages wrappers is a good solution for me.

Yeah, but it's harder here since there is no strong concept of default arguments or variadic arguments at the WASM level.  We're trying to figure it out. :)

**Comment by msx80** [comment]
Josh what we are trying to say is: just use the whole API with all parameters explicitly, that is: the calls in api.h
Music is like this:

    void music(s32 track, s32 frame, s32 row, bool loop, bool sustain, s32 tempo, s32 speed)

Just like that, you translate it in your favourite language with no defaults etc, those are the low-level api for that language, upon which everything is built. All language can handle simple fixed parameters. 

THEN *optionally* you can create an higher level wrapper that offers shortcuts and defaults etc.

> OH, there may also be performance implications of passing 10 unused params around, but I'm not sure I know enough to get into that so I'm not sure how much that can educate our discussion here. Vs a struct, which would be passed by reference, not value...

No, passing parameter in the stack is fast. It's definitely something that doesn't need optimizing. You can pass the struct by reference, sure, but you have to allocate and deallocate it and that's much worst. Also: all tic80 languages already pass ALL parameters, becouse that's the only way to communicate to the VM inside tic80. 
You can see for example [here](https://github.com/nesbox/TIC-80/blob/master/src/api/wren.c#L1163-L1213) how the defaults are already handled per-language and how the whole API with all parameters is already being called (becouse it's the only way that can be called).

The only difference is that, as of now, default are handled per-language *inside* tic80, the new development will see defaults handled per-language but *outside* tic80.

**Comment by joshgoebel** [comment]
The open question here seems to be should the API wasm "gateway glue" do any default processing... @nesbox seems to think so, I'm still on the fence.  The default code is mostly already written (cause I was leaning that way originally)... so it's easy to go either way at this point.  I think it's hard to think about this as WASM is very different thing than our other runtimes.

> No, passing parameter in the stack is fast. It's definitely something that doesn't need optimizing. You can pass the struct by reference, sure, but you have to allocate and deallocate it and that's much worst.

It wouldn't ever be dynamic allocations (`malloc`, etc).  It'd be on the stack in either case, just either the WASM stack (via params) or the runtime stack (inside the WASM VM) as a struct.  I'll take your word it's worse, but I find it hard to understand why it would be "much worse".  

> Also: all tic80 languages already pass ALL parameters, becouse that's the only way to communicate to the VM inside tic80.

I think we're talking around each other.  Yes, the C API requires all arguments - unavoidable... but the Lua API does NOT... just like technically our WASM API *could possibly not*.  So I was referring to the cost of passing WASM arguments.  One imagines a `map()` no arguments call is a BIT faster than `map(20 arguments)`... but perhaps it's not enough to matter at all... yes, I know the C side has to provide all the arguments... 

I think there are two perspectives dualing here:

- treating the WASM wrapper as every other scripting wrapper (smart and brains above the C API)
- treating the WASM wrapper as just glue to the raw C API

And we're leaning closer and closer to the latter, but perhaps a tiny bit of the former.

**Comment by joshgoebel** [comment]
Does anyone have any thoughts about API changes/growth over time?  We haven't discussed that at all...  The C API has changed and evolved slowly over time.  One thing (off the top of my head) is the recent addition of `bits` to `tic_api_peek`... if we simply make the C API the "unchangeable" WASM API then we're locked into binary compatible with that forever.  So lets take peek (unless someone has a better example)...

Say we'd done this with 0.80 and now we have a WASM ABI of `peek(addr, value)` for memory... and then we want to expand the API to cover `peek(addr,value,bits)`... WASM can't export two peek functions... old cartridges will expect the `peek(ii)i` signature not `peek(iii)i`... with interpreted languages we've always been sorta free to change the C binary API because we can just mask over that at the runtime level.  That won't be possible with WASM - at least not if the function signatures change.

So would `peek` remain forever and we start naming the functions based on args (like some compilers already do) so our new peek would be `peek_iii_i`?  Now the _low-level_ WASM API would need to export two functions:

- `peek` (old signature)
- `peek_iii_i` (new signature)

If so, should we preempt this and do so from the very beginning?  _I think it's worth some time to think about this now rather than later._

There are also some other inconsistencies we may one day fix: Why does `font` only allow a single transparency color when every other API takes a pointer to an array?  It's drawing sprites, presumable there could be multiple transparent colors.

So there is an example of a future API that once could imagine changing one day.

**Comment by nesbox** [comment]
I think now we won't be allowed to change the parameters in the API after the wasm support will be released, we can only add new API functions, otherwise, it becomes a nightmare.

**Comment by joshgoebel** [comment]
Well, before we consider the API written in stone forever should we perhaps update `tic_api_font` to take:

- pointer transparent color array
- count of colors

_...like all the other low level endpoints_?  This would seem to be a pretty easy quick change.

**Comment by joshgoebel** [comment]
@nesbox I went ahead and just expanded the C API: 08dc1d1

The other APIs can catch up later (or never)... but now the C API is consistent and one less thing to worry about in the future.

**Comment by joshgoebel** [comment]
@msx80 Would you be willing to look thru the WASM API binding code and see if you have any other thoughts?

- https://github.com/joshgoebel/TIC-80/blob/wasm_support/src/api/wasm.c#L137
- https://github.com/joshgoebel/TIC-80/blob/wasm_support/templates/zig/src/tic80.zig

Re: the remaining defaults.  I'll decide whether to rip them out at the last minute... I always hate deleting code I've already written.  In the Zig API I opted to code the defaults into the library as much as possible. (excluding "argument not passed" situations)

I was more looking for another pair of eyeballs to catch any weirdness, issues I may have missed, or things we may not have thought of.  I'm pretty happy with things at this point.

The Zig library exposes both the raw C API and then a nicer Zig layer on top with named arguments, etc...

**Comment by joshgoebel** [comment]
@msx80 Ping.  I'm about to undraft this PR... was hoping to get your feedback first to see if we need to consider any other last-minute API changes.

**Comment by msx80** [comment]
Hi there, sorry i havent followed, i can take a look tomorrow 👍

**Comment by joshgoebel** [comment]
@msx80 I'm pulling the PR out of draft status... since we're starting to talk about a 1.0 release and I think WASM should be part of that... so you're running out of time if you were interested in adding any feedback.

**Comment by joshgoebel** [comment]
Closing via #1772. (which was manually merged)
