### ISSUE TITLE
tic_ram vs tic_core seems a bit muddled

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1779]
Related: #1777

The relationship between tic_ram and tic_core seems a bit muddled... many of our functions take one when really they need both.  Conveniently since ram is at the beginning of the core struct we can do this pointer casting, but it also makes it hard (no, impossible) to see the dependencies between functions:

```
void tic_api_circb(tic_mem* memory, s32 x, s32 y, s32 r, u8 color)
{
    drawEllipse(memory, x, y, r, r, mapColor(memory, color), setElliPixel);
}
```

You might reasonably assume here that `drawEllipse` only works on RAM and doesn't require other state, but you'd be wrong because deep down the chain `setPixel` is going to cast `tic_mem*` back to `tic_core*` to get access to hidden clipping state information not available in RAM.  This hiddenness makes the code harder to follow and understand.

Also there are many places we create a new variable, cast to core, _only then to never even use that variable at all_.  Obviously we could just delete those lines, but I think it's a symptom of the larger issue.

---

If this is SO strong a bond, why not just pass core around everywhere... and if we should desire put more distance between (which seems a reasonable thing to me, if only for the clarity it would provide in the codebase) perhaps we should have a simpler context object we pass around instead that has pointers to both core and ram.

Also worth noting here is the very related #1508.    Moving hidden state into actual hardware "RAM" isn't just for fun... it would simplify a lot of this as well.  MOST of the drawing functions only need `core` because of the hidden `CLIP` state that is ONLY available there... if it was properly moved into RAM then this *artificial* dependency on `tic_core` would be removed.  Right now the coupling is way tighter than it needs to be, and 80% of it (I think) is `CLIP`.

Is there a reason ANY of the drawing functions should need access to anything other than RAM, other than `CLIP`?

**Comment by nesbox** [comment]
`tic_core` is designed for internal use only, so, the studio with the editors don't have access to the core data, only to `tic_mem`

> if it was properly moved into RAM then this artificial dependency on tic_core would be removed

Yes, it can be removed but for drawing functions only in case if you find a way to move CLIP to the RAM, but there are also IO and sound functions that use the core.
