### ISSUE TITLE
Doesn't drawTile already check clipping itself?

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1796]
In drawTile:

```
    if (scale == 1) {
        // the most common path
        s32 sx, sy, ex, ey;
        sx = core->state.clip.l - x; if (sx < 0) sx = 0;
        sy = core->state.clip.t - y; if (sy < 0) sy = 0;
        ex = core->state.clip.r - x; if (ex > TIC_SPRITESIZE) ex = TIC_SPRITESIZE;
        ey = core->state.clip.b - y; if (ey > TIC_SPRITESIZE) ey = TIC_SPRITESIZE;
```

It appears to be taking clipping into account, yet in `setPixel` *for every single pixel* we check the clipping individually... it seems this is not necessary.  If I replace the drawTile pixel paints with `setPixelFast` (not clip checked) I see the official benchmark (modified to remove square root noise) go from:

- before: 31500
- after: 32900

About a 4.4% win... for a hot path.  This is release, min size.  I think this is real win because I can't really see how the compiler could optimize this check away in any case.  I modified the demo cart to scale=1 and moved the guy around and he seems to clip just fine with no issues.

Thoughts?  Should I push PR?

**Comment by nesbox** [comment]
> Should I push PR

sure, pls if not difficult
