### ISSUE TITLE
Request: Rename master branch to main?

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1805]
This is so commonplace now (since GitHub has made it default) that the few repositories I work with not using the new default naming kind of throw me for a loop every time I go to work branches in the terminal.  Any chance we could rename primary development branch to the new default of `main`?  

GitHub makes it super easy to do this these days.

**Comment by nesbox** [comment]
Renamed to `main`
Please call these commands to change the branch locally
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
`readme.md` changes here 7e8b971a7a76792ab82dc2544a6c7a2d38198bca

**Comment by joshgoebel** [comment]
For anyone else who has a fork - I had to go thru these steps like 1.5 times (and rename my fork as well)... to get both my origin and `upstream` pointed to the correct place.  Just a heads up.

@nesbox Thanks!
