### ISSUE TITLE
Surfing tic80.com without needing a keyboard (with retro handheld devices)

### ISSUE THREAD

**Issue by Ardakilic** [nesbox/TIC-80#1809]
Hello,

Is it possible to implement a way to 'surf' without keyboard input?

I'm using Tic-80 with Anbernic RG351P, a retro handheld device, and I want to browse the tic80 catalog.

I know, this can be done by going into the shell, and typing 'surf tic80.com', but it does not have a keyboard input, just like old retro devices.

I thought about making a meta-cartridge, but I believe the cartridges won't have network capabilities, since I could not find a method to achieve this or to execute a command via cartridge script (maybe I'm missing something). 

I'm not asking for online play, so #243 should not be same with my request.

I just want to browse tic-80 site over the console, without needing a keyboard, something like [Splore of Pico-8](https://pico-8.fandom.com/wiki/Splore).

Thanks in advance,

**Comment by nathanjent** [comment]
Could you start tic80 with an argument? `tic80 --cmd surf`

**Comment by Ardakilic** [comment]
Sadly, as far as I can tell, it's not possible. You just select your .tic80 files from [EmulationStation](https://github.com/Aloshi/EmulationStation), and run them just like any other emulator. After I run the cartridge, I can go to Retroarch settings, however, I cannot see any option to put any argument or fallback to console. Even if I did, there would be no option to type tic80.com. That's why I thought a cartridge, which runs the command would be a solution to all of this.

**Comment by nesbox** [comment]
TIC-80 works like an emulator in Retroarch and you have to provide a cart to play a game.

**Comment by Ardakilic** [comment]
Hey @nesbox , thanks for the reply! That's exactly the purpose of my question. Is there any way to create a cart that just triggers the surf command? I checked the api but could not find a reference to trigger the surf command (maybe I'm missing something?) The rest would be essentially doable just with handheld's keys, from what I can tell.

If not possible currently, please consider this issue as a feature request.

Thanks!

**Comment by nathanjent** [comment]
Could you [modify the command tag in the es_systems.cfg file](https://emulationstation.org/gettingstarted.html#config). Sorry if this is way off base, I'm not familiar with the RetroArch setup.

**Comment by Ardakilic** [comment]
Hey @nathanjent , wouldn't that break the feature of running the cartridges which are downloaded locally?

[Here's the 351ELEC's es_systems.cfg](https://github.com/351ELEC/351ELEC/blob/dev/packages/ui/351elec-emulationstation/config/es_systems.cfg#L1824-L1842), I believe it runs [this command with arguments](https://github.com/351ELEC/351ELEC/blob/dev/packages/351elec/sources/scripts/runemu.sh), but I'm lost there.

**Comment by nathanjent** [comment]
@Ardakilic, you could try adding another system entry to that config that runs TIC-80 with the surf option. It looks like most of the entries use that same shell script which expects a rom file. That won't really work for surf. The surf features are not available to the carts at this time.

How is it set up for pico-8?

**Comment by Ardakilic** [comment]
@nathanjent I'll try to do that, thanks!

351ELEC runs splore with a bash script, as far as I can tell. When you navigate into pico-8 section, it has a 'Start Pico-8' option at cartridge browser startup.

[Autostart.sh](https://github.com/351ELEC/351ELEC/blob/dev/packages/351elec/sources/autostart.sh#L103) file adds [this following bash script](https://github.com/351ELEC/351ELEC/blob/dev/packages/351elec/sources/pico-8.sh) in to pico-8 roms folder as `Start Pico-8.sh`, and I believe this acts like a cartridge and starts Splore.

**Comment by nesbox** [comment]
>  I'll try to do that, thanks!

Pls don't waste your time, it won't work, it's just a cart player :)
The only way is to compile the whole TIC-80 studio to your system.

**Comment by Ardakilic** [comment]
351ELEC discord channel told me that it cannot be achieved because it's a RetroArch core and these shell scripts call RetroArch with parameters, not the emulator directly.

Meanwhile, I've asked them for a virtual keyboard solution as workaround. One can argue that retro gaming devices did not have internet access, but I wish this was achievable in a native way in tic80 in the retro handheld devices, without needing a keyboard input.

**Comment by LettucePie** [comment]
Hi

I think I might have fixed this issue

https://github.com/nesbox/TIC-80/pull/2387

**Comment by Ardakilic** [comment]
Hey @LettucePie , thank you for the feature! Sadly I'm crowded with work nowadays, but I'll try check next week. Thanks once again!
