### ISSUE TITLE
Paste glitch

### ISSUE THREAD

**Issue by IiTossiI** [nesbox/TIC-80#1810]
https://user-images.githubusercontent.com/94807008/149373932-63954c28-a500-4578-9236-f2a02bc6c380.mp4

Artifacts appear when you copy any sized drawing into a bigger frame.
Artifacts are different everytime image being pasted.

**Comment by paul59** [comment]
Can confirm the same on Linux with 0.9.1723 Pro.

(pasting a large area to a smaller one does nothing)

**Comment by nesbox** [comment]
Fixed here 5c917287e9c360f3b2fae8bbcb6352407e0a21b2
Thank you.
