### ISSUE TITLE
Main menu and easy access to editor

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1814]
Is there no easy way to get back to the editor now that the menu has been added?  It feels like a long slog to pull up menu, scroll down, choose close game when before I could just hit esc, code, run, and rapidly iterate... am I missing something?

**Comment by borbware** [comment]
easy-to-implement solution to this could be having F1-F5 buttons active to access editors when game is running

**Comment by nesbox** [comment]
I simplified menu logic and it works equally everywhere now, but this created the difficulty of exiting the game.

> easy-to-implement solution to this could be having F1-F5 buttons active
I don't know if it's worth having the F1-F5 buttons active, because these buttons could be used in the game.

Also, in the current realization, you can press ESC and then F1-F5 to go to the editors, it's the easiest way to close the game that I see.

**Comment by borbware** [comment]
> Also, in the current realization, you can press ESC and then F1-F5 to go to the editors

Ah, this is fast enough for me, didn't think to try it out.

Thanks for all the menu improvements btw! It looks very professional now. :>

**Comment by blinry** [comment]
I'd also love an easier way to switch between editing and running a cart! <3 That's something you do all the time, and in the current implementation, I press Esc and F1 in the wrong order pretty often.

Two proposals:

1. Pressing Esc in the menu brings you to the editor which was last open when you launched the game. So it would be a double tap on Esc to switch back to editing.
2. Have a "development mode" flag, where Esc directly jumps to the last editor. This flag could be on normally, and be off when TIC-80 directly boots into a game, I guess? It gets turned on as soon as an editor is entered. And if you need the menu, you can use the `menu` command?

I'd much prefer only having to press Esc a single time, as in option 2. But option 1 would be a simpler fix for now. What do y'all think? Maybe there's an even better way to enable quick toggling between editing and playing, while preserving cases in which the menu in between makes sense?

**Comment by joshgoebel** [comment]
A separate key to access the menu is another idea?

**Comment by nesbox** [comment]
We could add a "Development mode <ON/OFF>" option to the menu that will open the last used editor when pressing ESC.

**Comment by joshgoebel** [comment]
I think that would solve 90+% of this issue...  I used TIC-80 for years and never missed the menu... it seems something developers really would only need to test the menu itself...

**Comment by nesbox** [comment]
so let's do it, thanks

**Comment by nesbox** [comment]
Added `DEV MODE` to the game menu options https://github.com/nesbox/TIC-80/commit/c1b4095e5bb42b1328e6fec6f7dd6caf3b0a6364

**Comment by borbware** [comment]
wait, how do you disable dev mode? :D you can't access the menu when dev mode is on, after all....

**Comment by nesbox** [comment]
pls use `menu` command in the console :)
