### ISSUE TITLE
Unsaved changes menu allows scrolling off of options

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1817]
https://user-images.githubusercontent.com/13716824/149862664-5ad66ec4-3d3c-4734-9515-a4e299037ea6.mp4

Currently you can scroll onto the display text, not just the options

**Comment by nesbox** [comment]
It's funny, but it's by design, you can read multiline text with the gamepad only.
![video21](https://user-images.githubusercontent.com/1101448/149885605-b8b117d1-7f15-4edc-8cb5-c2366ddf84f6.gif)

**Comment by ChildishGiant** [comment]
I see how that could be useful but I think that it's counter-intuitive in this particular menu
