### ISSUE TITLE
Black border and inaccurate scaling

### ISSUE THREAD

**Issue by darltrash** [nesbox/TIC-80#1818]
Hello everyone! I recently built the Pro version using master after using the latest release published on Github, and I noticed some big differences when considering scaling and borders.

## 0.90.1729
![image](https://user-images.githubusercontent.com/38925212/150063925-bd524182-7d79-4323-a5d2-fc3455ccb36f.png)

## Master Pro
![image](https://user-images.githubusercontent.com/38925212/150064768-86a848de-12dd-4d72-a056-947f17a36bc3.png)

As seen, now there's an entire black border around the gradient instead of the gradient adjusting to the entirety of the border and that the scaling seems to not snap to integers as it did before.
Is this intentional? Am I missing out on something? I compiled everything as the readme told me and used the install steps for linux.

### Code used for SCN() (No changes whatsoever from version to version):
``` moon
W, H = 240, 136

clamp = (x, min, max) -> 
	x < min and min or (x > max and max or x)
	
lerp = (a, b, amount) -> 
	a + (b - a) * clamp(amount, 0, 1)

SCN = (scn) ->
	bg1r, bg1g, bg1b = pal 1 -- Taken from wiki, code-examples-and-snippets > pal-function
	bg2r, bg2g, bg2b = pal 8
	poke(0x3fc0, lerp(bg1r, bg2r, scn/H)) 
	poke(0x3fc1, lerp(bg1g, bg2g, scn/H))
	poke(0x3fc2, lerp(bg1b, bg2b, scn/H))
```

### Extra information (though it might be redundant):
Tic80 Version: `1.0.1996-dev Pro (`06fde12`)`
OS: `elementaryOS 6.1 (Ubuntu 20.04.3 LTS)`
Architecture: `x86_64`

**Comment by nesbox** [comment]
> Am I missing out on something?

I removed snap to integers to unify rendering with CRT monitor effect and without, but in the future, it can be added as an option in the config.

**Comment by joshgoebel** [comment]
Very sad to see snap to integers not being the default... I thought one purpose of a border was so our pixels could be "perfect squares" irregardless of the window size?

**Comment by darltrash** [comment]
> > Am I missing out on something?
> 
> 
> 
> I removed snap to integers to unify rendering with CRT monitor effect and without, but in the future, it can be added as an option in the config.

What about borders? Will they stay like that? What if my game isn't meant to have the CRT effect enabled? I have seen that it drastically affects legibility but that might get fixed with a future update.

**Comment by nesbox** [comment]
The borders and snap to integers can be implemented under new conditions, also these options could be added to the new main menu and enabled by default, as you wish :)

**Comment by darltrash** [comment]
> The borders and snap to integers can be implemented under new conditions, also these options could be added to the new main menu and enabled by default, as you wish :)

Sounds reasonable

**Comment by nesbox** [comment]
Added screen Integer Scaling option, enabled by default 7ab96aecf6c24f93d561dcfd2fa6e45e0a61cf75
![image](https://user-images.githubusercontent.com/1101448/158601063-c0c78dcd-c796-4fbf-9e34-51c23566aec8.png)

**Comment by nesbox** [comment]
Still decided not to complicate things, so, integer scaling + borders work in normal mode, and nothing of them in CRT mode.
Also, Integer Scaling removed from the options.

**Comment by schammy** [comment]
> Added screen Integer Scaling option, enabled by default [7ab96ae](https://github.com/nesbox/TIC-80/commit/7ab96aecf6c24f93d561dcfd2fa6e45e0a61cf75) ![image](https://user-images.githubusercontent.com/1101448/158601063-c0c78dcd-c796-4fbf-9e34-51c23566aec8.png)

Is integer scaling an option when exporting? Either forced on/off, or as an option for the person playing the game?

**Comment by schammy** [comment]
Oh I just bought the Pro version to test and didn't see the option in the menu, now re-reading your comment above, it sounds like maybe you removed the option from the menu, but it still exists somewhere? Can it be enabled via config or something?
