### ISSUE TITLE
Bug: Software mouse cursor cannot be disabled

### ISSUE THREAD

**Issue by eglavas** [nesbox/TIC-80#1824]
poke(0x3FFB,0) should turn off (system) mouse cursor - instead it makes it sprite #256 (in 4 bpp mode).

The other pokable values work as documented.

it's documented as: 

0x3FFB | MOUSE CURSOR      | 1     | sprite to use for mouse pointer

MOUSE CURSOR specifies which cursor to use:
0 = Disabled
1...127 = Sprite (#257 to #383 in 4bpp mode)
128 = ARROW
129 = HAND
130 = IBEAM
131...255 = Reserved

**Comment by nesbox** [comment]
Seems I broke it when added software mouse cursor :)
Thanks, will fix it.

**Comment by nesbox** [comment]
fixed here 556b2a922bb641dd04e691b53f3f2d8d5fdbe0ca
