### ISSUE TITLE
using line() can freeze tic80

### ISSUE THREAD

**Issue by fnordomat** [nesbox/TIC-80#1826]
Minimal example that freezes the whole environment (have to SIGKILL it and lose any unsaved changes):

```
function tic()
cls()
line(0,0,0,1e10,1)
end
```

It can happen with other functions like `tri` as well, when some of the endpoints are too far away.

Apparently in such cases it just goes on and on without the possibility of interruption.

IMO a function like `line` should be safe to use and not freeze the environment. Maybe the line-drawing algorithm could check the bounding box, or at least check for interruptions?

**Comment by nesbox** [comment]
You're right, we should check the bounding box, thanks.

**Comment by joshgoebel** [comment]
I believe this is/was done intentionally to allow clipping (ie, drawing to places out of frame is ok, just as long as you aren't trying to draw to position 1,000,000 or something crazy), but I suppose we could add bounds checking upfront, calculate the slope/direction of the line and then if either of it's start or final coordinates are "out of frame" just calculate bounded coordinates that would produce the same end effect.

Note: This quite possibly applies to other drawing primitives also... trying to draw a circle with 1 billion off-screen pixels is quite likely to also freeze the system... we should make a list of affected APIs before jumping into a fix for this.

**Comment by nesbox** [comment]
fixed here bf361fd2e6088b3cf06cf92c23f534a86c6078b4
