### ISSUE TITLE
--keepcmd seems to be broken

### ISSUE THREAD

**Issue by scambier** [nesbox/TIC-80#1827]
**What is expected:**

- TIC-80 is launched with `--cmd "load game.js & load build/code.js code & run" --keepcmd`
- The game starts with the code from `build/code.js`
- We update the code in `build/code.js`
- We hit ctrl+r inside TIC-80
- The new code inside `build/code.js` is injected into the cart, and the game is reloaded with the new code

**What is happening:**

TIC-80 is reloaded but the new code isn't loaded. The game is still running with the code that was initially loaded.

Context: https://github.com/nesbox/TIC-80/issues/1494#issuecomment-886551084

**Comment by nesbox** [comment]
ok, will check itm thanks

**Comment by scambier** [comment]
Nope, there's actually a nasty bug (sorry)! It was quite hard to reproduce though :p

It boils down to pressing ctrl+r the bypass reload confirmation (like after a sprite change).

Here's a repo with the instructions: https://github.com/scambier/TIC-80-bug

**Comment by nesbox** [comment]
Disabled shortcuts if console has active commands 6649d8c3adab5ed339e8c74607afb690a1d2f9c6
