### ISSUE TITLE
TIC-80 v1.0.2024-dev Pro HTML. Pressing the ESC key crashes the system, bad performance

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1828]
Test: https://kyuchumimo.itch.io/alter-ego-tic-80-tiny-computer (Downgraded to v0.90.1723)

**Comment by nesbox** [comment]
I see the crash but what about bad performance?

**Comment by Kyuchumimo** [comment]
Performance is worse in Firefox browser compared to TIC-80 v0.90.1723 vs v1.0.2024
