### ISSUE TITLE
TIC-80 v1.0.2024-dev Pro. Empty menu slot

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1830]
![empty menu slot](https://user-images.githubusercontent.com/74131798/152436322-b86c9530-503a-4272-81de-05cd26289320.gif)

**Comment by nesbox** [comment]
This is by design but we can fix it if it annoys you :)

**Comment by joshgoebel** [comment]
Personally I think it's nice.

**Comment by MFauzan26** [comment]
I think it looks bad, no text box, no logo, just plain text

**Comment by paul59** [comment]
I think the selection bar should go from 'options' to quit, not a selectable empty row between... either that or get rid of the blank line and move 'quit' and 'back' up a row :-D

**Comment by TimotheeGreg** [comment]
That has been solved here: https://github.com/nesbox/TIC-80/pull/2067 .
