### ISSUE TITLE
Opt-2 also triggering 2

### ISSUE THREAD

**Issue by sodapopcan** [nesbox/TIC-80#1832]
This feels like the same issue as #1595.  That issue is closed and the behaviour described in the ticket is fixed, but I'm still seeing an issue on macOS for `opt-2`.  Using that hotkey to switch to the sprite editor, the eye-dropper is always set to the current tool.

Thanks!

**Comment by nesbox** [comment]
This has been fixed in version 1.0 dev but it hasn't been released yet.
I assume you are using version 0.90.

**Comment by sodapopcan** [comment]
Gotcha!  I'm new to the platform and only picked it up a few days ago—I'll keep a closer eye on dev.  Thanks for the speedy response!

**Comment by TimotheeGreg** [comment]
That can be closed, 1.0 has been released long time ago.
