### ISSUE TITLE
Delay when calling sfx

### ISSUE THREAD

**Issue by Darenn** [nesbox/TIC-80#1839]
Hey everyone,
I'm trying to use the `sfx` function to play sounds.
But there is a big delay between the call and the actual sound being played.
Here's my testing program on version 1.0.2026 :
```
function TIC()
    if btnp(0) then sfx(0, 30, 30) end
end
```
Am I doing something wrong ?
Thanks!

**Comment by crb233** [comment]
I think this is related to #1764 and #714. Should be fixed in the dev build, but not the most recent release.

I've been having the same problem. For me, closing TIC-80 and reopening temporarily solves the problem.

**Comment by mooncalf** [comment]
I can confirm this delay is happening on the Mac, with Tic-80 version 1.0.2039-dev Pro (the latest, as of this afternoon). The delay starts at about a second and increases over time to several hours. Closing Tic and reopening resets the delay to about a second.
