### ISSUE TITLE
Code editor: Shift+Del deletes an extra character after cutting

### ISSUE THREAD

**Issue by rrrola** [nesbox/TIC-80#1841]
Shift+Del (Cut selected text / Cut current line, an alternative to Ctrl+X) deletes an extra character after the cut.

Expected result: Shift+Del should work exactly like Ctrl+X.

(Happened on 0.90.1723 in Windows.)

**Comment by rrrola** [comment]
The same issue happens after Ctrl+Del: an extra character is deleted.

**Comment by nesbox** [comment]
ok, thanks for the report

**Comment by nesbox** [comment]
Fixed here d7347aa05ca5e2c71b60e40a6380b7435453ab6d
Thanks
