### ISSUE TITLE
Code editor: Undo after Paste moves cursor to the place of the previous edit

### ISSUE THREAD

**Issue by rrrola** [nesbox/TIC-80#1842]
When doing Undo after pasting or writing a character, the cursor moves to the place where it was after the previous editing action.

Expected result: The cursor should move where it was before the paste or write event happened, like in other text editors.

Repro:
1. write "123", select it and copy it [Ctrl+C]
2. paste it [Ctrl+V] a few lines below
3. press undo [Ctrl+Z]: the cursor should stay on the line where you pasted the text, but it moves back after "123"

(Happened on 0.90.1723 in Windows.)

**Comment by nesbox** [comment]
ok

**Comment by MineRobber9000** [comment]
This is what happens when I do the exact same thing from this report in Atom.

Before undo:
```
123
123
123
123
123
123
|
```

(the | representing the cursor)

After undo:
```
123
123
123
|
```

TIC seems to match this behavior; I'm not sure what you were expecting to happen?

**Comment by rrrola** [comment]
I had this scenario in mind:
Before step 1:
```
abc
abc
```
After step 1 (Copy - 123 is selected):
```
123|
abc
abc
```
After step 2 (Paste):
```
123
abc
abc123|
```
After step 3 (Undo):
```
123|
abc
abc
```
Expected state after step 3:
```
123
abc
abc|
```

**Comment by MineRobber9000** [comment]
Yeah, TIC-80 1.0 currently does what you expect, while 0.90 does have the bugged behavior you describe.

**Comment by nesbox** [comment]
We can close it if it's fixed.
