### ISSUE TITLE
Editor discoverability: edit command, help text

### ISSUE THREAD

**Issue by rrrola** [nesbox/TIC-80#1843]
This seems like something so basic it should be obvious, but as a new user I had trouble opening the code editor.

What I've tried:
- Typing "edit" on the command line is an error (unknown command).
- Typing "help" on the command line displays the following message which doesn't mention the editor:
  > **usage**: help [‹text›|version|welcome|spec|ram|vram|commands|api|startup|terms|license]
  > type **help commands** to show commands
  > press **ESC** to enter UI mode
- I've tried "help welcome" that talks about the built-in editors but not how to open them.
- I've tried "help commands" and "menu".
- In the end, I went on the wiki and found the [F1 shortcut](https://github.com/nesbox/TIC-80/wiki/Hotkeys) (and also that ESC opens the editor).

I believe the last line in the basic help text should be "press **ESC** to switch editor/console" or similar.
The text displayed in "help welcome" could also mention how to enter the built-in editors (the F1..F5 hotkeys).
There should also be a commandline command to enter the editor: "edit"?
Maybe it should also be an option in the game menu.

(Windows, version 0.90.1723)

**Comment by nesbox** [comment]
We will try to remove this misunderstanding, thanks :)

**Comment by nesbox** [comment]
Changed help text to `press ESC to switch editor/console`, also restore `edit` command 2fb60df050ff7cc4d6d3db7749eb654435f6f19a
Thank you
