### ISSUE TITLE
Locally compiled version won't start, claims a folder doesn't exist even though it does

### ISSUE THREAD

**Issue by jennybrown8** [nesbox/TIC-80#1844]
I built tic80 locally.  It built fine, no errors.  When I try to run it, it gives the following error about a folder not existing.  I created the folder manually, then reran, and it still complains about it, even though the folder exists.  Seems to be a misleading error message when something else is the true cause, but I have no idea what.

    Windows 10 Pro 20H2, build 19042.1526
    Cloned from this repo on Feb 17 2022 from main. 
    Same error whether I build with or without pro flag.

    C:\Users\jenny\dev\demoart\TIC-80\build\bin>tic80
    error: folder `C:\Users\jenny\AppData\Roaming\com.nesbox.tic\TIC-80\` doesn't exist

    C:\Users\jenny\dev\demoart\TIC-80\build\bin>dir 
    C:\Users\jenny\AppData\Roaming\com.nesbox.tic\TIC-80\
    Volume in drive C is Windows
    Volume Serial Number is AC37-9F02

    Directory of C:\Users\jenny\AppData\Roaming\com.nesbox.tic\TIC-80

    Thu 2022-02-17  01:19 AM    <DIR>          .
    Thu 2022-02-17  01:19 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  574,803,382,272 bytes free

**Comment by nesbox** [comment]
Hmm, I've never seen this before, does the 0.90 version work?

**Comment by aliceisjustplaying** [comment]
I can repro this, strangely enough, on a Windows XP build (built on Windows 11) but executed on Windows XP. Works on Windows 7.

![Screenshot 2024-04-27 at 4 28 08 PM](https://github.com/nesbox/TIC-80/assets/81575558/01187995-241b-4a10-a70d-f715e1559a43)

**Comment by aliceisjustplaying** [comment]
double-checked with the CI build; same issue.

**Comment by aliceisjustplaying** [comment]
This is a bug in the runtime/toolchain and the tl;dr is that you need to use `GetFileAttributesEx` on Windows (or at least on Windows XP at least) instead of `stat`.

**Comment by aliceisjustplaying** [comment]
Not sure why the error happens for the OP, though.
