### ISSUE TITLE
WASM:  can we support remap callback on map? 

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1848]
Reference: #1772 

This one may be over my head. WASM3 author thinks technically yes, but it sounds like a chore - and WASM3 doesn't provide the needed support pieces yet.  Something we should look into for the future.

**Comment by soxfox42** [comment]
Opened wasm3/wasm3#448 to add the required underlying functionality, but Wasm3 development seems to be slow, so I don't know when this will be available upstream. Will try implementing the TIC-80 side against my w3 fork.

**Comment by soxfox42** [comment]
Turns out the functionality was added already - in 2021, before this issue was created. Odd that the author didn't think it was supported. I'll try to implement `remap` when I get a chance.
