### ISSUE TITLE
Enabling "Dev Mode" and resuming the game causes TIC to close, plus another nitpick about the game menu

### ISSUE THREAD

**Issue by MineRobber9000** [nesbox/TIC-80#1851]
The title says it all when it comes to the first bug I noticed. To replicate, build from `main` (I built a PRO binary, if that changes any code paths relating to this menu significantly), load up a game (I used `quest` from the demos), go into Options, turn on "Dev Mode", back out, and select "Resume Game" (with the A button). Instead of going back to the game with the game menu disabled, TIC-80 simply closes. What should happen (IMO) is that the game menu is simply disabled, and you're returned to the game (as if you had chosen "Close Game" and restarted, but without losing any progress you may have made).

The other nitpick about the game menu has to do with muscle memory. As someone who was encountering this menu for the first time, my instinct (honed from years of video games) is that in order to close the menu without necessarily needing to choose an option, I should either press B, or I should press Escape. In the game menu, however, either of those options will close TIC entirely.

**Comment by nesbox** [comment]
Omg, it crashes, it's not a feature :)

**Comment by MineRobber9000** [comment]
> Omg, it crashes, it's not a feature :)

Oh! Definitely not a feature then 🤣
