### ISSUE TITLE
If a game errors, the escape key no longer works as intended

### ISSUE THREAD

**Issue by MineRobber9000** [nesbox/TIC-80#1854]
When a game has an error, it causes the console to try and spawn the game again. Furthermore, loading another game and launching it causes the escape button to not work at all.

**Steps to reproduce:**
1. Download [bugreport.lua.txt](https://github.com/nesbox/TIC-80/files/8189030/bugreport.lua.txt) and rename to `bugreport.lua`.
2. Load `bugreport.lua` in a fresh build from the main branch.
3. Run it and observe the error (in this case, calling a nonexistent function).
4. Press the escape key.
 
**Expected behavior:**
The escape key would bring up the code editor.

**What happens:**
Instead, the escape key attempts to bring up the game, which errors again (for the same reason as last time). Furthermore, if you load another game and run it, you will not be able to press the escape key to exit it (in fact, nothing will happen).

**Comment by nesbox** [comment]
fixed here a81979d9e5d658a5d4335bab60a84c3aeedb6f83
thank you
