### ISSUE TITLE
More legible 5x3 ampersand (&)

### ISSUE THREAD

**Issue by rrrola** [nesbox/TIC-80#1855]
In the 5x3 part of the system font, the current ampersand is illegible:
```
##
##
###
# #
 ##
```
I suggest changing it to one of the following alternatives:
```
 ##   ##   ##
 ##  #    #
 #    ##   ##
# #  # #  # #
 ##   ##   #
```

**Comment by nesbox** [comment]
fixed here 1d6709ba6bd9886d96284f33e48d1ce533abf4b0
used this one
```
 ##
 ##
 #
# #
 ##
```
![image](https://user-images.githubusercontent.com/1101448/157418996-3c759fb4-d350-40a7-807c-b4e380f5a342.png)
