### ISSUE TITLE
Using a physical keyboard (Bluetooth or USB (OTG)) acts as typing on the ABXY buttons in gameplay (TIC-80 Android)

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1857]
See the virtual buttons on the screen:
https://user-images.githubusercontent.com/74131798/157561679-b6fa65f4-84ea-4e12-aaf8-ff80652b638a.mp4

This behavior does not occur in other applications such as Retroarch.

**Comment by nesbox** [comment]
I'm sure it's not a bug because your gamepad mapped to these keyboard buttons `A-z` `B-x` `X-a` `Y-s`.
Pls go to the game menu and clean the gamepad mapping to disable this behavior.

**Comment by Kyuchumimo** [comment]
How can I clean gamepad mapping?

**Comment by nesbox** [comment]
I'll add `clean mapping` item to the menu :)

**Comment by nesbox** [comment]
Added CLEAR MAPPING menu item 8064ce4addf6b2c13e936356ce405525113255a4
