### ISSUE TITLE
sfx function plays note 40/'E-4' by default, note default parameter value it is not documented in the wiki?.

### ISSUE THREAD

**Issue by Kyuchumimo** [nesbox/TIC-80#1858]
https://github.com/nesbox/TIC-80/wiki/sfx

`sfx id [note] [duration=-1] [channel=0] [volume=15] [speed=0]`

**Comment by nesbox** [comment]
There is no default note parameter, `sfx()` plays note that assigned in the Sfx Editor.
![image](https://user-images.githubusercontent.com/1101448/157845825-786dcca7-bf23-4429-9434-218c2cd9dcc7.png)
