### ISSUE TITLE
Unsaved changes screen crashes TIC-80 when loading project from disk

### ISSUE THREAD

**Issue by MineRobber9000** [nesbox/TIC-80#1859]
When you save a project in a text editor while there are conflicts between the project on disk and the project in TIC-80, instead of pulling up the screen for "are you sure you want to load?" it hard-crashes, emitting a loud beep and becoming unresponsive (requiring Task Manager to close).

**Steps to reproduce:**
1. Launch a build of TIC-80 Pro.
2. Save the default Lua cart as a project (or any cart, really).
3. Make a change in TIC-80 (for instance, drawing on a sprite, or placing things on the map) without saving it to disk.
4. Open the project in a text editor and make a change there (like adding a comment).
5. Save the project in the text editor (keeping in mind you have unsaved changes within TIC-80).

**Expected behavior:**
The unsaved changes screen pops up, allowing you to choose whether or not to load the file.

**What happens:**

https://user-images.githubusercontent.com/12676241/157786866-c6c8b30f-7437-4c59-b145-d0a4168dfa74.mp4

**Comment by nesbox** [comment]
Fixed here 7e9b35dfd7926584a5c250d16bf75886a087b68a
Thanks
