### ISSUE TITLE
Z-corrected ttri() causes Wren API to be unable to load

### ISSUE THREAD

**Issue by MineRobber9000** [nesbox/TIC-80#1872]
Wren games are entirely broken at present, due to the fact that the version of `ttri` that corrects for perspective has 17 parameters while Wren doesn't allow functions to have more than 16 parameters.

**Steps to reproduce:**

 - Start a build of TIC-80.
 - Run the `new wren` command (to bring up the wren demo cart).
 - Attempt to run the game.

**Expected behavior:**

It runs the demo cart.

**What actually happens:**

![image](https://user-images.githubusercontent.com/12676241/162266658-35896985-d846-4184-bda5-1d020ce3501e.png)

**Comment by MineRobber9000** [comment]
After looking at the code, the issue appears to be that Wren does not allow methods with more than 16 parameters, and the Z-corrected `ttri` has 17 parameters: https://github.com/nesbox/TIC-80/blob/main/src/api/wren.c#L80

**Comment by nesbox** [comment]
We need to find a workaround for the `ttri()` in Wren.

**Comment by MineRobber9000** [comment]
Originally, my thought process was to modify Wren to allow a 17th parameter, but Wren is decidedly not built with that in mind. Perhaps, for Wren (and Wren only), the parameter for using sprite RAM vs map RAM could be removed and replaced with a `ttri_sprite` or `ttri_map` (with an explanatory note in the wiki)?

**Comment by nesbox** [comment]
I added additional `ttri_depth(z1,z2,z3)` function to Wren only 1f28e3aa86edb52181c75290782a2770965aaf7a
So, to call `ttri()` with depth parameters you have to use two functions
``` js
TIC.ttri_depth(z1,z2,z3)
TIC.ttri(...)
```
and to disable depth, use
``` js
TIC.ttri_depth()
TIC.ttri(...)
```
