### ISSUE TITLE
Why the outline [ctrl+o] feature does not work with languages other than Lua?

### ISSUE THREAD

**Issue by ThaCuber** [nesbox/TIC-80#1876]
I can only use it when working with Lua, and I really like to use Moonscript when programming, so that would be nice if it could work with languages other than Lua.

**Comment by nesbox** [comment]
It also works with other languages. Could you provide an example of code that you think doesn't work with `ctrl+o`?

**Comment by ThaCuber** [comment]
Well...
In Wren it outlines only classes. (I guess it makes sense)
![image](https://user-images.githubusercontent.com/70547062/162646156-3b7d0aa9-e988-47ff-b452-1495786f2568.png)
In Squirrel it only outlines functions.
![image](https://user-images.githubusercontent.com/70547062/162646226-7e296a37-aac6-465b-b16d-0cd12093e143.png)
In Moonscript it won't outline anything at all.
![image](https://user-images.githubusercontent.com/70547062/162646140-20852749-d3c4-4f56-a270-78ee3ee38613.png)
All other languages seem to work fine.

**Comment by ThaCuber** [comment]
Found something in Moonscript:
Only functions like `func=->` get outlined.
Functions like `func = ->` or functions with parameters do *not* get outlined.

**Comment by nesbox** [comment]
I see it, thanks
the reason is that people add support for new languages but forget to properly implement the struct function for them :(
We'll fix it someday but it's not an easy task...
