### ISSUE TITLE
Regression: `config default` with no parameter crashes TIC-80

### ISSUE THREAD

**Issue by FayneAldan** [nesbox/TIC-80#1885]
Typing `config default` (to edit a default cart template) without specify the language causes TIC-80 to crash on f9e2a247956e123708810d91ff3addd0943d1a0d. Works fine on [0.90.1723](https://github.com/nesbox/TIC-80/releases/tag/v0.90.1723).

**Comment by pythonmcpi** [comment]
Can reproduce using the Windows (regular) build from Github Actions Build https://github.com/nesbox/TIC-80/issues/954.

**Comment by nesbox** [comment]
fixed crash here 21173d1245c3cdbb08b794c8d126865772819217
