### ISSUE TITLE
Wasm: Type mismatch between function signatures and implementations

### ISSUE THREAD

**Issue by PierceNg** [nesbox/TIC-80#1888]
In ```src/api/wasm.c```, in ```linkTicAPI```, all function parameters are declared to be either ```i``` or ```*```. But some functions, e.g., ```wasmtic_line```, are actually reading floats off the stack, not integers.  For ```wasmtic_line```, its correct signature is ```v(ffffi)```.

I've verified that ```line()``` doesn't work with the current incorrect signature, and works with the fixed signature.

Will send PR once I verify the other handful of functions.

**Comment by joshgoebel** [comment]
Pretty sure it's because these APIs were all changed recently to take floats when they took ints before. A fix would be great.
