### ISSUE TITLE
Update checker crashes TIC-80 if there is no internet

### ISSUE THREAD

**Issue by MineRobber9000** [nesbox/TIC-80#1889]
The update checker causes a crash when there is no internet.

**Steps to reproduce:**

1. Turn off internet (unplug Ethernet, disable Wi-Fi, etc.)
2. Open a build of TIC-80 from the latest `main` branch

**Expected behavior:**

TIC-80 opens without issue, allowing me to work on locally-stored carts.

**What happens:**

It crashes, with no error info logged to the console (that I can see).

**To demonstrate that the update checker is at fault:**

1. Turn internet back on (replug Ethernet, enable Wi-Fi, etc.)
2. Open TIC-80 and disable the update checker (`CHECK_NEW_VERSION=false`)
3. Turn internet back off
4. Open TIC-80 and observe how it doesn't crash this time

Bug originally reported by ThaCuber on the Discord, I verified it's still an issue as of latest main (`3a4c813`).

**Comment by MineRobber9000** [comment]
I can't quite put my finger on *why* the update checker is causing the crash, but disabling it does fix the issue. I *did* notice that `onHttpVesrsionGet` (sic) doesn't check for a `net_get_error`, but I don't see how it could get a `net_get_done` without the download succeeding.

**Comment by MineRobber9000** [comment]
Actually, after even further probing it seems the issue is that attempting to access the network when there is no network is the cause of the issue. This means that the current build of TIC-80 can potentially crash when:

1. Starting up (`CHECK_NEW_VERSION=true`, update checker calls the network to get the latest version)
2. Attempting to browse the tic80.com portion of surf (calls the network, obviously, to get cart listings/carts)
3. Attempting an export of any kind (calls the network to do the export build on the `tic80.com` server)

**Comment by nesbox** [comment]
fixed with #1890
