### ISSUE TITLE
Cant compile on Arch linux

### ISSUE THREAD

**Issue by mirkokral** [nesbox/TIC-80#1893]
I have got an error on a new Arch Linux installation.
Here is a paste of this error[:](https://www.youtube.com/watch?v=dQw4w9WgXcQ) [https://pastebin.com/raw/XBcbf9mc](https://pastebin.com/raw/XBcbf9mc)
I don't know why this happens

**Comment by joshgoebel** [comment]
Or perhaps that's the wrong string.h entirely?

**Comment by mirkokral** [comment]
Also some more info:
/etc/os-release file:
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```
i use gnome 42 as my desktop
uname -a:
```
Linux mirkopc 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64 GNU/Linux
```

**Comment by mirkokral** [comment]
found binary file of tic80, closing...
