### ISSUE TITLE
everything drawn in OVR with color 0 is transparent

### ISSUE THREAD

**Issue by fachi177** [nesbox/TIC-80#1897]
Why is everything drawn in OVR with color 0 transparent? It is intended?
Also, SCREEN OFFSET works the other way around now, I have to change the signs to make it work like before
you can see these problems in this game https://tic80.com/play?cart=1414

**Comment by joshgoebel** [comment]
See the wiki. You can set the transparent color. One of the colors must be transparent now.

**Comment by fachi177** [comment]
Oh, I just saw them. yes, one of the colors has to be transparent. now only 15 colors can be used in OVR.
I should change the name of my game from Paint32 to Paint31 XD

**Comment by nesbox** [comment]
> Also, SCREEN OFFSET works the other way around now

@fachi177 Does it work differently in both XY directions or just one?

**Comment by joshgoebel** [comment]
@fachi177 Did you try a no color such as 255?

**Comment by potato25** [comment]
How do you set color 0 as not transparent in OVR ?

**Comment by joshgoebel** [comment]
Poke the ovr trans register in VRAM.

**Comment by fachi177** [comment]
> @fachi177 Did you try a no color such as 255?

yes i did, but it only accepts 4-bit color value, you must put a color

> > Also, SCREEN OFFSET works the other way around now
> 
> @fachi177 Does it work differently in both XY directions or just one?

Yes, both. I had to put a minus sign on both of them to fix my game.

**Comment by joshgoebel** [comment]
_Were you poking the full 1 byte register?_ Obviously you can't poke a 8 bit value with poke4. 

I'm pretty sure we handled this case which means the docs are wrong that it's a 4 bit value only.

**Comment by joshgoebel** [comment]
Ping.

**Comment by joshgoebel** [comment]
This used to work as I describe (the register internally **was** 8 bit)... this was broken by the big endian patch though - which turned it into a 4 bit register: 99dc5553.  So now we probably need to decide to just call the register 8 bits truly (allowing you to turn off transparency in vbank1) - or if this is meant to be a new graphics chipset limitation. @nesbox

**Comment by nesbox** [comment]
> this was broken by the big endian patch though 

I don't see that it was broken by the big endian patch, it was 4bit before the 99dc5553bed3c2c71fc9352b28ec2af9ea1067fa
Anyway, TIC-80 uses only first 4 bits to get color info, other 4 bits are unused and it doesn't matter what to call `poke4()` or `poke()` in this case.

**Comment by joshgoebel** [comment]
@nesbox It absolute was 8 bit before. https://github.com/nesbox/TIC-80/commit/99dc5553bed3c2c71fc9352b28ec2af9ea1067fa#diff-c9998e9cc98408138dd404d46a35dc13b28d125c316fcc6200d0e46b40e87d8fL488

Line 488.  **That the register was actually 8 bits was intentional (at least this was always 100% clear to me) - exactly to allow for using all 16 colors in OVR1.**.   The big endianness change was not supposed to change the *behavior* of the engine, so this seems like it would be a bug in any case.

No?

**Comment by nesbox** [comment]
> It absolute was 8 bit before.

No, it was **4 bits** before `u8 border:TIC_PALETTE_BPP;`
where `TIC_PALETTE_BPP == 4`
