### ISSUE TITLE
mouse pointer unconditionally hidden on moving into window

### ISSUE THREAD

**Issue by sinsinpub** [nesbox/TIC-80#1899]
something bugged on mouse input capture? quite a critical visible bug since even can't operate on editors well via mouse 😭 
tested on win 64bit and winxp 32bit, not sure if happens for other builds
before:
![image](https://user-images.githubusercontent.com/160240/166414886-9e00a514-d8cf-44e5-969f-fdef71149b28.png)
after: (can notice pointer is hovering on sprite editor button)
![image](https://user-images.githubusercontent.com/160240/166414943-4ea2ad5e-a314-4298-8acb-2463088a5ad3.png)

**Comment by sinsinpub** [comment]
tried a game using mouse, seems ok for wasm case
![image](https://user-images.githubusercontent.com/160240/166415719-26d7284b-b934-4a33-9e3f-3c1fcd7e5498.png)
so it seems be a custom mouse cursor failure?
![image](https://user-images.githubusercontent.com/160240/166415799-d2caa0fb-faa0-48fe-b98f-998fceb99360.png)

**Comment by nesbox** [comment]
Please check your config, you should have mouse cursors in the sprites area
![image](https://user-images.githubusercontent.com/1101448/166415776-82dbd358-1fcb-49a0-aa35-5ef5b22c1024.png)

or try to reset the config with `config reset` command

**Comment by sinsinpub** [comment]
oh yea, i have copied and used old config folder. that should fix it 👌
