### ISSUE TITLE
Calling pix() function in OVR() to check for color values in TIC() doesn't work anymore ( v 1.0.2164 )

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#1900]
Calling pix() function in OVR() to check for color values of TIC() doesn't work anymore . It used to work in 0.90 before
This broke : [https://tic80.com/play?cart=2695](url)
![test1](https://user-images.githubusercontent.com/56357462/166417020-3d04bee8-8770-4b0d-a14e-c122dcc003a5.png)

**Comment by nesbox** [comment]
It wont work like this scince we added vbank switching.
In your example you clear the screen in the `vbank0` and try to get pixel color in `vbank1`.

**Comment by joshgoebel** [comment]
This would work if they switched back to bank1 first then used pix, right?

**Comment by nesbox** [comment]
yes, this would work if you switched to proper vbank

**Comment by joshgoebel** [comment]
The only problem with this architecture that I don't think I even thought of before is that if you are writing some sort of complex graphic effect that is literally reading every pixel from vram modifying it quickly and then writing it back to OVR vram.  

You could do that kind of thing before but now you have to wrap every single pixel access with two calls to vbank. I guess now I'm curious if anyone is actually doing that kind of thing. 

Personally I don't mind this limitation. It feels retro.

**Comment by joshgoebel** [comment]
> You could do that kind of thing before but now you have to wrap every single pixel access with two calls to vbank.

I forgot if we're still using memcopy internally for vbank switching but if we are that might rule out this type of approach since you'd be copying 64 kB of RAM every time you read a single pixel.

This could be another potential argument for increasing the memory of the base system. In that case one could do this but they'd  first copy VRAM to 32 kB of free memory for easy access.

**Comment by potato25** [comment]
See this : https://github.com/nesbox/TIC-80/issues/1908
I made that cart and now it's broken :(

**Comment by nesbox** [comment]
> I made that cart and now it's broken :(

Unfortunately, sometimes we have to sacrifice backward compatibility as in this case, sience 1.0 you have to specify which [VBANK](https://github.com/nesbox/TIC-80/wiki/vbank) you want to use before calling `pix()` API, sorry for that.
