### ISSUE TITLE
elli () function with Negative Major Radius ( a ) and Positive Minor Radius ( b ) is still being drawn on Screen ( v1.0.2164 )

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#1901]
elli ( x , y , a , b , color ) function with Negative Major Radius ( a ) and Positive Minor Radius ( b ) is drawn on Screen
![test1](https://user-images.githubusercontent.com/56357462/166419047-3f76911b-189b-4449-8be6-05ab6bfa01f9.png)

**Comment by joshgoebel** [comment]
Closing in favor of #1902 (larger example case).
