### ISSUE TITLE
circb () Function and  ellib () Function with Negative Radius is still being drawn on Screen ( v1.0.2164 )

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#1902]
As seen below , it draws circb() function with Negative Radius and ellib () Function either Negative Major Radius ( a ) or Negative Minor Radius ( b )
![test2](https://user-images.githubusercontent.com/56357462/166419591-f7d5aeaa-c3a6-493c-bfdf-0eb6324b114a.png)

**Comment by nesbox** [comment]
#1901 duplicate?

**Comment by joshgoebel** [comment]
Yep, but this has a better example case.  I'll close #1901 and tag this hotfix also.

**Comment by joshgoebel** [comment]
Is this not an issue for `elli` and `circ` also?

**Comment by nesbox** [comment]
fixed here 28354fa1a0a36d41de03a9083e7d96bbe36f33d4
