### ISSUE TITLE
Small screen on mobile

### ISSUE THREAD

**Issue by ginger-brave** [nesbox/TIC-80#1906]
When i updated TIC-80 to 1.0, the screen got smaller, and i'm an android user
Is this a bug or intentional?

**Comment by nesbox** [comment]
I suspect this is integer pixel scaling we enabled by default.
Could you please provide a screenshot to see how much worse it is?

**Comment by ginger-brave** [comment]
![Screenshot_20220503-150502_TIC-80](https://user-images.githubusercontent.com/104861287/166712620-25ebb297-cfb3-41e3-8aae-3f575a364c26.jpg)
The screen looks smaller than before

**Comment by mrcampbell** [comment]
Yeah, I'm having the same issue on the Samsung A42

**Comment by LeonStansfield** [comment]
I too am having this issue on a OnePlus Nord 2.
![Screenshot_2022-05-28-21-55-50-71_ca4b4f20a07efa80f235343e0ee37fcb](https://user-images.githubusercontent.com/23266792/170842616-51553d3c-38c6-47a0-815c-48be45e12c3e.jpg)

**Comment by joshgoebel** [comment]
Closing as dup of #2031.
