### ISSUE TITLE
OVR causes weirdness in pix function

### ISSUE THREAD

**Issue by MineRobber9000** [nesbox/TIC-80#1908]
Somehow, the `OVR` compatibility mode causes issues with the `pix` function, breaking carts that relied on being able to access overlay VRAM with it.

**Steps to reproduce:**
1. Find an affected cart ([this one](https://tic80.com/play?cart=2623) is the one I've been testing with)
2. Run the cart in the web app (using the latest 1.0.2164).

**Expected behavior:**

(captured using 0.90.1723 (9c38a80))

![Cool micro-organism look](https://user-images.githubusercontent.com/12676241/166583958-2047cca4-5a42-4d9c-abbb-2820c949143a.gif)

**What happens instead:**

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/12676241/166584228-1e1fede1-aeb2-475e-871d-73b9fff7cf72.gif)

The only way I've gotten something similar to happen to the cart in 0.90 is by breaking the update function on the cell nuclei (`upd2`). `upd2` uses `pix` extensively for its effects.

**Comment by potato25** [comment]
Yes , i created that cart and opened an issue here : https://github.com/nesbox/TIC-80/issues/1900
It also broke this [https://tic80.com/play?cart=2695](url)

**Comment by nesbox** [comment]
dup #1900

**Comment by joshgoebel** [comment]
@potato25 Could you please show me the segment of source you're using to generate this effect?  (ie, place it here in this issue)

Were you just using `pix()` to read from the default VRAM and then split back out to the previously "magic" OVR layer?  If I know exactly what you're doing it may be easier to help suggest a workaround.
