### ISSUE TITLE
Flashing colors in surf menu

### ISSUE THREAD

**Issue by ginger-brave** [nesbox/TIC-80#1913]
When you open a public game, colors start flashing

https://user-images.githubusercontent.com/104861287/166734153-e91a6234-efde-44ae-9204-be8036995ad7.mp4

**Comment by BuoYancYdabl** [comment]
epileptic-friendly game XD

**Comment by grigoriynikolaev** [comment]
So it isn't a bug, but a feature? Is there a way to turn it off system wide? Not an epileptic, but necessity to squint every time it happens is quit annoying.

**Comment by joshgoebel** [comment]
That looks like the animation boot sequence, but if we aren't shooting the boot screen then we shouldn't be doing the animation.

**Comment by nesbox** [comment]
Looks like a bug
