### ISSUE TITLE
Calling spr without color key crashes

### ISSUE THREAD

**Issue by massung** [nesbox/TIC-80#1915]
Version: 1.0.2164 (Pro)
OS: Linux
Language: Ruby

```ruby
spr 0,0,0
```
In the previous version it raised an exception indicating that the color key parameter was required.

Doesn't crash with Lua.

**Comment by AlecTroemel** [comment]
FWIW I was unable to reproduce this with a recent build off the main branch.

**Comment by sogaiu** [comment]
I tried with 2a662a0ad38514210c313b518f7691aab227c06c.

For `rubymark.tic`, I changed `draw` to be:
```ruby
def draw
  spr 0,0,0
  spr @sprite, @x, @y, 1, 1, 0, 0, 4, 4
end
```

When I ran things via ctrl-r, I got:
```
color must be either an array or a 
palette index (ArgumentError)
user code:27:in draw
user code:95:in TIC
user code:79
```
