### ISSUE TITLE
Broken fullscreen mode

### ISSUE THREAD

**Issue by kevidryon2** [nesbox/TIC-80#1917]
When I try to go to fullscreen on the latest version (v1.0.2164), the whole screen goes black (like what happens to mirkokral), my mouse is trapped within the TIC-80 window (and when I click it disappears), switching to another window doesn't display that window (only black), and my only way to get out of this situation is:

1. Click the TIC-80 window (I can't see my mouse, and the window isn't in the center)
2. Press F11

But then, TIC-80 still thinks I'm in fullscreen mode and has the pixels scaled wrong, but maximizing and de-maximizing the window reverts it to normal.

For information:
 - I use Linux Mint (20.3 Una)
 - I installed TIC-80 through the DEB package
 - I always keep my system updated

**Comment by nesbox** [comment]
dup #1910
