### ISSUE TITLE
Can't utilize Full Screen in Web Browser in Ver 1.0.2164

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#1918]
In Web Browser , when Dev mode is Enabled , when you're running a cart , when you press 'Esc' , it goes into Code Editor , but it also exits Full Screen mode . So , when you're always Editing and Running cart back and forth , you press 'Esc' , which always exists Full Screen Mode

**Comment by nesbox** [comment]
`ESC` is the browser's official key to exit full screen mode, and I'm pretty sure there's no way to turn it off.
I suggest you use `F1 F2 F3 ...` keys to exit a running game in dev mode.

**Comment by potato25** [comment]
Yes , it works . Thanks :)
