### ISSUE TITLE
print returns text width in pixel and prints

### ISSUE THREAD

**Issue by parlortrickss** [nesbox/TIC-80#1919]
Hello, I have noticed that when use print to return the pixel width of the string its printing, it also prints the string to screen. I am unsure if this is correct behavior, I was expecting it to not print and just give the pixel width.

I am using Fennel to do this.

**Comment by joshgoebel** [comment]
This is correct. Print always prints.

**Comment by nesbox** [comment]
Try to print text outside of the screen if you need only width.
