### ISSUE TITLE
Indent/Unindent no matter where you are on the line

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#192]
The problem with intending in TIC-80 is that to intend/unintend a line, you must first get to the first column of it which depending on the user's skill with the keyboard may generate too many additional keystrokes and make it slower to type in general.

To that end, I propose adding following shortcuts to the editor:
- Ctrl+Tab will intend current line no matter where you are in it, as opposed to tab which would just insert a tab character at the current column.
- Ctrl+Shift+Tab will unintend current line by one tab. If it isn't intended already, it will do nothing.

**Comment by frenetic** [comment]
@nesbox or @darkhog: this issue was fixed. Please, close it.
