### ISSUE TITLE
Experimentation with RAM

### ISSUE THREAD

**Issue by sorucoder** [nesbox/TIC-80#1920]
I know on the wiki it says that scripted cartridges are not intended to read or write memory outside of memory-mapped IO, but through experimenting, it seems to work regardless. My process was to create some variables, copy sprite and tile data from their memory-mapped IO buffers to various places (i.e. beyond the defined memory mapped IO, beyond 96k, and beyond 256k), copy it back, and sync it to the cartridge. I'm personally considering using this technique to have a copy of the clean tiles so that I can modify tiles on the fly. With that said, I have the following questions:
1. Should this be possible in scripted cartridges? The reason I ask is because it does seem to violate one of the mantras of TIC-80 (i.e. being a tool to make tiny retro games). If this is problematic to that ideal, should reading or writing to that memory overwrite the other banks, or even runtime variables?
2. What are the true address and size limitations, if any? I haven't experimented further than 272k, but I would imagine a segmentation fault may occur reading/writing to unreasonable addresses or sizes.

**Comment by joshgoebel** [comment]
This shouldn't be possible.   Unless @nesbox changed things there is ony 96kb of MMIO RAM for scripting runtimes, with only the WASM runtime having access to a full 256kb.  That memory is simply not allocated for the other runtimes.

Reading and writing past 96kb (or 256kb) is really a security issue and something we need to fix.

**Comment by joshgoebel** [comment]
Now I'm already on record as saying I think the full 256kb should be opened up for all runtimes (to allow copying RAM around to do advance things with graphics)... but time will tell...

**Comment by joshgoebel** [comment]
@sorucoder Can you provide your script here that you were using to access out of bounds RAM?

**Comment by joshgoebel** [comment]
Closing this issue until a reproducible example can be provided.  More than happy to reopen when we have sample code to review/test.

**Comment by sorucoder** [comment]
So, I used this script to test what I opened this issue recently:

```
-- title:   game title
-- author:  game developer, email, etc.
-- desc:    short description
-- site:    website link
-- license: MIT License (change this to your license of choice)
-- version: 0.1
-- script:  lua

local step=0
local done=false
local TILES=0x04000
local RAM=0x18000
local END=0x40000

function draw()
 cls(0)
 spr(1,0,8,-1,1,0,0,2,2)
end

function TIC()
 if not done then
  if step==0 then
   trace("Copying tiles to RAM")
   memcpy(TILES,RAM,8192)
  elseif step==1 then
   trace("Erasing tiles")
   memset(TILES,0,8192)
  elseif step==2 then
   trace("Moving RAM to tiles")
   memcpy(RAM,TILES,8192)
   memset(RAM,0,8192)
  elseif step==3 then
   trace("Copying tiles to end")
   memcpy(TILES,END,8192)
  elseif step==4 then
   trace("Erasing tiles")
   memset(TILES,0,8192)
  elseif step==5 then
   trace("Moving end to tiles")
   memcpy(END,TILES,8192)
   memset(END,0,8192)
  end
  done=true
 elseif btnp(4) then
  step=step+1
  if step>5 then
   step=0
  end
  done=false
 end
 
 draw()
end

-- <TILES>
-- 001:eccccccccc888888caaaaaaaca888888cacccccccacc0ccccacc0ccccacc0ccc
-- 002:ccccceee8888cceeaaaa0cee888a0ceeccca0ccc0cca0c0c0cca0c0c0cca0c0c
-- 003:eccccccccc888888caaaaaaaca888888cacccccccacccccccacc0ccccacc0ccc
-- 004:ccccceee8888cceeaaaa0cee888a0ceeccca0cccccca0c0c0cca0c0c0cca0c0c
-- 017:cacccccccaaaaaaacaaacaaacaaaaccccaaaaaaac8888888cc000cccecccccec
-- 018:ccca00ccaaaa0ccecaaa0ceeaaaa0ceeaaaa0cee8888ccee000cceeecccceeee
-- 019:cacccccccaaaaaaacaaacaaacaaaaccccaaaaaaac8888888cc000cccecccccec
-- 020:ccca00ccaaaa0ccecaaa0ceeaaaa0ceeaaaa0cee8888ccee000cceeecccceeee
-- </TILES>

-- <WAVES>
-- 000:00000000ffffffff00000000ffffffff
-- 001:0123456789abcdeffedcba9876543210
-- 002:0123456789abcdef0123456789abcdef
-- </WAVES>

-- <SFX>
-- 000:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000304000000000
-- </SFX>

-- <TRACKS>
-- 000:100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
-- </TRACKS>

-- <PALETTE>
-- 000:1a1c2c5d275db13e53ef7d57ffcd75a7f07038b76425717929366f3b5dc941a6f673eff7f4f4f494b0c2566c86333c57
-- </PALETTE>
```

And it seems to not work the way it did. So I guess it's fixed now.
