### ISSUE TITLE
¿porque no me abre TIC 80 1.0.2164 compilado manualmente?

### ISSUE THREAD

**Issue by eggbanana173** [nesbox/TIC-80#1924]
he compilado TIC 80 1.0.2164 sin errores pero cuando lo abro me sale esto:

> C:\Users\Personal\TIC-80\build\bin>tic80
error: folder `C:\Users\Personal\AppData\Roaming\com.nesbox.tic\TIC-80\` doesn't exist

¿Cómo se soluciona esto?

**Comment by NeoLight1010** [comment]
**Translation**

> # Why can't I open manually-compiled TIC 80 1.0.2164?
>
> I compiled TIC 80 1.0.2164 with no issues, but when I open it, I get this:
>
> > C:\Users\Personal\TIC-80\build\bin>tic80
> > error: folder C:\Users\Personal\AppData\Roaming\com.nesbox.tic\TIC-80\ doesn't exist
>
> How do I solve this?

**Comment by nesbox** [comment]
What about released version, does it work?

**Comment by nesbox** [comment]
Do you have a debugger to investigate the reason?

**Comment by eggbanana173** [comment]
lastimosamente no, ¿pero tu tienes uno para yo analizarlo?

**Comment by eggbanana173** [comment]
sospecho que es el sistema de análisis de la carpeta  "\com.nesbox.tic\TIC-80\" no este funcionando correctamente

**Comment by aliceisjustplaying** [comment]
Fixed in #2558
