### ISSUE TITLE
Window freezes if dragged onto extended desktop (Win10)

### ISSUE THREAD

**Issue by eglavas** [nesbox/TIC-80#1927]
Connected to a TV via HDMI, extended desktop onto it. Dragging TIC to extended desktop freezes the TIC window (no updates shown, even the cursor doesn't blink), but keypresses are logged and are displayed when dragged back to primary display. 

This doesn't happen with 0.90, but does with 0.80.

**Comment by joshgoebel** [comment]
Closing. (no response)

If  confirmed this is an issue with the latest 1.0 release, this can be reopened.
