### ISSUE TITLE
TIC-80 Pro version is broken on Linux

### ISSUE THREAD

**Issue by BlueTheBZR** [nesbox/TIC-80#1929]
Hi! I purchased the pro version recently and i'm having a serious issue with the program.

When i try to run **TIC-80 Pro** in Debian GNU/Linux it instantly fills the whole screen and gets trapped, i can't even use the program or write any commands, and i have to quit via terminal.

This happens always when i try to execute the pro version, i tried with both the .deb package and the x86_64 executable in the Linux zip file, so i had to return to the standard version.

There is a similar issue in the standard version when i pressed the the **F11** key, where it cause the same scenario, and makes the standard version unusable too.

As i said, this has occurred to me only in Linux, Android version runs well so far for me, i have to tested on Windows to see if something similar happens.

**Comment by parlortrickss** [comment]
Adding my twocents, i do not have this issue on Manjaro Linux. Running the Tic80 Pro from itch.io worked flawlessly, same as v.90. Im running 1.0.2164 Pro (b09c50c)

**Comment by BlueTheBZR** [comment]
I have tried  building version 1.0.2151-dev Pro ([d1b42d5](https://github.com/nesbox/TIC-80/commit/d1b42d5240bb1eb0a85c6af9e2f35c3e6e9c4be2)), and it works well, and **F11** does not hang the program anymore, but the issue still happens with the 1.0.2164 Pro .deb package and the x86_64 executable, in my last test, it also starts with the CRT filter activated, something that did not happened before.

**Comment by BlueTheBZR** [comment]
> I have tried  building version 1.0.2151-dev Pro ([`d1b42d5`](https://github.com/nesbox/TIC-80/commit/d1b42d5240bb1eb0a85c6af9e2f35c3e6e9c4be2)), and it works well, and **F11** does not hang the program anymore, but the issue still happens with the 1.0.2164 Pro .deb package and the x86_64 executable, in my last test, it also starts with the CRT filter activated, something that did not happened before.

I add this picture i took while trying to run the program, this is how it looks, and i can't do anything else after executing it...

![IMG_20220519_190745.jpg](https://user-images.githubusercontent.com/101472580/169429139-dfcc3220-a8a1-4341-a382-e38793cd5db7.jpg)

**Comment by BlueTheBZR** [comment]
Alright, looks like the bug only happens when i press `F11` once, and keeps happening after that every time i run the app,  i solved the problem by deleting the `com.nesbox.tic` folder, and it works again, but the issue comes back if i pressed the `F11` key, so it's still something that bothers me, at least i can use TIC-80 Pro now.

**Comment by ChildishGiant** [comment]
See #1577

**Comment by fabmars** [comment]
Solved here on Ubuntu with F11, or deleting .local/share/com.nesbox.tic
