### ISSUE TITLE
Add buttons to toggle channels on/off in music editor

### ISSUE THREAD

**Issue by Bentic** [nesbox/TIC-80#193]
Music editor suggestion:
Adding a button next to the pattern number selector of each channel to toggle it on or off (mute) for the current frame. It would keep the current number and keep the pattern visible but greyed out, instead of having to set it to 0 and remember which pattern was there before.

Extra suggestion: Ctrl or Shift + clicking these buttons would solo the channel (mute the other channels)
Extra suggestion 2: Ctrl or Shift + clicking a soloed channel will unmute the other channels based on their previous mute state (previously muted/off channels wouldn't be turned on again).

**Comment by nesbox** [comment]
added on/off channel tumblers
![image](https://user-images.githubusercontent.com/1101448/30977357-fc6566ca-a47f-11e7-88d9-31adae919dfa.png)

also, it will solo the channel if CTRL is pressed
