### ISSUE TITLE
WinXP version lagging so much

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#1934]
I just checked and tested two versions on i9 rtx 3060 32gb ram. Win version works fine no matter what. WinXP version starts to lag without almost anything. On my pc I cant use original win version. I can send you my "benchmark" if you want see yourself how its laggy in discord.

Checking GPU and CPU
writing (30x16)x6 sprites, every layer (6) applies its own moving rules

Results: 
Win version - 60 fps
WinXP version - 22 fps

**Comment by BuoYancYdabl** [comment]
UPD: Win version works on win7 only when game exported with alone=1.

**Comment by nesbox** [comment]
It lags because winxp version is built without GPU support, I think.

**Comment by BuoYancYdabl** [comment]
> It lags because winxp version is built without GPU support, I think.

is that issue will be fixed? Anyway Im closing this issue!
