### ISSUE TITLE
The version 1.0 Does not open on android 4.4, Please fix this

### ISSUE THREAD

**Issue by T15OFT** [nesbox/TIC-80#1937]
The version 1.0 Does not open on android 4.4, Please fix this

**Comment by T15OFT** [comment]
The version 1.0 Does not open on android 4.4, Please fix this

**Comment by T15OFT** [comment]
The version 1.0 Does not open on android 4.4, Please fix this

**Comment by joshgoebel** [comment]
Did the prior version?

**Comment by nesbox** [comment]
The reason is in SDL2 library we use to render, which requires at least Android SDK 24 which is Android 7.0
