### ISSUE TITLE
Multiple TIC-80 glitches

### ISSUE THREAD

**Issue by 100xCode** [nesbox/TIC-80#1939]
# Glitch 1
I'm making a game and run this code:
```moonscript
plyr = {
 x: 118
 y: 124
 num: 256
 spd: 1
 blt: {
  x: 0
  y: 0
  len: 5
  clr: 4
  spd: 2
 }
}
export TIC = ->
 cls!

 if btn 2 and plyr.x > 0
  plyr.x = plyr.spd
  plyr.num = 258
 if btn 3 and plyr.y < 232
  plyr.y = plyr.spd
  plyr.num = 257
 else
  plyr.num = 256
 
 if btn 4
  plyr.blt.x, y = plyr.x, y

 spr plyr.num, plyr.x, plyr.y
```
The third `if` statement messes everything up. Suddenly, the edge collisions don't work and the sprite only responds to the 0 (up) key. However, if you run the code using only the first two `if` statements, edge collisions work and left and right keys respond. Very annoying and confusing.
# Glitch 2
If I copy, delete or paste something in the TIC-80 code editor (`⌘`/`⌃`+`C`,`Backspace`/`Del`,`⌘`/`⌃`+`C`), and then press `⌘`/`⌃`, it does the hotkey's function multiple times over. It filled up my memory very fast and I was left with the *pleasure* of erasing ALL of it. (that part was easy though because I could just drag down to go the end of the line but regardless)

**Comment by another-m00** [comment]
The 1st one is a coding glitch, it usually doesn't have to do anything with TIC80 itself.

The 2nd one on the other hand is actually a quite big problem that I experienced already, TIC80 takes up 80% of the memory because you push the cut or copy key sometimes while selecting the whole code.

**Comment by 100xCode** [comment]
Thanks,  I figured the first one out a while ago. Maybe we ask @nesbox to fix the `⌘`/`⌃`+`some shortcut key` problem.
