### ISSUE TITLE
Font support in 2-bit and 1-bit

### ISSUE THREAD

**Issue by parlortrickss** [nesbox/TIC-80#1952]
In 4-bit the letter A starts at sprite #321, but where does it start for 2-bit and 1-bit sprites?

**Comment by soxfox42** [comment]
It uses the system described at https://github.com/nesbox/TIC-80/wiki/blit-segment, although it swaps the FG and BG pages which seems to be a backwards compatibility detail.

If you're using the simplified blit segment values, A is located at sprite 641 in 2bpp mode, and sprite 1281 in 1bpp mode. The individual pages don't have continuous sprite indexes though, as the indexes continue across the entire wider spritesheet. The easiest way to handle that is just to put them at the same position as you normally would in the sprite editor, and ignore the sprite numbers.

**Comment by parlortrickss** [comment]
thank you, i have worked it out with your help
