### ISSUE TITLE
Is it possible to create a tic-80 apk directly launching your game ?

### ISSUE THREAD

**Issue by Darenn** [nesbox/TIC-80#1953]
I know there is a tic-80 apk available and that people can surf to get games on the website.
But I would like to have my own apk launching my game (and post it on my store).

Is it possible to create a tic-80 apk directly launching your game ?

Thanks !

**Comment by nesbox** [comment]
It's possible but requires some input on your part, we have [src/system/sdl/player.c](https://github.com/nesbox/TIC-80/blob/main/src/system/sdl/player.c) which can play carts, you can build it for Android and create your own .apk with the game.

**Comment by Darenn** [comment]
Thanks for your help @nesbox.
I've looked at the file and I'm not sure what is the procedure to follow.
I've never used SDL or built .apk before.

Would it be possible to have an example or a link to some resources ?

**Comment by Darenn** [comment]
Oh maybe do you mean I should change the default cart, and rebuild tic-80 for android ?

**Comment by nesbox** [comment]
It's not an easy task, you can look at how we build TIC-80 for Android using Github Actions https://github.com/nesbox/TIC-80/blob/main/.github/workflows/build.yml#L530 and do the same for your project but based on `player.c`.

**Comment by Darenn** [comment]
Made a few attempts to build the thing after installing gradle and the android sdk but it's really a thing I don't know anything about.

Might try again later if the need for a mobile version of my tic-80 game is really arising.

But it's too bad ! Mobile experience is all about ease of use and the current way to get a specific game working with tic-80 on your phone is tedious.

I don't know if it's possible or already in the works but being able to export an apk would be great !

In any case, thanks again for your help I really appreciate it.

**Comment by Darenn** [comment]
Hello !
Regarding this issue, for a first version I would like to have an android version of my game downloadable from my itch page.
The folder would contain the tic-80 apk you are distributing on github, the cart of my game and instruction on how to install and launch my game on a Android phone.
Knowing that my game is not free, is this a problem to sell a game with your tic-80 apk in the files ?
Thanks !

**Comment by nesbox** [comment]
> is this a problem to sell a game with your tic-80 apk in the files ?

I don't think this is a problem, you just need to mention a link to the TIC-80 repository (or creators) in the description because we have MIT license.

**Comment by Darenn** [comment]
Ok thanks !

**Comment by BuoYancYdabl** [comment]
> > is this a problem to sell a game with your tic-80 apk in the files ?
> 
> I don't think this is a problem, you just need to mention a link to the TIC-80 repository (or creators) in the description because we have MIT license.

so you can actually sell in-tic built games with mentioning what is TIC-80 and, ofcourse, you as a developer of tic?
