### ISSUE TITLE
Add pixel mouse cursors instead of using the default OS ones.

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#1955]
So you can make your custom ones via config, but I would prefer if there were built-in ones. I am attaching my config.tic in which I made ones that I believe are quite decent.
[config.zip](https://github.com/nesbox/TIC-80/files/8885523/config.zip)

**Comment by nesbox** [comment]
We have pixel mouse cursors in 1.0
![image](https://user-images.githubusercontent.com/1101448/173790447-eb961ea8-15c3-4d6c-be92-99d3394bbfd7.png)

**Comment by BuoYancYdabl** [comment]
> So you can make your custom ones via config, but I would prefer if there were built-in ones. I am attaching my config.tic in which I made ones that I believe are quite decent. [config.zip](https://github.com/nesbox/TIC-80/files/8885523/config.zip)

To hide or show built-in cursor type in command line "help vram", find mouse cursor and try poking it till it be nothing.
