### ISSUE TITLE
Really easy "hacking"

### ISSUE THREAD

**Issue by r-gt** [nesbox/TIC-80#1963]
if you go to the URL of a game and replace "play" with "add" you can modify carts that are not yours

![image](https://user-images.githubusercontent.com/73716729/173973777-e0226627-3164-4c8f-a5d1-7dd2f743dfa3.png)

**Comment by r-gt** [comment]
wait. the website is down

**Comment by nesbox** [comment]
Actually, we check the user and you can't update someone else's cart, but you can see the `/add` page :)
I'll fix it soon, thanks for the report.

**Comment by nesbox** [comment]
fixed
