### ISSUE TITLE
Fullscreen breaks TIC-80

### ISSUE THREAD

**Issue by cacilhas** [nesbox/TIC-80#1966]
I enabled TIC-80 fullscreen flag, and since then, TIC-80 doesn’t grab focus anymore.

So I’m not able to disable fullscreen, since TIC-80 simply doesn’t communicate with keyboard or mouse.

How do I reset TIC-80 configurations?

Please don’t say I have to run `config reset`,’cause it’s impossible to do it if TIC-80 doesn’t recognise keyboard anymore.

**Comment by cacilhas** [comment]
I figure out how to reset settings:

```sh
rm -rf ~/.local/share/com.nesbox.tic
```

However, the fullscreen issue still exists: enabling fullscreen, TIC-80 stops grabbing focus on Linux.

**Comment by BuoYancYdabl** [comment]
If you wonder you can delete config file from User/AppData/Roaming/com.nesbox.tic/TIC-80/.local (I hope the path is correct). After launching without config it will automatically create new one

**Comment by nerddude24** [comment]
I also have the same problem (Arch Linux 64bit)

**Comment by nesbox** [comment]
dup of #1910
