### ISSUE TITLE
Customized ROM folder

### ISSUE THREAD

**Issue by massung** [nesbox/TIC-80#1978]
Perhaps this is already possible but I haven't found it in the documentation. But I'd very much like to be able to specify (via environment variable or dot file?) what the ROM folder used is.

I would love for it to be a Dropbox folder. Instead, my workflow currently is to do some work, save, open folder, copy to Dropbox, then on another machine copy from Dropbox to local ROM folder, then load, rinse and repeat.

Obviously GitHub is an option, but thought this feature would be useful for others as well.

**Comment by Anrock** [comment]
You can use a symlink until this option is implemented, I guess.

**Comment by nesbox** [comment]
I think you can use `--fs <path>` command line argument to assign your own folder.
More info is here https://github.com/nesbox/TIC-80/wiki/Command-line-arguments
