### ISSUE TITLE
"help =" crashes tic-80

### ISSUE THREAD

**Issue by Martsadas** [nesbox/TIC-80#1980]
![image](https://user-images.githubusercontent.com/48686725/178351881-c25b804c-e58c-46f1-a514-6a17303b6a16.png)
it doesn't crash in the online version but it crashes in the downloaded version

**Comment by pythonmcpi** [comment]
Can reproduce using the Windows (regular) build from Github Actions Build https://github.com/nesbox/TIC-80/issues/954.

**Comment by sogaiu** [comment]
It happened for me with: https://github.com/nesbox/TIC-80/releases/download/v1.0.2164/tic80-v1.0-win.zip

But a locally built version based on eb4e331455d8d3c0512f3d57a2d9daa61b96ff4b didn't exhibit this behavior here.

**Comment by nesbox** [comment]
fixed with #2057
