### ISSUE TITLE
Bug: Bookmarks "sticks" the code position

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#1986]
**Issue**
Sometimes when you have bookmarks, you can use the other part of code not marked by bookmarks. And for some reason after you open sprite or map editor and then go back your code editor position will be on one of this bookmarks. It sets which bookmark it will stick to by random. I had 2 bookmarks and after going back and forth between editors my code was randomly jumping between this two bookmarks.

**How to recreate**
1) Put bookmark anywhere you want;
2) Scroll somewhere else, write some code so the pointer will define its new position;
3) Open map or sprite editor, choose diferent sprites by pointer or do something;
4) Go back.
You'll see pointer is now on the bookmark and not where it was supposed to be.

**Comment by TimotheeGreg** [comment]
That's due to using F1 to switch to code editor. That's true also when you switch from game to code editor with Esc+F1.
And when you have several bookmarks it will move to the next bookmark each time.
