### ISSUE TITLE
Bug: vbank(1) doesnt draw colour 0

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#1989]
For some reason when using vbank(1) the black (0) colour skips its drawing. Check the bug.tic I sent, I draw 1 sprite 4 times, 2 with 0vbank and 2 with 1vbank. Also any text works fine except the black one, it dont show at all. Here is [cart](https://tic80.com/add?cart=671) Works on PC, Web. TIC-80 v1.0.2164 Pro (bougth)
UPD: I actually think this happens because when you call cls() in vbank1 you dont want to clear whole screen so 0 colour is set to 0. But in other cases you need draw something with 0 colour it wont show up because it set as transparent by default.

**Comment by BuoYancYdabl** [comment]
If it is a bug, tell me and Ill avoid using vbank() for now. If its me doing something wrong - also tell me, please!

**Comment by BuoYancYdabl** [comment]
I come with idea that using vbank1 to draw whole stuff (map, primitives, text etc) is definetly not best idea. Its better to do trought vbank0

**Comment by BuoYancYdabl** [comment]
Guess it is similar to #1897

**Comment by joshgoebel** [comment]
This is the correct behavior, one of the colors is going to be transparent - that's how bank1/OVR works...  bank1 is just a way to jump into OVR mode outside of OVR...  The transparent color is 0 by default.  But you could try setting it to 255 (ignoring the docs) and see if that works.  IIRC it does... and let us know and we can update the wiki accordingly.
