### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by NaH3** [nesbox/TIC-80#1994]
is just says 
"The procedure entry point GetSystemTimePreciseAsFiletime could not be located in the dynamic library KERNEL32.dll"

**Comment by BuoYancYdabl** [comment]
Use winxp version! This might happen because you using PC with integrated GPU to CPU

**Comment by NaH3** [comment]
im also in windows 7 ultimate 32bit

**Comment by BuoYancYdabl** [comment]
> im also in windows 7 ultimate 32bit

Thats definetly the windows version. Im using Win7 64 Max and have same issue. You only able to use winxp version. And you can youse exported win versions, but they might bug a lot, so im not recomening to do that. I hope I helped you!

**Comment by NaH3** [comment]
welp i just wanted to install tic80
