### ISSUE TITLE
`help cls` does not show help for `cls(...)` api function

### ISSUE THREAD

**Issue by jmdejong** [nesbox/TIC-80#1996]
When running `help cls` in the console it shows only the help for the `cls` command, but not for the `cls(...)` api function.
The existence of the command hides the help for the api function. This is annoying since the function has an argument that is now undocumented from the help.

**Comment by joshgoebel** [comment]
<img width="1136" alt="Screen Shot 2022-12-17 at 1 19 42 PM" src="https://user-images.githubusercontent.com/6473/208255897-d421eefa-f0f2-4e42-b567-6d6a5eb5b837.png">
