### ISSUE TITLE
Fullscreen breaks everything.

### ISSUE THREAD

**Issue by nerddude24** [nesbox/TIC-80#1999]
When i go into fullscreen by pressing F11, TIC-80 stops taking input and i just get stuck looking at the blinking cursor of the console and im forced to restart my pc.

_I'm using Arch Linux btw._ 

It seems the same problem is occuring here #1966

**Comment by paul59** [comment]
This seems to be a long-standing issue on Linux. I have the same problem with 1.0.2164 Pro on MX Linux - going fullscreen draws just a part of the display in the top left of the screen and locks the PC completely necessitating a reboot.

**Comment by nerddude24** [comment]
It looks like the problem is fixed when i built from source (2241-dev build).
