### ISSUE TITLE
ui not appearing in Lubuntu (BadWindow)

### ISSUE THREAD

**Issue by dcaillia** [nesbox/TIC-80#2006]
I'm on Lubuntu 20.04 LTE.

I started tic80 a couple of times successfully.

Then i toggled window un/decorate (a generic menu item on any window in lubuntu).
Then i tried "tic80 --fullscreen"

Since then i'm no longer able to run tic80 at all.

In this log ~/.config/lxqt/debug.log i see lines like this appearing whenever i try to run tic80

2022-08-13 03:19:39.691 (0x7ffe0936a5d0) Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 22508, resource id: 41943054, major code: 3 (GetWindowAttributes), minor code: 0
2022-08-13 03:19:39.691 (0x7ffe0936a5d0) Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 22509, resource id: 41943054, major code: 2 (ChangeWindowAttributes), minor code: 0

I do see a window flashing and then disappearing again.

On the shell where i started tic80, i get this

 TIC-80 tiny computer
 version 1.0.2164 (b09c50c)
 https://tic80.com (C) 2017-2022

 hello! type help for help

>

which looks like a prompt but whatever i type there nothing happens.

I uninstalled and reinstalled tic80 to no avail. 

It looks like lxqt remembers something invalid about this programs window. Not sure what or how. I even copied /usr/bin/tic80 into a different filename in a different place to no avail: same effect, same lxqt logging.

**Comment by franalbani** [comment]
I'm having the same problem, but after running a second instance of `tic80`.

I found a way to make it work again:

```console
mkdir /tmp/tic_80
tic80 --fs=/tmp/tic_80/
```

So it seems the default **file system folder** was corrupted.

Digging deeper: erasing `~/.local/share/com.nesbox.tic/TIC-80/.local/` solved it and allowed me to recover my working files.
(Be careful because it may be confusing depending on how accustomed you are with Linux: I just deleted the last `.local` folder; the inner one)

**Comment by dcaillia** [comment]
Thanks, that solves the problem.

So narrowed down: in lubuntu, using 1.0.2164 (b09c50c): 
when i start with --fullscreen it's broken (ui is not appearing). 
Then no matter how i restart it stays broken. 
Only after clearing ~/.local/share/com.nesbox.tic/.local i get it working again.

**Comment by nesbox** [comment]
dup #1910
