### ISSUE TITLE
joystick code breaks between two revisions

### ISSUE THREAD

**Issue by brickviking** [nesbox/TIC-80#2012]
I noticed some of the buttons on my Logitech F310 Gamepad not working (Down, Left and Right) though the rest (Up, A/B/X/Y, Back) work as expected. I used controller-test-cart.tic to do the testing, the results I got are below:

| Dpad/Leftstick | v1.0-2169-dev Pro | v1.0-2185-dev Pro |v1.0-2245-dev Pro |
|------------------|----------------|------------------|-|
|Up| yes | yes |yes|
|Down| yes |  no | no |
|Left | yes | no |  no |
|Right | yes | no |  no |
|Right side buttons|||
|A| yes| yes | yes |
|B| yes| yes | yes |
|X| yes| yes | yes |
|Y| yes| yes | yes |
|Back| yes| yes | yes |

Keyboard keys all work as expected. I did some tracking down of this, and commits are as follows:

* d1ec07adbe0df1325e4dcf46441a4179b5264f1e  (v1.0-2169-dev) works.
* 681f18c0f477e7d7b5b4fea4e330c44028afd34c  (v1.0-2185-dev) doesn't.
* all revisions after this point have the same joystick problem.

It would seem that the next revision (681f18c) added a whole lot of stuff related to endianness, and I'm rather wondering if the problems with the joystick relate to that at all? The commit message shown is listed as "Merge pull request from #1943 from phcoder/osx-ppc-rb-main".

v1.0-2245 was tested on both a Fedora 28 machine and a Ubuntu 22.04 machine, and I got the same results in each case.

**Comment by jacekjarosz55** [comment]
Can confirm the same thing happening with xbox 360 wireless controller on Arch linux

**Comment by nesbox** [comment]
fixed here 14ed85dbf1a0b4eb0605b242fe5fd2a65b9b00c3
