### ISSUE TITLE
Android Touch Drags Path

### ISSUE THREAD

**Issue by Gabby-Paolucci** [nesbox/TIC-80#2014]
On Android, using touch, the path of the curser travels from where was touched last to the new location while clicking. What this means is that drawing sprites is nearly impossible—you cannot edit a pixel at a time, only in lines as you move towards the center of the sprite.

I'm wondering if we could get the cursor to not select while traveling, to match the normal behavior in touch environments. 

Here's a capture of the effect in action, where I'm trying to draw individual pixels but get lines of travel:
![capture](https://user-images.githubusercontent.com/2521281/190029990-2b5edf23-3bd4-437e-ac23-e037bbcc31cf.gif)

**Comment by potassium-shot** [comment]
It seems to only happen when the finger goes outside the drawing area while still being down. I'll try to investigate the code for a potential fix if I find enough time

**Comment by sogaiu** [comment]
Possibly related:

* https://github.com/nesbox/TIC-80/issues/2269
* https://github.com/nesbox/TIC-80/issues/2270

If it's the same, [nesbox may have addressed it](https://github.com/nesbox/TIC-80/issues/2270#issuecomment-1691709246).

**Comment by potassium-shot** [comment]
The issue does resemble a lot #2269, but it definitely still occurs on the latest version on Android. ([1.1.2736](https://github.com/nesbox/TIC-80/releases/tag/v1.1.2736), even-though it says 1.1.2739 in the app)

**Comment by Gabby-Paolucci** [comment]
I'm on 1.1.2838 and this issue has been resolved, so I'm going to close this.
