### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [nesbox/TIC-80#2015]
oh well nevermind you have artifacts for the 32bit version that even work on windows XP... very good! :)
sorry i didnt noticed, but can you adjust the releases so that it says that those "windows ones" are 64bit?

**Comment by Lucretiel** [comment]
Just FYI to the maintainers of this project that OP has a history of making largely inflammatory and unconstructive requests for 32 bit architecture support and a bizarre crusade against 64 bit software (see https://github.com/melonDS-emu/melonDS/issues/1296, for example)

**Comment by MyTDT-Mysoft** [comment]
> Just FYI to the maintainers of this project that OP has a history of making largely inflammatory and unconstructive requests for 32 bit architecture support and a bizarre crusade against 64 bit software (see [melonDS-emu/melonDS#1296](https://github.com/melonDS-emu/melonDS/issues/1296), for example)

thats your opinion... but i value 32bit... just like you value your mother... and theres nothing wrong with that... so stop calling bullshit on my requests... i guess i'm getting a bunch of fans :), and they are NEVER unconstructive... and the only reason they are inflammatory is because nonsense people like you keep putting fire and try to gang-group against me... like if you were a bunch of sports idiots... trying to bullying the nerd guy...

**Comment by MyTDT-Mysoft** [comment]
thanks :)
