### ISSUE TITLE
html version: running a ruby cart crashes next run

### ISSUE THREAD

**Issue by ErmineII** [nesbox/TIC-80#2017]
to reproduce:

- open up TIC-80 for example at https://tic80.com/create
- open a ruby cart (for example `new ruby`)
- run it, then close it
- then, on any cart (ruby or not):
- run it

[Screen recording 2022-09-29 11.39.24.webm](https://user-images.githubusercontent.com/65429969/193076709-8aa27eb3-ec06-4a3f-b3b6-428d4449152b.webm)

tested on chrome and mobile and desktop firefox.

**Comment by nesbox** [comment]
fixed here da47a99951824d5b0295a8f6f48e35cd1c442b76
