### ISSUE TITLE
Exports based on forks or local builds?

### ISSUE THREAD

**Issue by AlecTroemel** [nesbox/TIC-80#2018]
I'm in the process of adding Janet lang support to tic80, heres the working fork+branch https://github.com/AlecTroemel/TIC-80/tree/charlotte_janet_support

As part of all this I've been trying to export carts using my local build (both to test things out, and also to just use janet in games before things are merged in). However, these builds (both native linux and html) end up using different builds of tic80! This was surprising to me at first, but digging through the source it seems like tic80 is doing a net request to `tic80.com/exports/<VERSION>/<TARGET>` to get the "build" of the target. 

is there any way to do this all off my local build? Or even use the builds made by my forks github actions? 

thanks!

**Comment by joshgoebel** [comment]
You might want to start here: https://github.com/nesbox/TIC-80/blob/main/.github/workflows/build.yml#L553

**Comment by nesbox** [comment]
> is there any way to do this all off my local build?

As option you could start your own local webserver, change `#define TIC_HOST "tic80.com"` to your own, then unzip all the files from the `tic80-export.zip` artifact to `localhost/exports/<VERSION>/` folder.
I don't other variants atm
