### ISSUE TITLE
Inconsistent delta

### ISSUE THREAD

**Issue by darltrash** [nesbox/TIC-80#2024]
I've noticed that all my old games run much much slower in the new versions of Tic80, which I noticed was caused by my delta number generator which looks like this:

```lua
local delta, last = 0, time()

function TIC()
   local now = time()
   delta = now - last
   last = now

   -- ...
end
```

Not only that, But I've also noticed that by changing the CPU power modes in Linux (like from power-save to full-power), the delta also changes drastically, making it essentially useless.

I am using Fedora 36.

**Comment by darltrash** [comment]
I would recommend using sokol_time.h and probably implement a delta() function or make the first argument of TIC() be delta

**Comment by joshgoebel** [comment]
It would be better to rely on delta frames (frame count) than delta time. But the time issue already has an issue open. Time is pretty much broken completely on Linux and some platforms. 

When it's fixed the games will likely work again.

**Comment by joshgoebel** [comment]
Closing as a dup of #1904.
