### ISSUE TITLE
Screen offset backward compatibility was lost in TIC-80 1.0.2164

### ISSUE THREAD

**Issue by mieki256** [nesbox/TIC-80#2028]
In TIC-80 1.0 and TIC-80 0.90, 0.80, 0.70, the plus and minus screen offset values are reversed.

Is this a specification? Or is it a bug?

This text has been converted by an automatic translation service.

## Operating environment

TIC-80 1.0.2164 / 0.90.1723 / 0.80.1344 / 0.70.6 + Windows10 x64 21H2

### Check for screen offset value in x-direction.

```lua
t=0
x,y=96,24

function TIC()
 cls(13)
 map(0,0)
 spr(1+t%60//30*2,x,y,0,3,0,0,2,2)
 print("HELLO WORLD!",84,84,12)
 t=t+1
end

function BDR(v)
 -- TIC-80 0.90 later
 local y=v-4
 if y<0 or y>135 then return end
 my_bdr(y)
end

function SCN(v)
 -- TIC-80 0.70.6
 my_bdr(v)
end

function my_bdr(y)
 poke(0x3FF9,y) -- Screen offset x
 poke(0x3FFA,0) -- Screen offset y
end
```

1.0.2164
![scrofsx_tic80_1_0_2164_ss](https://user-images.githubusercontent.com/1796122/199226712-76f90123-d997-4bf4-9546-54f84704623d.gif)

0.90.1723
![scrofsx_tic80_0_90_1723_ss](https://user-images.githubusercontent.com/1796122/199226771-728aed62-3d8b-4b08-ac15-d3df6081628f.gif)

0.80.1344
![scrofsx_tic80_0_80_1344_ss](https://user-images.githubusercontent.com/1796122/199226818-a5a14710-11bf-4260-9c0b-9601b37729c2.gif)

0.70.6
![scrofsx_tic80_0_70_6_ss](https://user-images.githubusercontent.com/1796122/199226843-d65e40ab-9ef7-4aa5-9a5d-b3dc14d0ffbb.gif)

### Check for screen offset value in y-direction.

```lua
t=0
x,y=96,24

function TIC()
 cls(13)
 map(0,0)
 spr(1+t%60//30*2,x,y,0,3,0,0,2,2)
 print("HELLO WORLD!",84,84,12)
 t=t+1
end

function BDR(v)
 -- TIC-80 0.90 later
 local y=v-4
 if y<0 or y>135 then return end
 my_bdr(y)
end

function SCN(v)
 -- TIC-80 0.70.6
 my_bdr(v)
end

function my_bdr(y)
 poke(0x3FF9,0)     -- screen offset x
 poke(0x3FFA,y*0.5) -- screen offset y
end
```

1.0.2164
![scrofsy_tic80_1_0_2164_ss](https://user-images.githubusercontent.com/1796122/199226976-71a96be8-d96d-445b-96d1-d6c7ed79d72a.gif)

0.90.1723
![scrofsy_tic80_0_90_1723_ss](https://user-images.githubusercontent.com/1796122/199226997-77bff5b4-d8bd-44e4-a00e-fbf9a9fbf0f3.gif)

0.70.6
![scrofsy_tic80_0_70_6_ss](https://user-images.githubusercontent.com/1796122/199227021-1063c863-b630-4912-a418-60e19cd5472a.gif)

**Comment by nesbox** [comment]
fixed here b7c83903d3e2faf3a27f35305603def32c224ff8
