### ISSUE TITLE
The screen is weird on my phone

### ISSUE THREAD

**Issue by Lufims** [nesbox/TIC-80#2029]
The screen is tiny
![Screenshot_20221103-093638](https://user-images.githubusercontent.com/73536178/199722137-c1d11fe1-89de-4ee1-9677-cb12ace87ec7.png)
Phone: Samsung Galaxy A03 Core

**Comment by Stepan-Savchuk** [comment]
The same issue occurred when I switched to PRO version. I use Nokia 5.4

**Comment by joshgoebel** [comment]
Do you have a "before" photo and know exactly which version worked well?

**Comment by Stepan-Savchuk** [comment]
I don't have a photo before version 1.0, but with 0.9 screen was at least more usable

**Comment by joshgoebel** [comment]
> but with 0.9 screen was at least until keyboard

How is that even possible given the aspect ratio??  Even in your snap above the screen could really only be 40% larger before it hits the sides, leaving a substantial space between keyboard and screen.

**Comment by Stepan-Savchuk** [comment]
In 0.9 there was less space between keyboard and screen

**Comment by joshgoebel** [comment]
Closing as a duplicate of #2031
