### ISSUE TITLE
It shows an error on my pc

### ISSUE THREAD

**Issue by Lufims** [nesbox/TIC-80#2030]
"It was not possible to localize the entry point of the procedure GetSystemTimePreciseAsFileTime on the dynamic link library KERNEL32.dll"
![Screenshot_1](https://user-images.githubusercontent.com/73536178/199828070-5a96536e-5305-469c-851b-4a1d14c812bb.png)

**Comment by joshgoebel** [comment]
What version of windows, etc?

**Comment by Lufims** [comment]
> What version of windows, etc?

OS: Windows 7 Professional 
Processor: Pentium (R) Dual-Core CPU E5300 2.60GHz
RAM: 4 Gb
Chipset: 256 Mb shared memory
Opengl: 1.4
DirectX: 9
Shader Model: 2.0 (I think, but i'm certain that is not 3.0)
Vertex Shader: 2.0 (I think)
Pixel Shader: None

**Comment by phedoff** [comment]
I think you have to use the [XP-Version](https://github.com/nesbox/TIC-80/releases/download/v1.0.2164/tic80-v1.0-winxp.zip) to be able to use it on Win 7

**Comment by Lufims** [comment]
> I think you have to use the [XP-Version](https://github.com/nesbox/TIC-80/releases/download/v1.0.2164/tic80-v1.0-winxp.zip) to be able to use it on Win 7

Ok, it worked now with the xp version, thanks.

**Comment by joshgoebel** [comment]
Closing since we found the solution.
