### ISSUE TITLE
Small screen on android

### ISSUE THREAD

**Issue by EliasWolf-Br** [nesbox/TIC-80#2031]
Im using a Motorola and the screen is small ;-;

**Comment by Stepan-Savchuk** [comment]
The same issue occurred when I switched to PRO version. I use Nokia 5.4

**Comment by nesbox** [comment]
Could be fixed by adding `INTEGER SCALE ON/OFF` option to the settings

**Comment by nesbox** [comment]
added `INTEGER SCALE ON/OFF` option (ON by default on Android)
6725bb66ac4536be27c63e99113fbc9b4e76e903
![image](https://user-images.githubusercontent.com/1101448/216969466-b4e204bc-1af8-4006-af45-44ad86b799db.png)
