### ISSUE TITLE
Two bugs in build/tools/wasmp2cart.c

### ISSUE THREAD

**Issue by NulAsh** [nesbox/TIC-80#2036]
First bug is purely cosmetic.
https://github.com/nesbox/TIC-80/blob/7f4ad780d75d2cd8446f856f85ba293af70530eb/build/tools/wasmp2cart.c#L74
prj2cart instead of wasmp2cart.
Second bug causes crush when started without parameters. Look at function processArgs. It accesses argv without checking argc, and we have access violation.

**Comment by joshgoebel** [comment]
Thanks for the report!  Would you be willing to contribute a PR?

**Comment by joshgoebel** [comment]
Fixed naming in #2044.
