### ISSUE TITLE
Build for old(er) devices, Xperia play

### ISSUE THREAD

**Issue by gbraad** [nesbox/TIC-80#2039]
Hi, I was wondering what specifics are used from the current API of Android that prevents it from running/working on for instance older devices, such as the Xperia Play (android 2.3). Lots of older Android devices would be ideal 'player' devices.

Please let me know. While I haven't done Android development for a long time, I am more than happy to contribute help in this regard.

**Comment by gbraad** [comment]
> SDL2 library for TIC80 rendering

SDL is only used for the rendering?

**Comment by nesbox** [comment]
yes, we put user input into it (gamepad+mouse+keyboard) and get a screen buffer, which is a `240*136*4pbb` byte buffer, plus an audio buffer. And all this works at a frequency of 60 Hz. SDL2 just draws the texture with the rendered screen and plays sound.
Ah, and provides usern input.

**Comment by joshgoebel** [comment]
@gbraad Did you have an idea for replacing SDL2 on such a platform and what could be used in it's place?
