### ISSUE TITLE
Update Fennel version

### ISSUE THREAD

**Issue by noncom** [nesbox/TIC-80#2040]
Please update the Fennel version to the latest? :)

The language is being actively developed, it would be cool if the updates won't be missed, at least at some reasonable periodicity.

**Comment by joshgoebel** [comment]
Perhaps if we asked @technomancy nicely?

**Comment by technomancy** [comment]
Hey!

We just noticed a couple weeks ago that the most recent release has a feature which won't work in TIC-80; it highlights compile errors using ANSI escape codes. There is a way to opt out of this on the latest git version but it hasn't yet landed in a stable release, so I'd like to hold off on updating until our 1.3.0 lands; hopefully some time next month.

**Comment by technomancy** [comment]
Fixed in #2130 btw.
