### ISSUE TITLE
Fully featured PICO-8 to TIC-80 cartridge converter

### ISSUE THREAD

**Issue by bztsrc** [nesbox/TIC-80#2043]
Hi,

I was looking for ~, but couldn't find any that actually works ([best](https://github-wiki-see.page/m/neilpopham/tic80/wiki/Porting-from-PICO-8) find), so I've decided to create a proper one.

This little tool works as a simple web-service (minimal wasm, could be added to the tic80.com site), but also compiles as a native CLI tool (Linux and Windows, probably any BSD too), totally dependency-free (no shared libraries or DLLs needed, it just works). It is still rough around the edges, but already usable as it is. FOSS, MIT licensed of course. Enjoy!
[p8totic.tgz](https://github.com/nesbox/TIC-80/files/10149487/p8totic.tgz)

## Compilation

Just run `make`. If you only want the web-service, then `make wasm` (requires emscripten), for the CLI only `make cli` (gcc or mingw). Has absolutely no library dependencies, so simply running `gcc p8totic.c -o p8totic` works too.

## Usage

It can read in PICO-8 cartridges in textual `.p8` format or binary `.p8.png` format, and saves it as a TIC-80 cartridge in binary `.tic` format.

It is a single file, p8totic.c, with a single API function, `int p8totic(uint8_t *buf, int size, uint8_t *out, int maxlen)`. This receives the PICO-8 cartridge in `buf`, and returns the TIC-80 cartride's size and data in `out`. That's all.

## Features

- Cover image. For the textual format, `__label__` is used, in a binary file a 128x128 area is cropped at position 16,24 from the png image. This is then centered on the TIC-80 240x136 screen and saved as bank 0 CHUNK_SCREEN.
- Sprites: the 256 PICO sprites with all the funky addressing and stripes are converted into CHUNK_TILES.
- Map: the map is resized correctly and saved as CHUNK_MAP. (Note: PICO-8 memory 0x1000 .. 0x1fff saved both for sprites and map)
- Sprite flags: just copied over and padded with zeros into CHUNK_FLAGS. Not sure if we have to do bit fiddling here or not. Let me know.
- Palette: the default PICO-8 palette is saved into the cartridge as SCN as well as OVR in CHUNK_PALETTE.
- Lua code: all funky PICO-8 compressions are supported (flat, old, new). If the code is smaller than 64k, then it is saved into CHUNK_CODE, however if it's bigger, then it is zlib compressed and saved as CHUNK_CODE_ZIP (I know that this supposed to be deprecated, but what other options are there?) Normally a PICO-8 Lua code can't be bigger than 64k, but this tool automatically adds [musurca](https://github.com/musurca/pico2tic)'s PICO-8 wrapper before the Lua code, and with that it could exceed 64k.

## TODO

- Music: is read correctly from the PICO-8, but I'm not sure how to store it into TIC-80 format (do we need CHUNK_PATTERNS too?)
- Sound effects: the PICO-8 binary works, but the textual somehow has 20 bits per note, but only 16 bits in-memory. I couldn't figure out how that supposed to work, the [PICO-8 spec](https://pico-8.fandom.com/wiki/P8FileFormat) isn't very helpful in this case.
- Testing, testing and even more testing. I did convert some cartridges, but I've just started coding this afternoon, so obviously I didn't had much time.

Hope you like it! If you plan to add it to this repo (and hopefully to the tic80.com site), then I'm willing to maintain it and fix all the edge cases. Just let me know what's wrong.

Cheers,
bzt

**Comment by joshgoebel** [comment]
Would love to see this and perhaps contribute in the future, could you put this up as a GitHub project?

Does this do anything to rewrite the code itself and deal with API changes between TIC-80 and PICO-8?

> (I know that this supposed to be deprecated, but what other options are there?)

You have use of all 8 pages now so you can save eight 64k code chunks that are concat to add up to 512kb of uncompressed Lua code.

**Comment by bztsrc** [comment]
> could you put this up as a GitHub project?

Sorry, github and me aren't really friends lately. I'm unable to create repos and commits for a while :-( That's why I've attached it.

> Does this do anything to rewrite the code itself and deal with API changes between TIC-80 and PICO-8?

Yes. It automatically adds musurca's Lua lib, and calls a function to replace strings in the Lua code (however that function is currently empty, but there's already a place for syntax differences too).

> You have use of all 8 pages now so you can save eight 64k code chunks that are concat to add up to 512kb of uncompressed Lua code.

Unfortunately the doc says otherwise. It says that 8 banks only supported in the PRO version, and also that banks are deprecated with the CHUNK_CODE chunk. I'm not sure how to go on, that's why I've added CHUNK_CODE_ZIP as a failsafe. But I'm listening, I'm open to any suggestions and feedback!

Cheers,
bzt

**Comment by bztsrc** [comment]
Here's the [doc](https://github.com/nesbox/TIC-80/wiki/.tic-File-Format). In the *Chunk Types* table, it says:
```
5 	CHUNK_CODE 	8 	(all 8 banks is PRO only)
```
And a little below, in the *Code* section, it says:
```
Note: 0.80 removed support for code banks. As a workaround, it loads each individual bank with a newline
separated between them, starting at bank 7 (which appears at the top) and working backwards to bank 0.
The bank number is otherwise considered deprecated with this chunk type.
```
Which I find hard to understand. Does this mean we can use the "bank" bits in the chunk or not? And if so, why are the banks reversed, and I really don't understand this part: "loads each individual bank with a newline separated between them". I can't guarantee that a Lua code always have a newline at every 64k offset, and also how one supposed to tell normal newlines apart from bank separator newlines? it just doesn't make sense to me.

Any suggestion how this supposed to work? Checking the source (cart.c) I'm pretty sure CHUNK_CODE is limited to 64k, and not concatenated, either in normal or reverse order.

Cheers,
bzt

**Comment by joshgoebel** [comment]
https://github.com/nesbox/TIC-80/blob/main/src/cart.c#L312

> all 8 banks is PRO only

This is said lots of places but doesn't always mean what you think.  In many cases the editors prevents you from EDITING additional banks, but they work just fine in practice (to play games, etc)... I think code is an exception - I think you can save 512kb pro or not (it would be easy for you to test this).

> Which I find hard to understand. 

Yikes.  All of this is so wrong, let me go rewrite it. :-). I've read (and written) some of this code lately, it's all much simpler than that.  You just use as many chunks as you need (up to 8)... they are concat one after another (as if contiguous) - newlines are irrelevant... that was long ago stuff...

**Comment by joshgoebel** [comment]
Updated, let me know if that helps!

**Comment by bztsrc** [comment]
> Yikes. All of this is so wrong, let me go rewrite it. :-). I've read (and written) some of this code lately, it's all much simpler than that. You just use as many chunks as you need (up to 8)... they are concat one after another (as if contiguous) - newlines are irrelevant... that was long ago stuff...

No worries! So I can store 512k of Lua code, all that's needed is a CHUNK_CODE header at every 64k, bank bits doesn't matter. This is actually pretty cool. And I can remove CHUNK_CODE_ZIP entirely, right?

Maybe I haven't put emphasis on this enough, but I think TIC-80 is pretty awesome! I prefer to choose it over PICO-8 any time! I hope if this tool gets ready, it will help lots of people to switch too!

Cheers,
bzt

**Comment by joshgoebel** [comment]
> all that's needed is a CHUNK_CODE header at every 64k, bank bits doesn't matter.

The bank bits do matter, you need bank 0 to bank 7 if you have 512kb of code.  The order of the chunks in the saved file shouldn't matter (though I'm pretty sure we save them sequentially)... what matters is that the bank #s are correct.

**Comment by bztsrc** [comment]
> Updated, let me know if that helps!

Indeed, thank you very very much!

> The bank bits do matter, you need bank 0 to bank 7 if you have 512kb of code.

Yes, from the updated doc this is now crystal clear!

> The order of the chunks in the saved file shouldn't matter

Yep, but I agree it's better to store them sequentially.

I'll attach the updated converter soon(ish), thanks a lot again!
bzt

**Comment by bztsrc** [comment]
Hi,

I've fixed everything we talked about, and uploaded the stuff to gitlab (*lab*, not hub, hope that's okay with you. Interestingly that codehost works like a charm).
[source](https://gitlab.com/bztsrc/p8totic)
[online converter](https://bztsrc.gitlab.io/p8totic/)

Going further, can you help me figuring out the PICO-8 text `__sfx__` format? What confuses me, that in memory each note is 16 bits, but in the text file there are 20 bits per note.

Cheers,
bzt

**Comment by joshgoebel** [comment]
> help me figuring out the PICO-8 text __sfx__ format?

No idea, sorry.

**Comment by thomasgauthier** [comment]
@bztsrc Is this related to your problem? https://github.com/jtothebell/fake-08/blob/78d8ffe77b4c27a535875db1e865a0eca1000671/source/cart.cpp#L507.

It's from an open source PICO-8 runtime.

You could also look at these:

- [tac08](https://github.com/0xcafed00d/tac08)
- [pemsa](https://github.com/egordorichev/pemsa-sdl)

Awesome work btw!

**Comment by bztsrc** [comment]
Little update: I've added PICO-8 codepage conversion. Also I've quickly put together a [source code tokenizer](https://gitlab.com/bztsrc/tok) and serializer, and with that library this tool now [converts Lua syntax](https://gitlab.com/bztsrc/p8totic/-/blob/f64ece6e105fb78681698ad5014dabb416342c70/src/lua_conv.h#L105) too. Replacing operators (like `!=` -> `~=`), shorthand operators (like `var +=` -> `var = var +`), functions to operators (like `shl(a,b)` -> `(a<<b)`) etc. What's not replaced, those API calls are still provided by the helper Lua library.

If there are other differences, let me know!

Cheers,
bzt

Cheers,
bzt

**Comment by bztsrc** [comment]
I think I close this issue, there's no point in keeping it open.

I did everything I could, almost everything is converted perfectly. Still need some help for the music (the waves and most of the sound effects are already converted). I understand that TIC-80 can do a lot more than PICO-8, but the point is, the converter should generate some sane defaults so that the music could sound the same or as close as possible to the original.

I need help with this latter part, any contributions are welcome.

Cheers and Merry Xmas,
bzt
