### ISSUE TITLE
Tic 80 fails to build on Windows x64 using mingw-w64 toolchain (from msys64) in SDL "windows_gaming_input.c" (known SDL bug?)

### ISSUE THREAD

**Issue by TheRektafire** [nesbox/TIC-80#2050]
The version of SDL currently being used by TIC 80 (https://github.com/libsdl-org/SDL/commit/b424665e0899769b200231ba943353a5fee1b6b6) causes building to fail under mingw-w64 apparently as a result of a mismatch between the mingw header type definitions and the actual Windows API type definitions (as detailed here https://github.com/libsdl-org/SDL/issues/5589). According to this similar issue https://github.com/tildearrow/furnace/issues/764 this was fixed in a later commit where a workaround was added https://github.com/libsdl-org/SDL/commit/d2c4d74dd0302369251dce9375b49f394e54f76a. So ideally the version used in TIC 80 could be bumped up to at least that one assuming it wouldn't break anything? (I don't really know enough about submodules and github and what not to try it myself at the moment unfortunately)

**Comment by drewbitt** [comment]
+1. It does fail to build on Windows due to SDL

```
C:\TIC-80\vendor\sdl2\src\joystick\windows\SDL_windows_gaming_input.c:649:113: note: expected '__FIReference_1_INT32 **' but argument is of type 'int **'
mingw32-make[2]: *** [vendor\sdl2\CMakeFiles\SDL2-static.dir\build.make:2551: vendor/sdl2/CMakeFiles/SDL2-static.dir/src/joystick/windows/SDL_windows_gaming_input.c.obj] Error 1
```

**Comment by drewbitt** [comment]
Libuv and SDL2 both need updates to build

```bash
cd vendor\sdl2
git fetch && git checkout 55b03c7493a7abed33cf803d1380a40fa8af903f
cd ..\libuv
git fetch && git checkout 988f2bfc4defb9a85a536a3e645834c161143ee0
```

However it will still fail near the end with
 ```bash
C:\TIC-80\src\system\sdl\player.c:25:10: fatal error: SDL.h: No such file or directory                                                                     25 | #include <SDL.h>                                                                                                                                                            |          ^~~~~~~   
```
which is located in `vendor/sdl2/include/SDL3`. Attempts to include with `-I` did not work. I am not proficient in makefiles & building; there is obviously more needed in an update.

**Comment by nesbox** [comment]
Updated SDL2 and libUV to the latest here 2165c2f87c27582f7199d5a299bb06d3e93c7dfc
Hope, this will help.
