### ISSUE TITLE
[LINUX] "Up" and "Left" arrow keys permanently pressed with external USB keyboard

### ISSUE THREAD

**Issue by RaelZero** [nesbox/TIC-80#2055]
Hi!

As per issue title, it appears that the TIC-80 application on my computer is detecting the "up" and "left" arrow keys to be permanently pressed while my external USB keyboard is attached to my laptop. 

My setup:
* Hardware: System76 Lemur Pro 10 with i7 CPU (see [here](https://tech-docs.system76.com/models/lemp10/README.html))
* OS: Arch Linux (updated as of 2022/12/16) with i3 desktop environment
* TIC-80 Version: 1.0.2164 Pro (b09c50c)
* External keyboard: "Anne Pro 2" (programmed with obinskit software)

Reproduction steps:
* Download, unzip and launch the TIC-80 application
* Press "CTRL-R" (run the "hello world" cartridge)
* The TIC-80 "character" immediately starts moving up and left, as if the "up" and "left" arrow keys were pressed

Other notes:
* Unplugging the external keyboard stops the character from moving. Replugging the keyboard resumes character moving
* The issue does not appear on the [web version](http://tic80.com/create) of TIC-80, even with the keyboard plugged in
* The issue does not appear if the keyboard is connected via bluetooth
* In the latest development version 1.0.2254-dev (fb8ba3f), the issue still appears, but only the "up" arrow appears to be pressed

Not a "breaking" bug (I can work around it by connecting via Bluetooth, but annoying nonetheless... 

Let me know if I can provide further info, and thanks for developing this great little fantasy computer!

**Comment by Jummit** [comment]
I have the same issue on Linux, with an USB keyboard. I can't remember when it started, maybe it's time for a git bisect...

**Comment by nesbox** [comment]
I suspect this issue is related to gamepad handling and I disabled it in a separate branch.
Can any of you test it on your systems, you can download the build from the artifacts section here https://github.com/nesbox/TIC-80/actions/runs/4216038702

**Comment by Jummit** [comment]
> I suspect this issue is related to gamepad handling and I disabled it in a separate branch. Can any of you test it on your systems, you can download the build from the artifacts section here [nesbox/TIC-80/actions/runs/4216038702](https://github.com/nesbox/TIC-80/actions/runs/4216038702)

I tried that version, and the issue does not appear.

**Comment by nesbox** [comment]
I've just added new GameController support instead of the old Joystick API from SDL2 lib, which would fix the keyboard issue. 
Could someone check the latest dev build, please?

**Comment by nesbox** [comment]
And pls check this one https://github.com/nesbox/TIC-80/actions/runs/4234237642
where I added GameController DB with a list of supported devices, this might also solve the issue

**Comment by Jummit** [comment]
> And pls check this one [nesbox/TIC-80/actions/runs/4234237642](https://github.com/nesbox/TIC-80/actions/runs/4234237642) where I added GameController DB with a list of supported devices, this might also solve the issue

Mmh, I get the issue in this build too.

**Comment by nesbox** [comment]
And the last one pls https://github.com/nesbox/TIC-80/actions/runs/4235362299
Here I try to determine gamepad type

**Comment by Jummit** [comment]
> And the last one pls [nesbox/TIC-80/actions/runs/4235362299](https://github.com/nesbox/TIC-80/actions/runs/4235362299) Here I try to determine gamepad type

That works! :tada:

**Comment by nesbox** [comment]
Finally, thank you

**Comment by nesbox** [comment]
I'm still trying to find a better way to fix the issue, could you pls run this build https://github.com/nesbox/TIC-80/actions/runs/4242011429 and send the log output here?
It should look like
```
SDL_IsGameController: 1
SDL_GameControllerNameForIndex: Xbox 360 Controller
SDL_GameControllerTypeForIndex: 1
SDL_GameControllerMappingForDeviceIndex: 030003f05e0400008e02000000007200,*,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,
```

**Comment by Jummit** [comment]
> I'm still trying to find a better way to fix the issue, could you pls run this build [nesbox/TIC-80/actions/runs/4242011429](https://github.com/nesbox/TIC-80/actions/runs/4242011429) and send the log output here? It should look like
> 
> ```
> SDL_IsGameController: 1
> SDL_GameControllerNameForIndex: Xbox 360 Controller
> SDL_GameControllerTypeForIndex: 1
> SDL_GameControllerMappingForDeviceIndex: 030003f05e0400008e02000000007200,*,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,
> ```

The output:

```
SDL_IsGameController: 1
SDL_GameControllerNameForIndex: Serial/Keyboard/Mouse/Joystick
SDL_GameControllerTypeForIndex: 0
SDL_GameControllerMappingForDeviceIndex: 03000b85c01600008704000011010000,Serial/Keyboard/Mouse/Joystick,a:b12,b:b10,back:b4,dpdown:b2,dpleft:b3,dpright:b1,dpup:b0,leftshoul
```

**Comment by nesbox** [comment]
Instead of using `SDL_GameControllerTypeForIndex()` I just filter devices by `Serial/Keyboard/Mouse/Joystick` name
https://github.com/nesbox/TIC-80/actions/runs/4243070077

**Comment by Jummit** [comment]
That one works, too.
