### ISSUE TITLE
HTML versions not loading cart automatically on dev builds when exported without editors

### ISSUE THREAD

**Issue by PAPERMOON-SO** [nesbox/TIC-80#2061]
HTML carts exported without editors for whatever reason don't load the cart automatically on startup. From my testing this only affects the non-stable versions I have (`1.0.2149-dev Pro (9a53121)`, `1.0.2246-dev (d23ffe1)` and `1.0.2246-dev Pro (d23ffe1)`), and doesn't affect the stable 0.90 and 1.0 executables. This also appears to only affect HTML exports, as Windows exports work fine for me (Windows is the only other platform I can test).

`dir` shows that the cart does exist and you can use `load` to load it and run it manually, but it doesn't do it automatically. However, if `alone=1` is specified when exporting, the cart will load automatically without issue. The actual cart contents don't seem to matter, as all of the above happens on all carts I've tried exporting.

**Comment by nesbox** [comment]
Fixed here 859c71904bb3fcd253b9831562da3f03922b297a
