### ISSUE TITLE
When you type help commands the result will be displayed saying "unknown topic?"

### ISSUE THREAD

**Issue by MasterNama17083** [nesbox/TIC-80#2073]
I'm going to type `help [commands]` something, and the result displayed why `unknown topic:` is here. Weird...
![video1](https://user-images.githubusercontent.com/80534869/211049526-c19c7f56-ad7d-4f3d-9b2a-ee420d10b01f.gif)

**Comment by jezze** [comment]
I think we have a fix for this already waiting to be merged: https://github.com/nesbox/TIC-80/issues/2073
