### ISSUE TITLE
Can't Seem To Show Or Hide Mouse Cursor When Playing TIC-80 Game?

### ISSUE THREAD

**Issue by BetaMaxHero** [nesbox/TIC-80#2081]
Hi,

I Googled a bit but was unable to solve below:
How to show or hide the mouse cursor in a TIC-80 game?

I tried:
`poke(0x3FFB,0)`
but nothing happens?

I bought TIC-80 on Itch website.
Let me know, thanks!

Jesse

**Comment by nesbox** [comment]
Hi, 
try to call `poke(0x3FFB,0)` on every `TIC()`
```lua
function TIC()
	cls(13)
	poke(0x3FFB,0)
end
```

**Comment by BetaMaxHero** [comment]
Hi,

Thanks, that worked.

Jesse
