### ISSUE TITLE
CRT filters

### ISSUE THREAD

**Issue by ambyra** [nesbox/TIC-80#209]
The low resolution pixels would look good with some classic crt filters.

**Comment by AnastasiaDunbar** [comment]
Custom shaders? Also make sure CRT filters are optional.

**Comment by to90zeroblue** [comment]
I was thinking more like a --filter: (1-4), with a few hand picked shaders to make it look like a real TV.

**Comment by to90zeroblue** [comment]
http://www.superrune.com/tools/supercrt.php is a good one

**Comment by darkhog** [comment]
I'd file it under "cool to have". Be sure to also make a filter to simulate convexness of a CRT (cushion displacement) - I think Nestopia has the best crt filters.

**Comment by nesbox** [comment]
It won't work with current renderer, SDL doesn't have shaders support
but, it can be done if I (or someone :) ) rewrite renderer to GL

**Comment by to90zeroblue** [comment]
Would this still run on web browsers? Oldskool software filter might an option if not.

**Comment by nesbox** [comment]
software filter might an option, but it's too heavy for CPU
usually, software filter costs about 30-40%

**Comment by to90zeroblue** [comment]
Yep, hardware is the way to go. Quick hack: conver sdl surface to a gl texture every frame and apply the filter. I never did this, maybe terribly slow as well. 

Then slowly port over code, so doesn't have to be done at once. 

Btw is the code available?

**Comment by nesbox** [comment]
Experimenting with simple CRT filter
![crt](https://user-images.githubusercontent.com/1101448/30520677-9440a36a-9bbb-11e7-8363-fff1ab1588a3.gif)

**Comment by Ferk** [comment]
It would be interesting if Tic-80 could be compiled as a Retroarch core. Retroarch has a lot of shaders and potentially it could be used to bring Tic to consoles able to run Retroarch.

**Comment by nesbox** [comment]
c7666f5
- added SDL GPU lib https://github.com/grimfang4/sdl-gpu with CRT monitor shader support
- press **F6** to enable/disable CRT monitor
- shader code saved in the _config_ (bank1)
- added `CRT_MONITOR` variable to the _config_ (`true` by default)
- works on every platform supported OpenGL (except PocketCHIP)
