### ISSUE TITLE
Default waves not appearing when creating a new fennel cartridge

### ISSUE THREAD

**Issue by TLAliceDev** [nesbox/TIC-80#2093]
When creating a new cartridge on any of the other available languages, there are 3 sound waves available on the SFX editor

![image](https://user-images.githubusercontent.com/109485802/213895573-07e1bfce-bb29-4f0f-9560-9524d55772e5.png)

When creating it in fennel however, these waves do not appear
![image](https://user-images.githubusercontent.com/109485802/213895585-cc62879a-d1ce-4792-9c9f-1ce50a629313.png)

**Comment by AlecTroemel** [comment]
I'd be happy to look into this one!
