### ISSUE TITLE
Window glitches out when streaming on Discord

### ISSUE THREAD

**Issue by GDPlayer** [nesbox/TIC-80#2105]
![image](https://user-images.githubusercontent.com/51692409/215322283-38fe8e35-8820-451b-bc18-0e1b6baef055.png) 
###### what
When attempting to stream TIC-80 to Discord this happens and stays there until you restart TIC-80.

**Comment by sogaiu** [comment]
Possibly related to https://github.com/nesbox/TIC-80/issues/1914.

[One of the comments](https://github.com/nesbox/TIC-80/issues/1914#issuecomment-1156244185) mentions "weird visual glitches".

**Comment by nesbox** [comment]
dupf of #1914
