### ISSUE TITLE
Buggy editor

### ISSUE THREAD

**Issue by gek169** [nesbox/TIC-80#2111]
![image](https://user-images.githubusercontent.com/6974902/216088732-a0c5ab92-45c9-4ccf-81e7-8b94d356abf5.png)

I deleted the starting comment, and it caused my code to be impossible to run.
This is a javascript cartridge.

This is the most scuffed thing I have ever seen in any editor.

All I did was select all the comments (click+drag) and delete the starting // comments.

Steps to reproduce:
1. Create a new cartridge.
2. Highlight all the initial comments with your mouse
3. delete them.
4. Try to run the cartridge

How do you release software this poorly written? Honestly.

**Comment by gek169** [comment]
it doesn't use a file extension?
Where is this stuff documented?

**Comment by gek169** [comment]
Alright, that worked.

**Comment by Anrock** [comment]
> it doesn't use a file extension?

No, `.tic` files are completely self-contained and package all resources into one file. See [format description](https://github.com/nesbox/TIC-80/wiki/.tic-File-Format) in the wiki.

> Where is this stuff documented?

In [cartridge metadata section](https://github.com/nesbox/TIC-80/wiki/the-code#cartridge-metadata), link is provided straight in [the home page](https://github.com/nesbox/TIC-80/wiki#code-editor) of wiki.
