### ISSUE TITLE
missing metadata when trying to upload pro cartridges to tic80.com

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#2121]
I tried to update an old cartridge created with tic80 pro, but upload failed due to missing metadata. I triple-checked all fields and the cover image, but it still didn't work.

Luckily I was able to upload the cart with the option of adding metadata in a separate cart.

If uploading pro cartridge metadata is not supported, there could at least be a disclaimer: "If you're uploading a TIC-80 pro cartridge, please add metadata in a separate cartridge."

**Comment by TimotheeGreg** [comment]
I had the same problem, and someone else on the discord too.

**Comment by nesbox** [comment]
Link to the cart https://tic80.com/play?cart=1378

**Comment by nesbox** [comment]
fixed
