### ISSUE TITLE
tic80.wasm not regenerated?

### ISSUE THREAD

**Issue by sthilaid** [nesbox/TIC-80#2126]
Hi! I've been doing local test with scheme in tic80 and I tried to export my tests to html. The export works but when I run the wasm in the webpages, I can see an error that indicates that the tic80.wasm is from an older build (last week?) since it shows an error that would be fixed in a new build (looks for the defstruct macro, which was pulled in recently). Is there a way to make a build fully autonomously locally without fetching the wasm?

**Comment by nesbox** [comment]
We have to find a workaround to test it locally. For now, you can build it yourself to wasm using Emscripten compiler, and replace tic80.wasm in the exported files.
