### ISSUE TITLE
time() seems to be running slow

### ISSUE THREAD

**Issue by JohnEmhoff** [nesbox/TIC-80#2128]
Hello! I just downloaded a new version (1.0.2164 pro; linux) and it seems that `time()` is messed up on my system -- it's running too slow, by a factor of about twenty-ish. To demonstrate, I've added this line to the base cart:

```
trace(time() .. " " .. tstamp())
```

...and here's a selection of lines from the output (showing one per second for our sanity):

```
>728.251 1676519803.0
>755.61 1676519804.0
>783.374 1676519805.0
>811.448 1676519806.0
```

Everything else seems fine though and runs at 60fps. `time()` from the previous version (0.90.1723) runs as expected.

**Comment by joshgoebel** [comment]
This has been fixed in `main` already, just not released.

**Comment by nesbox** [comment]
Closing as dup of #1904
