### ISSUE TITLE
Current MacOS release has broken time()

### ISSUE THREAD

**Issue by evilpaul-atebit** [nesbox/TIC-80#2142]
The current version available for download from https://github.com/nesbox/TIC-80/releases/ (`1.0.2164`) exhibits broken behaviour in the `time()` function.. at least on my Mac (2019 Intel model).

The following test cart demonstrates the behaviour:
```
f=0
function TIC()
 cls(0)
 local t=time()
 if (t/100)%2>=1 then
  for y=0,135 do
   for x=0,239 do
    pix(x,y,0)
   end
  end
 end
 print(t,0,0,12)
 local x=t%240
 line(x,0,x,135,12)
 print(f,0,10,12)
 f=f+1
end
```
This should show a bar smoothly moving across the screen, a milliseond counter and a frame counter. The code alternates every second between doing nothing else in the main loop and rendering a bunch of pixels. The line and millisecond counters move at different speeds depending on whether the main loop is doing the extra rendering or not, ie: dependent on the CPU load. The millisecond timer is also a factor of 10 out.

Gif attached:
![video1](https://user-images.githubusercontent.com/16197891/221271285-9db2bfb6-a00c-4e1b-9971-74bd7e93a2f4.gif)

On a Windows machine this test cart behaves as expected.

Cloning and building the latest version of the code `1.1.2481-dev` does work correctly on my Mac - the bar moves smoothly and the millisecond counter is correct. So.. it seems that the current release is broken and it has been fixed somewhere between 1.0.2164 and 1.1.2481.

**Comment by TimotheeGreg** [comment]
Yes, I think it has been fixed there https://github.com/nesbox/TIC-80/pull/2047

**Comment by nesbox** [comment]
yes, closing as dup #2047
