### ISSUE TITLE
itch.io page size bug

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#2148]
![IMG_20230301_005728](https://user-images.githubusercontent.com/36867670/222000882-865f1a1f-ba82-4e84-9c82-a18be1d9ac1b.jpg)
this is under "Demo versions"

**Comment by nesbox** [comment]
I think it's itch.io bug, not TIC-80 :)

**Comment by BuoYancYdabl** [comment]
Yeah, probably. I didn't dowloaded the file, so I thought the file wasn't been uploaded properly
