### ISSUE TITLE
Built-in Vector library

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#2150]
It would be great, if TIC had vector2, 3 and 4 libraries built in the same as math or table

**Comment by joshgoebel** [comment]
Are those part of Lua stdlib?

**Comment by darltrash** [comment]
i feel like that's huge overkill but i might be wrong

**Comment by joshgoebel** [comment]
What are these libraries? Just 2d/3d/4d vector math or?

**Comment by BuoYancYdabl** [comment]
> Are those part of Lua stdlib?

Not sure

> What are these libraries? Just 2d/3d/4d vector math or?

Almost, its just regular vectors that can help to calculate different values without need to search for the vector code yourself.

**Comment by blueloveTH** [comment]
for python there is a built-in module `linalg` for tic80 that provides common 2d/3d vector operations and 2d transformations via `mat3x3`.

```python
from linalg import vec2, vec3, mat3x3
```

**Comment by miratcan** [comment]
> for python there is a built-in module

linalg is not a Python built in, you need to install NumPy to get it. Which is a huge package.

**Comment by miratcan** [comment]
> Are those part of Lua stdlib?

No, but there is a library that can be used: https://github.com/anaef/lua-linear/tree/master

BTW I agree that most of the people implementing at least 2d vectors to create something serious.

**Comment by blueloveTH** [comment]
> > for python there is a built-in module
> 
> linalg is not a Python built in, you need to install NumPy to get it. Which is a huge package.

Yes, it is not a standard built-in. `linalg` module is only available in tic-80's python version. Check https://pocketpy.dev/modules/linalg/. Create a python project and it is available.

**Comment by blueloveTH** [comment]
> @blueloveTH I'm confused, is this already implemented?

Yes. Available.

**Comment by aliceisjustplaying** [comment]
Closing this in that case :)
