### ISSUE TITLE
Build with Janet breaks compiling on windows without Visual Studio

### ISSUE THREAD

**Issue by NPO-197** [nesbox/TIC-80#2154]
Janet requires having Visual Studio Build tools to compile, so currently it's not possible to build tic-80 from source on windows using MinGW unless you turn BUILD_WITH_JANET off in the cmake file. I was able to compile successfully on windows without issue using MinGW by disabling Janet, which works fine for me since I don't plan on using Janet, but I thought I should let you know that the read-me file might need to be updated since the build instruction for MinGW seem to be out of date.

I'm still pretty new to c++ compiling so I might just be missing something? but looking at https://github.com/janet-lang/janet It seems like they expect you to have VS Build tools to be able to compile, which I don't think is required for anything else in this project? 
VS Build tools are like 4.5 GB BTW so for me working on my laptop I'd rather just not have Janet 😓.

In the CMakeLists.txt file:
```    
if(MSVC)
        add_custom_command(
            OUTPUT ${THIRDPARTY_DIR}/janet/build/c/janet.c
            COMMAND ./build_win.bat
            WORKING_DIRECTORY ${THIRDPARTY_DIR}/janet/
        )
    else()
        add_custom_command(
            OUTPUT ${THIRDPARTY_DIR}/janet/build/c/janet.c
            COMMAND make build/c/janet.c
            WORKING_DIRECTORY ${THIRDPARTY_DIR}/janet/
        )
    endif()
```
And `make build/c/janet.c` fails on windows using just MinGW.

If there is something I should add, or If I'm just not being all that helpful, please let me know!

**Comment by sogaiu** [comment]
FWIW, in [a recent release of Janet](https://github.com/janet-lang/janet/blob/master/CHANGELOG.md#1270---2023-03-05), support for mingw and cygwin was added:

> Add support for mingw and cygwin builds (mingw support also added in jpm).

I think this was after Janet support was added to TIC80 though.

**Comment by AlecTroemel** [comment]
I'll hopefully be able to take a look at this tonight. In addition to any CmakeList.txt changes, we'll also probably need to update the janet git submodule. I was just going off of the main branch, but [janet 1.27](https://github.com/janet-lang/janet/releases/tag/v1.27.0) has everything we need to we should probably lock into that

**Comment by sogaiu** [comment]
Happy to do some testing -- just not familiar with the `MINGW` + TIC80 combination.  I think it would be nice if Visual Studio wasn't required.

**Comment by NPO-197** [comment]
I'd be happy to test as well, thanks for taking a look at it!

**Comment by AlecTroemel** [comment]
with https://github.com/nesbox/TIC-80/pull/2155 merged I believe this can be closed! @NPO-197 you mind double checking when you get a chance?

**Comment by NPO-197** [comment]
Double Checked compiled without error! Thanks so much @AlecTroemel and @sogaiu for your help!. 😄

**Comment by sogaiu** [comment]
@NPO-197 Thanks for bringing up the issue.  I also prefer not to have to install certain tooling if possible :)

@AlecTroemel Thanks for getting this to work -- did not look easy!
