### ISSUE TITLE
Enter key not working.

### ISSUE THREAD

**Issue by kijeEnki** [nesbox/TIC-80#2156]
When i press enter on my keyboard, nothing happens. It works in other programs, but not on tic80. The one on the sensor on screen keyboard works, but not the physical. I’ve tried different layouts — yet no success. It doesn’t work on the web version either

**Comment by scambier** [comment]
What code are you using to determine that the key is working or not?

**Comment by jinjanai** [comment]
When i enter a command and press enter nothing happens. Also since that issue i got a new computer and enter works now

**Comment by dharrington** [comment]
Same thing here with QMK. Probably it's implementing keypresses by polling state rather than keyboard events. I think that's the case looking at https://github.com/nesbox/TIC-80/blob/main/src/core/io.c
