### ISSUE TITLE
[request] please add an edition mode AUTOSAVE feature

### ISSUE THREAD

**Issue by atesin** [nesbox/TIC-80#2161]
sometimes i had the whole day working in my game, then in late night i go to bed, sleepy.....  to realize the next day i DIDNT SAVE my work, and i have no way to recover

did tic80 some sort of autosave (to temp file at least), or some save warning that prevent to power off the host computer?

**Comment by atesin** [comment]
another "feature" that could be harmful is being able to exit tic80 with the `alt-f4` key (and maybe others) immediately without any prompt!!... this happened to me a couple times also

**Comment by nesbox** [comment]
dup of #221
