### ISSUE TITLE
[request] Make tile flags editable in <4bpp color modes

### ISSUE THREAD

**Issue by JulianImp** [nesbox/TIC-80#2172]
I was fiddling around with 2bpp and 1bpp modes, and I just realized that the sprite editor removes flag support for them. Since the engine already tracks color depth, wouldn't it be feasible to use the same 512 bytes of flag data as 1024 nibbles (halving the number of flags each tile/sprite can use) for 2bpp, or 2048 pairs of bits for 1bpp?

I guess the `drawFlags` procedure in `sprite.c` would have to change the `BITS_IN_BYTE` constant reference to whatever value holds the current color bit depth, and change read/write operations to flag RAM so that they'd acess memory in smaller increments.

Without this fix, users would have to jump through hoops to use their desired flag values in games running on <4bpp color modes, but the RAM to store the flags and the routine to draw the editable checkboxes is already in place, so I believe it shouldn't be too hard to implement.

**Comment by joshgoebel** [comment]
Dup of #1995.
