### ISSUE TITLE
[1.1.2511-dev (ffd6965)] After startup and then you type the "menu" command to select the resume game results in a black screen via the default cart

### ISSUE THREAD

**Issue by MasterNama17083** [nesbox/TIC-80#2175]
We found a bug long ago, and that's how this resume game results in the black screen with hearing that square "C-4" note sound.
1. Type the `menu` command
2. Go to select `RESUME GAME`
3. Result in a black screen and how to be caused won't start up the default cart!

That's it :)

Let's take a look and see what's happened to watch a video:
https://user-images.githubusercontent.com/80534869/234012138-9578ffb1-620e-498f-a522-db4ef0f1ddbf.mp4

**Comment by nesbox** [comment]
fixed here b43d81456d88f3a953b0e14c7fa3f739c710ffd9
