### ISSUE TITLE
No build for arm64 Raspberry Pi

### ISSUE THREAD

**Issue by cdwfs** [nesbox/TIC-80#2188]
I just updated my RPi 400 from 32-bit Buster to 64-bit Bullseye, and none of the TIS-80 binaries in the latest release seem to work. Is that expected? Would it be straightforward to add this configuration to the release?

**Comment by cdwfs** [comment]
FWIW I was able to build a binary from source for 64-bit Bullseye with no trouble, just following the instructions in the README. Adding GPG keys and setting up the jessie-backports was no longer necessary; I just installed the listed packages through `apt`, and then cmake+make worked without a hitch.

**Comment by nesbox** [comment]
Please update our build files using Pull Request we will release a 64-bit version then.

**Comment by cdwfs** [comment]
😬 I'd love to help, but there's a bit of a gulf between "locally install some packages on an actual 64-bit RPi and run `cmake .. ; make`" vs. "figure out how to correctly extend an unfamiliar project's build setup to support a new platform". Any tips to point me in the right direction? Are the binaries built & tested locally on actual hardware, or cross-compiled from a cloud VM?

**Comment by KGOrphanides** [comment]
Looks like it's a [multiplatform Docker cross-compile](https://docs.docker.com/build/building/multi-platform/) @cdwfs 
(see https://github.com/nesbox/TIC-80/tree/main/build/rpi)

Looks like, to create a aarm64 deb package, at minimum, aarch64-linux-gnu needs to be called instead of arm-linux-gnueabihf in https://github.com/nesbox/TIC-80/blob/main/build/rpi/toolchain.cmake

And https://github.com/nesbox/TIC-80/blob/main/build/rpi/Dockerfile is calling https://github.com/raspberrypi/tools, which is depreciated and also can't do 64-bit.

I'm also super new to Docker builds, but I've made a fork and will do some poking.

**Comment by jackygoule** [comment]
Hello,
I not found build for arm64,and i test build with instructions without successful .
I test to install the build armhf with 
sudo dpkg --add-architecture armhf
Install run ,but tic80 don't run

I need help to run TIC-80 on my ubuntu arm 64 on pi400.

Thanks

**Comment by jackygoule** [comment]
Hello i success to build .
with this commands (ubuntu mate arm64 pi400)

sudo apt-get install git build-essential ruby-full libsdl2-dev zlib1g-dev
sudo apt-get install liblua5.3-dev
sudo apt-get install libcurl4-openssl-dev
git clone --recursive https://github.com/nesbox/TIC-80 && cd TIC-80/build
cmake ..
make -j4

It seem run normally

**Comment by nesbox** [comment]
Great, could you pls add these commands to our Build Instructions https://github.com/nesbox/TIC-80#build-instructions

**Comment by msx80** [comment]
I can confirm the solution by @jackygoule works for Raspberry Pi 5 too! the build was pretty fast too

**Comment by aliceisjustplaying** [comment]
I'll see if I can set up a self-hosted runner to produce builds for now.

**Comment by aliceisjustplaying** [comment]
I've set up a system for unofficial nightly builds in https://github.com/nesbox/TIC-80/pull/2586. See [this section of the README](https://github.com/nesbox/TIC-80?tab=readme-ov-file#unofficial-linuxarm64-nightly-builds) for details.
