### ISSUE TITLE
Bank parameter does not work for exporting music

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#2190]
The `bank` parameter doesn't work for exporting music tracks. Regardless of its value, the music track with the id corresponding to the `id` parameter from the **currently active bank** is exported

Thus, it's not possible to export music from other banks when using TIC-80 from the command line.

**Comment by joshgoebel** [comment]
How are you defining currently active?

**Comment by borbware** [comment]
![image](https://github.com/nesbox/TIC-80/assets/19384640/6609afd7-f199-4826-85f8-7f576490968d)
the one shown on red in the music editor.

**Comment by bztsrc** [comment]
> The bank parameter doesn't work for exporting music tracks. Regardless of its value, the music track with the id corresponding to the id parameter from the currently active bank is exported

According to the code, the function `tic_cart_save` does not have any reference to the "currently active bank" at all. It saves music patterns and tracks like this:
```c
        buffer = SAVE_CHUNK(CHUNK_PATTERNS, cart->banks[i].music.patterns,  i);
        buffer = SAVE_CHUNK(CHUNK_MUSIC,    cart->banks[i].music.tracks,    i);
```
Where `i` is a loop variable and given a value [here](https://github.com/nesbox/TIC-80/blob/main/src/cart.c#L307):
```c
    for(s32 i = 0; i < TIC_BANKS; i++)
```
I can't see how this code could only save the current bank, except `SAVE_CHUNK` checks and skips fully empty (filled with just zeros) banks.

Are you absolutely sure you have valid music data in the other banks too, not just in one?

Hope this helps,
bzt

**Comment by borbware** [comment]
Here's an example cartridge so you can try it for yourself if I'm missing something here.
[exportbankbug.zip](https://github.com/nesbox/TIC-80/files/11466766/exportbankbug.zip)

Consider these commands:
1) `export music megalo.wav id=0 bank=0`
2) `export music fanfare.wav id=0 bank=1`

If you run both the commands, they will export the same song, the one on bank 0 (because it's active by default).
If you go to music editor, disable bank sync (the red ankh symbol), and change the active bank to 1, the song on bank 1 is exported instead.

You can also choose to not disable bank sync: you will still get the song on bank 1 with both the commands, but it will be composed of noise, because the instrument on bank 1 is not defined.

**Comment by borbware** [comment]
If it helps any: my investigations lead me to the function [studioExportMusic](https://github.com/nesbox/TIC-80/blob/main/src/studio/studio.c#L325): it doesn't take the bank in as an argument, only the track.

**Comment by bztsrc** [comment]
Ah I see, it's not when saving a cartridge, but when exporting a wav. That's a different code path.

> my investigations led me to the function studioExportMusic: it doesn't take the bank in as an argument, only the track.

Indeed. I can confirm that wav export uses the bank selector of the studio and not the cli argument ([line 344](https://github.com/nesbox/TIC-80/blob/main/src/studio/studio.c#L344)).
```c
        const Music* editor = studio->banks.music[studio->bank.index.music];
```

Cheers,
bzt

**Comment by borbware** [comment]
Hmm, this looks simple enough that I could try my hand at fixing this myself. Let's see!

**Comment by borbware** [comment]
...not as simple as i thought.

I tried passing `params.bank` to the `studioExportMusic` function, but using

```
const Music* editor = studio->banks.music[bank];
```
instead of 
```
const Music* editor = studio->banks.music[studio->bank.index.music];
```
makes no difference :(

(I checked, the bank param does have the correct value of 0 or 1 inside the function.)

**Comment by borbware** [comment]
okay i found a solution. i'll create a pull request when i have time!
