### ISSUE TITLE
Dev html export not working

### ISSUE THREAD

**Issue by TimotheeGreg** [nesbox/TIC-80#2191]
Building the current dev version, the html export doesn't work well.
When I launch the game it works but if I click somewhere else and then I click back on the game it does not work any more.
Also, when the game works there are lines on top and bottom (and not when we click somewhere else).

You can test here: https://skeptim.itch.io/test?secret=qTgF4JuT8Y6AjQ5Jjnd4Htm5PE

![html_export_itchio](https://github.com/nesbox/TIC-80/assets/26139286/abf62eb2-ea0c-4496-93c9-6ed50c45f0a6)

Note: Others on discord had similar issues. I tried to reproduce theirs to open this github issue but what I get isn't exactly the same.

**Comment by AlecTroemel** [comment]
Interestingly, after clicking outside the game window you can get focus back on the game by hitting tab a couple times. 

Without knowing how the web build really works, it seems like the canvas is missing an `onClick` event?

**Comment by AlecTroemel** [comment]
Looking at older builds, we could be missing a `onmousedown="window.focus()"` on the canvas element
