### ISSUE TITLE
Python indentation

### ISSUE THREAD

**Issue by TimotheeGreg** [nesbox/TIC-80#2199]
That's very cool to have python on TIC-80, thank you very much !

I just started trying it and I saw that if I use a space instead of tab I got the error "SyntaxError: unindent does not match outer indentation level"
I suppose that's not on purpose.

Edit: In fact, it works if I use 4 spaces, but the tabs look like 1 space

**Comment by koltenpearson** [comment]
yeah python does not like mixing tabs and spaces. I am thinking what needs to be done is make a mode that can be turned on for the editor where the tab key will put a space instead of a tab

can anyone think of a better way?

**Comment by TimotheeGreg** [comment]
I don't think we should be able to turn it off because currently this code works and that's not recommended:
![screen9](https://github.com/nesbox/TIC-80/assets/26139286/a7678afd-a36e-4e9d-94fa-732924a72009)

Or in this case a tab should appear like 4 spaces long.

**Comment by TimotheeGreg** [comment]
Also, I see PEP 8 recommends using spaces instead of tab (https://peps.python.org/pep-0008/#tabs-or-spaces), so maybe the demo cart should use spaces

**Comment by TimotheeGreg** [comment]
I just saw that nesbox had planned to add `Tab size` and `Use spaces/tabs` to the config but finally removed it from the "To do" list https://github.com/nesbox/TIC-80/issues/629#issuecomment-720464749

**Comment by Anrock** [comment]
Basically same goes for moonscript that is also indent-based and sensitive to tab/space mixing.
