### ISSUE TITLE
-- buttonlayout: metatag

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#220]
For specifying how joystic buttons are laid out. Proposed values:
`default` - the normal layout (it will be assumed for the carts without the tag)
`snes` - similar to default, but a/b/x/y are laid out as they are on a snes controller
`nes` - standard NES layout. X/Y buttons are smaller and act as start/select respectively.
`fakenes` similar to NES layout but a is before b.

This would make it customizable - in some games having a layout with start/select makes more sense than having arrows+abxy.

**Comment by nesbox** [comment]
users can redefine gamepad buttons directly from the game menu
closing

**Comment by darkhog** [comment]
You misunderstood me. I meant visual layout on the touchscreen. Not keys associated with it., Please reopen it.

**Comment by nesbox** [comment]
yes, I misunderstood you, sorry
so, I don't want to add it to the metatags, but can add to the config
something like
``` lua
GAMEPAD=
{
	POS=
	{
		UP={1,0},
		DOWN={1,2},
		LEFT={0,1},
		RIGHT={2,1},
		A={4,0},
		B={4,2},
		X={3,1},
		Y={5,1},
	},

	...
},
```
you can cpecify position of touch buttons as you wish

**Comment by darkhog** [comment]
No, that should be on per-game basis as some games work better with certain layout that other. So you're designing the game and the gamepad it'd be played on, basically. Think of it like "special" controllers bundled with some games - the signals are basically the same (otherwise you couldn't even try playing Dark Souls on Guitar Hero controller or a DDR mat ;)), but positioning of the buttons are different.

**Comment by nesbox** [comment]
it can be per game if I embed config to the exported game

**Comment by darkhog** [comment]
What if player is loading the game via android app and (in future) surf?

**Comment by nesbox** [comment]
we will use settings from the local config then

**Comment by nesbox** [comment]
You can use `key()` api to handle the keyboard now.
Closing,,,
