### ISSUE TITLE
text selection is not inverting some text

### ISSUE THREAD

**Issue by timofey260** [nesbox/TIC-80#2203]
![image](https://github.com/nesbox/TIC-80/assets/69044246/fbe17659-16b6-466d-a04c-183cb73de777)

if i select a normal text in console, its color is inverted, but for colored text, it's not
is it work intended way or it's just a bug?

**Comment by TimotheeGreg** [comment]
I don't understand, sorry.
When you select something the background takes the color of the font (and gets white if no character) and the font goes black, that's the same for colored text. Did I misunderstood something?

**Comment by timofey260** [comment]
Why background does not change when selecting rainbow background and why colored font is not changing when selecting it?

**Comment by joshgoebel** [comment]
In console selection merely means in inversion of foreground an background - which is exactly what is shown in your snap.  AFAIk this has always been the behavior and is the intended behavior.

**Comment by timofey260** [comment]
alright, thanks
