### ISSUE TITLE
Wiki docs mismatch on OVR vs BDR calling order

### ISSUE THREAD

**Issue by AMcBain** [nesbox/TIC-80#2205]
Both [the API wiki page](https://github.com/nesbox/TIC-80/wiki/API#sequencing) and [the OVR wiki page](https://github.com/nesbox/TIC-80/wiki/OVR) indicate the rendering order is `TIC`, `BDR`, `OVR` however the small program below seems to indicate otherwise:

```Lua
t=0

function TIC()
 t=t+1
 trace('TIC '..t)
end

function BDR(s)
 if s==0 then
  trace('BDR start '..t)
 end
 if s==143 then
  trace('BDR end '..t)
 end
end

function OVR()
 trace('OVR '..t)
end
```

Unless there's weird reordering of trace calls to the console, this will output the following
```
>TIC 1
>OVR 1
>BDR start 1
>BDR end 1
>TIC 2
>OVR 2
>BDR start 2
>BDR end 2
```

I noticed this when writing a larger tech demo that can generate more than 15 colors + background on scanlines so I saved the pixel locations and color, then drew them in OVR. The misdocumented ordering meant my painting of pixels in OVR based on stuff generated in BDR will always be one cycle/frame behind.

I don't know how many carts depend on the ordering or how long its been this way, but it might be easiest to just update the docs.

**Comment by joshgoebel** [comment]
This may have changed.  OVR is deprecated now though, one should always use just BDR.

**Comment by AMcBain** [comment]
As far as I'm aware only [SCN](https://github.com/nesbox/TIC-80/wiki/SCN) is deprecated. If that's not the case, then the wiki *definitely* needs updated.

I don't care what order they're in (I updated my code to figure everything out beforehand so it doesn't matter), just so long as the docs match it.

**Comment by joshgoebel** [comment]
> As far as I'm aware only [SCN](https://github.com/nesbox/TIC-80/wiki/SCN) is deprecated.

My bad, you're right. :-)

**Comment by joshgoebel** [comment]
I corrected the ordering.
