### ISSUE TITLE
TIC-80 version mismatch between Local and Web

### ISSUE THREAD

**Issue by fosskers** [nesbox/TIC-80#2207]
Thank you for this amazing tool! 

I hit an issue today in publishing my first game, which was made with a `tic80` built from `master` (I have donated :pray: ). I wrote my game in an external editor, and when I was ready to publish I did a manual `save`, renaming the file to `snake.tic` and then uploading that. 

Upon trying to play the game on the TIC-80 site, I'm shown this:
![tic-error](https://github.com/nesbox/TIC-80/assets/229679/1b844284-7b24-420e-a9b9-5d0845dbb3c8)
 
My only use of `&` is in a few Fennel macros like:
```fennel
(fn any? [p coll]
  "Does any element of the collection satisfy the predicate?"
  (accumulate [found false _ x (ipairs coll) &until found]
    (p x)))
```
I notice that the web version is using the official release from May of last year. Since then, this PR was merged: https://github.com/nesbox/TIC-80/pull/2130 and I'm guessing that this difference is the reason my game doesn't work on the site.

If I'm right about the Fennel version mismatch, would it be possible to make a fresh release of TIC-80 to reflect the newer Fennel? In the meantime I can try to refactor such that I'm not using a `&until` clause.

Thank you!

**Comment by nesbox** [comment]
It's possible, we need to release the current dev version for this.
Don't know when it will happen, we still have some tasks open https://github.com/nesbox/TIC-80/projects/6

**Comment by fosskers** [comment]
In the meantime, I worked around this issue by removing the `&until` clauses I was using, which apparently were added in Fennel 1.2.0.

**Comment by fosskers** [comment]
Fennel 1.3.1 was recently released.

**Comment by nesbox** [comment]
web version will be updated after release
