### ISSUE TITLE
cls() doesn't respect color swapping

### ISSUE THREAD

**Issue by S0ZDATEL** [nesbox/TIC-80#2214]
If the colors are swapped by poking palette map, cls() still uses the original colors. For example:
```
function BOOT()
 poke4(2*0x3FF0+1,0) -- replace color 1 with color 0
end

function TIC()
 cls(1) -- fill the screen with color 1 (which should be 0 (but isn't))
 rect(20,20,200,96,1) -- draw a rectangle of color 1 (which is now 0, as intended)
end
``` 
This code should display a rectangle the same color as the background, so we shouldn't see anything. And yet we see a rectangle and the background in different colors, because cls() doesn't respect color swapping and uses original color 1, while rect() uses color 0 because of the swap.

**Comment by joshgoebel** [comment]
Hmmm, this does sound like a bug to me, but it also would be a pretty obvious breaking change.
