### ISSUE TITLE
[Support] 1.0 cant run on Android 6.0

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#2219]
I guess the app updated that much it cannot run anymore on low android version. Is it possible to lower the required android version of the app? 0.90 seems working fine but I cant find pro version anymore, it got replaced on itch.io by 1.0. If changing android required version is not the case is it possible to download 0.90 pro without building it?

**Comment by nesbox** [comment]
we depend on SDL2 library which doesn't support the lower Android version
