### ISSUE TITLE
Invalid mouse sprite ID corrupt/crash TIC-80

### ISSUE THREAD

**Issue by MegadronA03** [nesbox/TIC-80#2220]
related to poke(0x3ffc, x>130)
may be "error in error handling" - 235
may carsh - 233 234 239
crashes - 251 250 249 248 241 238 236 228 207 206 203 202 197 195 192 190 165  -6 -7
crash if drag to the top - 217 209 212 229
crash due to mouse movement - 235
cursor causes vram and config corruption - 209 212 229
offsetted (-x) - 191 220
offsetted (+x-y) - 229
scanline corruption on bottom and top left conners

there are other values that make appear cursor as something, but I only listed problematic ones

**Comment by nesbox** [comment]
fixed here 2324f28c483779d86c3a764efd9a553a3c2ed1e1
