### ISSUE TITLE
In Code Editor on an Extended Cart you can select the word and paste through causes crash TIC-80

### ISSUE THREAD

**Issue by MasterNama17083** [nesbox/TIC-80#2221]
**In Fact: Extended Cart _has_ limited 524K Bytes of Code _(For PRO Version)_**

If you do this to try out:

- **Step 1.** You have an extended cart brought from TIC-80 surf or something with 524K bytes to open the code editor.

- **Step 2.** Select the piece of code via cursor.

- **Step 3.** Paste it from locating here results crash the application.
#
https://github.com/nesbox/TIC-80/assets/80534869/e90abda7-2979-4459-afeb-e3a77b3615b1

Unfortunately, You have a non-pro version check for an extended cart that has 524K Bytes in the code editor it doesn't get pass-through code space via type on the keyboard.

**Comment by nesbox** [comment]
fixed here 1b58c71fec600d3036d63962526570c932acf352
