### ISSUE TITLE
how do i use the command export on tic 80

### ISSUE THREAD

**Issue by Antonygamergod** [nesbox/TIC-80#2226]
i use the command so much times like "export html" "export cart to html" but no one of this work how i export the frickin archive to html
![imagem_2023-07-03_174122267](https://github.com/nesbox/TIC-80/assets/77341150/c7517162-4c87-4f3f-9db4-1f70ab8e0a6f

**Comment by scambier** [comment]
![image](https://github.com/nesbox/TIC-80/assets/3216752/23e9d8eb-9737-42b7-8042-fadb0baed617)

`export html myexport`

**Comment by Antonygamergod** [comment]
Ok thank you
