### ISSUE TITLE
Ruby does not have OVR() callback support

### ISSUE THREAD

**Issue by AlexanDDOS** [nesbox/TIC-80#2235]
I wanted to use the `OVR()` callback to implement some nice interface for my first TIC-80 game on Ruby, but it turned out Ruby does not support it, unlike Lua

Lua example:
```lua
function TIC()
  cls(13) --Clear screen
end
function OVR()
  print("Hello world!",84,84) --Works fine
end
```

Ruby example:
```ruby
def TIC
  cls 13 #Clear screen
end
def OVR
  print "Hello world!",84,84 #Does not work!!!
end
```

Am I the only person who experiences it, and if I am not, can it be fixed for the future release?

**Comment by nesbox** [comment]
Unfortunately, `OVR()` was deprecated and we leave it in Lua for backward compatibility.
Pls use `vbank()` api In the new langs.
https://github.com/nesbox/TIC-80/wiki/vbank
