### ISSUE TITLE
Can't build latest version on macOS due to Janet issue

### ISSUE THREAD

**Issue by soxfox42** [nesbox/TIC-80#2241]
Attempting to build the latest version of TIC-80 from source on macOS fails due to a Janet build failure.
The error is specifically to do with a missing `O_CLOEXEC` define. A fix for this was pushed to Janet upstream about two months ago: https://github.com/janet-lang/janet/commit/2a6c615becc2268ec1ea52b80a1cea5e86cb778a.
Updating the Janet submodule to v1.29.1 allows the build to succeed.

**Comment by soxfox42** [comment]
(This issue might only occur on the macOS 14 Sonoma beta, I don't currently have a macOS 13 setup to test with.)

**Comment by nesbox** [comment]
waiting the PR #2244

**Comment by AlecTroemel** [comment]
@soxfox42 can you pull the latest changes to the master branch and try again? Janet version was upgrade in this commit https://github.com/nesbox/TIC-80/commit/cd05d0ab033e30e710de1cfefbc1375876ded605!

**Comment by soxfox42** [comment]
Finally got around to testing it, fresh build worked fine for me, so I'd say this is fixed.
