### ISSUE TITLE
TIC-80 freezes when editing code in external editor

### ISSUE THREAD

**Issue by src3453** [nesbox/TIC-80#2247]
## Problem
On the professional version of the TIC-80, when editing code with an external editor while the code is running, the TIC-80 may freeze with only the background of the menu screen and an interrupted beep. The screen cannot be closed by pressing the close button. (Oddly enough, this did not happen when music was not playing.)
## Reference image
![Animation](https://github.com/nesbox/TIC-80/assets/103661526/d5adc9a4-a1af-4ed9-ac32-0c055755a79e)

**Comment by andreyorst** [comment]
I had to deal with this pretty often lately while working on a game, and noticed that this only happened when I edited the cart both in the editor and in TIC itself (e.g. changed sprites, waves, etc.).

Pressing <kbd>Ctrl</kbd>+<kbd>S</kbd> on the screen unfreezes TIC and you can choose in the menu what to do, as it shows that the cart was modified.

**Comment by nesbox** [comment]
fixed here 9aee18c10bff7418704027d12fee89425bf6825e
