### ISSUE TITLE
[Bug] [QuickJS] Array destructuring causes a crash

### ISSUE THREAD

**Issue by scambier** [nesbox/TIC-80#2251]
I have built TIC-80 on Windows 10, with the following commands:

- `git clone --recursive https://github.com/nesbox/TIC-80 && cd TIC-80/build`
- `cmake -G "Visual Studio 16 2019" -DBUILD_PRO=On -DBUILD_SDLGPU=ON -DCMAKE_BUILD_TYPE=MinSizeRel ..`
- Rebuild Solution in VS2019

To reproduce:

- Open TIC-80 1.1.2684
- `new js`
- Add the following line in the `TIC()` function:

```js
const [x, y] = mouse()
```

- Reload the cart

![image](https://github.com/nesbox/TIC-80/assets/3216752/92969d7c-7c49-4b42-9f71-bc7cc2aba72f)

I can click "Ignore" several times and then the cart loads "normally" but I can't escape it (editors are unavailable)

---

The problem doesn't exist when TIC-80 is built on MacOS

**Comment by soxfox42** [comment]
@nesbox, found the problem and opened a PR on your QuickJS fork. It's not exactly a true bug, just MSVC being extra careful, since while `label_lvalue` is being passed to another function, it's not being used in this case.

**Comment by scambier** [comment]
It's fixed, thanks :)
