### ISSUE TITLE
Some keys are not working

### ISSUE THREAD

**Issue by Kitsuinox** [nesbox/TIC-80#2265]
I'm on TIC-80 1.1.2729 (20dcf59) in the code editor and some of the keys (", *, <, and the keys that require the ALT-GR + numbers as well as a few others) do not work on my Turkish-Q keyboard. Probably has something to do with #707.

**Comment by rnielikki** [comment]
This.
The app recognises `AltGr` key as `Alt` key
For example `AltGr`+`2`, I expected `@`, but instead the app shows the sprite editor (`Alt`+`2`)
Also I cannot put`<`, but can put `>` (with `shift`), this is so weird
My keymap is Finnish by the way.

In version 1.0, the key input works as expected (normally) and doesn't have the issue

**Comment by scambier** [comment]
There have been several reports on the Discord about issues with non-qwerty keyboards. I use an azerty layout, and  (for example), can't type the closing parenthese `)` in the code editor. Though it works in the CLI.
