### ISSUE TITLE
Sprite editor touch screen not working properly(Android)

### ISSUE THREAD

**Issue by MateusH7** [nesbox/TIC-80#2270]
when I try to draw something using the touch screen sometimes it will be painted in more than one place that I pressed to paint and sometimes even the whole rectangle for example I want to paint only (x1,y2) the whole line of x1 will be painted without me having pressed this area is like having the mouse pressed the whole time.

**Comment by sogaiu** [comment]
I tried here and noticed something similar.

Below are a couple of work-arounds (for the short term?):

1) I connected a pointing device via USB.  In that case using the device, I (more often?) see the graphical arrow indicating where I might be drawing and I didn't tend to end up seeing a line being drawn from one of the corners.

2) If using one's finger or stylus, first touch outside of the square area containing the image.  This seemed to reliably cause the graphical arrow to appear.  Then dragging one's finger or stylus to where one wants to draw from, lifting and then pressing the screen seemed to avoid the described issue of drawing in more than one place (at least the line forming unexpectedly seemed to stop here).

**Comment by MateusH7** [comment]
> I tried here and noticed something similar.
> 
> Below are a couple of work-arounds (for the short term?):
> 
> 1) I connected a pointing device via USB.  In that case using the device, I (more often?) see the graphical arrow indicating where I might be drawing and I didn't tend to end up seeing a line being drawn from one of the corners.
> 
> 2) If using one's finger or stylus, first touch outside of the square area containing the image.  This seemed to reliably cause the graphical arrow to appear.  Then dragging one's finger or stylus to where one wants to draw from, lifting and then pressing the screen seemed to avoid the described issue of drawing in more than one place (at least the line forming unexpectedly seemed to stop here).
> 

Thanks this really solve this problem.

**Comment by sogaiu** [comment]
Hopefully there can be some solution to this so that no work-arounds are necessary :)
