### ISSUE TITLE
Windows detects export as 'Virus'

### ISSUE THREAD

**Issue by sandmuel** [nesbox/TIC-80#2275]
As the title suggests, windows detects executable exports as simply a 'Virus'
I'm assuming this may be related to https://github.com/nesbox/TIC-80/issues/2025.

**Comment by sandmuel** [comment]
Note: I don't personally use Windows so I can't test anything. The only reason I know of this issue is because I sent my export to someone on Windows.

**Comment by Anrock** [comment]
Windows detects any non-widespread freshly created binary as a virus.

**Comment by nesbox** [comment]
This happens every time, Windows treats the tic80.exe binary as a virus in every release, but recognizes it as a false positive after a while and everything is fine. For example, I uploaded the latest binary to **Virustotal** and it didn't find anything dangerous.
https://www.virustotal.com/gui/file/67dded2e7cb03f922b6df1c4ee1e99e84d5b2f4f4eb71c18595ba7aa6da90689?nocache=1
![image](https://github.com/nesbox/TIC-80/assets/1101448/cdb3ce43-2665-438b-b53e-5acaba7ae30e)

**Comment by sogaiu** [comment]
I don't know if this applies, but I've been finding that in recent times, the options for downloading might need to be "teased out" via a process of clicking on things that don't immediately seem relevant.
