### ISSUE TITLE
Can't disable Janet when building

### ISSUE THREAD

**Issue by Doodlinka** [nesbox/TIC-80#2279]
I was trying to build TIC on Window 10 with MinGW64 from Git Bash and ran into a [weird issue](https://pastebin.com/ZsWZcByY) with the Janet part, so I decided to exclude it. I tried to set -DBUILD_WITH-JANET to 0 and FALSE but the console output was the same, even claiming Janet is still enabled. Editing CMakeLists.txt to set(BUILD_WITH_JANET_DEFAULT FALSE) (line 497) had no effect either. This error went away only when I commented out the entire Janet section.

Is this a bug? If Janet is supposed to be required, why does the flag exist? Also, is there a list of all build options? I intend to only use Lua, so would prefer to disable anything that isn't required.

**Comment by sogaiu** [comment]
Not that far back it was possible to disable.

The error message linked to suggests that Git Bash is required and FWIW there is mention of something similar [here](https://github.com/nesbox/TIC-80/issues/2163#issuecomment-1575686195).  Not sure if that's related.

**Comment by Doodlinka** [comment]
i found out -DBUILD_WITH-JANET is actually spelled -DBUILD_WITH_JANET, but the "set to false at line 497" still holds

**Comment by nesbox** [comment]
This is because BUILD_WITH_JANET is an option and it saves previously assigned values in the cache.
Try to clear the cache by deleting `CMakeCache.txt` file or pass `BUILD_WITH_JANET=Off` directly to the cmake command:
`cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_WITH_JANET=Off ..`

**Comment by Doodlinka** [comment]
what do the other flags in this command do?
cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_WITH_JANET=Off ..

**Comment by sogaiu** [comment]
IIUC, `-G Ninja` has to do with the build system cmake will generate for (in this case Ninja).  More on cmake generators [here](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html).

`-DCMAKE_BUILD_TYPE=MinSizeRel` seems to be documented [here](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) and there's a [relevant SO question](https://stackoverflow.com/questions/48754619/what-are-cmake-build-type-debug-release-relwithdebinfo-and-minsizerel).
