### ISSUE TITLE
Help for the wiki

### ISSUE THREAD

**Issue by TimotheeGreg** [nesbox/TIC-80#2289]
Hi,

I contributed a lot to the wiki recently, but I have reached a point where I could use some help.

Concerning my contributions, you will find the diff [here](https://github.com/nesbox/TIC-80/wiki/_compare/1f08a9dbd0703fd1cd605a934dae1b0560bc11a4...8157e13c6632e50f222164e25ffdb4b4c64e11e9?diff=split).
Among other things, I created new pages: [Configuration File](https://github.com/nesbox/TIC-80/wiki/System-Configuration-Cartridge), [Cover Image](https://github.com/nesbox/TIC-80/wiki/Cover-image), [Map Editor](https://github.com/nesbox/TIC-80/wiki/Map-Editor), [TIC-80 Menu](https://github.com/nesbox/TIC-80/wiki/TIC%E2%80%9080-Menu), [Beginners' Tips](https://github.com/nesbox/TIC-80/wiki/Beginners'-Tips). I changed The Code page to [Code Editor](https://github.com/nesbox/TIC-80/wiki/Code-Editor) and [Metadata](https://github.com/nesbox/TIC-80/wiki/Cartridge-Metadata) pages. I also updated old GIFs, and made new ones to illustrate example codes etc here and there. And countless other things.
However, I am a physicist not a programmer so I did not touch the too technical parts like RAM/VRAM, .tic format, etc.

Here are several points on which I want to modify the wiki but I would need help:
Import/Export:

- [x] On the [Console](https://github.com/nesbox/TIC-80/wiki/Console) page and in the help command, there are `...` in the list of arguments of `import`/`export`. Why?

- [x] There is not `alone=1` in the list of `export` arguments because it's a pro feature but there is `bank` which is a pro feature too. Why? Can we access the banks from `export` without the PRO version?
- [x] Probably a naive question here, but in which context is the `binary` argument used?

Input tag:
- [x] I don't understand the `input` tag: the wiki only mentions "mouse" keyword, I suppose there is "button" and "keyboard" too. Also I don't understand what it does, why is it necessary? If I only have `mouse()` function and no `btn` or `key` in my code then why would I need to disable keyboard?

Hotkeys:
- [x] Many hotkeys were missing, I continue to discover new hotkeys from time to time, can I find an exhaustive list somewhere maybe in the code (I didn't find myself).
- [x] There are probably missing hotkeys in sfx editor for instance.

Config file:
- [x] What is gamepad>touch>alpha configuration option?

Here are things that may need improvement but I don't think I am the good person to do it as I don't know much about these subjects. I don't want to risk writing mistakes on the wiki:
- There is no documentation about fennel `;; strict: true` tag on the wiki. I put a "TODO" about it on the [Supported Languages](https://github.com/nesbox/TIC-80/wiki/supported-languages#fennel-strict-tag) and the [Metadata](https://github.com/nesbox/TIC-80/wiki/Cartridge-Metadata) pages with a link to the pull request.
- The [Sprite-Editor](https://github.com/nesbox/TIC-80/wiki/Sprite-editor) page needs something about the two palettes, vbank and VRAM.
- The [vbank](https://github.com/nesbox/TIC-80/wiki/vbank) and [VRAM](https://github.com/nesbox/TIC-80/wiki/RAM) pages might need some work too. At least I have interrogations, here they are:
    - The vbank page says "This is most commonly used for layering effects", but can it be used just to have more colors?
    - I don't understand what VRAM is. I suppose it means Virtual RAM but it's not written anywhere and I don't understand the concept. However I probably don't need to understand it, but as it's mentioned I am curious.
    - Does the VRAM only concern the palette?
    - The [vbank](https://github.com/nesbox/TIC-80/wiki/vbank#examples) page is missing an example.

One last suggestion: I think we could showcase the wiki more. Maybe the LEARN tab on tic80.com could redirect directly to the wiki. Or the link could be larger and more central.

Note: I contributed during holidays, I am back to work so I will contribute when I have time and motivation. Do not hesitate to make the modifications yourself.

Thanks again for this project I love! I hope my contributions will help :smiley:

**Comment by joshgoebel** [comment]
>The vbank page says "This is most commonly used for layering effects", but can it be used just to have more colors?

Yes. 16 palette colors per layer, but vbank needs one color to be transparent, so only 31 colors really, not 32.

> I don't understand what VRAM is. 

Video RAM. https://en.wikipedia.org/wiki/Video_random-access_memory

> Does the VRAM only concern the palette?

No.  It concerns everything listed that is present in VRAM as shown in the memory map docs. https://github.com/nesbox/TIC-80/wiki/RAM#vram

Such as the full SCREEN data, palette, border colors, BLIT modes, etc...

**Comment by joshgoebel** [comment]
> so I did not touch the too technical parts like RAM/VRAM, .tic format

Yeah, I'd prefer most people leave those alone unless they really know their stuff.  I kind of used to "own" maintaining wiki but I've had less free time lately so I haven't kept up with it... I'm still very interested in helping with the API and technical stuff though (keeping it up to date and error free)... so if you have any specific questions there feel free to ask.

Less knowledge and less motivated to help in all the other areas (describing all the editor features in detail, etc)...

**Comment by sogaiu** [comment]
Regarding:

> On the [Console](https://github.com/nesbox/TIC-80/wiki/Console) page and in the help command, there are ... in the list of arguments of import/export. Why?

It appears the strings in question with `...` were added in [this commit](https://github.com/nesbox/TIC-80/commit/f029595cc104282ce4c9e0e32e0f31a59fa39819).

So may be the author of that commit would know :)

**Comment by TimotheeGreg** [comment]
> I kind of used to "own" maintaining wiki but I've had less free time lately so I haven't kept up with it...

Yes, I've seen that, thanks for your work! Honestly, all important information were on the wiki already, my modifications were just further improvements here and there. And I spent an active week on the wiki, but I don't know if I will continue to contribute on the longer term.
If there are some modifications I did you don't like feel free to change them.

> Yeah, I'd prefer most people leave those alone unless they really know their stuff.

Perfect, I won't touch vbank, VRAM, strict tag, etc. Feel free.

**Comment by nesbox** [comment]
> On the [Console](https://github.com/nesbox/TIC-80/wiki/Console) page and in the help command, there are ... in the list of arguments of import/export. Why?

I do not remember why :) we can remove it

**Comment by nesbox** [comment]
`alone=1` and `bank=<id>` are both pro features I think

**Comment by TimotheeGreg** [comment]
I removed the `...` from the wiki and added `alone=0` to the list of arguments. It is still mentioned in the description that `alone` is a pro feature.

**Comment by TimotheeGreg** [comment]
> I'm still very interested in helping with the API and technical stuff though (keeping it up to date and error free)... so if you have any specific questions there feel free to ask.

On the discord softmagic was struggling with ttri perspective correction:

> there's some perspective distortion. it does not help that TIC-80's ttri function is undocumented in the case of perspective correction
>i only know i can give the function points z1,z2 and z3 - but i have no idea what these mean without trial and error!

**Comment by joshgoebel** [comment]
Sorry I don't know, that's newer behavior... the wiki does say:

> This function does not perform perspective correction, so it is not generally suitable for 3D graphics

And the top mentions "texture correction", not perspective... but I have no idea on this one.  Sorry.

**Comment by TimotheeGreg** [comment]
Ok, no problem! Thanks

**Comment by sogaiu** [comment]
> in which context is the binary argument used?

Don't know but the following might be clues:

I think [these lines](https://github.com/nesbox/TIC-80/blob/c3b90f951bf9022032abbb79cb31d2c67116bf6d/src/studio/screens/console.c#L1772-L1784) are involved and when searching across the repository I see example uses in templates / instructions related to C, D, Rust, and Zig:

* https://github.com/nesbox/TIC-80/blob/c3b90f951bf9022032abbb79cb31d2c67116bf6d/templates/c/buildcart.sh#L5
* https://github.com/nesbox/TIC-80/blob/c3b90f951bf9022032abbb79cb31d2c67116bf6d/templates/d/buildcart.sh#L5
* https://github.com/nesbox/TIC-80/blob/c3b90f951bf9022032abbb79cb31d2c67116bf6d/templates/rust/README.md?plain=1#L20
* https://github.com/nesbox/TIC-80/blob/c3b90f951bf9022032abbb79cb31d2c67116bf6d/templates/zig/README.md?plain=1#L12

May be if you write a cart in C, D, Rust, or Zig, part of the process of getting that working is to compile to wasm and then import the result?

**Comment by joshgoebel** [comment]
Yes, `import binary` is how you get the BINARY segment into the cartridge, which is what WASM cartridges run.

**Comment by TimotheeGreg** [comment]
Ok, thanks! I won't add it to the Console page, as long as it's on the WASM page.

**Comment by TimotheeGreg** [comment]
I understood that the `input` tag is for displaying the gamepad and/or keyboard on Android so I modified this part on the Metadata page https://github.com/nesbox/TIC-80/wiki/Cartridge-Metadata#the-input-tag
However, I don't have an Android device myself so I can't test it to verify.

**Comment by sogaiu** [comment]
I tried the `mouse`, `keyboard`, and `gamepad` values for the input tag on an Android tablet.

They seemed to work as advertised at least in the version of TIC-80 I had installed.
