### ISSUE TITLE
Some keys are not working with foreign keyboard (i.e. right parenthesis for azerty layout)

### ISSUE THREAD

**Issue by sdaclin** [nesbox/TIC-80#2310]
Unfortunately this closed issue doesn't solve the problem for french layout AZERTY and the right parenthesis isn't working at all.
* https://github.com/nesbox/TIC-80/issues/2265#issuecomment-1684931628

# How to reproduce 

* switch your layout to french keyboard (here is the visual keymap https://fr.wikipedia.org/wiki/AZERTY#/media/Fichier:KB_-_AZERTY_-_FR_-_Windows_-_FR.png)
* run tic-80 and open the script editor
* try to enter a right parenthesis `)`

Nothing happen

# Corrupted versions

* https://github.com/nesbox/TIC-80/tree/v1.1.2736
* https://github.com/nesbox/TIC-80/tree/v1.1.2729

# Last working version

* https://github.com/nesbox/TIC-80/tree/v1.0.2164

**Comment by TimotheeGreg** [comment]
I can’t reproduce it on Linux Ubuntu for some reason :man_shrugging:  but someone on the discord had the same problem on Windows and Linux with a Finnish keyboard and the +, - and < keys.

**Comment by scambier** [comment]
I use a (belgian) azerty on windows, I can't type (at least) those keys: `< ) : $`

I also can't type `[ ]` using alt+gr, but it works with ctrl+alt. `{ }` work fine with alt+gr.

**Comment by helgrima** [comment]
I use Finnish keyboard and + and < don't work on Windows or Linux.

**Comment by jezv** [comment]
I'm using a UK qwerty keyboard.  The '#' key works on the console screen but not on the code editor screen

**Comment by daniskarma** [comment]
Windows version 1.1.2736
Spanish QWERTY keyboard
On the command line I can write all characters. But in the code editor I cannot use: + ] { } <

**Comment by PFLAtm** [comment]
German QWERTZ keyboard 
cannot write | < # + § \ in the code editor

**Comment by sdaclin** [comment]
I've tested artifact from the PR and it works as expected !
Thanks a lot for yourwork @nesbox <3
https://github.com/nesbox/TIC-80/actions/runs/6525000543
