### ISSUE TITLE
Add command shows dialog in chrome but no way to submit file at https://tic80.com/create

### ISSUE THREAD

**Issue by jcollard** [nesbox/TIC-80#2313]
I am unable to use the `add` command in the web browser to add a file. I receive a dialog and can select a file but cannot submit the form. Any help is appreciated.

![no-submit-button](https://github.com/nesbox/TIC-80/assets/3529380/0bd43433-7ad4-4722-9978-26a123a59a18)

**Comment by nesbox** [comment]
fixed here 59ff33bb14d0654c157c012da996fafff5317028 but on the website will be updated after release
