### ISSUE TITLE
python pocketpy linalg vec2 class methods crash when called

### ISSUE THREAD

**Issue by jezv** [nesbox/TIC-80#2317]
version 1.1.2736 (https://github.com/nesbox/TIC-80/commit/59ab3594e522a4ef553d6ed8eea29aa7728dcf87)
windows 11

repro steps:

1. .\tic80.exe --fs=./test --scale=6
2. new python
3. SC to enter code editor
4. add the following after the line y=24

```
y=24

from linalg import vec2
vec2(0,0).dot(vec2(0,0))
```

results in runtime error

```
>error while processing the main code

>Traceback (most recent call last):
  File "<c-bound>", line 14
    vec2(0,0).dot(vec2(0,0))
TypeError: expected 0 arguments, but 
got 1
```

maybe related to https://github.com/nesbox/TIC-80/issues/2316

**Comment by blueloveTH** [comment]
Let me check this please.

**Comment by blueloveTH** [comment]
![image](https://github.com/nesbox/TIC-80/assets/28104173/d04fd78c-11c3-4cfe-89cb-d76e8f4f4e64)
![image](https://github.com/nesbox/TIC-80/assets/28104173/94fcb2e8-39b4-4162-8a3c-a8cf43f9debf)

Fixed.
