### ISSUE TITLE
Can not import (add) game file in browser version of TIC-80

### ISSUE THREAD

**Issue by Vodorohelios** [nesbox/TIC-80#2320]
When I try to load a game file, my browser (google chrome) opens a dialog where I choose path to the file, but after this nothing happens. I see a window with a file name that I chose. And if I close this window nothing happens. Cart isn't added.

**Comment by TimotheeGreg** [comment]
That seems to be the same issue than #2313 
The problem is the same with Firefox on Linux too.

**Comment by nesbox** [comment]
close as duplicate
