### ISSUE TITLE
can't input certain characters in Spanish (Dominican Republic) layout

### ISSUE THREAD

**Issue by thacuber2a03** [nesbox/TIC-80#2328]
(Linux, Pop!_OS 22.04, Cinnamon DE)
I am unable to write ^, {, } and ~, and for most languages, the first and last wouldn't be a problem, but ^ is necessary in Moonscript to export all symbols that start with an uppercase letter, { and } are necessary for tables in Lua, maps in Python, and are a requirement to use Wren, Squirrel and JavaScript, so currently I'm only able to use the embedded lisps and WASM.

**Comment by sogaiu** [comment]
Possibly related? #2310

**Comment by thacuber2a03** [comment]
wait, really? I thought that because it was closed it was solved...

**Comment by sogaiu** [comment]
As the original description above didn't mention the version of TIC-80 tested, it seemed worth mentioning #2310 :)

**Comment by nesbox** [comment]
dup of #2310

**Comment by thacuber2a03** [comment]
yeah, sorry about that, I thought it wasn't relevant anymore
