### ISSUE TITLE
Release with foreign keyboard key fix

### ISSUE THREAD

**Issue by TimotheeGreg** [nesbox/TIC-80#2329]
Hi @nesbox,
We are several persons on the github to think that the fix for foreign keyboard keys (https://github.com/nesbox/TIC-80/commit/4212d28ef7791f64a05dbba4fdb193edea8a6b28) is quite critical, so we want to encourage of a release with this fix. Would that be possible?
Thanks in advance!

**Comment by nesbox** [comment]
yes, we can release it, but before, could you pls test it to make sure it works
you can download the latest build here https://nightly.link/nesbox/TIC-80/workflows/build/main
thanks

**Comment by TimotheeGreg** [comment]
Great! I just tested the linux-deb version with a French AZERTY, German QWERTZ and UK QWERTY I got no problem, I can type everything in the code editor.

**Comment by pruebaoscar** [comment]
Hi all, just tested in windows 11 with spanish keyboard layout, all keys are working. Thanks!
PD: could be possible release the pro version with this fix? 
Thank you!

**Comment by nesbox** [comment]
released v1.1.2837
