### ISSUE TITLE
Windows Defender detects TIC80 v1.1.2837 as virus - Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by arcade-mntra** [nesbox/TIC-80#2337]
Was eager to try the updated python bindings but Windows Defender detects and deletes v1.1.2837 release file as a trojan with Threat Level = Severe.

I hope this is a false positive since previous versions did not invoke such an alert from Windows Defender. 
Even as a false positive, it will affect adoption and usage by new users if others are also getting a virus alert on Windows.

Reproduction steps:
1. OS Windows 10
2. Download [tic80-v1.1-win.zip](https://github.com/nesbox/TIC-80/releases/download/v1.1.2837/tic80-v1.1-win.zip)

![TIC80_v1 1 2837-win_detected_as_virus](https://github.com/nesbox/TIC-80/assets/118503637/adcdbbef-baa7-4f50-b836-68e91fc0b866)

**Comment by sogaiu** [comment]
Tried to reproduce...

I downloaded what seemed like the `.zip` file from a link on [this page](https://github.com/nesbox/TIC-80/releases/tag/v1.1.2837) on to a device running Windows 10.

I right-clicked on the resulting `tic80-v1.1.zip` in Windows explorer and chose the "Scan with Microsoft Defender..." item.

In my case I got something along the lines of:

```
No current threats.
Last scan: ...
O threats found
Scan lasted 1 seconds
3 files scanned
```

So in my case, it seems that nothing was detected.

---

FWIW, I used `certutil` to calculate a sha256 checksum:

```
C:\Users\user\Downloads>certutil.exe -hashfile tic80-v1.1-win.zip sha256
SHA256 hash of tic80-v1.1-win.zip:
12aa47e205072c4960d86316f8940da862bf3429f1adba0ef70c5441caa6de0e
CertUtil: -hashfile command completed successfully.
```

**Comment by Anrock** [comment]
Virustotal also shows [0 detections](https://www.virustotal.com/gui/file/12aa47e205072c4960d86316f8940da862bf3429f1adba0ef70c5441caa6de0e/detection).

Windows Defender is known to false positevely mark any "fresh" executables until they earn enough "reputation". So nothing can be done, just wait until Windows Defender starts thinking that file is "known" enough.

**Comment by arcade-mntra** [comment]
> Windows Defender is known to false positevely mark any "fresh" executables until they earn enough "reputation". So nothing can be done here, just wait until Windows Defender starts thinking that file is "known" enough.

You are correct. Just now download the file and there's no popup from Windows Defender. 
Time to test drive the updated python version :)
