### ISSUE TITLE
Smallfont printing doesn't work under Python

### ISSUE THREAD

**Issue by deananorth** [nesbox/TIC-80#2338]
Version: TIC-80 1.1.2837 Pro running under Windows 10 22H2 build 19045.3570

## Affected code

```lua
-- Lua code for the purposes of control

function TIC()
	cls(15)
	print("HELLO WORLD!",5,5,12,false,1,true)
end
```

Lua output

![image](https://github.com/nesbox/TIC-80/assets/59711369/ca220306-18fc-474d-9266-5f132eb83ae2)

```python
# Affected Python code

def TIC():
	cls(15)
	print("HELLO WORLD!",5,5,12,False,1,True)
```

Python output

![image](https://github.com/nesbox/TIC-80/assets/59711369/39bff60a-9867-436b-abcb-49809823c836)

## Expected result:

Python print statement should produce smallfont output in the same way
that the Lua print statement should.

## Actual result:

The Smallfont parameter (the `True` on the right) is ignored and the full sized font is printed
to the screen.

**Comment by TimotheeGreg** [comment]
Python was not tested for long before release. This should interest @blueloveTH .

**Comment by jezv** [comment]
I also get this on version 1.1.2736 (59ab359)

**Comment by blueloveTH** [comment]
I will check this soon. Thanks for remind me @TimotheeGreg .

**Comment by blueloveTH** [comment]
I found the `print` function takes incorrect signature.

```python
print(text, x=0, y=0, color=15, fixed=False, scale=1, smallfont=False, alt=False)
```

the correct one is,

```python
print(text, x=0, y=0, color=15, fixed=False, scale=1, alt=False)
```

I will submit a pr to fix this. You can use python's keyword argument to guarantee to hit the right `alt` arg.
```python
# This should work

def TIC():
	cls(15)
	print("HELLO WORLD!",5,5,12,False,1,alt=True)
```

**Comment by TimotheeGreg** [comment]
That was fast! ^^ Thanks!

**Comment by deananorth** [comment]
You guys are on the ball. :)

Also TIL you can place argument names into function calls. I've got a lot to learn.

e.g.
```python
a_function_of_some_sort(argument2="foobar")
```
