### ISSUE TITLE
More gamepads for multiplayer

### ISSUE THREAD

**Issue by billohreally** [nesbox/TIC-80#234]
I'd love to make fun local multiplayer games for TIC80 with more than two players (four would be great but eight would be really nice).

Would this be possible?

**Comment by harraps** [comment]
If I recall the RAM layout, each gamepad has 8 buttons, so 16 bits in total.
It wouldn't be possible to have more gamepads or else it would screw up the actual RAM layout.
Also old video game console used to have only 2 controller ports, so I believe that is why this limitation was chosen.

To have more players, you could choose to make each player use only a part of the controller. (Think of Mario Party 7 on GameCube)
Or an interesting feature would be to have network functions to send and receive packets.

**Comment by frenetic** [comment]
Related: https://github.com/nesbox/TIC-80/issues/484

**Comment by nesbox** [comment]
yes, added 4 gamepads support here #484
closing
