### ISSUE TITLE
Screenshot and screen recording crashes TIC when launched with scale argument

### ISSUE THREAD

**Issue by peignenappe** [nesbox/TIC-80#2345]
TIC-80 crashes when F8 or F9 pressed. It seems to be related with the --scale argument as it works just fine when i start without options.
Are there log files somewhere to know what is happening ?

version 1.1.2837 Pro (be42d6f) on windows

**Comment by sogaiu** [comment]
As a data point, on a Linux machine with `tic80 --scale 1`, I didn't succeed in reproducing the issue using version 1.2.2801-dev (0937023).

Haven't tried on Windows.

**Comment by nesbox** [comment]
I reproduced it with `tic80 --scale 5` command

**Comment by nesbox** [comment]
fixed here https://github.com/nesbox/TIC-80/pull/2356
