### ISSUE TITLE
VS Code Python Issue

### ISSUE THREAD

**Issue by mickeyordog** [nesbox/TIC-80#2349]
I need some help getting the stubs from [here](https://github.com/nesbox/TIC-80/wiki/supported-languages#python-integration) to work in VS Code. Basically I used `new python` to create a new Python game and saved it as testing.py. Then I copied all these stubs into a separate file called testing.pyi in the same directory. But VS Code / Pylance still think that all of the TIC80 API calls are functions that don't exist. Any idea on why this might be happening?

**Comment by sogaiu** [comment]
By:

> But VS Code / Pylance still think that all of the TIC80 API calls are functions that don't exist.

what is it that you see that indicates this?

I ask because I tried what I understood to be what you described and don't see anything to suggest this.  That is, when I look at `testing.py`, I see no evidence of errors.

I don't see anything in the `PROBLEMS` or the `DEBUG CONSOLE` tabs either.

**Comment by mickeyordog** [comment]
Oh it works for you? For me every API call (eg btn) is underlined in red and the error says function is not defined. I’ll take a look at your repo but let me know if you have any idea why this is happening

**Comment by sogaiu** [comment]
> For me every API call (eg btn) is underlined in red and the error says function is not defined. 

I don't see that here.

Unfortunately, I don't have any good ideas why that might be, sorry.

**Comment by mickeyordog** [comment]
I was able to get it to work by renaming the file with the stubs to stubs.py and adding from stubs import * at the top of testing.py. This gets Pylance to accept that the functions are defined, but the only problem is now with that import statement, the game won't run in TIC80. I can solve this by commenting it out every time I want to run the game, but do you or anyone know of a better solution, maybe some way I could get that line only in vs code and not to run in tic80?

**Comment by sogaiu** [comment]
I don't think I have Pylance in my setup.

Perhaps its presence is related to seeing errors?  Or may be some other extension...

**Comment by blueloveTH** [comment]
@mickeyordog You can use `TYPE_CHECKING` to control the stub imports.

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from stubs import *
```
`TYPE_CHECKING` is `False` at runtime but `True` for pylance.

**Comment by mickeyordog** [comment]
That worked, thanks!
