### ISSUE TITLE
TIC-80 does not start on Windows XP

### ISSUE THREAD

**Issue by SIRprise** [nesbox/TIC-80#2357]
If I try to start the XP-version of TIC-80 on my german XP, I got:
"error: folder 'C:\Dokumente und Einstellungen\SIRprise\Anwendungsdaten\com.nesbox.tic\TIC-80\' doesn't exist"
The problem is: It actually does exist (it is empty)

The problem seems to be similar to #1495

**Comment by nesbox** [comment]
As a temporary solution, you can run it with `tic80 --fs .` command

**Comment by SIRprise** [comment]
Didn't work: "error: folder `.` doesn't exist.
It seems to be I can enter any value and it won't be found, even if I copy everything to C:\temp and use --fs C:\temp

**Comment by aliceisjustplaying** [comment]
Fixed in #2558
