### ISSUE TITLE
REVERT_SCROLL option should be for horizontal instead of vertical scrolling 

### ISSUE THREAD

**Issue by TimotheeGreg** [nesbox/TIC-80#2358]
Just tested pull request #2355 with the nightly build and it reverse the vertical y-scroll instead of the horizontal x-scroll as was mentioned in #2335

Indeed l.2144 of studio.c, that's `scrolly`:
![Capture d’écran du 2023-11-12 08-21-11](https://github.com/nesbox/TIC-80/assets/26139286/35a5a429-200e-4463-ba25-5d9521b58865)

**Comment by nesbox** [comment]
🤦
