### ISSUE TITLE
Python built-in map function

### ISSUE THREAD

**Issue by bonjorno7** [nesbox/TIC-80#2363]
You can use filter, but map is shadowed by the TIC-80 function of the same name.
Is there a way to call Python's map?
If not, would it be possible to add one?
Like calling it py_map or something.

**Comment by blueloveTH** [comment]
```python
from builtins import map as py_map
```

**Comment by bonjorno7** [comment]
Oh I had no idea there was a module for Python built-ins.
Is there one for TIC-80 functions too?

**Comment by bonjorno7** [comment]
My main question was answered so I'll close the issue.
