### ISSUE TITLE
Thin text cursor

### ISSUE THREAD

**Issue by bonjorno7** [nesbox/TIC-80#2364]
The 1-character thick text cursor is fine, but I still occasionally get confused by it, because I'm used to the modern thin line cursor.

**Comment by TimotheeGreg** [comment]
You can customize this in the configuration file, look at https://github.com/nesbox/TIC-80/wiki/System-Configuration-Cartridge#sprites-and-sfx

**Comment by bonjorno7** [comment]
Which sprite or option specifically?
I can't seem to find it.

**Comment by TimotheeGreg** [comment]
Oh, ok, I misunderstood!

**Comment by bonjorno7** [comment]
Found the implementation in drawCursor in code.c and it's easy enough to change.
Still need to figure out how to add an option though, since I figure not everyone will want this.

**Comment by TimotheeGreg** [comment]
Maybe that could inspire you for adding an option: https://github.com/nesbox/TIC-80/pull/2355 :shrug:

**Comment by bonjorno7** [comment]
That looks like exactly what I need, thanks!
