### ISSUE TITLE
Dark mode keyboard overlay

### ISSUE THREAD

**Issue by bonjorno7** [nesbox/TIC-80#2365]
The keyboard overlay on Android is quite bright, while the code editor itself is a pleasant dark theme.

**Comment by TimotheeGreg** [comment]
You can customize this too https://github.com/nesbox/TIC-80/wiki/System-Configuration-Cartridge#sprites-and-sfx the keyboard color is customizable but the keyboard *characters* color is not yet customizable but that is on the TODO list, it's the issue #2341

**Comment by bonjorno7** [comment]
When I opened the config, I thought I had to run it, and got confused there.
I see now that what I should do is *edit* the config cart.
It's not a one click solution but it is very powerful, so that's nice.

**Comment by TimotheeGreg** [comment]
By the way, if you want, feel free to publish and put your dark keyboard theme on the wiki. I don’t use Android but I am sure others have the same issue ^^
https://github.com/nesbox/TIC-80/wiki/Themes#example-themes
