### ISSUE TITLE
Space between # and text for comments added with Ctrl + /

### ISSUE THREAD

**Issue by bonjorno7** [nesbox/TIC-80#2368]
In Python, comments typically have a space between the # and the text.
I think it'd be nice to add that automatically when commenting code with the Ctrl + / shortcut.
And then automatically remove the excess space when using Ctrl + / to uncomment.

**Comment by blueloveTH** [comment]
I see there is no special setting for this in python.c. Can not be done :/

**Comment by aliceisjustplaying** [comment]
@blueloveTH can I close this with wontfix?

**Comment by bonjorno7** [comment]
It's alright by me.
