### ISSUE TITLE
Rainbow parentheses

### ISSUE THREAD

**Issue by bonjorno7** [nesbox/TIC-80#2369]
Different colored parenthesis (and other types of brackets) make it easier to identify pairs at a glance:
![image](https://github.com/nesbox/TIC-80/assets/43251584/89e5a3f9-51a4-49f7-a7d0-fa01963263c1)
This may be overkill for the little code editor but I think it's worth mentioning.

**Comment by TimotheeGreg** [comment]
Indeed, I personally think it is overkill, there already is a highlighting of matching delimiters, and we are restricted by number of colors in TIC-80. But that's always good to share ideas, thanks

**Comment by bonjorno7** [comment]
Yeah you're right, I'll close this one.
