### ISSUE TITLE
Raw data editor

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#242]
This suggestion would help with making better games with TIC.

How about adding Raw Data Editor (later on abbr. as RDE)? The RDE will have layout similar to an ordinary hex editor, with ability to add/remove bytes at the very end (+/- buttons). Why the last part? Read on to find out.

The rationale behind RDE is that to store data in a TIC-80 game you have to do one of the following:
- Encode it in sprite data
- Encode it in map data
- Use Lua tables

The first two means you can't use sprite/map data to store actual... sprites and map and the last one is wasteful compared to storing same information as raw bytes.

The RDE would share byte count with code, meaning characters (bytes) not used for code could be used by RDE and vice versa. The length of the RDE data would be entirely up to user with the maximum being 65535-space used by code. This also would mean that if total of code size+RDE space reaches 65535 you won't be able to input any new code or increase RDE space,.

As to why I think using lua tables isn't an option here is that, as I've said, they're wasting bytes compared to storing data as raw bytes. Consider example of this table declaration, which I've conveniently got rid of any characters that could bloat it, leaving only necessities (including the fact that table's name is only 1 letter long):

``` lua
t={23,67,45,89,172,220}
```

That declaration is 25 bytes long (remember, each letter is a separate byte). If we'd want to make it local, we'd waste additional 6 bytes (`local` and a space). If we cut away any lua syntactic sugar, including commas, we'd be left with 16 bytes (of course no separators means we have no idea where one number ends and another begins). Meanwhile, the entire thing, if entered in RDE, would amount to only 6 bytes:
`17 43 2D 59 AC DC`

Of course you always will be able to unroll data entered in RDE into a Lua table for convenience (and I would recommend it as well), but Lua tables created at runtime are not taking any code space, beyond initial declaration and the unroll code itself.

The RDE would have its own "address space" starting from 0000 and not depending on how much code is already there for user convenience.

To interact with raw data, two functions would be provided: `readrawbyte(numAddress)` and `readrawword(numAddress)`. The first function will return a byte found in that address or nil if address is outside raw data space set in RDE. The second will return 16bit word starting at that address. To read more data (dwords, qwords, null-terminated strings, etc.) the user will need to write his or her own function.

The raw data will be effectively ROM.

**Comment by DjPale** [comment]
Not sure I get the reasoning behind this feature in a FC. You are trying to circumvent the limitations which are there for providing focus. I think this messes with the core concepts and defeats the purpose. If you are at the point where limitations become a real problem and your game is great - why not port it to a game engine?

**Comment by darkhog** [comment]
The limitations would still be there. You either use the 64k space for custom data or game's code. They'd just make more sense, that's all.

**Comment by hseiken** [comment]
I'm not sure where I am on this one.  I think in one way, darkhog's request is legit.  In the other hand, I know in the old days, a programmer couldn't remap ram so easily, so they would have to create tricks to use memory for what it wasn't intended for, say, storing text as images.  I dunno, it goes both ways.  Which one; the one that  allows easier flexibility to create lo-fi games or the one that more enforces the hardware limitation side, replicating historical design dilemmas?  ?????  I dunno...

**Comment by nesbox** [comment]
This is beyond the functionality of the TIC, too complicated I think.
