### ISSUE TITLE
Can't add credentials in code editor.

### ISSUE THREAD

**Issue by Luke-Software1024** [nesbox/TIC-80#2429]
I type
```
-- name: game name
-- author: Luke
-- desc: game description
-- language: python
```
but TIC-80 doesn't read that.

**Comment by TimotheeGreg** [comment]
`--` allows to put comments in lua, if you use python it's `#`
```python
# name: game name
# author: Luke
# desc: game description
# language: python
```

Type `new python` in the console to have a working python Hello world game.

**Comment by Luke-Software1024** [comment]
> `--` allows to put comments in lua, if you use python it's `#`
> 
> ```python
> # name: game name
> # author: Luke
> # desc: game description
> # language: python
> ```
> 
> Type `new python` in the console to have a working python Hello world game.

I did that.

**Comment by TimotheeGreg** [comment]
Nice! You could close the issue now.
