### ISSUE TITLE
How to add a cart?

### ISSUE THREAD

**Issue by Playerwaar** [nesbox/TIC-80#2441]
Hello! "Please add at least TITLE, AUTHOR and COVER (by press F7) metadata to the cartridge and try again." how can I do it??

**Comment by nesbox** [comment]
Run your game, wait until you want to take a screenshot, press F7, close the game, and save the cart.
Also, could you check the TITLE and AUTHOR tags in the header of the code?

**Comment by TimotheeGreg** [comment]
Note that you have more details on the wiki. One page for the [metadata](https://github.com/nesbox/TIC-80/wiki/Cartridge-Metadata) and one for the [cover image](https://github.com/nesbox/TIC-80/wiki/Cover-image).

**Comment by TimotheeGreg** [comment]
This issue can be marked as solved https://tic80.com/dev?id=7124)
