### ISSUE TITLE
[enhancement] Source Control friendly cartridge 

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [nesbox/TIC-80#2454]
make an alternative cartridge format that stores its data externally and then gets loaded at runtime, and provide tooling to convert this format into the current `.tic` format

**Comment by nesbox** [comment]
I think we already have it, you can save a cart in text format, pls use `save cart.lua` command (pro feature)

**Comment by TheDrawingCoder-Gamer** [comment]
oh ur right, even excludes the WASM binary. nvm LOL
