### ISSUE TITLE
Virtual screen size calculation error?

### ISSUE THREAD

**Issue by manungsa** [nesbox/TIC-80#2481]
TIC80 documentation says that the virtual screen size will be the same 240x136 on all times. But, when running my code that will move the character inside the screen, the character goes out of bounds!
![tic80-bug](https://github.com/nesbox/TIC-80/assets/105505135/182367ca-0319-4bf4-b658-201ac201b8c4)
What i suspect is that the border's right and bottom side doesn't account for the screen dimension which makes the out of bounds.

**Comment by TimotheeGreg** [comment]
The screen is 240 pixels wide, so you can see pixels 0 to 239. If you print something at pixel 240 it's out of screen. Same for the y value.
Try to clamp from 0 to 239 and 0 to 135, that should work.
Note that if you want your character to be fully visible, you need to account for its width and height in the values you use in your clamp function.
