### ISSUE TITLE
When injecting a cart, the save function should automatically save to the loaded file

### ISSUE THREAD

**Issue by scambier** [nesbox/TIC-80#250]
When you launch TIC by injecting it a cart via the command line, the `save` function (or ctrl+s) should automatically save to that cart, without needing to type its name.

If the injected cart isn't in the TIC folder, maybe display a message saying that we have to type the name explicitly, to avoid any unwanted overwrite.

**Comment by Viza74** [comment]
I think it is not necessary to differentiate the files opened from the save folder or not (there is no safeguard in the save folder, why would other folders work differently?)
IMHO just save the tic file from wherever it was opened.

**Comment by nesbox** [comment]
hmm, TIC was designed to work with local FS only, so it doesn't know anything about external files
as a variant, I can give to the loaded cart same name you provided in cmd and it will be saved to local FS without confirmation dialog

**Comment by nesbox** [comment]
fixed with #175
