### ISSUE TITLE
Sprite editor mode selection hotkeys stop working when selecting

### ISSUE THREAD

**Issue by SolarLune** [nesbox/TIC-80#2514]
When pixels are selected using the Select tool (number key 3 on the keyboard) in the sprite editor, you can no longer use the number-keys to change tool.

**Comment by Miguel-hrvs** [comment]
While it's solved the workaroud is selecting with the mouse one of the tools, then the keyboard hotkeys will work again.

**Comment by Miguel-hrvs** [comment]
The fix is ready, I'll make a pr.
Here you have the file: 
[sprite-c.zip](https://github.com/user-attachments/files/16143114/sprite-c.zip)
