### ISSUE TITLE
Keyboard shortcut `alt-5` conflicts with `{` character on macOS with a French keyboard

### ISSUE THREAD

**Issue by Ecco** [nesbox/TIC-80#2520]
TIC-80 is currently unusable for Mac users in France. Indeed, to type a brace character `{` on a French Mac keyboard you're supposed to hit `Alt-(`.

However, when a user with a French Mac keyboard layout presses `Alt-(`, TIC-80 switches to the Music editor instead of yielding a `{` character.

Note: On those keyboards, the `(` key is shared with the `5` key. To get a `5` you're supposed to press `Shift-(`. I guess this somehow trips TIC-80 that confuses `Alt-(` with the `Alt-5` shortcut (that, on this keyboard, should therefore be `Alt-Shift-(`.

![French Mac Keyboard and parenthesis key](https://github.com/nesbox/TIC-80/assets/55989/a87de444-c957-4494-a588-9691cea21cbf)

I tested this on the current macOS release as well as on the latest HTML build of the main branch. The bug is present in both builds.

**Comment by aliceisjustplaying** [comment]
There is a way to detect they keyboard layout in SDL2: https://gist.github.com/g2p/8597984

**Comment by KTamas** [comment]
@Ecco PR with fix at https://github.com/nesbox/TIC-80/pull/2657.

**Comment by aliceisjustplaying** [comment]
@Ecco PR with fix at https://github.com/nesbox/TIC-80/pull/2657.
