### ISSUE TITLE
[Suggestion] Gamepad shortcut to exit surf

### ISSUE THREAD

**Issue by Skeptim** [nesbox/TIC-80#2530]
https://github.com/nesbox/TIC-80/pull/2387 added a gamepad shortcut to surf, that's really practical. But I think that exiting surf using a gamepad shortcut (X or B button) would make sense. That's what I expected while testing.
@LettucePie 

Edit: Writing this I realized the "Back/select" button worked as Escape and can be used to exit surf, however I did not find it when I first tried. Also I can't test on Android but I think there is no "Back/select" button on screen.

**Comment by LettucePie** [comment]
Hello again!

I agree with your suggestion. It makes sense to be able to easily navigate in and out of surf menu. My first instinct is to say the B button; the same button which functions as back or directory-up. If I remember, there already is a function that is listening and reacting to that button input. An if statement to see if our current point in the fs is equal to the "root" could then route to the exit.

One potential issue I could see is if users already expect and anticipate that hitting B at the root won't exit surf. For example: Someone may have an overly organized folder system, and they're used to spamming B to get back to the start. They would now need to be more delicate or else exit surf, then have to re-enter surf. A small nuisance for sure, but still something that could be polished out.

Maybe a Press and Hold system, along with a small "Exiting" message and possible a bar filling up... Or just using X lol. Sorry I may have over-complicated this.

**Comment by Skeptim** [comment]
Thanks for the fast reaction!
I agree with you, hitting B while on the root makes sense. I don't think we really need a press and hold system because if you exit surf by mistake, that's so easy to re-enter surf by pressing X. The press and hold system could be a larger nuisance than re-entering by pressing X.
