### ISSUE TITLE
Command line not fully visible when using past commands

### ISSUE THREAD

**Issue by Skeptim** [nesbox/TIC-80#2573]
If I use a command line that is longer than one line it will go to line so we can see it entirely but then if I press the Up arrow of the keyboard to use this same "too long" command line, we will see only the first line.
That's minor.

Here is an example, after using the command line once, I press Up arrow and I can't see the command line I am using entirely.

![video20](https://github.com/nesbox/TIC-80/assets/26139286/f70a13d2-620b-4e0a-8531-3b62df0f038b)

**Comment by Miguel-hrvs** [comment]
That's true, also happens in the master branch, is pretty annoying. I'll see if I can do something.

**Comment by Miguel-hrvs** [comment]
One fast fix would be to apply the cls command automatically while pressing the up arrow key to show history:

https://github.com/nesbox/TIC-80/assets/81558772/ea2d90e6-bb7d-44d0-a1b8-54a26a279b23
