### ISSUE TITLE
Scanline position for border and screen not aligned

### ISSUE THREAD

**Issue by tsulej** [nesbox/TIC-80#259]
When you use scanline to change palette for border and screen part, positions are not aligned. Border is stretched vertically.

![image](https://user-images.githubusercontent.com/1256957/29170941-f50e40a2-7dda-11e7-8c65-45779bccd2e2.png)

cartridge: https://tic.computer/play?cart=167
uncomment line 14

(saving cover fails too for this code)

**Comment by nesbox** [comment]
yes, this is how it works
screen and border have two independent textures with the same height 136px
screen always keeps 240:136 aspect ratio, when the border stretches depending on the window size

**Comment by nesbox** [comment]
I removed border texture, so, now TIC renders screen and border to one texture

![bars](https://user-images.githubusercontent.com/1101448/32435161-406b488c-c2f1-11e7-97b0-aebf96022937.gif)

fixed it here a4826af

closing
