### ISSUE TITLE
TIC-80 cannot create new files "error: not found any language"

### ISSUE THREAD

**Issue by VC-dell** [nesbox/TIC-80#2617]
My current version is 1.2.2953-dev Pro (18dacc0)
I am using Endeavour OS
I tried to build TIC-80 from main and stable branch via github but both of them cannot create new files or load files

Logs when creating new files:
```
TIC-80 tiny computer
 version 1.2.2953-dev Pro (18dacc0)
 https://tic80.com (C) 2017-2024

 hello! type help for help

>new lua
error: not found any language.
cart not created
>
```

Logs when loading a file via 'surf':
```
TIC-80 tiny computer
 version 1.2.2953-dev Pro (18dacc0)
 https://tic80.com (C) 2017-2024

 hello! type help for help

>surf
cart wip_morio_like_game.tic loaded!
use RUN command to run it

tic80.com>fish: Job 1, 'tic80' terminated by signal SIGSEGV (Address boundary error)
```

What are possible causes of these errors and how do I fix it?
Is there any more information needed to give more clarity to this issue?

**Comment by Skeptim** [comment]
Related to https://github.com/nesbox/TIC-80/issues/2613#issuecomment-2162668027

**Comment by runemoennike** [comment]
@VC-dell you can work around this by either launching `build/bin/tic80` directly, or building with `-DBUILD_STATIC=ON`

**Comment by VC-dell** [comment]
Thanks guys. It works now

**Comment by Miguel-hrvs** [comment]
Would be great to specify the -DBUILD_STATIC_DEFAULT=ON flag in the readme's linux install instructions to help users find the solution fast.
