### ISSUE TITLE
Improve filename completion behavior

### ISSUE THREAD

**Issue by DjPale** [nesbox/TIC-80#262]
Tested on Windows 10 - 0.30.dev

When attempting to use the `load` and using completion, the completion stops at the first filename that might be a non-tic file. Trying to press `Tab` again does not cycle further files. The use case here is that we have external scripts with similar names as tic-carts and they are suggested.

![image](https://user-images.githubusercontent.com/1427902/29242517-338d05c4-7f8f-11e7-8af9-5358c3711b79.png)

Suggested alternatives for fixes:
* Use filter to only select allowed file types
* Allow cycling through all relevant filenames

(Minor issue)

**Comment by farvardin** [comment]
we can also add, in the case you have those files:

file1.tic
file2.tic
file3.tic

if you type f + tab, then it will automatically complete to file1.tic. It should instead complete to file and display possible relevant files (it would even be better to cycle through files)

If you have those 3 files into a "test" folder, it won't complete if you type test/fi + tab

if you have :
test (a folder)
test1.tic (a file)

it won't complete to "cd test" if you type "cd tes" + tab, it will complete to "cd test1.tic" instead

**Comment by TimotheeGreg** [comment]
I can't reproduce this on Linux, I think that has been solved already.
