### ISSUE TITLE
If`alt+1` produces a key that's valid in TIC-80, it gets inserted in the code editor instead of executing the shortcut

### ISSUE THREAD

**Issue by aliceisjustplaying** [nesbox/TIC-80#2661]
Per the title, for some reason the alt+1 shortcut will insert `1` but only under Linux. 

Found while working on https://github.com/nesbox/TIC-80/pull/2657.

**Comment by aliceisjustplaying** [comment]
The Linux thing was a red herring: this happens with every keyboard layout where `alt+1` produces a valid key. 

On macOS with the default US keyboard, `alt+1` produces `¡`, which is not valid in TIC-80. On Windows 11 with the default US keyboard, alt+1 does nothing. Likely the reason this was not caught before.

**Comment by aliceisjustplaying** [comment]
This is a problem specifically when switching away the editor and switching back.-.

**Comment by Miguel-hrvs** [comment]
Is very similar to the f1 bookmark problem that was fixed recently.
