### ISSUE TITLE
Keep getting this error when compiling on Linux Mint 22 and Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by RadioactiveBen** [nesbox/TIC-80#2667]
this is the error
`gmake[2]: *** [vendor/sdl2/CMakeFiles/SDL2-static.dir/build.make:432: vendor/sdl2/CMakeFiles/SDL2-static.dir/src/dynapi/SDL_dynapi.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1077: vendor/sdl2/CMakeFiles/SDL2-static.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2`

this is the input command 
`sudo cmake -DBUILD_SDLGPU=On -DBUILD_WITH_ALL=On -DBUILD_PRO=On .. && sudo cmake --build . --parallel`

**Comment by Miguel-hrvs** [comment]
Try clearing cache and with: cmake -DBUILD_SDLGPU=On -DBUILD_WITH_ALL=On -DBUILD_PRO=On -DBUILD_STATIC=ON -DCMAKE_BUILD_TYPE=MinSizeRel .. && cmake --build . --config MinSizeRel --parallel 2
If it doesn't work, ask in linux mint forums, seems distro related.

**Comment by aliceisjustplaying** [comment]
@RadioactiveBen can you post the full output? The line you copied doesn't seem to contain the actual error.

**Comment by Miguel-hrvs** [comment]
sudo apt install rake
And try again

**Comment by RadioactiveBen** [comment]
it worked ur awesome thx so much

**Comment by Miguel-hrvs** [comment]
You're welcome, once compiled use sudo make install to access it through the search bar or console.
