### ISSUE TITLE
sound cutoff bug

### ISSUE THREAD

**Issue by jackj106** [nesbox/TIC-80#287]
while leaving tic80 open with a closed laptop or (maybye) a slept comouter, opening/waking it will cause tic80s sound to be 5-7 seconds behind what it should be.
i accidentally put this up on the itch.io community.
i think ths must happen due to a hierachy issue as far as what gets proccessor while in sleep mode.

**Comment by nesbox** [comment]
yes, reproduced it, will fix

**Comment by AnastasiaDunbar** [comment]
I have talked about this too.
![image](https://user-images.githubusercontent.com/11806048/31417630-69f91b40-ae63-11e7-9495-14cf1d0ab12b.png)

**Comment by AnastasiaDunbar** [comment]
I think sound delays by time because it happened when I left the computer on.

**Comment by jordanranson** [comment]
Hey, so its 2018 and this bug still exists. It happens on my 2017 MacBook Pro, using High Sierra. It happens whenever I put the app into full-screen (or take out of full-screen) or when I close and reopen my laptop lid.

**Comment by StinkerB06** [comment]
Yes, very annoying and would really love it fixed.

**Comment by another-m00** [comment]
This has been fixed since, can we close it now?
