### ISSUE TITLE
SURF shows covers in wrong color (doesn't use game's palette)

### ISSUE THREAD

**Issue by nalquas** [nesbox/TIC-80#305]
While I don't know how to get around this issue without breaking the 16 color limitation, it seems somewhat annoying that cover images aren't displayed in their correct colors if they were made with a custom palette.

Let me show you what I mean:
This is how my cover normally looks:
![cover](https://user-images.githubusercontent.com/22664233/30655473-44254912-9e31-11e7-8d5a-3b5cc700be1d.gif)

And this is how it looks when shown in SURF:
![screen](https://user-images.githubusercontent.com/22664233/30655401-1c014378-9e31-11e7-9e92-725ed5a252cf.gif)

While it isn't that big of an issue in this particular example, it would be a very huge problem if the game were to use a significantly changed palette.

As a side note, SURF always seems to use the palette of the last game that was loaded in TIC-80. (So if you start a game through SURF, then close the game and open SURF again you'll see SURF using the palette of that game.)

**Comment by Effer** [comment]
I noticed this too. I think it could be possible to load the cart's palette when scrolling the entries.

There's a major problem anyway, the same as in editors when using custom palette. Consider the case you're using a palette composed of 16 shades of gray in your game, all the GUI colors will be poorly readable. The same for the SURF interface.

It would be nice to have a way to switch the palette and draw the background, then the next frame change another palette and draw the GUI. You'll pay on framerate 30 vs 60. This is not possible right now, changing palette affects also colors already draw the previously.  
Don't know if this limit is something wanted or that simulate an hardware thing.

**Comment by darkhog** [comment]
Perhaps it could be possible to draw Surf's UI using standard TIC palette but in OVR thing?

**Comment by nesbox** [comment]
yes, it's possible with OVR

**Comment by nesbox** [comment]
Fixed at the moment.
Closing.
