### ISSUE TITLE
Browser hang if i run html-build, in native build OK. JavaScript.

### ISSUE THREAD

**Issue by AlRado** [nesbox/TIC-80#306]
[demo_test.zip](https://github.com/nesbox/tic.computer/files/1320474/demo_test.zip)

**Comment by nesbox** [comment]
so, seems problem was in the Emscripten (LLVM compiler C->JS)
I just updated it and it works fine now
[demo_test.zip](https://github.com/nesbox/TIC-80/files/1340993/demo_test.zip)
closing...
