### ISSUE TITLE
Ctrl+s in-game resets cart, with palette bug. 

### ISSUE THREAD

**Issue by trelemar** [nesbox/TIC-80#309]
Similar to the other issue I opened last night with the palette. TIC will load the default palette and reset the game as well if Ctrl+s is pressed mid-game. Linux 64 bit 0.45.0 other versions untested. Didn't happen in 0.40.0.

**Comment by nesbox** [comment]
yes, same as #308

**Comment by trelemar** [comment]
The issue here is that Ctrl+s resets the cart as if you press Ctrl+r right after.

**Comment by nesbox** [comment]
anyway, it was fixed with #308
