### ISSUE TITLE
spr rotate 360 degrees

### ISSUE THREAD

**Issue by digitsensitive** [nesbox/TIC-80#310]
Hello there! It would be great if sprites could be rotated not only every 90 degrees but stepwise by 1 degree. Any change to see that coming? Thank you.

**Comment by nesbox** [comment]
on one hand, it's convenient for game dev, on the other hand, retro consoles couldn't rotate sprites
I don't like, but it's debatable

**Comment by coolq1000** [comment]
I agree that it is not retro, but we should decide where to draw the line in terms of how _retro_ it should be. In my opinion, it would be more beneficial to have the ability to rotate more accurately.

Also, digitsensitive, if you need this right away, I'm willing to try making a sprite rotation function of you'd want 😉

**Comment by nesbox** [comment]
in .46 you can use `textri` api to rotate sprites
like this
![demo](https://user-images.githubusercontent.com/1101448/31165848-44de7a8a-a8f5-11e7-9832-da9b7ce4d8f1.gif)

**Comment by coolq1000** [comment]
@nesbox that's really awesome! I'm still going to make my own rotate method, but cool to have textured triangles!

Was it hard to implement? Or is it a SDL feature?

**Comment by nesbox** [comment]
@coolq1000 it's implemented by @Nullious https://github.com/nesbox/TIC-80/pull/317

**Comment by coolq1000** [comment]
@nesbox Ah, cool!

**Comment by nesbox** [comment]
closing then
