### ISSUE TITLE
Set/Get spritesheet pixel

### ISSUE THREAD

**Issue by digitsensitive** [nesbox/TIC-80#313]
Is it just me or is the set spritesheet pixel function not working anymore? Worked fine to get pixel.

Tried this example:
https://github.com/nesbox/tic.computer/wiki/code-examples-and-snippets#setget-spritesheet-pixel

Thank you!

**Comment by nesbox** [comment]
possibly, you have to call `sync` api to copy RAM to cartridge

**Comment by nesbox** [comment]
^
