### ISSUE TITLE
Is it normal to require to be online on android? 

### ISSUE THREAD

**Issue by owengraven** [nesbox/TIC-80#314]
Hi,

When running tic-80 without internet it just stays black without action, is this normal behaviour? Also if hes, why does it need to be online?

Running on a lg g6, android 7.0

I'm new to the beta, but i love it, i spend hours already making my own little programs, reminds me of my ti-84 calculator and can't wait to learn enough to code a simple game.

**Comment by nesbox** [comment]
it's not normal, 
do you see the black screen without any text?

**Comment by owengraven** [comment]
I get the tic-80 thing but the help text and command prompt doesn't appear, once back on a connection (wifi or data) everything works fine again.

see screenshot:
https://i.imgur.com/e7CopSz.png

**Comment by darkhog** [comment]
Looks to me that it hangs during checking for update phase. Which on 'droid is unnecessary since gplay will update automatucally. So it could be cut via conditional compilation for that version.

**Comment by nesbox** [comment]
ok, I disabled version checking in .46

**Comment by owengraven** [comment]
It is indeed fixed, well done
