### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by Risike** [nesbox/TIC-80#318]
Hi !
I'm trying to build Tic-80 with Visual Studio 2015 Community.
I've a lot of errors and Warnings...
Must I configure something before building ?

**Comment by jackwilsdon** [comment]
What errors are you getting?

**Comment by Rolzad73** [comment]
@Risike could you paste in the errors to the issue?

I also had a small issue compling Win version, but I expected my environment my have differences, so it took some time, but I got mine compiling.

Win 10
Visual Studio 2017

In Visual Studio, I did have to set on 'tic' project the Win SDK settings to 7.0 (as opposed to the default it was set to) and the Platform Toolset to Win XP v141_xp.

![tic-80_vs2107_settings](https://user-images.githubusercontent.com/3611989/31127136-fdde97ca-a81b-11e7-9816-0eebe729146d.png)

I also may have had to set in Linker settings (also on 'tic' project) the Additional Library directories to ",,\,,\,,\lib\windows"

![tic-80_vs2107_settings_linker](https://user-images.githubusercontent.com/3611989/31127142-02b70462-a81c-11e7-9ac0-c1f6c5733fdb.png)

I can't remember anything else I did. But if you send the error messages you are seeing, maybe we can move you forward.

**Comment by nesbox** [comment]
@Risike pls provide the error log
until closing...
