### ISSUE TITLE
Load the cartridge and run

### ISSUE THREAD

**Issue by geomodular** [nesbox/TIC-80#322]
Hi,
according to wiki there is an option using the command line argument to load the cartridge and run game:

> tic game.tic ==> load the cartridge and run game

I believe this doesn't work and I am keep getting the hello world template every time am trying load own project. I am experiencing this on 0.45 and 0.46 linux 64 build. Not tested on other builds.

**Comment by nesbox** [comment]
seems TIC doesn't see your cartridge
could you pls provide the command you run?

**Comment by geomodular** [comment]
I got it working! I had to copy tic file next to binary and run:

> ./tic o4c.tic

I believe absolute path works too. Sorry, I relied on the fact that tic was aware of my cartridge using ls command.

**Comment by nesbox** [comment]
great, closing
