### ISSUE TITLE
Any invalid command crashes tic-80 android

### ISSUE THREAD

**Issue by owengraven** [nesbox/TIC-80#325]
Don't know if it's expected behaviour.

If you type any invalid command in the command line, it will crash the app.

I noticed when typing rub instead of run, but also tebt, adgkr, and others consistently crash the app 

Android, Lg G6, nougat 7.1

**Comment by Rolzad73** [comment]
This has also been reported in https://github.com/nesbox/TIC-80/issues/324

If you can supply a logcat at the time of the crash it would help in diagnosing.

**Comment by nesbox** [comment]
same here #324
