### ISSUE TITLE
textri() causes error when using javascript

### ISSUE THREAD

**Issue by UninspiredUsername** [nesbox/TIC-80#328]
This code results in an error "RangeError: invalid stack index 12":
```javascript
function TIC() {
 cls();
 textri(0, 0, 
	32, 0, 
	0, 32, 
	8, 0, 
	24, 0, 
	8, 16,
	false, -1);
}
```

Its equivalent in LUA works perfectly fine:
```lua
function TIC()
 cls()
 textri(0, 0, 
	32, 0, 
	0, 32, 
	8, 0, 
	24, 0, 
	8, 16,
	false, -1)
end
```
![screen](https://user-images.githubusercontent.com/26863236/31312213-41659f62-ab8b-11e7-9a90-e44d30c3e464.gif)

**Comment by nesbox** [comment]
fixed in .47
