### ISSUE TITLE
btn() always returns number

### ISSUE THREAD

**Issue by UninspiredUsername** [nesbox/TIC-80#339]
`btn()` returns a bitfield of all the buttons pressed, so up = 1, down = 2, left = 4, left+up = 5, up+left+down = 7, etc. Which is all well and good, except `btn(n)` returns the same bitfield but limited to that one button. (So `btn(4)` returns 16 when "A" is held and 0 otherwise.)

Is that the intended behavior? Because the wiki says `btn(n)` should return "true" when held, not a number. If this is the intended behavior, then the wiki could use some updating.

I primarily use javascript if it matters. (I just realized that lua might treat >= 1 as true, which would make the wiki _technically_ correct in a way.)

If this is how it's intended to work, do you mind if I edit the wiki? I've noticed some other minor inaccuracies and missing information too. I've been toying around with TIC-80 allot lately, so I'd be happy to clean the wiki up a bit while I'm at it.

**Comment by nesbox** [comment]
It's a bug and it should return boolean in JS
I made a fix
thanks
