### ISSUE TITLE
Memory Bank Suggestion

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#341]
One thing historically that was very common for later gameboy and gameboy color games was the concept of memory bank switching.

I would like to propose that you could include memory bank switching for the map/sprites (assuming they don't share space) and sfx/patterns/tracks.

This is a feature that FC's like pico8 have faked with "multicarting". Not a fan, personally. I was also able to work around it by using RLE compression on strings that could overwrite the current sprite table. I imagine it would be easy to integrate into the editor, and extending the API should enforce backwards compatibility.

perhaps `mbank(int)` could switch the memory banks. There could be a soft/hard limit imposed, considering different games uses different amount of memory banks. One could easily argue that there are only so many chips you could fit into a physical cart, so it would be fair to hard cap it.

Anyway, if this is something that interests you, huzzah. If it is, but you don't have time, please say so; I'd be happy to see if I can make a PR.

**Comment by UninspiredUsername** [comment]
The entire cart is loaded into ram when loading the game, and TIC uses the sprites/map/sound from RAM and not the cart. So an alternative to this idea might be to have some extra room for data in the cart, along with a way to edit it and a function to copy it over into RAM on the fly.

**Comment by nesbox** [comment]
yes, it can be done
I see it as a new tab in the editor's toolbar where you can create/switch current bank
You could add new _chunk type_ for the RLE bank data here https://github.com/nesbox/TIC-80/blob/cd101d429af1d85044dc1e352a37d954415a5764/src/tic.c#L61 and implement save/load
so, I like the idea
thanks

**Comment by nesbox** [comment]
@josefnpat pls do it, if it'll make you happy  :)

**Comment by josefnpat** [comment]
@nesbox I'll give it a try when I have some time. Feel free to steal it from me if it interests you as well <3

**Comment by fangzhangmnm** [comment]
How about it now?

**Comment by nesbox** [comment]
@fangzhangmnm going to add it

**Comment by nesbox** [comment]
trying to imagine how _Bank Switching_ will look
![bank](https://user-images.githubusercontent.com/1101448/33942949-a044903e-e028-11e7-9b5a-698bf8fa86a9.gif)

**Comment by frenetic** [comment]
Question: Each memory bank will have their sprites, tunes, music? So, if I decide to use `mbank(2)` I will only be able to access the sprites and audio from that bank? Or will there be a way to use sprites from `mbank(2)` but audio from, lets say, `mbank(0)`?

**Comment by nesbox** [comment]
@frenetic second variant
for example, `mbank("sfx",5)` will load SFX data from 5th bank from cartridge to the RAM
and you can call `mbank` only one time per frame I think

**Comment by frenetic** [comment]
Cool.
Id like to suggest that calling `mbank` should be "expensive". Like, using a `sleep(1 second)`, or something like that...

**Comment by nesbox** [comment]
or you can get an error message if you call `mbank` more than 1 sec...

**Comment by jahodfra** [comment]
while just one sec prevention? I had to wait e.g. 15 minutes to load a game from tape drive on c64.
I think waiting 5 seconds to change the cartridge would be more appropriate. (it can even add creativity with transitions and loading screens). E.g. something like computing score at the end of level in Prehistoric II.

**Comment by adiron** [comment]
How about write the contents of the cassette being loaded to the audio, briefly, as though loaded from a datasette? ;)

**Comment by nesbox** [comment]
_Bank Switching_ is implemented
use `sync(section = nil, bank = 0, tocart = false)` api to switch bank in _Runtime_
**Parameters:**
- **section** can be `"tiles"` or `"sprites"` or `"map"` or `"sfx"` or `"music"` or `"pal"` or `nil` (by default to switch all the sections to the _bank)_
- **bank** can be `0-7`
- **tocart** is direction to move data, `true` - to copy data from RAM to cart, `false` - to copy data from cart to RAM

found bugs will be opened in separate issues
also, still thinking about bank switching limitation

thanks all for help 👍

**Comment by ambyra** [comment]
I don’t like the bank switching limitation, not really useful for any sort of creativity. 

If you do want some sort of limitation though, an arbitrary time limit is a weird way to do it. 

Instead, make it be interrupt based, where the computer pauses until the interrupt returns (like next frame), or just ignore more than one call per frame. 

Switching a bank could end the current TIC() loop, so people will only put sync at the end of a loop.

**Comment by frenetic** [comment]
@ambyra It seems you can only run `mbank` once per frame (`TIC` iteration).

**Comment by nesbox** [comment]
yes, you can switch it one time per `TIC()`
also, I'm thinking, what to use as section parameter, string as now  or maybe integer with bit values
```
tiles = 	1
sprites = 	2
map = 		4
sfx = 		8
music = 	16
```
so you can combine them like `sync(1 | 4, ...)` for tiles and map for example, instead string representation...

**Comment by fangzhangmnm** [comment]
Another very important problem is that the developer should be able to choose the number of banks he used, or loading a game on webpage will be rather slow if it had to load all the unused banks.

**Comment by nesbox** [comment]
.tic cartridge doesn't save unused (empty) banks, so, it's not a problem @fangzhangmnm

**Comment by nesbox** [comment]
d2fe2ad changes
`sync(mask = 0, bank = 0, tocart = false)`
where `mask` can be
``` lua
tiles=   1<<0 -- 1
sprites= 1<<1 -- 2
map=     1<<2 -- 4
sfx=     1<<3 -- 8
music=   1<<4 -- 16
palette= 1<<5 -- 32
```
or combination of them, if `mask == 0` all the bank types will be switched

**Comment by trelemar** [comment]
I haven't been following this too closely, I pulled the latest, not seeing the bank switching UI on the top bar? Is only the bank logic done so far?
Perhaps instead of a UI element a simple console command "bank 2" for example might work fine enough. Then just show the current bank index in the top bar?

**Comment by nesbox** [comment]
added a pin button to synchronize banks between editors 6a19f59
![pin](https://user-images.githubusercontent.com/1101448/34250447-ebe1b32a-e64d-11e7-8e66-436e84ae433f.gif)
