### ISSUE TITLE
Use scanline trick to draw Sprite and Map editors with cart palette

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#345]
and draw all other modes with system palette

**Comment by egordorichev** [comment]
Oh, that would be really neat, thank you, @nesbox !

**Comment by nesbox** [comment]
done, all the modes use system palette except sprite and map
also removed unnecessary _palmap_ data from the config

**Comment by egordorichev** [comment]
Nice :) Well you will release 0.47?

**Comment by nesbox** [comment]
will do tonight

**Comment by egordorichev** [comment]
Great :) Was hoping to get it done before the FC jam.
