### ISSUE TITLE
Add Retina support for macOS build

### ISSUE THREAD

**Issue by yanykin** [nesbox/TIC-80#348]
If you run application on macOS device with Retina screen, window title looks little bit ugly because of low resolution. You can add Retina support by adding these lines to `Info.plist` without any rebuild
```
<key>NSHighResolutionCapable</key>
<true/>
```
In some cases, you will need to reset cache of the app using command
```
sudo touch /Applications/tic.app/
```

**Comment by nesbox** [comment]
thanks, will do

**Comment by nesbox** [comment]
@yanykin pls test, if not diffucult :)
[tic_0.48.0.dmg.zip](https://github.com/nesbox/TIC-80/files/1404795/tic_0.48.0.dmg.zip)

**Comment by yanykin** [comment]
@nesbox it works, that's okay :)
