### ISSUE TITLE
Arguments do not read correctly in cygwin

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#354]
I have the latest version of cygwin installed. Using cygwin I cannot run the `-code` argument, and with windows' cmd.exe, I can.

![image](https://user-images.githubusercontent.com/646162/32062369-e8fc8cba-ba39-11e7-8bdf-3b7bcb0a6971.png)

**Comment by matheuslessarodrigues** [comment]
Wait. Cygwin does not let you use `-` in your command args?

**Comment by josefnpat** [comment]
@matheuslessarodrigues It does:

![image](https://user-images.githubusercontent.com/646162/32179138-96a60934-bd5c-11e7-833b-6434755f12a1.png)

**Comment by josefnpat** [comment]
@Nullious made me realize that cygwin uses the `tic` package just like debian does. Running `./tic.exe foo.tic` works as intended.
