### ISSUE TITLE
Using ALT-F4 when running an unsaved cart will emit a tone

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#355]
Repro:

1) Start TIC-80
2) Make an edit that would have this warning screen appear:
![image](https://user-images.githubusercontent.com/646162/32072738-4e31b956-ba59-11e7-97c4-cd020f1b809e.png)
3) `run` the game
4) Attempt to close the game with `ALT-F4`
5) Select `NO`

What happens: A loud tone is emitted continuously
What I expect: A loud annoying tone is not emitted continuously

**Comment by nesbox** [comment]
fixed
