### ISSUE TITLE
SURF mode doesn't always load data

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#358]
![tic80_wtf2](https://user-images.githubusercontent.com/646162/32111427-1f8031c6-bb00-11e7-8b37-c400f1a3f2e6.gif)

I notice it takes a few attempts to load specific indexes from the SURF feature. I don't think this is intended.

**Comment by StinkerB06** [comment]
Can you show all carts from the Music Category using screen recorder?

**Comment by matheuslessarodrigues** [comment]
Maybe it's because it's still fetching games list but yet lets you click "[games]" menu?

**Comment by josefnpat** [comment]
@matheuslessarodrigues I believe that as well, but it should show loading and block for me, not just silently fail, or?

**Comment by nesbox** [comment]
we use curl lib now and it loads web data corectly
