### ISSUE TITLE
how to build for emscripten

### ISSUE THREAD

**Issue by noxarivis** [nesbox/TIC-80#359]
Please add to the readme the instructions to build the HTML5 version of TIC-80

**Comment by matheuslessarodrigues** [comment]
There's this tutorial that shows how to compile with mingw32. In the process, an HTML5 version is built from source.
Link: http://lessa.codes/tic80-build-tutorial/

**Comment by noxarivis** [comment]
isnt mingw32 for Windows?

**Comment by matheuslessarodrigues** [comment]
Yes it is. But the makefile distributed makes you need to first compile to html and then proceed to compile to windows. So I wrote this tutorial with step-by-step on how to compile it :)

**Comment by noxarivis** [comment]
well, how to do that on Fedora 27 ?

**Comment by matheuslessarodrigues** [comment]
I imagine the steps are similar:

- clone TIC
- install EMScripten Compiler. Tutorial [link](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html)
- run these commands
```
cd TIC-80
cd tools/bin2txt
make
cd ../..
make emscripten
```

Please see if this helps!

**Comment by noxarivis** [comment]
Nope, results in an error  

'''
[lura@torak-v5 bin2txt]$ make
gcc -O3 -Wall -std=c99 bin2txt.c -I../../include/zlib -L../../lib/mingw -lz -o bin2txt.exe
/usr/bin/ld: inkompatibles ../../lib/mingw/libz.a wird bei der Suche nach -lz übersprungen
[lura@torak-v5 bin2txt]$ cd ../..
[lura@torak-v5 TIC-80]$ make emscripten
emcc src/studio.c src/console.c src/run.c src/ext/file_dialog.c src/ext/md5.c src/ext/gif.c src/ext/net/SDLnet.c src/ext/net/SDLnetTCP.c src/ext/net/SDLnetselect.c src/fs.c src/tools.c src/start.c src/sprite.c src/map.c src/sfx.c src/music.c src/history.c src/world.c src/config.c src/keymap.c src/code.c src/dialog.c src/menu.c src/net.c src/surf.c src/tic80.c src/tic.c src/ext/blip_buf.c src/jsapi.c src/luaapi.c src/ext/duktape/duktape.c src/html.c -O3 -Wall -std=c99 -Iinclude/lua -Iinclude/zlib -Iinclude/gif -Iinclude/sdl2 -Iinclude/tic80 -D_GNU_SOURCE -Wno-typedef-redefinition -s USE_SDL=2 -s TOTAL_MEMORY=67108864 --llvm-lto 1 --memory-init-file 0 --pre-js lib/emscripten/prejs.js -Llib/emscripten -llua -lgif -lz -o build/html/tic.js
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/home/lura/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_13.zip
WARNING:root:unpacking port: sdl2
INFO:root:generating port: sdl2.bc... (this will be cached in "/home/lura/.emscripten_cache/asmjs/sdl2.bc" for subsequent builds)
INFO:root: - ok
src/fs.c:700:6: error: conflicting types for 'fsOpenSystemPath'
void fsOpenSystemPath(FileSystem* fs, const char* path) {}
     ^
src/fs.h:70:5: note: previous declaration is here
int fsOpenSystemPath(FileSystem* fs, const char* path);
    ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make: *** [makefile:267: emscripten] Fehler 1

'''

**Comment by jackwilsdon** [comment]
That seems to be a mistake in the code as opposed to something you've done during compilation - the method has a different signature in it's implementation than it's header definition.

**Comment by nesbox** [comment]
I made a fix here df67bb1

**Comment by noxarivis** [comment]
nice, i really love working with TIC-80

**Comment by noxarivis** [comment]
yup that fixed that

**Comment by noxarivis** [comment]
@nesbox 
I recommend adding a small howto for linux in the readme for the emscripten build.

here is a vague description how i did it on Fedora WS 26:

installed emscripten
cloned the tic_0.48.0 branch
cd into TIC-80
make emscripten

**Comment by josefnpat** [comment]
@nesbox @noxarivis 

We should consider moving the build instructions to the wiki so that folks who figure out how to compile stuff on different os's (linux and macOS mostly) can provide details themselves!

**Comment by nesbox** [comment]
ok, I added section https://github.com/nesbox/TIC-80/wiki/build-instructions
