### ISSUE TITLE
rename tic executable

### ISSUE THREAD

**Issue by to90zeroblue** [nesbox/TIC-80#363]
tic conflicts with another command in OSX. Would it cause problems to rename the file? 

Suggestions:

tic80
tic-80
t80
ticomputer

**Comment by nesbox** [comment]
ok, I'll rename to _tic80_

**Comment by josefnpat** [comment]
While the arch linux repo does not have a `tic` package, the arch users have opted in to naming the binary `tic-80`:

https://aur.archlinux.org/packages/tic-80/
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tic-80

Whatever we choose to name it to, we should consider leaving a comment on the arch AUR mentioning the preferred binary name.

**Comment by josefnpat** [comment]
I have found a collision: https://manpages.debian.org/testing/ncurses-bin/tic.1.en.html

Which is a part of the rather common `ncurses-bin` package.

I highly suggest moving to `tic80` or `tic-80` for 0.48.0

If we can get that in, I can start adding some extra makefile options: http://nuclear.mutantstargoat.com/articles/make/#going-the-extra-mile-for-release

**Comment by nesbox** [comment]
cfc8fa2

**Comment by nesbox** [comment]
done

**Comment by to90zeroblue** [comment]
Yay! I’m so excited for this release btw:)
