### ISSUE TITLE
Screen shot all music carts from surf?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#365]

**Comment by josefnpat** [comment]
Hello @StinkerB06.

Thank you for the feature request. Unfortunately this request is rather vague. Please read the following SO answer, and provide more a detailed feature request;

https://meta.stackexchange.com/a/259196

**Comment by StinkerB06** [comment]
But it it not a feature request you silly!

**Comment by josefnpat** [comment]
@StinkerB06 Sorry, then I really have no idea what this ticket means.

Please read the following article, and provide a more detailed bug report:

https://wiredcraft.com/blog/how-we-write-our-github-issues/
