### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#370]
![image](https://user-images.githubusercontent.com/646162/32251590-a4f7e422-be5f-11e7-87a4-0d12b53c2431.png)

The first open brace is technically commented, and should look like this:

![image](https://user-images.githubusercontent.com/646162/32251629-db19ab30-be5f-11e7-81ba-2f1f701bf4ba.png)

e.g:
```lua
 --[[
 x,y,down = mouse()
 if down then
   pix(x,y,COLOR_ON)
 end
 --]]
```
```lua
 ---[[
 x,y,down = mouse()
 if down then
   pix(x,y,COLOR_ON)
 end
 --]]
```

**Comment by nesbox** [comment]
already fixed

**Comment by josefnpat** [comment]
hahah anice
