### ISSUE TITLE
Make it clear how to get to the editors

### ISSUE THREAD

**Issue by iguessthislldo** [nesbox/TIC-80#375]
It took me much longer than I would have liked to figure out how to get to the editors. I had to see #169 to see that it was the escape key. As a shell user I was trying to find a command(s) to get to it, but ESC is fine if it was clear. Maybe say it in the help command and/or in the start message?

**Comment by iguessthislldo** [comment]
I see now that it does say "press ESC to enter UI mode" in `help` but that still isn't very clear.

**Comment by josefnpat** [comment]
What if we added an `edit` or `editor` command to the console?

**Comment by noxarivis** [comment]
@iguessthislldo @josefnpat 
first ^^ 

#361

**Comment by nesbox** [comment]
let's add `edit` command

**Comment by josefnpat** [comment]
@noxarivis lol, oh well. As long as one is open, I'm happy.

**Comment by josefnpat** [comment]
Please assign this to me!

**Comment by josefnpat** [comment]
@nesbox please review if you have time <3

**Comment by josefnpat** [comment]
oh no i merged this into the bloody master, one sec

**Comment by nesbox** [comment]
@josefnpat so, I made some changes to branches:
old `master` renamed to `stable`
new `master` is a default working branch (current version)
force-pushes are disabled and all the branches require _pull request_ review before a merge
hope, this will get rid of confusion

**Comment by josefnpat** [comment]
@nesbox That will work perfectly.

**Comment by iguessthislldo** [comment]
@nesbox @josefnpat Thanks!
