### ISSUE TITLE
Use scancodes for button inputs.

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#377]
From: https://www.reddit.com/r/programming/comments/7a5wlh/tic80_tiny_computer_a_fantasy_computer_for_making/dp7tlyw/

> The only thing I really dislike is that it uses Z and X by default and not X and C. You make it uncomfortable to play for half of Europe

I think this is a really good point. I know [love uses scancodes](https://love2d.org/wiki/love.keyboard.getScancodeFromKey) to get around this issue. I think we should consider this for our non US friends.

**Comment by nesbox** [comment]
TIC uses scancodes to handle input
The problem is that people use keyboard buttons names (Z X A S) instead gamepad buttons names (A B X Y)

**Comment by noxarivis** [comment]
i use WASD for all keys
Keyboard | Gamepad
S = A
D = B
A = X
W = Y

**Comment by josefnpat** [comment]
oh, does that make this ticket moot? @nesbox

**Comment by nesbox** [comment]
@josefnpat seems to
I'm thinking how to explain to people that TIC doesn't know anything about keyboard buttons, maybe show "intro" screen with current gamepad buttons mapping on every game start, as an idea
