### ISSUE TITLE
Come up with policy for ordering commands in console and change help command

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#378]
Right now the commands listed under help are pretty random. We should come up with a policy of some sort, even if it's just "do it alphabetically".

**Comment by nesbox** [comment]
I don't like that all the commands don't fit a screen and you have to scroll to view all of them.
Maybe, print the commands consecutive without a description...

**Comment by josefnpat** [comment]
That's a really good point. What if we treat it like `import` and add a usage case;

```
> help
usage: help edit|help|import|run|resume|etc
> help folder
open working folder in OS
usage: folder
```

**Comment by josefnpat** [comment]
Then we can just sort the usage args by alpha?

**Comment by nesbox** [comment]
yep 👍 I like it

**Comment by noxarivis** [comment]
another thing, the help doesnt fit on Android

**Comment by lolbot-iichan** [comment]
Ooops. Described similar suggestion in #461.

**Comment by lolbot-iichan** [comment]
#154 is related.

**Comment by nesbox** [comment]
lets do it with #154
