### ISSUE TITLE
Import sprites not import pallete.

### ISSUE THREAD

**Issue by harrisyu** [nesbox/TIC-80#379]
Import sprites not import pallete, but find the nearest color instead.
I think we should make it consistent for better import export workflow.

**Comment by nesbox** [comment]
the same as #364

**Comment by frenetic** [comment]
I did not understand what you meant.
Could you please explain it?

**Comment by sayaks** [comment]
i had this issue too. i imported sprites using `import sprites`, and i didn't get the palette that was used to make those sprites. i only got the sprites.

steps to reproduce:
1. create new cart
2. change palette such that two colors are very similar
3. paint using both colors
4. export sprites
5. create new cart
6. import previously exported sprites
7. the two different colors get mapped to the same color, and the palette is not imported

**Comment by TimotheeGreg** [comment]
That's related to #1411. Note that this behavior has been clarified on the wiki [here](https://github.com/nesbox/TIC-80/wiki/Console#importing-images) some time ago.
I think that's on purpose in order to not modify previous sprites and tiles.

**Comment by aliceisjustplaying** [comment]
Per @Skeptim's comment, this is documented and now closed.
