### ISSUE TITLE
Include icons on Linux desktops.

### ISSUE THREAD

**Issue by Popolon** [nesbox/TIC-80#380]
I attached a standard Linux desktop entry. it can be installed in :
/usr/share/applications/

Feel free to change/adapt as you want, I looked at few other .desktop files to make this one.

Something will be needed in Makefile to install it on Linux desktops, same process for all desktops, independent of hardware and desktop environment.

Perhaps a linux-install/install-linux section with the following rules:
install -Dm644 docs/logo/logo64.png "/usr/share/pixmaps/tic-80.png"
install -Dm644 docs/tic-80.desktop "/usr/share/applications/tic-80.desktop"

**Comment by nesbox** [comment]
ok, where is attached desktop entry?

**Comment by josefnpat** [comment]
We could include the .desktop and the `png` in the `make install`

I think we might want to make an SVG for the logo, looking at the way love is doing it: https://bitbucket.org/rude/love/src/37e1ced87caf/platform/unix/?at=default

**Comment by Popolon** [comment]
I believed I attached it, can't found again, so here is the content:
[Desktop Entry]
NameN=tic-80
Comment=a fantasy computer for making, playing and sharing tiny games.
Comment[fr]=Un ordinateur fantasiste pour faire, jouer et partager des petits jeux.
GenericName=
Exec=/usr/bin/tic-80
Icon=tic-80
Type=Application
StartupNotify=true
Categories=Game;Emulator;System;Development;IDE;
MimeType=text/plain;

**Comment by josefnpat** [comment]
@Popolon does this associate `*.tic` files with tic80 as well?

**Comment by Popolon** [comment]
Some corrections.
I make typo: 
*  NameN=tic-80 => Name=tic-80
* GenericName can be removed.
And that's better if Exec doesn't give path, and has %f to accept drag'n'drop of files as argument
* Exec=tic-80 %f

```
[Desktop Entry]
Name=tic-80
Comment=a fantasy computer for making, playing and sharing tiny games.
Comment[fr]=Un ordinateur fantasiste pour faire, jouer et partager des petits jeux.
Exec=tic-80 %f
Icon=tic-80
Type=Application
StartupNotify=true
Categories=Game;Emulator;System;Development;IDE;
MimeType=text/plain;
```

@josefnpat: you need to define a mime-type in the system with .tic extension first, and then  associate it in MimeType=.

There are standards for mime-types, I don't know them very well.

https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html

A xml should be placed here (need to check if x-tic-80 or vnd.tic-80 is the most standard compliant :
/usr/share/mime/application/x-tic-80.xml

And should be something like:
```
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="application/x-tic-80">
  <comment>Tic-80 fantasy computer cartridge</comment>
  <comment xml:lang="en">Tic-80 fantasy computer cartridge</comment>
  <comment xml:lang="fr">Cartouche pour ordinateur fantaisiste tic-80</comment>
  <generic-icon name="tic-80"/>
  <glob pattern="*.tic"/>
</mime-type>
```

And so, in the .desktop
MimeType=x-tic-80

**Comment by Popolon** [comment]
After looking around the net, the convention seem to be x-<namreoftheapplication>

Si the mime-type could be (for example): 
application/x-tic-80
and then on the tic-80.desktop file, MimeType should be:
```
MimeType=application/x-tic-80;
```

So we have this tic-80.desktop file:
```
[Desktop Entry]
Name=tic-80
Comment=a fantasy computer for making, playing and sharing tiny games.
Comment[fr]=Un ordinateur fantasiste pour faire, jouer et partager des petits jeux.
Exec=tic-80 %f
Icon=tic-80
Type=Application
StartupNotify=true
Categories=Game;Emulator;System;Development;IDE;
```
And this x-tic-80.xml :
```
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="application/x-tic-80">
  <comment>Tic-80 fantasy computer cartridge</comment>
  <comment xml:lang="en">Tic-80 fantasy computer cartridge</comment>
  <comment xml:lang="fr">Cartouche pour ordinateur fantaisiste tic-80</comment>
  <generic-icon name="tic-80"/>
  <glob pattern="*.tic"/>
</mime-type>
```
The mime-type file should be installed in /usr/share/mime/application/, and an update of the mime-type database need to be done :
```
install -m 644 x-tic-80.xml /usr/share/mime/application/
update-mime-database /usr/share/mime
```

**Comment by Popolon** [comment]
Up ! this could be implemented as is, do you want a clone + pull request?

**Comment by RobLoach** [comment]
A pull request for this would be helpful, thanks!

**Comment by nesbox** [comment]
already fixed
