### ISSUE TITLE
Music editor: sustaining notes through frames

### ISSUE THREAD

**Issue by mihaelkyeah** [nesbox/TIC-80#382]
Hello, dev/s.

Using and testing the music editor I have noticed that empty patterns don't work for keeping notes sustained in a channel, as they obligatorily cut off when switching frames. Is this intentional? I have had to use cloned instruments with plain volume envelopes to simulate sustaining which in fact consists of note retriggering in disguise.

I'm suggesting being able to sustain a note from a frame to another, using an empty pattern (different than zero).

Seeing how the patterns are limited (60 patterns when 1 song out of 8 alone can take up to 20 or more, especially when using more to mimic sustains), and I would assume that so are the instrument slots, I assume that you're going for a policy of making the best use out of a reduced quantity of resources; **this is only a suggestion** that I'm bringing up because I think it would help save space and allow for more possibilities in the music editing department.

On that note, I also wonder if it would be much trouble to add the feature to place volume changes on notes already playing without needing to retrigger them.

I hope this helps improve the program if you're willing to include it. This is also the very first fantasy computer I've ever used and except for that one detail, I'm quite pleased with it. Keep up the good work!

Regards,
-kyusawamura/mihaelkyeah

**Comment by nesbox** [comment]
It's not intentional, but all the notes reset from frame to frame at the moment.
Will try to fix that.
Thanks

**Comment by nesbox** [comment]
@kyusawamura could you please provide your cart with the music to test?

**Comment by frenetic** [comment]
Hey guys, was this one fixed?
