### ISSUE TITLE
Save to tmp file before run

### ISSUE THREAD

**Issue by lincerely** [nesbox/TIC-80#385]
It would be useful if tic-80 can save the session to an temporary `.tic` file automatically before running the game.

This additional feature can prevent data loss due to program/computer crash (e.g. out of memory), allowing developer to revisit the code and reproduce the error.

It is similar to [vim's swap file](http://vimdoc.sourceforge.net/htmldoc/recover.html).

**Comment by josefnpat** [comment]
This relates to #356

**Comment by lolbot-iichan** [comment]
This is also releated to #197 (endless loops), which is the only source of data loss that I had really experienced.

**Comment by nesbox** [comment]
dup of #221
