### ISSUE TITLE
License for cartridges.

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#387]
It would be nice to see from a cartridge if it can be modified and redistributed and on what conditions (the software license).

Also it would be nice to have some manifest in the cartridge with a link e.g. to github project and contact to the author.

I am wondering if I can modify existing game to create a split screen version. Currently the only way is to comment under the game on web page.

**Comment by jahodfra** [comment]
There is possibility to write the manifest as comment at the start of the source code.

**Comment by jahodfra** [comment]
There is possibility to write the manifest as comment at the start of the source code.

**Comment by jahodfra** [comment]
There is possibility to write the manifest as comment at the start of the source code.

**Comment by jahodfra** [comment]
There is possibility to write the manifest as comment at the start of the source code.

**Comment by nesbox** [comment]
we can add `-- license: CC0` tag to the header comments and I'll parse it when you upload cart to the website

**Comment by jahodfra** [comment]
We can even suggest names of the popular licenses.
https://choosealicense.com/licenses/

I am not sure if the license functionality is actually needed. It would be
good if the web would show what the owner allows to do with the project,
but that depends on people marking it.

čt 9. 11. 2017 v 6:51 odesílatel Vadim Grigoruk <notifications@github.com>
napsal:

**Comment by frenetic** [comment]
I like the idea of the `-- license` metatag. But, if you plan to add it, you should also consider a metatag to the content/author/cart site, like `--site: my.itch.io/cart`.

**Comment by ChildishGiant** [comment]
This is probably the list of standardised license identifiers you'll want to use. https://spdx.org/licenses/

**Comment by joshgoebel** [comment]
@nesbox How would you feel about adding a few more metatarsi:

- `license`
- `site`

To encourage cartridge authors to add these details...

**Comment by nesbox** [comment]
I don't mind and think they should be optional.
