### ISSUE TITLE
Compilation on Raspberry Pi B+ fails on LTO

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#389]
on new Raspbian I cannot build tic due to some LTO incompatibility.

```
pi@raspberrypi:~/tic/TIC-80 $ make arm
gcc -D__ARM_LINUX__ src/studio.c src/console.c src/run.c src/ext/file_dialog.c src/ext/md5.c src/ext/gif.c src/ext/net/SDLnet.c src/ext/net/SDLnetTCP.c src/ext/net/SDLnetselect.c src/fs.c src/tools.c src/start.c src/sprite.c src/map.c src/sfx.c src/music.c src/history.c src/world.c src/config.c src/keymap.c src/code.c src/dialog.c src/menu.c src/net.c src/surf.c src/tic80.c src/tic.c src/ext/blip_buf.c src/jsapi.c src/luaapi.c src/ext/duktape/duktape.c -O3 -Wall -std=c99 -Iinclude/lua -Iinclude/zlib -Iinclude/gif -Iinclude/sdl2 -Iinclude/tic80 -Llib/arm -D_GNU_SOURCE -lSDL2 -llua -ldl -lm -lpthread -lrt -lz -lgif -flto -o bin/tic
lto1: fatal error: bytecode stream generated with LTO version 3.0 instead of the expected 5.2
compilation terminated.
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:282: recipe for target 'arm' failed
make: *** [arm] Error 1
pi@raspberrypi:~/tic/TIC-80 $ cat /etc/issue
Raspbian GNU/Linux 9 \n \l
pi@raspberrypi:~/tic/TIC-80 $ cat /etc/debian_version
9.1
```

**Comment by nesbox** [comment]
I just added new build instructions yesterday, without LTO and prebuild libraries
```
sudo apt-get install git build-essential libgtk-3-dev libsdl2-dev lua5.3-dev libgif-dev zlib1g-dev
git clone https://github.com/nesbox/TIC-80
cd TIC-80
make linux
```
please try to build on your Pi and let me know
thanks

**Comment by jahodfra** [comment]
I will try to do that in the evening - compilation on raspberry takes 10's
of minutes.

I am also considering building binary on desktop and moving it.
I tried to compile with -fno-lto but that failed on dependencies. I suppose
this maybe also uses enclosed binaries.

čt 9. 11. 2017 v 6:46 odesílatel Vadim Grigoruk <notifications@github.com>
napsal:

**Comment by jahodfra** [comment]
Hi have you published the commit? I don't see any change regarding to arm flags.

https://github.com/nesbox/TIC-80/commit/7035731624b2290077801e039d2ec18ad211697e#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by nesbox** [comment]
You don't need arm flag, use 'make linux' pls

**Comment by son-link** [comment]
Just i can compile on my Raspberry Pi 3 under RetroPie (based on Raspbian Jessie) usimg the instructions for ALT Linux 64-bits and run fine, but i can't remap my gamepad (DualShock 3). Later i try with mi older gamepad.
Note: i can't compile with -llua5.3, search this under LINUX_FLAGS and delete 5.3 and works.

**Comment by torabora** [comment]
Today you can compile TIC-80 in this way.
Add jessie-backports repo to /etc/apt/sources.list:
deb http://ftp.debian.org/debian jessie-backports main
then run apt-get update (don`t worry about GPG)
Install needed soft:
sudo apt-get install git build-essential libgtk-3-dev libsdl2-dev zlib1g-dev
Install  liblua5.3-dev from jessie-backports:
sudo apt-get install -t jessie-backports liblua5.3-dev 
Get fresh TIC-80 and compile
git clone https://github.com/nesbox/TIC-80
cd TIC-80
make linux
run it: sh /bin/tic
Enjoy!

**Comment by nesbox** [comment]
@torabora great, added your steps to Build Instructions https://github.com/nesbox/TIC-80/wiki/Build-instructions#raspberry-pi
thanks

**Comment by jahodfra** [comment]
I compiled the .linux target on Raspberry B+. Unfortunately the program
runs so slow, that it takes over 10s just for to display new letters in
console.  Processor is over 100%. :(

pá 10. 11. 2017 v 20:28 odesílatel Vadim Grigoruk <notifications@github.com>
napsal:

**Comment by nesbox** [comment]
@torabora does it run slow on your side too?

**Comment by torabora** [comment]
no, it runs pretty fast

**Comment by jahodfra** [comment]
@torabora which model do you have?

**Comment by torabora** [comment]
Raspberry Pi 3 Model B

**Comment by jahodfra** [comment]
I borrowed Raspberry Pi 3 and it runs faster than version 2 so I can e.g. write to console. But e.g. surf command is unbearable slow and I wasn't able to play any game (I would estimate that it does around 1fps). I am not sure what I am doing wrong :/.

**Comment by nesbox** [comment]
@jahodfra pls try to install OpenGL driver
http://www.raspberryconnect.com/gamessoftware/item/314-trying_out_opengl_on_raspberry_pi_3

**Comment by AlRado** [comment]
Hello @jahodfra!
I followed the installation instructions on the wiki Raspberry Pi (Retropie) and I did it!
Surf on some games really slows down, but this happens on all platforms.
Please run the Tools> PERFORMANCE_MONITOR cartridge and see how many FPS it will show. On my RaspberryPi 3B -> 16 FPS, and in the browser on the laptop -> 13

**Comment by jahodfra** [comment]
I am using raspbian stretch. Apparently my problem was disabled OpenGL driver as suggested by @nesbox. After enabling it:

Raspberry Pi 2 B had 1-2fps.
Raspberry Pi 3 had 10 fps,
My phone Honor 7 had 24 in client and 11 fps in browser.

I tried 8bit panda and on Rpi2 it was too slow to be playable, but on Rpi3 it ran fine.

**Comment by nesbox** [comment]
@jahodfra ok, could you pls switch to this temporary branch https://github.com/nesbox/TIC-80/tree/chip2
and try to build and run it on your RPi
thanks

**Comment by jahodfra** [comment]
Can you specify which Raspberry? Rpi2 or Rpi3? Should I disable OpenGL
driver?

ne 12. 11. 2017 v 19:23 odesílatel Vadim Grigoruk <notifications@github.com>
napsal:

**Comment by son-link** [comment]
I compiled chip2 tree on my Pi 3 and now is too slow, 7FPS. I do not use the OpenGL driver, EmulationStation, Retroarch, etc, crash if enabled on RetroPie.

**Comment by nesbox** [comment]
thanks to all, I'll investigate it here #393
