### ISSUE TITLE
Permanent memory bug at first "run"?

### ISSUE THREAD

**Issue by andrechalom** [nesbox/TIC-80#390]
I'm having a weird bug using `pmem`. I'm trying to use `pmem(0)` to keep track of a high score, but maybe I'm missing something? I'm running tic 0.47.0 under ArchLinux, and I've tried using several invocations ("tic", "tic cart.tic", "tic cart.tic -code-watch game.lua" all result in the same problem).

The problem is: 

- I have run my game some times, and saved a "highscore" of 10 to pmem(0).
- I load my cart, and run it. `trace(pmem(0))` indicate the saved value is zero.
- I press Ctrl-R again. Suddenly, `trace(pmem(0))` indicates the correct value of 10.

Am I doing something wrong or is this really a bug?

**Comment by drako0812** [comment]
Are you making sure to call `sync()`? `sync()` makes any changes to the cartridge while running permanent (aka writes it to the cartridge file).

[Wiki: sync](https://github.com/nesbox/TIC-80/wiki/sync)

**Comment by nesbox** [comment]
`sync` copies only _sprites/map/sound_ data, seems it's a real bug with `pmem`
I'll see, thanks

**Comment by nesbox** [comment]
so, persistent memory depends on md5 hash of your code, _pmem_ resets every time you change the code
but you can define `-- saveid: my awesome game` and it will keep pmem
https://github.com/nesbox/TIC-80/wiki#cartridge-metadata

**Comment by andrechalom** [comment]
I am aware of the saveid, and I'm using it in my project. This does not
close the issue. Is there any other info I can provide to help you track
this bug?

**Comment by nesbox** [comment]
are you built TIC from sources or using stable version?

**Comment by andrechalom** [comment]
I had built TIC from source using commit
7035731624b2290077801e039d2ec18ad211697e. Now I've tried again, rebuilding
from f4808d40d4ca85c8b3a0562bd7eb0d9e436d04ee, and the problem is gone.
Thanks!

**Comment by nesbox** [comment]
great, thanks
