### ISSUE TITLE
dofile hmmms

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#394]
This:
![image](https://user-images.githubusercontent.com/13716824/32751535-333e0686-c8be-11e7-9c29-0bbbacad552f.png)
Produces this:
![image](https://user-images.githubusercontent.com/13716824/32751553-407fa430-c8be-11e7-81f6-44dcf38eea31.png)

The same goes for "miner.js":
![image](https://user-images.githubusercontent.com/13716824/32751590-62fdb1dc-c8be-11e7-94fa-88980cfee4cc.png)
![image](https://user-images.githubusercontent.com/13716824/32751603-6a9012b4-c8be-11e7-9810-632809b0749f.png)

# Unless I have my metadata in the cart, since **this runs fine**:
![image](https://user-images.githubusercontent.com/13716824/32752446-1bfc8274-c8c1-11e7-9d11-434060040b1f.png)

But then adding the metadata to the front of the lua version doesn't work:
![image](https://user-images.githubusercontent.com/13716824/32751783-d42759b2-c8be-11e7-8b09-7d4840a4b724.png)
![image](https://user-images.githubusercontent.com/13716824/32751789-d9934550-c8be-11e7-9984-5b91ce6a49a1.png)

So I then put `dofile` on the first line and the meta data after:
![image](https://user-images.githubusercontent.com/13716824/32751818-f1783842-c8be-11e7-9bb8-8496292f2a70.png)
![image](https://user-images.githubusercontent.com/13716824/32751828-f81d6924-c8be-11e7-8b3a-0b4d73b53c4e.png)

So all in all, I'm confused but I can still use my external editor with js so it's not holding me up. I'm running Version 0.47.0 (stable) natively on Windows 10

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/32752548-7906369a-c8c1-11e7-9f40-f78b60112b04.png)
this is now running but throwing errors with my code. And when I make a change to my code it's not being updated when I run again

**Comment by StinkerB06** [comment]
What OS are you running TIC-80 on?

**Comment by ChildishGiant** [comment]
> I'm running Version 0.47.0 (stable) natively on Windows 10

**Comment by AlRado** [comment]
The code should be located near executable tic. exe
![dofile](https://user-images.githubusercontent.com/440703/32763273-be4bec74-c90f-11e7-9106-14637be39613.gif)

**Comment by ChildishGiant** [comment]
It is. You get a different error for not having it in the correct spot. `dofile: file 'example.file' not found`

**Comment by nesbox** [comment]
@ChildishGiant _file is not found_ because you use wrong relative path

**Comment by ChildishGiant** [comment]
I'm not getting _file not found_. I'm getting the _you can use 'dofile' only on the first line_. Even when it is on the first line.
