### ISSUE TITLE
Implement an interface for language plugins

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#398]

**Comment by nesbox** [comment]
example made by @Nullious https://bitbucket.org/MonstersGoBoom/sharelanguagetest/
thanks

**Comment by Jummit** [comment]
The link to Nullious language test isn't working.

**Comment by Nullious** [comment]
I had to remove the share after the decision to have a pro/paid version of Tic80 was announced. Contractually I can't contribute nor share code with Tic80 any longer.  @jummit

**Comment by nesbox** [comment]
😲

**Comment by frenetic** [comment]
Is this a thing? Can we close this one?
