### ISSUE TITLE
Add extra low res mouse mode

### ISSUE THREAD

**Issue by josefnpat** [nesbox/TIC-80#399]
So currently, the `--mouse` mode only detects if the left mouse button is detected.

I realize that there isn't any space left (as noted in #36) but was thinking that we could either:

1) remove a bit from the width (reducing horizontal fidelity by two) to add RMB
2) remove a bit from the height (reducing vertical fidelity by two) to add RMB
3) remove a bit from the width and height to add RMB and MouseWheelDown

perhaps a `--mouselow` attribute?

**Comment by nesbox** [comment]
Honestly, it looks like not very an elegant solution
Also a question, how right mouse button will work on touch devices?

**Comment by josefnpat** [comment]
You're right - I forgot target deploys to android. Unless you can think of a reason to keep this open, I'll close it.
