### ISSUE TITLE
if mouse is clicked in a box function [enhancement]

### ISSUE THREAD

**Issue by Jummit** [nesbox/TIC-80#403]
Every time i make a game with mouse support i make a function to get if the mouse is pressed inside a box.
Syntax is like this:
`mousebox(mouseX, mouseY, boxX, boxY, boxWidth, boxHeight)`
Would be cool to have this added.

**Comment by nesbox** [comment]
not sure, don't want to clutter up api with so small functions

**Comment by Jummit** [comment]
Ok, I can easily write my own function to do it. I will close this now.
