### ISSUE TITLE
Cannot clone the wiki

### ISSUE THREAD

**Issue by stefnotch** [nesbox/TIC-80#404]
Thanks to a github bug, pages like https://github.com/nesbox/TIC-80/wiki/Pathfinding:-BFS-Algorithm can't be cloned. The pages have a colon (`:`) in their file name and Windows/NTFS don't support colons in file names.

One possible workaround would be to use `U+A789` `꞉` instead.

**Comment by nesbox** [comment]
I see you are fixed it
close
