### ISSUE TITLE
Very bad audio

### ISSUE THREAD

**Issue by sirsnowy7** [nesbox/TIC-80#406]
Usually, I get very, very good audio quality out of my Raspberry Pi 3B, with no latency, and good bass and treble, with a speaker plugged in. However, whenever I use TIC-80, I get very high latency - up to a whole second of it - and just completely horrible sound quality, as if all sounds were noise waves. I tried running the audio editor on both my Android phone and my Raspberry Pi. The Raspberry Pi gave me seconds of latency, while my phone gave me quick response and good quality sound.
I also tried music demos, to the same result.
What's the problem here?

**Comment by nesbox** [comment]
I think it's performance problem, we are working on it here #393
so, it's a duplicate, I close it
