### ISSUE TITLE
getPixel doesn't correctly map the pixel.

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#408]
setPixel maps color through mapping and then marks it into a screen.
getPixel takes color from the pixel and then maps it through mapping (but correctly it should map it through inverse of mapping).

if mapping is (color + 1) % 16 and color = 5
than setPixel marks 6
getPixel takes 6 and maps it to 7

That is apparently not correct. I suppose we cannot ensure that mapping has inverse function so I would recommend not to map color back in getPixel.

**Comment by nesbox** [comment]
seems to be true, we shouldn't map color in _getPixel_ function

**Comment by nesbox** [comment]
fixed
