### ISSUE TITLE
Please add hints in the music editor - there are so many confusing cells in it

### ISSUE THREAD

**Issue by AlRado** [nesbox/TIC-80#411]

**Comment by Jummit** [comment]
But in the music editor? Maybe a tutorial or so, but there is not very much space in the editor itself...

**Comment by carlsmith** [comment]
I agree with @Jummit - external documentation would be a better solution.

**Comment by frenetic** [comment]
Could you guys draft something, so we can improve our Wiki?

**Comment by TimotheeGreg** [comment]
The music editor wiki page exists since 2021and has been detailed a lot since then, there are some tutorials too, I think this issue can be closed.
