### ISSUE TITLE
Allow to load a map of tiles of any length, not only 32kb

### ISSUE THREAD

**Issue by AlRado** [nesbox/TIC-80#412]

**Comment by lolbot-iichan** [comment]
By "any length" do you mean "any length below 32kb"? (my suggestion: yes)
If map is smaller then 32kb, should other map bytes be zeroed or left as is? (my suggestion: zeroed)

**Comment by AlRado** [comment]
You are absolutely right: any length below 32kb and other map bytes be zeroed

**Comment by nesbox** [comment]
done
