### ISSUE TITLE
input rgb values into palette editor

### ISSUE THREAD

**Issue by ambyra** [nesbox/TIC-80#415]
It would be nice to have a box to enter rgb palette values instead of using the sliders.

**Comment by nitrofurano** [comment]
entering hexcolours (from sites like colourlovers, chromapost, etc.) would be great too! specially with clipboard (copy/paste) support

**Comment by frenetic** [comment]
You can select the color you want to change and click the paste hex code button, to replaced the selected code for a new hex, like `deeed6`.
You can also copy/paste a sequence of **16** hex codes and click the paste button to replace the entire palette. (this sequence can contain spaces and line breaks).

It is not what you requested, but it is what TIC-80 has right now.
I hope it helps you while your request is being analyzed by @nesbox .

**Comment by nesbox** [comment]
Added text edit for rgb values b6b9693
![image](https://user-images.githubusercontent.com/1101448/118982741-62d6d480-b984-11eb-866e-3acee771a2e7.png)
