### ISSUE TITLE
`save` only includes sprites 0-255 when the map is empty

### ISSUE THREAD

**Issue by harbichidian** [nesbox/TIC-80#420]
Using the new `save <filename>.lua` command in v0.50, only the sprites in the "Tiles" section (0-255) are saved to the file. Sprites in the actual "Sprites" section (256-511) are not saved.

**Comment by harbichidian** [comment]
With nothing in the map, `save` seems to populate `<SPRITES>` with sprites 0-255 and no `<TILES>` element.

After adding something to the map, `save` populates `<TILES>` with sprites 0-255, `<SPRITES>` with sprites 256-511, and `<MAP>` with the map data.

**Comment by nesbox** [comment]
can't reproduce, could you provide binary version of your cart

**Comment by harbichidian** [comment]
@nesbox yeah, I can't re-reproduce it. Strange.
