### ISSUE TITLE
Import sprite to specific slot

### ISSUE THREAD

**Issue by HardlineStudios** [nesbox/TIC-80#426]
Right now importing sprites always starts at slot 0. It'd be nice if you could import starting at whatever slot was last selected.

**Comment by SuperPupperDoggo** [comment]
Or, even better, be able to specify where it imports

**Comment by nesbox** [comment]
I think adding some extra parameters to the `import sprite` command.
For example, it could look like `> import sprites img.png bank=2 page=2 mode=4 x=5 y=16`
Same for `import sfx` `import music` `export ...` and etc commands.

**Comment by SuperPupperDoggo** [comment]
Yea that sounds good.

**Comment by nesbox** [comment]
Added `bank=0 x=0 y=0 w=0 h=0 ovr=0` params to the import command c71d4bf
