### ISSUE TITLE
Music gets choppy when run in browser

### ISSUE THREAD

**Issue by fangzhangmnm** [nesbox/TIC-80#427]
I tried my game in Edge and Chrome, but the music became choppy.

**Comment by Ewpratten** [comment]
this also happens for me. it seems like the music is being played at half speed.

**Comment by nesbox** [comment]
I'll create a test app soon, and we will try to investigate why it gets choppy...

**Comment by nesbox** [comment]
So, I added some fixes
could you pls run this in the browser and let me know?
[html.zip](https://github.com/nesbox/TIC-80/files/1584259/html.zip)
@fangzhangmnm @Ewpratten
Thanks

**Comment by BozoDel** [comment]
Howdy!

So, I noticed this chopiness too. Also, it seems that it's not just the sound, but the whole game is running at half speed (compared to running it on the downloaded TIC-80). I tested with a stopwatch, by jumping in 8-bit Panda. It's not precise, but it doesn't have to be: the difference is huge.

The same thing happened with the html file you provided.

I'm using Firefox on Linux, btw. Please tell me if you need more info or tests.

**Comment by nesbox** [comment]
hmm, I even can't guess the reason
could you test it in Chrome pls

**Comment by BozoDel** [comment]
It gets more strange. On Chrome, 0.60.0 works fine, but 0.50.1 is choppy.

**Comment by nesbox** [comment]
I did some changes with game loop timing in 0.60.3

**Comment by BozoDel** [comment]
Oh, so sorry, I meant 0.60.3, not 0.60.0.
