### ISSUE TITLE
Watch command line arguments for sprites

### ISSUE THREAD

**Issue by adiron** [nesbox/TIC-80#428]
Hi!

I'm coding a tiny game on tic80 and prefer to edit my sprites outside of the TIC80 editor. I can load the sprites just fine with `-sprites`, but it means I have to exit and reopen TIC80.

It could be useful to have a command to always watch the sprite for changes and load that into the cartridge upon change.

This is already done for code with `-code-watch`.

**Comment by buckle2000** [comment]
A better solution would be to remember the last placement of window.
You should then use something like [`entr`](http://eradman.com/entrproject) to restart `tic80`.

**Comment by joshgoebel** [comment]
Why not just `import sprites`?
