### ISSUE TITLE
command quit missing

### ISSUE THREAD

**Issue by nitrofurano** [nesbox/TIC-80#430]
when i try to enter "quit", it shows an error "unknown command: quit" - and when i try "exit" instead, it quits fine

is there planned to have soon "quit" command behaving like "exit"?
and i think would be great having ctrl+q available (and perhaps alt+f4 for people more used to that)

thanks!

**Comment by nesbox** [comment]
don't see the problem to use `exit` instead `quit`
anyway, I added `quit` and `CTRL+Q` shortcut
