### ISSUE TITLE
Proper command line interface

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#432]
The tic-80 should be able to print own version and help. Cartridge file should be possible to specify on any place not just as the first argument.

I recommend using one of the following libraries:
http://www.gnu.org/software/libc/manual/html_node/Parsing-Program-Arguments.html

**Comment by nesbox** [comment]
yes, it cmd parsing works wrong
thanks

**Comment by nitrofurano** [comment]
for example, when we add -fullscreen argument, .tic files doesn’t get opened, for example "tic80 -fullscreen game.tic" - and thanks! :)

**Comment by nesbox** [comment]
fixed with #416

**Comment by jahodfra** [comment]
Hi I think the command still lacks ability to self document itself -help, -version, -license. That's actually quite useful and expected in unix env. I can take this ticket and implement that with the help of arg_parse if you are willing to include this dependency.

**Comment by nesbox** [comment]
@jahodfra yes, pls do
also, I don't think we need to use an external library to parse so easy command line
just add another case somewhere here https://github.com/nesbox/TIC-80/blob/2b406bce51c003ae0e1cd94cd4fe534c441678ed/src/console.c#L2918

**Comment by jahodfra** [comment]
I will check our options and what the library actually solves. I suppose
mainly error reporting :).

čt 7. 12. 2017 v 16:34 odesílatel Vadim Grigoruk <notifications@github.com>
napsal:

**Comment by jahodfra** [comment]
So argp (part of GNU C library) reports unknown options and missing operands. Also it automatically generates help on --help command and allows specification of usage on --usage. Also the --version command prints the version of the binary.

I also noticed that it handles -- escape argument character. So it is possible to pass arguments starting with "-".

It is not hard to use. Only disadvantage is that we would have to use long operand e.g. --code instead of -code.

I am not sure if it is available out of the box for all platforms.
http://www.gnu.org/software/libc/manual/html_node/Argp-Examples.html#Argp-Examples

**Comment by jahodfra** [comment]
So generally I think it is better to extend existing util about --version, --help (or -help, -version) commands. @nesbox: What do you think about replacing one dash e.g. "-code" with two dashes "--code" ? Double dashes is standard in unix.

**Comment by nesbox** [comment]
what if we could use both `-` and `--` prefixes

**Comment by jahodfra** [comment]
I will do that.

**Comment by jahodfra** [comment]
@nesbox Why are the errors in command line displayed in system dialogs? Wouldn't it be enough to just print them to stderr ? I am wondering if the parsing should not happen at the start of the program.
Also do I understand correctly that Emscripten and Android do not process standard command line arguments?

**Comment by TimotheeGreg** [comment]
I think this is solved.
