### ISSUE TITLE
Flags in the Map Editor

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#433]
divide map into two parts
add a layer to the Map Editor
draw flags representation on the second layer if enabled

**Comment by Jummit** [comment]
Maybe use sprites from the sprite map as flags, you could use empty sprites to just use them as flags, the are numbered so it would be easy to work with. I would like this because you could make maps with two layers, one for items and one for the map.

**Comment by AnastasiaDunbar** [comment]
@Jummit I think it's better with the maps, why use empty sprites that just take up space for graphics when you could just use an array for flags and access using sprite index?

**Comment by Nullious** [comment]
I'd suggest flags for tiles vs flags for the map. a "floor" tile is always going to be a floor, an "underwater" tile will always visually be underwater so the flag should be tied to the visuals. doing it in the map will make it easier to miss important aspects.

**Comment by jahodfra** [comment]
I think flags have to have graphic representation - so the level editor will know what the flag represents.

Maybe it could be just mode for map, where on some selection the editor would display part of the map as overlay (and reduce the map area to half).

**Comment by Nullious** [comment]
losing 256 bytes for 8 bits of flags per character 
or 128 bytes for 4 bits of flags per character IS a lot more preferable than losing half the map.

**Comment by jahodfra** [comment]
Do the flags per tile bring something over having the specification directly in the code?

**Comment by RobLoach** [comment]
There are now sprite flags, but no API to grab the flags that had been set. Perhaps they could become the return value of `spr()`?

![Screenshot at 2020-04-11 01-53-22](https://user-images.githubusercontent.com/25086/79036563-45d3ad80-7b97-11ea-968a-777ef02b477d.png)

**Comment by potato25** [comment]
would dividing map into two parts consume map memory and space ?
Wonder how map would look like with flags representation

**Comment by rahul625** [comment]
Since fget() and fset() are implemented , should this be added to 0.90 project ?

**Comment by nesbox** [comment]
Let's decide after the release.

**Comment by nesbox** [comment]
Let's stop on flags for sprites atm
