### ISSUE TITLE
Fold function in code editor

### ISSUE THREAD

**Issue by Jummit** [nesbox/TIC-80#435]
Because the text size in the editor is very large, you can't have an overview of your code. If you could fold functions, loops and tables you would close everything you don't need and editing would be a lot nicer/easier. Here is a [gif](https://discourse-cdn-sjc1.com/business/uploads/github_atom/original/3X/c/3/c32ed189ea5c96f3f751995518bde37528113675.gif) (I didn't make it)

**Comment by adiron** [comment]
To get this right now, you can edit your code in an editor which has code folding. (with the pro version)

**Comment by nitrofurano** [comment]
Amos (perhaps Stos too) had such feature - Geany IDE comes with it as well

**Comment by Jummit** [comment]
@adiron I use runfile() at the time. But i want to make the code editor usable, so I can code there.

**Comment by jahodfra** [comment]
I think the target is not to reimplement profi text editor inside TIC. The feature is quite nice, but no so easy to develop. To implement the editor has to be able to parse the program to identify sections (Lua, Js, Moonscript). Alternative is to do folding according to the indentation. There is also lot of interaction so moving to folded lines have to automatically expand them.

**Comment by nesbox** [comment]
I think _folding_ is too much for such a small editor, maybe just add bookmarks by `CTRL+F2/F2`

**Comment by Jummit** [comment]
That would close #405, because you could add bookmarks to go to your tables.

**Comment by nesbox** [comment]
working on bookmarks...

**Comment by nesbox** [comment]
Added Bookmarks support to the Code Editor cf598db (work in progress).
```
CTRL+F1         - toggle bookmarks
SHIFT+F1        - go to previous bookmark
F1              - go to next bookmark
CTRL+SHIFT+F1   - remove all the bookmarks
```
![screen](https://user-images.githubusercontent.com/1101448/91639463-71104980-ea1f-11ea-900e-42bccdd3fb48.gif)
