### ISSUE TITLE
sync() raises "RangeError: invalid stack index 0" in JS

### ISSUE THREAD

**Issue by adiron** [nesbox/TIC-80#437]
I was writing a game in JS when I encountered a bug in which running `sync()` in JS raises the following error:

> RangeError: invalid stack index 0

I've not been able to solve this problem.

Version of TIC80:  `TIC-80 tiny computer 0.50.1 Pro`
OS: `macOS 10.13.1 (17B1003)`

(I've not tested this on other OSes)

**Comment by nesbox** [comment]
I made a fix, pls check
[tic80_pro_437_fix.dmg.zip](https://github.com/nesbox/TIC-80/files/1526114/tic80_pro_437_fix.dmg.zip)
Thanks
