### ISSUE TITLE
Vibration on mobile when screen is shaking

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#44]
Can be useful in games like https://spazzylemons.itch.io/ticochet

**Comment by harraps** [comment]
Add the same functionality for game controller, if possible.

**Comment by nesbox** [comment]
@harraps will try, thanks

**Comment by nesbox** [comment]
info for me: 
**Force Feedback Support** 
https://wiki.libsdl.org/CategoryForceFeedback

**Comment by nesbox** [comment]
also vibration for touch gamepad

**Comment by Anrock** [comment]
I suppose that will require expanding TIC-80 API anyways.

**Comment by nesbox** [comment]
wonfix
