### ISSUE TITLE
[Android] USB keyboard not working as input

### ISSUE THREAD

**Issue by shockdesign** [nesbox/TIC-80#444]
I've plugged my USB keyboard and it doesn't seem to be working using it as an input device with TIC-80, however on screen keyboard works fine..

Keyboard does work with other inputs natively in other apps.

**Comment by frenetic** [comment]
@shockdesign Could you please test it again to check if this bug still persists?
Also, could you please provide more information about the device, operating system and keyboard.
Thanks.
