### ISSUE TITLE
Make mouse pointer disappear in games that don't support it

### ISSUE THREAD

**Issue by adiron** [nesbox/TIC-80#445]
On macOS, when playing games, the mouse pointer stays visible even in games without mouse support. 

In my opinion the desired behavior is to make the mouse pointer disappear upon keyboard input.

I haven't tested other platforms but I would imagine they behave similarly.

**Comment by LovelyA72** [comment]
I think if will be better if the mouse disappear after few seconds of delay. And will appear when you move your mouse again(just like YouTube)

**Comment by lolbot-iichan** [comment]
Well, actually, there is some point in hiding cursor even in mouse-controlled games if they provide custom cursors like https://tic.computer/play?cart=148

**Comment by adiron** [comment]
Maybe there needs to be a cartridge tag enabling game creators to request the mouse to stay in view if they don't want it disappear. Default should be no pointer (if your game has a pointer I get the feeling that it's best practice to implement it yourself)

**Comment by jahodfra** [comment]
I am wondering how many cartridges use mouse without specific cursor. Maybe it makes sense to start with disabled mouse cursor. Should we even allow system cursor?

**Comment by jahodfra** [comment]
I implemented hiding mouse if there is "--input" tag with different value than "mouse" #498

**Comment by nesbox** [comment]
done here efadc1f by @jahodfra 
thanks
