### ISSUE TITLE
Customize keymap on export

### ISSUE THREAD

**Issue by adiron** [nesbox/TIC-80#448]
At the moment, keymaps depend on the user's `config.tic`.

When exporting to JS, it means that the controls are **back to defaults** and player 2 is unbound. This limits the creation of 2-player games.

When exporting a game as native, it generally means that the game's keymap config would be whatever the user has in their own `config.tic`. I don't think this is desired behavior necessarily - especially since the entire premise of "export" is to create a **self-contained** game. If it depends on the user's config, it's not exactly self-contained.

Lastly, it prevents some creative use of the controls to extend existing functionality in games :)

IMO, the desired behavior would be to give content creators ways to change their games' keymaps. Especially when exporting js! Also, self-contained exported games should have their configs stored entirely separately.

**Comment by nesbox** [comment]
relevant #220

**Comment by adiron** [comment]
Interesting, and I agree that issue is very relevant to this one. It's basically the touchscreen equivalent. Glad someone brought it up, actually, since I haven't thought of it myself! 👍 

## Use cases
As for this issue, it depends on use cases. I will try to outline two:

**1. User has TIC-80 configured on their system, they are opening your game via `load`, `surf` etc.**:
The user probably has their own custom bindings/controls that they like/are familiar with. They know how to define controls if they want to.

**2. User has opened your game via the browser or native app without opening TIC-80 first and manually loading the game**
The user may not know about TIC-80 at all. They likely don't have a preferred control scheme for TIC-80 games. All they know about is the game they're looking at right now and don't want to define a control scheme.

## Proposed technical solution

I propose two things:
a. Add a tag in the cartridge code to specify _default keyboard controls_ (and possibly touchscreen controls, see #220). e.g.:
`-- defaultcontrols: up1:w, down1:s, left:a, right1:d, up2:up, left2:left, right2: right, down2:down`
(Where up1 is player 1's up key, up2 is player 2's up key, etc.)
Exact syntax and implementation is debatable ofc.

These controls will only be applied in use case 2 (where the user isn't a TIC-80 user and the game was opened from a native app or web page). The user may override them manually, but they will be applied by default.

b. Add an `insistdefault` tag
Some games may need more than 8 buttons per player, or have vastly different layouts, and may suggest their own keyboard controls.

With feature A, use case 2 is covered. But use case 1 may not be aware that the game has suggested controls. In this case, users of use case 1 will receive a notification that the game has their own suggested controls that are optimized for the game. Something like:

`This game has specific a specific keyboard layout suggested by the developer. Would you like to use it?
[YES] [NO]`

**Comment by adiron** [comment]
I just want to come back to this issue for a moment, as I'm working on a two-player game and at the moment can't show it to other people on the web. That is, not without them having to dig through menus to set the controls first! :(

It's a two player game, and `export html` exports an HTML without player 2 bindings.

**Comment by nesbox** [comment]
dup of #220
