### ISSUE TITLE
Application restart resilience

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#451]
It is quite common the application is killed e.g. when interrupted by different application. It would be nice to be able to recover the cartridge.

**Comment by nesbox** [comment]
relevant #356 ?

**Comment by fadookie** [comment]
Not sure if this is the same issue I'm having but it appears as if any time TIC-80 is backgrounded, upon resuming it shows a black screen. This makes it very difficult to use as an editor. It does seem that sound continues to play and it responds to the back button.

Device: Google Pixel 1st Gen
OS: Android 9.0

**Comment by pcornier** [comment]
black screen is reported here: #657

**Comment by nesbox** [comment]
we are going to add autosave to backup here #221 
black screen fixed with #657
