### ISSUE TITLE
Allow using/pasting palettes with less than 16 colors

### ISSUE THREAD

**Issue by frenetic** [nesbox/TIC-80#454]
I was having a good chat at this thread https://itch.io/t/171821/huge-list-of-pallets when I realized: there are cool games with less than 16 colors.
Probably, someone using TIC-80 would like to give a try to the challenge of using less than 16 colors to make a game.
The downside is: You cannot paste a palette with less than 16 rgbs hex codes.

My idea is: allow users to paste 2+ color palettes. If this happens, the remaining available color slots should default to black (0x000000) or null (if user tries to use this color, it gets an error).

**Comment by nitrofurano** [comment]
i guess these colours could be also repeated, or mixed randomly or sequentially

**Comment by joshgoebel** [comment]
I would imagine pasting a palette with fewer colors would NOT touch later palette entries that were not in the pasted palette.

**Comment by nesbox** [comment]
Allowed pasting palette < 16 colors 4b5f782
Thanks.
