### ISSUE TITLE
Allow users to paste palettes with white spaces

### ISSUE THREAD

**Issue by frenetic** [nesbox/TIC-80#455]
Users may visit sites with palette lists, like https://lospec.com/palette-list and try to copy and paste one of their palettes into TIC-80.
However, their palette strings may have line breaks and/or a EOF character, which would block the "pasting" event, making it "hard" for users, since they have to convert the palette into a huge string.

Palette example:
```
0d080d
4f2b24
825b31
c59154
f0bd77
fbdf9b
fff9e4
bebbb2
7bb24e
74adbb
4180a0
32535f
2a2349
7d3840
c16c5b
e89973
```

Users have to convert it into a single like string, and make sure it does not have some kind of EOF character.

**Comment by nesbox** [comment]
fixed here #456
