### ISSUE TITLE
Category "Demos" is confusing

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#460]
"Demos" category on website has both state of art finished non-Game works and demonstration of cool effects and ideas (aka "Demoscene"), API sample usage code snippets and proofs-of-concepts for some hacks (aka "Tutorials") and even small engines (aka "Tools"?!).

Maybe you should split it and/or add some recomendation on how cartridges should be categorized.

**Comment by Anrock** [comment]
Seems to be done already.

**Comment by lolbot-iichan** [comment]
@Anrock It does not seem to fixed. "Demos" is still a single category on website: https://tic.computer/play?cat=1 and there are still different types of apps in this single category: demoscene, code snippets, tools, etc. This issue can be closed as "Wontfix" if @nesbox is OK with it, though...

**Comment by Anrock** [comment]
Oh, I see what you mean. To me it seems fine right now - it contains demonstration versions of something. But having some guidelines on categories seems like a reasonable request.

**Comment by nesbox** [comment]
wontfix
