### ISSUE TITLE
pwd (print the current directory)

### ISSUE THREAD

**Issue by Popolon** [nesbox/TIC-80#466]
It was hard to find what was the current directory on linux version, and I was not able to find it on Android version. The directory where cartridge are saved by default is so not clear. export/import open a file requester but not save, so there is no clue to know what is the current directory. I tried to use find function in termux on Android to find my saved cartridge without success.

Add a unix like pwd function in the console that print the current directory could help a lot.

Could be related to #30 and #54

**Comment by lolbot-iichan** [comment]
TIC80's folder paths are relative. `cd /` brings you to TIC's root folder, not actual fs root. So, `pwd` consistent with `cd` & `mkdir` should print relative paths, like `/`.

If this request is implemented, command name should be different from `pwd`.

**Comment by MineRobber9000** [comment]
Also, `folder` opens the folder that the games are stored in (on Linux version at least).

**Comment by trelemar** [comment]
as @MineRobber9000  said, `folder` command will open system file manger in TIC's data folder.

**Comment by Popolon** [comment]
That was not the good answer at all. folder open the directory but don't say where is it in the filesystem.

**Comment by Popolon** [comment]
I downloaded again last apk version (0.60.3) from this github repository for Android, and folder command doesn't even exists on Android version :
<pre>
>folder
unknown command:folder
</pre>
