### ISSUE TITLE
[chrome os / android] Keyboard not working on chromeos

### ISSUE THREAD

**Issue by Ewpratten** [nesbox/TIC-80#467]
in the a Tic80 android app on chrome os, tic does not support any buttons except 'UP, DOWN, LEFT, RIGHT, ENTER, BACKSPACE, SHIFT' so the default 'a,s,z,x' do not work and using the other buttons is inconvenient.

**Comment by nesbox** [comment]
relevant to #60
it was closed in .60
pls check
