### ISSUE TITLE
Crash on TIC-80 Pro

### ISSUE THREAD

**Issue by LovelyA72** [nesbox/TIC-80#470]
When i drag a tic file on my self compile TIC-80(tic80.exe), It will appear a white screen  and the game will crash.

I am using Visual Studio 2015 Professional to compile the program.

Will that happens on  official release of TIC-80 Pro? It will not happen on non-pro version

**Comment by nesbox** [comment]
yes, reproduced
thank you

**Comment by jahodfra** [comment]
For me it crashes on write at console.c:2984 (memcpy function). (according to valgrind)

**Comment by nesbox** [comment]
fixed here e5bc8f2
thanks
