### ISSUE TITLE
Please, add "cartidge reset" api call

### ISSUE THREAD

**Issue by taticoma** [nesbox/TIC-80#473]
It will be very usefull if You add somethink like ```cart_reset()``` thats performs total reload of cartridge(maps, sprites etc) and restarts game.

**Comment by lolbot-iichan** [comment]
Like the idea, it may be a useful thing to do after GAME OVER screen, to quickly return player to main menu without dealing with code.

I suggest to call it just `reset()`.

**Comment by nesbox** [comment]
will try to add `reset()`
also, you can use `sync()` to reload sprites/map/... from the cartridge to RAM

**Comment by nesbox** [comment]
added `reset()` API
Cart will be reset on the next tick after `reset` is called
done
