### ISSUE TITLE
Pro version's drag and drop issue No.2

### ISSUE THREAD

**Issue by LovelyA72** [nesbox/TIC-80#475]
In the newest build, It won't crash when you drag and drop tic file on the exe. But the cursor will become a quarter of TIC-80's logo. It happens on multiple carts.
![qq 20171219104658](https://user-images.githubusercontent.com/29054052/34138386-2c10f0a0-e4aa-11e7-8c8f-79b770c67103.png)
![image](https://user-images.githubusercontent.com/29054052/34138432-67f3c71e-e4aa-11e7-8051-ca0778915e54.png)

Still using Visual Studio 2015

Thanks.

**Comment by nesbox** [comment]
hmm, can't reproduce
could you type `config` command and look at 
``` lua
	CURSOR=
	{
		SPRITE=-1,
		PIXEL_PERFECT=true,
	},

```

what values do you have?

**Comment by nesbox** [comment]
@LovelyA72 ^

**Comment by LovelyA72** [comment]
![image](https://user-images.githubusercontent.com/29054052/34319805-c26c6466-e825-11e7-9680-24f5f21298df.png)
sorry for being late... This is my config. It looks like the value is false...
(Ignore my silly window nameXD)

**Comment by nesbox** [comment]
what if you call `config reset` command...

**Comment by nesbox** [comment]
still can't reproduce
could you please run debug version in the VS and look what is going here https://github.com/nesbox/TIC-80/blob/master/src/studio.c#L2252
thanks @LovelyA72

**Comment by LovelyA72** [comment]
Well... Now even i can not reproduce it... I think it might be just a graphic card issue... Sorry about that

**Comment by nesbox** [comment]
ok, thanks you
