### ISSUE TITLE
This code makes assumption that get_script_config(tic)->singleComment is 3 chars long

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#478]
https://github.com/nesbox/TIC-80/blob/6a19f59b9d00a09b3318e3270194b162c6ca34b0/src/code.c#L1086

**Comment by lolbot-iichan** [comment]
I suggest to use something like this: https://github.com/lolbot-iichan/TIC-80/blob/c9ce739a79742fa36e7bc7a9be26bbca8f7ba528/src/code.c#L1214-L1215

**Comment by nesbox** [comment]
done
