### ISSUE TITLE
This code makes assumption that every language highlighter can be implemented with unified parse()

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#479]
https://github.com/nesbox/TIC-80/blob/ef502b2496b8122da112879e0df8ffc16ec8655d/src/code.c#L375

Maybe we need something like `tic->api.get_script_config(tic)->parse` for supporting languages with custom highlighters.

**Comment by nesbox** [comment]
moved parse logic to the lang config 6bb605e
done
