### ISSUE TITLE
[found in fork] 'writeArrayToMemory' was not exported in tic.js

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#482]
I have merged latest commits to my repo https://github.com/lolbot-iichan/TIC-80
EXE file build with `make command` works all right.
JS file build with `make emscripten`  does not work.
Emscripten version is 1.37.26

After adding `-s ASSERTIONS=1` to `EMS_LINKER_FLAGS`, I get this message in web-console:

pre-main prep time: 3 ms
tic.js:1:7401
Successfully compiled asm.js code (total compilation time 596ms; stored in cache)
tic.js
Calling stub instead of signal()
tic.js:1:7401
Calling stub instead of sigaction()
tic.js:1:7401
tic.js:1:7316
 TIC-80 tiny computer 0.60.0 dev
tic.js:1:7316
 http://tic.computer (C) 2017
tic.js:1:7316
'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)
tic.js:1:7316
'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)
tic.js:1:7401
uncaught exception: abort("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)") at jsStackTrace@file:///tic.js:1:21907
stackTrace@file:///tic.js:1:22078
abort@file:///tic.js:37:22388
Module.writeArrayToMemory@file:///tic.js:1:28058
ASM_CONSTS<@file:///tic.js:1:31195
_emscripten_asm_const_i@file:///tic.js:1:39228
Uh@file:///tic.js:13:1
qS@file:///tic.js:25:1
dynCall@file:///tic.js:1:9497
ASM_CONSTS</<@file:///tic.js:1:30988
doCallback@file:///tic.js:1:504541
done@file:///tic.js:1:504679
done@file:///tic.js:1:487651
storeLocalEntry@file:///tic.js:1:486111
reconcile/</<@file:///tic.js:1:487877
loadRemoteEntry/req.onsuccess@file:///tic.js:1:486461

Have I merged something badly or JS build is broken?

**Comment by lolbot-iichan** [comment]
Looks like this is related to recent changes to emscripten: https://github.com/kripken/emscripten/issues/5940

**Comment by nesbox** [comment]
yes, reproduced on Emscripten 1.37.26
will fix, thanks

**Comment by nesbox** [comment]
fixed
