### ISSUE TITLE
Move persistent memory outside of the RAM

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#483]
People are complaining all the time that current 28 bytes PMEM is too small to store game data.

**Comment by nesbox** [comment]
so, I moved persistent memory outside of RAM and it's 1K (256 x 32bit signed integers)
`pmem(index = 0...255, [value]) -> value`
done here 9786c6d

**Comment by BuoYancYdabl** [comment]
That means i can now use pmem(150), for example?

**Comment by nesbox** [comment]
@BuoYancYdabl yes, will work
