### ISSUE TITLE
[Enhancement] Perlin/Simplex noise facilities

### ISSUE THREAD

**Issue by adiron** [nesbox/TIC-80#487]
Perlin/simplex noise is very useful in computer graphics for all kinds of things. I think it would be a good addition to TIC-80 if it had a convenient API so game makers wouldn't have to implement their own (in the worst case) or copy-paste boilerplate and take up precious program memory (in the best case)

**Comment by AnastasiaDunbar** [comment]
Made perlin noise [here](https://gist.github.com/AnastasiaDunbar/d1ec3f0f678a00ddc5947b1a3fdd10ea).

**Comment by adiron** [comment]
Definitely useful. :) Thanks

**Comment by nesbox** [comment]
so, I think the noise is beyond the scope of TIC API
added it to the snippets https://github.com/nesbox/TIC-80/wiki/Code-examples-and-snippets
closing
