### ISSUE TITLE
key/keyp: Right shift doesn't work

### ISSUE THREAD

**Issue by DarkHole1** [nesbox/TIC-80#488]
I tested new API for keyboard and find, that left shift works, but right - no
I tested it with this cart - [key_demo.tic.txt](https://github.com/nesbox/TIC-80/files/1593828/key_demo.tic.txt)

**Comment by nesbox** [comment]
yes, right shift/ctrl/alt should work
thanks

**Comment by nesbox** [comment]
fixed

**Comment by lolbot-iichan** [comment]
@nesbox I have integrated this fix and it does not seems to be fixed.
Can you please test it with [key.tic.txt](https://github.com/nesbox/TIC-80/files/1594841/key.tic.txt) ?

**Comment by lolbot-iichan** [comment]
Full rebuild helped.
The reason is that Makefile does not state that bin/studio.o depends on src/keycodes.c

**Comment by nesbox** [comment]
added `keycodes.c` dependency to _Makefile_ 75491ea
thanks
