### ISSUE TITLE
TIC-80 crashes when moving mouse over keys in sfx mode

### ISSUE THREAD

**Issue by Tinchetsu** [nesbox/TIC-80#493]
0.60.0 Pro dev
I made a windows build from master branch [d4131c0], and I found this crash.
If you mouse hover some piano keys in sfx mode, the app crashes.

![crash](https://user-images.githubusercontent.com/10901731/34468482-82512bcc-eee8-11e7-9b43-962dd8a726b0.gif)

**Comment by nesbox** [comment]
reproduced, thanks

**Comment by nesbox** [comment]
very strange crash, I fixed it but didn't get why it crashed on _Release x64_ only (Visual Studio 2015)
