### ISSUE TITLE
Game Menu -> Gamepad Config configures only 2 gamepads

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#494]
With new memory layout, there is 4 gamepads now.

1. Press ESC to go to Game Menu
2. Select Gamepad Config
Expected result: there is a way to configure all 4 gamepads.
Actual result: there is no way to configure gamepad №3 and №4, only first two are configurable.

**Comment by lolbot-iichan** [comment]
Test app: http://lolbot-iichan.github.io/TIC-80/bin/html/js_input.html

**Comment by nesbox** [comment]
WOW, great app, thanks 👍

**Comment by nesbox** [comment]
fixed here b3c3b40
![image](https://user-images.githubusercontent.com/1101448/34763700-219c20c2-f5fd-11e7-8d51-532ceeb7cfc3.png)
