### ISSUE TITLE
"keymap" command configures only 2 gamepads

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#496]
With new memory layout, there is 4 gamepads now.
1. Go to console
2. Type "keymap"
Expected result: there is a way to configure all 4 gamepads.
Actual result: there is no way to configure gamepad №3 and №4, only first two are configurable.

NOTE: this command is actually quite useless since there is another keymap configurator in Game Menu.

**Comment by nesbox** [comment]
yes, going to remove `keymap` as deprecated

**Comment by nesbox** [comment]
removed `keymap` command 53ccf8f
