### ISSUE TITLE
misprint: SDL_SCANCODE_RGUI mapped twice, SDL_SCANCODE_LGUI not mapped 

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#499]
See: https://github.com/nesbox/TIC-80/blob/173fe4167b1d128e6b2d8f764eb7a0f52f65fb1f/src/keycodes.c#L225-L232

P.S.: I don't know how to send pull requests now, as my branch has unwanted brainfuck features. Is there an easy way?

**Comment by nesbox** [comment]
fixed here 2a76fbd

**Comment by nesbox** [comment]
> P.S.: I don't know how to send pull requests now, as my branch has unwanted brainfuck features. Is there an easy way?

what if you create another one fork and send PR from it?
