### ISSUE TITLE
Exported html/js doesn't run in Firefox 57.0.3 (64-bit) on Ubuntu 16.04

### ISSUE THREAD

**Issue by kaplan2539** [nesbox/TIC-80#501]
Exported games runs fine in Chrome. However, in my default Firefox browser (57.0.3) nothing shows up and I get the following error in the Firefox log:

Successfully compiled asm.js code (total compilation time 1251ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))
jump.html
DOMError
message: "A mutation operation was attempted on a database that did not allow mutations."
name: "InvalidStateError"
__proto__: DOMErrorPrototype
constructor: ()
name: "DOMError"
prototype: DOMErrorPrototype
constructor: function ()
message: Getter
name: Getter
__proto__: Object { … }
Symbol(Symbol.hasInstance): undefined
__proto__: function ()
message: Getter
name: Getter
__proto__: Object { … }
jump.html:34:23666

**Comment by nesbox** [comment]
pls attach the _jump.html_

**Comment by kaplan2539** [comment]
It even does not work with the default code after a "new". It's attached.

[jump.html.txt](https://github.com/nesbox/TIC-80/files/1610867/jump.html.txt)

**Comment by nesbox** [comment]
Do you use _Private Mode_ to load the demo?
TIC tries to init internal FileSystem and your Firefox doesn't allow to do it...

**Comment by Luraktinus** [comment]
firefox is also a shitty browser, besides abusing users...

**Comment by Luraktinus** [comment]
i wish ubuntu would not bundle this Firefox spyware

**Comment by kaplan2539** [comment]
@nesbox: Yes, indeed I have private mode as a default. Do you think it would make sense detect private mode and inform the user?

**Comment by nesbox** [comment]
I think I should make it workable in _Private_ mode too

**Comment by kaplan2539** [comment]
That would be great. BTW I love TIC-80 - it's really awesome!!

**Comment by nesbox** [comment]
TIC .70 runs in the Firefox Private mode 
you could check it here https://tic.computer/crt/index.html
closing...
