### ISSUE TITLE
update to SDL 2.0.7

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#502]

**Comment by nesbox** [comment]
updated to SDL 2.0.7 4188b92

**Comment by nesbox** [comment]
moved external libs / pre-built libs to 3rd-party

**Comment by lolbot-iichan** [comment]
mingw build is broken, cannot find -lSDL2 which is actually missing at 3rd-party/pre-built/mingw

> gcc bin/studio.o bin/console.o bin/run.o bin/file_dialog.o bin/md5.o bin/gif.o bin/SDLnet.o bin/SDLnetTCP.o bin/SDLnetselect.o bin/fs.o bin/tools.o bin/start.o bin/sprite.o bin/map.o bin/sfx.o bin/music.o bin/history.o bin/world.o bin/config.o bin/code.o bin/net.o bin/dialog.o bin/menu.o bin/surf.o bin/html.o bin/res.o bin/libtic80.a -O3 -Wall -std=c99 -DTIC80_PRO -I../3rd-party/lua-5.3.1/src -I../3rd-party/zlib-1.2.8 -I../3rd-party/giflib-5.1.4/lib -I../3rd-party/SDL2-2.0.7/include -I../3rd-party/blip-buf -I../3rd-party/duktape-2.2.0/src -I../3rd-party/SDL2_net-2.0.1 -Iinclude -L../3rd-party/pre-built/mingw -lmingw32 -lSDL2main -lSDL2 -lz -lgif -llua -lcomdlg32 -lws2_32 -mwindows -o bin/tic80.exe
> c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -lSDL2main
> c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find -lSDL2
> collect2.exe: error: ld returned 1 exit status

**Comment by nesbox** [comment]
fixed SDL for MinGW https://github.com/nesbox/3rd-party/commit/c00322e805d2e9a34368ad69af0ef754fb6ce06a
