### ISSUE TITLE
Special functions should have common formatting

### ISSUE THREAD

**Issue by ambyra** [nesbox/TIC-80#503]
TIC and OVR are 3 characters, all caps. scanline() should be SCN or something to match. Also, all tic80 special functions should match this format or be otherwise standardized.

**Comment by ambyra** [comment]
Have both, mark scanline deprecated. It would be good to have official looking functions that are consistent.

**Comment by nesbox** [comment]
ok, I added `SCN` callback and now all the callbacks have 3 chars names: `TIC SCN OVR` e0cc606

old `scanline` also works, but not highlighted in the Code Editor
