### ISSUE TITLE
bin2txt/makefile uses old 3rd-party libs paths

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#504]
https://github.com/nesbox/TIC-80/blob/dca6c033007c055071753551018c854b65241829/tools/bin2txt/makefile#L1-L18

Should be something like this:

> OPT=-O3 -Wall -std=c99
> SRC=bin2txt.c
> INCLUDE=-I../../../3rd-party/zlib-1.2.8
> LIB=-lz
> 
> all: windows
> 
> windows: $(SRC)
> 	gcc $(OPT) $(SRC) $(INCLUDE) -L../../../3rd-party/pre-built/mingw $(LIB) -o bin2txt.exe
> 
> linux32: $(SRC)
> 	gcc $(OPT) $(SRC) $(INCLUDE) -L../../../3rd-party/pre-built/linux32 $(LIB) -o bin2txt
> 
> linux64: $(SRC)
> 	gcc $(OPT) $(SRC) $(INCLUDE) -L../../../3rd-party/pre-built/linux64 $(LIB) -o bin2txt
> 
> macosx: $(SRC)
> 	gcc $(OPT) $(SRC) $(INCLUDE) -L../../../3rd-party/pre-built/macos $(LIB) -o bin2txt

**Comment by nesbox** [comment]
fixed here 8b02b29
