### ISSUE TITLE
Keywords get highlighted incorrectly

### ISSUE THREAD

**Issue by LegitimatlyMe** [nesbox/TIC-80#505]
Keywords get highlighted incorrectly when a variable name includes it.
math.min gets affected the most due to it having "in" at the end.

The bug only affects names that meet these conditions: 
- A keyword is included in the name
- The keyword has a space after

```lua
local min = math.min
```
would be highlighted as 
![tic80_2018-01-11_19-42-36](https://user-images.githubusercontent.com/16442486/34858932-1150bdac-f708-11e7-8a12-095914412f87.png)

**Comment by LegitimatlyMe** [comment]
Actually, upon closer inspection, the keyword doesn't require a space after.
The strange thing is that it only seems to highlight `in` at this example in the screenshot above and nowhere else.

**Comment by nesbox** [comment]
will fix it soon, thanks

**Comment by nesbox** [comment]
fixed here 0f7d0f9

**Comment by nesbox** [comment]
released hotfix https://github.com/nesbox/TIC-80/releases/tag/v0.60.3
