### ISSUE TITLE
Linux Sound Lag 

### ISSUE THREAD

**Issue by MrDiamond123** [nesbox/TIC-80#506]
On the "Game Menu", surf and sound in games, it has a delay before playing the sound.
(Both fullscreen and windowed mode)
I built the pro version myself (if that helps) 

Doesn't affect using the Web Version on Chrome

**Comment by nesbox** [comment]
does it reproduce on previous versions?

**Comment by MrDiamond123** [comment]
let me check...

(Version used btw is 0.60.3 Pro Built like 10 minutes ago)

**Comment by MrDiamond123** [comment]
on non pro version the sound has less of a delay (even less on fullscreen?)

**Comment by nesbox** [comment]
hmm, interesting, you tested .50 and it still has to delay
what OS do you use, Linux?

**Comment by MrDiamond123** [comment]
I didn't test .50 I tested the Non-pro version of .60

**Comment by nesbox** [comment]
pls test on .50, it's important to understand the problem
what OS?

**Comment by MrDiamond123** [comment]
I am trying to install it now (old computer, slow speed :( )

**Comment by nesbox** [comment]
ah, I see, you use Linux :)

**Comment by MrDiamond123** [comment]
I would try to test it on .50 but the archives for both the 64bit version and the source code don't like me (Don't want to extract) :(

**Comment by MrDiamond123** [comment]
Doesn't reproduce in V0.50.1 Pro :)
BTW On each release GitHub makes a hidden branch :)

**Comment by nesbox** [comment]
I made some fixes
pls test on this branch https://github.com/nesbox/TIC-80/commits/%23506

**Comment by MrDiamond123** [comment]
still a delay (about 1.5 seconds)

**Comment by MrDiamond123** [comment]
now music is a little delayed

**Comment by nesbox** [comment]
made another one fix
pls test again

**Comment by MrDiamond123** [comment]
about the same delay

**Comment by nesbox** [comment]
ok, this one 8b07814 pls

**Comment by MrDiamond123** [comment]
its the same >:(

**Comment by nesbox** [comment]
do you see SYNC label in the top right corner?

**Comment by MrDiamond123** [comment]
nope

**Comment by nesbox** [comment]
pls this one 1ea0899
do you have 60Hz or 100Hz monitor?

**Comment by MrDiamond123** [comment]
its running at 60 hz

**Comment by MrDiamond123** [comment]
Want me to test it at 50Hz?

**Comment by nesbox** [comment]
no, just test 1ea0899 fix :)

**Comment by MrDiamond123** [comment]
:(

**Comment by MrDiamond123** [comment]
Let me try building it as the normal version (not pro)

**Comment by nesbox** [comment]
what SDL2 version installed on your system?
and could you try to build using the command `make linux64-lto-pro` (or `make linux32-lto-pro` depending on your system)?

**Comment by MrDiamond123** [comment]
i don't have sdl2??

**Comment by MrDiamond123** [comment]
nvm 2.0.4

**Comment by nesbox** [comment]
it may be a reason, try to build with LTO support as I provided

**Comment by MrDiamond123** [comment]
i did and the delay lessen a tiny bit

**Comment by nesbox** [comment]
I don't see other reasons :(
Could you try to find a revision when it started to reproduce (from .50 to .60)?
if you have some free time pls

**Comment by MrDiamond123** [comment]
Okay

**Comment by MrDiamond123** [comment]
checking commit 82d23a

**Comment by nesbox** [comment]
any news?

**Comment by nesbox** [comment]
???
so, nobody reported about the issue, I close it temporary then

**Comment by BozoDel** [comment]
I tried out TIC-80 for the first time today (64-bit Linux), and did nothing but add and load and run cartridges. The sound lag showed up after a while. It goes away if you just turn TIC-80 off and on again. I'll see if it happens again, if it shows a pattern. Then I can test an older version. But I can't promise to do it soon, sorry...

**Comment by BozoDel** [comment]
Ok, so today I messed around with the TIC for longer than I did yesterday, and I had no sound lag at all. Maybe it's like an actual computer in that sense. Sometimes it gets weird, but you just have to reboot it.

**Comment by frenetic** [comment]
@BozoDel which carts did you try?
You downloaded them manually or you used `surf`?

**Comment by BozoDel** [comment]
The first time, I think I tried all demo carts, plus these:
https://tic.computer/play?cart=351
https://tic.computer/play?cart=193
https://tic.computer/play?cart=188
https://tic.computer/play?cart=315

Now today, I toyed with almost all of them for a while, then played quite a bit of 8 bit panda.

I downloaded all of them manually (I hadn't figured out surf yet).

**Comment by MrDiamond123** [comment]
sorry haven't had time to report on the issue

**Comment by Gaffen** [comment]
Just wanted to add my report here; encountering the issue on MacOS devices. Audio is often severely out of sync for the native TIC80 app. Web player is totally fine, however.

**Comment by different55** [comment]
Sound wasn't working at all for me on Linux when cloning directly from git, compiled 0.60.3 instead and sound is working now but with some pretty extreme delay, timed it at 72 seconds after just a few minutes with TIC-80 open.

The startup sound plays immediately when TIC opens, and just a few seconds after that there's a few seconds delay.
