### ISSUE TITLE
SYNC label is annoying

### ISSUE THREAD

**Issue by betofloresbaca** [nesbox/TIC-80#507]
I think this functionality must be optional and disabled by default because it only is useful when testing the game. It can have a entry on the config cartridge for toggle the message and should be activate by the command line like:
`tic80 -synclabel`
For the tic games it should be activated programmaticaly like:
`synclabel(true)`

PD. The names for the function and command line parameter are only illustrative. You can select a better ones or implement another way to allow toggle of this property.

**Comment by betofloresbaca** [comment]
Don`t misunderstand me. The SYNC label is a cool thing but this add noise when using the editors or playing a game.

**Comment by nesbox** [comment]
as a variant, you can change `MISSED_FRAMES` in the _config_
change it to 2 or more and you will see SYNC label only on the second skipped frame

**Comment by betofloresbaca** [comment]
Ok, that sounds good
