### ISSUE TITLE
Include mouse pointer when exporting GIFs

### ISSUE THREAD

**Issue by glorphindale** [nesbox/TIC-80#509]
TIC-80 0.50.1

When creating a GIF with mouse-driven cart (`--input: mouse`) the resulting animation does not include the mouse pointer location.
It makes the result slightly confusing when game does not itself indicate the current mouse position (drawing a custom cursor or something like that).

**Comment by frenetic** [comment]
This happened: https://github.com/nesbox/TIC-80/issues/522
Could you please test it again with the latest released version?

**Comment by glorphindale** [comment]
0.70.6 - pointer is not included.

**Comment by nesbox** [comment]
The mouse cursor renders on the editors stage b2a72d466740e61a6b96424f04dc1faa5a5bf8a4 and is visible on gif's.
![video4](https://user-images.githubusercontent.com/1101448/131245384-23b7af43-3062-434c-8149-03eeb1b9d879.gif)
