### ISSUE TITLE
Use WebAssembly instead ASM.JS

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#515]
seems all the popular browsers support WebAssemly https://caniuse.com/#feat=wasm

**Comment by nesbox** [comment]
added `wasm` target to _Makefile_ 6cc4560 and surprisingly, it compiled without any problems

here is version to test [wasm.zip](https://github.com/nesbox/TIC-80/files/1652119/wasm.zip) (works via webserver only)

**Comment by AnastasiaDunbar** [comment]
Yay!

**Comment by nesbox** [comment]
Enabled WASM by default with issue #777

**Comment by nesbox** [comment]
Done
