### ISSUE TITLE
Code from other banks gets added to bank 0, if using external editor.

### ISSUE THREAD

**Issue by Tinchetsu** [nesbox/TIC-80#516]
Tested in windows, 0.60.3 Pro from stable branch

When you add code to another bank in TIC80 builtin editor, and then edit the lua file in an external editor, code from other banks gets added to bank 0, in TIC80 code editor.

![banks](https://user-images.githubusercontent.com/10901731/35547936-e7070ac2-055a-11e8-8dd3-33a6ada5d272.gif)

**Comment by nesbox** [comment]
fixed here 4a60393
