### ISSUE TITLE
CLI save injected code

### ISSUE THREAD

**Issue by Gi972** [nesbox/TIC-80#517]
Hello @nesbox ,

The temp save before run works?
I see you talk about the #385  and #250 but when I try inject code the save not working 
So I don't know if you implement

if not
It possible add to the cli a argument -save for save a injected code to a tic file?
No need launch the card but just save to .tic format.

if you can save and launch also,  I take this too :-)

Tell me if is possible thanks.

**Comment by nesbox** [comment]
ok, added `-save` param here 8d92516
