### ISSUE TITLE
Lose sound when switching between Tic80 editor and different desktop app

### ISSUE THREAD

**Issue by oliverrrrrr** [nesbox/TIC-80#518]
When switching to a browser window or another desktop app then back to the Tic80 editor, I lose all  sound and have to quit and restart the editor. 
 
I am on 0.60.03 Pro, macOS High Sierra.

**Comment by nesbox** [comment]
pls check this version (with disabled VSYNC) and let me know
[tic80_novsync.dmg.zip](https://github.com/nesbox/TIC-80/files/1699680/tic80_novsync.dmg.zip)
thanks

**Comment by oliverrrrrr** [comment]
HI Vadim, yes, the version with VSYNC disabled works perfectly. Thanks for all your amazing work with Tic80, I love it.

**Comment by nesbox** [comment]
fixed here 6721fb6
thanks
