### ISSUE TITLE
How about a possible Libretro core?

### ISSUE THREAD

**Issue by hyarsan** [nesbox/TIC-80#519]
This project looks great, and I feel like it would be perfect for Libretro.

Links that might help:
http://libretro.com/
https://www.libretro.com/index.php/develop/
https://github.com/libretro/libretro-common/blob/master/include/libretro.h
http://retroarch.com/
https://discord.gg/3YbdCxG

**Comment by rogersachan** [comment]
Seeing as there's a CHIP-8 core for retroarch this seems reasonable. Having a libretro core would allow tic-80 games work for platforms that haven't been implemented like the Nintendo 3DS/Switch or Xbox 360.
