### ISSUE TITLE
new GIF encoder

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#522]
https://github.com/martincohen/Punity/blob/master/lib/gifw.h

**Comment by trelemar** [comment]
So this may produce smaller file sizes?

**Comment by nesbox** [comment]
I hope :)

**Comment by StinkerB06** [comment]
The TIC-80 crashes if you record a very long GIF.

**Comment by aliceisjustplaying** [comment]
Fixed per https://github.com/nesbox/TIC-80/issues/2218#issuecomment-1680819771.
