### ISSUE TITLE
Draw sprite with color index mapping?

### ISSUE THREAD

**Issue by Terumoc** [nesbox/TIC-80#523]
This is a suggestion for an enhancement that would be nice. I think it's a feature in another "tiny computer" project though I can't remember which.

I would like to be able to draw a sprite where one color in the sprite is replaced with another in the pallete. For example, you could have a sprite that uses color 1 in the spritemap, but specify a modifier to "map" color 1->color 2, and draw that same sprite as color 2 instead based on the same sprite data. This is a really good way to reuse a limited set of sprites.

There are of course ways to modify the palette mid-execution through scanline/SCN or poking new color values, but doing so affects many sprites and is more complex than simply substituting one color index for another.

I know SPR has a lot of arguments already, so perhaps something like a "SPRMAP(x,y)" command that allows you to specify mapping color index X in sprite data to be instead drawn as color index Y. This mapping could remain in effect until it is changed or "SPRMAP()" is called with no arguments, disabling all color mapping--just for one idea of how it could work.

**Comment by nesbox** [comment]
you can do this by poking `PALETTE MAP - 0x03FF0` in VRAM
``` lua
-- swap c0 and c1 colors, call pal() to reset
function pal(c0,c1)
	if(c0==nil and c1==nil)then for i=0,15 do poke4(0x3FF0*2+i,i)end
	else poke4(0x3FF0*2+c0,c1)end
end
```
https://github.com/nesbox/TIC-80/wiki/code-examples-and-snippets#palette-swapping

**Comment by Terumoc** [comment]
I completely missed that; I see how you can accomplish this now. Thanks!

**Comment by c1oudsky** [comment]
How would I go if I want to draw my sprite with another color from my palette, not changing the palette itself? Similar to how the icons in Tic's UI change their color when hovered on/chosen
Quick search over the net didn't help me >^< I imagine it'd either be a parameter for spr(), or a command that refills specified palette color on a specified part of screen to another

**Comment by blubbers122** [comment]
> How would I go if I want to draw my sprite with another color from my palette, not changing the palette itself? Similar to how the icons in Tic's UI change their color when hovered on/chosen Quick search over the net didn't help me >^< I imagine it'd either be a parameter for spr(), or a command that refills specified palette color on a specified part of screen by another

I don't see any parameter for `spr` to do what you describe.

Here's an example of an approach I took to 'recolor' sprites in code. Hopefully this helps you:
```javascript
pal(2, 4); // temporarily replace red with yellow in pallete
spr(1, x, y); // draw sprite 1.. but all red pixels in that sprite are yellow now
pal(); // reset pallete to default
```

```javascript
// swap c1 and c2 colors, call pal() to reset
function pal(c1,c2) {
	if(!c1 || !c2) {
		for (let i=0;i<15; i++) {
			poke4(0x3FF0*2+i,i)
		} 
	} 
	else {
		poke4(0x3FF0*2+c1,c2)}
}
```

**Comment by joshgoebel** [comment]
Correct you do this with `pal`, though one could obviously write a nice wrapper very easily if one desired a different "one liner" style API...
