### ISSUE TITLE
Data comments inserted into code for -code-watch

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#524]
When I run the cartridge with -code-watch the data comments are displayed in code area and when I store the cartridge the data comments in a file are duplicated.

This doesn't happen when I load cartridge through "load" command.

**Comment by jahodfra** [comment]
The same happens for -code argument.

**Comment by nesbox** [comment]
I got the problem, `-code` and `-code-watch` are designed to use in _non-Pro_ version to inject code (you provided in a text file) to the cartridge, but in your case, you are trying to inject text cartridge (Pro) as code part, and of course, TIC loads whole text to the Code Editor.
Just use `tic80 cart.lua` without `-code/-code-watch` arguments, TIC will load text cart as it should and will work with _live reload_ in both directions.
Not a bug

**Comment by jahodfra** [comment]
I haven't known that live reload works when the cartridge is just passed as parameter. I will use that.
