### ISSUE TITLE
Warning on startup "parameter or file not processed: ."

### ISSUE THREAD

**Issue by DePingus** [nesbox/TIC-80#527]
Hi. On Windows 10 64-bit and Windows 7 32-bit when I start TIC-80 0.60.3 with the " . " command line argument to use the current directory as storage ( tic80.exe . ) I get a Warning box that says "parameter or file not processed: . " After I press OK, TIC-80 seems to work normally, even using the current directory as storage like I intended.

**Comment by nesbox** [comment]
fixed a481dac

**Comment by DePingus** [comment]
You the man!
