### ISSUE TITLE
Sync api - Define constants for mask.

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#531]
With MASK prefix to avoid conflicts. Currently I have them defined in code, but it would be nice if they'd be part of standard api:

```
MASK_TILES   = 1<<0 -- 1
MASK_SPRITES = 1<<1 -- 2
MASK_MAP     = 1<<2 -- 4
MASK_SFX     = 1<<3 -- 8
MASK_MUSIC   = 1<<4 -- 16
MASK_PALETTE = 1<<5 -- 32
```

So we can avoid using magic numbers which is a bad coding practice and shouldn't be used unless you need to optimize for space.

**Comment by nesbox** [comment]
yes and no, on one hand, you can save code a bit, on the other hand, it will overload the _API_

**Comment by darkhog** [comment]
I don't think some constants would overload the API, you'd still basically tell Lua to use numbers, just it would be more readable, so instead `sync(0,1+2+32,false)` you'd use `sync(0,MASK_TILES+MASK_SPRITES+MASK_PALETTE,false)`. It'd be more readable in development and would only need to be changed when optimizing for space (after hitting 64kb of code) to less readable, magic number version.

**Comment by nesbox** [comment]
you can define your own constants in the code for masks
