### ISSUE TITLE
The errors aren't descriptive when using banks

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#537]
I know the error wasn't in the TIC function, let alone 141 line and as it turned out, the error was in another bank. Perhaps the error format should include the bank erroneous line was detected in?

**Comment by nesbox** [comment]
yes, the error should show the bank

**Comment by PerdeT** [comment]
Is this coming to next release? This bug keeps me from using banks atm (and my biggest project would totally benefit from more code storage)

**Comment by nesbox** [comment]
.80 supports only one code bank
