### ISSUE TITLE
Constantly getting "cart not created" message

### ISSUE THREAD

**Issue by twocredits** [nesbox/TIC-80#538]
I just built from the latest source (https://github.com/nesbox/TIC-80/commit/ce83d422be79b2bea2870d2b6719955c7162595e) and, while the issue in question doesn't seem to have any effect on functionality, I figured I should report it. When building the latest source on Windows 10 in a new install of MSVC2015 Community, TIC-80 is telling me "cart not created" every time I enter the "new" command. It asks if I'm sure due to unsaved changes and I've tested to see if it erases simple changes, which it does, but it insists that a new cart is not created. This is happening in all builds (Debug, Debug Pro, Release, Release Pro). This does not happen in the latest official Windows release, 0.60.3.

**Comment by nesbox** [comment]
yes, reproduced, thanks

**Comment by nesbox** [comment]
fixed here 2396cef
thanks
