### ISSUE TITLE
Ask user whether to save changes, not whether to load cart

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#540]
So you have a mechanism set to detect changes to a cart. Great. But why do you ask if the user want to load cart and lose changes, instead to whether or not user want to save changes before loading a new cart, which is more intuitive.

**Comment by jahodfra** [comment]
It is not possible to write changes into the same cartridge as that would lose the data there.
Maybe it makes sense to store data to temporary file on disk so user can have chance to revert data. But that can generate quite a lot of files on the disk. So maybe just to store the last one?

**Comment by darkhog** [comment]
![obraz](https://user-images.githubusercontent.com/1531474/36610962-db23d096-18c9-11e8-9337-e0abf0e45126.png)
That's how it should be done.
![obraz](https://user-images.githubusercontent.com/1531474/36611028-0966111c-18ca-11e8-8537-fd153abc1009.png)
Not like this.

**Comment by jahodfra** [comment]
So where the changes would be written? To the same file which was already changed on disk by e.g. editor?

**Comment by darkhog** [comment]
And where does Word/Excel/Windows Notepad write changes? I don&#39;t see any issues at all.  
                
              
               
                 
                  Dnia 23 lutego 2018 19:27 František Jahoda &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   So where the changes would be written? To the same file which was already changed on disk by e.g. editor?

**Comment by jahodfra** [comment]
@darkhog 
So if the cart is changed on the disk the message is:
Cart has changed! Do you want to reload it? >Yes No

On exiting:
You have unsaved changes. Do you really want to exit? >Yes No

Sorry I was bit confused by mechanism which detects changes in a cart. I agree that on exit the default should be to save. And it should be an option to cancel the operation.

**Comment by jahodfra** [comment]
Also I suppose the function to write that doesn't have to be 4 times in a code.

**Comment by nesbox** [comment]
Don't see a problem here, it's a matter of habit I think.
