### ISSUE TITLE
Add mousep()

### ISSUE THREAD

**Issue by Tau5** [nesbox/TIC-80#542]
I wish a mousep() function like keyp() and btnp()

**Comment by trelemar** [comment]
I think nesbox is trying to keep the api as clean as possible. There are a few simple ways to do this yourself though. `mouse()` also returns x and y coords so `mousep` would have to return just the click?

```lua
function TIC(){
mousePressed=mouse()[2]
lastPressed=mousePressed
}

function mousep(){
 return mousePressed&&mousePressed!=lastPressed
}
```

**Comment by nesbox** [comment]
wontfix, sorry
