### ISSUE TITLE
Bug: Crash when stop recording with long gif length

### ISSUE THREAD

**Issue by Tau5** [nesbox/TIC-80#543]
Steps to reproduce:
1. Increase gif length in TIC config to 120 seconds
2. Record a gif 
3. Stop it (Its not necessary that the gif is 2min. long)
4. Enjoy.

**Comment by frenetic** [comment]
Is this still happening on the latest version?
@Tau5 Could you please try to reproduce it?

**Comment by nesbox** [comment]
Can't reproduce, maybe will be fixed with #522
