### ISSUE TITLE
[osx] CPU usage jumps 10x when idling in the background

### ISSUE THREAD

**Issue by bferguson3** [nesbox/TIC-80#544]
*Environment*:
MacBook Air, iOS High Sierra
Tic-80 0.60.3 Pro

*Reproduction Steps*:
1. Start Tic-80.
2. Cmd-tab to any other process, browse the web, etc, leaving Tic-80 to idle for several minutes.
3. Open system resources monitor and observe Tic-80 is using ~70% CPU
4. Regain focus to Tic-80
5. Observe CPU drops to normal levels (for me ~7%)

*Notes*:
1. Fully reproducible.
2. No interaction with the app is required in any way to reproduce this issue.

**Comment by hseiken** [comment]
It's ceiling cat, stealing your CPU cycles when you is not lookingz.

**Comment by bferguson3** [comment]
oh nooooos!

After messing with it some more I found it's not reliable, but still pretty reproducible. I'll open the editor, do a 'ls' command, really small stuff, then while reading docs my laptop fan will kick up hard. 

Not sure what exactly sets it off, though.

**Comment by nesbox** [comment]
to fix it, pls type `config`, go to the _Code Editor_, change `USE_VSYNC=false`, save config and restart TIC
it already fixed in .70
thanks
