### ISSUE TITLE
Continuous integration system

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#545]
I think it is worthy to use CI system to ensure that the TIC can be build without warnings on all platforms.
E.g. even before merging in the CL.

**Comment by darkhog** [comment]
I think so as well.

Related: This would also be a nice opportunity to introduce nightly builds so people who are willing to can test bleeding edge features without having to build TIC themselves.

**Comment by nesbox** [comment]
great, will try to add https://travis-ci.org service

**Comment by nesbox** [comment]
it works https://travis-ci.org/nesbox/TIC-80

![image](https://user-images.githubusercontent.com/1101448/37518825-e4fcdf18-2927-11e8-972d-dd9eb92bddec.png)

**Comment by jahodfra** [comment]
Nice! Does it make sense to add other targets?

**Comment by nesbox** [comment]
@jahodfra I think yes, Travis also supported MacOS, not sure about Windows
