### ISSUE TITLE
Invalid access to memory

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#546]
Valgrind output on head.
[results.txt](https://github.com/nesbox/TIC-80/files/1754399/results.txt)

==9839== Invalid write of size 8
==9839==    at 0x11C1CCDF: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x11C1E3EA: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x11C1C2A6: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x11C1C522: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x11966DCA: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x11968D05: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x1196C967: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x458984: GL_UpdateTexture.lto_priv.1437 (SDL_render_gl.c:936)
==9839==    by 0x4614E2: SDL_UnlockTexture_REAL (SDL_render.c:1148)
==9839==    by 0x4BE4CD: blitCursor (system.c:727)
==9839==    by 0x4076D8: renderCursor (system.c:801)
==9839==    by 0x4076D8: tick (system.c:826)
==9839==    by 0x4076D8: start (system.c:1051)
==9839==    by 0x4076D8: main (system.c:1153)
==9839==  Address 0x7f37eaf3b000 is not stack'd, malloc'd or (recently) free'd

==9839== Invalid write of size 4
==9839==    at 0x11C0A746: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9839==    by 0x103604CB: ??? (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==9839==    by 0x4F9CC2: X11_GL_SwapWindow (SDL_x11opengl.c:925)
==9839==    by 0x407627: tick (system.c:829)
==9839==    by 0x407627: start (system.c:1051)
==9839==    by 0x407627: main (system.c:1153)
==9839==  Address 0x7f37eaff5f94 is not stack'd, malloc'd or (recently) free'd

**Comment by nesbox** [comment]
trying to understand where is the problem, inside SDL or TIC?

**Comment by jahodfra** [comment]
I think this can e.g. mean, that you don't set default values for variables or anything else, just access to bad memory. Of course this can happen even in libs.

**Comment by jahodfra** [comment]
==9872== Invalid write of size 4
==9872==    at 0x11C192FD: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9872==    by 0x11BADC6F: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_dri.so)
==9872==    by 0x1035FB82: ??? (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==9872==    by 0x10337A53: ??? (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==9872==    by 0x10333C2A: ??? (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==9872==    by 0x10333D8D: glXChooseVisual (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==9872==    by 0x4FD1FC: X11_GL_GetVisual (SDL_x11opengl.c:606)
==9872==    by 0x4FD1FC: X11_GL_InitExtensions (SDL_x11opengl.c:342)
==9872==    by 0x4FD1FC: X11_GL_LoadLibrary.part.4 (SDL_x11opengl.c:235)
==9872==    by 0x48683A: SDL_GL_LoadLibrary_REAL (SDL_video.c:2792)
==9872==    by 0x48683A: SDL_CreateWindow_REAL (SDL_video.c:1389)
==9872==    by 0x487B0C: ShouldUseTextureFramebuffer (SDL_video.c:220)
==9872==    by 0x487B0C: SDL_VideoInit_REAL (SDL_video.c:544)
==9872==    by 0x4B49A6: SDL_InitSubSystem_REAL (SDL.c:170)
==9872==    by 0x40654B: start (system.c:1004)
==9872==    by 0x40654B: main (system.c:1153)
==9872==  Address 0x7f67cfb89000 is not stack'd, malloc'd or (recently) free'd

I think SDL2 is the probable culprit.

**Comment by tksuoran** [comment]
This is not SDL specific.
"valgrind glxgears" gives plenty of invalid writes too.

**Comment by Rickodesea** [comment]
Apparently,  this is a known issue.  Some claim that this is normal with the underlining graphics drivers and to just ignore the errors.
