### ISSUE TITLE
failed to run on linux

### ISSUE THREAD

**Issue by theFox6** [nesbox/TIC-80#547]
I tried to download and run the TIC-80 on my linux following your instructions, but I get the error:
`./tic80: error while loading shared libraries: .so: cannot open shared object file: No such file or directory`

**Comment by nesbox** [comment]
fixed in #521
try this build [tic80_64bit_0.63.3.tar.gz](https://github.com/nesbox/TIC-80/files/1698898/tic80_64bit_0.63.3.tar.gz)
