### ISSUE TITLE
wiki command

### ISSUE THREAD

**Issue by darkhog** [nesbox/TIC-80#549]
After typing "wiki" in the command shell, TIC-80 wiki would open in a new tab of the default browser. I think this would be useful, especially if you have browser closed and don't want to muck around with opening it and then clicking through to get to it.

**Comment by nesbox** [comment]
I think it should be improved in future, maybe with `api` param...
done here cb4076f

**Comment by darkhog** [comment]
No, I meant directly from the app, similar to the folder command.  
                
              
               
                 
                  Dnia 7 marca 2018 23:33 StinkerB06 &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   Well, there is a link to the GitHub Wiki already just in tic.computer/learn.
