### ISSUE TITLE
Disable CRT by command line

### ISSUE THREAD

**Issue by mathpeseg** [nesbox/TIC-80#552]
CRT is enable by default, and i think that in my pi3 it is getting slow because of that. i can't manage to disable the CRT by myself, so i think  it would be great to be able to disable it by command line.

**Comment by nesbox** [comment]
I can do it disabled by default
If you want to disable it, go to `config`, change `CRT_MONITOR=false` and save

**Comment by nesbox** [comment]
6166b08
- made `CRT_MONITOR=false` by default
- added `-crt-monitor` command line parameter to force start with CRT shader
