### ISSUE TITLE
Music Editor work wrong in android

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#554]
I don't understand, what key i should press, for do anything in music redactor? Nothing happend. Can you add piano key on android in free version of app, please, or fix this issue.

**Comment by nesbox** [comment]
use `ZXCVBNM` `SDGHJ` to enter notes, but, unfortunately, Android screen keyboard doesn't send _KeyDown_ events, it will work only with physical keyboard
will add screen piano in .70

**Comment by kikeroga3** [comment]
I installed Android version TIC-80 on 005SH.
However, the physical key of 005SH also did not work.

005SH
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQx7VBm_ayZTkVEJmRI152aaSBB0SSiCurZqZF1ih9dk90trcw

P.S.
I am glad that TIC-80 can install even to old Android version.
It is moving at a sufficient speed there. (-:

**Comment by nesbox** [comment]
@kikeroga3 
pls test your keyboard on this build [tic80_keyboard_fix.zip](https://github.com/nesbox/TIC-80/files/1801796/tic80_keyboard_fix.zip)
(this build has issues with screen scaling)

**Comment by kikeroga3** [comment]
tic80_keyboard_fix.apk could not be installed on 005SH (Android 2.3.4).
005SH can not be updated to Android 2.3.5 or higher.

**Comment by BuoYancYdabl** [comment]
Forget to close it
