### ISSUE TITLE
[Feature Request] Flash system sprite RAM (config) from cart or membank

### ISSUE THREAD

**Issue by bferguson3** [nesbox/TIC-80#556]
Hi,

I've been looking into ability to add non-English support, or custom fonts to fantasy consoles like Pico-8 and Tic-80 with little success

Font() is not extremely useful as it takes up a lot of sprite space (almost making memory bank switching for printing text a necessity)  and only supports 8x8 tiles.
Spr() as well, without being able to designate a x,y coordinate on the sprite sheet like pico-8, makes it very difficult to utilize for anything other than 8x8 square fonts (not legible for a lot of languages).

Tic-80 seems like the best bet, though, and I have an idea that would fit within the "aesthetic":

What if one of the membanks of a TIC-80 cart resembled the config.tic file, and could be temporarily "flashed" to RAM while that cart is running?

This would allow custom 'system' fonts that retain when carts are shared, as well as custom arrow/button graphics and the like. 

Let me know what you think.
thanks

**Comment by lolbot-iichan** [comment]
Have you seen this cart https://tic.computer/play?cart=263 ?

**Comment by nesbox** [comment]
@bferguson3 I thought about it and have an idea to distribute the exported game with own _config.tic_, but it won't work if you distribute your game as .tic cart...
Will keep your solution in my mind, thanks

**Comment by nesbox** [comment]
Now you can save font data in 1 bit per pixel mode and save a lot of sprite space.
Please, check `bpp.tic` example.
