### ISSUE TITLE
Crash when copying and pasting in several editors (sprite, map editor)

### ISSUE THREAD

**Issue by dagondev** [nesbox/TIC-80#558]
Selecting something and copying and pasting always crashes the TIC-80. Builded from code that is about 3 days ago (need get home to check from what commit I builded exe).

**Comment by dagondev** [comment]
On commit 81fbd92 still crashes.

**Comment by nesbox** [comment]
hmm, can't reproduce
any additional info I should know?

**Comment by dagondev** [comment]
Weird. Let's see, windows build. I can reproduce bug on empty cart I got when starting TIC. Go to sprite editor, copy tile with something on it, then try to paste it on other tile. Can I provide some file or log or whatever?

**Comment by nesbox** [comment]
do you use MinGW or Visual Studio?

**Comment by dagondev** [comment]
Visual Studio

**Comment by nesbox** [comment]
@dagondev could you please look at where is it crashes in the debugger?

**Comment by dagondev** [comment]
Sorry I missed the most important thing. Crash occures in x64, on x86 pasting works fine.

**Comment by nesbox** [comment]
reproduced on x64

**Comment by nesbox** [comment]
fixed here 8484a86
thanks
