### ISSUE TITLE
esc key disables fullscreen instead of returning to console

### ISSUE THREAD

**Issue by DaAndroid614** [nesbox/TIC-80#562]
(HTML5)
i don't even know if this could be done, but i'd find it more convenient if esc was used to change menus while fullscreen and only F11 would exit it. I could've sworn i saw something else do this.

**Comment by nesbox** [comment]
I think it's impossible to intercept ESC button pressing in browsers to not to exit fullscreen mode.
I'm trying to do it here https://github.com/nesbox/TIC-80/blob/dbcd4d74ef2d64768758854647292912e3941339/build/html/prejs.js#L3 without success
