### ISSUE TITLE
Cannot use function scanline() to poke or poke4 sound registers.

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#563]
Doing this will treat poke write value to be at maximum. Always.

**Comment by nesbox** [comment]
yes, in scanline() you can change palette/screen offset only
by design

**Comment by StinkerB06** [comment]
Then how will I play raw PCM through volume manipulation?

**Comment by StinkerB06** [comment]
Seriously, NesBox, old computers could use CPU cycles to manipulate the sound registers to do crazy things, like playing a PCM sample. The only problem is that it took a large amount of CPU time, not enough for running a game program or something where PCM is a consistent need.

**Comment by frenetic** [comment]
But `scanline` does not represent CPU time.
The `TIC` function does.
What you want to do cant be done inside `TIC`?
