### ISSUE TITLE
Allow using io library

### ISSUE THREAD

**Issue by Avevad** [nesbox/TIC-80#564]
Unfortunately, You will get "attempt to index a nil value" error when calling io lib functions

**Comment by nesbox** [comment]
IO library is disabled in TIC by design

**Comment by Avevad** [comment]
What is the "design" you mean? Old computers couldn't write/read files?

**Comment by nesbox** [comment]
yes, old computers could
but it's limitation, TIC can load/save data to cartridge only (or _persistent memory_)
sorry

**Comment by Avevad** [comment]
Thanks for answer. (~~I still hope io library will be added in future~~)

**Comment by Terumoc** [comment]
Why even use TIC or any "fantasy computer" if you're going to just use regular files? The entire design aesthetic is "old-school games with all assets on a standalone 'cartridge' with limitations of its system". (at least that's my gist of it)

If that's not what you're looking for just pick up Love2D (https://love2d.org/) or something, use retro-style graphics limited to your own chosen palette and have fun. Love2D is Lua-based and my choice when I'm looking for something beyond the small computer design.
