### ISSUE TITLE
Bug on launch

### ISSUE THREAD

**Issue by Bigaston** [nesbox/TIC-80#566]
When I launch TIC-80, it go to the surf screen and wouldn't go back. I've uninstal it, reinstal it, but nothing. I've try to exit it but it going to it.

Gif : https://i.imgur.com/TqORX7H.gifv

**Comment by nesbox** [comment]
Usually, it happens when you have connected device and TIC recognizes it like a gamepad. Do you have anything connected?

**Comment by MrBigaston** [comment]
I've no gamepad connected :/

**Comment by nesbox** [comment]
maybe an unusual mouse or touchpad?

**Comment by MrBigaston** [comment]
I'm on a desktop computer and a Razer Ouroboros

**Comment by nesbox** [comment]
SDL2 lib detects your Razer Ouroboros as a gamepad for unknown reason...

**Comment by MrBigaston** [comment]
Oh... Well. Okay. What I can do to fix that?

**Comment by abcq2** [comment]
try launching TIC-80 with the Razer Ouroboros unplugged, then plug it back in once the program is launched.

Unfortunately the only other solutions would require modifying or replacing either SDL2 or the Ouroboros drivers

**Comment by frenetic** [comment]
@Bigaston do you know if this bug still persists? Could you please test it on the latest released version?

**Comment by Bigaston** [comment]
I've correct the bug, it's came from my computer. I've a custom gamepad (I don't know why) who is installed on my PC and made all bug
