### ISSUE TITLE
More colorful default palette and editor

### ISSUE THREAD

**Issue by ambyra** [nesbox/TIC-80#567]
The default editor and palette colors are a little sad, at least compared to the pico8 palette. Maybe the 1.0. version could have a new paint job? 

This site has a lot of nice options. 

https://lospec.com/palette-list

**Comment by Nullious** [comment]
As the palette is freely changeable I don't see this as a huge issue, you can change the palette in config and that becomes the default .

**Comment by ambyra** [comment]
The editor palette as well? Anyway, I think a new default color scheme for would be nice for the 1.0 version. I’m creating some samples.

**Comment by ambyra** [comment]
![1b](https://user-images.githubusercontent.com/10302044/37674419-ba446eb8-2cd7-11e8-8759-8f75831756cd.PNG)
![2b](https://user-images.githubusercontent.com/10302044/37674420-ba9b4116-2cd7-11e8-9eda-25c09e3ec3b8.PNG)
![3b](https://user-images.githubusercontent.com/10302044/37674422-baf10056-2cd7-11e8-8867-c16563f81677.PNG)
![4b](https://user-images.githubusercontent.com/10302044/37674426-bb6021ca-2cd7-11e8-86bb-635844fdc18b.PNG)
![5b](https://user-images.githubusercontent.com/10302044/37674427-bbb9bafa-2cd7-11e8-8520-124b2d7a20ff.PNG)

**Comment by frenetic** [comment]
I like your samples!
What do you guys think would be the best approach?
Changing the default color schema or having a few different schemas the user can select/change through config?

**Comment by nesbox** [comment]
Dup of #873
