### ISSUE TITLE
Add font width/height to the config

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#568]
and remove `TIC_FONT_WIDTH`... defines from `tic.h`

**Comment by nesbox** [comment]
added FONT section to the _config/theme_ 03efd90
``` lua
THEME=
{
...	
	FONT=
	{
		WIDTH=4,
		HEIGHT=6,
	},
}
```
here is font made by @Nullious 
![tinyfont](https://user-images.githubusercontent.com/1101448/37284400-76f87be4-260c-11e8-923f-6302a4f4e045.gif)

and how it looks in TIC with `width=4` and `height=6`

![image](https://user-images.githubusercontent.com/1101448/37284217-c06543da-260b-11e8-9dee-81b354926d38.png)
![image](https://user-images.githubusercontent.com/1101448/37284179-9a5287de-260b-11e8-84a0-0691956fcffa.png)
![image](https://user-images.githubusercontent.com/1101448/37284190-a2bddf4a-260b-11e8-9117-bdd9b2fc8f94.png)

**Comment by StinkerB06** [comment]
This is going to be very useful for using game fonts being the system font.
