### ISSUE TITLE
use dofile to import libraries

### ISSUE THREAD

**Issue by theFox6** [nesbox/TIC-80#574]
I think it would be nice if `dofile()` could be used to import libraries and then use the in the code in your cart.
![thiswouldbeawesome](https://user-images.githubusercontent.com/28263817/37973796-9ab8f01a-31db-11e8-8603-8e5ec7419482.gif)
Here I would load my Library with some nice advanced printing functions and then I would use them in the code given in the cart.

I think it could be done by making `dofile()` insert the code out of the file virtually at the position where the `dofile()` stood.

**Comment by trelemar** [comment]
Wouldn't this defeat the purpose of having a code limit?

**Comment by theFox6** [comment]
> insert the code out of the file virtually at the position where the `dofile()` stood.

It wouldn't defeat the limit if the file is inserted into the same buffer as the cartidge...

**Comment by nesbox** [comment]
#715 duplicate
