### ISSUE TITLE
Please wrap around PMEM index variable when below 0 or above 255

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#575]
You get an error on the command line if it is below 0 or above 255. Example of API use:

```
pmem(256,value)
```
or...
```
pmem(-1,value)
```
![syntax error with pmem](https://user-images.githubusercontent.com/30059831/38079276-5d91980e-32f3-11e8-8338-5fb2acb1dec2.gif)
I was trying to make a program that displayed PMEM states of save ID's.

I'd suggest you to implement this before releasing 0.70.0.

**Comment by nesbox** [comment]
pmem index can be `[0...255]` only
try to use `index = index % 256`

**Comment by StinkerB06** [comment]
Please make an example cart please. I don't know this much.

**Comment by nesbox** [comment]
try to read about modulo operator in Lua
https://www.lua.org/manual/5.1/manual.html

**Comment by StinkerB06** [comment]
where should it be in the code? I'm using up and down buttons to choose PMEM index to read

**Comment by nesbox** [comment]
try this
``` lua
if btnp(0) then index=index+1 end
if btnp(1) then index=index-1 end
print("value is "..pmem(index%256))
```

**Comment by StinkerB06** [comment]
Thanks! https://tic.computer/play?cart=494
