### ISSUE TITLE
Please add API command to write/read variable integer sizes to RAM in easier way

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#578]
Here's an idea of how it could be like:
`intvw(addr,bit_offset,int_size,value,sign)`

"addr" is the start address of the integer in the 80K RAM.
"bit_offset" is the bit in the 80K RAM byte to start the integer from. (0-7)
"int_size" is the size of the integer. (From 1 bit to 32 bits)
"value" is the value to store in the integer.
"sign" makes the last bit in the integer a flag bit to negate its value. (True/False)

And same as for reading the integer:
`intvr(addr,bit_offset,int_size,sign)`

**Comment by planer28** [comment]
You can just do something like this:
pmem(0,val<<(valuenumber*valuesize))
And when reading:
val=(pmem(0)>>(valuenumber*valuesize))&(maxvalue)
Though you still need to specify the slot, but that's what I use.

**Comment by nesbox** [comment]
Not sure if we have to waste the API with such small functionality, pls wrap `peek/poke` for such purposes.
As for `pmem()`, in .80 PMEM mapped to the RAM.
