### ISSUE TITLE
Button release function

### ISSUE THREAD

**Issue by Graicc** [nesbox/TIC-80#579]
Since there is already a btnp function, It should be easy to add a btnr (button release) function as well. Yeah, that would just be nice to have.

**Comment by StinkerB06** [comment]
And keyr for the keyboard.

**Comment by capturts** [comment]
But btnp() only checks if the button is pressed _right now_. This would only make sense if there were _callback functions_ that got called when the button was pressed or released.

If you need to do something like this then in the TIC() function you could just use a variable to "remember" that, say, _left_ was pressed. And then just before you check if the button currently pressed, check if that variable is set; _ie has the button been released_.

**Comment by Graicc** [comment]
@capturts btnp() is true on the first frame the button is pressed, so btnr() would be true on the first frame the button is released (i.e. in the last frame it was pressed and now it isn't). I don't see how there would be a need for callback functions in order to be useful. I know you could easily implement it, but you would basically be rewriting a bunch of code that is already built in (for the btnp() function) in order to do a similar function.

**Comment by capturts** [comment]
Ok, I see what you mean now. I don't suppose I've had the need for such a thing, but I see it could be handy in various situations.

**Comment by nesbox** [comment]
Sorry, I wouldn't want to extend the API with such small functions.

**Comment by revdeluxe** [comment]
perhaps just make the btn() return value if they are pressed or released in a boolean manner.

**Comment by revdeluxe** [comment]
i suggest using while loop instead of if statement if you want to know if the btn() is released.

**Comment by joshgoebel** [comment]
This is simply not necessary in core as it can easily be done with a tiny helper function. Definitely an area for client libs to shine.
