### ISSUE TITLE
Sync flashes in the corner of the screen.

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#580]
Version: 0.60.3 Pro
Whenever using TIC, even in the editor I get red SYNC text flashing on screen.
https://gfycat.com/BlackandwhiteDefiantBurro
![](https://thumbs.gfycat.com/BlackandwhiteDefiantBurro-size_restricted.gif)

![image](https://user-images.githubusercontent.com/13716824/38437471-7474c054-39cf-11e8-88a6-cd11d5b1320b.png)
I'm assuming it's to do with vsync and the config that @Nullious is talking about is 
![image](https://user-images.githubusercontent.com/13716824/38437509-8de63612-39cf-11e8-97b3-d048ff7b412f.png)

**Comment by abcq2** [comment]
Yeah, I think it displays when a frame is partly rendered but waiting for vsync. vsync also reduces the frame rate a little so it's kind of a self fulfilling prophecy. try turning off `USE_VSYNC`

**Comment by planer28** [comment]
To disable it, change MISSED_FRAMES to a high number, like 500.
This basically mean that sync will show if 500 frames have to be skipped in order to run at full speed.

**Comment by briangordon** [comment]
After running for a few minutes I see SYNC flash even with MISSED_FRAMES set to 6000. 

I'm running on Android (on a Gemini PDA). I `config save`d and restarted to make sure the config had taken effect.

**Comment by frenetic** [comment]
Could you guys test it on the latest version?

**Comment by nesbox** [comment]
`SYNC` label was removed in the latest version
