### ISSUE TITLE
Incorrect Highlighting in Code Editor

### ISSUE THREAD

**Issue by capturts** [nesbox/TIC-80#581]
If have some code like this:
```
print([===[
This is the first line
This isn't the first line
]===])
```
But after the _'_ highlighting is incorrect. The code works, but it shows wrong in the editor.

I did find a work-around
```
print([===[
This is the first line
This isn't the first line
]===]) --'
```
Which fixes the highlighting, until you have a second _'_ in the string.

**Comment by frenetic** [comment]
Related to https://github.com/nesbox/TIC-80/issues/370

**Comment by nesbox** [comment]
dup of #370
