### ISSUE TITLE
0.60.3 becomes increasingly unstable with sound popping and crashes.

### ISSUE THREAD

**Issue by abcq2** [nesbox/TIC-80#583]
(edited my posts because original description was unhelpful)

Hello,

I am running TIC-80 0.60.3, the Windows binary version downloaded from the official site. I am on Windows 7 with a Mobility Radeon GPU.

After the program runs for a few minutes in any cartridge, the sound begins popping and crackling and eventually the program crashes to desktop.

I do not believe this to be a performance issue; 0.50 runs perfectly smoothly, whereas I can crash 0.60.3 to the desktop by running the "hello world" cartridge for a few mintues then just typing `folder` repeatedly. Crash dump follows:

```
Problem signature:
  Problem Event Name:		APPCRASH
  Application Name:		tic80.exe
  Application Version:		0.60.3.0
  Application Timestamp:	5a59f599
  Fault Module Name:		ntdll.dll
  Fault Module Version:		6.1.7601.17514
  Fault Module Timestamp:	4ce7ba58
  Exception Code:		c0000005
  Exception Offset:		0002e39e
  OS Version:			6.1.7601.2.1.0.768.3
  Locale ID:			2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
```

**Comment by StinkerB06** [comment]
Maybe because of your system's performance? What are your specs?

**Comment by abcq2** [comment]
I would have assumed it was my specs if it were just the sound popping and frame skipping, but I can totally crash the program by typing the `folder` command repeatedly.

It's 2 (hardware) core 2.7 GHz, 4GB RAM, mobility Radeon graphic

**Comment by abcq2** [comment]
fat fingered on my phone. I don't think it's possible to edit posts?

anyway I can cause the issue with the Hello World cart or by repeatedly typing 'folder', it is a full crash to desktop, and I can't even partially replicate on 0.46 or 0.50, so I don't think it's performance. plus CPU and RAM usage are totally normal.

**Comment by StinkerB06** [comment]
Were you on a computer? If you where, on which operating system?

**Comment by abcq2** [comment]
Whoops. Windows 7, 64-bit

**Comment by abcq2** [comment]
saw some mention online of integrity checking this DLL so this was the result

```
C:\Windows\system32>sfc /verifyonly

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection did not find any integrity violations.
```

**Comment by frenetic** [comment]
@abcq2 could you please test it on the latest released version?

**Comment by abcq2** [comment]
@frenetic I can't reproduce the issue on 0.70.6. Thank you :+1:
