### ISSUE TITLE
divide by zero crashes tic80

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#585]
> I was doing some tweetcart experiments and accidentally did a divide-by-zero which crashed the app.  pico-8 handles this quietly,  which IMO is a double edged sword, but a run-time error would be fine I think.

**Comment by planer28** [comment]
I tried this in JavaScript:
```JavaScript
// title:  game title
// author: game developer
// desc:   short description
// script: js

var x=96

function TIC()
{
	x=x/0
}
```
And nothing happened, it didn't crash and didn't throw an error.
So I'm guessing it's Lua-exclusive?

**Comment by frenetic** [comment]
It may be a Lua thing...
http://lua.2524044.n2.nabble.com/catching-divide-by-zero-td7655163.html

**Comment by nesbox** [comment]
I tested the code
``` lua
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua

t=0
x=96
y=24

test=y/0
trace(test)
function TIC()end
exit()
```

and got `inf` output without any crash
![image](https://user-images.githubusercontent.com/1101448/78883506-44549900-7a62-11ea-9da6-3944232172d0.png)
Seems, the crash occurred in the other situation, closing.

**Comment by 12buntu** [comment]
This issue still occurs while using Wren and the `line` function:

![image](https://user-images.githubusercontent.com/36310448/103179341-ff270000-4858-11eb-8cb7-6aef6481c14e.png)

Should I open a new issue?

**Comment by RobLoach** [comment]
Maybe an issue for Wren?
