### ISSUE TITLE
No sound on Mac OS 10.13.4 after focus lost

### ISSUE THREAD

**Issue by McGittyHub** [nesbox/TIC-80#588]
neither the sfx editor or the music editor is producing any sound.

**Comment by gianluca-tenino** [comment]
I get this problem as well unless I don't have the window fullscreen.

**Comment by nesbox** [comment]
Hmm, can't reproduce, close for now.

**Comment by Giulidan** [comment]
I don't have any sound from TIC80 when I activate the fullscreen mode, having to restart it in windowed mode, otherwise is mute. I'm using 1.0.2164 Pro version on Windows 10.
