### ISSUE TITLE
Can't type ‘=’ on Firefox

### ISSUE THREAD

**Issue by andraaspar** [nesbox/TIC-80#589]
US keyboard, Win10, https://tic.computer/create (0.60.3)

The button does not type ‘=’ and it also does not type ‘+’ (with shift). Completely ignored. Works on Chrome though.

**Comment by frenetic** [comment]
Reproduced it today.

**Comment by henrebotha** [comment]
As of TIC-80 version 0.70.6 and Firefox version 70.0.1, this bug still exists.

**Comment by nesbox** [comment]
All is ok on Firefox 82.0.2
Closing...
