### ISSUE TITLE
No sound in Chrome 66

### ISSUE THREAD

**Issue by McGittyHub** [nesbox/TIC-80#590]
My version of chrome 66.0.3359.139

Following warning is written to the console:

The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Comment by AnastasiaDunbar** [comment]
Disable it here: chrome://flags/#autoplay-policy

**Comment by nesbox** [comment]
We added `Click to play` link in .80 to enable sound.
Closing...
