### ISSUE TITLE
Token limit?

### ISSUE THREAD

**Issue by andraaspar** [nesbox/TIC-80#591]
Since TIC-80 supports JS, nothing stops me from minifying my code. It seems to be against the spirit of the whole thing...

**Comment by andraaspar** [comment]
I did a test. I created a small project (~5k) in MoonScript and translated it to TypeScript. The compiled JS was way too large (~8k). I had to opt for not using Webpack but use global scope instead (`/// <reference path='...' />`). I also had to enable top-level name mangling in UglifyJS. After all this, minified JS was still larger than plain MoonScript: `4940` vs. `4818`.

Conclusion: minified JS is roughly equivalent to plain MoonScript in size. Tooling is nicer, but hey. Don't overcomplicate. Closing this.

**Comment by RobLoach** [comment]
@andraaspar With MoonScript, did you end up bundling the files together? Or keeping it all in one .moon file?

I got MoonScript to compile the .moon files, and then bundled them together with [lua-amalg](https://github.com/siffiejoe/lua-amalg). The file size ends up being much larger than straight up .moon file, was curious what you ended up with.

**Comment by andraaspar** [comment]
@RobLoach: I keep everything in one file and use VS Code's collapse function to keep it manageable. It makes refactoring easier as well, since it's just a find and replace.

I abandoned JS altogether in the TIC, since I heard that performance is also a lot worse than lua / moonscript.
