### ISSUE TITLE
Crash when eval TIC()

### ISSUE THREAD

**Issue by Tau5** [nesbox/TIC-80#593]
If you simply run `eval("TIC()")` it crashes

**Comment by planer28** [comment]
I just have no idea why would you want to call the TIC function manually, especially through eval().

**Comment by AnastasiaDunbar** [comment]
You can do:
```js
// script: js
function TIC(){}
eval("TIC=function TIC(){cls(0);print('Hello!',0,0,15);};");
```

**Comment by AnastasiaDunbar** [comment]
You could try:
```js
// script: js
eval("function TIC(){cls(time());};");
```

**Comment by nesbox** [comment]
crash fixed here 60c4386

**Comment by AnastasiaDunbar** [comment]
`eval` can be used to produce functions without writing your own parser.

**Comment by StinkerB06** [comment]
@AnastasiaDunbar Please post the Lua version of the eval example you posted above. JS isn't my go-to language.

**Comment by AnastasiaDunbar** [comment]
```lua
eval("function TIC()cls(time())end")
```
?
