### ISSUE TITLE
Interest in Fennel support?

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#594]
I have a patch where I've added support for the [Fennel programming language](https://fennel-lang.org) to TIC-80: https://github.com/technomancy/TIC-80/commit/d114930dbed917b8f79c6f71c20769cfff374cb8 (edit: note that the commit message shows a few steps which are still manual that need to happen if you want to try out that branch for yourself)

Fennel is a single-file compiler that emits Lua code, so as you can see it was not much work to get it supported; I followed the example from MoonScript which is similar, but MoonScript is a fair bit more complex overall.

If there is interest in having this in mainline TIC-80 I would be happy to polish up and submit it as a proper pull request. I'm one of the lead devs on the Fennel language, so if you have any questions about it I'm happy to answer them. If you decide it's not a good fit for mainline TIC-80 that's fine too; I can maintain the patches in my own fork and that's good enough for me.

**Comment by nesbox** [comment]
I think it's a good idea.
Thanks :)

**Comment by technomancy** [comment]
Great; glad to hear it.

It looks like `bin/assets/*` are supposed to be autogenerated, but they are checked into git and not included in the `.gitignore`; was that intentional?

**Comment by nesbox** [comment]
you can regenerate `assets` if you need, in my case I do it only once before building version
