### ISSUE TITLE
X11 keyboard layout not respected

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#596]
When I play TIC on a machine that is configured for dvorak (in X11), keyboard input is still interpreted as if it were in qwerty.

I believe this was not the case in January the last time I built from source, but since the "3rd-party" repository doesn't have tags on it I had trouble trying to go back and build an old version to check.

**Comment by frenetic** [comment]
Im sorry to hear that @Jummit :(

Could you guys please try to reproduce it on the latest released version?

**Comment by technomancy** [comment]
Works great on 0.70.6; thanks!
