### ISSUE TITLE
Build issue on Linux Debian

### ISSUE THREAD

**Issue by RyanLeadbetter** [nesbox/TIC-80#599]
I am unable to build TIC-80 on Linux Debian.

For a normal build, use the linux target.
-lto targets (Link Time Optimization) have smaller output size.
wasm, emscripten and mingw targets require their compilers to be installed.
1) dependencies	 4) linux64-lto	  7) mingw
2) linux	 5) emscripten	  8) chip-lto
3) linux32-lto	 6) wasm	  9) exit
Select build target: 2
make static -C 3rd-party/wren-0.1.0/
make[1]: Entering directory '/home/ryan/TIC-80/3rd-party/wren-0.1.0'
make[2]: Entering directory '/home/ryan/TIC-80/3rd-party/wren-0.1.0'
       str src/vm/wren_core.wren          
/usr/bin/env: ‘python’: No such file or directory
util/wren.mk:230: recipe for target 'src/vm/wren_core.wren.inc' failed
make[2]: *** [src/vm/wren_core.wren.inc] Error 127
make[2]: Leaving directory '/home/ryan/TIC-80/3rd-party/wren-0.1.0'
Makefile:32: recipe for target 'static' failed
make[1]: *** [static] Error 2
make[1]: Leaving directory '/home/ryan/TIC-80/3rd-party/wren-0.1.0'
Makefile:375: recipe for target '3rd-party/wren-0.1.0/lib/libwren.a' failed
make: *** [3rd-party/wren-0.1.0/lib/libwren.a] Error 2
Select build target:

**Comment by theonlyames** [comment]
I believe you don't have the needed third party repositories, try cloning the repo again using: `git clone --recurse-submodules https://github.com/nesbox/TIC-80` or add them manually.

**Comment by nesbox** [comment]
Build instructions were updated

**Comment by Sushnata1** [comment]
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Error at /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.27/Modules/FindCURL.cmake:182 (find_package_handle_standard_args)
  CMakeLists.txt:1001 (find_package)

I got this error message while running the 'cmake ..' command. Please help

**Comment by sogaiu** [comment]
It looks like some `curl`-related bits are missing.

In practice I haven't found that not having the Doxygen stuff matters -- though perhaps others have found differently.

**Comment by Sushnata1** [comment]
Can you suggest me what to do ?
