### ISSUE TITLE
sync(0) will sync everything except code.

### ISSUE THREAD

**Issue by DaAndroid614** [nesbox/TIC-80#600]
It would be useful if using the sync() command would sync code from a cart after it's edited. This would come in handy if you could resume and test edited code without restarting a cart.

**Comment by planer28** [comment]
But you can't edit code during runtime...

**Comment by planer28** [comment]
Oh and remember that if you'd want the code changes to be applied, you'd HAVE TO restart the cart, because if you don't re-run the code, there won't be any changes, and if you do, you will also redefine all your variables.

**Comment by nesbox** [comment]
Yes, this is how it works
