### ISSUE TITLE
Creating fedora package for tic-80

### ISSUE THREAD

**Issue by Nunuvin** [nesbox/TIC-80#603]
I might have some spare time on my hands and was wandering if it was a good idea/get a green light to create packages for tic-80 in fedora and maybe ubuntu.
Any thoughts?

EDIT: not very comfortable with debian.

**Comment by frenetic** [comment]
What do you mean with packages?
PPA packages or Flatpak/Snap?

**Comment by Nunuvin** [comment]
I was thinking along the lines of PPA package I guess. I eliminating the difficulties with installing tic (ie building from source, even though thats not that bad) can be very helpful and make it more appealing and accessible to more people.

**Comment by Nunuvin** [comment]
sure

**Comment by nesbox** [comment]
dup of #253
