### ISSUE TITLE
Fresh build crashes on launch on macOS High Sierra 10.13.4

### ISSUE THREAD

**Issue by armadsen** [nesbox/TIC-80#605]
I'm building master on macOS 10.13.4 using vanilla toold (ie. system-included and included with Xcode) using `make macosx` and `make`. When I run the compiled app, it crashes on launch. Crash log is attached.

The binary release of the pro version from itch.io works fine. I'm building master because I'd like to use the support for Wren that's not in the public binary release.

[TIC80Crash.txt](https://github.com/nesbox/TIC-80/files/2037307/TIC80Crash.txt)

**Comment by nesbox** [comment]
I've fixed the crash recently, but on another branch, will merge it soon...
Thanks

**Comment by armadsen** [comment]
Thanks for the quick response! Let me know if I can do anything to help (I’m a Mac developer, myself).

**Comment by armadsen** [comment]
Confirmed that this is fixed in the #320 branch, presumably by 6d945a2. The switch to cmake there is really nice too :)
