### ISSUE TITLE
I keep getting "502: Bad gateway" error when I try to see tic.computer notifications

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#606]
Everytime I want to check the notifications on the tic.computer website, it just shows me an error.

![bandicam 2018-05-24 19-21-45-917](https://user-images.githubusercontent.com/30059831/40522942-2059e9de-5f88-11e8-8198-ec29ff67f32f.jpg)

**Comment by nesbox** [comment]
hmm, strange, I'll look at it soon...
thanks

**Comment by StinkerB06** [comment]
Please fix it!

**Comment by Anrock** [comment]
Is this still an issue?

**Comment by Anrock** [comment]
Closed as #936 dupe
