### ISSUE TITLE
Can't convert function to string properly (JavaScript)

### ISSUE THREAD

**Issue by planer28** [nesbox/TIC-80#607]
I wrote an operating system-like thing, and wanted it's terminal to show the lengths of the programs (which are stored as functions), however everything I tried returns function () { [ecmascript code] }.

**Comment by AnastasiaDunbar** [comment]
This is a [Duktape](http://duktape.org) issue.

**Comment by planer28** [comment]
Uh, so I assume it can't be easily fixed from here?

**Comment by AnastasiaDunbar** [comment]
You do also know that whitespace in functions are included when it's converted to string? Also [see this](https://github.com/svaarala/duktape/issues/1647).
You could also write your programs like:
```js
var program="\
function(){\
 print(\"Hello.\",0,0);\
}";
```

**Comment by planer28** [comment]
Yeah, but I have a whole set of system software built the way it is, plus it just makes the thing longer.
AND I also like the syntax highlighting.

**Comment by AnastasiaDunbar** [comment]
I can't help you here for now because I don't know what you'd do. I'm not sure if there's a better JavaScript engine that TIC-80 could use too.

**Comment by planer28** [comment]
I understand. I mean, it ain't like using the terminal for checking sizes of programs is important in a graphical operating system, so I actually don't care too much about it :P
