### ISSUE TITLE
Interest in perspective corrected textri() ?

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#612]
Yesterday we discussed on discord about textri and its use to render textured 3d graphic. Turns out it's not really suitable becouse the image interpolation doesn't take into account the depth of the image, creating [affine texture mapping](https://en.wikipedia.org/wiki/Texture_mapping#Affine_texture_mapping) artifacts.

A possible solution that was proposed is to add three new optional parameters, d1, d2, d3 that represents the depth of the three vertices and change the interpolation method if they are provided. 

The change should not be hard to implement (i could give it a try eventually), but it's probably more a question of pertinence. Should TIC support this kind of 3d primitive? 

Note that one could implement his own raster in Lua but i'm sure the performance penality would be noticeable.

**Comment by Tinchetsu** [comment]
I think this is a good idea. I'm also making 3D stuff with textri, and this can be very handy.
Perhaps a function like textri3D()?

**Comment by Nullious** [comment]
It should be done with just additional parameters , no new functions, if you don't pass in the Z parameters it should just use the normal path ( for speed ) then Z divide when needed parameters are passsd in.

**Comment by rdococ** [comment]
I tried to implement a function to render perspective correct textured triangles in Lua, but it was way too slow. You can try subdivision, but that doesn't really work that well either. So far, the only triangles that are good for games are flat and single-color, which is boring.

**Comment by nesbox** [comment]
We could have another one func like `ptextri()` to render a perspective corrected triangle.
Or something like `pttri() / ttri()`

**Comment by nesbox** [comment]
Added perspective correction to the `textri()` with three additional depth parameters `z1 z2 z3`
Now it looks like `textri(x1,y1,x2,y2,x3,y3,u1,v1,u2,v2,u3,v3,[src=0],[chroma=off],[z1=0, z2=0, z3=0])`

### with correction
![video5](https://user-images.githubusercontent.com/1101448/160176923-acfbc5fe-2dbf-422b-b958-8667b5c19972.gif)

### without correction
![video10](https://user-images.githubusercontent.com/1101448/160176927-85937cb5-640a-4bd1-a979-a1ac00b12c9b.gif)

commit 747bd73d3ce30a496b222d4de31b09800c488fbf

**Comment by nesbox** [comment]
Also, old carts can be easily modified to use the corrected texture.
![video11](https://user-images.githubusercontent.com/1101448/160574227-a7ef6ae9-cb69-448a-9414-20d80ccd351a.gif)
