### ISSUE TITLE
JavaScript runs slower than Lua

### ISSUE THREAD

**Issue by planer28** [nesbox/TIC-80#617]
I made a simple water simulation in js, it ran at ~5 FPS. After a rewrite in Lua (with things working exactly the same way) it ran at full speed.

**Comment by nesbox** [comment]
TIC uses Duktape as JS interpreter
unlikely that we can do anything here

**Comment by planer28** [comment]
Uh. Too bad.

**Comment by AnastasiaDunbar** [comment]
Would you mind if you'd share your source code for JS and Lua?

**Comment by planer28** [comment]
I've done something to both and now the water particles keep eating themselves, but otherwise it works the same:
`// title:  game title
// author: game developer
// desc:   short description
// script: js

mflr=Math.floor

buf=[]
tmp=[]

// [vars]

lastm=mouse()

// [end vars]

// [settings]

iswalll=true //left wall
iswallr=true //right wall

// [end settings]

function cpmap(){
	var n=0
	var x=0
	var y=0
	//while(n<32640)do
		//wrmap(n%240,mflr(n/135),peek(0x08000+n))
		//n=n+1
	//end
	while(y<136){
		wrmap(x,y,mget(x,y))
		x++
		if(x>239){x=0;y++}
	}
	tmp=buf
	buf=[]
}

function wrmap(x,y,a){
	buf[x+y*240]=a
	pix(x,y,a)
}
function isempty(x,y){
	if(rdtmp(x,y)==0&&!(buf[x+y*240]==8))return true
	return false
}
function rdtmp(x,y){var t=tmp[x+y*240];if(t==undefined){return 0} return tmp[x+y*240]}

function update(){
	buf=[]
	var x=0
	var y=0
	var r
	for(x=0;y<136;x++){
		r=mflr(Math.random()*4096)%256
		if(rdtmp(x,y)==8){
			if(rdtmp(x,y+1)==0&&y<135)wrmap(x,y+1,8)
			else if(r>128&&isempty(x+1,y)){if(x<240){wrmap(x+1,y,8)}else{wrmap(x,y,8)}}
			else if(r<125&&isempty(x-1,y)){if(x>0){wrmap(x-1,y,8)}else{wrmap(x,y,8)}}
		}if(x>239){x=0;y++}
	}
	tmp=buf
}

cls()
cpmap()
var t=0

function TIC(){
	cls()
	var mus=mouse();var mx=mus[0];var my=mus[1]
	var ml=mus[2];var mr=mus[3]
	if(ml)wrmap(mx,my,8)
	if(mr){
		wrmap(mx,my,8)
		wrmap(mx+1,my,8)
		wrmap(mx-1,my,8)
		wrmap(mx,my+1,8)
		wrmap(mx,my-1,8)
	}
	update()
	t++
}
`
And here's Lua:
`-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua

buf={}
tmp={}

-- [vars] --

lastmx,lastmy,lastml=mouse()

-- [end vars] --

-- [settings] --

iswalll=true --left wall
iswallr=true --right wall

-- [end settings] --

function cpmap()
	local n=0
	local x=0
	local y=0
	--while(n<32640)do
		--wrmap(n%240,n//135,peek(0x08000+n))
		--n=n+1
	--end
	while(y<136)do
		wrmap(x,y,mget(x,y))
		x=x+1
		if(x>239)then x=0 y=y+1 end
	end
	tmp=buf
	buf={}
end

function wrmap(x,y,a)
	buf[x+y*240]=a
	pix(x,y,a)
end
function isempty(x,y)
	if(rdtmp(x,y)==0 and not (buf[x+y*240]==8))then return true end
	return false
end
function rdtmp(x,y)local t=tmp[x+y*240]if(t==nil)then return 0 end return tmp[x+y*240]end

function update()
	buf={}
	local x=0
	local y=0
	local r
	while(y<136)do
		r=math.random(0,255)
		if(rdtmp(x,y)==8)then
			if(rdtmp(x,y+1)==0 and y<135)then wrmap(x,y+1,8)
			else if(r>128 and isempty(x+1,y))then if(x<239)then wrmap(x+1,y,8)else wrmap(x,y,8) end
			else if(r<125 and isempty(x-1,y))then if(x>0)then wrmap(x-1,y,8)else wrmap(x,y,8) end
			end end end
		end
		x=x+1
		if(x>239)then x=0 y=y+1 end
	end
	tmp=buf
end

cls()
cpmap()
local t=0

function TIC()
	cls()
	local mx,my,ml,mm,mr=mouse()
	if(ml)then wrmap(mx,my,8) end
	if(mr)then
		wrmap(mx,my,8)
		wrmap(mx+1,my,8)
		wrmap(mx-1,my,8)
		wrmap(mx,my+1,8)
		wrmap(mx,my-1,8)
	end
	update()
	t=t+1
end
`

**Comment by AnastasiaDunbar** [comment]
[I converted Lua to JavaScript by hand myself, and you're right, it is slow.](https://pastebin.com/YPat5BM5)
I've been also amazed by how quick a recursive flood fill performs in Lua (but stack-based was apparently slower) when I played around with LÖVE.

**Comment by planer28** [comment]
Well at least it's fine for most stuff which don't include redrawing the screen from an array :)

**Comment by planer28** [comment]
And well I have rewritten it today in a completely different way and it works smooth as butter

**Comment by planer28** [comment]
Damn I didn't want to press that
