### ISSUE TITLE
All menus continuously scroll up

### ISSUE THREAD

**Issue by L1011H** [nesbox/TIC-80#621]
All menus scroll up continuously directly after starting tic-80. Win7 x64 0.60.3 binary from the website.

**Comment by StinkerB06** [comment]
I think it's due to the gamepad input.

**Comment by L1011H** [comment]
It doesn't seem to be a controller issue as it happens with all controllers unplugged as well.

**Comment by StinkerB06** [comment]
TIC-80 checks for the Gamepad input, so you can otherwise start browsing the SURF menu with touching the QWERTY keyboard.

**Comment by L1011H** [comment]
Solved. There seems to be a conflict with vJoy a virtual joystick driver(https://sourceforge.net/projects/vjoystick/) Uninstalling prevented the issue.
