### ISSUE TITLE
The uppercase O and 0 of the website font look the same.

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#625]
When I've seen people mention my username "StinkerB06" in the website comments of cartridges, the zero is sometimes the letter O. I use a TTS extension on my Chrome to make sure that character is typed correctly by the person who typed my username. The "06" in my username is the century number I was born in. I'd prefer that this wouldn't happen any further.

At least modify the zero in the website's font to have that line in the middle (derived from the Consolas font), or even replace the font with a much more-readable font.

**Comment by StinkerB06** [comment]
Edit: This is also the same with TIC-80's default font upon running the executable for the first time.

**Comment by AnastasiaDunbar** [comment]
A slash could be added for 0: ![image](https://user-images.githubusercontent.com/11806048/41759829-a55ef1d2-75f0-11e8-91ab-073ed4271940.png)

**Comment by planer28** [comment]
Yup, that would be nice.

**Comment by nesbox** [comment]
Already done
