### ISSUE TITLE
[Linux] CLA -fullscreen not working?

### ISSUE THREAD

**Issue by telanus** [nesbox/TIC-80#626]
Hi

Compiled tic-80 on Kubuntu 18.04, and it runs quite well. While writing a runner for [Lutris](https://lutris.net/) I was testing the Command Line Arguments, and those I tested work, but the -fullscreen one doesn't seem to work, tic80 doesn't complain that the argument is unknown, but it doesn't go fullscreen

**Comment by frenetic** [comment]
@telanus can this issue be closed?
