### ISSUE TITLE
Ctrl-D in the code editor should duplicate the current line

### ISSUE THREAD

**Issue by RamiLego4Game** [nesbox/TIC-80#627]
As the title says

**Comment by RamiLego4Game** [comment]
Any update ? This shouldn't take time to implement

**Comment by jahodfra** [comment]
Why do you feel entitled to demand unpaid work from somebody?
https://gomakethings.com/open-source-etiquette/

Please, consider making the feature yourself.

**Comment by RamiLego4Game** [comment]
Just refreshing this issue, and, I have no C knowledge, thanks for your
response.

**Comment by jahodfra** [comment]
I wanted to just note, that TIC-80 creator has feelings too. The C language is not so hard and its still widely used, so I wouldn't consider the lost time to learn it.

**Comment by RamiLego4Game** [comment]
Okay, I guess will all this hate I better give up about requesting this simple thing and close the issue ?
