### ISSUE TITLE
Build failing on Archlinux both from AUR and github

### ISSUE THREAD

**Issue by MrEvilCookie** [nesbox/TIC-80#635]
When installing TIC-80 from ArchUserRepository it errors with ``ERROR: Failure while downloading https://github.com/tjahneee/3rd-party/archive/v0.60.3-libs.tar.gz   Aborting...`` two times and then prints 
``:: failed to verify integrity or prepare tic-80 package`` two times at the end.
Here is a screenshot of output (hastebin doesen't want to wark with pacaur for some reason):
![image](https://user-images.githubusercontent.com/20132158/42734541-86538cb0-884e-11e8-8f5f-1c8807f239f0.png)
Then I tried to do 
``
git clone --recursive https://github.com/nesbox/TIC-80 && cd TIC-80 && ./build.sh
`` (I made sure that I have latest git.)
The output was:
![image](https://user-images.githubusercontent.com/20132158/42734576-0cb5f1c6-884f-11e8-87e4-8f891e0b0182.png)
Then I searched the issues and found #367 and #352 and tried everything that was recommended in those issues. I also tried ``make linux`` but then got output: 
![image](https://user-images.githubusercontent.com/20132158/42734598-60726c04-884f-11e8-9e1b-dc91bcacc912.png)
I don't know what to try now and because of this I am submitting this issue. Hope somebody knows a solution to this. Thanks in advance.

**Comment by db0z** [comment]
This error is on part of Wren, a third-party library used by TIC-80. It may be that it's only noticed by newer versions of the compiler or something. You can simply suppress it by changing a line in `3rd-party/wren-0.1.0/util/wren.mk` from 
```
C_WARNINGS := -Wall -Wextra -Werror -Wno-unused-parameter
```
to 
```
C_WARNINGS := -Wall -Wextra -Wno-unused-parameter
```
(without `-Werror`).

**Comment by frenetic** [comment]
Hey guys, is this still an issue?
