### ISSUE TITLE
Cursor Hotspot / Hitbox

### ISSUE THREAD

**Issue by torridgristle** [nesbox/TIC-80#637]
Currently the I-Beam cursor uses the top left as the hotspot, though Windows and probably everything else uses the middle of the I so it can be used like crosshairs on letters. This can be an issue when the cursor can be absolutely anything within an 8px square so manual settings for the hotspot may be required for fluid and easy to use I-Beam cursors.

Perhaps a line like IBEAM_HOTSPOT in the config and the value is 2 numbers next to each other for X and Y coords starting from top left so the default can be 00 for 0th column and 0th row. For my own I-Beam cursor I'd need 33 for 3rd column and 3rd row or 34 for 3rd column and 4th row.

Reckon the bitmap just needs to be offset to match.

Something like this might as well be implemented for everything since the Hand cursor typically has the extended finger as the hotspot and it's often not in the top-left. This would also allow for any weirdo out there to use a centered vertical arrow cursor.

**Comment by joshgoebel** [comment]
I think you'd want `CURSOR_HOTSPOT` and a position in RAM also... you could do this with 1 byte.  We have 3 bytes left in VRAM.

```
x hotspot - 4bit
y hotspot - 4bit
```

Though then the "hardware" changing it magically if you poked a new cursor might be weird, so I'm not sure the default behavior for ibeam (or other cursors) should change?...

**Comment by TimotheeGreg** [comment]
The hotspot of the I-Beam cursor is now in the center and the hotspot of the Hand cursor is at the end of the finger. So this is solved.
