### ISSUE TITLE
Page Up / Page Down

### ISSUE THREAD

**Issue by torridgristle** [nesbox/TIC-80#639]
Page up / Page down would be pretty useful for the console interface what with the small window and limited lines.  Currently all I've tried that seems to work is moving a hand onto my mouse to scroll.

**Comment by jahodfra** [comment]
Please split issues into individual pieces. 
The smaller the piece the more frugal discussion it can produce. Also it increase the probability that somebody will try to implement it.

I think you are proposing the following changes:
1. PageUp, PageDown keys should work in console.
2. Key for clearing console command.
3. Cached cartridges working offline. #453

**Comment by torridgristle** [comment]
Yeah, that makes sense, I'll split them up. Just didn't want nesbox to come back to 10+ issues but at least it'd be orderly.

**Comment by nesbox** [comment]
Added `PageUp, PageDown` to the Console here 1644f80
