### ISSUE TITLE
config.tic Custom Shader Corruption

### ISSUE THREAD

**Issue by torridgristle** [nesbox/TIC-80#641]
While editing the CRT shader at the end of the config cartridge I've encountered a problem where editing the config in TIC-80 and saving it, or maybe just saving it will cause the problem, adds some seemingly random bytes toward the end of the file. Sometimes right at the end, sometimes in the middle of some words in the shader, I think replacing some letters while also adding some.

My last test seemed to only add extra garbage to the end:
20 20 20 7D 0A 5D 5D 0A
becomes
20 20 20 7D 0A 5D 5D 0A 01 82 35 59 FD 8A 14 08 88 D9 E1 01 50 F4 EF 01 11

Maybe you'll recognize these bytes because they don't really mean anything to me.

**Comment by nesbox** [comment]
I don't think this is a bug, maybe TIC adds another chunk after the code chunk.
