### ISSUE TITLE
mget is for some reason on the incorrect position

### ISSUE THREAD

**Issue by KirppuAapo** [nesbox/TIC-80#642]
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua

    function move()
     if btn(0) and tile>WALL then 
      p.y=p.y-1 
     end
     if btn(1) and tile>WALL then 
      p.y=p.y+1 
     end
     if btn(2) and tile>WALL then 
      p.x=p.x-1 
     end
     if btn(3) and tile>WALL then 
      p.x=p.x+1 
     end
    end

function init()
	WALL=5
	p={
		x=0,
		y=0,
		vx=0,
		vy=0,
		jumpvel=2.4,
		isgrounded=0
	}
	g={
		graw=1
	}
end

init()
p.x=16
p.y=24
function TIC()

	tile=mget(p.x, p.y)

	isgrounded=0

	if tile<WALL then
		p.isgrounded=1
		else p.isgrounded=0
	end

	
	
	if p.isgrounded==1 then
		g.graw=0
	else g.graw=g.graw*1
	end
	
	--p.y=p.y+g.graw
	
	cls()
	map()
	rect(p.x,p.y,8,8,15)
	print(p.isgrounded)
	print(mget(p.x,p.y),0,8)
	move()
end

The mget completely in the wrong place

**Comment by nesbox** [comment]
try to use
`mget(p.x//8,p.y//8)`

**Comment by KirppuAapo** [comment]
Oh ok thx

**Comment by KirppuAapo** [comment]
Oh ok thx
