### ISSUE TITLE
Vertical Games

### ISSUE THREAD

**Issue by SchynsO** [nesbox/TIC-80#644]
Since the screen of TIC-80 is not a square (like PICO-8), it could be possible to make games in portrait mode. But when making the game, it is quite inconvenient having to turn your real screen 90° to be able to test your game comfortably.

Would it be possible to add a tag in the game data to tell if it should be displayed in portrait or landscape mode ?

**Comment by StinkerB06** [comment]
I'd prefer not it to be a tag, but rather an API function that sets it.

**Comment by harraps** [comment]
But if it is an API function, you could change it at run time.
Would it make any sense ?

**Comment by planer28** [comment]
Yes, you could use it just as a tag (even place it with the tags), and your game could switch between portrait and landscape mode at runtime.

**Comment by harraps** [comment]
How would the screen rotate in window mode ?
If we rotate the screen in fullscreen mode, does it means that the pixel will change of size too ?

What would be the benefit of being able to change the screen orientation at runtime ?

**Comment by rdrpenguin04** [comment]
Maybe make something appear to be spinning with less code/sprites?

**Comment by rdrpenguin04** [comment]
Window size can change, and in fullscreen mode, you can just have black sides.

**Comment by novemberisms** [comment]
I feel having it be an API goes against the spirit of TIC80. It REALLY wouldn't make sense if you could do this on a retro computer. You can't just rotate your monitor sideways in the middle of a game!

If this does make it, it HAS to be a tag set per cart. As some retro arcade games had vertical orientation, and it doesn't make sense (codewise, implementationwise, and common-sensewise) for you to be able to switch orientation on the fly.

**Comment by planer28** [comment]
Yeah, you're right.

**Comment by jahodfra** [comment]
There is related issue with how this should interact with the editors and surf mode. The editors and surf mode will probably not work in different layout without redesign. Also I suppose the surf should allow running both type of games. Moreover change of layout has to also work in browser.

**Comment by Quistnix** [comment]
I would love to see this feature as well. Is this on the roadmap?

**Comment by nesbox** [comment]
Not sure about portrait mode, TIC will stay in landscape mode only, sorry.

**Comment by ChildishGiant** [comment]
I feel like this is a roadblock to lots of games, especially considering that TIC runs on android and phone games are often portrait. Sure, they're still possible but on mobile the controls will be in the completely wrong place and on PC you have to hope that your player has a monitor capable of rotation. I think all that's needed is a flag that turns the whole screen 90° when the game is running.
