### ISSUE TITLE
does it run on TempleOS?

### ISSUE THREAD

**Issue by rudolfolah** [nesbox/TIC-80#645]
the technical constraints look about the same 😉 as [TempleOS](https://en.wikipedia.org/wiki/TempleOS):

>240x136 pixels display, 16 color palette, 256 8x8 color sprites, 4 channel sound and etc.

as compared to:

>TempleOS...runs 8-bit ASCII with graphics in source code and has a 2D and 3D graphics library, which run at 640x480 VGA with 16 colors.

**Comment by hseiken** [comment]
Too bad templeOS looks like the brainchild of a fundamentalist inviting armageddon. Also, the author says he's the 'smartest programmer who's ever lived and chosen to make God's temple (nevermind there's actually at least 50 recognized gods in 2018 so which one does he refer to?).

If TiC80 never supported this OS, I don't think it would be a bad thing...the number 1 way to end terrorism is to not support it. The OS technical aspects seem interesting despite it's origins, however. 

Also it's quite hilarious how it's worded on the site: "All content owned by Terry Davis and is in public domain."  Quite a contradictory statement if ever there was one.  

/critique of OS & author that has nothing to do with TiC80

**Comment by frenetic** [comment]
@rudolfolah Im not sure TempleOS has enough zealots to test/use TIC80.
But you, or anyone else, are always welcome to contribute.

**Comment by nesbox** [comment]
It doesn't:)
