### ISSUE TITLE
spr Color Remap option

### ISSUE THREAD

**Issue by novemberisms** [nesbox/TIC-80#649]
It would be extremely helpful if `spr` came with an option to remap drawn sprite colors on the fly. 

something like `spr( id, x, y, alpha, scale, flip, remap_table )`
where `remap_table` is a lua table
it will draw the sprite, but all colors corresponding to the keys in the remap_table will be changed to the values in the remap_table

for instance, a remap table of `{ [1]=5, [3]=7}` will draw the sprite, but all pixels of color 1 will be changed to color 5, and all pixels of color 3 will be redrawn as 7. This occurs after the alpha transparency filter.

Applications would be for flashing sprites red when taking damage, or having different swords have different materials simply by specifying a remap table.

I'm currently making a Legend of Zelda Breath of the Wild demake, and would really appreciate this functionality. Instead of having many different sprites with slightly different colors for the enemies and weapons, I could save on sprite space and have a lot more kinds of materials and enemies.

**Comment by nesbox** [comment]
try to use `pal(c0,c1)` function from the _Snippets_ before sprite drawing
https://github.com/nesbox/TIC-80/wiki/code-examples-and-snippets#palette-swapping

**Comment by novemberisms** [comment]
This solved my issues completely! Thank you!

I just wish there was documentation on the significance of 0x3FF0, the palette map. It only appears on the RAM layout, but there's no description of what it does. If I had known I wouldn't have bothered you :P
