### ISSUE TITLE
Windows Build problems

### ISSUE THREAD

**Issue by fr500** [nesbox/TIC-80#650]
Hi

I'm considering starting a libretro port, so as a first step I'm trying to build standalone, but I'm stuck at 

```
In file included from src/tic.c:34:0:
src/machine.h:27:10: fatal error: blip_buf.h: No such file or directory
 #include "blip_buf.h"
```

I have found a few referecens and libraries, do I need to build this library first?

**Comment by nesbox** [comment]
Hi,

you have to pull `3rd-party` submodule and setup include path to `3rd-party/blip-buf`

here is build instructions https://github.com/nesbox/TIC-80#windows
