### ISSUE TITLE
Tiny font in the Code Editor

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#652]
add font switch button to the toolbar

**Comment by nesbox** [comment]
how it looks
![screen](https://user-images.githubusercontent.com/1101448/43667015-f25a8596-977e-11e8-9ddc-97ce0b4edbc4.gif)

**Comment by StinkerB06** [comment]
When will you release 0.70.0? It's been over half a year since 0.60.3 was released.

**Comment by nesbox** [comment]
In a week, I hope. Just one Issue left to close .70 milestone
