### ISSUE TITLE
Enable keyboard in landscape mode on Android

### ISSUE THREAD

**Issue by Spreit** [nesbox/TIC-80#660]

**Comment by nesbox** [comment]
don't know where to find a place for the keyboard in landscape mode

**Comment by noncom** [comment]
Good idea, but, yeah, that's not easy.. Maybe a smaller screen and a different (wider?) keyboard layout would do? An optional mode like that could be interesting.

**Comment by hseiken** [comment]
On screen keyboard would cover up the screen no matter what you do unless you scale down the TIC 80 output.  Not to mention, Androids don't have standardized keyboards (for instance, I use Hacker Keyboard) and they take up different real estate on the screen.  

The real solution is to use portrait until you get fed up and buy a real keyboard, especially if you're typing because touch keyboards aren't meant for any serious work and suck like a black hole's gravity field.

**Comment by hseiken** [comment]
Which is the more important bug to solve between these two, imo.  But I'm not in charge of the show.

**Comment by phedoff** [comment]
It's an old thread, but why not split tic-80's keyboard, put half of it to the left, the editor in the middle of the screen and the other half of the keyboard on the right hand side of the screen? That should work. And one could finally write an uppercase 'a' or 'z' with big thumbs (impossible for at least me to shift-a). 😃

**Comment by stevenfelix505** [comment]
If you want to use keyboard in landscape mode, please refer to [this link](https://github.com/nesbox/TIC-80/wiki/Hotkeys-Android)

**Comment by BrunoDSL** [comment]
Currently, I'm running into this issue where TIC-80 crashes when you have an external keyboard connected. If you run it without a keyboard connected, it opens...Only to crash when you connect a keyboard.

**Comment by nesbox** [comment]
@BrunoDSL what keyboard do you use? thanks

**Comment by phedoff** [comment]
Can't confirm a crash with Logitech K380 (TIC80 0.80.04 (8005)).

Btw: when will a more recent version of TIC80 be available on itch.io? They still have 0.80.03 (8003).

**Comment by nesbox** [comment]
> Btw: when will a more recent version of TIC80 be available on itch.io? They still have 0.80.03 (8003).

The version will be updated after release, 0.90 still in development and we have 85 opened issues https://github.com/nesbox/TIC-80/projects/2

**Comment by BrunoDSL** [comment]
> @BrunoDSL what keyboard do you use? thanks

Logitech K230. Also tested with a no-name tablet case keyboard (listed as GAIA USB Keyboard).

**Comment by BrunoDSL** [comment]
I was able to test with another phone similar to mine but with a lower Android version (Moto G4 Play running Android 7.1. Mine is running 10) and, external keyboard works there... Except it has to be "up" in landscape mode. If you click the button row to lower it, TIC-80 stops responding to keyboard input. Mouse still works though.

**Comment by meyerdg** [comment]
I have a Bluetooth keyboard for my tablet, but I can't even use that if I'm in landscape mode. Games will take input but the command line and editors ignore everything.

**Comment by phedoff** [comment]
Is the virtual (android) keyboard visible? Like @BrunoDSL wrote: it has to be up or the kb won't react.

**Comment by BrunoDSL** [comment]
> Is the virtual (android) keyboard visible? Like @BrunoDSL wrote: it has to be up or the kb won't react.

The way I made the keyboard work is not the best, but it could work until it's updated.
This was tested on the latest version of TIC-80, which you have to download from the releases page, as whoever is in charge of the Android version has not updated the Play Store version yet.

- Start TIC-80 with the phone in portrait mode.
- Press Esc to leave out of Surf.
- You'll see a keyboard icon at the bottom. Tap it.

After you do that, you can turn the phone in landscape mode and it will recognize the keyboard. The landscape keyboard will also appear in case you're not using an external one.

Also, there's the annoyance. Even if you bring the keyboard up using a shortcut, TIC-80 won't respond to any input unless that keyboard icon is tapped.

**Comment by phedoff** [comment]
in 0.90-dev the keyboard works in landscape mode w/o the virtual kb having to be open (start app, tap kb-icon once - virtual keyboard shows up, rotate phone to landscape mode, pressing a key on the bluetooth keyboard makes the virtual keyboard disappear), so it works as desired, maybe you should use this version.

**Comment by BrunoDSL** [comment]
> in 0.90-dev the keyboard works in landscape mode w/o the virtual kb having to be open (start app, tap kb-icon once - virtual keyboard shows up, rotate phone to landscape mode, pressing a key on the bluetooth keyboard makes the virtual keyboard disappear), so it works as desired, maybe you should use this version.

I don't have a PC I run TIC-80 from and there are no built apks for 0.90-dev. Even if I had a PC, there are no instructions for building the APK.

**Comment by phedoff** [comment]
I too don't have the pro version, because it won't be released until all issues are fixed (see above), but you can get the dev version [here](https://github.com/nesbox/TIC-80/actions/runs/755745452) if your question was, where to get it from. O_o

**Comment by nesbox** [comment]
8c22d63 changes:
- hardware keyboard automatically works in the both portrait/landscape modes
- software system keyboard appears when you tap this button (portrait only)
![image](https://user-images.githubusercontent.com/1101448/123815173-ee863e00-d8fe-11eb-8500-64320836f97f.png)
- internal TIC keyboard displayed in all other cases (portrait only)
