### ISSUE TITLE
0.70.1 pro on Android: back button broken

### ISSUE THREAD

**Issue by BraininaBowl** [nesbox/TIC-80#668]
Since the 0.70.1 update, tic-80 no longer reacts to the back button on my Android 8.1.0 OnePlus 6.

**Comment by fadookie** [comment]
For me the back button seems to work to exit from a demo cart or the default hello world, but if I create a new cart and run it I get stuck in run mode forever and the back button doesn't work.

**Comment by fadookie** [comment]
Possible dupe of https://github.com/nesbox/TIC-80/issues/717

**Comment by nesbox** [comment]
fixed with the PR #975
