### ISSUE TITLE
The software keyboard availability in apps

### ISSUE THREAD

**Issue by noncom** [nesbox/TIC-80#670]
The new software keyboard is a brilliant addition to the computer! It is in many ways much better than any native Android keyboard for use with TIC-80. However, the keyboard is not available from within applications. For example, there's the `TIC-Edit` available among the `Tools` preinstalled with TIC-80, but it is completely unusable since all that the Android version is coming up within the app, is the joystick. 

So I think that it would be nice to have a command that allows a particular application to request either the keyboard or the joystick to be displayed to the user. And it could also be useful to be able to manually switch between the two from the GAME MENU, somewhere aside GAMEPAD CONFIG.

**Comment by nesbox** [comment]
I think it's #1561 dup
