### ISSUE TITLE
Android bluetooth keyboard problems

### ISSUE THREAD

**Issue by noncom** [nesbox/TIC-80#671]
I am trying to use TIC-80 with an external Android bluetooth keyboard and getting all sorts of weird behavior from it:

- The cursor keys work OK
- The letter keys in the console only work if I hold either `Control` or `Alt/Option`. If I release the modifier key while still holding a letter key, it sticks, and the letter continues to type in until I press the modifier key and the letter key again
- The letter keys in the Code Editor only type a letter only exactly in the situation when the letter repeat is produced in the previous point. That makes it clear that the input in the Console and in the Code Editor behaves differently which only adds to the weirdness.
- I did not manage to make the `Enter` or `Backspace` keys work
- The F keys don't do the switching between the IDE windows. Instead I have found that the `Alt/Option + NUM` combination works as if an F key with the appropriate number key was pressed. Say, `F2` action is achieved with the `Alt/Option + 2` combination (as described in the manual)
- The ABXY (`AZSX` on the keyboard) keys on a joystick during a game also only work with the `Control` or `Alt/Option` modifiers
- Probably there are more strange things, but that's what I've not yet discovered

My Android system is 6.0.1 and the bluetooth keyboard I'm using is quite popular in its class: https://market.yandex.ru/product/10505818

It very much adds to the disappointment that it works perfectly within LIKO-12 or any other Andoird application. I would love to see it working with TIC-80 too!

**Comment by fmaida** [comment]
I can confirm this issue on my Amazon Fire HD 10 with a Logitech K380 keyboard.
I shoot this very short video:

https://youtu.be/Qh4uppjo2GM

**Comment by nesbox** [comment]
@fmaida I created an update, pls check the latest version...

**Comment by fmaida** [comment]
Thank you. I can now confirm that the bluetooth keyboard is working properly.

**Comment by MrPelucaa** [comment]
In wich version did this get fixed? Im getting the exact same problem on my bluetooth keyboard
