### ISSUE TITLE
TIC-80 slows down Xorg sporadically

### ISSUE THREAD

**Issue by different55** [nesbox/TIC-80#672]
Left TIC-80 running on my PC last night, woke up this morning and Xorg was taking up 100% of one of my cores and everything was chugging along at maybe 10-15FPS. I did a quick Google search that got me nowhere, then started shutting down programs to try and find a cause. Soon as I saved my cartridge and shut down TIC-80, my desktop was perfectly responsive again.

I'm running Ubuntu 18.04, desktop is GNOME, I'm not sure what other info you might need to track this down but just let me know what I can do.

**Comment by different55** [comment]
Looks like it doesn't appear to be a gradual slowdown. I stepped away from my computer for 10-15 minutes and when I got back everything was nice and choppy. Closed and reopened TIC-80 and everything's good again.

**Comment by vitaly-pushkar** [comment]
I have the same issue, actually. If TIC-80 is left open for more than 30 minutes - it causes the Xorg to consumer 100% of one core. I am on Ubuntu 19.10 with GNOME

**Comment by nesbox** [comment]
Could you please test the latest dev build?
Seems the issue has been fixed recently, you can download it here https://builds.tic80.com/master/2020.04.04/linux

**Comment by different55** [comment]
Had it running for 2 hours now, still smooth sailing.

**Comment by nesbox** [comment]
thanks, closing then
