### ISSUE TITLE
Sprite and map editors use color 15 from current cart instead of config

### ISSUE THREAD

**Issue by db0z** [nesbox/TIC-80#677]
This seems to be the only color affected (and only in some places). Feels like an inconsistency.
![screen](https://user-images.githubusercontent.com/25254726/44116339-f1e7214e-a018-11e8-924c-6459b601c8ad.gif)

**Comment by AnastasiaDunbar** [comment]
I see nothing wrong here. Cartridges are supposed to have their own color palettes for maps and sprites.

**Comment by nesbox** [comment]
This is because I draw UI on the background and the sprites with the cursor in OVR mode which has only cart palette. Don't know how to fix this at the moment.

**Comment by nesbox** [comment]
fixed in .80
