### ISSUE TITLE
Add back International Keyboard Layout

### ISSUE THREAD

**Issue by GameExpress** [nesbox/TIC-80#680]
Hello!

On the latest TIC-80 update (0.70.1), TIC-80 stopped using the keyboard layout I was using. It is now using the American keyboard layout which I'm not used to! I literally put a '@' every time I try to put a quote. I have no idea why you changed that!

Please fix it!!!!

**Comment by nesbox** [comment]
duplicate #655

**Comment by GameExpress** [comment]
Yep I just found it and was about to delete it
