### ISSUE TITLE
Touch=Mouse support for html5 exports?

### ISSUE THREAD

**Issue by darkgriffin1986** [nesbox/TIC-80#685]
The html5 games can load up on mobile phones such as android devices, that part appears to work quite well.  

With the wide screen size, I found it works best in landscape, but many browsers support that rotation to view wide web based content out of the box.

However, touching the screen does not appear to result in any "clicks" being registered in TIC-80.  So even a mouse based TIC-80 game can't be played in this manner.  (I am on Samsung S8+, using firefox.  I have not tested this with my own code yet, only noticed that the few games I tried around the arcade sites didn't work on the phone, while on my PC I can click to start the game fine.)

It would be great if touching the screen/browser element counted for "clicking" on the TIC-80 game.  I realize this would not be as "precise" as the real mouse input, but I think designing around the challenge could make for some great mobile friendly tic-80 games.  This feature could be a real "leg up" over some of the alternative virtual consoles out there.

This could allow us to develop TIC-80 "mouse input supported" games, and players on mobile devices could play them by simply using their web browsers to load/play the game.  It would greatly open the door for distributing html5 TIC-80 games as well, as a lot of arcade sites value mobile input support.

If it's added in, I would recommend against supporting multi-touch or any advanced stuff like swipes.  To keep with the spirit of the TIC-80 "time period" style, it should just allow mouse clicking just like a pc mouse, of course. :)

**Comment by BraininaBowl** [comment]
I know this is an oldie, but I'd really like this fix/addition. I mostly distribute my games on itch.io and being able to play in the browser would be very helpful.

**Comment by nesbox** [comment]
Touch input works in the browser, try to test on this game for example https://tic80.com/play?cart=978.
