### ISSUE TITLE
Add OVR() palette to the sprite editor

### ISSUE THREAD

**Issue by Spreit** [nesbox/TIC-80#693]
But there is no space in ram to store it

**Comment by planer28** [comment]
You just wrote to add something, and said there is no space to?
You can store the pallete in code, just make it in the pallete editor and copy it into a string.

**Comment by potato25** [comment]
How will this workout with recent BPP added ? It was added here : https://github.com/nesbox/TIC-80/pull/1099

**Comment by rahul625** [comment]
One of the solutions is you add 2 buttons to left of palette , first button for TIC() palette and 2nd for OVR() palette . Just a thought :) 
![Screenshot_2020-07-23-10-20-04-130_com nesbox tic](https://user-images.githubusercontent.com/47915829/88253159-85e61880-ccce-11ea-91dd-85e74592da91.png)
![Screenshot_2020-07-23-10-20-51-829_com nesbox tic](https://user-images.githubusercontent.com/47915829/88253167-8ed6ea00-ccce-11ea-8fbb-c81e3e0e76b9.png)

**Comment by nesbox** [comment]
Added **Advanced Mode** button where OVR palette can be selected, also flags and BPP mode.
![screen](https://user-images.githubusercontent.com/1101448/90265349-21485480-de5b-11ea-98fd-1725248f6d18.gif)

**Comment by BraininaBowl** [comment]
Does this overrule/replace the copy/paste palette functionality?

**Comment by nesbox** [comment]
> Does this overrule/replace the copy/paste palette functionality?

No, this doesn't, copypaste buttons moved to the right near rgb sliders.
