### ISSUE TITLE
Cannot compile TIC-80 on PocketCHIP

### ISSUE THREAD

**Issue by TaTooKa** [nesbox/TIC-80#697]
Hi,

I have an outdated version of TIC-80 on my PocketCHIP and wanted to update it. Since there's no arm binary download, I'm trying to compile from source.

I'm running ./build.sh with target 8 (`chip-lto`), and am getting this error:

```
gcc `pkg-config --cflags gtk+-3.0` `pkg-config --cflags gtk+-3.0` src/studio.c s
rc/console.c src/run.c src/ext/file_dialog.c src/ext/md5.c src/ext/gif.c 3rd-par
ty/SDL2_net-2.0.1/SDLnet.c 3rd-party/SDL2_net-2.0.1/SDLnetTCP.c 3rd-party/SDL2_n
et-2.0.1/SDLnetselect.c src/fs.c src/tools.c src/start.c src/sprite.c src/map.c
src/sfx.c src/music.c src/history.c src/world.c src/config.c src/code.c src/dial
og.c src/menu.c src/net.c src/surf.c src/system/chip.c src/tic80.c src/tic.c 3rd
-party/blip-buf/blip_buf.c src/jsapi.c src/luaapi.c src/wrenapi.c 3rd-party/dukt
ape-2.2.0/src/duktape.c src/html.c -O3 -Wall -std=gnu99 -D__CHIP__ -I3rd-party/l
ua-5.3.1/src -I3rd-party/zlib-1.2.11 -I3rd-party/giflib-5.1.4/lib -I3rd-party/SD
L2-2.0.7/include -I3rd-party/sdl-gpu/include -I3rd-party/wren-0.1.0/src/include 
-I3rd-party/moonscript -I3rd-party/fennel -I3rd-party/blip-buf -I3rd-party/dukta
pe-2.2.0/src -I3rd-party/SDL2_net-2.0.1 -Iinclude -L3rd-party/pre-built/arm `pkg
-config --libs gtk+-3.0` -lSDL2 -lsdlgpu -llua -lwren -lgif -ldl -lm -lpthread -
lrt -lz -lGL -flto -o bin/tic80              
                                   
src/system/chip.c: In function 'processKeyboard':                               
src/system/chip.c:125:27: fatal error: ../keycodes.c: No such file or directory
   #include "../keycodes.c"                                                     
                           ^                                                    
compilation terminated.
``` 

(I previously ran it with option 1, `install packages` to get all required libs, and also cloned the repo with `recursive` option to have the 3rd party libs). 

In case there's no easy solution for this, I see that the latest version in **releases** with a **chip** tar.gz is `0.60.3`. Is there any way to get a binary download for the latest version?

**Comment by sreuter** [comment]
@TaTooKa I successfully compiled the latest master on the PocketCHIP, but it's 10x slower compared to the prebuilt 0.60.3 release. I assume I missed a flag or something so some acceleration is missing, or it's related to this: https://itch.io/t/399679/new-version-runs-slowly

**Comment by nesbox** [comment]
@sreuter try to compile with `-DCMAKE_BUILD_TYPE=Release` flag
