### ISSUE TITLE
Keyboard layout still not fixed

### ISSUE THREAD

**Issue by GameExpress** [nesbox/TIC-80#701]
The keyboard layout I'm using (Croatian) still doesn't work (on version 0.70.2)
Now it's even worse.
I cannot put these characters: { } [ ] : ; | \ + =
Please fix this. This is a critical issue as I cannot create and modify arrays, nor can I do basic arithmetic.

**Comment by nesbox** [comment]
it's strange
what about other keys like `Y` `C` `X`, do they work properly?

**Comment by nesbox** [comment]
so, I reproduced it and found the solution, will release .70.3 soon :)

**Comment by GameExpress** [comment]
yes, other keys work fine.

**Comment by nesbox** [comment]
I made some fixes, could you please test it [tic80_kbd_fix.zip](https://github.com/nesbox/TIC-80/files/2319527/tic80_kbd_fix.zip)
Thanks

**Comment by GameExpress** [comment]
Ok, so it is fixed.
But I forgot to tell you that the number row is incorrect.
The number row still isn't using the layout I'm using.
And the comma, dot, and minus sign when holding shift work wrong.
It should be: ; : _
But it's: < > _
And there's a key right of the left shift key that puts '<' ('>' on shift)
And I still cannot use these keys: ; : + =

**Comment by nesbox** [comment]
ok, thanks, I'm going to make another one fix in next 30 min
pls keep in touch

**Comment by nesbox** [comment]
Please check this one [tic80_kbd2_fix.zip](https://github.com/nesbox/TIC-80/files/2320036/tic80_kbd2_fix.zip)
Thank you

**Comment by nesbox** [comment]
close as #655 duplicate
