### ISSUE TITLE
Save carts on browser

### ISSUE THREAD

**Issue by Risike** [nesbox/TIC-80#702]
Hi,

Sorry for my bad english.

I would like to know if it's possible to save carts when you use TIC to create a game on a browser on my own web server.

Thanks !

**Comment by nmmarzano** [comment]
Hi Risike! While I haven't been active lately and don't know if anything like what you're asking for has been implemented beyond exporting the cart image and uploading it to distribute it, I don't think this is the place to be asking such questions as it's a section for reporting issues with the project and the people frequenting this place might not be ready or willing to answer. 

If you check the readme in the welcome page, you'll find a link to the project's discord server under "Community" where you could ask questions related to the use of the console. I hope you can find help there!

**Comment by nesbox** [comment]
@Risike yes, use `save game.tic` command and it will be saved to the browser cache.
