### ISSUE TITLE
Cannot input '[' and ']' on 0.70.3

### ISSUE THREAD

**Issue by GameExpress** [nesbox/TIC-80#707]
On my keyboard layout (Croatian), to input a **[** I need to press "ALT GR" + "F".
But if I press that, then the "find" toolbar shows up and the **[** isn't even inputted.
Same thing for the **]** where I need to press "ALT GR" + "G" and it opens the "go to" toolbar

**Comment by GameExpress** [comment]
And when trying to input **{** (ALT GR + B) it doesn't input it until I let go of ALT GR.
Same thing for: **\** (ALT GR + Q) **|** (ALT GR + W) and **@** (ALT GR + V)

**Comment by nesbox** [comment]
Please test [tic80_dirty_fix.zip](https://github.com/nesbox/TIC-80/files/2320472/tic80_dirty_fix.zip)

**Comment by GameExpress** [comment]
now the "ATL GR keys" are working perfectly.
But now the keyboard layout is broken again...

**Comment by nesbox** [comment]
I installed a Croatian layout to the system and checked all the keys, so I can input everything, letters, numbers, and signs. Maybe something is different when you use real keyboard :(
With what keys you do you have problems?

**Comment by nesbox** [comment]
just checked
```
1234567890'
qwertzuiop
asdfghjkl
yxcvbnm,.-
```
with Shift
```
!@#$%^&*()"
QWERTZUIOP
ASDFGHJKL
YXCVBNM<>_
```

with right Alt
```
~^`\|[]@{}<>
```

**Comment by Ghegs** [comment]
For me on my Finnish keyboard: 

0.70.3: Keyboard mapping issues fixed, but with characters that require ALT GR (like [ and ] ) the character isn't entered until I let go of ALT GR.

0.70.5: Keyboard mapping is broken, but I can enter ALT GR -characters without releasing ALT GR and for those characters the mapping is correct.

**Comment by GameExpress** [comment]
I just installed 0.70.5 and the same thing is happening

**Comment by GameExpress** [comment]
yep, it worked perfectly.
There was only 1 problem that when inputting pressing ALT GR + F or G it would input the character but it would also open the "find" or "go to" menu

**Comment by Ghegs** [comment]
60.3 works perfectly for me too, even ALT-GR -characters work perfectly.

**Comment by nickifr** [comment]
Yes, 0.60.3 worked flawlessly here as well

**Comment by nesbox** [comment]
Please, someone...
[tic80_kbd_fix.zip](https://github.com/nesbox/TIC-80/files/2321290/tic80_kbd_fix.zip)

**Comment by GameExpress** [comment]
The layout is finally fixed, but ALT GR keys aren't working again.

**Comment by GameExpress** [comment]
ALT GR keys aren't working, but the layout is fine

**Comment by nickifr** [comment]
With that one on QWERTZ, ALT-GR and Shift is working on everything as it should, but in some cases the symbols you should get by not pressing shift aren't entered. (pressing Shift-< results in ">" as it should, but pressing < does not result in "<" for some reason; I also can't type "#", the whole numpad doesn't work, I can't input "+" or "^")

**Comment by nesbox** [comment]
Please... [tic80_altgr_fix2.zip](https://github.com/nesbox/TIC-80/files/2321335/tic80_altgr_fix2.zip)

**Comment by nickifr** [comment]
That one's working perfectly! Everything, even shift and alt-gr, is doing precisely what it should on QWERTZ!

**Comment by Ghegs** [comment]
Same here!

Except for one small thing: I can't enter the character < in console, yet it works fine in editor. Not sure if I'd ever need it in console, but thought it worthy of mention.

**Comment by GameExpress** [comment]
ok, it's fixed, just that I cannot enter '\' because when pressing ALT GR + Q it asks me if I want to exit. But it's fine since I probably won't need that key...
