### ISSUE TITLE
Can't input some chars on TIC-80 v0.70.5 (italian keyboard)

### ISSUE THREAD

**Issue by naufr4g0** [nesbox/TIC-80#710]
With old TIC releases I have no keyboard layout issues at all, but with new ones I can't input a lot of chars like '+' , '-', '*', '=' ...  and some other chars are moved.
Old releases works great with my italian keyboard, but now is a mess.
Why not simply restore old keyboard layout files?

**Comment by AnastasiaDunbar** [comment]
I've discussed about this #709 but there's already an open issue about it here: #655

**Comment by naufr4g0** [comment]
I read the discussions on the links you posted, but It seems like there are no solutions yet!

**Comment by nesbox** [comment]
fixed here #707
