### ISSUE TITLE
Scrolling in Chrome is inverted

### ISSUE THREAD

**Issue by nalquas** [nesbox/TIC-80#713]
Scrolling in Chrome (68) isn't working correctly, always scrolling in the opposite direction you want it to.
If you try to scroll up, TIC-80 scrolls down. If you try to scroll down, TIC-80 scrolls up.

This problem does not happen on Firefox (61).

I tried Edge as well - In Edge, scrolling in TIC-80 isn't or is only partially registered, making scrolling by mouse impossible.

TIC-80 version at the time of writing: 0.70.5

**Comment by RobLoach** [comment]
This is working just fine for me...

Ubuntu, Chromium 76.0.3809.87
Ubuntu, Firefox 68.0.1

**Comment by nesbox** [comment]
In .80 all is ok.

**Comment by ChildishGiant** [comment]
For me in the browser scrolling up moves toward the bottom, scrolling down moves towards the top.

0.80.1344 on tic80.com 
Chromium (Including new edge) & Firefox
Windows 10

**Comment by ChildishGiant** [comment]
This is still prevalent in 0.90.1723 (9c38a80)
In the sprite editor, tracker and code editor it's all inverted.

**Comment by nalquas** [comment]
Can confirm, I'm still having this issue on Firefox 91.0 (Manjaro).

**Comment by TextBox75** [comment]
Still having issues with this, please fix.
