### ISSUE TITLE
The hard limit for the character count is not accurate when editing code in an external file

### ISSUE THREAD

**Issue by novemberisms** [nesbox/TIC-80#715]
So all I have in the code editor is this: `dofile("tests.moon")` and I'm editing tests.moon in SublimeText.

When editing code in an external file, the hard limit for the character count is not accurate. The limit is supposed to be 65536 characters, but if I make `tests.moon` more than exactly `63283` characters, (2253 characters under the limit), TIC complains and asserts that the code is larger than 65536.

But if I copy and paste the contents of `tests.moon` into the TIC code editor, it works just fine.

**Comment by nesbox** [comment]
this is can be because of use `\r\n` in your `tests.moon` instead `\n`

**Comment by novemberisms** [comment]
This is definitely the case. 

Maybe a future version of TIC-80 can automatically detect `\r\n` line endings and trim them down to `\n` before loading in an external file?

**Comment by nesbox** [comment]
Removed `dofile()` because a lot of misunderstanding how to use it, how to export cart with it.
Also, we always have text carts support.
Done here d7c7364.

**Comment by nesbox** [comment]
Therefore, text cart format now enabled by default in the non-pro version, done here cd91711.
