### ISSUE TITLE
Cannot exit a cart if it was ran with CTRL,+R

### ISSUE THREAD

**Issue by Spreit** [nesbox/TIC-80#717]
At least on Android

**Comment by nesbox** [comment]
what about BACK button? does it work?

**Comment by Spreit** [comment]
Back button is the only option now and it doesn't work

**Comment by carlsmith** [comment]
To be a bit clearer, I'm finding that the Back button works as the Escape key in all the usual contexts, except if you use Ctrl-Enter on the (builtin) soft keyboard to run a cart. The keybinding works to launch the cart, but once you're in the game, hitting Back does nothing. If you run the cart with the `run` command (from the shell), the Back button works as expected.

**Comment by nesbox** [comment]
Closing duplicate of #668
