### ISSUE TITLE
SCN() vs scanline()

### ISSUE THREAD

**Issue by jminor** [nesbox/TIC-80#720]
The scanline function is `scanline(_)` in the docs, but in wren it is `SCN(_)`. In a quick test it looks like lua accepts either one. This should either be the same in all of the languages, or documented as different. Also the syntax highlighter highlights "SCN" but not "scanline". Personally I like SCN which matches with TIC and OVR, but that's just me :)

If you pick which one, I could make a pull request with the fix.

**Comment by nesbox** [comment]
I left `scanline()` for backward compatibility, pls use the new name `SCN()`

**Comment by nesbox** [comment]
updated wiki

**Comment by jminor** [comment]
Thanks :)

**Comment by StinkerB06** [comment]
@nesbox Why should we care? scanline() is still a pretty good thing for gradients and wavy effects.
