### ISSUE TITLE
IOS port problems

### ISSUE THREAD

**Issue by otaviosoato** [nesbox/TIC-80#727]
Hi guys!

So, I had problems on the iOS port by https://github.com/brunophilipe/TIC-80 with System keyboard and in the "Play Mode".

System Keyboard: I can't add new line in the code editor and also can't execute a command line.
Play Mode: I can't exit! haha

Im using iPad Pro 12.9 latest iOS version.

Best regards!
Otavio Soato

**Comment by joey-suplari** [comment]
I am having the same issue as @otaviosoato.

**Comment by joshgoebel** [comment]
@nesbox Do we want to offer support for the iOS version here in this repo or should we refer these types of issues to the port authors?

**Comment by nesbox** [comment]
I think we will add iOS support in this repo one day :)
