### ISSUE TITLE
Blue screen on Android device.

### ISSUE THREAD

**Issue by CereEnder** [nesbox/TIC-80#730]
Device Pocophone F1, Android Oreo.

Blue screen, or mask, instead of the original colours.
If I go out and enter again without killing app, it shows black screen.

**Comment by nesbox** [comment]
#657 duplicate
about 'blue screen' https://github.com/nesbox/TIC-80/issues/657#issuecomment-412490184
> The blue tint can be fixed by turning on "disable HW overlays" in development settings.
