### ISSUE TITLE
online play for turn based game

### ISSUE THREAD

**Issue by thisajh** [nesbox/TIC-80#735]
possible to implement network play for turn based games?  useful for simple board or card game experiments.  either send data between players directly or using a server, or possibly use a shared spreadsheet on google docs or drive?

**Comment by Meowlit12** [comment]
I think this has been agreed to be out of scope.
https://github.com/nesbox/TIC-80/issues/243#issuecomment-329758709

**Comment by RobLoach** [comment]
While it may be out of scope, it may be an option for the TIC-80 libretro core through [Netplay](https://retroarch.com/?page=netplay) and (ab)using `pmem`. Saved states are a dump of the current pmem, so in theory, you could connect to a netplay session, and use the same persistent memory for a multiplayer game.

**Comment by nesbox** [comment]
dup of #457
