### ISSUE TITLE
Floating point exception tic-80 on armv7l 

### ISSUE THREAD

**Issue by cuu** [nesbox/TIC-80#736]
Just compiled the tic-80 on GameShell, a arm based device, Quad-core Cortex-A7 CPU(just show info, not an ad)

Got Floating point exception

anyone can give me a hint to fix this?
Thanks very much

**Comment by sreuter** [comment]
I just ran into the same issue on the PocketCHIP.

@nesbox Any idea what could cause this?

**Comment by sreuter** [comment]
@cuu Loading it from the graphical terminal instead of from remote/SSH has fixed things for me. So it seems to be a bit of a misleading error and rather depends on the environment it's launched in.

**Comment by cuu** [comment]
I am gonna close this issue now
I fixed it by running into gdb ,I remember that's just a div zero cause the Floating point exception
it's a simple error that gdb can handle it well
