### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by Natureshadow** [nesbox/TIC-80#737]
Hi,

I intend to package and maintain TIC-80 for the Debian distribution, for use in the Debian Edu software suite, among others.

There is one issue: TIC-80 depends on some librearies als odeveloped by nesbox, e.g. blip-buf, that are merged into the git repository as a submodule, not not released separately. They are also not part of any source distribution, because the only source distribution to find is the automatically exported tag from GitHub.

If these libraries are only used in TIC-80 and always released together with TIC-80, can you please provide a source tarball containing them? If not, can you please release these libraries separately, so we can package them as well?

Please do not build a source tarball with the whole 3rd-party submodule, because that also contains code copies of external libraries already available in Debian.

**Comment by nesbox** [comment]
Hi,

The Blip_buf library was developed by Shay Green and hosted on Google Code website https://code.google.com/archive/p/blip-buf/ and here is Github version https://github.com/nesbox/blip-buf cloned by me.

Unfortunately, I don't uderstand what should I do, sorry...

**Comment by Natureshadow** [comment]
The easiest thing would be to create a source tarball containing the 3rd-party directory, and uplaoding that along with the binaries.

**Comment by Natureshadow** [comment]
Also, the issue is not new and you alread yreacted to it a while back: https://github.com/nesbox/3rd-party/issues/1

**Comment by xordspar0** [comment]
> The easiest thing would be to create a source tarball containing the 3rd-party directory, and uplaoding that along with the binaries.

Would it be enough to just tag a release in the Github repo of the library? Then Github would make a source tarball for that version.

**Comment by Natureshadow** [comment]
GitHub does not include submodules. So no.

**Comment by xordspar0** [comment]
I mean make a release of the submodules. For example, make a release of blip-buf at the commit that the submodule is pointing to.

**Comment by nesbox** [comment]
Already distributing as deb package
