### ISSUE TITLE
Build with default VS2017 instruction is incompatible with Windows 7

### ISSUE THREAD

**Issue by SagePtr** [nesbox/TIC-80#743]
Instruction says:
```
cmake -G "Visual Studio 15 2017 Win64"
```
The resulting build is incompatible with Windows 7 because "GetSystemTimePreciseAsFileTime" function is not found in Kernel32.dll (it requires Windows 8 at least)
It's due to this Duktape issue: https://github.com/svaarala/duktape/issues/1663

To make things compatible, for example I could generate solution with different toolset, which fallbacks to Windows XP functions:
```
cmake -G "Visual Studio 15 2017 Win64" -T v141_xp
```
Probably this information should be added in readme, or CMake configuration should be changed to use compatible toolset by default.

**Comment by nesbox** [comment]
Added Windows XP support, fixed .exe icon, we have 4 builds now: `win32, win64, win32-xp, win64-xp`
f81648d

**Comment by c1oudsky** [comment]
Still experiencing this issue on windows 7 with 0.90.1723
