### ISSUE TITLE
No longer works on winXP?

### ISSUE THREAD

**Issue by eglavas** [nesbox/TIC-80#752]
Is windows xp no longer supported?

0.60.3 is the last version that works.

**Comment by StinkerB06** [comment]
I hope NesBox did it because Microsoft discontinued XP ~4 years prior.

**Comment by nesbox** [comment]
TIC supports XP, I think there is a problem with SDLGPU library which doesn't work without OpenGL drivers. Will try to fix this in .80

**Comment by wadetb** [comment]
One thing I noticed is that `GetSystemTimePreciseAsFileTime` is used by the JavaScript runtime but is Win8+.

**Comment by nesbox** [comment]
Closing as a duplicate of #743
