### ISSUE TITLE
How the heck do I use the map() remap callback ?

### ISSUE THREAD

**Issue by PseudoCactus42** [nesbox/TIC-80#753]
I've been searching for a while now, but I can't seem to find a descript explanation on how I'm supposed to use the remap callback function. I've found examples of ways in which it can be used, but none of them really explain what they're doing, apart from a block of code. I seem to be really bad at understanding other people's code, especially if it lacks comments, so I was hoping that somebody here might be able to explain it to me.

For example, say I had three water tiles, and I wanted to animate them on the map: How would I go about doing so? Please explain any maths you include as well as any not otherwise obvious code included.

**Comment by AnastasiaDunbar** [comment]
In JavaScript:
```js
function remap(tile,x,y){
	var outTile=tile,
	    flip=0,
	    rotate=0;
	if(tile===yourWaterfallTile){
		outTile+=Math.floor(gameTicks*speed)%frames;
	}
	return[outTile,flip,rotate]; //or simply `return outTile;`.
}
//Then you can do `map(0,0,30,17,0,0,-1,1,remap);`.
```

**Comment by StinkerB06** [comment]
Here's a Lua version of @AnastasiaDunbar's snippet:
```lua
--Note that `yourWaterfallTile`, `speed` and `frames` aren't defined here.
--This is up to you. The value of `speed` should be greater than 0 but less than or equal to 1.
gameTicks=0
function remap(tile,x,y)
	local outTile,flip,rotate=tile,0,0
	if tile==yourWaterfallTile then
		outTile=outTile+math.floor(gameTicks*speed)%frames
	end
	return outTile,flip,rotate --or simply `return outTile`.
end
function TIC()
	cls()
	map(0,0,30,17,0,0,-1,1,remap) --The `remap()` function is used here.
	gameTicks=gameTicks+1
end
```

**Comment by StinkerB06** [comment]
Added to the wiki:
https://github.com/nesbox/TIC-80/wiki/map/2cae6223992abc4ca3f2e94c3040cba087a923a5
I think you can close this issue now.
