### ISSUE TITLE
[Feature Request] Cartridge embedded in PNG export for easy sharing

### ISSUE THREAD

**Issue by ElfEars** [nesbox/TIC-80#755]
The ability to create a png with a .tic cartridge embedded and the game's f7 cover image displayed (and also subsequently easily being able to load it) would be extremely useful. 
A png image is much easier to share than a .tic file as nearly every website accepts .pngs (provided no compression is done) with very few accepting indeterminate file types. 
It also adds a visual element helping tic cartridges naturally stand out on webpages and in filesystem thumbnails and being able to easily distinguish between them.

Several similar fantasy consoles also have this feature and it is a very popular way to share creations.

**Comment by nesbox** [comment]
It can be done with LSB based image steganography I think.
Let's try :)

**Comment by zenith391** [comment]
why not use the [tEXt](http://www.libpng.org/pub/png/spec/iso/index-object.html#11tEXt) PNG chunk ? Althought it says it should not contains null characters, since it isn't meant for display this shouldn't matter much as the text string is not null-terminated.

However with this method, data will be lost if converting from PNG to any other image format.
But it has the added benefit of being way easier to implement.

**Comment by joshgoebel** [comment]
> why not use the tEXt PNG chunk ?

Some sites will strip this data as it's not relevant for display.

**Comment by nesbox** [comment]
I did some experiments with embedding a cart to png image on [png-test](https://github.com/nesbox/TIC-80/tree/png-test) branch.

Original `256x256` image (9 877 bytes):
![cover](https://user-images.githubusercontent.com/1101448/108511356-d9eec500-72d0-11eb-83d7-5343c599e108.png)

With embedded **BALMUNG** cart (80 663 bytes):
![out](https://user-images.githubusercontent.com/1101448/108511362-dce9b580-72d0-11eb-9d39-b686df3402b1.png)

Very pleased with the result, almost no difference is visible.
Also, we have to design a `256x256` cartridge template with a cover and game info now...

**Comment by SDMelipone** [comment]
Looks like an opportunity for a design contest. Having a simple, recognizable, and striking design could be an important part of TIC-80's visibility.

**Comment by nesbox** [comment]
Welcome if you have ideas :)

**Comment by Anrock** [comment]
Is there any specific requirements like size of the image, dimensions, some ares dedicated for user to draw on like redshift disks have?

**Comment by nesbox** [comment]
I think `256x256` with `240x136` cover inside is the main requirement.

**Comment by nesbox** [comment]
How the cartridge could look (WIP)

![image](https://user-images.githubusercontent.com/1101448/108850091-00c03a80-75f4-11eb-8040-b1cd1a7437dc.png)

**Comment by joshgoebel** [comment]
Could we put the cartridge "size" on the outside maybe?  Some calculation of # of banks used + code size, etc...

**Comment by borbware** [comment]
i like this idea very much! the wip cartridge has already a nice look.

some thoughts & questions:
- text "TIC-80" should be present somewhere
- maybe the TIC-80 mascot, too!
- pins at bottom instead of top?
- it would be nice to be able to decide the color of the cartridge, famicom style
- could one fit pro cartridges in 256*256 images as well?

**Comment by nesbox** [comment]
Some progress:
![image](https://user-images.githubusercontent.com/1101448/108880778-aafb8a80-7613-11eb-9e9e-082ff6b7ee00.png)
Thank you for the thoughts :)
Pro carts fit `256x256` without any problems.

**Comment by RobLoach** [comment]
Personally, I like the dark one the most. Keeping with the [Sweetie-16](https://lospec.com/palette-list/sweetie-16) color palette and feel is important.

**Comment by nesbox** [comment]
Me too :)
![image](https://user-images.githubusercontent.com/1101448/108883448-7fc66a80-7616-11eb-8cee-043e72482bf7.png)

**Comment by joshgoebel** [comment]
0.02:

- Do we really need to explain it's a `cartridge`?
- TIC-80, logo, and `tic80.com`... do we need ALL the above?
- Giving "TIC-80 cartridge" more prominence than the title and author name feels wrong to me
- I can't read "by Sintel" it's way too dark (accessibility contrast ratio is really bad)
- What about "embossing" the logo onto the cartridge itself (top left or right)?

Could we do more of a 3d treatment on the pins or something?  Most cartridges I'm familiar with the pins are on the inside (hidden inside the cartridge)... so is this more of a cartridge or more of an SD card thingy?

**Comment by RobLoach** [comment]
In regards to top versus bottom text, I actually enjoy the loader at the top most :wink: First one from https://github.com/nesbox/TIC-80/issues/755#issuecomment-784363180 .

**Comment by joshgoebel** [comment]
Ok maybe I shouldn't have said "doesn't matter"... but I think there is a lot of leeway here in "keeping with the brand" vs "must match the exact hex codes used elsewhere". :-)  We can keep with the brand without matching the colors 100%.  I'd say the hues and "getting close" is enough to preserve the brand.

> We could tweak the greys, but we should also apply that to the rest of the default palette too.

A palette designed for images on a website and proper accessibility is not necessarily the same palette you'd want in game.

I'm working on a quick mockup.

**Comment by nesbox** [comment]
>Do we really need to explain it's a cartridge?

I think yes, especially for people who sees it for the first time

> TIC-80, logo, and tic80.com... do we need ALL the above?

I think yes, it's increasing recognizability

> Giving "TIC-80 cartridge" more prominence (by space) than the title and author name feels wrong to me

Yes, we could call it `TIC-80 disk` here for example

> I can't read "by Sintel" it's way too dark (accessibility contrast ratio is really bad)

Agreed

> What about "embossing" the logo onto the cartridge itself (top left or right)?

I tried, but without success

It's just a **fantasy** cartridge for **fantasy computer**, we can imagine what we want :)

**Comment by joshgoebel** [comment]
@nesbox Is the actual underlying data using the entire 256x256 area?

**Comment by joshgoebel** [comment]
> Yes, we could call it TIC-80 disk here for example

That's nice... but I think a smaller font would also help with my actual issue of the prominence.

**Comment by RobLoach** [comment]
> Yes, we could call it TIC-80 disk here for example

Note that TIC-80 applications are mostly refered to as "cartridges" elsewhere, like "download cartridge" on the cart page, and even in the URL: https://tic80.com/play?cart=1625

**Comment by nesbox** [comment]
> @nesbox Is the actual underlying data using the entire 256x256 area?

yes, each pixel has 4 RGBA channels, so each pixel is a 4-byte value and I'm using 2-3 low bytes to encode cart data

**Comment by joshgoebel** [comment]
So someone altering their own cartridge later would be sort of difficult without destroying the data. :)

**Comment by nesbox** [comment]
Cart icon
![image](https://user-images.githubusercontent.com/1101448/108889823-ddaa8080-761d-11eb-8d19-d1c363b1f399.png)

**Comment by joshgoebel** [comment]
![108883448-7fc66a80-7616-11eb-8cee-043e72482bf7](https://user-images.githubusercontent.com/6473/108890897-1aee1e80-75dc-11eb-9c23-ddc19682ba84.png)

Ignore the details (like my attempt at the "cart" font) and try to focus on the bigger picture.  See if you think there is anything to like here.  I'm not a graphics persons but I tried to make a quick pass as a more 3D bottom.

**Comment by nesbox** [comment]
Looks good, I like it, thanks :)

**Comment by joshgoebel** [comment]
@nesbox What would be nice is if the cartridge was just a PNG file inside of the project that the "label" (title, author, etc) and title graphic is overlaid on top of... then it'd be easy for anyone to experiment with this later just by updating that PNG and recompiling.

**Comment by joshgoebel** [comment]
Or what if cartridges were shaped like TIC-80 itself? :-) 

![tic80_shape](https://user-images.githubusercontent.com/6473/108897072-b33bd180-75e3-11eb-87bf-96475543ff43.png)
![tic80_shape_white](https://user-images.githubusercontent.com/6473/108897075-b59e2b80-75e3-11eb-8ad5-90945b745dc6.png)

**Comment by joshgoebel** [comment]
I like the cartridge and website links on top best here: (thin font)

![tic80_shape](https://user-images.githubusercontent.com/6473/108900137-46c2d180-75e7-11eb-9bd0-69e15ea2937f.png)

**Comment by RobLoach** [comment]
I appreciate the idea of having it look like the logo, but out of all of them I like Alt Layout from https://github.com/nesbox/TIC-80/issues/755#issuecomment-784421075 the most so far. Keep It Simple Stupid :wink:

**Comment by joshgoebel** [comment]
![cart](https://user-images.githubusercontent.com/6473/108911641-855f8880-75f5-11eb-8f99-5548dfe8ec5b.png)

Ok, I need to stop. LOL.

**Comment by nesbox** [comment]
Let's choose between these two carts:


![image](https://user-images.githubusercontent.com/1101448/108979313-9662d500-769b-11eb-860f-518880c6a829.png)

![image](https://user-images.githubusercontent.com/1101448/108978786-0ae94400-769b-11eb-9b26-69da736c7122.png)

**Comment by borbware** [comment]
I'd leave the description text out, it would break with longer descriptions.

I've been bouncing between top and down pins, but finally, the subtle 3d effect sold me on the bottom pins. Any case, i like the word "cartridge" more than a "card" - it's been in use for the tic _cartridges_ before after all.

The monochrome tic logo is very classy! The arrow could be smaller, tho, it's making the lower part of the cartridge a bit too busy imo, at least in the bottom pins version.

**Comment by Anrock** [comment]
Aye for bottom-pinned version and cartridge. Btw, I think cartridge template shouldn't dictate screenshot and title areas and it's better to leave them blank (and withouth separator) so authors can be more creative with fonts and title position.

**Comment by joshgoebel** [comment]
@nesbox Is there a reason you lost the shadow on the pins?  It doesn't look quite right without that... the top of the pins would be in shadow from the cartridge housing...

(Re: "Tic-80 cartridge") Personally I find the shadowed text much harder to read than non-shadowed.

**Comment by nesbox** [comment]
> Is there a reason you lost the shadow on the pins? It doesn't look quite right without that... the top of the pins would be in shadow from the cartridge housing...

I tried but I can't find a proper color for the shadow of the pins in the sweetie16 palette :)

**Comment by nesbox** [comment]
With fixed shadowed text
![image](https://user-images.githubusercontent.com/1101448/109017357-2585e200-76c8-11eb-9c2c-3418ff4d5bb0.png)

**Comment by joshgoebel** [comment]
And this is where being obsessed with the palette _vs the hues_ (which preserves the same feel/branding) really does you in... because you really need a hue shifted yellow for the shadow. :-)

Dither?

![109017357-2585e200-76c8-11eb-9c2c-3418ff4d5bb0](https://user-images.githubusercontent.com/6473/109019749-47ab4000-7687-11eb-8613-d5747c14afea.png)

**Comment by nesbox** [comment]
> What did you change?

I made game text lighter, but not I got that you mean the shadowed text near the logo :)

Dither works as a variant, thank you.

**Comment by joshgoebel** [comment]
> but not I got that you mean the shadowed text near the logo

Yes the font I used is much easier to read than the tinier one you picked... (shadowed or not)... is it meant to be read or purely decorative? :-)

**Comment by nesbox** [comment]
This is the tiny font we are using in TIC80. I'm always trying to use the default font and default sweetie16 palette colors to design such things.

**Comment by joshgoebel** [comment]
_Even if the end result is worse [in that overall legibility suffers]?_  Did you try a variant with "cartridge" in caps?

You are keeping in mind not everyone is going to ZOOM these cartridges to read what it written on them...?  If the text is illegible when the image is shown at a small size then it's really just decoration...

**Comment by borbware** [comment]
I'd go with the smaller font even for the game title & game creator names!

You wouldn't need to have that long titles to overflow with the current design. Besides, if the game creator wants, they can feature the game title (and their name) more prominently in the cover image.

That would be more in line with actual game cartridges (or banner images in online marketplaces), for that matter.

**Comment by joshgoebel** [comment]
>  Besides, if the game creator wants, they can feature the game title (and their name) more prominently in the cover image.

I did have this thought earlier as well... most video game cartridges have a single sticker and that serves multiple purposes for logo/branding/name/etc... I think really what would be cool here is if the cartridge was really more of a "physical good"... and if someone wanted to make a special cartridge they could design it however they wanted.  Make it blue.  Have a larger graphic. Add decorative molding... just so long as it still had the correct "shape" and "pinout". :-) [of course those things are largely irrelevant also technically speaking]

I plan on doing RetroJam in the next week or so so if I have time I might see if our artist would want to try their hand at making a custom spiffy cartridge PNG. :-)

@nesbox Do you have any issue with people doing custom carts on their own - ie if the community makes some tools to make that super easy to do would you fight that by making the official binary start inspecting the images for the official template or something along those lines?  Or just os long as the binary data was encoded properly it would work, period?

**Comment by nesbox** [comment]
> Do you have any issue...

I'd like we have one common cart template with TIC logo and URL and allow the user to design the "sticker" he wants, with labels and other things.
The current design could be provided by default but technically, it doesn't matter for TIC how the cart looks, it just tries to decode the image, and the user allowed to encode the cart to any `256x256` png he wants.

**Comment by joshgoebel** [comment]
> I'd like we have one common cart template with TIC logo and URL and allow the user to design the "sticker" he wants, with labels and other things.

I generally have no problem with the logo and URL, only the font - I'm talking more bigger picture design elements, plastic color, molding, etc.  Not sure if we're talking past one another or not.  I definitely see the need/desire for a "brand" of cartridge that everyone gets by default.  I don't think *everyone* will do their own, it would just be nice if it was a thing that remains doable. :-)

For example right now I'm looking at doing a Gameboy Color game for RetroJam (letterboxes on TIC-80)... and if all you do is decode the data then I could make a 256x256 that looked more like an actual Gameboy cartridge - in keeping with the Jam theme - but still could just drag and drop if all you cared about what the raw data. :)

**Comment by nesbox** [comment]
Added PNG cart saving/loading here 335d795
Use `save name.png` command to check.

Example:
![power](https://user-images.githubusercontent.com/1101448/113429374-1853c580-93e1-11eb-8a80-33672e3f01c4.png)

**Comment by ChildishGiant** [comment]
These should be available to download from the tic.computer website along with the standard cart

**Comment by nesbox** [comment]
@ChildishGiant sure, will be added

**Comment by shinkarom** [comment]
What is the maximum cartridge size for saving to png?
