### ISSUE TITLE
Lua library inside cartridge

### ISSUE THREAD

**Issue by afonsojramos** [nesbox/TIC-80#756]
Is there any way to import a lua library to the cartridge? 
If so, where does the library need to be if it is for example, contained in a single file?

**Comment by afonsojramos** [comment]
@nesbox

**Comment by nesbox** [comment]
just copy/paste the library code to the cart
or you can save the lib code to any part of your cart (map section for example) and load using `loadstring(code)` lua func
also, here is an example of code loaded from cart cover https://tic.computer/play?cart=90

hope, this will help you

**Comment by afonsojramos** [comment]
The problem is that I was trying to use a Unit Testing library, in this case, LuaUnit, which is bigger than the character limit... So I needed a way of doing it outside of the running application.

**Comment by nesbox** [comment]
so, it's a problem
the only way I see is to store the lib code as map data and load it using `loadstring()` but it's definitely not worth it

**Comment by afonsojramos** [comment]
In that case I think we're going to just export the code and test it outside TIC-80! Thanks!

**Comment by lincerely** [comment]
In case anyone still looking for a solution, you can use `require` function to include external library. (https://www.lua.org/pil/8.1.html)
