### ISSUE TITLE
Web site's "add game" fails for Fennel cartridges

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#757]
I get "Please add at least TITLE, AUTHOR and COVER (by press F7) metadata to the cartridge and try again." when I try to upload a Fennel cartridge.

I'm guessing this is because it's searching for known comment syntax for the title/author headers and doesn't know that `;` is a comment char for Fennel. If you can point me towards where the code for this check is, I can update it. Thanks.

**Comment by nesbox** [comment]
oops, will fix it tonight
thanks

**Comment by StinkerB06** [comment]
Nesbox, I can't hit the like button on any cartridge on the site anymore.
The button is no longer there on my end.

**Comment by nesbox** [comment]
@technomancy 
I fixed the Fennel comments, please check
thank you

**Comment by nesbox** [comment]
@StinkerB06 pls open a new issue and describe your problem with all the details (OS browser...)

**Comment by technomancy** [comment]
Thanks; works great now.
