### ISSUE TITLE
Invalid palette on  Samsung Galaxy S3

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#76]
![img_20170327_154848](https://cloud.githubusercontent.com/assets/1101448/24367794/a051d73c-1326-11e7-897a-e658a5f2c7de.jpg)
![img_20170327_154923](https://cloud.githubusercontent.com/assets/1101448/24367795/a05628d2-1326-11e7-8605-0355106bed97.jpg)

**Comment by Marcuss2** [comment]
For those wondering why I didn't take a screenshot: When I took it, it looked how it should and not how it actually displayed.

**Comment by trelemar** [comment]
@Marcuss2 Can you reproduce this with current version?

**Comment by Marcuss2** [comment]
Yes, it is still happening with current version.

**Comment by nesbox** [comment]
can't reproduce it on any other device, seems it's SDL issue

**Comment by frenetic** [comment]
@Marcuss2 Can you reproduce it with version `0.50.1`+ ?

**Comment by frenetic** [comment]
Do you have `negative colors` activated on your phone?
http://www.samsung.com/hk_en/support/skp/faq/927468

If so, please deactivate it and check if things work.

**Comment by chrisleewoo** [comment]
I have the same issue on my Samsung galaxy S9. I tried disabling all visual enhancements on the phone and I still see negative colors on TIC80

**Comment by nesbox** [comment]
try this https://github.com/nesbox/TIC-80/issues/657#issuecomment-412490184
"The blue tint can be fixed by turning on "disable HW overlays" in development settings."

**Comment by chrisleewoo** [comment]
Perfect, this was very helpful.
