### ISSUE TITLE
TIC-80 lag makes 8-bit Panda die!

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#760]
I keep getting input lag upon playing 8-bit Panda. It makes me miss certain moves in the game, most often killing Panda.

**Comment by StinkerB06** [comment]
How 'bout add savestates?

**Comment by frenetic** [comment]
Tell us more about how you are playing the game.
TIC version, OS, system specs.
Knowing this helps a lot!

**Comment by RobLoach** [comment]
> How 'bout add savestates?

8-Bit Panda saves to pmem, so while save states arn't possible, it will save your progress. Managed to (ab)use this with cheats for the libretro port:
https://github.com/libretro/libretro-database/blob/master/cht/TIC-80/8%20Bit%20Panda.cht

> I keep getting input lag upon playing 8-bit Panda.

Probably your machine. Loads and plays without any lag for me.
