### ISSUE TITLE
Map editor: replace tile feature

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#764]
If there's ever a need to move tiles around in the tile editor, it might mess up maps I've already made.

An easy fix for this would be a tool in map editor to replace all tiles with id `x` with a tile of id `y`.

**Comment by PerdeT** [comment]
Well, in some cases it does help! But not when the tiles to be replaced are spread across the map and not adjacent with each other, and that's my main issue here. So an option to the fill tool to not follow adjacent tiles would be useful!

**Comment by nesbox** [comment]
It can be implemented as `ctrl+fill` or smth like that.

**Comment by Kyuchumimo** [comment]
This is a good idea and very useful. It would allow reordering tiles on sprite editor
