### ISSUE TITLE
[Feature Request] Add Libraries

### ISSUE THREAD

**Issue by GameExpress** [nesbox/TIC-80#767]
Add the ability to add libraries which can be imported into games by using a command.

To define a library you can use something like this (in the metadata of the file):
```lua
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua
-- type:   library
```

And then in another game import by using a command, for example:
`import("Collision.tic")`

This is my idea and I think that libraries would be very useful.
Of course, I'm not sure if this is a difficult this to do or not and I understand if it's too difficult to implement or manage such a feature.

**Comment by StinkerB06** [comment]
But what if there's more than 64 kilobytes?

**Comment by GameExpress** [comment]
Well what if the library added to the game's memory?
So if I import a library then it adds to the main game memory.
For example:
A game takes up 1273 bytes, but after importing it suddenly takes up 1894 bytes.

**Comment by planer28** [comment]
You can paste a library's code in to your game code.

Just saying.

**Comment by RobLoach** [comment]
While I recommend a compile/build/concatenation process instead, there is `dofile('bump.lua')` that you could do.

For [Dangerous Dave](https://github.com/RobLoach/DangerousDave-TIC80), I put together [scriptpackager](https://www.npmjs.com/package/scriptpacker) that would aggregate the dependencies together.

**Comment by nesbox** [comment]
unlikely will be added, many difficulties, pls use other tools to concatenate sources
also #715 duplicate
