### ISSUE TITLE
HTML5 export (many) glitches

### ISSUE THREAD

**Issue by JasonNumberThirteen** [nesbox/TIC-80#770]
I noticed small bug about switching from windowed to fullscreen mode. I have to press F11 exactly three times to switch to fullscreen. Inversely works correct. Occurs on Chrome and Firefox (on Edge doesn't launch itself AT ALL). There is also some lagging, but because I saw earlier reports of that, I won't duplicate it. Additionally, when I export again (to later release an update for example), entire persistent memory is vanished ("saveid" in metadata used).

**Comment by nesbox** [comment]
Now it works better, pls check .80
