### ISSUE TITLE
"tic80 -fullscreen" not working

### ISSUE THREAD

**Issue by sovietotaku** [nesbox/TIC-80#773]
"-fullscreen" command line argument is not working. At last, in 0.70.6 Windows build.

**Comment by moonlit** [comment]
Not working currently (built from repository) on macOS 10.12.6 either.

**Comment by nesbox** [comment]
Fixed in .80

**Comment by revdeluxe** [comment]
umm idk i think it's not working...
tic80 --fullscreen --skip --cmd="demo & load tetris.tic & run"

i just see blank screen but the terminal works though
when i pressed 'ESC' and then typed 'exit' i can see what it did verbosely in my FISH/BASH

also the commands are mouthful.
maybe just maybe shrink it... like
tic80 -fs -c="demo & load tetris.tic & run"
tic80 <SCREEN MODE> <BOOT OPTIONS> <CMD>
you know :)

here's a clip

https://user-images.githubusercontent.com/38414584/145436861-0c5705ca-efe0-49b0-83ca-437ae218b794.mp4

**Comment by RobLoach** [comment]
Looks like it went Fullscreen?

**Comment by nesbox** [comment]
Just checked, it works on Windows, maybe it's only Linux related issue.
Also let's rename `--fullscreen` to `--fs`.
Thank you.

**Comment by RobLoach** [comment]
> Just checked, it works on Windows, maybe it's only Linux related issue.

`--fullscreen` is working fine for me on Linux Ubuntu MATE 20.04.

> Also let's rename --fullscreen to --fs.

Note that `--fs` is filesystem right now :upside_down_face:

**Comment by nesbox** [comment]
oops :) then let's leave it as is or maybe @revdeluxe has other variants :)

**Comment by nesbox** [comment]
Working for me on Ubuntu.
Please check the latest build https://nightly.link/nesbox/TIC-80/workflows/build/main
