### ISSUE TITLE
Memory layout

### ISSUE THREAD

**Issue by arthurferrai** [nesbox/TIC-80#774]
Looking through the code, the memory layout on [wiki](https://github.com/nesbox/TIC-80/wiki/RAM) looks inaccurate according to [source](https://github.com/nesbox/TIC-80/blob/stable/src/tic.h#L417). Doc says there are 16 bytes of `...` (which I understand it's unused) while source code reserves 12 bytes of `unknown` data.
Also, I think wiki/ram command could use something more descriptive than `...` for unused/reserved memory space.

**Comment by StinkerB06** [comment]
The keyboard buffer size was increased from 4 to 8.

**Comment by StinkerB06** [comment]
Hmm... I did a quick test of the 5th...8th and those appear not to be keyboard buffer values at all. 0xFF8C acted weird, it only reflected to key depress state, and 0xFF8D ~ 0xFF8F were `0` when returned by `peek()`.

**Comment by arthurferrai** [comment]
> also `...` is unused space

Yup, I got that, but I needed to look to source code to deduce that. I think using `UNUSED` word is more clear/descriptive than using `...`.

Also, if `0x14000` is of size 0, why it's on the list at all?
