### ISSUE TITLE
Keyboard on Android version

### ISSUE THREAD

**Issue by avevad** [nesbox/TIC-80#785]
Please return virtual keyboard on Android version

**Comment by StinkerB06** [comment]
Perhaps with an option in the config file?

**Comment by Avevad** [comment]
What do you mean by "option"?

**Comment by AsixJin** [comment]
I agree with this suggestion. I apperciate the keyboard in TIC 80 but its really bothersome to work with.

**Comment by ingdanko** [comment]
Bump. Please at least let us choose between the system and the TIC one.

**Comment by Avevad** [comment]
Did something change?
Is it so hard to add this option?

**Comment by nesbox** [comment]
It's not hard, will be added in .80

**Comment by nesbox** [comment]
Added system keyboard on Android here bf055ef
TIC internal keyboard is temporarily disabled in .80

**Comment by nesbox** [comment]
You can download build with the system kbd on Android here https://builds.tic80.com/master/2020.07.15/android

Button to activate keyboard looks like:
![image](https://user-images.githubusercontent.com/1101448/87545906-64bf6f80-c6b1-11ea-911e-db4156b65274.png)

**Comment by avevad** [comment]
18 months later we got it. :smile: 
Thank you for help

**Comment by nesbox** [comment]
:)
