### ISSUE TITLE
Gamepad Buttons on Android

### ISSUE THREAD

**Issue by AsixJin** [nesbox/TIC-80#786]
Can the buttons be labeled with the key they match with. Games don't use 'abxy' when giving instructions and it can be confusing.

For example, I was playing a game that said press X, but they meant the keyboard not the gamepad X.

**Comment by StinkerB06** [comment]
What was the name of the game you were playing that said to press the X key?

**Comment by AsixJin** [comment]
It wasn't just one game nor is that important. Some games uses keyboard prompts (aszx) and some use gamepad prompts (abxy). If im playing on Android and the game uses keyboard prompts (or vice versa) that can be confusing.

**Comment by BuoYancYdabl** [comment]
I think its idea to developers: if you have tips about gamepad keys - make a keyboard keys workable too.

**Comment by nesbox** [comment]
Yes, agreed, you should care about labels as a developer.
