### ISSUE TITLE
The iOS version 0.60.3  can not run on a real iPad

### ISSUE THREAD

**Issue by FreeBlues** [nesbox/TIC-80#787]
The iOS version 0.60.3(https://github.com/brunophilipe/TIC-80) can not run on a real iPad

It can work on the iOS emulator, but can not run on a real iPad. When you input a command and press Enter, a red "SYNC" appears on the top right of the screen, but nothing happened.

**Comment by nesbox** [comment]
iOS not officially supported in this repo atm, pls create an issue in https://github.com/brunophilipe/TIC-80
