### ISSUE TITLE
Can't build on Raspbery pi 3: : cannot find -lbcm_host 

### ISSUE THREAD

**Issue by 3eluk** [nesbox/TIC-80#794]
HW: Raspberry pi 3 model B
OS: Raspbian stretch

<pre>[  4%] Built target sdlgpu
[  9%] Built target squirrel
[ 10%] Built target lpeg
[ 19%] Built target lua
[ 22%] Built target giflib
[ 24%] Built target wren
[ 27%] Built target tic80core
[ 28%] Built target sokol
[ 29%] Built target sokol-renderer
[ 33%] Built target zlib
[ 33%] Built target bin2txt
[ 43%] Built target tic80prolib
[ 83%] Built target SDL2-static
[ 84%] Built target SDL2main
[ 84%] Linking CXX executable bin/sdl-renderer
/usr/bin/ld: cannot find -lbcm_host
collect2: error: ld returned 1 exit status
CMakeFiles/sdl-renderer.dir/build.make:92: ошибка выполнения рецепта для цели «bin/sdl-renderer»
make[2]: *** [bin/sdl-renderer] Ошибка 1
CMakeFiles/Makefile2:277: ошибка выполнения рецепта для цели «CMakeFiles/sdl-renderer.dir/all»
make[1]: *** [CMakeFiles/sdl-renderer.dir/all] Ошибка 2
Makefile:129: ошибка выполнения рецепта для цели «all»
make: *** [all] Error 2 </pre>
Excuse me for non-translated Russian text.

**Comment by RaspberyPye** [comment]
Hi, after doing this i got a further error:
 `[ 94%] Built target SDL2main
[ 94%] Linking CXX executable bin/player-sdl
/usr/bin/ld: lib/libSDL2.a(SDL_dynapi.c.o): undefined reference to symbol 'dlopen@@GLIBC_2.4'
/usr/bin/ld: //lib/arm-linux-gnueabihf/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/player-sdl.dir/build.make:93: bin/player-sdl] Error 1
make[1]: *** [CMakeFiles/Makefile2:200: CMakeFiles/player-sdl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by nesbox** [comment]
dup of #1017
