### ISSUE TITLE
Build fails with older macos (10.11.6)

### ISSUE THREAD

**Issue by oliverKuha** [nesbox/TIC-80#795]
With macos 10.11.6 I am not able to build TIC-80. Nor can I install it with prebuild package. So it seems that TIC-80 is not supported on these older versions of macos. If that is a intention, could it be stated somewhere like supported platforms list or something?

**Comment by nesbox** [comment]
It's not an intention, I just don't have an older mac to test.
Pls, try to build the latest version with CMake build system.
Here is build commends.
https://github.com/nesbox/TIC-80/blob/master/.github/workflows/build.yml#L181
