### ISSUE TITLE
Weird/glitched carts in SURF menu

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#801]
One of my friends was playing on an older version of TIC-80 (0.60.3) and he noticed some weird carts that pull up another cart or return a "cart loading error". I don't know if this bug exists in the latest version (0.70.6), since I've never seen it before.
![weird glitched carts](https://user-images.githubusercontent.com/30059831/51795845-8c113c80-219e-11e9-80ed-9727b94555ac.gif)

**Comment by nesbox** [comment]
Fixed in .80
