### ISSUE TITLE
Separate assets (palette, sprites, ets) from code in pro version

### ISSUE THREAD

**Issue by HelveticaScenario** [nesbox/TIC-80#802]
When you save a cart as a code file, such as `game.js`, the assets get inserted into the bottom of the file as comments (`TILES`, `WAVES`, `SFX`, `PALETTE`). this is fine when you are editing `game.js` directly because the tic80 editors update those comments, but if you are using a language like typescript which compiles `game.ts` to `game.js`, those asset comments get overridden when the file is compiled. is it possible to split those assets into a different file, maybe one with the same name like `game.assets` or referenced in a tag or something, so it doesn't get overridden?

One other alternative is to add something akin to the `dofile` function in lua in the other available languages. i think duktape supports commonjs `require`, but when i tried that in tic it didn't work.

**Comment by nesbox** [comment]
Hmm, what if write a script which will split two files, typescript generated code and .js with  sprites/...
