### ISSUE TITLE
tic80.exe process stays running after being closed; high CPU usage

### ISSUE THREAD

**Issue by db0z** [nesbox/TIC-80#803]
Noticed on 0.70.6 with Windows' Task Manager on a very slow PC.

Steps to reproduce: simply run it and close it either with "exit" or the close button.

After running for a while, tic80.exe may or may not have its CPU usage jump to 25 on my machine. This was easiest to reproduce by repeating the procedure above 3+ times, but it has happened to me with just 1 process under normal usage as well.

**Comment by nesbox** [comment]
Can't reproduce on .80.
