### ISSUE TITLE
Errors aren't reported in coroutines

### ISSUE THREAD

**Issue by rdococ** [nesbox/TIC-80#804]
I don't have a cartridge that shows this bug at the moment (although I can provide one), but if a runtime error occurs in a coroutine, the error doesn't get reported.

**Comment by librorumque** [comment]
That's intended behavior in Lua. Instead, `coroutine.resume` first returned value is `false` when error happens. [Lua-wiki](http://lua-users.org/wiki/CoroutinesTutorial)

**Comment by rdococ** [comment]
> That's intended behavior in Lua. Instead, `coroutine.resume` first returned value is `false` when error happens. [Lua-wiki](http://lua-users.org/wiki/CoroutinesTutorial)

Oh, that's interesting. I would have thought that you'd use a "pcall" in conjunction with a coroutine to do that, but I suppose that coroutines themselves can do the trick.
