### ISSUE TITLE
Display in non-sokol build

### ISSUE THREAD

**Issue by a2** [nesbox/TIC-80#807]
Building from 528bb40b4f30c05f46172ad6cf408d453a1e8be2 on macOS 10.14.3 (18D42) with Xcode 10.1 (10B61)

---

Top: Sokol build
Bottom: Non-sokol (SDL?) build
<img width="770" alt="screen shot 2019-02-08 at 4 43 45 pm" src="https://user-images.githubusercontent.com/241156/52488780-e8258900-2bc0-11e9-8d6f-5b9183e4dce0.png">

**Comment by nesbox** [comment]
yes, here we have a problem with sdl_gpu library we are using to render screen.
I've reproduced it recently too, very strange, on previous mac os version all was ok.

**Comment by a2** [comment]
@nesbox Oh good, I thought it was just me. The version I downloaded from the releases page ([v0.70.6](https://github.com/nesbox/TIC-80/releases/tag/v0.70.6)) works but shows a popup on 10.14 on launch :/

<img width="532" alt="image" src="https://user-images.githubusercontent.com/241156/52489621-fb395880-2bc2-11e9-9d3e-9a705adbb56b.png">

**Comment by nesbox** [comment]
has to be fixed here 1fcde1a
