### ISSUE TITLE
Disabling default audio driver crashes TIC-80

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#808]
If you have TIC-80 running, and decide to disable your default audio driver on Windows, TIC will crash out of nowhere. Please fix.

How I found out:
My personal brother uses TIC-80 and PICO-8, and makes a bunch of sprite hacks from various carts. He had 7 TIC-80s open at a time, as well as 7 PICO-8s. On YouTube and some other stuff I use, I got a bunch of audio driver error messages. I was making something on a music tracker called [OpenMPT](https://openmpt.org/), but I got freaked out because the audio driver (Realtek HD Audio) was being so unresponsive. I went to disable and re-enable the driver. In a matter of seconds, I saw a bunch of **_TIC-80 has stopped working_** pop-ups out of nowhere. The PICOs didn't crash, however.

**Comment by nesbox** [comment]
Huh, don't  know how to reproduce
