### ISSUE TITLE
--input: [gamepad/mouse/keyboard] issue.

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#810]
Android version of tic (even a pro version) have issue with --input: argument. Since it not work anymore after update on .70. Can you fix it?

**Comment by dagondev** [comment]
As it was linked elsewhere by nesbox. +1. Not hiding touch gamepad while on android with game that have --input:mouse really sucks as you are forced in portrait mode only.

**Comment by nesbox** [comment]
disabled touch gamepad/keyboard on startup and fixed `input:` metatag here c85bd14
