### ISSUE TITLE
OSX: "No mountable file systems" 

### ISSUE THREAD

**Issue by Joe-Gigs** [nesbox/TIC-80#815]
Trying to open the latest Dmg. Getting this message.
Anyone else faced this?
![screen shot 2019-03-02 at 8 59 22 pm](https://user-images.githubusercontent.com/14349974/53689903-1d3f7a00-3d2e-11e9-88ce-8f930c83aaae.png)

**Comment by BuoYancYdabl** [comment]
Rename it to exe

**Comment by gregsadetsky** [comment]
I couldn't get any of the recent .dmg files to open either. The most recent one that did work was [0.60.3](https://github.com/nesbox/TIC-80/releases/download/v0.60.3/tic80_0.60.3.dmg).

**Comment by nesbox** [comment]
fixed .dmg creating here 960ab92
the latest build here https://builds.tic80.com/master/2020.07.17/mac
