### ISSUE TITLE
Bluetooth keyboard in Android with SwiftKey (custom keyboard))

### ISSUE THREAD

**Issue by Sky84** [nesbox/TIC-80#818]
Hello,
I've a pb with a jelly comb keyboard.
The letters work only with holding CTRL key on my Honor 10 with emui 9

**Comment by MrPelucaa** [comment]
Yes, I have this same problem. It was made aware in #671 and apparently got fixed but im still getting this bug.

**Comment by MrPelucaa** [comment]
@Sky84 Have you tried using the default keyboard? If you have any other touch keyboard active (like swiftkey) it may be that. Thats how I fixed the same issue. Select the default input method before connecting the bluetooth keyboard. Hope it works!

**Comment by Sky84** [comment]
> @Sky84 Have you tried using the default keyboard? If you have any other touch keyboard active (like swiftkey) it may be that. Thats how I fixed the same issue. Select the default input method before connecting the bluetooth keyboard. Hope it works!

Thank you ! Without swiftkey it's working
