### ISSUE TITLE
[Chrome] Website version's SURF menu displays folders not shown before

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#822]
This also contains the actual /com.nesbox.tic/TIC-80/ directory where you saved cartridges to within the browser.
![screen](https://user-images.githubusercontent.com/30059831/54492351-039c4780-4883-11e9-900b-f14a72bc255a.gif)

**Comment by nesbox** [comment]
Tic just shows folders in your's browser storage
Not a bug
