### ISSUE TITLE
Cannot enlarge memory arrays error when running TIC in chrome

### ISSUE THREAD

**Issue by Jaxsun** [nesbox/TIC-80#824]
I've exported some small TIC carts to HTML, it seems that after a little while of running them I get the following error in the Chrome console and TIC just freezes up.

Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 67108864, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

This happens consistently after running for 5-10 minutes in Chrome, but I haven't been able to reproduce this in another browser (I've only tried Edge so far) or in TIC just running on my desktop.

I also haven't been able to reproduce this playing games on the tic website, it seems to only occur when using the exported HTML files as is.

**Comment by BuoYancYdabl** [comment]
Try to set ALLOW_MEMORY_GROWTH to 0.

**Comment by nesbox** [comment]
Pls provide cart to reproduce, thanks
