### ISSUE TITLE
Sound Registers Visualizer Lua port?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#829]
@nesbox, why is your [Sound Registers Visualizer](https://tic.computer/play?cart=115) cartridge in JavaScript? I don't know much about that programming language and I want a Lua version!

**Comment by StinkerB06** [comment]
[SoundRegVis Lua port attempt.lua.txt](https://github.com/nesbox/TIC-80/files/3075454/SoundRegVis.Lua.port.attempt.lua.txt)
Alright, here's my attempt. Looking really good so far, except the noise wave is just a solid line in the "negative" phase. Please fix it.

**Comment by nesbox** [comment]
I don't think it's tic related issue

**Comment by StinkerB06** [comment]
Oh, I see why! Forgot to add a `~=0` on lines 57 and 103!
