### ISSUE TITLE
Cartridge loss

### ISSUE THREAD

**Issue by avevad** [nesbox/TIC-80#831]
I spent 2 days writing my project in TIC-80 every time saving when I exitting the app. But now, I opened TIC-80 and tried to load my cart. It said "card loading error". I opened the explorer and looked at the TIC-80 folder, noticed that my card file size is 0. What the hell? How to repair it? I'm using Android version 0.60.3.

**Comment by BuoYancYdabl** [comment]
I have bad news - there is no way to fix this. But first of all please say where are your local data storages? At external or internal storage? Because if it on external that may be a reason.

**Comment by BuoYancYdabl** [comment]
Why did you close this issue. It might be fixed sooner.

**Comment by avevad** [comment]
Nobody seems to be having the same issue. Also, my phone is old and it sometimes can be freaky. All these circumstances made me think that it's whole my fail, thus I closed the issue. However, anyone still can comment it.
