### ISSUE TITLE
(Version 0.70.6) Almost always crashes when trying to re-enter surf mode.

### ISSUE THREAD

**Issue by DDevil97** [nesbox/TIC-80#834]
It's really easy to replicate, just enter surf mode, load a random cart, close it via the menu, exit surf mode to inspect the source of the loaded cart and such, enter surf mode again, instant crash. It happens both in the Windows and Android version. Interestingly, it seems to happen more frequently (almost always) when you exit surf mode and enter the Demos category, not sure why

**Comment by StinkerB06** [comment]
My guess is that I believe the website's server is in the Republic of Belarus (where @nesbox lives), and it takes some time (especially if you're far away from that country) for the SURF-mode packet to get to the server and return all carts in the specified category.

The _Demos_ category has the most carts of all. The more carts there are, the slower the response back from the server. When a connection fails or there isn't internet, TIC-80 is likely to freeze and crash.

**Comment by DDevil97** [comment]
Mmmmmm, Tic80 seems to deal fine with internet cutting down in the middle of accessing a category, it just returns an empty list. In fact, i don't have to be connected at all, if i enter surf mode, enter the demo category, exit, activate airplane mode, and try to enter surf mode it crashes anyway. Funny

**Comment by BuoYancYdabl** [comment]
Same issue. But i leave in Ukraine (this country near Belarus). So i dont think thats because of internet. I think app try to reload cover image and got crashed.

**Comment by BaRRaKudaRain** [comment]
If it's UWP version try to reset it. It may be helpful.

--
----------------------------------------
An outsider, the BaRRaKudaRain

-----Original Message-----

**Comment by nesbox** [comment]
I know about the issue and it already fixed in .80

**Comment by DDevil97** [comment]
> I know about the issue and it already fixed in .80

Well i will close the issue then, thanks for the consistently good support!

**Comment by Masternama-8000** [comment]
Hmm.. this **demos** is crashes a TIC-80 Surf. Nesbox country (**Belarus**)  **Demos** entered after cover image gets crashed. Nesbox's server it works **demos**. 

Here we go there is a old problem here
https://itch.io/t/466604/tic-80-surf-mode-demos-after-crashing
