### ISSUE TITLE
Program crashes after random interval (~10 min), bringing down Xwayland

### ISSUE THREAD

**Issue by buckle2000** [nesbox/TIC-80#837]
**Version:** 0.70.6 downloaded from [here](https://github.com/nesbox/TIC-80/releases)
also confirmed on latest git version

If I open the program and do anything meaning ful, the program will always crash in 20 minutes, also crashing `Xwayland` and `gnome-shell`. The desktop environment will then restart with no warning message. I have no idea why this would happen.

Here's the output of `valgrind --error-limit=no ~/software/tic80 2>| sudo tee /var/log/tic80` until it crashes: [Valgrind stderr](https://github.com/nesbox/TIC-80/files/3145274/tic80.log.txt)

Here's the backtrace of coredump of `Xwayland`: [gdb output](https://github.com/nesbox/TIC-80/files/3145281/a.txt)

**Comment by nesbox** [comment]
possibly was fixed here #1012
