### ISSUE TITLE
Is there an MML converter for TIC-80?

### ISSUE THREAD

**Issue by kikeroga3** [nesbox/TIC-80#838]
Is there a tool for TIC-80 to convert MML music?
Or do you have plans to make it in the future?
There are many songs made in MML in the past, so it would be nice to be able to use them.

**Comment by kikeroga3** [comment]
I tried my best as much as possible.

<pre>
-- MML Data
dat={
	"@0v5o4CRDRERFRGRARBR>CR",
	"@1v3o1CBRCBRCBRCBRBRBR",
	"@2v2o3ARARARARARARARAR",
	"@3v5o6FFFFFFFFFFFFFFFR"
}
tmp=80;rws=64;spd=6
nt=1;sn=0;oc=4;vo=5
mml="@vo<>-+R__CcDdEFfGgAaB"

function w_mpat(pt,rw)
	ad=0x11164+64*3*pt
	n=((15-vo)<<12)+(nt<<8)+((oc-1)<<5)+sn
	poke(ad+rw*3,n//256)
	poke(ad+rw*3+2,n&255)
end

-- Pattern 1,2,3,4 on Track 0
ad=0x13E64;n=(1<<18)+(2<<12)+(3<<6)+4
poke(ad,n&255)
poke(ad+1,(n>>8)&255)
poke(ad+2,(n>>16)&255)
-- Tempo Rows Speed
poke(ad+16*3,tmp+106)
poke(ad+16*3+1,64-rws)
poke(ad+16*3+2,spd-6)

-- MML Convert
for ch=1,4 do
	ri=1;wi=0	-- Read Write Index
	repeat
		c=string.sub(dat[ch],ri,ri);ri=ri+1
		i=string.find(mml,c)
		if i then
			if i<4 then
				v=tonumber(string.sub(dat[ch],ri,ri))
				ri=ri+1
			end
			if i==1 then sn=v end
			if i==2 then vo=v*3 end
			if i==3 then oc=v end
			if i==4 then oc=oc-1 end
			if i==5 then oc=oc+1 end
			if i==6 then nt=nt-1 end
			if i==7 then nt=nt+1 end
			-- Set Note
			if i>7 then nt=i-7
				w_mpat(ch-1,wi);wi=wi+1
			end
		end
	until ri>#dat[ch]
end
-- Play Music
music(0)

function TIC()end
</pre>

**Comment by buckle2000** [comment]
If you have the pro version of TIC80 you can save your cart as `xxxxx.lua` (plain text). Then you can modify the cart in plain text.

**Comment by kikeroga3** [comment]
Thanks for your comment!
I bought the PRO version.
The Pro version makes it easy to read data, but it is more difficult to create a practical MML conversion program.

**Comment by buckle2000** [comment]
you can write a program that just writes to stdout and paste the output in the catridge.
`./convert < in.mml | xcopy`

**Comment by kikeroga3** [comment]
Thank you! I understood how to make it well.
