### ISSUE TITLE
Persistent real time clock

### ISSUE THREAD

**Issue by lf94** [nesbox/TIC-80#841]
In many retro consoles, they provided clocks inside cartridges to keep time for various reasons. The best example of this is in Pokemon Gold and Silver for tracking the time of day. Providing a `prtc()` or `clock()` function would be great!

**Comment by RobLoach** [comment]
`os.time`?
https://www.lua.org/pil/22.1.html

**Comment by lf94** [comment]
Would that do the trick? On the surface I want to say yes.

**Comment by RobLoach** [comment]
Try it, if it works, then great!

**Comment by StinkerB06** [comment]
The `os` library was removed from TIC-80.

**Comment by lf94** [comment]
> Try it, if it works, then great!

I opened this issue not for myself, but for others :) I have no intention on using TIC-80 at this time.

**Comment by StinkerB06** [comment]
`print(os)` just says `nil`, and trying to use any of its functions (like `print(os.time())`) crashes the cart.

**Comment by RobLoach** [comment]
[`time()`](https://github.com/nesbox/TIC-80/wiki/time) is being used already. We could introduce a `date()` function that returns an array.

``` lua
local dateTable = date()
local year = dateTable[0]
local month = dateTable[1]
local day = dateTable[2]
local hour = dateTable[3]
local minute = dateTable[4]
local seconds = dateTable[5]
local milliseconds = dateTable[6]
```

**Comment by RobLoach** [comment]
Hmmm, I think having `date()` return the UNIX timestamp may be the best, most portable, option.
