### ISSUE TITLE
internet in TIC 80

### ISSUE THREAD

**Issue by hanamileh** [nesbox/TIC-80#843]
думаю можно добавить API чтобы можно было передовать данные по интернету (другу например) т.е. например мне нужно передать другу свои кординаты, для этого я в код пишу send(x,1) send(y,2) (или что там будет) а друг их должен получить (например) x=get(1) y=get(2)
а чтоб данные можно было получать только с моего компа, в начале можно написать к примеру —sendid: 43657
можно будет делать мультиплеер или ммо игру
или даже например соц сеть :D
------------------------------------------
I think you can add the API to transfer data over the Internet (friend for example) i.e. for example I need to give them your coordinates, for that I write code send(x,1) send(y,2) (or whatever it is) and each of them needs to receive (for example) x=get(1) y=get(2)
and that data could only be obtained with my computer, in the beginning you can write for example —sendid: 43657
you can do multiplayer or MMO game
or even for example social network :D

**Comment by RobLoach** [comment]
Multiplayer could be possible in the [TIC-80 libretro core](https://github.com/nesbox/TIC-80/pull/846), if memory serialisation and pmem is figured out.

**Comment by BuoYancYdabl** [comment]
then someone should has a server of each game

**Comment by hanamileh** [comment]
let it work on the same server as the site :D

**Comment by saranvdev** [comment]
I think the only feasible way is to use Peer2Peer and use TIC-80 server as a god-server connecting all p2p clients, ie. each client has to compute things for every other client

**Comment by RobLoach** [comment]
Got it working in [RetroArch Netplay](https://retroarch.com/?page=netplay) for the libretro core:
https://tic.computer/play?cart=893

You need to have all important information in `pmem()`. RetroArch will sync the states for multiplayer through netplay.

**Comment by RobLoach** [comment]
https://github.com/nesbox/TIC-80/issues/457
