### ISSUE TITLE
Use LuaJIT to run lua cartridges

### ISSUE THREAD

**Issue by kostik1337** [nesbox/TIC-80#849]
LuaJIT can run significantly faster with reasonable compile time. Maybe it should be optionally enabled with those header comments

**Comment by StinkerB06** [comment]
TIC-80 uses Lua 5.3 as the base. Is LuaJIT up to date?

**Comment by kostik1337** [comment]
Oh, that's right, LuaJIT only supports Lua 5.1 and Lua version doesn't seem to be updated anytime soon. Guess I'll just close the issue.

**Comment by StinkerB06** [comment]
Why doesn't every developer that integrates Lua into an application use the latest version? Did they never know it existed?
