### ISSUE TITLE
Palette Editor Tool

### ISSUE THREAD

**Issue by aaronsnoswell** [nesbox/TIC-80#852]
Hi @nesbox. Thanks for such an awesome fantasy console :) I love TIC-80.

I just wanted to give you a heads up. I made a jsFiddle online palette editor for TIC-80. It's a work in progress, but it's currently functional. I've added a link to this editor to the [bottom of the palette wiki page](https://github.com/nesbox/TIC-80/wiki/palette#online-palette-editor).

Hope that's OK.

**Comment by nesbox** [comment]
Hi, that's OK :)
Thank you.
