### ISSUE TITLE
RPI 3 B+ Debian Cmake issue

### ISSUE THREAD

**Issue by Awesomegamer6566** [nesbox/TIC-80#857]
When I tried To use Cmake, It said: 
`CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.9 or higher is required.  You are running version 3.7.2

-- Configuring incomplete, errors occurred!
`
I cannot get the newest version of cmake.
Btw im running Debian 9.8

**Comment by RobLoach** [comment]
If raspbian/debian doens't prove an updated version of cmake, I'd recommend compiling it.

**Comment by Anrock** [comment]
Quick grep shows highest `cmake_minimum_required` is `3.4` in `3rd-party/squirrel/CMakeLists.txt`. Maybe something has changed meanwhile. @Awesomegamer6566 can you try again?
