### ISSUE TITLE
fatal: unable to access 'https://github.com/nesbox/TIC-80/': Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by davidpgil** [nesbox/TIC-80#859]
I'm trying to install TIC-80 with the Ubuntu 14.04 instructions on my Ubuntu 16.04 machine and am blocked by this error message upon typing:

git clone --recursive https://github.com/nesbox/TIC-80 && cd TIC-80

How can I proceed?

**Comment by nesbox** [comment]
Hmm, don't know, seems your Ubuntu doesn't like cert from the Github.
As a solution, try to temporary disable SSL certificate verification using command `git config --global http.sslVerify false`

**Comment by davidpgil** [comment]
Worked!
