### ISSUE TITLE
(Feature) CODESPACEx4 in 0.80

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#862]
Since at 0.80 version of tic code banks will be removed increase the main bank code space x4 times. Some of projects cant fit in 64k due to insane amount of scripts.

**Comment by StinkerB06** [comment]
Or maybe x8 times.

**Comment by BuoYancYdabl** [comment]
> Or maybe x8 times.

So there is no point to remove 7 banks of code. If nesbox will leave 4 banks of code i will be very glad, cuz thats enough on everything!

**Comment by BuoYancYdabl** [comment]
I will open this issue when 0.80 outcomes.
