### ISSUE TITLE
Compiling on Raspberry Pi with retropie

### ISSUE THREAD

**Issue by JustGlowing** [nesbox/TIC-80#863]
I just compiled tic80 on a Raspberry Pi 3B with retropie installed.

I'm able to run `bin/tic80` it just open the terminal on the console and not the graphical interface. So I can run the command `help`, but if I run `edit` it gets stuck.

I get the same result if try to run it from emulationstation.

Any recommendation?

**Comment by RobLoach** [comment]
Do you get any errors during compilation or runtime? Anything appear in the terminal?

**Comment by JustGlowing** [comment]
The compilation went smooth but I had to add `link_directories(/opt/vc/lib)` to `CMakeList.txt`.

**Comment by RobLoach** [comment]
Seems like that would be a good addition. I've been trying to get it to compile myself for Lakka. Mind creating a PR for it? Nesbox might have some ideas.

**Comment by JustGlowing** [comment]
I might do it during the weekend.

Still, it doesn't work with emulation station.

**Comment by RobLoach** [comment]
Got it to compile the libretro core through [Lakka](https://github.com/libretro/Lakka-LibreELEC). Needed the following PR to allow it to build correctly: https://github.com/nesbox/TIC-80/pull/871

**Comment by JustGlowing** [comment]
Looks great! I'll try it out.
