### ISSUE TITLE
bin2txt errors

### ISSUE THREAD

**Issue by RobLoach** [nesbox/TIC-80#864]
When building TIC-80 for LibreELEC, I'm getting some errors around bin2txt...

```
[ 60%] Built target bin2txt
[ 61%] Generating ../bin/assets/config.tic.dat
[ 62%] Generating ../bin/assets/benchmark.tic.dat
[ 62%] Generating ../bin/assets/fenneldemo.tic.dat
[ 62%] Generating ../bin/assets/font.tic.dat
[ 63%] Generating ../bin/assets/fire.tic.dat
[ 63%] Generating ../bin/assets/benchmark.tic.dat
bin/bin2txt: 1: bin/bin2txt: Syntax error: word unexpected (expecting ")")
[ 64%] Generating ../bin/assets/config.tic.dat
bin/bin2txt: 1: bin/bin2txt: Syntax error: word unexpected (expecting ")")
bin/bin2txt: 1: bin/bin2txt: Syntax error: word unexpected (expecting ")")
bin/bin2txt: 1: bin/bin2txt: Syntax error: word unexpected (expecting ")")
make[2]: *** [CMakeFiles/tic80lib.dir/build.make:63: ../bin/assets/benchmark.tic.dat] Error 2
make[2]: *** Waiting for unfinished jobs....
bin/bin2txt: 1: bin/bin2txt: Syntax error: word unexpected (expecting ")")
make[2]: *** [CMakeFiles/tic80lib.dir/build.make:138: ../bin/assets/config.tic.dat] Error 2
```

Would it be crazy to commit the built .dat files directly to the repo to save having to compile bin2txt?

**Comment by nesbox** [comment]
Hmm, don't like the idea to commit .dat files, sorry :)
But, who does throw the error, cmake?

**Comment by RobLoach** [comment]
I agree. Would prefer to find the root of the problem. I believe it's part of this part...
```
add_custom_command(OUTPUT ${OUTNAME}
	COMMAND ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/bin2txt ${CART_FILE} ${OUTNAME} -z
	DEPENDS bin2txt ${CART_FILE}
)
```

It takes a bit of time to compile, but to reproduce...

```
git clone https://github.com/RobLoach/Lakka-LibreELEC.git
cd Lakka-LibreELEC
DISTRO=Lakka PROJECT=RPi2 ARCH=arm scripts/build tic80
```

**Comment by RobLoach** [comment]
The problem was that bin2txt was being compiled in ARM, but was trying to execute in x64 format :cry: 

I know it's not the best solution, but seems to work! plllllllzzzzzzzzzzzz???

Alternatively we could port bin2txt to Lua or something :thinking:

**Comment by nesbox** [comment]
@RobLoach What if we just wrap the code where we include this .dat files with preprocessor definition, `#define BUILD_DEMO_CARTS` for example?
I think this could solve the problem.

**Comment by RobLoach** [comment]
That's a great idea!

1. Build bin2txt only if `BUILD_DEMO_CARTS` is defined
2. Add `BUILD_DEMO_CARTS` C define
2. Where we include the carts, only include them in `BUILD_DEMO_CARTS` is there

**Comment by nesbox** [comment]
Sounds good, you can also wrap with definition whole `onConsoleInstallDemosCommand()` function here here https://github.com/nesbox/TIC-80/blob/master/src/console.c#L1447

**Comment by RobLoach** [comment]
:+1:
