### ISSUE TITLE
Publish hashes of binaries on https://tic.computer/create

### ISSUE THREAD

**Issue by mhykes** [nesbox/TIC-80#865]
Hi,

I downloaded the .zip version for Windows.  When I launch the application, Windows Defender SmartScreen says it blocked the program.  It shows the publisher as 'Unknown publisher'.  This makes me feel uncomfortable about the security of your .zip version.

![image](https://user-images.githubusercontent.com/7273963/60683863-3b49f200-9e68-11e9-864a-5974c5196b27.png)

For now, I'm going to use the version published through the Windows Store.  I'd love to trust the .zip version, though.

Thank you for providing this nifty retro development platform.

**Comment by nesbox** [comment]
Yes, I have to buy a certificate to sign my binaries.
Btw, you can install TIC80 through the itch.io app without SmartScreen warning.

**Comment by mhykes** [comment]
Thank you for responding.  I see binary signing isn't exactly cheap.  I haven't done any desktop development for ages, so had lost track of the costs.  Maybe you could publish a hash of the executable so it could be manually verified.  This seems to be common in open-source projects.

**Comment by nesbox** [comment]
yes, good idea, I'll publish SHA256 for binaries on the website
btw, you can check binary hash on our build server (https://builds.tic.computer/master/2019.09.27/win for example)

**Comment by nesbox** [comment]
Added SHA256 for the downloads https://tic80.com/create

**Comment by mhykes** [comment]
Awesome.  Thank you.
In today's climate of insecurity every bit counts.
