### ISSUE TITLE
Folder parsing in command line 

### ISSUE THREAD

**Issue by Anthys** [nesbox/TIC-80#866]
Hi,
When I want to launch Tic-80 with `./tic80 [DIR TO OPEN]`, it always show the message "parameter or file not processed" (except if the dir is `.`), but anyway open the right file when I dismiss this error message.
I'm on linux 16.04.

**Comment by Anthys** [comment]
Actually it's worse than that. If I execute `./tic80 [DIR TO OPEN]` and dismiss the error message, I will get the right directory under the surf menu (or the ls command), but if I run a card that has `dofile(thing.lua)` (with thing.lua located under the dir to open), I will get a message `thing.lua not found`, and the card won't start.

**Comment by RobLoach** [comment]
The first parameter should be the `cart.tic` file.... If you want code, it'll be...
```
tic80 cart.tic -code thing.lua
```

**Comment by Anthys** [comment]
I'm sorry if I wasn't clear. I'm not talking about running a certain card, but about opening TIC-80 in a certain directory. According to [this](https://itch.io/t/160754/solved-change-startup-path), `tic80 [DIR]` is something that should work. However, I believe it only works with '.' as [DIR], and not with a path.
I know that the `-code [FILE]` works, but it is not a reason to let the "dofile()" function remain buggy.

**Comment by nesbox** [comment]
`parameter or file not processed` message and `dofile(thing.lua)` are already disabled in .80
