### ISSUE TITLE
TIC-80 UWP Comand Line Parameters

### ISSUE THREAD

**Issue by mhykes** [nesbox/TIC-80#867]
Hi,

I'm using the Windows Store (UWP) version of the TIC-80.  After much trial I found how to launch this from the command line so that I can do the command line commands.  I'm using a shortened version of the steps shown here:  [Starting Windows 10 Store App From the Command Line](https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/starting-windows-10-store-app-from-the-command/836354c5-b5af-4d6c-b414-80e40ed14675?auth=1&page=1)  

I can get the TIC-80 to start on the command line without parameters, but as soon as I add any parameters I just get Windows Explorer.  Any suggestions, other than not to use the UWP version?

Having fun with TIC-80 in the mean time.

**Comment by nesbox** [comment]
unfortunately, I'm going to support UWP version anymore :(
pls, use native build
sorry
