### ISSUE TITLE
sokol-gfx: shader compatibility problem with older Intel GPUs

### ISSUE THREAD

**Issue by floooh** [nesbox/TIC-80#868]
Hi, just a heads up so you're aware of this problem:

https://github.com/floooh/sokol/issues/179

I'm thinking about going back to shader model 4, and possibly making the D3D shader model configurable via sg_shader_desc, no work has been done yet though.

**Comment by iryont** [comment]
I believe this is a good idea in general. It would be quite useful here since I have some customers with older hardware on which I would like to still use shaders which do not require SM 5.0.

**Comment by nesbox** [comment]
Thank you for letting us know.
