### ISSUE TITLE
It's time to change default palette

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#873]
I think DB16 palette become boring a bit and I propose to change it to something that looks more like a toy, `Sweetie16` palette is a good example I think. I told with GrafxKid (Sweetie16 author) and he doesn't mind.
Example, how it would look:
![image](https://user-images.githubusercontent.com/1101448/61135694-d7a87000-a4ca-11e9-9c7d-e2b78c293d52.png)
https://lospec.com/palette-list/sweetie-16

**Comment by kawa-yoiko** [comment]
I love the Sweetie 16 palette!! >ᴗ< Its wide range of shades really make for a nice UI. A major compensation would be the lack of a proper pinkish expression, but cartridges can have their own palette if they really need it.

IMHO dark red/green on dark blue in the code editor looks a bit strange... Orange and lime might be more suitable. The rest look great!

**Comment by StinkerB06** [comment]
Looks very juicy!

**Comment by raydeejay** [comment]
Do consider how this change will affect existing games :-)

**Comment by nesbox** [comment]
Existing games continue use db16 by default or palette defined in a cart. I don't see any problems here.

**Comment by raydeejay** [comment]
Uhhhhh right, it's saved in the cart :sweat_smile:

**Comment by RobLoach** [comment]
As long as the color slots stay the same on the [Palette list](https://github.com/nesbox/TIC-80/wiki/palette), I think this would be a great addition... Would you mind having this after the 0.80.0 release?

**Comment by nesbox** [comment]
@RobLoach What color slots do you mean? I don't get, sorry :)
I'm going to release the new palette with 0.80.

**Comment by RobLoach** [comment]
Sounds good with me :smile: 

I mean this....


|Color Name |Index|
|:---------:|:---:|:----:|
|Black      |0    |
|Dark Red   |1    |
|Dark Blue  |2    |
|Dark Gray  |3    |
|Brown      |4    |
|Dark Green |5    |
|Red        |6    |
|Light Gray |7    |
|Light Blue |8    |
|Orange     |9    |
|Blue/Gray  |10   |
|Light Green|11   |
|Peach      |12   |
|Cyan       |13   |
|Yellow     |14   |
|White      |15   |

Would be great to match the colors as close as possible in the new palette.... Example: 0 is still black, 15 is still white.

**Comment by nesbox** [comment]
ahh, ok, not sure color indexes will be saved

**Comment by kawa-yoiko** [comment]
> Would be great to match the colors as close as possible in the new palette

With Sweetie 16, the best possible arrangement has only 2 inconsistencies ↓
<img width="201" alt="palette" src="https://user-images.githubusercontent.com/45892908/61574453-99c2d180-aaf2-11e9-8f7c-21ac1a859e52.png">

However, I don't feel it's sensible to permute a palette to match another, as each palette has its own logic for indices. DB16 matches each of its more saturated colours with its dark counterpart 8 slots apart.
![DB16](https://raw.githubusercontent.com/geoffb/dawnbringer-palettes/master/DB16/db16.png)

Sweetie 16 is not designed with this in mind. It is instead created to hold a vibrant chromatic gradient in 0-7 and a "blue-scale" one in 8-15, each spanning a wide range of brightness.
![sweetie-16-32x](https://user-images.githubusercontent.com/45892908/61574372-7186a300-aaf1-11e9-8d6e-1086e35a7852.png)

DB16's design is fundamentally suitable for adding shades; Sweetie's is especially fit for gradients and bluish greyscales. These are their unique characters, not to be swapped ^ ^

If the colours are rearranged, the palette will lose its "flow" as an ordered set. It might take time to get used to a new one, but doing so will surely help us get the best out of it!

**Comment by trelemar** [comment]
I love the way the UI looks with this palette! The only thing I'd be worried about is how well games can use these colors. They are very vibrant. Db16 is very tried and true to work well for most things. I guess I will have to test the palette more to see is potential.

**Comment by saranvdev** [comment]
Sweetie 16 looks cool

**Comment by rahul625** [comment]
yes, it's time to change default palette =D

**Comment by rahul625** [comment]
when's 0.80 going to release anyways?

**Comment by rahul3125** [comment]
yes , change default palette at any cost please

**Comment by rahul3125** [comment]
didn't know about palette editor in sprite editor till now XD

**Comment by nesbox** [comment]
Working with the Sweetie16 colors, this is how Sprite editor will look soon
![image](https://user-images.githubusercontent.com/1101448/68376307-71bab500-0159-11ea-9eae-3a09bd498eba.png)

And the Code editor, I added `Bookmarks` support to the left panel, it should be useful for navigating
![image](https://user-images.githubusercontent.com/1101448/68376433-ac245200-0159-11ea-85ff-7b1e7ca240b4.png)

**Comment by RobLoach** [comment]
This also means the TIC-80 logo changes :wink: 

![1101448](https://user-images.githubusercontent.com/25086/68402622-9eff6700-0149-11ea-9c88-0c9578d1d58c.png)

**Comment by nesbox** [comment]
the latest editors
![image](https://user-images.githubusercontent.com/1101448/69901008-5aec3480-138c-11ea-9f9b-158db34a9e14.png)

**Comment by nesbox** [comment]
new sfx editor UI merged to master e7f4746
![screen](https://user-images.githubusercontent.com/1101448/76705705-eea30000-66f2-11ea-8091-a103d1755d6a.gif)

**Comment by StinkerB06** [comment]
Please add the wave envelope back! I can't make drums or FM-sounding instruments without it.

**Comment by nesbox** [comment]
@StinkerB06 yes, will be added on a separate screen

**Comment by StinkerB06** [comment]
Ok, I'll wait. Thanks for at least making progress, this UI looks sleeker than the previous one so far.

**Comment by nesbox** [comment]
all the screens changed to Sweetie16
closing

**Comment by LEMONTECHyt** [comment]
can you please make it so that i can design my own palette in the config to use forever please?
