### ISSUE TITLE
Pass nil/null to use default value

### ISSUE THREAD

**Issue by RobLoach** [nesbox/TIC-80#875]
Following a discussion on Discord, it would be great to have it so that when you pass `nil` or `null` as a function's argument, it would use the default value.

[`spr()`](https://github.com/nesbox/TIC-80/wiki/spr) for instance, it would be great if you could call....

```
spr(5, 100, 150, 10, nil, nil, nil, 2, 2)
```

Since `nil` is passed in for scale, flip and rotate, it would use the default value for those.

Scale: 1
Flip: 0
Rotate: 0

Should be able to apply the same logic to....

- [ ] Lua
- [x] JavaScript
- [ ] Wren
- [ ] Fennel

We could do it with [`lua_isnil()`](https://www.lua.org/manual/5.1/manual.html#lua_isnil) in Lua. [`duk_is_null()`](https://duktape.org/api.html#duk_is_null) in JavaScript, etc.

**Comment by nesbox** [comment]
I still unsure if it's ok to load default value if you pass `null` value, it looks strange a bit for me.
Anyway, I will ask colleagues what they think about the issue, maybe it's only strange from my side :)
Thanks.

**Comment by nesbox** [comment]
Also, I forgot to say that we always can use **Named Arguments** for such purposes.
We only have to write wrappers for all the API methods which will get a table with names and values as a parameter, for example, `spr()` calling would look like:
``` lua
spr{id=5, x=100, y=100, flip=2}
```
I like this idea more than passing `null` values.
What do you think?

**Comment by RobLoach** [comment]
Named arguments are a great idea for this! Didn't know Lua had those.

**Comment by RudenkoArts** [comment]
I agree that null is looking strange and unnecessary. You can always look in api and see what is default value. Also if it check for null in one place, and not for others its not good i think, and adds complexity.
