### ISSUE TITLE
Steam listing?

### ISSUE THREAD

**Issue by rogersachan** [nesbox/TIC-80#878]
Could be made free to play like retroarch is being handled, or priced as a donation the same way krita and other FOSS applications are listed on the windows store. You could also take advantage of Steam's controller handling and other related features.

**Comment by RobLoach** [comment]
RetroArch is going up on Steam. You can download the TIC-80 libretro core through it.

![Screenshot at 2019-07-17 22-18-21](https://user-images.githubusercontent.com/25086/61424219-ce5f3f00-a8e0-11e9-9264-7a5a1183669f.png)
