### ISSUE TITLE
Update Makefile for libretro

### ISSUE THREAD

**Issue by paradadf** [nesbox/TIC-80#884]
Hi! Thanks for this wonderful fantasy computer and also for the new libretro port. I'm looking forward on adding this to recalbox, and I'd like to know if updating the [Makefile](https://github.com/nesbox/TIC-80/blob/master/src/system/libretro/Makefile) is planned so it includes libretro PLATFORM definitions, so we can easily cross-compile this core.

Specially addressing @RobLoach for the work he has done on this matter.

**Comment by nesbox** [comment]
I propose not to use makefiles at all and add all the platform definitions to CMake file only

**Comment by RobLoach** [comment]
Glad you checked it out and adding it to Recalbox! We've updated the buildbot scripts to use cmake directly, and they seem to be building correctly:
https://github.com/libretro/libretro-super
http://buildbot.libretro.com/nightly/linux/x86_64/latest/

Would prefer to delete the mock Makefile instead, as that was just used temporarily when I didn't know buildbot had cmake support.

**Comment by paradadf** [comment]
Ok, I'll fight with cmake then :D 
Thanks again!

**Comment by RobLoach** [comment]
Mind if we keep this one open? Or make a new issue to get some of the defs in cmake? I'm curious myself.

**Comment by RobLoach** [comment]
@paradadf Did you figure anything out with the build process? I've found the builds that are pushed up to buildbot seem to be working, and Lakka is building TIC-80 okay for ARM devices.

**Comment by paradadf** [comment]
@RobLoach yes, tic-80 is already integrated in the mster branch of recalbox and it will be officially available on the soon to be released 6.1 version. I‘ve only tested it on rpi and pc, but it compiles fine on odroid boards too.

**Comment by RobLoach** [comment]
The [libretro-super](https://github.com/libretro/libretro-super) scripts have been much improved. You should be able to use...

```
SINGLE_CORE=tic80 FORCE=YES EXIT_ON_ERROR=1 ./libretro-buildbot-recipe.sh recipes/WHATEVERPLATFORMYOUWANT
```

**Comment by nesbox** [comment]
It seems it can be closed.
