### ISSUE TITLE
Console access from libretro‘s port

### ISSUE THREAD

**Issue by paradadf** [nesbox/TIC-80#886]
Hi! I was able to compile TIC-80, thanks!
I‘m wondering if it is possible to access the console for game edition/creation in the libretro port.
I‘ve tried these commands but they don‘t seem to work.
https://github.com/nesbox/TIC-80/wiki#hotkeys
Of course, ESC exists the emulator as that‘s the usual behavior wirh retroarch, but I would have expected that any of the other combos work.

**Comment by RobLoach** [comment]
It would be great to have console access. Haven't looked into the innards of the main tic80 program to see how that's achieved. Right now it's mimicing just the rendering examples found in `examples/sdl` or `examples/sokal`.

Don't want to duplicate effort, as much as possible.

**Comment by RobLoach** [comment]
While having console access, and the complete editor, would be nice in the libretro implementation. I think this is out of scope for the libretro player. Possibly look into the baremetal build? Thanks paradadf!

**Comment by nesbox** [comment]
Completely agreed, console access is out of the scope of libretro player.
