### ISSUE TITLE
High-res mode?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#887]
Maybe we can sacrifice some bits of the framebuffer to bump the resolution up a bit. This also reduces the number of on-screen colors. Old computers had this feature.

Maybe we can have dedicated register(s) somewhere at `0x3FFC`~`0x3FFF` to select the color-depth / screen-resolution ratio?

**Comment by StinkerB06** [comment]
Hmm... Maybe something like this?

| Mode | Color Depth | Resolution |
| --- | --- | --- |
| 0 | 4 | 240x136 |
| 1 | 2 | 480x136 |
| 2 | 2 | 240x272 |
| 3 | 1 | 480x272 |

**Comment by nesbox** [comment]
Not a bad idea and it also was discussed here #723.
Thanks.

**Comment by Quentie** [comment]
I love it. But maybe it would even be possible to allow the programmer to choose the resolution  & color depth dynamically e.g.: in cartridge metadata or as a function? 

Of course only as long as the required memory does not exceed what is actually available. 
This would also allow different aspect ratios.

**Comment by StinkerB06** [comment]
A function? We can obviously be able to change the mode during runtime, sure.

**Comment by Quentie** [comment]
Hm sorry what I was really hinting at was to not use an enum to choose the display mode but make resolutions (width and height) and color depth freely choosable as long as they fit into the underlying memory available. This would give even more flexibility than a simple enum

**Comment by Quentie** [comment]
Ah ok i see you wanted to store the mode in a register. Hm ok maybe than there is no space to store three values like width height and colordepth there?

**Comment by StinkerB06** [comment]
My initial idea is if the TIC-80 main screen was 480x272. If it's in 240x136 16-color mode, then the 240x136 image would be scaled 2x both horizontally and vertically. If one axis has double-resolution enabled (and thus the bit-depth of all pixels is reduced in half), that axis would be scaled 1x, with the other axis being at 2x. To compensate for the resolution being >256 pixels, we'd want to have 8 more bits of data for each screen offset value, stored in 2 of our 4 reserved bytes of VRAM, giving us 16-bit values.

SCN() and OVR() tricks that work for palettes and screen offsets might also be able to work with our depth/resolution ratio selection. For example, in SURF mode: TIC() draws the cartridge art at the appropriate resolution, SCN() sets the mode enum to 0 for OVR on line 0 (which is the only line it could be set on), and OVR() draws the HUD in mode 0.

**Comment by saranvdev** [comment]
What about a low-res mode for LOWREZ jam? 64x64

I have to use PICO-8 for the jam, because it has such mode

**Comment by Josh-McMillan** [comment]
If you read the rules for LOWRESJAM, you can use TIC-80, you just have to use only a 64x64 area, then leave the rest black/blank.

But I assume you would prefer to have a scaled 64x64, correct?

**Comment by StinkerB06** [comment]
I think I may have just made this up:
```
Bit:     76543210
0x3FFC:  ------NN   N: Mode enum (like above)
0x3FFD:  ---Y---X   X/Y: LSB of horizontal/vertical offset (only for double-size axis)
0x3FFE:  HHHHHHHH   Horizontal size plus 1. Multiply by 2 if double-size.
0x3FFF:  VVVVVVVV   Vertical size plus 1. Multiply by 2 if double-size. V≥144 is treated as 144.
```
If any resolution that costs >16320 bytes is specified, repeat framebuffer data (like `peek4(pixelOffset%32640)`.

**Comment by StinkerB06** [comment]
Hello anyone??

**Comment by Skaruts** [comment]
I'm just curious, how many colors would be available with 320x200 or 320x240 resolutions? (Because those are my favorite small resolutions. Especially the first one.)

**Comment by nesbox** [comment]
Close as part of  #723
