### ISSUE TITLE
Windowed mode on Android

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#888]

**Comment by BuoYancYdabl** [comment]
what is this and how it should work :)

**Comment by nesbox** [comment]
Something like
![image](https://user-images.githubusercontent.com/1101448/62025345-90b3bd80-b1e0-11e9-8095-8b86ab59761c.png)

**Comment by nesbox** [comment]
just tested the latest .80 Android build from https://builds.tic.computer/master
and it works windowed on my Samsung s5e (DEX mode)
pls, check it
