### ISSUE TITLE
pix() function poor efficiency

### ISSUE THREAD

**Issue by saranvdev** [nesbox/TIC-80#894]
Especially when the game runs in the web browser.
If we render 136x240 pixels using pix(), the game has 6 FPS in the web browser and 60 FPS in native version.

I had to change the rendering to spr() function for a jam game because of that. The same amount of pixels rendered by spr() has constant 60 FPS.

**Comment by nesbox** [comment]
Hi,
I don't think `pix()` has low efficiency, you are calling it too frequently, an about 32640 times per frame.
How many times do you call `spr()` per frame?

**Comment by StinkerB06** [comment]
https://tic.computer/play?cart=237#comment-1507

**Comment by saranvdev** [comment]
> How many times do you call spr() per frame?
510 times, but that results in the same amount of pixels placed, 32640

Well alright, looks like pix just isn't made for map rendering. I could try directly poking memory, there should be no difference if spr() does the same.

**Comment by CatsAreFluffy** [comment]
Using `poke(...)` to write 2 pixels at once works slightly better than `pix(...)` or `poke4(...)` (~30FPS with pix/poke4, ~40FPS with poke on a 3D program I'm working on)

**Comment by nesbox** [comment]
try to use this solution #896, when it will be implemented of course :)
