### ISSUE TITLE
[Sprite Editor] Swapping sprite colors

### ISSUE THREAD

**Issue by saranvdev** [nesbox/TIC-80#895]
A tool for changing all pixels of a clicked color to the selected palette color, in a current sprite area (1x1/2x2/4x4/8x8).

Ie.:
1. Select Swap tool & the replacement color
2. Click on the choosen image pixel
3. All pixels of the choosen color get replaced with the replacement color, in the selected sprite area

That would be really useful for designing sprites of all kinds, when we want to check how they look with different colors.

**Comment by StinkerB06** [comment]
You can use the `PALETTE MAP` memory region to change the draw palette during runtime.

This code draws a red version of TICSY, followed by the regular blue version:
```lua
remap={[2]=1,[8]=6}

function TIC()
	
	cls()
	
	-- Change draw palette
	for i=0,15 do poke4(0x7FE0+i,remap[i] or i) end
	spr(1,48,40,14,3,0,0,2,2)
	
	-- Revert draw palette back to normal
	for i=0,15 do poke4(0x7FE0+i,i) end
	spr(1,144,40,14,3,0,0,2,2)
	
end
```

**Comment by nesbox** [comment]
I think this is too much for such a small editor, let's create a palette list and change the palettes right in the editor to check how the sprites look with different colors.
