### ISSUE TITLE
macOS - Caps lock is detected as both Esc and Caps Lock when remapped to send Esc

### ISSUE THREAD

**Issue by adiron** [nesbox/TIC-80#897]
When setting caps lock to send esc via the macOS System Preferences [like so](https://imgur.com/a/ZYiKy5q), TIC-80 would recognize a keystroke on the Caps Lock key as BOTH escape AND caps lock.

Caps lock would not be enabled system-wide however.

System:

MacBook Pro (15-inch, 2017)
macOS Mojave 10.14.5 (18F132)

**Comment by kawa-yoiko** [comment]
Apparently this has been fixed with the dependency upgrades in 1342d0e.

**Comment by nesbox** [comment]
great, we can close it...
