### ISSUE TITLE
Any tips for changing the CRT filter?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#899]
I'd like to know how to remove the "curves" of the TIC-80 CRT filter, among other aspects.

**Comment by RobLoach** [comment]
If you use the RetroArch core, you could use any shader you want :wink: 

https://www.retroarch.com/index.php?page=shaders

**Comment by StinkerB06** [comment]
I'm talking about this:

![TIC-80 CRT Shader in config cartridge](https://user-images.githubusercontent.com/30059831/62658148-e4c74c00-b91c-11e9-8c2b-571c1679ffb0.gif)

**Comment by nesbox** [comment]
change `vec2 warp=vec2(1.0/64.0,1.0/48.0); ` to `vec2 warp=vec2(0.0,0.0);`
