### ISSUE TITLE
Properly name of cart.tic software in website

### ISSUE THREAD

**Issue by paradadf** [nesbox/TIC-80#901]
Hi! https://tic.computer/play shows games like `MARIO BROS?` or `8 BIT PANDA "VIRTUAL BOY" EDITION`, which contains character which are invalid in filenames like `?` or `"`. The names per-se aren't a problem, but downloading the softwares and naming the carts are, at least in order to have an unified convention, because all cartridges are named `cart.tic`. Would it be possible to name the carts officially?

**Comment by RobLoach** [comment]
If you're looking to quickly download the carts, I've put this together:
https://github.com/RobLoach/libretro-database-tic80

**Comment by paradadf** [comment]
Thanks! Really helpful. But I'm thinking more of ofical cart names à la no-intro (just to get an idea). This might be helpful as well ;)
https://gitlab.com/recalbox/recalbox/blob/master/package/recalbox-romfs/recalbox-romfs-tic80/roms/tic80/recalbox-tic80

**Comment by RobLoach** [comment]
This is pretty cool!

I've just used the titles for the names in thumbnails:
https://github.com/libretro-thumbnails/TIC-80/tree/master/Named_Titles

Figured the rest of the metadata could be useful in the database instead (cart ID, release date, etc).

**Comment by nesbox** [comment]
Fixed on the server, also client shows filesystem safe filename (cd18681), like:
```
 TIC-80 tiny computer
 version 0.90.1695-dev Pro (28fd122)
 https://tic80.com (C) 2017-2021

 hello! type help for help

>cd tic80.com
tic80.com>ls

[Devs]
[Play]
ascii_chase.tic
birdhead.tic
blobbyeyes.tic
bubblenoid.tic
clouds.tic
cloudy.tic
doodle.tic
fast_textured_raycaster_v_1_1.tic
game_of_life.tic
hello_world_matrix.tic
infestation.tic
invasion.tic
mctic.tic
micro_organisms_3.tic
minibros.tic
monster_spider.tic
motion.tic
mountain_journey.tic
pattern.tic
portal_2d.tic
rainy.tic
save_the_world.tic
sentinel.tic
spiral_world.tic
star_s_maze.tic
starzone_demo.tic
top_down_free_movement_demo.tic
transparent_skull.tic
vand_particles_pack.tic
yin_yang_world.tic
```
