### ISSUE TITLE
Palette loading bug

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#902]
First of all, the *.tic file format allows for chunk sizes smaller than the memory associated with them. This is a very simple compression method for carts, in case you have zero-filled bytes left at the end of the memory region. The remaining bytes that are not stored in the file are therefore zero when the chunk is loaded.

But this isn't fully true for the 48-byte palette memory though. When TIC-80 saves a cart, it applies this compression method to the palette chunk in the file (along with the sprites, map, sound, etc. chunks). The loading process is the slightly different part for palettes.

Instead of filling the remaining palette memory with zeroes (or black colors/intensities in this case), it instead uses the DB16 palette's byte values at offsets _n_...47 (where _n_ is both the size of the palette chunk in the cartridge file, and the offset of the first palette memory byte to not be present in the chunk). This may ruin a game's palette.

**Repro Steps:**
1. Create a new cart with `new` command.
2. Paste this palette string into the palette editor (saved chunk is 8 bytes, 40 bytes are filled):
```
00000000000000ff00000000000000000000000000000000000000000000000000000000000000000000000000000000
```
3. Save the cart with whatever filename.
4. Re-load the cart you just saved.

**Expected Result:** The palette should be two blacks, followed by a green and thirteen more blacks.
**Preserved Result:** The palette instead becomes two blacks, followed by a mint green, and then DB16 colors 3...15.

A workaround is to make color 15 have the darkest level of blue, i.e. RGB `#xxxx01`.

**Comment by RobLoach** [comment]
Worked for me... After I saved and quit, and re-ran, the palette data was saved.

![Screenshot at 2019-08-08 03-34-53](https://user-images.githubusercontent.com/25086/62683908-81c1cd80-b98d-11e9-937b-018b14adc9bc.png)

**Comment by StinkerB06** [comment]
I get something like this instead:
![TIC-80 Palette Bug](https://user-images.githubusercontent.com/30059831/62744329-00a11f80-b9fb-11e9-9108-f48d26c0f345.gif)

**Comment by RobLoach** [comment]
What version are you running?

**Comment by StinkerB06** [comment]
I'm running 0.80.0-dev Pro, which I compiled using the MinGW build
instructions. The bug also persists in 0.70.6.

**Comment by kawa-yoiko** [comment]
I have a fix in #915. The problem does not occur with carts saved in plain text format, which I guess is the reason @RobLoach did not reproduce it ^ ^

**Comment by StinkerB06** [comment]
Yes, I saved it in the default *.tic format that you can otherwise load in the free version.

Also @kawa-yoiko, I don't think plain-text was the format he used to reproduce it with. Plain-text is only available in the PRO version. You can see that his screenshot doesn't have that bank-switching button, so it's definitely the free version, as you can't save (or even load) plain-text carts.

**Comment by kawa-yoiko** [comment]
> You can see that his screenshot doesn't have that bank-switching button

Ah indeed, I missed that > <

**Comment by nesbox** [comment]
fixed
@StinkerB06 please check

**Comment by StinkerB06** [comment]
@nesbox Worked so far, awesome! But there's another problem, mentioned in the issue @Masternama-8000 referenced.
