### ISSUE TITLE
Disabling BUILD_DEMO_CARTS breaks the build

### ISSUE THREAD

**Issue by RobLoach** [nesbox/TIC-80#907]
After some testing on https://github.com/nesbox/TIC-80/commit/4eef02123e44de6e80392f4e69fd2ad4b5fbc556#diff-75218e1e64b8201a55c2ac2203e8970cL293 , I've found disabling building the demo carts can break some builds....

```
git clone https://github.com/nesbox/TIC-80.git
cd TIC-80
git submodule update --init --recursive
cd build
cmake .. -DBUILD_SDL=0 -DBUILD_SOKOL=0 -DBUILD_LIBRETRO=1 -DBUILD_DEMO_CARTS=0
make
```

```
[ 83%] Building C object CMakeFiles/tic80lib.dir/src/console.c.o
/home/rob/Documents/TIC-80/src/console.c: In function ‘getDemoCart’:
/home/rob/Documents/TIC-80/src/console.c:518:14: fatal error: ../bin/assets/luademo.tic.dat: No such file or directory
     #include "../bin/assets/luademo.tic.dat"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/tic80lib.dir/build.make:75: recipe for target 'CMakeFiles/tic80lib.dir/src/console.c.o' failed
make[2]: *** [CMakeFiles/tic80lib.dir/src/console.c.o] Error 1
CMakeFiles/Makefile2:78: recipe for target 'CMakeFiles/tic80lib.dir/all' failed
make[1]: *** [CMakeFiles/tic80lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
```

This may affect Android and Emscripten builds, since they have the demo carts disabled by default.

**Comment by nesbox** [comment]
You have to call `bash build_demos.sh` command before build if you disabled `DBUILD_DEMO_CARTS ` flag.

**Comment by msx80** [comment]
Are we sure that the way demo carts are handled is good? There's a number of issues with it. For example, building the bin2txt utility and then using it breaks any crosscompilation attempt. Also the files get placed in an unintuitive folder where they're probably not "cleaned" (i think this is why it often works when trying special builds, becouse they were produced in previous builds).

the build_demos.sh script solve some of these issues but it's outside of the build scripts and is not mentioned in documentation.

Perhaps we would be better off with simply committing the converted files alongside the original carts. They're seldomly changed anyway, if ever. Maybe a note in the readme of that folder, reminding to rebuild the dumps when making changes, could be enougth.

Also, on linux a similar output can be obtained with some standard commands like xxd, od or hexdump (i get that they're not available on windows).

IHTH

**Comment by nesbox** [comment]
@msx80 Maybe it's not an ideal solution, but I don't see any other better.
I use `build_demos.sh` script on Travis CI to build TIC for WASM and Android only, all the other platforms build without.
Also, what do you think if we add your BareMetal implementation as a submodule to `src/systems` and setup CI to automatically build it in Travis? 😃

**Comment by msx80** [comment]
> Also, what do you think if we add your BareMetal implementation as a submodule to `src/systems` and setup CI to automatically build it in Travis? 😃

I'd love it :) But consider that it depends on https://github.com/smuehlst/circle-stdlib, which also have a lot of dependencies. Obviously adding all that stuff to tic80 is not sensible, i don't know if there's a way to add them optionally in some way? Also i'm not an expert on Travis or CI so i'd need some help.

Also, some changes are required in the codebase, for example accessing the filesystem is done with some different calls and so fs.c needs different implementation for most functions. I did it [here](https://github.com/msx80/TIC-80/commits/master) with compiler switches over BAREMETAL, it's a bit ramshackle too.

Also, the implementation is not 100% complete. There's some minor issues and the gamepad support is not completed.

On the plus side, my RPI2 was able to run most games decently well, i think RPI3 will be even better and Circle is adding support for RPI4, which i heard is quite a leap in performances.

If that sounds acceptable to you, i can try to clean things up.

**Comment by RobLoach** [comment]
Leveraging submodules is a neat idea. We could move all `/demos` to a submodule, with the compiled demos for platforms that couldn't do the compiled/baremetal build.
