### ISSUE TITLE
Compilation error on OSX

### ISSUE THREAD

**Issue by JustGlowing** [nesbox/TIC-80#908]
If you compile on OSX following the instructions in the readme you get the following error:

```
CMake Error at 3rd-party/sdl2/CMakeLists.txt:2 (message):
  Prevented in-tree built.  Please create a build directory outside of the
  SDL source code and call cmake from there


-- Configuring incomplete, errors occurred!
```

This solved the problem for me:

```
cd build
cmake ..
make -j4
```

Also, to build the pro version I had to go in the `CMakeLists.txt` and set `BUILD_PRO` to `ON`.

**Comment by RobLoach** [comment]
I believe all documentation is updated.

**Comment by JustGlowing** [comment]
Great!
