### ISSUE TITLE
"_TIC80" userdata variable?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#910]
What's the purpose?
![TIC80 userdata](https://user-images.githubusercontent.com/30059831/63344375-284e8c80-c305-11e9-8f22-4a74a7e44b02.gif)

**Comment by nesbox** [comment]
For internal purposes, this is the address of LUA VM.

**Comment by StinkerB06** [comment]
Also, the bit32 library appears to be missing. It shows up in the [latest Lua build](http://luabinaries.sourceforge.net/), but it's not available in TIC-80 Lua.

**Comment by nesbox** [comment]
removed `_TIC80` here fe76c4f
also, the API should works a bit faster now :)
