### ISSUE TITLE
Integrating Raspberry Baremetal build

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#912]
Hi there, to continue discussion on #907 , i made some tests and updated the build of my baremetal port to the latest TIC80 sources.

In the end, modifications on the codebase is limited to the following:

- fs.c: this is the biggest change, most of the primitive functions in here need a different implementation.
- tic80_types.h: need changes to avoid a type conflict.
- CMakeList.txt: a block for Baremetal is added at the beginning as a preamble, to set all variables etc.

Everything else is new files that could go in any folder.
The strategy i used is to build tic80lib as usual (i haven't added a new target) with BAREMETAL switch, which is basically just crosscompiling it to ARM with some custom stuff for RPI. Then i made a separate program (the kernel), based on circle examples code, that link to the tic80lib.a. This is a separate Makefile that include stuff from circle and circle-stdlib, not sure it is possible to include it in the main CMake build file.

I think we could put the kernel on src/system/baremetalrpi and the Makefile on build/baremetalrpi, or some similar combination. In build/baremetalrpi i can put a readme with all steps to checkout circle and build everything.

If you're ok i can prepare a pull request (in a couple of weeks, i'm leaving for vacation soon :D ). Obviously everything can be changed later if we find a better fit.

I was able to build TIC80 with all languages except squirrel (for some reason it breaks crosscompilation, i think it has some dangling arm switch inside somewhere).

**Comment by nesbox** [comment]
Sounds awesome, as for `fs.c` I think we could make some kind of abstraction layer for the file system operations, will do after your PR...
Thank you.

**Comment by nesbox** [comment]
will setup CI scripts soon
thanks

**Comment by msx80** [comment]
Hi there, you may want to wait for my next pr (with some more hardware support) before setting up ci, as the building instructions have changed a little

**Comment by nesbox** [comment]
Hi,
I tried to setup CI for the bare-metal build but with no success, seems we are a bit outdated with the Circle repo now.
@msx80 could you pls look at?
Thank you.

**Comment by msx80** [comment]
Hi there, i'll take a look! With RPi4 and RPI400 it starts to get interesting.
But i'll take some time as i'm a bit busy lately..

**Comment by nesbox** [comment]
Hi, thank you 👍

**Comment by msx80** [comment]
I gave a try, i've updated some stuff and can compile some of the libs, but zip is giving me errors.

`In file included from /home/nicola/TIC-80/vendor/zip/src/zip.c:47:
/home/nicola/TIC-80/vendor/zip/src/miniz.h: In function 'mz_zip_set_file_times':
/home/nicola/TIC-80/vendor/zip/src/miniz.h:4479:11: error: implicit declaration of function 'utime'; did you mean 'ctime'? [-Werror=implicit-function-declaration]
 4479 |   return !utime(pFilename, &t);
      |           ^~~~~
      |           ctime
cc1: all warnings being treated as errors
`

Seems some shenanigans with utime.h. In miniz.h there's a switch that seems to be added just for that (MINIZ_NO_TIME), but if i define it, some other things break:

`In file included from /home/nicola/TIC-80/vendor/zip/src/zip.c:47:
/home/nicola/TIC-80/vendor/zip/src/miniz.h: In function 'mz_zip_writer_add_file':
/home/nicola/TIC-80/vendor/zip/src/miniz.h:6331:8: error: implicit declaration of function 'mz_zip_get_file_modified_time' [-Werror=implicit-function-declaration]
 6331 |   if (!mz_zip_get_file_modified_time(pSrc_filename, &file_modified_time))
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
`

I'm not sure what to make of it, seems like it doesn't handle the switch correctly as it still uses some functions that are switched off. I've tried to update to the latest version of the library but the behaviour doesn't change.

I'll look deeper into it when i'll have some more time, in the meantime i report the progress, if anyone has some idea it's welcome :D

**Comment by nesbox** [comment]
I'll try to fork the `zip` lib and fix it asap...

**Comment by nesbox** [comment]
I've fixed the compilation with `MINIZ_NO_TIME` here fc28282, pls update submodules.
@msx80

**Comment by msx80** [comment]
Thanks @nesbox! After spending some time on it i have good news: i was able to build and run tic80 again! :)
I'm sure the build system could be cleaned up a lot (i went through trial and error), but it's working, and i haven't touched anything outside of my folders, other than the main CMakeLists.txt

Now, i have the weirdest bug on keyboard input: i don't seems to be able to type anything on either the console or the code window. Keyboard is working and tic80 is responding to some keystrokes: cursors, function keys, ENTER, CTRL-R, CTRL-C/V/X, delete, backspace all works, but if i type any command like "ls" or "run", nothing appears (when i hit ENTER it gets me a new line but no text).
Since CTRL-R is working, i would expect to be able to type the letter R. Any idea on what could cause this behaviour ?

PS when i get it working, should i submit the changes via PR ?

**Comment by nesbox** [comment]
Awesome news!!! :)
I think I know the reason for the keyboard bug and just pushed a fix 68015d1.
Pls submit the changes via PR if not difficult. Will it work with the Github Actions?
Thank you.

**Comment by msx80** [comment]
I had the feeling it was some bug on the mainstream :)

I'll submit via PR, no problem. As soon as i fix a couple of bugs on file access.

Sorry but i'm totally ignorant about Github Actions and CI in general, no idea how they work. I'll update the [baremetal build guide](https://github.com/nesbox/TIC-80/blob/master/build/baremetalpi/README.md) with the new procedure, it's mostly executing configure and make scripts and the like. The step where you have to change a file is gone i think.

**Comment by nesbox** [comment]
I'll add Github Actions myself if you provide detailed build instructions, no problems here.
Thanks.

**Comment by msx80** [comment]
Ok, it works now, i located that nasty memory corruption bug (took a whole day but ok) and it's ok. The build process is updated, as long as you can run arbitrary commands on Actions, it should be possible to add it.

I'll fix some remaining minor issues in the future. Hopefully after putting my hands on a RPi4 (or 400)

**Comment by nesbox** [comment]
Merged, will try to setup CI soon.
Thank you.

**Comment by nesbox** [comment]
Baremetal build added to Github Actions a4df306.
