### ISSUE TITLE
TIC-80 0.80.0-dev Can't run program

### ISSUE THREAD

**Issue by Masternama-8000** [nesbox/TIC-80#913]
This is Version **0.80.0-dev**

Downloaded TIC-80 latest version opening your program. pop up see error  

![tic-80 error 0 80 0-dev](https://user-images.githubusercontent.com/54476488/63638814-76b7ae80-c6aa-11e9-9f83-6774cebaeee9.jpg)

**Comment by nesbox** [comment]
seems, you downloaded `tic80-MinGW-w64.zip`, it depends on some mingw libs
so, install MinGW or try another build, `tic80-MSVC.zip` for example
