### ISSUE TITLE
Export and publish games instruction

### ISSUE THREAD

**Issue by JustGlowing** [nesbox/TIC-80#922]
I made a small game and now I have the following questions:

1) How do I export my game in html? When I run `export html` I get `unknown parameter: html`.

2) How do I submit my game to this https://tic.computer/play ?

PS: I have the pro version that I compiled my self.

Thanks for your work, TIC-80 is truly amazing!

**Comment by nesbox** [comment]
Hi, 
1. What TIC version do you use? Because html export is broken in .80, in case you build TIC from sources.
2. Just register on the website, save cover for your cart directly in TIC and upload the cart.

**Comment by JustGlowing** [comment]
I'm using 0.80.0, I'll update it later.

I'll definitely update my game once the final levels are done ;-)

**Comment by JustGlowing** [comment]
Here's my submission https://tic.computer/play?cart=939

**Comment by nesbox** [comment]
@JustGlowing great game, thank you :)
