### ISSUE TITLE
Website "store" improvements

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#923]
Hi there, just a low priority issue, but i think the website "play" tab could use some updates. I propose the following:

1. a "developer" page. Basically you click on the author of a cart and you get a page where you can see all of his/her carts. Actually something similar is already present when you click on your name (https://tic.computer/profile). It would be nice both to search other games similar to one you liked and to share you own "production" with a single link.

2. A "popular this month" (or "this semester" or "this year") that shows like the "popular" tab but limited to carts uploaded the last month. This is becouse by now entries on the "popular" tab are more or less set on stone (they are unreacheable and being there gets the most visibility), while the new has a big turnover and stuff quickly disappear. Main page could show a selection from Popular this month and a selection of Popular of all times. This changes will give more exposure to new games that are good.

Also #616 if it sounds sensible.

I think the sources of the website are closed but if you want i could offer to help.

**Comment by Masternama-8000** [comment]
Yes, Secret Agents is copy game by M4jestik so I uploaded this game.

**Comment by borbware** [comment]
"Popular this month" would be so good. It's quite difficult to find newer quality titles from the website! Another option would be a "Featured" section where some titles are hand-picked for showcase, and are listed newest first.

**Comment by nesbox** [comment]
Unfortunately, I'm not a web developer and do website things very slow.
As a variant, I could open website sources and let the community improve it.

**Comment by RobLoach** [comment]
If you're concerned about opening it up to everyone, a small team could do wonders. Depending on stack, I'd be willing to help out a bit.

**Comment by nesbox** [comment]
Server: `node.js` + `sqlite3` + `EJS`
Client: `jquery` + `bootstrap`

**Comment by msx80** [comment]
i think opening website sources, either privately to a small team or publicly would be the best choice. I'd offer to work but lately i'm a bit swamped with my job and have not much time for hobby coding.

**Comment by jf1x** [comment]
I'm a web dev and would be happy to submit some PRs for the website, if you choose to open it.

**Comment by nesbox** [comment]
I added `new & popular`, `most recent` and `top rated` filters to the cart categories.
Where `new & popular` shows carts uploaded for the last month.

![image](https://user-images.githubusercontent.com/1101448/106354623-3f6c1900-6304-11eb-9f82-561637751e88.png)

**Comment by nesbox** [comment]
Added `Most popular developers` page https://tic80.com/dev

![image](https://user-images.githubusercontent.com/1101448/106481255-4be7a180-64bd-11eb-9e6a-02b40104ddac.png)

**Comment by msx80** [comment]
Awesome, thanks :)

**Comment by msx80** [comment]
There's also a [per-dev page](https://tic80.com/dev?id=1409), finally i can share my stuff with a single link 👍 

Also: must.. resist.. urge.. to.. compete.. for.. top.. developers.. :)

**Comment by nesbox** [comment]
SURF also shows popular developers list as well as `New/Recent/Top` filters.

![surf](https://user-images.githubusercontent.com/1101448/106603265-21eeb780-656f-11eb-8951-fa3ff5868268.gif)

**Comment by borbware** [comment]
Amazing! this makes SURF much nicer to use.

One SURF feature that I'd like to see in the future would be seeing all your liked games listed. It'd feel like you have your own TIC-80 game library :> 

I do realise that this might not be that simple to implement, as it requires logging into your account. however.

**Comment by nesbox** [comment]
@borbware Great idea, thanks 👍
