### ISSUE TITLE
Video resolution screen

### ISSUE THREAD

**Issue by Masternama-8000** [nesbox/TIC-80#925]
I found this

| Video Plugin Name  | Resolution           |
| :---------------------: | :-----------------: |
| SDL                           | 512x288              |
| Sokol                        | 769x457              |

**Comment by Masternama-8000** [comment]
@nesbox This **SDL** is default screen size. 

**SDL** = horizontal screen is long. vertical screen is short.
**Sokol** = horizontal screen is long. vertical screen is long. 

Whatever Screen is border color called **black.**

| Name               | RAM Address  |
| :---------------------: | :---------------------: |
| Screen border | 0x3FF8             |

**Comment by nesbox** [comment]
ok, SDL renderer has 2x scale, when Sokol 3x :)
It's not an issue :)
closing...
