### ISSUE TITLE
TIC-80 0.80.0-dev crashes app in android

### ISSUE THREAD

**Issue by Masternama-8000** [nesbox/TIC-80#926]
I download new latest version. This android version is **4.1.2** (Old).
Open your **TIC-80** app. While 5 seconds after app gets crashed.

![Screenshot_2019-09-09-17-04-50](https://user-images.githubusercontent.com/54476488/64780068-1e731e80-d57d-11e9-8d8f-593b0f5fb413.png)

Results

| Device Name                        | Android version   | Supported                        |
| :-------------------------: | :----------------:| :---------------------:  |
| Samsung Galaxy Tab 2       | 4.1.2                      | No **(Not supported)** |

This older version is not supported.
This new version is supported. 

This Android older 4.1.2 version [ ❌Not supported] can't run TIC-80 New "0.80.0-dev" version. crashes a app. New android version [ ✔Supported] it works TIC-80 "0.80.0-dev".

builds.tic.computer

**Comment by StinkerB06** [comment]
Does it work in Android 5 (lolipop)?

**Comment by Masternama-8000** [comment]
@StinkerB06 Yeah, This older android version is running TIC-80 **0.80.0-dev** is doesn't work ;(. TIC-80 old version it works 0.70.7****.

**Comment by Masternama-8000** [comment]
![Screenshot_20190915-185909](https://user-images.githubusercontent.com/54476488/64922386-516f1980-d7ec-11e9-95e5-7633a3749238.png)

It works!, Android version **6.0.1** Thanks!.

**Comment by Masternama-8000** [comment]
| Device Name                                  | Android version     | Supported                                       |
| :-------------------------------------------------: | :---------------------------: | :-------------------------------------------------: |
| Moto G Turbo Edition                   | 6.0.1                         | Yes **(Supported)**                     |

**Comment by Masternama-8000** [comment]
Closing...

**Comment by Masternama-8000** [comment]
Closed Issue
