### ISSUE TITLE
Load code from JS file

### ISSUE THREAD

**Issue by ValentinChareyre** [nesbox/TIC-80#927]
Hello ! 🙂

I have bought the PRO version of TIC-80 in order to save my cartridges into text format in order to work with a friend on it using a versioning system (he does the art while I code).

I would like to have a cartridge for the art and one for the code:

- art.tic : Contains the sprites, maps, musics, sfx (empty code)
- game.js : Contains the **javascript** code (empty art)

According to the documentation, I should be able to load a cartridge using `load art.tic` as "main cartridge", and then use `load game.js code` to "overwrite" the loaded code using the `game.js` cartridge.

However, it does not work. It seems like only `tic` cartridges can be loaded this way (however, using `load game.js` works fine and the game can run, without any art obviously)

----

Steps to reproduce:

1. Open TIC-80 0.70.6 **PRO**

2. Create a new directory
`> mkdir load-js`
`> cd load-js`

3. Create a new TIC cartridge and save it
_Note, any other format will give the same result_
`> new`
`new cart is created`
`> save art `
`cart art.tic saved!`

4. Create a new **JAVASCRIPT** cartridge and save it
`> new js`
`new cart is created`
`> save game.js `
`cart game.js saved!`

5. Change the code of the javascript cartridge
Replace `cls(13)` by `cls(0)` for instance, or change the `Hello World` message
Don't forget to save using CTRL + S

6. Load `art` cartridge
`> load art.tic`
`cart art.tic loaded!`
`use RUN command to run it`

7. Load the **CODE** of the `game.js` cartridge 
`> load game.js code`
`cart loading error` 😭

----

I **need** to use javascript file format. The `tic` format seems to be binary and even if I put only my JS code (with the header comments) into a `tic` file, I get the error `the code is empty` when running the cartridge.

I have to mention that, the only workaround I have found is running TIC-80 from the command line

```bash
# tic80 has been added to my path
> tic80 art.tic -code game.js
```

PS: The reason I **need** javascript as code format is because I would like to use a transpiler (Typescript) to create my javascript final file.

Thanks in advance, have a nice day !

**Comment by RobLoach** [comment]
`tic80` does not run .js or .lua games. Only .tic files... So `-code file.js` is how you inject the code into the cart.

Another fancy thing you can do is...

```
tic80 cart.tic -sprites sprite.gif -code index.js
```

To have it also inject the spirtes.

I did this with [Threes-TIC80](https://github.com/robloach/threes-tic80). There's a Makefile in there you can check out.

**Comment by ValentinChareyre** [comment]
>`tic80` does not run .js or .lua games. Only .tic files... So `-code file.js` is how you inject the code into the cart.

I am able to run `tic80 code.js` from OS command line, and `load code.js` + `run` from TIC-80 command line too.

----

This is not the problem here, I want to load a tic game cart from TIC-80 command line and use the code of another cart, using TIC-80 command line too.

**Comment by StinkerB06** [comment]
You can write an interpreter program that appends your JS code to the end of a *.tic file:
https://github.com/nesbox/TIC-80/wiki/tic-File-Format

However, the code that you want to append must be ≥ the size of the code text that's already in the *.tic file, as the loader appears to not clear the code memory when loading multiple code chunks to the same bank number. This causes overlap and may cause the code to crash, or the JS/Lua/whatever compiler to fail.

**Comment by ValentinChareyre** [comment]
@StinkerB06 Thanks for the suggestion, I started to code a small script to put the generated JS script inside my _art_ (JS) cartridge before noticing the `load code` option I found on [Twitter](https://twitter.com/tic_computer/status/872120196525428737).

I am disappointed the `load code` does not work for JS. Will try to inject inside TIC cartridge.

**Comment by StinkerB06** [comment]
https://tic.computer/play?cart=951
I just put together a cart with two code (type `0x05`) chunks. The website got the metadata from the 2nd code chunk instance (that I manually appended to the end of the file). The TIC-80 app also loaded from the 2nd instance and executed whatever was in it.

**Comment by nesbox** [comment]
@ValentinChareyre what if you save your game using `save game.js` command
it will look like:
```js
// title:  game title
// author: game developer
// desc:   short description
// script: js

var t=0
var x=96
var y=24

function TIC()
{
	if(btn(0))y--
	if(btn(1))y++
	if(btn(2))x--
	if(btn(3))x++

	cls(13)
	spr(1+((t%60)/30|0)*2,x,y,14,3,0,0,2,2)
	print("HELLO WORLD!",84,84)
	t++
}

// <TILES>
// 001:efffffffff222222f8888888f8222222f8fffffff8ff0ffff8ff0ffff8ff0fff
// 002:fffffeee2222ffee88880fee22280feefff80fff0ff80f0f0ff80f0f0ff80f0f
// 003:efffffffff222222f8888888f8222222f8fffffff8fffffff8ff0ffff8ff0fff
// 004:fffffeee2222ffee88880fee22280feefff80ffffff80f0f0ff80f0f0ff80f0f
// 017:f8fffffff8888888f888f888f8888ffff8888888f2222222ff000fffefffffef
// 018:fff800ff88880ffef8880fee88880fee88880fee2222ffee000ffeeeffffeeee
// 019:f8fffffff8888888f888f888f8888ffff8888888f2222222ff000fffefffffef
// 020:fff800ff88880ffef8880fee88880fee88880fee2222ffee000ffeeeffffeeee
// </TILES>

// <WAVES>
// 000:00000000ffffffff00000000ffffffff
// 001:0123456789abcdeffedcba9876543210
// 002:0123456789abcdef0123456789abcdef
// </WAVES>

// <SFX>
// 000:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000304000000000
// </SFX>

// <PALETTE>
// 000:140c1c44243430346d4e4a4e854c30346524d04648757161597dced27d2c8595a16daa2cd2aa996dc2cadad45edeeed6
// </PALETTE>


```
You see, it contains all the spites/sfx/... data,
and you can run it using `tic80 game.js` cmd,
also, it supports live code reloading if you edit `game.js` in an external editor
I think this should solve your needs (works in PRO only).
Please check and let us know, thanks...

**Comment by ValentinChareyre** [comment]
I already use JavaScript format for my cartridges. What I want is one cartridge containing the art (edited using the Sprite, Map and Music editor of TIC-80) and one cartridge for the code (generated using a transpiler).

Then, I wanted to use the `code` option of TIC-80 in order to load the 2nd cartridge. For now, I only have the possibility to load it using my OS command line.

Either I use this last technique, or I will try to merge the code cartridge into the art one. Didn't take the time to do it yet.

**Comment by ValentinChareyre** [comment]
I already use JavaScript format for my cartridges. What I want is one cartridge containing the art (edited using the Sprite, Map and Music editor of TIC-80) and one cartridge for the code (generated using a transpiler).

Then, I wanted to use the `code` option of TIC-80 in order to load the 2nd cartridge. For now, I only have the possibility to load it using my OS command line.

Either I use this technique, or I try to merge the code cartridge into the art one after my code has been transpiled into JS. Didn't take the time to do it yet.

@nesbox ?
