### ISSUE TITLE
[Libretro] update core to latest dev build

### ISSUE THREAD

**Issue by QcSamuel** [nesbox/TIC-80#929]
Hi i'm making a issue to ask to update the libretro core to the latest dev build
this will fix the small font issue and the performance regression that affect the current version.

to replicate the performance issue play fps80 https://tic.computer/play?cart=237 on the tic-80 core and the game speed will be slow then try the latest standalone dev build 
http://dev.nesbox.com/master and the game will play at normal speed. this is not a libretro bug only older tic-80 builds have the same issue

**Comment by RobLoach** [comment]
I'm not quite sure what would cause the slowdown. What hardware are you running the libretro core on? I've found CPU intensive carts can get slow on a RPi.

Brought the latest into the fork over at https://github.com/libretro/TIC-80/ ... Buildbot should re-build it soon. I'm able to run FPS80 on RetroArch on my desktop, wihtout slowdown.

Been wanting to put together a suite of bunny benchmarks across the different languages to help test perf.

**Comment by RobLoach** [comment]
Could be just that this cart is CPU intensive... The `retro_run()` call happens 60 times a second, on a single thread.

**Comment by QcSamuel** [comment]
my cpu is i5-4440 and the slowdown was there on a older dev build try the oldest build then the 2019.07.28 with fps80

**Comment by QcSamuel** [comment]
my cpu is i5-4440

**Comment by RobLoach** [comment]
@QcSamuel Thanks a lot for opening this up. I've created an issue specific to the libretro core over at: https://github.com/libretro/TIC-80/issues/1

I've also made a semi-benchmarking tool over at https://github.com/RobLoach/Bunnymark-TIC80 . Will be curious how these compare. Thanks!
