### ISSUE TITLE
Lack of Lua "bit32" library?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#932]
Can you add the bit32 library back? It's still available in Lua 5.3 standalone.

**Comment by Masternama-8000** [comment]
@StinkerB06 Yes, I upgrade Lua 5.3?.

**Comment by Masternama-8000** [comment]
Also available latest version Lua **5.3.5**. Well **TIC-80** **0.80
0-dev** version see new code, script & api. With **Lua 5.3.5**.

Link
https://www.lua.org/download.html

**Comment by nesbox** [comment]
@StinkerB06 why do you need `bit32` library?
when Lua 5.3 has all the bitwise operations https://www.lua.org/manual/5.3/manual.html#3.4.2

**Comment by StinkerB06** [comment]
There are some functions like replace and rotate, which are otherwise not available with the 5.3 bitwise operators.

**Comment by nesbox** [comment]
ok, as I see it's marked as deprecated
https://github.com/nesbox/3rd-party/blob/62c418b272da3104df4a04a5a280311892d62df5/lua-5.3.1/src/lbitlib.c#L227
It won't be added, sorry
