### ISSUE TITLE
Please fix website's notifications page

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#936]
It's still showing a CloudFlare 502 error page, saying that the page is offline. @Masternama-8000 reportedly doesn't suffer from this issue, according to a screenshot he sent to me on Hangouts.

I've already told you more than a year ago in #606 to fix it, you said you'll "look at the issue soon", but you haven't actually fixed it yet so far.

**Comment by StinkerB06** [comment]
Clicking the bell marks all unread notifications as read correctly, it's just the page itself not showing up.

**Comment by StinkerB06** [comment]
Also, the CloudFlare that's causing this error is the one in Sacramento, CA. I don't live in this city, but I still live in California. Try to contact them to report that tic.computer/notifications is not loading.

**Comment by Masternama-8000** [comment]
@StinkerB06 Thanks for the report!. 

Now what happens....

9 September 2019

@StinkerB06 your live is **United States (California)**. TIC-80 website found notifications. I cannot show notification. What happended TIC-80 website. See **Error 502** message. So @nesbox  server's Server is data connection failed. 

![error 502](https://user-images.githubusercontent.com/54476488/65816184-51bcdb00-e216-11e9-8316-99f629e8483a.jpg)

@Masternama-8000 My live is **Maharashtra** **(India)**. I new found 1 notification. See nothing happens tic.computer/notifications.

Thank you

**Comment by Masternama-8000** [comment]
https://lh3.googleusercontent.com/-gESPjIB2o4g/XXYzWDPj-2I/AAAAAAAAEhU/iUnJnru_TXERZAiib1-p9lUUZMlsyhEngCK8BGAs/s512/2019-09-09.png

**Comment by Masternama-8000** [comment]
![2019-09-09](https://user-images.githubusercontent.com/54476488/65816281-4f0eb580-e217-11e9-8c01-75cd144211ee.png)

**Comment by StinkerB06** [comment]
After this error shows up, back out. Reload the page. It takes forever to load (longer than usual). Yeah, something might be very wrong with @nesbox's server.

**Comment by StinkerB06** [comment]
I just created a 2nd account on the TIC-80 site. It's notifications page shows up just fine:
![image](https://user-images.githubusercontent.com/30059831/65818053-acc4e280-e1c2-11e9-8538-377b28848661.png)

It could be a glitch in my main account. The username is `StinkerB06` and the email is `stinkerb06@gmail.com`.

**Comment by Masternama-8000** [comment]
It's another account. There is Username: `Stinker2006` Email: `stinkerb066@gmail.com`

**Comment by StinkerB06** [comment]
@Masternama-8000 Can you please stop suggesting alternative email addresses?

**Comment by Masternama-8000** [comment]
Ok
