### ISSUE TITLE
(0.80.0-dev Pro) Very old carts have all-black palette

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#939]
The fix done by 15eb3a4 doesn't appear to be a full fix. I've noticed than an old cart (https://homineludens.itch.io/tic-simon-say) has an all-black palette (except for the red gradient), when the game is supposed to use the DB16/config palette:
![Simon all-black](https://user-images.githubusercontent.com/30059831/65978489-a9cb2b80-e428-11e9-9294-e56affe5c73b.gif)

These old games don't have a palette chunk, because these old TIC-80 versions were yet to have a palette editor. This is the reason for TIC-80 loading the config palette first before loading the game's own palette. To fix this:

_**Load** the config palette when there **isn't** a palette chunk at all_, or _**don't load** the config palette when there **is** a palette chunk (including 0-length chunks)._

**Comment by Masternama-8000** [comment]
@StinkerB06 Cartridge is **older** than **less 3 years**. **TIC-80** Cartridge bank is **OK**. Now **palette** chunk is **can't load** your palette. **TIC-80** cartridge inside **palette**. **Palette** is damaged to the chunk palette. Palette chunk **Doesn't** loaded so **Palette** gets corrupted.

**Comment by Masternama-8000** [comment]
https://github.com/nesbox/TIC-80/issues/902

**Comment by nesbox** [comment]
@StinkerB06 you are right, thanks
fixed here 9729ba7 as part of #902 issue
closing as a duplicate
