### ISSUE TITLE
TIC-80 SURF: Show the cover image resolution is 480x272 after TIC-80 Cover Image is broken

### ISSUE THREAD

**Issue by Masternama-8000** [nesbox/TIC-80#940]
I found this:
[COVER IMAGE > 240X136 TEST](https://tic.computer/play?cart=959) 

**TIC-80 Cover image** change your **Cover image** resolution **240x136** to converted **480x272**.

## What happens if.....

**TIC-80 SURF** see what happens changed **Cover image** **480x272** resolution show a appears **image**.

##
This **480x272** resolution **Cover image**. **TIC-80 SURF** version **Cover image** looks like **damaged** **image**.

![Screenshot_2019-10-01-20-56-12](https://user-images.githubusercontent.com/54476488/66053942-d67a6280-e550-11e9-87f2-e37bc2aa8523.png)

Maybe **Cover image** gets corrupted :(.

_**I fix this!**_

**Comment by Masternama-8000** [comment]
Reopen the **TIC-80 SURF** see **random** cover image **corruption**

![randomcover](https://user-images.githubusercontent.com/54476488/66057100-c31dc600-e555-11e9-99c5-421606daa6eb.gif)

**Comment by Masternama-8000** [comment]
I removed **exit ()**. While running **TIC-80 Cartridge** see through **without** cover image.

![screen without cover](https://user-images.githubusercontent.com/54476488/66057964-33791700-e557-11e9-9866-ab4ebe637547.gif)

**Comment by Masternama-8000** [comment]
It's cover image bug

**Comment by nesbox** [comment]
I don't see any problems here, you are using a cover image with the wrong format and want to see normal cover?
As a solution, I can check the cover image format on start and show an error if it wrong.

**Comment by StinkerB06** [comment]
@nesbox That cover image is a 480×272 GIF. That is four times the normal TIC-80 resolution. Perhaps you can:
- Scale the cover image to fit the normal 240×136 resolution
- Allow animated GIFs to play (https://tic.computer/play?cart=567)
- Draw the cover image on the TIC layer and the rest of the SURF HUD on the OVR layer. Calculate the 16 most-frequent colors in the cover image and use as the TIC palette, and use the DB16/config palette as the OVR palette.

**Comment by Masternama-8000** [comment]
@StinkerB06 @nesbox This **TIC-80 SURF** version **Cover image** changed resolution. Well, This **Cover image** **_(Changed resolution)_** gets **broken**. Now **Normal Cover Image Resolution** _**(240x136)**_ is **OK** it's fixed **cover image**.

**Comment by nesbox** [comment]
fixed broken image in the Surf 9d1943d
