### ISSUE TITLE
Please add option to export game ( html ) from web ( browser ) version 

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#946]
Please add option to export game as html file from web browser version because i can't install   TIC-80 in windows version , i get error , i've tried lot of times before , so please sometime in future make browser versions export html games

**Comment by StinkerB06** [comment]
What's your OS and PC specs?

**Comment by nesbox** [comment]
@potato25 what error do you get on Windows?

**Comment by potato25** [comment]
![Capture](https://user-images.githubusercontent.com/56357462/66736938-3d204a00-ee88-11e9-840b-f637f86364bc.PNG)

**Comment by potato25** [comment]
i have windows 7 32-bit

**Comment by nesbox** [comment]
@potato25 could you pls find an earlier version here https://github.com/nesbox/TIC-80/releases which works on your PC?

**Comment by potato25** [comment]
it's ok , i use browser version

**Comment by Masternama-8000** [comment]
@potato25 what's a crashed TIC-80 program?. You got error?

**Comment by Masternama-8000** [comment]
Look picture while running TIC-80 program after crashed looks strange

**Comment by StinkerB06** [comment]
Maybe your PC is not good enough. Try upgrading.

**Comment by potato25** [comment]
I didn't know that you can export by android app , thanks for help , I can export HTML file
