### ISSUE TITLE
Lua 5.4?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#949]
Wouldn't you mind upgrading from Lua 5.3 to Lua 5.4?

**Comment by nesbox** [comment]
the latest Lua release is 5.3.5

**Comment by nesbox** [comment]
Of course it will be updated when released :)

**Comment by asiekierka** [comment]
It's not so simple. Lua minor version releases introduce incompatibilities -> [here's a list of them between 5.3 and 5.4](https://www.lua.org/work/doc/manual.html#8). In addition, the TIC-80 build of Lua allows some 5.2 compatibility shims, which would also be dropped in 5.4.

I would recommend treating new versions of Lua (like 5.4) as separate scripting languages, setting them as defaults. In this case, I would alias "lua" to "lua53" (for compatibility purposes) and add "lua54" for Lua 5.4, using it as the new default when 5.4.0 comes out.

**Comment by nesbox** [comment]
omg, I didn't know about these incompatibilities, thank you for info @asiekierka
