### ISSUE TITLE
Cannot play sfx notes that have been generated with a sine function

### ISSUE THREAD

**Issue by borbware** [nesbox/TIC-80#950]
`sfx()` cannot play integer notes that have been generated with a sine function, like this:

```
note = (12+6*math.sin(note))//1
trace(note)
sfx(28, note, -1, 3, 4,1)
```
I suspect it has something to do with floats?

Even though note is an integer and in the wanted range, this produces the error message `invalid note, should be like C#4`

**Comment by StinkerB06** [comment]
You should use `math.floor()` instead of `//1`. The floor-division operator doesn't convert to integer.

The usage of a float instead of an integer as the note number in the `sfx()` call is broken. Only floats 0.0 to 9.0 work, but they have the same behavior as writing 0 or "C-1".

**Comment by nesbox** [comment]
so, we can close the issue.
thanks :)
