### ISSUE TITLE
Add some method of synchronizing actions to music

### ISSUE THREAD

**Issue by darkerbit** [nesbox/TIC-80#951]
I have been trying to create several rhythm games in TIC-80, and have found that the default `music` command is unsuitable for the task, being impossible to properly synchronize the game and music.
The music seems to have a tendency to run slightly faster or slightly slower with the default music player.

I have solved this problem by writing my own music player (three of them, infact), but I believe it would be best to provide this ability within TIC-80 itself.

My proposition would be extremely simple: two new commands.

```lua
-- load track without playing it, can also be used to jump to a different time in the same track
-- if called without parameters, simply restart the track
mload([track=-1], [frame=-1], [row=-1])

-- play and go forward one row in the music
mstep()
```

This way, timing could be managed inside the game's code, making it trivial to synchronize game events with the music.

`mload` could also feasibly be added as a parameter of the existing `music` command:
```lua
music(track, frame, row, loop, [play=true])
```

**Comment by LonelyLasagna** [comment]
I'm currently starting a rhythm game too and I've been using the `peek()`  function to get the state of the music engine directly. Take a look at  [the memory section](https://github.com/nesbox/TIC-80/wiki/RAM) of the wiki for more details.

**Comment by BraininaBowl** [comment]
I've done a dynamic music system in my [Silly Goblins](https://braininabowl.itch.io/silly-goblins) project, where I'd `peek()` at the current track and start another track at the exact same position. I think the same would be useable for a rhythm game.

My code:
```
musicbeat = peek(0x13FFC+2)+1
musicstate = gamestate
if musicstate == 0 then
	music(0,0,musicbeat)
elseif musicstate == 1 then
	music(2,0,musicbeat)
elseif musicstate == 2 then
	music(3,0,musicbeat)
end

```

**Comment by nesbox** [comment]
yes, you can `peek()/poke()` music state directly
