### ISSUE TITLE
PCM sound channel?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#953]
Do you think it is a good idea to add a PCM sound channel to the next version of TIC-80?

Obviously, it is technically possible to play PCM on the TIC-80. Set the frequency register of any of the four channels to `60`, and stream the PCM data into the 32-step waveform buffer each frame. This gives an effective sampling rate of 1.92 KHz. Absolutely awful, but it should work.

I'd love to find/have a way to get a higher sampling rate. Because of the limited amount of cartridge space you get, it would only be useful for tiny sound effects.

**Comment by nesbox** [comment]
The PCM channel is unlikely to be added, but I'm thinking of allowing some way to change the sound registers in the `SCN ()` callback.
