### ISSUE TITLE
Ubuntu package

### ISSUE THREAD

**Issue by superseeker13** [nesbox/TIC-80#954]
Is their any interest in turning this project into a Ubuntu package?

**Comment by RobLoach** [comment]
PPA? Flatpak? Snap?

**Comment by Anrock** [comment]
Apparently nobody have time for that (except author of #737), see
AppImage #811
Deb packages #737
Snap #253

**Comment by superseeker13** [comment]
Ok, I was considering helping to create and maintain a snap package.

**Comment by Anrock** [comment]
Ok, so closing as dupe of #253.
