### ISSUE TITLE
Why does TIC-80 build all the dependencies (sdl, curl, etc) from source??

### ISSUE THREAD

**Issue by chocabloc** [nesbox/TIC-80#960]

**Comment by nesbox** [comment]
yes, it builds all the 3rd-party libs from sources https://github.com/nesbox/3rd-party

**Comment by chocabloc** [comment]
Isn't it a waste of time? I mean, we could use the prebuilt binaries.

**Comment by nesbox** [comment]
We could, but there are a lot of problems, you have to keep these prebuilt libs somewhere for all the supported platforms (win, linux, mac, android, web, raspberrypi...), also, you have to keep them in the actual state. When in case building from sources you have to build them only one time on start and any further code changes don't cause a rebuild of them.
It's not a problem, I think.

**Comment by chocabloc** [comment]
Idk about all, but it could have an ability to use pre-built binaries if available for at least sdl2. Compiling it all may not always be possible.

**Comment by chocabloc** [comment]
Also, how much do we need to download for the first build

**Comment by chocabloc** [comment]
And I am not talking about keeping them in the repo. I am talking about using the dlls for sdl2 available at the website.

**Comment by nesbox** [comment]
Ok, got it, you can change SDL2 dependencies here https://github.com/nesbox/TIC-80/blob/b9e9a8a33a091257d9e46ded2ad2f362016033cd/CMakeLists.txt#L502

**Comment by chocabloc** [comment]
How do I go about doing that? I have just joined github yesterday, and I am a noob. Sorry

**Comment by nesbox** [comment]
You can fork the repo and make code changes you want and build, but I recommend you just download the latest dev build here https://builds.tic80.com

**Comment by chocabloc** [comment]
Well, thanks
