### ISSUE TITLE
Loading cartridges with active code banks broken

### ISSUE THREAD

**Issue by hstampfl** [nesbox/TIC-80#962]
Loading .lua or .tic with code banks does not load correct

**Comment by StinkerB06** [comment]
The code bank system in 0.70.6 PRO is pretty broken, so nesbox disabled it in 0.80.0-dev PRO.

**Comment by hstampfl** [comment]
ah, ok.... sadly. all my active tests have sorted the functions over the 8 banks to clean up my stuff :(

**Comment by BraininaBowl** [comment]
Same here. Will there be a new implementation in a later version? I heavily rely on banks to organise my code and to prevent the function filter from getting sluggish.

**Comment by nesbox** [comment]
I removed banks for the Code Editor, instead of this code saves and loads as zipped data to the cart (max 64K). Also to load deprecated code bank sections was added a workaround.
Fixed here 513a5fe.

**Comment by nesbox** [comment]
The changes were reverted, needs to be improved.

**Comment by nesbox** [comment]
Added workaround to load code from banks but with 64K limit bbf4c6e
