### ISSUE TITLE
The "upd" function to terminal

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#965]
The android version of tic has sad bug: if you try to search for a games on surf mode and if you doesnt seen game yet its cover image will try to load from tic.computer. But somehow it unable to load and tic crashes. Fortunately the image loads after restart, but do that thing everytime doesnt cool. So i just asking you to add a function that will instantly download all unloaded cover images of games. The example of using it:
--When tic loaded enter "update" or "upd" or "coverUpdate" to start update process.
--Tic will calculate the amount of cover images and will check if this image is on device. If its not he will set the image in the load schedule.
--After tic calculate all the cover images just start to download them. Let him every second send the message into terminal "loaded <number> of <number> cover images" where the first <number> is already loaded cover images and the second <number> is "to do".
Also add some arguments like "stop" "start" "select/<category>".
"upd select/WIP" will select WIP directory to load its covers.
"upd start" will start the loading
"upd stop" will stop the loading. All images that already loaded will stay on device.
Or simply fix the bug with tic crashing. That will be much easier, but the command thing will make something like retro-loading of games, but in fast type.

**Comment by RobLoach** [comment]
Downloading all cover images seems aggressive for not much benefit to very few users.

**Comment by nesbox** [comment]
Bug with the crash is fixed. Not sure we need `upd` command, sorry.
