### ISSUE TITLE
Keyboard bug

### ISSUE THREAD

**Issue by MasiuGames** [nesbox/TIC-80#970]
I'm opening tic80 and all is working nice. I'm opening script and i can write my script. But after few seconds, opens console, and F1 F2 F3 etc arrows and other keys aren't working. They're working only when i will click backspace or enter at the same time.

**Comment by wadetb** [comment]
I helped troubleshoot this and it was caused by a steering wheel plugged into the computer spamming the `escape` key.

The joypad code has any button after 4 being treated as `tic_key_escape`. 
I wonder if we should disable it since it can effectively break the UI?

**Comment by wadetb** [comment]
Wonder if TIC-80 should be using the SDL GameController API (https://wiki.libsdl.org/CategoryGameController) instead of the lower level Joystick API. 

The former provides mappings that are a lot closer to what TIC-80 expect, including an explicit "back" button.

**Comment by nesbox** [comment]
Ok, let's try using GameController API instead of Joystick API.

**Comment by nesbox** [comment]
Added using of SDL GameController API instead of the lower level Joystick API here d147d91b2ab6a4f635a035ec591365fadbfaf955
