### ISSUE TITLE
(0.80.0-dev) Add stereo panning registers to RAM layout?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#973]
There are functional stereo registers at `0x0FF98` to `0x0FF9B` in the RAM layout. Why doesn't this appear when you type the `ram` command?

**Comment by StinkerB06** [comment]
What should this be named? `STEREO REGISTERS`?

**Comment by nesbox** [comment]
already added `0x14000 STEREO VOLUME`
