### ISSUE TITLE
Replacement of circ() and circb() functions

### ISSUE THREAD

**Issue by potato25** [nesbox/TIC-80#979]
Replace circ() and circb() functions with elli( x,y,a,b,color ) and ellib( x,y,a,b,color ) ellipse functions where x , y are x , y co-ordinates of Center , a and b are Semi-major , Semi-minor axis and color is color of ellipse  .

**Comment by nesbox** [comment]
It won't be a replacement to not break backward compatibility, just new api functions.
Thanks.

**Comment by potato25** [comment]
ok , i see , older carts using circ() and circb() would be effected due to extra parameter

**Comment by ElNico56** [comment]
If elli() and ellib() are added maybe there should also be an angle parameter to rotate the ellipse around x,y

**Comment by potato25** [comment]
it's not needed , i don't see the use of it anymore i guess , maybe when first version was introduced , instead of circ and circb , it should have been ellipse and ellipse boundary functions

**Comment by nesbox** [comment]
Added `elli(x y a b color)`, `ellib(x y a b color)` API functions d8b6548
The algorithm for drawing an ellipse was taken from here http://members.chello.at/~easyfilter/bresenham.html

**Comment by nesbox** [comment]
Updated wiki
https://github.com/nesbox/TIC-80/wiki/elli
https://github.com/nesbox/TIC-80/wiki/ellib
