### ISSUE TITLE
Keyboard layout not recognized

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#980]
My GB keyboard layout isn't being correctly recognized. In a terminal used to launch Tic-80, the shift key works as expected for ",@ and ~ but these aren't recognized at Tic-80's command prompt or in the code editor (my #/~ key isn't recognized at all). Is there some setting I'm missing or is this a bug?

**Comment by nesbox** [comment]
What version, .70?
Seems a bug...

**Comment by paul59** [comment]
Sorry, completely forgot the necessary details! I compiled 0.8 dev and it's on Linux Mint 64 bit. My keyboard works as expected everywhere else so it looks like 0.8 is seeing it as a US version.

Just tried stable 0.70.6 and that works properly.

(not related but I can't start 0.8 from the file manager, I have to use the terminal. File manager sees it as a 'application/shared-xlib' for some reason)

**Comment by hj-jiaxing** [comment]
Using the build instructions in the readme file, TIC-80 doesn't recognize my it_IT keyboard layout, so i need to change the keyboard layout to en_US layout to write "="

**Comment by asexto** [comment]
Is this a duplicate of bug #747 ?

**Comment by hj-jiaxing** [comment]
> Is this a duplicate of bug #747 ?

i think so

**Comment by nesbox** [comment]
dup of #747
