### ISSUE TITLE
Scroll console output with 2 fingers (Android / 0.70.7pro)

### ISSUE THREAD

**Issue by phedoff** [nesbox/TIC-80#981]
Has this been removed, is it broken or was it changed? It doesn't work for me.
(Whenever I want to know an address in RAM, I  save, quit and use the wiki - save & quit because T80 crashes, if it loses focus, but that's a different issue.)
Apparently it once was available: https://github.com/nesbox/TIC-80/issues/120#issuecomment-303956490_

**Comment by nesbox** [comment]
Yes, It was removed, but we are adding special "hand" button to make it workable again in .80

**Comment by nesbox** [comment]
#245 dup
