### ISSUE TITLE
Crash 0.8.0-dev crash after save

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#982]
After saving a cart, TIC locked up ie unable to enter console commands use F1,F2 etc or close window. Linux Mint 19.3, 64bit
Here's the output from the terminal:

>save framework
cart framework.tic saved!

>X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Resource id in failed request:  0x6e000ee
  Serial number of failed request:  1295980
  Current serial number in output stream:  1295982

**Comment by paul59** [comment]
I haven't been able to reproduce this since. I've had a quick google around and wonder if was related to having suspended the PC while TIC was open.

**Comment by nesbox** [comment]
Can't reproduce.
