### ISSUE TITLE
Raspberry Pi Error

### ISSUE THREAD

**Issue by RaspberyPye** [nesbox/TIC-80#984]
I am trying to build from sources and have reached the 'make' command, however i encounter an error:
/usr/bin/ld: cannot find -lbcm_host
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/player-sdl.dir/build.make:93: bin/player-sdl] Error 1
make[1]: *** [CMakeFiles/Makefile2:200: CMakeFiles/player-sdl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I have found a similar error on this forum, but the solution was confusing. Here it is:
https://github.com/nesbox/TIC-80/issues/794
I don't understand the solution, where would i put that code? I tried placing it on line 4, but got this error:
/usr/bin/ld: lib/libSDL2.a(SDL_dynapi.c.o): undefined reference to symbol 'dlopen@@GLIBC_2.4'
/usr/bin/ld: //lib/arm-linux-gnueabihf/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/player-sdl.dir/build.make:93: bin/player-sdl] Error 1
make[1]: *** [CMakeFiles/Makefile2:200: CMakeFiles/player-sdl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I don't know what to do and i appreciate the help, 
Love what you're doing with TIC-80, i just wish i could access it!
Thanks!

**Comment by oschettler** [comment]
Hi RaspberyPye, I am trying the same (compiling on a RaspberryPi 4) and got the same error.
I have already installed the missing libraries in /opt/vc and pointed the linker to them, but the error persists. This is what I have tried:

````
sudo apt-get install --reinstall libraspberrypi0 libraspberrypi-dev libraspberrypi-doc libraspberrypi-bin

# There is a file /etc/ld.so.conf.d/00-vmcs.conf with the line "/opt/vc/lib"

sudo ldconfig -v # finds the library 
````
Still I get the error. The command that fails is 

````
/usr/bin/c++    -rdynamic CMakeFiles/player-sdl.dir/src/player/sdl.c.o  -o bin/player-sdl lib/libtic80core.a lib/libSDL2.a lib/libSDL2main.a lib/liblua.a lib/liblpeg.a lib/libwren.a lib/libsquirrel.a lib/libgiflib.a -lm -ldl /usr/lib/arm-linux-gnueabihf/libsndio.so -ldbus-1 -libus-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,--no-undefined -Wl,-rpath,/opt/vc/lib -lbcm_host -pthread 
````

This command is in file ``. I can run it with bash, even added `-Wl,--verbose` to see the linker output. It just doesn't find the library /opt/vc/lib/libbcm_host.so.  
So, I replaced `-lbcm_host.so` with `/opt/vc/lib/libbcm_host.so`. This works. But then the next compilation step fails.

How could I make `-lbcm_host` work?

**Comment by farvardin** [comment]
For building on raspberry pi (4), I had to install libglvnd-dev instead of libglu1-mesa-dev (as adviced by apt-get).
(I also had to install libasound2-dev but I just suppose it was missing from the readme)

Then I followed advice on https://github.com/nesbox/TIC-80/issues/794#issuecomment-452013327 and added as the 2nd line in CMakeLists.txt:
> link_directories(/opt/vc/lib)

and that's all. I've managed to compile tic80 and the linker no longer complained about lbcm_host (there is a bcm_host.h in /opt/vc/include/)

**Comment by nesbox** [comment]
Dup of #1017
