### ISSUE TITLE
key()/keyp() codes 66 to 78 don't work

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#987]
The keyboard buffer at `0x0FF88` to `0x0FF8B` in RAM can store the `Esc` key (66) and `F1` to `F12` keys (67 to 78). But the `key()` and `keyp()` API functions only go up to 65. Attempting to read above 65 produces the error message `unknown keyboard code`.

**Comment by nesbox** [comment]
Fixed here 810bf72
Thanks
