### ISSUE TITLE
Suggestion: Option to suppress boot messages in PRO version?

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#989]
It would be nice to be able to suppress the TIC boot/cartridge loading messages (in the PRO version). For game jams and stand-alone apps users may not know what a fantasy console is and might be confused or put off by these messages.

Is there also a way to suppress the button/key images that are overlaid when starting a game?

**Comment by StinkerB06** [comment]
The boot animation can be skipped with the `-skip` command line argument.

**Comment by paul59** [comment]
Ah, thanks for that.

**Comment by paul59** [comment]
Re-opened regarding second question about image overlays.

**Comment by dagondev** [comment]
Do you mean touch controls? If so then I am also interested. When I looked for this about 2-3 months ago only found that you can change alpha (in settings on tic-80) of those and make them invisible (but still there) which isn't great if you game relies on mouse. :(

**Comment by paul59** [comment]
> Do you mean touch controls? If so then I am also interested.
Yes, could do with an option to toggle them on/off.

**Comment by nesbox** [comment]
I think this is #810 duplicate

**Comment by paul59** [comment]
Not sure if it's the same issue, I'm only using writing programs for use on PC with a keyboard (ie without a gamepad) so I'd like to disable the images that show the four arrow buttons on the left and the 'ABXY' buttons on the right every time I run a cart. If that's the same issue, feel free to close this! :D

**Comment by paul59** [comment]
paul59>Is there also a way to suppress the button/key images that are overlaid when starting a game?

I've only just realized that these can be hidden by setting the alpha value in config:
`	GAMEPAD=
	{
		TOUCH=
		{
			ALPHA=255,
		},
	}`
An option to suppress all TIC's loading messages when running a native cart would be appreciated though.

**Comment by nesbox** [comment]
gamepad images were disabled here c85bd14
closing
