### ISSUE TITLE
Mouse() reports positions outside the screen

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#990]
Mouse() returns values in excess of 239 (x) and 135 (y) up to a maximum value of 255. When the cursor is to the left of the visible area if returns 255. Shouldn't this be reporting screen co-ords rathr than 'wrapped' window co-ords?

Version 0.80.0 dev on Linux 64 bit.

**Comment by paul59** [comment]
I'm guessing this unexpected behaviour is a related issue - move the mouse off the left-hand edge of the screen:

-- input: mouse
function TIC()  
    cls(1)
    local mx,my=mouse()
   rect(mx-32,my-32,64,64,15)
end

**Comment by nesbox** [comment]
#559 dup
