### ISSUE TITLE
Request: able to execute console commands from a program

### ISSUE THREAD

**Issue by kikeroga3** [nesbox/TIC-80#991]
::Request::
I want to be able to execute console commands from a program written in a code editor.
External files can be read using the import command while the program is running, making it easy to create a full-length adventure game.
Please consider.

**Comment by another-m00** [comment]
You can load external commands in lua and javascript by default. This comes with the language.
In lua its: `load(<code>)`
In javascript its `eval(<code>)`
Commands that require file access are disabled, so you cannot load from or write to external files, but you can compress data to any memory location (eg: the map part), so you actually can write a complete adventure, with the right compression.

_Sadly I don't know moon,squirrel, and wren, but im pretty sure its possible_

**Comment by kikeroga3** [comment]
Thanks for the answer about external commands.

I created the following in the style of storing line drawing data in memory.
https://tic80.com/play?cart=1280

It still seems that it's difficult to create an adventure game with many rich graphics without loading external files.

For example following.. (-;
https://apkpure.com/yugekitai/jp.blogspot.turnipworks.yugekitai

**Comment by RobLoach** [comment]
I'm unclear on what you're trying to accomplish. Are you looking to use your own editor? What is the problem you're trying to solve?

I've put together a compilation process for some of the projects I had. [Dangerous Dave](https://github.com/RobLoach/DangerousDave-TIC80), for instance, used a Node.js script to combine all the files together.

**Comment by kikeroga3** [comment]
Sorry my reply wasn't clear to you.
And thanks for your reply.
I will take a look at your sources. I'm sure it will be helpful.

Thank you for everything.

**Comment by nesbox** [comment]
@kikeroga3 unfortunately, a script won't have access to the console commands, sorry
