### ISSUE TITLE
Use PNG for screenshots instead of GIF?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#992]
I think it would be better to use PNG for screenshots rather than GIF. This has two advantages:
1. To allow screens with more than 256 on-screen colors to be preserved. The maximum amount of colors that can be shown is `(16×136)+16 = 2192` (using `TIC`/`SCN`/`OVR` together).
2. For tweeting multiple screenshots at once on Twitter. You can only tweet one GIF at a time, so I would have to spend a tedious amount of time converting my screenshots to PNG.

You can still keep GIF with cover images (F7) and animated videos (F9).

**Comment by nesbox** [comment]
We have to add `libpng` as a dependency that will increase the size of the .exe and increase the compile-time, not sure if it's worth it.

**Comment by sknebel** [comment]
@nesbox given TIC-80 now already uses PNG (and thus links needed libraries) for carts, would you accept a PR to add PNG screenshots as an option if someone worked on it?

**Comment by nesbox** [comment]
sorry, my mistake, I misunderstood the problem 🤦 
yes, we can use PNG support to save a screenshot and will accept the PR
sorry for my inattention
