### ISSUE TITLE
Crash while surfing

### ISSUE THREAD

**Issue by avevad** [nesbox/TIC-80#994]
I've loaded latest version of TIC from releases page on github, unpacked it and started. Then, I've entered `surf` command, navigated to `[tic.computer/play]` folder, then navigated to `[Games]` folder, opened it, and TIC-80 crashed.

stdout:
```
 TIC-80 tiny computer 0.70.6
 http://tic.computer (C) 2017

 hello! type help for help

>surf
>double free or corruption (!prev)
fish: './tic80' terminated by signal SIGABRT (Abort)
```

**Comment by nesbox** [comment]
it's strange, could you please check latest build https://builds.tic80.com/master/2020.01.19

**Comment by Avevad** [comment]
`[tic80.com/play]` folder is empty

**Comment by Avevad** [comment]
okay, i found out that the tic80.com site doesn't open in my browser (ERR_CONNECTION_RESET)

**Comment by Avevad** [comment]
have just tried to open it with VPN and it works

**Comment by Avevad** [comment]
idk how to enable proxy for tic80

**Comment by nesbox** [comment]
hmm, from what country are you trying to open tic80.com?

**Comment by Avevad** [comment]
I'm from Russia

**Comment by Avevad** [comment]
There's no reason for blocking the site by my provider, alright?

**Comment by Avevad** [comment]
But it seems to be blocked, ERR_CONNECTION_RESET error appears often in that case

**Comment by Anrock** [comment]
Yup, can confirm it's blocked for me too. RKN is known to ban random sites without any reason.

**Comment by Avevad** [comment]
What's the reason of changing `TIC_HOST` to `tic80.com`? I've tried to change it back to `tic.computer` and now I can surf. Also, after testing it, I found out that the bug which is the subject of the issue is irreproducible in build from src (master branch with `#define TIC_HOST "tic80.com"` changed to `#define TIC_HOST "tic.computer"`).

**Comment by nesbox** [comment]
Because tic80.com is going to be a new domain name in next version and tic.computer will redirect to it.

**Comment by phorust** [comment]
I'm also having this problem and it's easy to reproduce, I just scroll around on the menu. Usually I crash by the time I get to the "Mario Bros?" cart.

**Comment by nesbox** [comment]
@phorust could you pls check the crash on the latest build https://builds.tic80.com/master/2020.01.19

**Comment by phorust** [comment]
Sorry, I pressed cmd+enter for a newline and entered my comment early on accident. 

> It's fixed by downloading 2020.01.25's nightly, but then I don't have the pro features anymore

**Comment by nesbox** [comment]
yes, we upload only non pro version to the build server

**Comment by phorust** [comment]
ok, I built myself a pro version of the latest build 2020.01.25 and 2020.01.19, and they both crash, so I'm guessing the crashes I'm getting is a pro version only thing.  

I think it may have to do with the following lines
https://github.com/nesbox/TIC-80/blob/de2dacdb33eb41cfe88923d131f52e93adab7df7/src/surf.c#L389-L390
there's one other `TIC80_PRO` check / `hasProjectExt` call in that file.

here's the dump I'm getting with the crash: https://gist.github.com/phorust/261bc6618de9f97f21b38d27164a2623

I'd love to help debug this but I don't know where to start; not sure how to use cgdb or Xcode with this.

**Comment by Avevad** [comment]
> I'm guessing the crashes I'm getting is a pro version only thing.

I don't thik so. I had crashes appeared on non-pro version

**Comment by sssilver** [comment]
Running on the latest macOS Catalina, having the same issue on both my laptop and my daughter's laptop. In the surfer, when navigating to the TIC80 Collection, and then going into Games, after going down the list enough times the TIC-80 process crashes.

**Comment by nesbox** [comment]
Fixed with the latest release.
