### ISSUE TITLE
Array of color keys in map/font/textri?

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#996]
The `spr()` function's `colorkey` parameter can accept a table array of numbers (instead of just a single number), so that we can specify multiple simultaneous transparent color indexes in the same sprite. However, such functionality doesn't exist with the other three functions as mentioned in the title.

**Comment by RobLoach** [comment]
The chroma key is used to determine how to blit the image. Having multiple choma keys could have a pretty poor effect on performance.

Is there another way you could accomplish this?
