### ISSUE TITLE
Audio delay on macOS 0.70.6 Pro

### ISSUE THREAD

**Issue by mngyuan** [nesbox/TIC-80#997]
There's an audible delay in audio, maybe 100ms. I can hear it in SURF when I'm moving between carts and in the SFX editor and in my cart as well. I'm getting `parameter or file not processed -psn_0_581774` sometimes on start, is this related?

Not having this issue in `2020.01.25`'s nightly.

**Comment by nesbox** [comment]
Duplicate of #714
