### ISSUE TITLE
"Fading" mouse pointer in libretro (or in general)

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#998]
Hi there, a small suggestion for the libretro core (which i'm often using for playing tic80 games lately).

It would be nice to have a "disappearing" mouse. Like an option that says: after x seconds of not moving, the mouse would disappear.

This would work for mouse based games (as the mouse is almost always moving) and for gamepad based games (as the mouse will soon disappear).

It would avoid going back to the option and change the mouse settings when you switch between game types.

(eventually the same thing could be implemented in regular tic80 but it's less of a problem there so probably not worth).

I had it implemented [here](https://github.com/nesbox/TIC-80/blob/master/src/system/baremetalpi/kernel.cpp) but it's a simple counter..

tagging @RobLoach for attention :)

**Comment by RobLoach** [comment]
That's a great idea. What would you think is a good amount of time to wait for it to disappear? 5 seconds?

**Comment by msx80** [comment]
I used a counter at 600, which is 10 seconds. Anything between 5 and 10 should be good i think. (perhaps make it optional since you're probably making an option already?)

Also, it's just a detail but i found it better to start the program with the mouse already "disappeared" (had the counter start at 600), obviously feel free to implement the other way.
