### ISSUE TITLE
(0.80-dev suggestion) Allow array of volumes in sfx() for left/right

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#999]
We can set the left/right volumes of notes in the music tracker with your new `Mxy` command, but I'd also want the ability to set the left/right volumes of SFX as well. Maybe make the volume argument of `sfx()` allow a table or array with left and right volume specifications, while allowing a number to be used instead of a table for backward compatibility.

**Comment by nesbox** [comment]
Fixed here 63ef300.
Thanks.

**Comment by nesbox** [comment]
Reminder for me: update wiki after 0.90 release
